profiles-anki-could-not-read-your-profile = Anki nije mogao pročitati vaše podatke profila. Veličine prozora i detalji za prijavu na sinkronizaciju su zaboravljeni.
profiles-anki-could-not-rename-your-profile = Anki nije mogao preimenovati vaš profil jer nije mogao preimenovati mapu na disku. Osigurajte da imate dopuštenja pisati u Documents/Anki i da nijedan drugi program ne pristupa vašoj mapi profila, zatim pokušajte ponovno.
profiles-folder-already-exists = Mapa već postoji.
profiles-open = Otvori
profiles-open-backup = Otvori sigurnosnu kopiju...
profiles-please-remove-the-folder-and = Uklonite mapu { $val } te pokušajte ponovno.
profiles-profile-corrupt = Profil neispravan
profiles-profiles = Profili
profiles-quit = Izlaz
profiles-user-1 = Korisnik 1
profiles-confirm-lang-choice = Jeste li sigurni da želite prikazati Ankijevo sučelje na jeziku: { $lang }?
profiles-could-not-create-data-folder = Anki nije mogao stvoriti svoju mapu za podatke. Pogledajte odjeljak priručnika "File Locations" te osigurajte da ta lokacija nije samo za čitanje.
profiles-prefs-corrupt-title = Postavke neispravne
profiles-prefs-file-is-corrupt = Ankijeva datoteka pref21.db bila je neispravna i ponovno je stvorena. Ako ste koristili više profila, ponovno ih dodajte pod istim nazivom kako biste povratili svoje kartice.
profiles-profile-does-not-exist = Traženi profil ne postoji.
profiles-creating-backup = Stvaranje sigurnosne kopije...
profiles-backup-created = Sigurnosna kopija stvorena.
profiles-backup-creation-failed = Stvaranje sigurnosne kopije nije uspjelo: { $reason }
profiles-backup-unchanged = Nema promjena od zadnjeg sigurnosnog kopiranja.
