notetypes-front-field = Sdat
notetypes-back-field = Uɣal
notetypes-add-reverse-field = Rnu idis n deffir
notetypes-text-field = Aḍris
notetypes-basic-name = Azadur
notetypes-card-2-name = Takarḍa 2
notetypes-card-1-name = Takarḍa 1
notetypes-add = Rnu: { $val }
notetypes-add-note-type = Rnu anaw n tezmilt
notetypes-cards = Tikaṛḍiwin...
notetypes-copy = { $val } unɣel
notetypes-fields = Urtan...
notetypes-footer = Aḍar
notetypes-header = Aqeṛṛu
notetypes-options = Iγewwaren...
notetypes-type = Tawsit
