card-stats-added = Apondut
card-stats-first-review = Primièra revision
card-stats-review-count = Revisions
card-stats-average-time = Durada mejana
card-stats-total-time = Durada totala
card-stats-card-template = Tipe de carta
card-stats-deck-name = Paquet
card-stats-card-id = Identificant carta
card-stats-review-log-date = Data
card-stats-review-log-type-review = Contrarotlar
card-stats-review-log-type-filtered = Filtrat
