notetypes-back-field = Verso
notetypes-add-reverse-field = Apondre lo verso
notetypes-basic-name = Elementari
notetypes-basic-reversed-name = Generalitats (dos senses)
notetypes-basic-optional-reversed-name = Generalitats (convèrsa facultativa)
notetypes-cloze-name = Tèxte amb traucs
notetypes-card-2-name = Carta 2
notetypes-card-1-name = Carta 1
notetypes-add = Apondre : { $val }
notetypes-add-note-type = Apondre un tipe de nòta
notetypes-cards = Cartas…
notetypes-clone = Duplicar : { $val }
notetypes-copy = Còpia de { $val }
notetypes-fields = Camps...
notetypes-footer = Pè de pagina
