preferences-automatically-sync-on-profile-openclose = Sincronizar automaticament a la dobertura e a la tampadura.
preferences-backups = Salvaments
preferences-backupsanki-will-create-a-backup-of = <b>Salvaments</b><br>Anki va crear un salvament de vòstra colleccion a cada còp qu’es tampada o sincronizada.
preferences-basic = Elementari
preferences-keep = Gardar
preferences-network = Ret
preferences-preferences = Preferéncias
preferences-synchronisation = <b>Sincronizacion</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Sincronizacion</b><br> Desactivada pel moment ; per l’activar clicatz sul boton de sincronizacion dins la fenèstra principala.
