card-stats-added = قوشۇلدى
card-stats-first-review = تۇنجى تەكرار
card-stats-latest-review = ئاخىرقى تەكرار
card-stats-interval = مەزگىل
card-stats-ease = ئاسانلىقى
card-stats-review-count = تەكرارلىقى
card-stats-lapse-count = ئۇنتۇلۇشى
card-stats-average-time = ئوتتۇرىچە ۋاقىت
card-stats-total-time = جەمئى ۋاقىت
card-stats-new-card-position = ئورنى
card-stats-card-template = كارتا تۈرى
card-stats-note-type = خاتىرە تۈرى
card-stats-deck-name = دەستە
card-stats-preset = ئالدىن سەپلەش
card-stats-note-id = خاتىرە كىملىكى
card-stats-card-id = كارتا كىملىكى
card-stats-review-log-rating = باھالاش
card-stats-review-log-type = تۈرى
card-stats-review-log-date = چېسلا
card-stats-review-log-time-taken = ۋاقىت
card-stats-review-log-type-learn = ئۆگىنىش
card-stats-review-log-type-review = تەكرار
card-stats-review-log-type-relearn = قايتا ئۆگىنىش
card-stats-review-log-type-filtered = سۈزۈلگەن
card-stats-review-log-type-manual = قولدا
card-stats-review-log-type-rescheduled = قايتا كۈنتەرتىپلەندى
card-stats-review-log-elapsed-time = ئۆتكەن ۋاقىت
card-stats-no-card = (كۆرسىتىدىغان كارتا يوق)
card-stats-custom-data = ئىختىيارى سانلىق مەلۇمات
card-stats-fsrs-stability = ئەستە ساقلىنىشچانلىقى
card-stats-fsrs-difficulty = قىيىنلىقى
card-stats-fsrs-retrievability = ئەستە تۇرۇشچانلىقى
card-stats-fsrs-forgetting-curve-title = ئۇنتۇش ئەگرى سىزىقى
card-stats-fsrs-forgetting-curve-first-week = تۇنجى ھەپتە
card-stats-fsrs-forgetting-curve-first-month = تۇنجى ئاي
card-stats-fsrs-forgetting-curve-first-year = تۇنجى يىل
card-stats-fsrs-forgetting-curve-all-time = ھەممە ۋاقىت
card-stats-fsrs-forgetting-curve-probability-of-recalling = ئەسلەش ئېھتىماللىقى
card-stats-fsrs-forgetting-curve-desired-retention = ئارزۇدىكى ئەستە ساقلاش نىسبىتى

## Window Titles

card-stats-current-card = نۆۋەتتىكى كارتا ({ $context })
card-stats-previous-card = ئالدىنقى كارتا ({ $context })
