decks-add-new-deck-ctrlandn = يېڭى دەستە قوش(Ctrl+N)
decks-build = قۇر
decks-cards-selected-by = كارتا تاللاش ئۇسۇلى
decks-create-deck = دەستە قۇر
decks_create_even_if_empty = ئەگەر بوش بولغان تەقدىردىمۇ بۇ دەستەنى قۇرىدۇ/يېڭىلايدۇ
decks-custom-steps-in-minutes = ئىختىيارى ئۆگىنىش باسقۇچى (مىنۇت)
decks-deck = دەستە
decks-decreasing-intervals = كېمەيگۈچى مەزگىل
decks-delete-deck = دەستە ئۆچۈر
decks-enable-second-filter = ئىككىنچى سۈزگۈچنى قوزغات
decks-filter = سۈزگۈچ:
decks-filter-2 = 2-سۈزگۈچ
decks-get-shared = ھەمبەھىر دەستىگە ئېرىشىش
decks-import-file = ھۆججەت ئەكىر
decks-increasing-intervals = ئۆسكۈچى مەزگىل
decks-latest-added-first = ئاخىرىدا قوشۇلغىنى ئالدىدا
decks-limit-to = چېكى
decks-minutes = مىنۇت
decks-most-lapses = كۆپ ئۇنتۇلىدىغان
decks-new-deck-name = يېڭى دەستە ئاتى:
decks-no-deck = [دەستە يوق]
decks-oldest-seen-first = باشقا كۆرگىنى ئالدىدا
decks-order-added = قوشۇلغان تەرتىپتە
decks-order-due = مۆھلەت تەرتىپىدە
decks-please-select-something = دەستە تاللاڭ.
decks-random = خالىغانچە
decks-relative-overdueness = نىسپىي ۋاقىت ھالقىشچانلىقى بويىچە
decks-repeat-failed-cards-after = كارتا تەكرارلانمىغاندىن كېيىنكى كېچىكىش ۋاقتى
# e.g. "Delay for Again", "Delay for Hard", "Delay for Good"
decks-delay-for-button = { $button } كېچىكىش
decks-reschedule-cards-based-on-my-answers = بۇ دەستىدىكى جاۋاب بېرىش ئەھۋالىمغا ئاساسەن كارتىنى قايتىدىن كۈنتەرتىپكە تىزىدۇ.
decks-study = ئۆگىنىش
decks-study-deck = دەستە ئۆگىنىش
decks-filtered-deck-search-empty = تەمىنلىگەن ئىزدەش شەرتىگە ھېچقانداق كارتا ماس كەلمىدى. بەزى كارتا مۇستەسنا چۈنكى باشقا سۈزۈلگەن دەستىگە قويۇلغان ياكى يوشۇرۇلغان.
decks-unmovable-cards = بارلىق مۇستەسنا كارتىنى كۆرسەت
decks-learn-header = ئۆگىنىش
# The count of cards waiting to be reviewed
decks-review-header = مۆھلەت
decks-zero-minutes-hint = (0 = كارتىنى ئەسلى دەستەگە قايتۇرىدۇ)
