editing-actual-size = ئەمەلىي چوڭلۇقتە كۆرسىتىشنى ئاچ/ياپ
editing-add-media = ۋاسىتە قوش
editing-align-left = سولغا توغرىلا
editing-align-right = ئوڭغا توغرىلا
editing-an-error-occurred-while-opening = { $val } نى ئېچىۋاتقاندا خاتالىق كۆرۈلدى
editing-attach-picturesaudiovideo = رەسىم/ئۈن/سىن يۈكلە
editing-bold-text = توم تېكىست
editing-cards = كارتا
editing-center = ئوتتۇرا
editing-change-color = رەڭ ئۆزگەرت
editing-cloze-deletion = بوش ئورۇن تولدۇرۇش (يېڭى كارتا)
editing-cloze-deletion-repeat = بوش ئورۇن تولدۇرۇش (ئوخشاش كارتا)
editing-copy-image = سۈرەت كۆچۈر
editing-couldnt-record-audio-have-you-installed = ئۈن خاتىرىيەلمىدى. «lame» ئورنىتىلغانمۇ يوق تەكشۈرۈڭ؟
editing-customize-card-templates = كارتا قېلىپىنى خاسلاشتۇر
editing-customize-fields = ئىختىيارى بۆلەك
editing-cut = كەس
editing-double-click-image = سۈرەتنى قوش چەك
editing-double-click-to-expand = قوش چېكىلسە يايىدۇ
editing-double-click-to-collapse = قوش چېكىلسە يىغىدۇ
editing-edit-current = نۆۋەتتىكىنى تەھرىرلە
editing-edit-html = HTML تەھرىر
editing-fields = بۆلەك
editing-float-left = سولغا لەيلەت
editing-float-right = ئوڭغا لەيلەت
editing-float-none = لەيلەتمە
editing-indent = تارايتىشنى ئاشۇر
editing-italic-text = يانتۇ تېكىست
editing-jump-to-tags-with-ctrlandshiftandt = بەلگىگە ئاتلا Ctrl+Shift+T
editing-justify = ئوڭ سولغا توغرىلا
editing-latex = LaTeX
editing-latex-equation = LaTeX تەڭلىمىسى
editing-latex-math-env = LaTeX ماتېماتىكا مۇھىتى
editing-mathjax-block = MathJax بۆلەك
editing-mathjax-chemistry = MathJax خىمىيە
editing-mathjax-inline = MathJax قۇر ئىچى تەڭلىمە
editing-mathjax-placeholder = { $accept } بېسىلسا قوشۇلىدۇ، { $newline } يېڭى قۇر.
editing-media = ۋاسىتە
editing-open-image = سۈرەت ئاچ
editing-show-in-folder = قىسقۇچتا كۆرسەت
editing-ordered-list = تەرتىپلەنگەن تىزىم
editing-outdent = تارايتىشنى كېمەيت
editing-paste = چاپلا
editing-record-audio = ئۈن خاتىرىلە
editing-remove-formatting = پىچىمنى چىقىرىۋەت
editing-restore-original-size = ئەسلى چوڭلۇققا ئەسلىگە قايتۇر
editing-select-remove-formatting = چىقىرىۋېتىدىغان پىچىمنى تاللا
editing-show-duplicates = تەكرارلانغاننى كۆرسەت
editing-subscript = ئاستى ئىندېكىس
editing-superscript = ئۈستى ئىندېكىس
editing-tags = بەلگە
editing-tags-add = بەلگە قوش
editing-tags-copy = بەلگە كۆچۈر
editing-tags-remove = بەلگىنى چىقىرىۋەت
editing-tags-select-all = ھەممە بەلگىنى تاللا
editing-text-color = تېكىست رەڭگى
editing-text-highlight-color = تېكىست يورۇتۇش رەڭگى
editing-to-make-a-cloze-deletion-on = مەۋجۇت خاتىرىگە بوش ئورۇن تولدۇرۇش قۇرۇشتا، ئاۋۋال «خاتىرە › خاتىرە تۈرىنى ئۆزگەرت» نى تاللاپ بوش ئورۇن تولدۇرۇش خاتىرە قېلىپىغا ئۆزگەرتىڭ.
editing-toggle-html-editor = HTML تەھرىرلىگۈچنى ئاچ/ياپ
editing-toggle-visual-editor = كۆرۈنۈشچان تەھرىرلىگۈچنى ئاچ/ياپ
editing-toggle-sticky = يېپىشقاقلىقنى ئاچ/ياپ
editing-expand = ياي
editing-collapse = يىغ
editing-expand-field = بۆلەكنى ياي
editing-collapse-field = بۆلەكنى يىغ
editing-underline-text = تېكىست ئاستى سىزىق
editing-unordered-list = تەرتىپسىز تىزىم
editing-warning-cloze-deletions-will-not-work = ئاگاھلاندۇرۇش، خاتىرە قېلىپىنى بوش ئورۇننى تولدۇرۇش قېلىپىغا ئۆزگەرتىشتىن ئىلگىرى، تەڭشىگەن بوش ئورۇننى تولدۇرۇشىڭىز ئىشلىمەيدۇ.
editing-mathjax-preview = MathJax ئالدىن كۆزەت
editing-shrink-images = سۈرەتنى كىچىكلەت
editing-close-html-tags = HTML بەلگىنى ئۆزلۈكىدىن ياپ
editing-from-clipboard = چاپلاش تاختىسىدىن
editing-alignment = توغرىلاش
editing-equations = تەڭلىمە
editing-no-image-found-on-clipboard = چاپلاش تاختىسىدا سۈرەت بايقالمىدى.
editing-image-occlusion-mode = سۈرەت دالدىلاش ھالىتى
editing-image-occlusion-zoom-out = يىراقلات
editing-image-occlusion-zoom-in = يېقىنلات
editing-image-occlusion-zoom-reset = يېقىن يىراقنى ئەسلىگە قايتۇر
editing-image-occlusion-toggle-translucent = يېرىم سۈزۈكنى ئاچ/ياپ
editing-image-occlusion-delete = ئۆچۈر
editing-image-occlusion-duplicate = تەكرار
editing-image-occlusion-group = گۇرۇپپا تاللاش
editing-image-occlusion-ungroup = تاللىغاننى گۇرۇپپىلىما
editing-image-occlusion-select-all = ھەممىنى تاللا
editing-image-occlusion-alignment = توغرىلاش
editing-image-occlusion-align-left = سولغا توغرىلا
editing-image-occlusion-align-h-center = توغرىسىغا ئوتتۇرىغا توغرىلا
editing-image-occlusion-align-right = ئوڭغا توغرىلا
editing-image-occlusion-align-top = چوققىغا توغرىلا
editing-image-occlusion-align-v-center = بويىغا ئوتتۇرىغا توغرىلا
editing-image-occlusion-align-bottom = ئاستىغا توغرىلا
editing-image-occlusion-select-tool = تاللا
editing-image-occlusion-zoom-tool = يېقىن يىراق
editing-image-occlusion-rectangle-tool = چاسا
editing-image-occlusion-ellipse-tool = ئېللىپىس
editing-image-occlusion-polygon-tool = كۆپ تەرەپلىك
editing-image-occlusion-text-tool = تېكىست
editing-image-occlusion-fill-tool = رەڭ تولدۇرىدۇ
editing-image-occlusion-toggle-mask-editor = نىقاب تەھرىرلىگۈچنى ئاچ/ياپ
editing-image-occlusion-reset = سۈرەت دالدىلاشنى ئەسلىگە قايتۇر
editing-image-occlusion-confirm-reset = بۇ سۈرەت دالدىلاشنى راستتىنلا ئەسلىگە قايتۇرامسىز؟

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML تەھرىرلىگۈچ
