profiles-anki-could-not-read-your-profile = Anki تەرجىمىھال سانلىق مەلۇماتىڭىزنى ئوقۇيالمىدى. كۆزنەك چوڭلۇقى، تىزىمغا كىرىش تەپسىلاتىڭىز ئۇنتۇلىدۇ.
profiles-anki-could-not-rename-your-profile = Anki تەرجىمىھالىڭىزنىڭ ئاتىنى ئۆزگەرتەلمەيدۇ چۈنكى ئۇ دىسكىدىكى تەرجىمىھال قىسقۇچ ئاتىنى ئۆزگەرتەلمەيدۇ. Documents/Anki غا يېزىش ئىجازىتىڭىز بارلىقىغا كاپالەتلىك قىلىڭ، ھەمدە باشقا پىروگرامما تەرجىمىھال قىسقۇچنى زىيارەت قىلىۋاتقان بولسا، سەل تۇرۇپ قايتا سىناڭ.
profiles-folder-already-exists = قىسقۇچ مەۋجۇت.
profiles-open = ئاچ
profiles-open-backup = زاپاسنى ئاچ…
profiles-please-remove-the-folder-and = قىسقۇچ { $val } نى چىقىرىۋېتىپ ئاندىن قايتا سىناڭ.
profiles-profile-corrupt = تەرجىمىھال بۇزۇلغان
profiles-profiles = تەرجىمىھال
profiles-quit = چېكىن
profiles-user-1 = 1-ئىشلەتكۈچى
profiles-confirm-lang-choice = Anki نىڭ ئارايۈزىنى { $lang } كۆرسىتەمسىز؟
profiles-could-not-create-data-folder = Anki سانلىق مەلۇمات ساقلايدىغان قىسقۇچنى قۇرالمىدى. قوللانمىدىكىك ھۆججەت ئورنى (File Locations) بۆلىكىنى كۆرۈڭ، ھۆججەت ئورنىنىڭ ئوقۇشقىلا بولىدىغان ئەمەسلىكىگە كاپالەتلىك قىلىڭ.
profiles-prefs-corrupt-title = مايىللىق بۇزۇلغان
profiles-prefs-file-is-corrupt = Anki نىڭ prefs21.db ھۆججىتى بۇزۇلغان ھەمدە قايتىدىن قۇرۇلغان. ئەگەر كۆپ تەرجىمىھال ئىشلەتكەن بولسىڭىز، ئوخشاش ئاتتىكى تەرجىمىھال ئىشلەتسىڭىز كارتىلىرىڭىزنى ئەسلىگە كەلتۈرگىلى بولىدۇ.
profiles-profile-does-not-exist = ئىلتىماس قىلغان تەرجىمىھال مەۋجۇت ئەمەس.
profiles-creating-backup = زاپاس قۇرۇۋاتىدۇ…
profiles-backup-created = زاپاس قۇرۇلدى.
profiles-backup-creation-failed = زاپاس قۇرالمىدى: { $reason }
profiles-backup-unchanged = ئاخىرقى زاپاستىن كېيىن ئۆزگىرىش يوق.
