actions-add = Додај
actions-cancel = Откажи
actions-choose = Изабери
actions-close = Затвори
actions-copy = Копирај
actions-custom-study = Додатно учење
actions-decks = Шпилови
actions-delete = Избриши
actions-export = Извоз карте у други формат
actions-filter = Филтер
actions-help = Помоћ
actions-import = Увоз
actions-name = Назив:
actions-new = Ново
actions-new-name = Нови назив:
actions-options = Опције
actions-options-for = Опције за { $val }
actions-preview = Преглед
actions-rebuild = Поново изгради
actions-rename = Преименуј
actions-rename-deck = Преименуј шпил
actions-replay-audio = Поново репродукуј звук
actions-reposition = Премести
actions-save = Сачувај
actions-search = Тражи
actions-shortcut-key = На тастатури: { $val }
actions-suspend-card = Суспендуј карту
actions-processing = Обрада...
