card-stats-added = Додато
card-stats-first-review = Виђена први пут
card-stats-latest-review = Последњи преглед
card-stats-interval = Интервал
card-stats-ease = Лакоћа
card-stats-review-count = Понављања
card-stats-lapse-count = Промашаји
card-stats-average-time = Просечно време
card-stats-total-time = Укупно време
card-stats-new-card-position = Позиција
card-stats-card-template = Тип карата
card-stats-note-type = Тип белешке
card-stats-deck-name = Шпил
card-stats-note-id = ID белешке
card-stats-card-id = ID карте
card-stats-review-log-rating = Оцена
card-stats-review-log-type = Тип
card-stats-review-log-date = Datum
card-stats-review-log-time-taken = време
card-stats-review-log-type-learn = Учење
card-stats-review-log-type-review = Понављање
card-stats-review-log-type-relearn = Поновно учење
card-stats-review-log-type-filtered = Филтрирано
card-stats-review-log-type-rescheduled = Прерасподели
