custom-study-cards = карте
custom-study-cards-from-the-deck = карте из шпила
custom-study-choose-tags = Изабери ознаке
custom-study-custom-study-session = Сесија додатног учења
custom-study-due-cards-only = Рок само за карте
custom-study-increase-todays-new-card-limit = Увећај данашњи лимит за нове карте
custom-study-increase-todays-new-card-limit-by = Увећај данашњи лимит за нове карте на
custom-study-increase-todays-review-card-limit = Увећај данашњи лимит за понављања
custom-study-increase-todays-review-limit-by = Увећај данашњи лимит за понављања на
custom-study-new-cards-only = Само нове карте
custom-study-no-cards-matched-the-criteria-you = Нема карата које одговарају задатим критеријумима.
custom-study-ok = Потврди
custom-study-preview-new-cards = Преглед нових карата
custom-study-preview-new-cards-added-in-the = Преглед нових карата, које су додате последње
custom-study-require-one-or-more-of-these = Потребна је једна или  неколико ових ознака:
custom-study-review-ahead = Преглед спреда
custom-study-review-ahead-by = Преглед спреда за
custom-study-review-cards-forgotten-in-last = Понављање последње заборављене карте
custom-study-review-forgotten-cards = Понављање заборављених карата
custom-study-select = Изабери
custom-study-select-tags-to-exclude = Изабери искључујуће ознаке:
custom-study-selective-study = Селективно учење
custom-study-study-by-card-state-or-tag = Преглед стања карте или ознаке
