editing-add-media = Додај медија датотеку
editing-an-error-occurred-while-opening = Грешка при отварању { $val }
editing-bold-text-ctrlandb = Подебљано (Ctrl+B)
editing-cards = Карте
editing-cut = Исеци
editing-edit-current = Уређивање параметара
editing-edit-html = Уређивање HTML
editing-fields = Поља
editing-html-editor = HTML уређивач
editing-jump-to-tags-with-ctrlandshiftandt = Пређи на ознаке са Ctrl+Shift+T
editing-latex = LaTeX
editing-latex-equation = LaTeX формула
editing-latex-math-env = Искључена формула LaTeX
editing-media = Носач
editing-paste = Налепи
editing-set-foreground-colour-f7 = Задај бојy текста (F7)
editing-show-duplicates = Прикажи дупликате
editing-subscript-ctrland = Индекс (Ctrl+=)
editing-superscript-ctrlandand = Експонент (Ctrl++)
editing-tags = Ознаке
editing-to-make-a-cloze-deletion-on = Да бисте додали попуњавање пропуста у постојећој белешци, потребно је да јој прво измените тип у "пропуст" (cloze), преко Уреди>Измени тип белешке
editing-warning-cloze-deletions-will-not-work = Упозорење, пропуштање неће радити док не укључите тип на врху за пропуштање (Cloze).
