qt-misc-all-cards-notes-and-media-for = Alle kort, noter og medier for denne profil vil blive slettet. Er du sikker?
qt-misc-anki-updatedanki-has-been-released = <h1>Anki er opdateret</h1>Anki { $val } er blevet udgivet.<br><br>
qt-misc-browse = Gennemse
qt-misc-change-note-type-ctrlandn = Skift notetype (Ctrl+N)
qt-misc-check-the-files-in-the-media = Tjek filerne i mediekataloget
qt-misc-choose-deck = Vælg kortsæt
qt-misc-choose-note-type = Vælg notetype
qt-misc-configure-interface-language-and-options = Konfigurér grænsefladesprog og indstillinger
qt-misc-create-filtered-deck = Opret filtreret kortsæt ...
qt-misc-debug-console = Konsol til fejlsøgning
qt-misc-deck-will-be-imported-when-a = Kortsæt bliver importeret når en profil åbnes.
qt-misc-default = Standard
qt-misc-empty-cards = Tomme kort ...
qt-misc-error-during-startup = Fejl under opstart: { $val }
qt-misc-filtered-deck = Filtreret kortsæt { $val }
qt-misc-ignore-this-update = Se bort fra denne opdatering
qt-misc-in-order-to-ensure-your-collection = For at sikre at din samling fungerer korrekt når der flyttes mellem enheder, så kræver Anki at dine computeres interne ure er indstillet korrekt. Det interne ur kan gå forkert, selv om dit system viser den lokale tid korrekt.  Gå venligst til tidsindstillingerne på din computer og tjek følgende:  - AM/PM - Forskydning af tid - Dag, måned og år - Tidszone - Sommer- og vintertid  Forskellen i forhold til korrekt tid: { $val }.
qt-misc-invalid-property-found-on-card-please = Ugyldig egenskab fundet i kort. Brug venligst Værktøjer>Tjek database, og dukker problemet op igen, så stil venligst et spørgsmål på supportstedet.
qt-misc-loading = Henter...
qt-misc-manage = Administrér
qt-misc-name-exists = Navnet eksisterer.
qt-misc-non-unicode-text = <tekst som ikke er i unicode>
qt-misc-optimizing = Optimerer...
qt-misc-please-connect-a-microphone-and-ensure = Tilslut en mikrofon, og forsikr dig, at andre programmer ikke bruger lydenheden.
qt-misc-please-ensure-a-profile-is-open = Sørg venligst for at have en profil åben og at Anki ikke er aktiv, forsøg dernæst igen.
qt-misc-please-select-1-card = (vælg venligst 1 kort)
qt-misc-please-select-a-deck = Vælg venligst et kortsæt.
qt-misc-please-use-fileimport-to-import-this = Benyt venligst Fil>Importér for at importere denne fil.
qt-misc-processing = Behandler...
qt-misc-resume-now = Fortsæt nu
qt-misc-reverted-to-state-prior-to = Gendannet til tilstand før '{ $val }'.
qt-misc-shift-key-was-held-down-skipping = Skift-tasten blev holdt nede. Spring over automatisk synkronisering og indlæsning af udvidelsesmoduler.
qt-misc-study-deck = Studér kortsæt ...
qt-misc-target-deck-ctrlandd = Mål-kortsæk (Ctrl+D)
qt-misc-the-following-character-can-not-be = Det følgende tegn kan ikke anvendes: { $val }
qt-misc-the-requested-change-will-require-a = Den ønskede ændring ville kræve et fuld upload af databasen når du synkroniserer din samling næste gang. Hvis du har genopfriskninger eller andre ændringer som venter på et andet apparat der ikke er synkroniseret endnu, mistes de. Vil du fortsætte?
qt-misc-there-must-be-at-least-one = Der skal mindst være én profil.
qt-misc-this-file-exists-are-you-sure = Denne fil findes. Er du sikker på at du vil overskrive den?
qt-misc-undo = Fortryd
qt-misc-undo2 = Fortryd { $val }
qt-misc-waiting-for-editing-to-finish = Afventer færdiggørelse af redigering.
qt-misc-would-you-like-to-download-it = Vil du gerne downloade den nu?
qt-misc-second = { $count ->
    [one] { $count } sekund
   *[other] { $count } sekunder
  }
