# ⚠️ Do not rename the file - screenshot_store.yml is referenced by screenshot_compare.yml
#
# Adapted from https://github.com/takahirom/roborazzi/blob/4be7f304fa23f2f00fad67ab612aec2035ac9db2/.github/workflows/StoreScreenshot.yml
# Modified from the original: adapted to AnkiDroid CI conventions.
#
# Copyright 2023 takahirom
# Copyright 2019 Square, Inc.
# Copyright The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


name: "🛠️ Screenshots: Store Baseline"

on:
  push:
    branches:
      - main
  # On PRs, only run this when structural changes occur, to be sure 'main' can still store baselines
  pull_request:
    paths:
      - '.github/workflows/screenshot_*.yml'
      - 'gradle/libs.versions.toml'
      - 'AnkiDroid/build.gradle'
      - 'AnkiDroid/build.gradle.kts' # future-proof
      - '**/ScreenshotTest.kt'
      - 'tools/compare-screenshot-test.sh'

permissions: {}

jobs:
  store-screenshot-test:
    # On PRs, this verifies the workflow runs on `main`, it's not a store
    name: ${{ github.ref == 'refs/heads/main' && 'store' || 'test' }}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: read # for clone
      actions: write # for upload-artifact

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "jetbrains"
          java-version: "21"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Better than caching and/or extensions of actions/setup-java
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          # Use open source provider: https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#basic-caching
          cache-provider: basic
          gradle-version: wrapper

      - name: Record screenshots
        id: record-test
        run: |
          # Use --rerun-tasks to disable cache for test task
          ./gradlew recordRoborazziPlayDebug -Pscreenshot --stacktrace --rerun-tasks

      - name: Upload screenshot baseline
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ always() }}
        with:
          name: screenshot  # downloaded by screenshot_compare.yml
          path: |
            **/build/outputs/roborazzi
          retention-days: 30

      - name: Upload screenshot reports
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ always() }}
        with:
          name: screenshot-reports
          path: |
            **/build/reports
          retention-days: 30

      - name: Upload screenshot test results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ always() }}
        with:
          name: screenshot-test-results
          path: |
            **/build/test-results
          retention-days: 30