qt-accel-about = &Über
qt-accel-about-mac = Über Anki …
qt-accel-cards = &Karten
qt-accel-check-database = &Datenbank überprüfen
qt-accel-check-media = &Medien überprüfen
qt-accel-edit = &Bearbeiten
qt-accel-exit = &Beenden
qt-accel-export = Exportieren …
qt-accel-export-notes = Notizen &exportieren …
qt-accel-file = &Datei
qt-accel-filter = Fil&ter
qt-accel-find = S&uchen
qt-accel-find-and-replace = Suchen und &ersetzen …
qt-accel-find-duplicates = &Duplikate suchen …
qt-accel-go = &Gehe zu
qt-accel-guide = &Anleitung
qt-accel-help = &Hilfe
qt-accel-import = &Importieren …
qt-accel-info = Kartenstat&istik …
qt-accel-invert-selection = Auswahl &umkehren
qt-accel-next-card = &Nächste Karte
qt-accel-note = N&otiz
qt-accel-notes = &Notizen
qt-accel-preferences = &Einstellungen …
qt-accel-previous-card = &Vorherige Karte
qt-accel-select-all = &Alle auswählen
qt-accel-select-notes = &Notizen auswählen
qt-accel-support-anki = Anki unter&stützen
qt-accel-switch-profile = Benutzerprofil wech&seln
qt-accel-tools = E&xtras
qt-accel-undo = &Rückgängig
qt-accel-redo = Wiede&rherstellen
qt-accel-set-due-date = Fälligkeits&datum setzen …
qt-accel-forget = Lernfortschritt zu&rücksetzen
qt-accel-view = &Ansicht
qt-accel-full-screen = &Vollbildmodus ein-/ausschalten
qt-accel-layout = &Layout
qt-accel-layout-auto = &Automatisch
qt-accel-layout-vertical = &Vertikal
qt-accel-layout-horizontal = &Horizontal
qt-accel-zoom-in = H&ineinzoomen
qt-accel-zoom-out = Herausz&oomen
qt-accel-reset-zoom = Zoom zu&rücksetzen
qt-accel-toggle-sidebar = Seitenleiste anzeigen/ausblenden
qt-accel-zoom-editor-in = Im Editor hine&inzoomen
qt-accel-zoom-editor-out = Im Editor herausz&oomen
qt-accel-create-backup = &Sicherungskopie erstellen
qt-accel-load-backup = Auf den Stand der Siche&rungskopie zurücksetzen
qt-accel-upgrade-downgrade = Anki-Version wechseln
