profiles-anki-could-not-read-your-profile = آنکی قادر به خواند اطلاعات پروفایل شما نبود. اندازۀ پنجره و اطلاعات همگام‌سازی اکانت فراموش شده‌اند.
profiles-anki-could-not-rename-your-profile = آنکی به دلیل ناتوانی در نامگذاری مجدد پوشۀ پروفایل شما روی هارد درایو، قادر به نامگذاری مجدد پروفایل شما نیست. لطفاً از اینکه اجازۀ ویرایش مسیر Documents/Anki را دارید و هیچ نرم‌افزار دیگری در حال استفاده از پوشۀ پروفایل شما نیست اطمینان حاصل کرده و مجدداً تلاش کنید.
profiles-folder-already-exists = پوشه از قبل وجود دارد.
profiles-open = باز کردن
profiles-open-backup = باز کردن پشتیبان…
profiles-please-remove-the-folder-and = لطفاً پوشۀ { $val } را حذف کرده و دوباره امتحان کنید.
profiles-profile-corrupt = پروفایل خراب است
profiles-profiles = پروفایل‌ها
profiles-quit = خروج
profiles-user-1 = کاربر 1
profiles-confirm-lang-choice = آیا از تغییر زبان آنکی به { $lang } اطمینان دارید؟
profiles-could-not-create-data-folder = آنکی قادر به ایجاد پوشه دیتا نبود. لطفاً محل فایل‌ها از راهنما را ببینید، تا مطمئن شوید که این محل در حالت فقط خواندن نیست.
profiles-prefs-corrupt-title = تنظیمات خراب
profiles-prefs-file-is-corrupt = فایل prefs21.db خراب بود و از نو ایجاد شد. اگر از چند پروفایل استفاده می‌کردید، لطفاً آنها را با نام‌های قبلی دوباره اضافه کنید تا کارت‌های موجود در آن پروفایل‌ها بازیابی شوند.
profiles-profile-does-not-exist = پروفایل درخواست شده وجود ندارد.
profiles-creating-backup = در حال تولید پشتیبان...
profiles-backup-created = پشتیبان ایجاد شد.
profiles-backup-creation-failed = ایجاد پشتیبان انجام نشد: { $reason }
profiles-backup-unchanged = هیچ تغییری نسبت به آخرین نسخه پشتیبان وجود ندارد.
