decks-add-new-deck-ctrlandn = Ajouter un nouveau paquet (Ctrl+N)
decks-build = Générer
decks-cards-selected-by = cartes sélectionnées par
decks-create-deck = Créer un paquet
decks_create_even_if_empty = Créer/Mettre à jour ce paquet même s'il est vide
decks-custom-steps-in-minutes = Pas personnalisés (en minutes)
decks-deck = Paquet
decks-decreasing-intervals = Intervalles décroissants
decks-delete-deck = Supprimer le paquet
decks-enable-second-filter = Activer un second filtre
decks-filter = Sélection :
decks-filter-2 = Filtre 2
decks-get-shared = Partages
decks-import-file = Importer
decks-increasing-intervals = Intervalles croissants
decks-latest-added-first = Les derniers ajouts d’abord
decks-limit-to = Limiter à
decks-minutes = minutes
decks-most-lapses = Les plus difficiles (en nombre de faux pas)
decks-new-deck-name = Nouveau nom du paquet :
decks-no-deck = (aucun paquet)
decks-oldest-seen-first = Les plus anciennement vues d’abord
decks-order-added = Ordre d’ajout
decks-order-due = Ordre des échéances
decks-please-select-something = Veuillez sélectionner au moins un élément.
decks-random = Au hasard
decks-relative-overdueness = Échéance dépassée relative
decks-repeat-failed-cards-after = Répéter les cartes non connues plus tard.
# e.g. "Delay for Again", "Delay for Hard", "Delay for Good"
decks-delay-for-button = Délai pour { $button }
decks-reschedule-cards-based-on-my-answers = Replanifier les cartes selon mes réponses dans ce paquet
decks-study = Étudier
decks-study-deck = Étudier le paquet
decks-filtered-deck-search-empty = Aucune carte trouvée pour la recherche fournie. Certaines cartes peuvent avoir été exclues parce qu'elles se trouvent dans un autre paquet filtré, ou suspendues.
decks-unmovable-cards = Montrer les cartes exclues
decks-learn-header = En cours
# The count of cards waiting to be reviewed
decks-review-header = À réviser
decks-zero-minutes-hint = (0 = renvoyer la carte dans le paquet original)
