profiles-anki-could-not-read-your-profile = Anki n’a pas pu lire les données de votre profil. Les tailles des fenêtres et les informations de connexion à la synchronisation ont été oubliées.
profiles-anki-could-not-rename-your-profile = Anki n’a pas pu renommer votre profil car il n’a pas réussi à renommer le dossier profil sur le disque. Veuillez vous assurer que vous avez bien la permission d’écrire dans Documents/Anki et qu’aucune autre application n’est en train d’accéder à vos dossiers profils, puis réessayez.
profiles-folder-already-exists = Le dossier existe déjà.
profiles-open = Ouvrir
profiles-open-backup = Ouvrir la sauvegarde...
profiles-please-remove-the-folder-and = Veuillez enlever le dossier { $val } et réessayer.
profiles-profile-corrupt = Profil corrompu
profiles-profiles = Comptes
profiles-quit = Quitter
profiles-user-1 = Utilisateur 1
profiles-confirm-lang-choice = Êtes-vous sûr de vouloir afficher l'interface d'Anki en { $lang } ?
profiles-could-not-create-data-folder = Anki n'a pas pû créer son dossier de données. Veuillez consulter la section Emplacement des fichiers du manuel, et assurez-vous que l'emplacement n'est pas en lecture seule.
profiles-prefs-corrupt-title = Préférences corrompues
profiles-prefs-file-is-corrupt = Le fichier d'Anki prefs21.db a été corrompu et a été recréé. Si vous utilisiez plusieurs profils, veuillez les ajouter à nouveau en utilisant les mêmes noms pour récupérer vos cartes.
profiles-profile-does-not-exist = Le profil demandé n'existe pas.
profiles-creating-backup = Création de sauvegarde...
profiles-backup-created = Sauvegarde créée.
profiles-backup-creation-failed = Échec de la création de sauvegarde : { $reason }
profiles-backup-unchanged = Pas de changement depuis la dernière sauvegarde.
