qt-misc-addons = Gehigarriak
qt-misc-all-cards-notes-and-media-for = Profil honen karta, ohar eta euskarri guztiak ezabatuko dira. Ziur zaude?
qt-misc-anki-updatedanki-has-been-released = <h1>Anki eguneratuta</h1>Anki { $val } argitaratu da.<br><br>
qt-misc-backing-up = Babeskpopia egiten...
qt-misc-browse = Arakatu
qt-misc-change-note-type-ctrlandn = Aldatu ohar-mota (Ktrl+N)
qt-misc-check-the-files-in-the-media = Egiaztatu edukien direktorioko fitxategiak
qt-misc-choose-deck = Aukeratu karta-sorta
qt-misc-choose-note-type = Aukeratu nota-mota
qt-misc-closing = Ixten...
qt-misc-configure-interface-language-and-options = Konfiguratu interfazearen hizkuntza eta aukerak
qt-misc-create-filtered-deck = iragazitako sorta sortu
qt-misc-debug-console = Arazketa kontsola
qt-misc-deck-will-be-imported-when-a = profila ireki bezain laster sorta inportuta izango da
qt-misc-default = Lehenetsia
qt-misc-empty-cards = Karta hutsak
qt-misc-error-during-startup = Abiarazteko akatsa: { $val }
qt-misc-filtered-deck = Sorta iragazitakoa { $val }
qt-misc-ignore-this-update = Ezikusi egin eguneratze honi
qt-misc-in-order-to-ensure-your-collection = Gailu batetik beste batera mugitu duzun bilduma ondo dabilela egiaztatzeko, Anki-k zure ordenagiluko barne-erlojua konpontuta dagoela behar du. Barne-erlojua oker ibil daiteke, nahiz eta zure sistemak tokiko denbora zuzena erakusten duen.  Mesedez, denborako kudeatzailera joan eta hori zehaztu :   - AM/PM - erlojuaren joera - Egun, hilabete eta urte - ordu eremua - Udako ordutegia  kendura denbora zuzenera : { $val }
qt-misc-invalid-property-found-on-card-please = kartan ezaugarri baliogabe bat dago. Mesedez erabili Tresnak> Egiaztatu Datu-basea eta arazoak agertzen bada berriro, Anki webgunean galdetu
qt-misc-loading = Kargatzen...
qt-misc-manage = Kudeatu
qt-misc-name-exists = Izena existitzen da jadanik.
qt-misc-non-unicode-text = ez unicode testua
qt-misc-optimizing = Optimizatzen
qt-misc-please-connect-a-microphone-and-ensure = Mesedez, mikrofon bat konektatu eta beste programek ez dutela audio gailua erabiltzen egiazta ezazu
qt-misc-please-ensure-a-profile-is-open = mesedez profil bat irekita dagoela eta anki ez dagoela lanpetuta segurta ezazu, eta gero berriro entseatu
qt-misc-please-select-1-card = aukeratu karta bat mesedez
qt-misc-please-select-a-deck = Mesedez, sorta bat aukera ezazu
qt-misc-please-use-fileimport-to-import-this = Mesedez, Fitxategi>Inportatu menuz fitxategi hau inportatu
qt-misc-processing = Prozesatzen...
qt-misc-resume-now = orain jarraitu
qt-misc-reverted-to-state-prior-to = aurreko egoerara '{ $val }' itzulita
qt-misc-shift-key-was-held-down-skipping = Shift Tekla sakatuta gelditu da. Sinkronizatze automatikoa eta gehigarriak kargatzea baztertu.
qt-misc-shortcut-key-left-arrow = Zuzeneko azipen tekla: Ezker gezi
qt-misc-shortcut-key-right-arrow-or-enter = Zuzeneko azipen tekla: Eskuin gezi edo Enter
qt-misc-study-deck = Ikasi sorta...
qt-misc-sync = Sinkronizatu
qt-misc-target-deck-ctrlandd = Jomuga izanda sorta(Ktrl+D)
qt-misc-the-following-character-can-not-be = Ez da posible { $val } karakterea erabiltzea
qt-misc-the-requested-change-will-require-a = Eskatutako aldaketa datu-baseko kargatze osoa beharko du hurrengo aldian zure bilduma sinkronizatzeko. Berrikuspenak edo beste gailu batean itxoiten ari diren aldaketa batzuk baldin badituzu, eta ez dira dagoeneko sinkronizatuak, galduta egongo dira. Jarrai ?
qt-misc-there-must-be-at-least-one = Profila bat existitu behar du gutxienez
qt-misc-this-file-exists-are-you-sure = Fitxategia existitzen da. Ziur zaude gainidatzi nahi duzula?
qt-misc-undo = Desegin
qt-misc-undo2 = { $val } desegin
qt-misc-waiting-for-editing-to-finish = editatzeari itxoin bukatzeko
qt-misc-would-you-like-to-download-it = Orain deskargatu nahi duzu?
qt-misc-second = { $count ->
    [one] Segundo { $count }
   *[other] { $count } segundo
  }
