qt-accel-about = &Hakkında...
qt-accel-about-mac = Anki Hakkında...
qt-accel-cards = &Kartlar
qt-accel-check-database = Veritabanını &Kontrol Et
qt-accel-check-media = &Ortamı Kontrol Et
qt-accel-edit = Dü&zenle
qt-accel-exit = Kapat
qt-accel-export = &Dışa Aktar...
qt-accel-export-notes = &Notları dışa aktar...
qt-accel-file = &Dosya
qt-accel-filter = Fil&tre
qt-accel-find = &Bul
qt-accel-find-and-replace = Bul ve Değ&iştir...
qt-accel-find-duplicates = &Yinelenenleri Bul...
qt-accel-go = &Git
qt-accel-guide = &Kılavuz
qt-accel-help = &Yardım
qt-accel-import = &İçe Aktar...
qt-accel-info = &Bilgi...
qt-accel-invert-selection = S&eçimi Tersine Çevir
qt-accel-next-card = Sonraki &Kart
qt-accel-note = N&ot
qt-accel-notes = &Notlar
qt-accel-preferences = &Tercihler
qt-accel-previous-card = &Önceki Kart
qt-accel-select-all = &Tümünü Seç
qt-accel-select-notes = &Notları Seç
qt-accel-support-anki = &Anki'ye Destek Ol...
qt-accel-switch-profile = &Profil Değiştir
qt-accel-tools = &Araçlar
qt-accel-undo = &Geri Al
qt-accel-redo = Yeniden yap
qt-accel-set-due-date = &Son Tarihi Ayarla
qt-accel-forget = Unut
qt-accel-view = &Görüntüle
qt-accel-full-screen = &Tam Ekran Aç/Kapat
qt-accel-layout = &Düzen
qt-accel-layout-auto = &Otomatik
qt-accel-layout-vertical = &Dikey
qt-accel-layout-horizontal = &Yatay
qt-accel-zoom-in = &Yakınlaştır
qt-accel-zoom-out = &Uzaklaştır
qt-accel-reset-zoom = Yakınlaştırmayı &Sıfırla
qt-accel-toggle-sidebar = Kenar Çubuğunu Aç/Kapa
qt-accel-zoom-editor-in = Düzenleyiciyi &Yakınlaştır
qt-accel-zoom-editor-out = Düzenleyiciyi &Uzaklaştır
qt-accel-create-backup = &Yedek Oluştur
qt-accel-load-backup = Yedeğe &Geri Dön
qt-accel-upgrade-downgrade = Sürüm Yükseltme/Düşürme
