card-stats-added = 添加日期
card-stats-first-review = 首次复习日期
card-stats-latest-review = 最后复习日期
card-stats-interval = 间隔
card-stats-ease = 简易度
card-stats-review-count = 复习次数
card-stats-lapse-count = 遗忘次数
card-stats-average-time = 平均用时
card-stats-total-time = 总计用时
card-stats-new-card-position = 所在位置
card-stats-card-template = 卡片模板
card-stats-note-type = 笔记模板
card-stats-deck-name = 所属牌组
card-stats-preset = 预设配置
card-stats-note-id = 笔记编号
card-stats-card-id = 卡片编号
card-stats-review-log-rating = 评分
card-stats-review-log-type = 状态
card-stats-review-log-date = 日期
card-stats-review-log-time-taken = 时间
card-stats-review-log-type-learn = 学习
card-stats-review-log-type-review = 复习
card-stats-review-log-type-relearn = 重新学习
card-stats-review-log-type-filtered = 已筛选
card-stats-review-log-type-manual = 手动更改
card-stats-review-log-type-rescheduled = 已重新排程
card-stats-review-log-elapsed-time = 上次复习后经过时间
card-stats-no-card = （没有卡片可供展示）
card-stats-custom-data = 自定义数据
card-stats-fsrs-stability = 记忆稳定期
card-stats-fsrs-difficulty = 难度
card-stats-fsrs-retrievability = 记忆可提取性
card-stats-fsrs-forgetting-curve-title = 遗忘曲线
card-stats-fsrs-forgetting-curve-first-week = 首周
card-stats-fsrs-forgetting-curve-first-month = 首月
card-stats-fsrs-forgetting-curve-first-year = 首年
card-stats-fsrs-forgetting-curve-all-time = 全部时间
card-stats-fsrs-forgetting-curve-probability-of-recalling = 回忆成功概率
card-stats-fsrs-forgetting-curve-desired-retention = 期望的记忆保留率

## Window Titles

card-stats-current-card = 当前卡片（{ $context }）
card-stats-previous-card = 上一张卡片（{ $context }）
