custom-study-all-cards-in-random-order-dont = Alle kaarten in willekeurige volgorde (niet herschikken)
custom-study-all-review-cards-in-random-order = Alle herhaalkaarten in willekeurige volgorde
custom-study-cards = kaarten
custom-study-cards-from-the-deck = kaarten van de set
custom-study-choose-tags = Tags kiezen
custom-study-custom-study-session = Aangepaste studiesessie
custom-study-due-cards-only = Enkel verwachte kaarten
custom-study-increase-todays-new-card-limit = De limiet op nieuwe kaarten vandaag verhogen
custom-study-increase-todays-new-card-limit-by = De limiet op nieuwe kaarten vandaag verhogen met
custom-study-increase-todays-review-card-limit = De limiet op herhaalkaarten vandaag verhogen
custom-study-increase-todays-review-limit-by = De limiet op herhaalkaarten vandaag verhogen met
custom-study-new-cards-in-deck-over-today = Nieuwe kaarten in de set voorbij de limiet van vandaag: { $val }
custom-study-new-cards-only = Enkel nieuwe kaarten
custom-study-no-cards-matched-the-criteria-you = Geen enkele kaart voldeed aan de criteria die u ingaf.
custom-study-ok = Ok
custom-study-preview-new-cards = Nieuwe kaarten op voorhand herhalen
custom-study-preview-new-cards-added-in-the = Vooraf nieuwe kaarten bekijken die zijn toegevoegd in de laatste
custom-study-require-one-or-more-of-these = Vereis één of meer van deze tags:
custom-study-review-ahead = Op voorhand herhalen
custom-study-review-ahead-by = Op voorhand herhalen voor
custom-study-review-cards-forgotten-in-last = Kaarten herhalen die vergeten waren in de laatste
custom-study-review-forgotten-cards = Vergeten kaarten herhalen
custom-study-reviews-due-in-deck-over-today = De verwachte herhalingen voor de set over de limiet van vandaag: { $val }
custom-study-select = Willekeurig
custom-study-select-tags-to-exclude = Selecteer ongewilde tags:
custom-study-selective-study = Selectief studeren
custom-study-study-by-card-state-or-tag = Leren aan de hand van kaartstatus of tag
