editing-add-media = Media toevoegen
editing-an-error-occurred-while-opening = Er deed zich een probleem voor bij het openen van { $val }
editing-attach-picturesaudiovideo-f3 = Foto's/audio/video toevoegen (F3)
editing-bold-text-ctrlandb = Vetgedrukte tekst (Ctrl + B)
editing-cards = Kaarten
editing-change-colour-f8 = Van kleur veranderen (F8)
editing-cloze-deletion-ctrlandshiftandc = Cloze (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = Kon audio niet opnemen. Hebt u 'lame' geïnstalleerd?
editing-customize-card-templates-ctrlandl = Kaartsjablonen aanpassen (Ctrl+L)
editing-customize-fields = Velden aanpassen
editing-cut = Knippen
editing-edit-current = Huidige bewerken
editing-edit-html = HTML bewerken
editing-fields = Velden
editing-html-editor = HTML-editor
editing-italic-text-ctrlandi = Cursieve tekst (Ctrl + I)
editing-jump-to-tags-with-ctrlandshiftandt = Spring naar tags met Ctrl+Shift+T
editing-latex-equation = LaTeX-formule
editing-latex-math-env = LaTeX wiskunde-omgeving
editing-mathjax-block = MathJaxblok
editing-mathjax-chemistry = MathJax chemie
editing-mathjax-inline = MathJaxinline
editing-paste = Plakken
editing-record-audio-f5 = Audio opnamen (F5)
editing-remove-formatting-ctrlandr = Opmaak verwijderen (Ctrl+R)
editing-set-foreground-colour-f7 = Voorgrondkleur instellen (F7)
editing-show-duplicates = Dubbels tonen
editing-subscript-ctrland = Onderschrift (Ctrl+=)
editing-superscript-ctrlandand = Bovenschrift (Ctrl++)
editing-to-make-a-cloze-deletion-on = Om een cloze te maken van een bestaande aantekening moet u eerst het type veranderen naar cloze, via Bewerken>Aantekeningstype.
editing-underline-text-ctrlandu = Tekst onderstrepen (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = Waarschuwing, clozes zullen niet werken zolang u het type bovenaan niet verandert naar Cloze.
