fields-add-field = Veld toevoegen
fields-delete-field-from = Veld uit { $val } verwijderen?
fields-editing-font = Lettertype invoerveld
fields-field = Veld:
fields-field-name = Veldnaam:
fields-fields-for = Velden voor { $val }
fields-font = Lettertype:
fields-new-position-1 = Nieuwe positie (1...{ $val }):
fields-notes-require-at-least-one-field = Aantekeningen moeten ten minste één veld bevatten.
fields-remember-last-input-when-adding = Laatste invoer tijdens toevoegen onthouden
fields-reverse-text-direction-rtl = Omgekeerde tekstrichting (RNL)
fields-size = Grootte:
fields-sort-by-this-field-in-the = Gebruik dit veld in de browser om te sorteren
fields-that-field-name-is-already-used = Die veldnaam is al in gebruik.
