preferences-automatically-sync-on-profile-openclose = Profiel automatisch synchroniseren bij openen/sluiten
preferences-backups = Back-ups
preferences-backups2 = back-ups
preferences-backupsanki-will-create-a-backup-of = <b>Back-ups</b><br>Anki zal een back-up maken van uw collectie telkens wanneer het programma geopend of gesynchroniseerd wordt.
preferences-basic = Basis
preferences-change-deck-depending-on-note-type = Set veranderen op basis van aantekeningstype
preferences-changes-will-take-effect-when-you = De wijzigingen treden in werking wanneer u Anki opnieuw opstart.
preferences-hardware-acceleration-faster-may-cause-display = Hardwareversnelling (sneller, kan weergaveproblemen veroorzaken)
preferences-hours-past-midnight = uur na middernacht
preferences-interface-language = Interfacetaal:
preferences-keep = Bewaar
preferences-learn-ahead-limit = Maximaal vooruit leren
preferences-mins = minuten
preferences-network = Netwerk
preferences-next-day-starts-at = Volgende dag begint om
preferences-note-media-is-not-backed-up = Let op: er wordt geen back-up gemaakt van uw media. Maak voor de zekerheid zelf regelmatig een back-up van uw Anki-bestanden.
preferences-on-next-sync-force-changes-in = Forceer veranderingen in één richting bij volgende synchronisatie
preferences-paste-clipboard-images-as-png = Plak afbeeldingen van het klembord als PNG
preferences-please-restart-anki-to-complete-language = Gelieve Anki te herstarten om de taalverandering te voltooien.
preferences-preferences = Voorkeuren
preferences-scheduling = Herplannen
preferences-show-learning-cards-with-larger-steps = Leerkaarten met grotere leerstappen voor herhalingen weergeven
preferences-show-next-review-time-above-answer = De tijd van de volgende herhaling boven de antwoordknoppen tonen.
preferences-show-remaining-card-count-during-review = Aantal resterende kaarten tijdens leren tonen
preferences-some-settings-will-take-effect-after = Sommige instellingen worden pas toegepast nadat u Anki opnieuw opgestart heeft.
preferences-synchronisation = <b>Synchronisatie</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Synchronisatie</b><br> Uitgeschakeld; klik op de Sync-knop in het hoofdscherm om deze functie in te schakelen.
preferences-synchronize-audio-and-images-too = Geluiden en afbeeldingen ook synchroniseren
preferences-this-will-reset-any-cards-in = Hiermee worden alle leerkaarten opnieuw ingesteld, gefilterde kaartspellen gewist en de plannerversie gewijzigd. Verdergaan?
preferences-timebox-time-limit = Maximale studeertijd
preferences-when-adding-default-to-current-deck = Gebruik standaard de huidige set bij het toevoegen
preferences-you-can-restore-backups-via-fileswitch = U kunt back-ups herstellen via Bestand > Profiel omschakelen.
