adding-add-shortcut-ctrlandenter = Añadir (atajo: ctrl+enter)
adding-added = Añadidas
adding-discard-current-input = ¿Descartar la entrada actual?
adding-keep-editing = Seguir editando
adding-edit = Editar “{ $val }”
adding-history = Historia
adding-note-deleted = (Nota borrada)
adding-shortcut = Atajo: { $val }
adding-the-first-field-is-empty = El primer campo está vacío.
adding-you-have-a-cloze-deletion-note = Tienes un tipo de nota de respuesta anidada pero no has insertado ningún nido. ¿Quieres continuar?
adding-cloze-outside-cloze-notetype = Solo se puede anidar una respuesta en notas de tipo respuesta anidada
adding-cloze-outside-cloze-field = El anidamiento de una respuesta solo se puede usar en campos que usan el filtro “cloze:”. Este suele ser el primer campo.
