adding-add-shortcut-ctrlandenter = (ctrl+enter :اختصار) إضافة
adding-added = أُضيفت
adding-discard-current-input = هل تريد تجاهل المدخلات الحالية؟
adding-keep-editing = استمر بالتحرير
adding-edit = تحرير "{ $val }"
adding-history = السجل
adding-note-deleted = (ملحوظة محذوفة)
adding-shortcut = اختصار: { $val }
adding-the-first-field-is-empty = الحقل الأول فارغ.
adding-you-have-a-cloze-deletion-note = أنت تستخدم نوع ملحوظات ملء الفراغات لكنك لم تصنع أي عبارة ملء فراغات. هل تريد الاستمرار؟
adding-cloze-outside-cloze-notetype = يمكن استخدام عبارات ملء الفراغات في أنواع ملحوظات ملء الفراغات فقط.
adding-cloze-outside-cloze-field = يمكن استخدام عبارات ملء الفراغات في الحقول التي تستخدم فلتر 'cloze:' فقط. يكون هذا الحقل الأول عادةً.
