profiles-anki-could-not-read-your-profile = لم يستطع أنكي قراءة بيانات ملفك الشخصي. أحجام النوافذ ومعلومات دخول المزامنة تم نسيانها.
profiles-anki-could-not-rename-your-profile = لم يستطع أنكي إعادة تسمية ملفك الشخصي لعدم استطاعته إعادة تسمية مجلد الملف الشخصي على القرص. تأكد من أن لديك الإذن بالكتابة إلى مجلد مستندات/أنكي وأنه لا توجد برامج أخرى تحاول الوصول إلى مجلدات ملفك الشخصي، ثم أعد المحاولة.
profiles-folder-already-exists = المجلد موجود مسبقًا.
profiles-open = فتح
profiles-open-backup = فتح نسخة احتياطية...
profiles-please-remove-the-folder-and = احذف المجلد { $val } ثم حاول مجددًا.
profiles-profile-corrupt = الملف الشخصي تالف
profiles-profiles = ملفات شخصية
profiles-quit = خروج
profiles-user-1 = مستخدم 1
profiles-confirm-lang-choice = هل أنت متأكد من أنك تريد استخدام أنكي بلغة { $lang }؟
profiles-could-not-create-data-folder = لم يتمكن أنكي من إنشاء مجلد البيانات. انظر قسم مواقع الملفات في دليل الاستخدام، وتأكد من أن الموقع قابل للكتابة.
profiles-prefs-corrupt-title = التفضيلات تالفة
profiles-prefs-file-is-corrupt = ملف prefs21.db لأنكي تالف وتمت إعادة إنشائه. إذا كنت تستخدم عدة ملفات شخصية، أعد إضافتها باستخدام الأسماء نفسها لاستعادة بطاقاتك.
profiles-profile-does-not-exist = لا يتوفر الملف الشخصي المطلوب.
profiles-creating-backup = إنشاء نسخة احتياطية...
profiles-backup-created = تم إنشاء النسخة الاحتياطية.
profiles-backup-creation-failed = فشل إنشاء نسخة احتياطية: { $reason }
profiles-backup-unchanged = لا تغييرات منذ آخر نسخة احتياطية.
