decks-add-new-deck-ctrlandn = Přidat nový balíček (Ctrl+N)
decks-build = Sestavit
decks-cards-selected-by = karet setříděných podle
decks-create-deck = Vytvořit balíček
decks_create_even_if_empty = Vytvořit/aktualizovat tento balíček i když je prázdný
decks-custom-steps-in-minutes = Vlastní kroky (v minutách)
decks-deck = Balíček
decks-decreasing-intervals = Snižujícího se intervalu
decks-delete-deck = Odstranit balíček
decks-enable-second-filter = Zapnout druhý filtr
decks-filter = Filtr:
decks-filter-2 = Filtr 2
decks-get-shared = Stáhnout sdílené
decks-import-file = Importovat soubor
decks-increasing-intervals = Zvyšujícího se intervalu
decks-latest-added-first = Poslední přidané nejdříve
decks-limit-to = Omezit na
decks-minutes = minut
decks-most-lapses = Nejvíce zapomínaných
decks-new-deck-name = Název nového balíčku:
decks-no-deck = [žádný balíček]
decks-oldest-seen-first = Nejstarší zobrazit nejdříve
decks-order-added = Pořadí přidání
decks-order-due = Pořadí opakování
decks-please-select-something = Prosím proveďte výběr.
decks-random = Náhodně
decks-relative-overdueness = Relativní zpožděnost
decks-repeat-failed-cards-after = Zopakovat chybné karty poté
# e.g. "Delay for Again", "Delay for Hard", "Delay for Good"
decks-delay-for-button = Posunutí pro { $button }
decks-reschedule-cards-based-on-my-answers = Přeplánování karet založené na mých odpovědích v tomto balíčku
decks-study = Studovat
decks-study-deck = Studovat balíček
decks-filtered-deck-search-empty = Vyhledávání neodpovídají žádné karty. Některé karty mohly být vyloučeny, protože jsou v jiném filtrovaném balíčku nebo vyřazené.
decks-unmovable-cards = Zobrazit všechny vyloučené karty
decks-learn-header = Učení
# The count of cards waiting to be reviewed
decks-review-header = Zkoušení
decks-zero-minutes-hint = (0 = vrátí kartu do původního balíčku)
