editing-actual-size = Přepnout skutečnou velikost
editing-add-media = Přidat multimédia
editing-align-left = Zarovnat vlevo
editing-align-right = Zarovnat vpravo
editing-an-error-occurred-while-opening = Při otvírání { $val } došlo k chybě
editing-attach-picturesaudiovideo = Připojit obrázky/zvuk/video
editing-bold-text = Tučný text
editing-cards = Karty
editing-center = Na střed
editing-change-color = Změnit barvu
editing-cloze-deletion = Doplňovačka
editing-cloze-deletion-repeat = Doplňovačka (stejná karta)
editing-copy-image = Kopírovat obrázek
editing-couldnt-record-audio-have-you-installed = Zvuk nebylo možné nahrát. Máte nainstalovaný „lame“?
editing-customize-card-templates = Přizpůsobit šablony karet
editing-customize-fields = Přizpůsobit pole
editing-cut = Vyjmout
editing-double-click-image = dvojklik na obrázek
editing-double-click-to-expand = (dvojklikem rozbalit)
editing-double-click-to-collapse = dvojklikem sbalit
editing-edit-current = Upravit tuto kartu
editing-edit-html = Upravit HTML
editing-fields = Pole
editing-float-left = Obtékání zprava
editing-float-right = Obtékání zleva
editing-float-none = Bez obtékání
editing-indent = Zvětšit odsazení
editing-italic-text = Kurzíva
editing-jump-to-tags-with-ctrlandshiftandt = Skočit na štítky přes Ctrl+Shift+T
editing-justify = Do bloku
editing-latex = LaTeX
editing-latex-equation = Rovnice v LaTeXu
editing-latex-math-env = Matem. proměnná LaTeXu
editing-mathjax-block = MathJax blok
editing-mathjax-chemistry = MathJax chemie
editing-mathjax-inline = MathJax inline
editing-mathjax-placeholder = Stiskněte { $accept } pro potvrzení, { $newline } pro nový řádek.
editing-media = Multimédia
editing-open-image = Otevřít obrázek
editing-show-in-folder = Zobrazit ve složce
editing-ordered-list = Číslovaný seznam
editing-outdent = Zmenšit odsazení
editing-paste = Vložit
editing-record-audio = Nahrát zvuk
editing-remove-formatting = Odstranit formátování
editing-restore-original-size = Obnovit původní velikost
editing-select-remove-formatting = Vybrat formátování, které se má odstranit
editing-show-duplicates = Zobrazit duplikáty
editing-subscript = Dolní index
editing-superscript = Horní index
editing-tags = Štítky
editing-tags-add = Přidat štítek
editing-tags-copy = Kopírovat štítky
editing-tags-remove = Odstranit štítky
editing-tags-select-all = Vybrat všechny štítky
editing-text-color = Barva textu
editing-text-highlight-color = Barva zvýraznění textu
editing-to-make-a-cloze-deletion-on = Chcete-li přidat doplňovačku do existující poznámky, musíte její typ nejdřív změnit na doplňovačku přes „Poznámky > Změnit typ poznámky“.
editing-toggle-html-editor = Přepnout editor HTML
editing-toggle-visual-editor = Přepnout vizuální editor
editing-toggle-sticky = Přepnout přichycení
editing-expand = Rozbalit
editing-collapse = Sbalit
editing-expand-field = Rozbalit pole
editing-collapse-field = Sbalit pole
editing-underline-text = Podtržený text
editing-unordered-list = Odrážkový seznam
editing-warning-cloze-deletions-will-not-work = Pozor, doplňovačky nebudou fungovat, dokud nezměníte typ výše na Doplňovačku.
editing-mathjax-preview = Náhled MathJax
editing-shrink-images = Zmenšit obrázky
editing-close-html-tags = Automaticky uzavírat HTML tagy
editing-from-clipboard = Ze schránky
editing-alignment = Zarovnání
editing-equations = Rovnice
editing-no-image-found-on-clipboard = Ve schránce nenalezen žádný obrázek.
editing-image-occlusion-mode = Režim okluze obrázku
editing-image-occlusion-zoom-out = Oddálit
editing-image-occlusion-zoom-in = Přiblížit
editing-image-occlusion-zoom-reset = Resetovat přiblížení
editing-image-occlusion-toggle-translucent = Přepnout průhlednost
editing-image-occlusion-delete = Odstranit
editing-image-occlusion-duplicate = Duplikovat
editing-image-occlusion-group = Seskupit výběr
editing-image-occlusion-ungroup = Zrušit seskupení výběru
editing-image-occlusion-select-all = Vybrat vše
editing-image-occlusion-alignment = Zarovnání
editing-image-occlusion-align-left = Zarovnat vlevo
editing-image-occlusion-align-h-center = Zarovnat vodorovně na střed
editing-image-occlusion-align-right = Zarovnat vpravo
editing-image-occlusion-align-top = Zarovnat nahoru
editing-image-occlusion-align-v-center = Zarovnat svisle na střed
editing-image-occlusion-align-bottom = Zarovnat dolů
editing-image-occlusion-select-tool = Vybrat
editing-image-occlusion-zoom-tool = Zoom
editing-image-occlusion-rectangle-tool = Pravoúhelník
editing-image-occlusion-ellipse-tool = Elipsa
editing-image-occlusion-polygon-tool = Polygon
editing-image-occlusion-text-tool = Text
editing-image-occlusion-fill-tool = Vyplnit barvou
editing-image-occlusion-toggle-mask-editor = Přepnout editor masky
editing-image-occlusion-reset = Resetovat okluzi obrázku
editing-image-occlusion-confirm-reset = Jste ji jistí, že chcete resetovat okluzi tohoto obrázku?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML editor
