qt-misc-addon-will-be-installed-when-a = Հավելումը տեղադրվելու է հատկագիրը բացելուն պես:
qt-misc-addons = Հավելումներ
qt-misc-all-cards-notes-and-media-for = Այս հատկագրի բոլոր քարտերը, գրառումները և մեդիանիշքերը ջնջվելու են: Վստա՞հ եք:
qt-misc-anki-updatedanki-has-been-released = <h1>Anki-ն արդիացվեց</h1>Թողարկվել է Anki { $val }:<br><br>
qt-misc-automatic-syncing-and-backups-have-been = Վերականգնելու ընթացքում ինքնաշխատ համաժամեցումը և պահուստավորումը անջատվել են: Նրանք կրկին միացնելու համար փակեք հատկագիրը կամ վերամեկնարկեք Anki-ն:
qt-misc-backing-up = Պահուստավորվում է...
qt-misc-browse = Զննել
qt-misc-change-note-type-ctrlandn = Փոխել գրառման տեսակը (Ctrl+N)
qt-misc-check-the-files-in-the-media = Ստուգել նիշքերը մեդիայի գրացուցակում
qt-misc-choose-deck = Ընտրել կապուկը
qt-misc-choose-note-type = Ընտրել գրառման տեսակը
qt-misc-closing = Փակվում է...
qt-misc-configure-interface-language-and-options = Կազմաձևել միջերեսի լեզուն և ընտրանքները
qt-misc-copy-to-clipboard = Պատճենել սեղմատախտակի մեջ
qt-misc-create-filtered-deck = Ստեղծել զտված կապուկ...
qt-misc-debug-console = Վրիպազերծման կառավարակետ
qt-misc-deck-will-be-imported-when-a = Կապուկը ներմուծվելու է հատկագիրը բացելուն պես
qt-misc-default = Սկզբնադիր
qt-misc-empty-cards = Դատարկ քարտեր...
qt-misc-error-during-startup = Մեկնարկման սխալ՝ { $val }
qt-misc-filtered-deck = Զտված կապուկ { $val }
qt-misc-ignore-this-update = Անտեսել այս արդիացումը
qt-misc-in-order-to-ensure-your-collection = Որպեսզի համոզվեք հավաքածուի ճիշտ աշխատանքի մեջ սարքերի միջև տեղափոխելիս, Anki-ին հարկավոր է, որ համակարգչի ներքին ժամացույցը ճիշտ լինի: Ներքին ժամացույցը կարող է սխալ լինել անգամ եթե համակարգը տեղական ժամը ճիշտ է ցույց տալիս:   Բացեք Ձեր համակարգչի ժամի կարգավորումների պատուհանը և ստուգեք հետևյալը՝  - AM/PM - Ժամի հոսընթացը - Ժամային գոտին - ամառային ժամը  Ժամը ճշտելու տարբերությունը՝ { $val }:
qt-misc-invalid-property-found-on-card-please = Քարտի վրա անվավեր հատկություն է հայտնաբերվել: Օգտագործեք Գործիքներ>Ստուգել շտեմարանը, եթե խնդիրը կրկնվի, ապա հարց ուղղեք օժանդակման կայքէջում:
qt-misc-loading = Բեռնվում է...
qt-misc-manage = Կարգավորել
qt-misc-manage-note-types = Գրառումների տեսակները
qt-misc-name-exists = Անվանումը գոյություն ունի:
qt-misc-non-unicode-text = <ոչ-unicode գրվածք>
qt-misc-optimizing = Լավարկում...
qt-misc-please-connect-a-microphone-and-ensure = Միացրեք խոսափողը և համոզվեք, որ այլ ծրագրերը չեն օգտագործում ձայնային սարքը:
qt-misc-please-ensure-a-profile-is-open = Համոզվեք, որ հատկագիրը բաց է, Anki-ն զբաղված չէ և կրկին փորձեք:
qt-misc-please-select-1-card = (ընտրեք 1 քարտ)
qt-misc-please-select-a-deck = Ընտրեք կապուկը:
qt-misc-please-use-fileimport-to-import-this = Օգտագործեք Նիշք>Ներմուծել այս նիշքը ներմուծելու համար:
qt-misc-processing = Մշակում...
qt-misc-replace-your-collection-with-an-earlier = Փոխարինե՞լ Ձեր հավաքածուն ավելի վաղ պահուստով:
qt-misc-resume-now = Շարունակել հիմա
qt-misc-revert-to-backup = Հետադարձել պահուստին
qt-misc-reverted-to-state-prior-to = Հետադարձել մինչև '{ $val }' կարգավիճակին:
qt-misc-segoe-ui = "Segoe UI"
qt-misc-shift-key-was-held-down-skipping = Shift ստեղնը սեղմված էր: Բաց է թողնվում ինքնաշխատ համաժամեցումը և հավելումների բեռնումը:
qt-misc-shortcut-key-left-arrow = Ստեղնաշարի ստեղնը՝ Ձախ սլաք
qt-misc-shortcut-key-right-arrow-or-enter = Ստեղնաշարի ստեղնը՝ Աջ սլաք կամ Enter
qt-misc-stats = Վիճակագրություն
qt-misc-study-deck = Սովորել կապուկը...
qt-misc-sync = Համաժամեցում
qt-misc-target-deck-ctrlandd = Թիրախային կապուկ (Ctrl+D)
qt-misc-the-following-character-can-not-be = Հետևյալ գրանշանը չի կարող օգտագործվել՝ { $val }
qt-misc-the-requested-change-will-require-a = Հարցվող գործողությունը կպահանջի տվյալների շտեմարանի վերբեռնում հաջորդ համաժամեցման ժամանակ: Այլ սարքերում կատարված ու չհամաժամեցված փոփոխությունները (կրկնություններ ևն) կկորչեն: Շարունակե՞լ:
qt-misc-there-must-be-at-least-one = Պետք է լինի առնվազն մեկ հատկագիր:
qt-misc-this-file-exists-are-you-sure = Այս նիշքը արդեն գոյություն ունի: Վստա՞հ եք, որ ուզում եք վերագրել այն:
qt-misc-unable-to-access-anki-media-folder = Չի հաջողվում մատչել Anki-ի մեդիա պանակը: Հնարավոր է, որ համակարգի ընթացիկ պանակի թույլտվությունները սխալ են:
qt-misc-unable-to-move-existing-file-to = Չհաջողվեց տեղափոխել առկա նիշքը աղբարկղի մեջ: Փորձեք վերամեկնարկել համակարգիչը:
qt-misc-undo = Հետարկում
qt-misc-undo2 = Հետարկել՝ { $val }
qt-misc-unexpected-response-code = Պատասխանի անսպասելի կոդ՝ { $val }
qt-misc-waiting-for-editing-to-finish = Սպասում է խմբագրության ավարտին:
qt-misc-would-you-like-to-download-it = Կուզե՞ք հիմա ներբեռնել այն:
qt-misc-your-collection-file-appears-to-be = Ձեր հավաքածուի նիշքը վնասված է: Պատճառը կարող է լինել Anki-ն բաց լինելու ժամանակ նիշքի պատճենումը կամ տեղափոխումը, նաև հավաքածուի ցանցային կամ ամպային հիշասարքում պահվելը: Եթե համակարգիչը վերագործարկելուց հետո խնդիրները չեն անհետանում, ապա բացեք ինքնաշխատ պահուստը հատկագրի էկրանից:
qt-misc-your-firewall-or-antivirus-program-is = Ձեր հրապատը կամ հակավիրուսային ծրագիրը չեն թողնում Anki-ին միացում հաստատել: Anki-ի համար բացառություն ավելացրեք այդ ծրագրերում:
qt-misc-second = { $count ->
    [one] { $count } վայրկյանում
   *[other] { $count } վայրկյանում
  }
