#!/bin/bash
#
# build mo files
#
set -eo pipefail

targetDir="../aqt_data/locale/gettext"
mkdir -p $targetDir

echo "Compiling *.po..."
for file in po/desktop/*/anki.po
do
    echo "Building '$file'"
    outdir=$(echo "$file" | \
        perl -pe "s%po/desktop/(.*)/anki.po%$targetDir/\1/LC_MESSAGES%")
    outfile="$outdir/anki.mo"
    mkdir -p $outdir
    mergedfile="$(msgmerge -q "$file" po/desktop/anki.pot)"
    printf '%s' "$mergedfile" | msgfmt - --output-file="$outfile" \
        || (error=$? \
            && printf '%s' "$mergedfile" > "$file.error" \
            && printf 'See the file "%s" to find the error line number just showed!\n' "$file.error" \
            && exit $error)
done
