#!/bin/bash
#
# build mo files
#
set -eo pipefail

targetDir="../aqt_data/locale/gettext"
mkdir -p $targetDir

echo "Compiling *.po..."
for file in po/desktop/*/anki.po
do
    outdir=$(echo "$file" | \
        perl -pe "s%po/desktop/(.*)/anki.po%$targetDir/\1/LC_MESSAGES%")
    outfile="$outdir/anki.mo"
    mkdir -p $outdir
    msgmerge --for-msgfmt "$file" po/desktop/anki.pot | msgfmt - --output-file="$outfile"
done
