#!/bin/bash

set -eo pipefail

out=../aqt_data/locale/qt
mkdir -p $out

qtTranslations=$(python -c "from PyQt5.QtCore import *; print(QLibraryInfo.location(QLibraryInfo.TranslationsPath))")
rsync -a $qtTranslations/qt* $out
