#!/bin/bash
#
# update translation files
#

all=all.files
echo "Updating anki.pot..."
for i in ../anki-lib-python/anki/{*.py,importing/*.py,template/*.py}; do
    echo $i >> $all
done
for i in ../anki-qt/aqt/{*.py,forms/*.py}; do
    echo $i >> $all
done

xgettext -cT: -s --no-wrap --files-from=$all --output=anki.pot
rm $all
