#!/bin/bash
#
# update translation files
#


topDir=$(dirname $0)/../..
cd $topDir

all=all.files
echo "Updating anki.pot..."
for i in pylib/anki/{*.py,importing/*.py}; do
    echo $i >> $all
done
for i in qt/aqt/{*.py,forms/*.py}; do
    echo $i >> $all
done

xgettext -cT: -s --no-wrap --files-from=$all --output=qt/i18n/anki.pot
rm $all
