#!/usr/bin/env python

import os, sys
if __name__ == "__main__":
    try:
        modDir=os.path.dirname(os.path.realpath(__file__))
        runningDir=os.path.split(modDir)[0]
    except NameError:
        # py2exe
        runningDir=os.path.dirname(sys.argv[0])
        modDir=runningDir
    sys.path.insert(0, os.path.join(modDir, "libanki"))
    sys.path.insert(0, os.path.join(os.path.join(modDir, ".."), "libanki"))
    import aqt
    try:
        import aqt.forms
    except ImportError, e:
        if "aqt.forms" in str(e):
            print "If you're running from git, did you run build_ui.sh?"
            print
        raise
    aqt.run()
