#!/bin/bash

set -e

. scripts.inc

rm -rf dist

for dir in $DEVEL; do
  echo $dir
  (cd $dir && make build BUILDFLAGS="$BUILDFLAGS")
done

# add build hash to outputs
ver=$(cat meta/version)
hash=$(cat meta/buildhash)
(cd dist && rename "s/$ver/${ver}+$hash/" *.whl)
