#!/bin/bash

set -e

. scripts.inc

# install prereqs before checking
for dir in $DEVEL; do
    echo $dir
    (cd $dir && make develop BUILDFLAGS="$BUILDFLAGS")
done    

for dir in $CHECKABLE; do
  echo $dir
  (cd $dir && make check)
done
