sonar.projectKey=ankitects_anki
sonar.organization=ankitects
sonar.projectVersion=0.1

sonar.sources=pylib/anki,qt/aqt,qt/tools,ts,rslib,tools
sonar.tests=pylib/tests,qt/tests,tools/tests
sonar.exclusions=out/**,target/**,node_modules/**,**/generated/**,**/*.sql,extra/**

sonar.python.version=3.10
sonar.python.coverage.reportPaths=\
    out/coverage/python-pylib/coverage.xml,\
    out/coverage/python-qt/coverage.xml

sonar.javascript.lcov.reportPaths=out/coverage/typescript/lcov.info

sonar.rust.lcov.reportPaths=out/coverage/rust/lcov.info
