sonar.projectKey=ankitects_anki
sonar.organization=ankitects

sonar.sources=pylib,qt,ts,rslib
sonar.exclusions=out/**,target/**,node_modules/**,**/generated/**

sonar.python.version=3.11
sonar.python.coverage.reportPaths=\
    out/coverage/python-pylib/coverage.xml,\
    out/coverage/python-qt/coverage.xml

sonar.javascript.lcov.reportPaths=out/coverage/typescript/lcov.info

sonar.rust.coverage.reportPaths=out/coverage/rust/lcov.info