qt-accel-about = 정보(&A)...
qt-accel-cards = 카드(&C)
qt-accel-check-database = 데이터베이스 검사(&C)
qt-accel-check-media = 미디어 검사(&M)...
qt-accel-edit = 편집(&E)
qt-accel-exit = 종료(&X)
qt-accel-export = 내보내기(&E)...
qt-accel-export-notes = &노트 내보내기
qt-accel-file = 파일(&F)
qt-accel-filter = 필터(&T)
qt-accel-find = 찾기(&F)
qt-accel-find-and-replace = 찾기 및 바꾸기(&P)...
qt-accel-find-duplicates = 중복된 항목 찾기(&D)...
qt-accel-go = 이동(&G)
qt-accel-guide = 안내서(&G)...
qt-accel-help = 도움말(&H)
qt-accel-import = 가져오기(&I)...
qt-accel-info = 정보(&I)
qt-accel-invert-selection = 선택 항목 반전(&I)
qt-accel-next-card = 다음 카드(&N)
qt-accel-note = 노트(&O)
qt-accel-notes = 노트(&N)
qt-accel-preferences = 환경 설정(&P)...
qt-accel-previous-card = 이전 카드(&P)
qt-accel-select-all = 전체 선택(&A)
qt-accel-select-notes = 노트 선택(&N)
qt-accel-support-anki = Anki 후원(&S)...
qt-accel-switch-profile = 프로필 전환(&S)
qt-accel-tools = 도구(&T)
qt-accel-undo = 실행 취소(&U)
qt-accel-redo = 다시 실행(&R)
qt-accel-set-due-date = 만기 설정(&D)
qt-accel-forget = 초기화(&F)
qt-accel-view = &뷰
qt-accel-full-screen = 전체 화면으로 전환(&F)
qt-accel-layout = &레이아웃
qt-accel-layout-auto = &자동
qt-accel-layout-vertical = &세로
qt-accel-layout-horizontal = &가로
qt-accel-zoom-in = 확대(&I)
qt-accel-zoom-out = 축소(&O)
qt-accel-reset-zoom = 원본 비율 보기(&R)
qt-accel-zoom-editor-in = 편집기 줌 &인
qt-accel-zoom-editor-out = 편집기 줌 &아웃
qt-accel-create-backup = 백업하기(&B)
qt-accel-load-backup = &백업으로 복원
