#!/bin/bash

set -e

rm -rf bazel-dist
bazel build -c opt dist --symlink_prefix=bazel-docker/links/ \
    --experimental_no_product_name_out_symlink
tar xvf bazel-docker/links/bin/dist.tar
if [ "$PACKAGE" != "" ]; then
    (cd qt/package && ./build.sh)
fi
bazel shutdown
