#!/bin/bash

set -e

rm -rf bazel-dist
bazel --output_user_root=bazel-docker/root \
    build -c opt dist --symlink_prefix=bazel-docker/links/ \
    --experimental_no_product_name_out_symlink
tar xvf bazel-docker/links/bin/dist.tar
bazel --output_user_root=bazel-docker/root shutdown
