importing-failed = आयात अपयशी राहिले.
importing-allow-html-in-fields = फील्डांमध्ये एचटीएमएल अनुमत करा
importing-appeared-twice-in-file = फाईलमध्ये दोनदा आढळलं: { $val }
importing-by-default-anki-will-detect-the = मुलभूत मघ्ये, आन्की रकाना ते रकाना मधील टॅब, स्वल्पविराम वगैरे सारख्या अक्षराचा तपास लावेल. जर आन्की त्या अक्षराला चुकीच्या पद्धतीने तपास लावत असेल तर ते आपण इथे प्रविष्ट करु शकतात. टॅब दर्शित करण्यासाठी \t वापरा.
importing-change = बदलवा
importing-colon = अपूर्णविराम
importing-comma = स्वल्पविराम
importing-field-mapping = रकाना मांडणे
importing-field-of-file-is = फाइल मधील <b>{ $val }</b> रकाना आहे:
importing-ignored = <दुर्लक्ष केले>
importing-import-options = पर्याय आयात करा
importing-map-to = { $val } ला मांडा
importing-map-to-tags = टॅगना मांडा
importing-mapped-to = <b>{ $val }</b> ला मांडले
importing-mapped-to-tags = <b>टॅग</b>ना मांडले
importing-rows-had-num1d-fields-expected-num2d = '{ $row }' मध्ये { $found } रकाने होते, { $expected } अपेक्षीत होते
importing-supermemo-xml-export-xml = सुपरमेमो एक्सएमएल निर्यात (*.xml)
importing-added = जोडले
