[package]
name = "anki_io"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true
description = "Utils for better I/O error reporting"

[dependencies]
camino.workspace = true
snafu.workspace = true
tempfile.workspace = true
