qt-accel-about = &Про Anki
qt-accel-about-mac = Про Anki...
qt-accel-cards = &Картки
qt-accel-check-database = &Перевірити базу даних
qt-accel-check-media = Перевірити &медіа-файли...
qt-accel-edit = &Редагування
qt-accel-exit = &Вихід
qt-accel-export = &Експортувати...
qt-accel-export-notes = &Експортування нотаток…
qt-accel-file = &Файл
qt-accel-filter = Фільl&тр
qt-accel-find = &Знайти
qt-accel-find-and-replace = &Знайти і замінити...
qt-accel-find-duplicates = Пошук &дублікатів...
qt-accel-go = &Перейти
qt-accel-guide = &Довідник...
qt-accel-help = &Допомога
qt-accel-import = &Імпортувати…
qt-accel-info = &Інфо...
qt-accel-invert-selection = &Інвертувати вибір
qt-accel-next-card = &Наступна Картка
qt-accel-note = Н&отатка
qt-accel-notes = &Нотатки
qt-accel-preferences = &Параметри...
qt-accel-previous-card = &Попередня картка
qt-accel-select-all = &Виділити все
qt-accel-select-notes = Вибрати &нотатки
qt-accel-support-anki = &Підтримати Anki...
qt-accel-switch-profile = &Змінити профіль
qt-accel-tools = &Інструменти
qt-accel-undo = &Скасувати
qt-accel-redo = &Повернути
qt-accel-set-due-date = Встановити дату &пригадування
qt-accel-forget = &Забути
qt-accel-view = &Вигляд
qt-accel-full-screen = &Повний екран
qt-accel-layout = Розкладка&
qt-accel-layout-auto = &Автоматично
qt-accel-layout-vertical = &Вертикальна
qt-accel-layout-horizontal = &Горизонтальна
qt-accel-zoom-in = При&близити
qt-accel-zoom-out = &Віддалити
qt-accel-reset-zoom = &Звичайний маштаб
qt-accel-toggle-sidebar = Перемкнути бічну панель
qt-accel-zoom-editor-in = Збі&льшити масштаб у редакторі
qt-accel-zoom-editor-out = Зме&ншити масштаб у редакторі
qt-accel-create-backup = Створити &резервну копію
qt-accel-load-backup = Повернутися до резервної копії
qt-accel-upgrade-downgrade = Оновлення/Відновлення
