qt-accel-about = &Тухай
qt-accel-about-mac = Anki-гийн тухай...
qt-accel-cards = &Хөзрүүд
qt-accel-edit = &Засварлах
qt-accel-exit = &Гарах
qt-accel-export = &Экспортлох...
qt-accel-file = &Файл
qt-accel-filter = &Шүүх
qt-accel-find = &Хайх
qt-accel-find-and-replace = &Хайжгаад орлуулах...
qt-accel-go = &Очих
qt-accel-guide = &Гарын авлага
qt-accel-help = &Тусламж
qt-accel-import = &Импорт
qt-accel-info = &Мэдээлэл
qt-accel-invert-selection = &Сонголтыг чанх эсрэг
qt-accel-next-card = &Дараагийн карт
qt-accel-previous-card = &Өмнөх карт
qt-accel-select-all = &Бүгдийг сонго
qt-accel-support-anki = &Anki-г дэмжих
qt-accel-switch-profile = &Профайл солих
qt-accel-tools = &Хэрэгсэлүүд
qt-accel-undo = &Буцаах
qt-accel-redo = &Дахин хийх
qt-accel-forget = &Тохируулах
qt-accel-layout-auto = &Авто
qt-accel-upgrade-downgrade = Шинэчлэх/Бууруулах
