adding-add-shortcut-ctrlandenter = قوش (قىسقا يول: ctrl+enter)
adding-added = قوشۇلدى
adding-discard-current-input = ھازىر كىرگۈزگەننى تاشلىۋېتەمدۇ؟
adding-keep-editing = تەھرىرلەشنى داۋاملاشتۇر
adding-edit = تەھرىر «{ $val }»
adding-history = تارىخ
adding-note-deleted = (خاتىرە ئۆچۈرۈلدى)
adding-shortcut = قىسقا يول: { $val }
adding-the-first-field-is-empty = تۇنجى بۆلەك بوش.
adding-you-have-a-cloze-deletion-note = سىز بوش ئورۇن تولدۇرۇش خاتىرە تۈرىنى ئىشلىتىۋاتىسىز ئەمما بوشلۇقنى تەڭشىمىدىڭىز. داۋاملاشتۇرامدۇ؟
adding-cloze-outside-cloze-notetype = پەقەت بوش ئورۇن تولدۇرۇش خاتىرە تۈرىدە بوشلۇق تەڭشىگىلى بولىدۇ.
adding-cloze-outside-cloze-field = پەقەت «cloze:» سۈزگۈچى بار بۆلەكتە  بوشلۇق تەڭشىگىلى بولىدۇ. ئادەتتە تۇنجى سۆز بۆلىكى.
