[package]
name = "makeapp"
publish = false

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.70"
apple-bundles = "0.17.0"
camino = "1.1.4"
clap = { version = "4.2.1", features = ["derive"] }
glob = "0.3.1"
lazy_static = "1.4.0"
plist = "1.4.3"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
simple-file-manifest = "0.11.0"
walkdir = "2.3.3"
workspace-hack = { version = "0.1", path = "../../../tools/workspace-hack" }
