[package]
name = "makeapp"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
apple-bundles.workspace = true
camino.workspace = true
clap.workspace = true
glob.workspace = true
plist.workspace = true
serde.workspace = true
serde_json.workspace = true
simple-file-manifest.workspace = true
walkdir.workspace = true
