[package]
edition = "2021"
name = "makeapp"
version = "0.1.0"
authors = ["Ankitects Pty Ltd and contributors"]
license = "AGPL-3.0-or-later"

[dependencies]
anyhow = "1.0.53"
glob = "0.3.0"
plist = "1.3.1"
walkdir = "2.3.2"
apple-bundles= "0.6.0"
tugger-file-manifest= "0.6.0"
lazy_static = "1.4.0"
