editing-actual-size = Przełącz rzeczywisty rozmiar
editing-add-media = Dodaj pliki
editing-align-left = Wyrównaj do lewej
editing-align-right = Wyrównaj do prawej
editing-an-error-occurred-while-opening = Wystąpił błąd przy otwieraniu { $val }
editing-attach-picturesaudiovideo = Dołącz obraz/audio/wideo
editing-bold-text = Pogrubienie
editing-cards = Karty
editing-center = Wycentrowanie
editing-change-color = Zmień kolor
editing-cloze-deletion = Luka (nowa karta)
editing-cloze-deletion-repeat = Luka (ta sama karta)
editing-copy-image = Kopiuj obraz
editing-couldnt-record-audio-have-you-installed = Nie można nagrać dźwięku. Czy masz zainstalowany program "lame"?
editing-customize-card-templates = Dostosuj szablony kart
editing-customize-fields = Dostosuj pola
editing-cut = Wytnij
editing-double-click-image = podwójne kliknięcie grafiki
editing-double-click-to-expand = podwójne kliknięcie rozwija
editing-double-click-to-collapse = podwójne kliknięcie zwija
editing-edit-current = Edytuj aktualną
editing-edit-html = Edytuj HTML
editing-fields = Pola
editing-float-left = Opływanie z lewej
editing-float-right = Opływanie z prawej
editing-float-none = Bez opływania
editing-indent = Zwiększ wcięcie
editing-italic-text = Pochylenie
editing-jump-to-tags-with-ctrlandshiftandt = Przeskocz do tagów, wciskając Ctrl+Shift+T
editing-justify = Wyjustowanie
editing-latex = LaTeX
editing-latex-equation = Równanie LaTeX
editing-latex-math-env = Środowisko matematyczne LaTeX
editing-mathjax-block = Blok MathJax
editing-mathjax-chemistry = Chemia MathJax
editing-mathjax-inline = Liniowy MathJax
editing-mathjax-placeholder = Naciśnij { $accept }, aby zaakceptować oraz { $newline }, aby przejść do nowej linii.
editing-media = Pliki
editing-open-image = Otwórz obraz
editing-show-in-folder = Pokaż w folderze
editing-ordered-list = Lista uporządkowana
editing-outdent = Zmniejsz wcięcie
editing-paste = Wklej
editing-record-audio = Nagraj dźwięk
editing-remove-formatting = Usuń formatowanie
editing-restore-original-size = Przywróć oryginalny rozmiar
editing-select-remove-formatting = Wybierz formatowanie do usunięcia
editing-show-duplicates = Pokaż duplikaty
editing-subscript = Indeks dolny
editing-superscript = indeks górny
editing-tags = Tagi
editing-tags-add = Dodaj tag
editing-tags-copy = Kopiuj tagi
editing-tags-remove = Usuń tagi
editing-tags-select-all = Zaznacz wszystkie tagi
editing-text-color = Kolor tekstu
editing-text-highlight-color = Kolor zaznaczenia tekstu
editing-to-make-a-cloze-deletion-on = Aby wprowadzić wypełnianie luk do istniejącej notatki, musisz zmienić jej typ na lukę poprzez Notatki>Zmień typ notatki
editing-toggle-html-editor = Przełącz edytor HTML
editing-toggle-visual-editor = Przełącz edytor wizualny
editing-toggle-sticky = Przełącz przyklejenie
editing-expand = Rozwiń
editing-collapse = Zwiń
editing-expand-field = Rozwiń pole
editing-collapse-field = Zwiń pole
editing-underline-text = Podkreślenie
editing-unordered-list = Lista nieuporządkowana
editing-warning-cloze-deletions-will-not-work = Uwaga: wypełnianie luk nie będzie działać, jeśli nie ustawisz typu na górze na Luka.
editing-mathjax-preview = Podgląd kodu MathJax
editing-shrink-images = Zmniejsz obrazy
editing-close-html-tags = Automatycznie domykaj tagi HTML
editing-from-clipboard = Ze schowka
editing-alignment = Wyrównanie
editing-equations = Równania
editing-no-image-found-on-clipboard = W schowku nie ma obrazka.
editing-image-occlusion-mode = Tryb zakrycia obrazu
editing-image-occlusion-zoom-out = Pomniejsz
editing-image-occlusion-zoom-in = Powiększ
editing-image-occlusion-zoom-reset = Domyślne powiększenie
editing-image-occlusion-toggle-translucent = Przełącz przezroczystość
editing-image-occlusion-delete = Usuń
editing-image-occlusion-duplicate = Duplikuj
editing-image-occlusion-group = Grupuj zaznaczone
editing-image-occlusion-ungroup = Oddziel zaznaczone od grupy
editing-image-occlusion-select-all = Zaznacz wszystko
editing-image-occlusion-alignment = Wyrównanie
editing-image-occlusion-align-left = Wyrównanie do lewej
editing-image-occlusion-align-h-center = Wyrównanie środkowych osi poziomo
editing-image-occlusion-align-right = Wyrównanie do prawej
editing-image-occlusion-align-top = Wyrównanie do góry
editing-image-occlusion-align-v-center = Wyrównanie środkowych osi pionowo
editing-image-occlusion-align-bottom = Wyrównanie do dołu
editing-image-occlusion-select-tool = Zaznaczenie
editing-image-occlusion-zoom-tool = Powiększenie
editing-image-occlusion-rectangle-tool = Prostokąt
editing-image-occlusion-ellipse-tool = Elipsa
editing-image-occlusion-polygon-tool = Wielokąt
editing-image-occlusion-text-tool = Tekst
editing-image-occlusion-fill-tool = Wypełnij kolorem
editing-image-occlusion-toggle-mask-editor = Przełącz edytor maski
editing-image-occlusion-reset = Resetuj zakrycie obrazu
editing-image-occlusion-confirm-reset = Czy na pewno chcesz zresetować te zakrycie obrazu?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Edytor HTML
