card-stats-added = Bygevoeg
card-stats-first-review = Eerste hersienning
card-stats-latest-review = Laaste hersienning
card-stats-ease = Gemak
card-stats-review-count = Hersienings
card-stats-lapse-count = Vervalle
card-stats-average-time = Gemiddelde Tyd
card-stats-total-time = Totale Tyd
card-stats-new-card-position = Posisie
card-stats-card-template = Tipe kaart
card-stats-note-type = Tipe Nota
card-stats-deck-name = Kaartpak
card-stats-note-id = Kaart ID
card-stats-card-id = Kaart ID
card-stats-review-log-rating = Gradering
card-stats-review-log-type = Tipe
card-stats-review-log-date = Datum
card-stats-review-log-time-taken = Tyd
card-stats-review-log-type-learn = Leer
card-stats-review-log-type-review = Hersien
card-stats-review-log-type-relearn = Herleer
card-stats-review-log-type-filtered = Gefiltreer
card-stats-review-log-type-rescheduled = Herskeduleer
