preferences-automatically-sync-on-profile-openclose = Sinchroniseer outomaties sodra die profiel oop of toegemaak word
preferences-backups = Rugsteun afskrifte
preferences-backups2 = gerugsteunde
preferences-backupsanki-will-create-a-backup-of = <b>Rugsteen kopies</b><br>Anki sal rugsteen afskrifte van jou versameling maak elke keer wanneer dit toegemaak word of gesinchroniseer word.
preferences-basic = Basies
preferences-change-deck-depending-on-note-type = Verander kaartpak, afhangende van die nota tipe
preferences-hours-past-midnight = ure na middernag
preferences-interface-language = Koppelvlak taal:
preferences-keep = Hou
preferences-learn-ahead-limit = Leer vooruit beperking
preferences-mins = minute
preferences-network = Netwerk
preferences-next-day-starts-at = Volgende dag begin om
preferences-note-media-is-not-backed-up = Nota: Media is nie gerugsteun nie. Skep 'n rugsteun kopie van jou Anki gids om veilig te wees.
preferences-on-next-sync-force-changes-in = Op volgende sinkronisasie, forseer veranderinge in een rigting.
preferences-paste-clipboard-images-as-png = Plak die knipbord beelde as PNG
preferences-please-restart-anki-to-complete-language = Om die taalkeuse te voltooi, moet Anki oorbegin.
preferences-preferences = Voorkeure
preferences-scheduling = Herskeduleer
preferences-show-next-review-time-above-answer = Toon volgende hersienning tyd bo die antwoord knoppies
preferences-show-remaining-card-count-during-review = Wys oorblywende kaart telling tydens hersienning
preferences-some-settings-will-take-effect-after = Sommige instellings sal in werking tree nadat jy Anki oorbegin.
preferences-synchronisation = <b>Sinchronisasie/b
preferences-synchronizationnot-currently-enabled-click-the-sync = <b> Synchronisasie </ b> <br>   Nie tans geaktiveer nie, kliek op die sync knoppie in die hoof venster om dit te aktiveer.
preferences-synchronize-audio-and-images-too = Sinchroniseer klank en beelde ook
preferences-timebox-time-limit = Gekose tyd limit
preferences-when-adding-default-to-current-deck = Wanneer jy bygevoeg, sal die kaartpak na standaard toe skuif.
