actions-add = ᱥᱮᱞᱮᱫᱽ ᱢᱮ
actions-all-selected = ᱡᱷᱚᱛᱚ ᱵᱟᱪᱷᱟᱣᱮᱱᱟ
actions-any-selected = ᱡᱟᱦᱟᱸ ᱵᱟᱪᱷᱟᱣᱟᱜ ᱜᱮ
actions-cancel = ᱵᱟᱹᱰᱨᱟᱹ
actions-choose = ᱵᱟᱪᱷᱟᱣ
actions-close = ᱵᱚᱸᱫᱚᱭ ᱢᱮ
actions-copy = ᱱᱚᱠᱚᱞ ᱢᱮ
actions-create-copy = ᱱᱚᱠᱚᱞ ᱛᱮᱭᱟᱨ ᱢᱮ
actions-custom-study = ᱱᱤᱡᱮᱛᱮ ᱯᱟᱲᱦᱟᱣ
actions-decks = ᱰᱮᱠᱥ
actions-delete = ᱢᱮᱴᱟᱣ ᱢᱮ
actions-export = ᱠᱩᱞ ᱢᱮ
actions-filter = ᱪᱷᱟᱹᱱᱤ
actions-help = ᱜᱚᱲᱚ
actions-import = ᱟᱹᱜᱩ
actions-manage = ᱥᱚᱢᱵᱷᱲᱟᱣ...
actions-name = ᱧᱩᱛᱩᱢ :
actions-new = ᱱᱟᱶᱟ
actions-new-name = ᱱᱟᱶᱟ ᱧᱩᱛᱩᱢ:
actions-options = ᱟᱯᱱᱟᱨ ᱢᱚᱱᱮ ᱛᱮᱭᱟᱜ ᱠᱚ
actions-options-for = { $val } ᱞᱟᱹᱜᱤᱫ ᱢᱚᱱᱮ ᱛᱮᱭᱟᱜ
actions-preview = ᱧᱮᱞ ᱵᱤᱲᱟᱹᱣ
actions-rebuild = ᱫᱩᱦᱲᱟᱹ ᱛᱮᱭᱟᱨ
actions-rename = ᱫᱚᱦᱲᱟ ᱧᱩᱛᱩᱢ
actions-rename-deck = ᱰᱮᱠ ᱟ ᱧᱩᱛᱩᱢ ᱵᱚᱫᱚᱞ‌ ᱢᱮ
actions-rename-tag = ᱴᱮᱜᱼᱟᱜ ᱧᱩᱛᱩᱢ ᱵᱚᱫᱚᱞ‌ ᱢᱮ
actions-rename-with-parents = ᱥᱟᱹᱛᱷᱤ ᱠᱚ ᱥᱟᱶ ᱧᱩᱛᱩᱢ ᱵᱚᱫᱚᱞ ᱢᱮ
actions-remove-tag = ᱴᱮᱜᱽ ᱚᱪᱚᱜᱽ ᱢᱮ
actions-replay-audio = ᱥᱟᱰᱮ ᱫᱩᱦᱲᱟᱹ ᱮᱢ ᱢᱮ
actions-reposition = ᱡᱟᱭᱜᱟ ᱵᱚᱫᱚᱞ ᱢᱮ
actions-save = ᱥᱟᱺᱪᱟᱣ
actions-search = ᱥᱮᱸᱫᱽᱨᱟ
actions-select = ᱵᱟᱪᱷᱟᱣ ᱢᱮ
actions-shortcut-key = ᱠᱷᱟᱴᱚᱢᱟᱪᱷᱟ ᱪᱟᱹᱵᱤ: { $val }
actions-suspend-card = ᱠᱟᱰ ᱵᱚᱸᱫᱚᱭ ᱢᱮ
actions-set-due-date = ᱵᱤᱱᱤᱰ ᱢᱟᱹᱦᱤᱛ ᱥᱟᱹᱛ ᱢᱮ
actions-answer-card = ᱛᱮᱞᱟ ᱠᱟᱰ
actions-unbury-unsuspend = ᱛᱚᱯᱟ ᱚᱰᱚᱠ ᱢᱮ/ᱠᱷᱩᱞᱟᱹ ᱨᱩᱣᱟᱹᱲ ᱢᱮ
actions-add-deck = ᱰᱮᱠ ᱥᱮᱞᱮᱫᱽᱢᱮ
actions-add-note = ᱱᱚᱴ ᱥᱮᱞᱮᱫᱽ ᱢᱮ
actions-update-tag = ᱴᱮᱜᱽ ᱦᱟᱹᱞᱤᱭᱟᱹᱠ ᱢᱮ
actions-update-note = ᱱᱚᱴ ᱦᱟᱹᱞᱤᱭᱟᱹᱠ ᱢᱮ
actions-update-card = ᱠᱟᱰ ᱦᱟᱹᱞᱤᱭᱟᱹᱠ ᱢᱮ
actions-update-deck = ᱰᱮᱠ ᱦᱟᱹᱞᱤᱭᱟᱹᱠ ᱢᱮ
actions-forget-card = ᱠᱟᱰ ᱦᱤᱲᱤᱧ ᱢᱮ
actions-build-filtered-deck = ᱰᱮᱠ ᱛᱮᱭᱟᱨ ᱢᱮ
actions-add-notetype = ᱱᱚᱴᱯᱨᱚᱠᱟᱨ ᱥᱮᱞᱮᱫᱽ ᱢᱮ
actions-remove-notetype = ᱱᱚᱴᱯᱨᱚᱠᱟᱨ ᱚᱪᱚᱜᱽ ᱢᱮ
actions-update-notetype = ᱱᱚᱴᱯᱨᱚᱠᱟᱨ ᱦᱟᱹᱞᱤᱭᱟᱹᱠ ᱢᱮ
actions-update-config = ᱠᱚᱱᱯᱷᱤᱜᱽ ᱦᱟᱹᱞᱤᱭᱟᱹᱠ ᱢᱮ
actions-card-info = ᱠᱟᱰ ᱵᱟᱵᱚᱛ
actions-previous-card-info = ᱢᱟᱲᱟᱝᱟᱜ ᱠᱟᱰ ᱵᱟᱵᱚᱛ
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = ᱱᱚᱶᱟ ᱠᱟᱹᱢᱤᱦᱚᱨᱟ ᱫᱚ ᱟᱢᱟᱜ ᱥᱤᱥᱴᱚᱢ ᱨᱮ ᱥᱟᱹᱯᱚᱴ ᱵᱟᱹᱱᱩᱜᱼᱟ ᱾

## Flags

actions-flag-number = { $number } ᱯᱚᱛᱠᱟ
actions-flag-red = ᱟᱨᱟᱜ
actions-flag-orange = ᱜᱮᱨᱩᱟ
actions-flag-green = ᱦᱟᱹᱨᱤᱭᱟᱹᱲ
actions-flag-blue = ᱞᱤᱞ
actions-flag-pink = ᱯᱤᱝᱠ
actions-flag-turquoise = ᱦᱟᱹᱨᱤᱭᱟᱹᱲ ᱢᱮᱥᱟ ᱞᱤᱞ
actions-flag-purple = ᱵᱮᱝᱜᱩᱱᱤ
actions-set-flag = ᱯᱚᱛᱠᱟ ᱥᱮᱴ ᱢᱮ
