qt-accel-about = &Аб праграме
qt-accel-about-mac = Аб Anki...
qt-accel-cards = &Карткі
qt-accel-check-database = Праверыць &базу даных
qt-accel-check-media = Праверыць &медыя
qt-accel-edit = &Рэдагаваць
qt-accel-exit = &Выхад
qt-accel-export = &Экспарт...
qt-accel-export-notes = &Экспартаваць нататкі...
qt-accel-file = &Файл
qt-accel-filter = Фі&льтраваць
qt-accel-find = &Знайсці
qt-accel-find-and-replace = Знайсці і за&мяніць...
qt-accel-find-duplicates = Знайсці д&ублікаты...
qt-accel-go = &Перайсці
qt-accel-guide = &Дапаможнік
qt-accel-help = &Даведка
qt-accel-import = &Імпартаваць...
qt-accel-info = З&весткі...
qt-accel-invert-selection = &Інвертаваць выбар
qt-accel-next-card = &Наступная картка
qt-accel-note = На&татка
qt-accel-notes = &Нататкі
qt-accel-preferences = &Параметры
qt-accel-previous-card = &Папярэдняя картка
qt-accel-select-all = Выбраць &усё
qt-accel-select-notes = Выбраць &нататкі
qt-accel-support-anki = &Падтрымаць Anki
qt-accel-switch-profile = &Пераключыць профіль
qt-accel-tools = &Інструменты
qt-accel-undo = &Адрабіць
qt-accel-redo = &Узнавіць
qt-accel-set-due-date = Задаць &тэрмін...
qt-accel-forget = &Забыць
qt-accel-view = В&ыгляд
qt-accel-full-screen = Пераключыць поўны &экран
qt-accel-layout = &Макет
qt-accel-layout-auto = &Аўтаматычна
qt-accel-layout-vertical = &Вертыкальна
qt-accel-layout-horizontal = &Гарызантальна
qt-accel-zoom-in = Па&вялічыць
qt-accel-zoom-out = Па&меншыць
qt-accel-reset-zoom = &Скінуць маштаб
qt-accel-toggle-sidebar = Паказаць/схаваць бакавую панэль
qt-accel-zoom-editor-in = Па&вялічыць рэдактар
qt-accel-zoom-editor-out = Па&меншыць рэдактар
qt-accel-create-backup = С&тварыць рэзервовую копію
qt-accel-load-backup = В&ярнуць да рэзервовай копіі
qt-accel-upgrade-downgrade = Змена версіі Anki
