editing-actual-size = Uključi/isključi stvarnu veličinu
editing-add-media = Dodaj medije
editing-align-left = Poravnaj lijevo
editing-align-right = Poravnaj desno
editing-an-error-occurred-while-opening = Dogodila se greška pri otvaranju { $val }
editing-attach-picturesaudiovideo = Priloži slike/zvuk/video
editing-bold-text = Podebljani tekst
editing-cards = Kartice
editing-center = Sredina
editing-change-color = Promijeni boju
editing-cloze-deletion = Nadopunjavanje (nova kartica)
editing-cloze-deletion-repeat = Nadopunjavanje (ista kartica)
editing-copy-image = Kopiraj sliku
editing-couldnt-record-audio-have-you-installed = Snimanje zvuka nije uspjelo. Jeste li instalirali 'lame'?
editing-customize-card-templates = Prilagodi predloške kartica
editing-customize-fields = Prilagodi polja
editing-cut = Izreži
editing-double-click-image = dupli klik na sliku
editing-double-click-to-expand = dupli klik za proširiti
editing-double-click-to-collapse = dupli klik za sklopiti
editing-edit-current = Uredi trenutnu
editing-edit-html = Uredi HTML
editing-fields = Polja
editing-float-left = Plutanje slijeva
editing-float-right = Plutanje zdesna
editing-float-none = Bez plutanja
editing-indent = Povećaj uvlaku
editing-italic-text = Kurziv
editing-jump-to-tags-with-ctrlandshiftandt = Skoči na oznake s Ctrl+Shift+T
editing-justify = Obostrano
editing-latex = LaTeX
editing-latex-equation = LaTeX jednadžba
editing-latex-math-env = LaTeX math okr.
editing-mathjax-block = MathJax blok
editing-mathjax-chemistry = MathJax za kemiju
editing-mathjax-inline = MathJax inline
editing-mathjax-placeholder = Pritisnite { $accept } da prihvatite, { $newline } za novi redak.
editing-media = Multimedija
editing-open-image = Otvori sliku
editing-show-in-folder = Pokaži u mapi
editing-ordered-list = Poredani popis
editing-outdent = Smanji uvlaku
editing-paste = Zalijepi
editing-record-audio = Snimi zvuk
editing-remove-formatting = Ukloni formatiranje
editing-restore-original-size = Obnovi originalnu veličinu
editing-select-remove-formatting = Odaberite formatiranje koje će se maknuti
editing-show-duplicates = Prikaži duplikate
editing-subscript = Indeks
editing-superscript = Eksponent
editing-tags = Oznake
editing-tags-add = Dodaj oznaku
editing-tags-copy = Kopiraj oznake
editing-tags-remove = Ukloni oznake
editing-tags-select-all = Odaberi sve oznake
editing-text-color = Boja teksta
editing-text-highlight-color = Boja isticanja teksta
editing-to-make-a-cloze-deletion-on = Kako biste dodali nadopunjavanje teksta u postojeću bilješku, prvo je morate pretvoriti u tip bilješke na nadopunjavanje putem 'Bilješke>Promijeni tip bilješke'
editing-toggle-html-editor = Uključi/isključi HTML uređivač
editing-toggle-visual-editor = Uključi/isključi vizualni uređivač
editing-toggle-sticky = Uključi/isključi ljepljivost
editing-expand = Proširi
editing-collapse = Sklopi
editing-expand-field = Proširi polje
editing-collapse-field = Sklopi polje
editing-underline-text = Podcrtaj tekst
editing-unordered-list = Neporedani popis
editing-warning-cloze-deletions-will-not-work = Upozorenje, nadopunjavanje teksta neće funkcionirati dok gore na vrhu ne promijenite tip bilješke u "nadopunjavanje teksta".
editing-mathjax-preview = MathJax pregled
editing-shrink-images = Umanji slike
editing-close-html-tags = Automatski zatvori HTML oznake
editing-from-clipboard = Iz međuspremnika
editing-alignment = Poravnanje
editing-equations = Jednadžbe
editing-no-image-found-on-clipboard = Nije nađena slika u međuspremniku.
editing-image-occlusion-mode = Način prekrivanja slike
editing-image-occlusion-zoom-out = Udalji
editing-image-occlusion-zoom-in = Približi
editing-image-occlusion-zoom-reset = Resetiraj zoom
editing-image-occlusion-toggle-translucent = Uključi/isključi prozirnost
editing-image-occlusion-delete = Obriši
editing-image-occlusion-duplicate = Dupliciraj
editing-image-occlusion-group = Grupiraj odabrano
editing-image-occlusion-ungroup = Odgrupiraj odabrano
editing-image-occlusion-select-all = Odaberi sve
editing-image-occlusion-alignment = Poravnanje
editing-image-occlusion-align-left = Poravnaj lijevo
editing-image-occlusion-align-h-center = Centriraj horizontalno
editing-image-occlusion-align-right = Poravnaj desno
editing-image-occlusion-align-top = Poravnaj gore
editing-image-occlusion-align-v-center = Centriraj vertikalno
editing-image-occlusion-align-bottom = Poravnaj dolje
editing-image-occlusion-select-tool = Odaberi
editing-image-occlusion-zoom-tool = Zoom
editing-image-occlusion-rectangle-tool = Pravokutnik
editing-image-occlusion-ellipse-tool = Elipsa
editing-image-occlusion-polygon-tool = Poligon
editing-image-occlusion-text-tool = Tekst
editing-image-occlusion-fill-tool = Popuni bojom
editing-image-occlusion-toggle-mask-editor = Uključi/isključi uređivač maski
editing-image-occlusion-reset = Resetiraj prekrivanje slike
editing-image-occlusion-confirm-reset = Jeste li sigurni da želite resetirati ovo prekrivanje slike?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML uređivač
