qt-accel-about = Anki &haqida
qt-accel-about-mac = Anki haqida...
qt-accel-cards = &Kartalar
qt-accel-check-database = Maʼlumotlar bazasini &tekshirish
qt-accel-check-media = &Media fayllarni tekshirish
qt-accel-edit = &Tahrirlash
qt-accel-exit = Chi&qish
qt-accel-export = &Eksport qilish...
qt-accel-export-notes = Qaydlarni &eksport qilish...
qt-accel-file = &Fayl
qt-accel-filter = Fil&tr
qt-accel-find = &Topish
qt-accel-find-and-replace = Topish va &almashtirish
qt-accel-find-duplicates = &Nusxalarni topish...
qt-accel-go = Oʻt&ish
qt-accel-guide = &Qoʻllanma
qt-accel-help = &Yordam
qt-accel-import = &Import qilish...
qt-accel-info = &Maʼlumot...
qt-accel-invert-selection = Tanlovni teskarisiga oʻgirmoq
qt-accel-next-card = &Keyingi karta
qt-accel-note = &Qayd
qt-accel-notes = &Qaydlar
qt-accel-preferences = &Sozlamalar
qt-accel-previous-card = &Oldingi karta
qt-accel-select-all = &Barchasini tanlash
qt-accel-select-notes = Qa&ydlarni tanlash
qt-accel-support-anki = Ankiʼni qoʻllab-qu&vvatlash
qt-accel-switch-profile = &Profilni almashtirish
qt-accel-tools = &Asboblar
qt-accel-undo = &Bekor qilish
qt-accel-redo = &Qaytarish
qt-accel-set-due-date = &Muddatini belgilash...
qt-accel-forget = &Tiklash
qt-accel-view = &Koʻrinish
qt-accel-full-screen = &Butun ekran rejimi
qt-accel-layout = &Maket
qt-accel-layout-auto = &Avtomatik
qt-accel-layout-vertical = &Vertikal
qt-accel-layout-horizontal = &Gorizontal
qt-accel-zoom-in = Ka&ttalashtirish
qt-accel-zoom-out = &Kichiklashtirish
qt-accel-reset-zoom = &Masshtabni qayta tiklash
qt-accel-toggle-sidebar = Yon panelni ochish/yopish
qt-accel-zoom-editor-in = Muharrirni ka&ttalashtirish
qt-accel-zoom-editor-out = Muharrirni &kichiklashtirish
qt-accel-create-backup = &Zaxira nusxasini yaratish
qt-accel-load-backup = Zaxira nusxasiga qa&ytish
qt-accel-upgrade-downgrade = Versiyani yuksaltirish/tushurish
