browsing-add-notes = เพิ่มโน้ต...
browsing-add-tags2 = เพิ่มแท็ก...
browsing-add-to-selected-notes = เพิ่มไปที่โน้ตที่ถูกเลือก
browsing-remove-from-selected-notes = นำออกจากโน้ตที่ถูกเลือก
browsing-addon = ส่วนเสริม
browsing-all-fields = ช่องข้อมูลทั้งหมด
browsing-answer = คำตอบ
browsing-any-flag = ธงใดก็ได้
browsing-average-ease = ค่าความง่ายในการจำเฉลี่ย
browsing-average-interval = ระยะห่างโดยเฉลี่ย
browsing-browser-appearance = รูปลักษณ์เบราว์เซอร์
browsing-browser-options = ตัวเลือกเบราว์เซอร์
browsing-buried = ถูกซ่อนสำหรับวันนี้
browsing-card = การ์ด
browsing-cards = การ์ด
browsing-card-list = รายการการ์ด
browsing-cards-cant-be-manually-moved-into = ไม่สามารถย้ายการ์ดไปสำรับแบบกรองเอง
browsing-cards-deleted = การ์ด { $count } ใบถูกลบแล้ว
browsing-cards-deleted-with-deckname = การ์ด { $count } ใบถูกลบจาก { $deck_name } แล้ว
browsing-change-deck = เปลี่ยนสำรับ
browsing-change-deck2 = เปลี่ยนสำรับ...
browsing-change-note-type = เปลี่ยนประเภทโน้ต
# Action in a context menu (right mouse-click on a card type)
browsing-change-note-type2 = เปลี่ยนประเภทโน้ต...
browsing-change-notetype = เปลี่ยนประเภทโน้ต
browsing-clear-unused-tags = ลบแท็กที่ไม่ได้ใช้
browsing-confirm-saved-search-overwrite = มีการค้นหาชื่อ { $name } บันทึกไว้แล้ว ต้องการบันทึกทับหรือไม่
browsing-created = สร้างเมื่อ
browsing-current-deck = สำรับปัจจุบัน
browsing-current-note-type = ประเภทโน้ตปัจจุบัน:
browsing-delete-notes = ลบโน้ต
browsing-duplicate = ซ้ำ
browsing-ease = ค่าความง่ายในการจำ
browsing-enter-tags-to-add = ใส่แท็กที่จะเพิ่ม:
browsing-enter-tags-to-delete = ใส่แท็กที่จะลบ:
browsing-filtered = (กรอง)
browsing-find = <b>ค้นหา</b>:
browsing-find-and-replace = ค้นหาและแทนที่
browsing-find-duplicates = ค้นหาโน้ตซ้ำ
browsing-first-card = การ์ดใบแรก
browsing-flag = ธง
browsing-font = <b>ฟอนต์</b>:
browsing-font-size = <b>ขนาดฟอนต์</b>:
browsing-found-as-across-bs = พบ { $part } ใน { $whole }
browsing-ignore-case = ไม่สนใจตัวพิมพ์เล็ก/ใหญ่
browsing-in = <b>ตรงที่</b>:
browsing-interval = ระยะห่างระหว่างการทบทวน
browsing-last-card = การ์ดใบสุดท้าย
browsing-learning = (กำลังเรียน)
browsing-line-size = <b>ขนาดบรรทัด</b>:
browsing-manage-note-types = จัดการประเภทโน้ต
browsing-move-cards = ย้ายการ์ด
browsing-move-cards-to-deck = ย้ายการ์ดไปที่สำรับ:
browsing-new = (ใหม่)
browsing-new-note-type = ประเภทโน้ตใหม่:
browsing-no-flag = ไม่มีธง
browsing-no-selection = ไม่มีการ์ดหรือโน้ตที่ถูกเลือกอยู่
browsing-note = โน้ต
browsing-notes = โน้ต
browsing-optional-filter = ตัวกรองไม่บังคับ:
browsing-please-give-your-filter-a-name = กรุณาตั้งชื่อตัวกรอง:
browsing-preview-selected-card = ตัวอย่างการ์ดที่เลือก ({ $val })
browsing-question = คำถาม
browsing-randomize-order = สุ่มลำดับ
browsing-remove-tags = นำแท็กออก...
browsing-replace-with = <b>แทนที่ด้วย</b>:
browsing-reposition = เปลี่ยนตำแหน่ง...
browsing-reposition-new-cards = เปลี่ยนตำแหน่งการ์ดใหม่
browsing-search-bar-hint = ค้นหาการ์ด/โน้ต (พิมพ์ข้อความ แล้วกด Enter)
browsing-search-in = ค้นหาใน:
browsing-select-deck = เลือกสำรับ
browsing-selected-notes-only = โน้ตที่เลือกเท่านั้น
browsing-shift-position-of-existing-cards = เปลี่ยนตำแหน่งการ์ดปัจจุบัน
browsing-sidebar = แถบด้านข้าง
browsing-sidebar-filter = ตัวกรองในแถบด้านข้าง
# The field that is used for sorting (sort is an adjective here, not a verb)
browsing-sort-field = ช่องข้อมูลที่ใช้เรียงลำดับ
browsing-suspended = ถูกพัก
browsing-tag-rename-warning-empty = แท็กที่ปัจจุบันไม่มีโน้ตที่ใช้ ไม่สามารถเปลี่ยนชื่อได้
browsing-target-field = ช่องข้อมูลเป้าหมาย:
browsing-toggle-bury = ซ่อน/เลิกซ่อนสำหรับวันนี้
browsing-toggle-suspend = พัก/เลิกพัก
browsing-group = { $count } กลุ่ม
browsing-note-count = { $count } โน้ต
browsing-notes-updated = อัปเดตโน้ต { $count } โน้ตแล้ว
browsing-cards-updated = อัปเดตการ์ด { $count } ใบแล้ว
browsing-sidebar-expand = ขยาย
browsing-sidebar-collapse = ย่อ
browsing-sidebar-expand-children = ขยายลูก
browsing-sidebar-collapse-children = ย่อลูก
browsing-sidebar-decks = สำรับ
browsing-sidebar-tags = แท็ก
browsing-sidebar-notetypes = ประเภทโน้ต
browsing-sidebar-saved-searches = การค้นหาที่บันทึกไว้
browsing-sidebar-save-current-search = บันทึกการค้นหาปัจจุบัน
browsing-sidebar-card-state = สถานะการ์ด
browsing-sidebar-flags = ธง
browsing-today = วันนี้
browsing-tooltip-card = ชื่อแม่แบบของการ์ด
browsing-tooltip-cards = จำนวนการ์ดที่โน้ตนี้มี
browsing-tooltip-notetype = ชื่อประเภทของโน้ต
browsing-studied-today = เรียนแล้ว
browsing-added-today = เพิ่มแล้ว
browsing-again-today = อีกครั้ง
browsing-edited-today = แก้ไขแล้ว
browsing-sidebar-first-review = ทบทวนครั้งแรก
browsing-sidebar-due-today = ครบกำหนด
browsing-sidebar-overdue = เกินกำหนด
browsing-row-deleted = (ลบแล้ว)
browsing-removed-unused-tags-count = ลบแท็กที่ไม่ได้ใช้ { $count } แท็กแล้ว
browsing-changed-new-position = เปลี่ยนตำแหน่งของการ์ดใหม่ { $count } ใบ
browsing-reparented-decks = เปลี่ยนชื่อสำรับ { $count } ชุดแล้ว
browsing-sidebar-card-state-review = ทบทวน

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

