addons-possibly-involved = Astennoù engouestlet marteze: { $addons }
addons-window-title = Astennoù
addons-code = Kod:
addons-config = Keflun.
addons-configuration = Kefluniadur
addons-disabled = (lazhet)
addons-disabled2 = (lazhet)
addons-install-addon = Staliañ an astenn
addons-install-addons = Staliañ an astenn(où)
addons-install-anki-addon = Staliañ astenn Anki
addons-install-from-file = Staliañ diwar ur restr...
