fields-add-field = Дадаць поле
fields-delete-field-from = Выдаліць поле з { $val }?
fields-editing-font = Шрыфт рэдагавання
fields-field = Поле:
fields-field-name = Назва поля:
fields-description = Апісанне
fields-fields-for = Палі для { $val }
fields-font = Шрыфт:
fields-new-position-1 = Новая пазіцыя (1...{ $val }):
fields-notes-require-at-least-one-field = Нататкі патрабуюць прынамсі аднаго поля.
fields-reverse-text-direction-rtl = Адваротны кірунак тэксту (RTL)
fields-collapse-by-default = Прадвызначана згортваць
fields-html-by-default = Прадвызначана выкарыстоўваць рэдактар HTML
fields-size = Памер:
fields-sort-by-this-field-in-the = Сартаваць па гэтаму полю ў браўзеры
fields-that-field-name-is-already-used = Гэта назва поля ўжо ўжываецца.
fields-name-first-letter-not-valid = Назва поля не можа пачынацца з #, ^ або /.
fields-name-invalid-letter = Назва поля не можа змяшчаць :, ", { "{" } або { "}" }.
