editing-actual-size = Alternar tamaño real
editing-add-media = Engadir ficheiros multimedia
editing-align-left = Aliñar á esquerda
editing-align-right = Aliñar á dereita
editing-an-error-occurred-while-opening = produciuse un erro ao abrir { $val }
editing-attach-picturesaudiovideo = Anexar imaxes/son/vídeo
editing-bold-text = Aplicar letra grosa
editing-cards = Tarxetas
editing-center = Centrar
editing-change-color = Cambiar a cor
editing-cloze-deletion = Resposta aniñada (tarxeta nova)
editing-cloze-deletion-repeat = Resposta aniñada (mesma tarxeta)
editing-copy-image = Copiar imaxe
editing-couldnt-record-audio-have-you-installed = Non se puido gravar o son. Tes «lame» instalado?
editing-customize-card-templates = Personalizar modelos de tarxetas
editing-customize-fields = Personalizar campos
editing-cut = Cortar
editing-double-click-image = preme dúas veces na imaxe
editing-double-click-to-expand = preme dúas veces para expandir
editing-double-click-to-collapse = preme dúas veces para colapsar
editing-edit-current = Editar a actual
editing-edit-html = Editar HTML
editing-fields = Campos
editing-float-left = Flotante á esquerda
editing-float-right = Flotante á dereita
editing-float-none = Sen flotar
editing-indent = Aumentar a sangría
editing-italic-text = Aplicar cursiva
editing-jump-to-tags-with-ctrlandshiftandt = Ir ás etiquetas con Ctrl+Maiús+T
editing-justify = Xustificar
editing-latex = LaTeX
editing-latex-equation = Ecuación LaTeX
editing-latex-math-env = Entorno matemático LaTeX
editing-mathjax-block = Bloque de MathJax
editing-mathjax-chemistry = MathJax para ecuacións químicas
editing-mathjax-inline = MathJax en liña
editing-mathjax-placeholder = Preme { $accept } para aceptar e { $newline } para unha liña nova.
editing-media = Recursos multimedia
editing-open-image = Abrir imaxe
editing-show-in-folder = Amosar en cartafol
editing-ordered-list = Lista numerada
editing-outdent = Diminuír a sangría
editing-paste = Pegar
editing-record-audio = Gravar son
editing-remove-formatting = Eliminar formato
editing-restore-original-size = Restaurar o tamaño orixinal
editing-select-remove-formatting = Selecciona o formato para eliminar
editing-show-duplicates = Amosar os duplicados
editing-subscript = Subíndice
editing-superscript = Superíndice
editing-tags = Etiquetas
editing-tags-add = Engadir etiqueta
editing-tags-copy = Copiar etiquetas
editing-tags-remove = Eliminar etiquetas
editing-tags-select-all = Seleccionar tódalas etiquetas
editing-text-color = Cor do texto
editing-text-highlight-color = Cor de realce to texto
editing-to-make-a-cloze-deletion-on = Para crear ocos nunha nota existente, primeiro debe cambiala a un tipo de nota de ocos, mediante Editar > Cambiar o tipo de nota.
editing-toggle-html-editor = Alternar o editor HTML
editing-toggle-visual-editor = Alternar o editor visual
editing-toggle-sticky = Alternar ancoraxe
editing-expand = Expandir
editing-collapse = Colapsar
editing-expand-field = Expandir campo
editing-collapse-field = Colapsar campo
editing-underline-text = Subliñar texto
editing-unordered-list = Lista desordenada
editing-warning-cloze-deletions-will-not-work = Aviso: os ocos non funcionarán a non ser que cambie o tipo de nota a Ocos.
editing-mathjax-preview = Vista previa do MathJax
editing-shrink-images = Diminuír imaxes
editing-close-html-tags = Pechar as etiquetas HTML automaticamente
editing-from-clipboard = Dende o portapapeis
editing-alignment = Aliñamento
editing-equations = Ecuacións
editing-no-image-found-on-clipboard = Non se atopou ningunha imaxe no portapapeis.
editing-image-occlusion-mode = Modo de oclusión de imaxe
editing-image-occlusion-zoom-out = Reducir zoom
editing-image-occlusion-zoom-in = Ampliar zoom
editing-image-occlusion-zoom-reset = Restabelecer zoom
editing-image-occlusion-toggle-translucent = Alternar a transparencia
editing-image-occlusion-delete = Eliminar
editing-image-occlusion-duplicate = Duplicar
editing-image-occlusion-group = Agrupar selección
editing-image-occlusion-ungroup = Desagrupar selección
editing-image-occlusion-select-all = Seleccionar todo
editing-image-occlusion-alignment = Aliñamento
editing-image-occlusion-align-left = Aliñar á esquerda
editing-image-occlusion-align-h-center = Centrar horizontalmente
editing-image-occlusion-align-right = Aliñar á dereita
editing-image-occlusion-align-top = Aliñar enriba
editing-image-occlusion-align-v-center = Centrar verticalmente
editing-image-occlusion-align-bottom = Aliñar abaixo
editing-image-occlusion-select-tool = Seleccionar
editing-image-occlusion-zoom-tool = Zoom
editing-image-occlusion-rectangle-tool = Rectángulo
editing-image-occlusion-ellipse-tool = Elipse
editing-image-occlusion-polygon-tool = Polígono
editing-image-occlusion-text-tool = Texto
editing-image-occlusion-fill-tool = Encher con cor
editing-image-occlusion-toggle-mask-editor = Alternar o editor de máscara
editing-image-occlusion-reset = Reiniciar a oclusión de imaxe
editing-image-occlusion-confirm-reset = Tes a certeza de querer reiniciar esta oclusión de imaxe?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Editor de HTML
