preferences-automatically-sync-on-profile-openclose = Sincronizar automaticamente ao abrir/pechar o perfil
preferences-backups = Copias de seguranza
preferences-change-deck-depending-on-note-type = Cambiar baralla dependendo do tipo de nota
preferences-changes-will-take-effect-when-you = Os cambios terán efecto cando reinicies o Anki.
preferences-hours-past-midnight = horas pasada a medianoite
preferences-language = Idioma
preferences-interrupt-current-audio-when-answering = Interromper o son ao responder
preferences-learn-ahead-limit = Tempo límite para adiantar o estudo
preferences-mins = mins.
preferences-network = Rede
preferences-next-day-starts-at = O seguinte día comeza ás
preferences-on-next-sync-force-changes-in = Forzar cambios nunha dirección na próxima sincronización
preferences-paste-clipboard-images-as-png = Pegar imaxes do portapapeis como PNG
preferences-paste-without-shift-key-strips-formatting = Pegar sen a tecla Maiús elimina o formato
preferences-generate-latex-images-automatically = Xerar imaxes LaTeX (risco de seguranza)
preferences-periodically-sync-media = Sincronizar ficheiros multimedia periodicamente
preferences-preferences = Preferencias
preferences-scheduling = Reprogramar
preferences-show-learning-cards-with-larger-steps = Amosar as tarxetas en aprendizaxe con intervalos maiores antes dos repasos
preferences-show-next-review-time-above-answer = Amosar intervalo do próximo repaso enriba dos botóns de resposta
preferences-spacebar-rates-card = O espazador (ou enter) tamén responde a tarxeta
preferences-show-play-buttons-on-cards-with = Amosar botóns de reprodución en tarxetas con son
preferences-show-remaining-card-count = Amosar o número de tarxetas restantes
preferences-some-settings-will-take-effect-after = Algúns axustes terán efecto despois de reiniciar o Anki.
preferences-tab-synchronisation = Sincronización
preferences-synchronize-audio-and-images-too = Sincronizar o son e as imaxes
preferences-timebox-time-limit = Intervalos temporais de estudo
preferences-user-interface-size = Tamaño da interface de usuario
preferences-when-adding-default-to-current-deck = Ao engadir, facelo na baralla predeterminada
preferences-you-can-restore-backups-via-fileswitch = Podes restaurar as túas copias de seguranza en Ficheiro > Cambiar perfil.
preferences-default-search-text = Texto de busca predeterminado
preferences-default-search-text-example = por exemplo: "deck:current"
preferences-theme = Tema
preferences-theme-follow-system = O mesmo do sistema
preferences-theme-light = Claro
preferences-theme-dark = Escuro
preferences-v3-scheduler = Algoritmo de planificación V3
preferences-check-for-updates = Comprobar se hai actualizacións
preferences-ignore-accents-in-search = Ignorar acentos na busca (máis lento)
preferences-backup-explanation =
    O Anki crea copias de seguranza da túa colección periodicamente. Cando as copias teñan máis de 2 días,
    o Anki comezará a eliminar algunhas para liberar espazo no disco.
preferences-daily-backups = Copias de seguranza diarias a manter:
preferences-weekly-backups = Copias de seguranza semanais a manter:
preferences-monthly-backups = Copias de seguranza mensuais a manter:
preferences-minutes-between-backups = Tempo entre copias de seguranza automáticas (en minutos):
preferences-reduce-motion = Reducir o movemento
preferences-reduce-motion-tooltip = Desactiva as animacións e transicións da interface de usuario
preferences-custom-sync-url = Servidor de sincronización persoal
preferences-custom-sync-url-disclaimer = Se es usuario avanzado, consulta o manual.
preferences-hide-top-bar-during-review = Ocultar a barra superior durante o estudo
preferences-hide-bottom-bar-during-review = Ocultar a barra inferior durante o estudo
preferences-always = Sempre
preferences-full-screen-only = Só no modo pantalla completa
preferences-appearance = Aparencia
preferences-general = Xeral
preferences-style = Estilo
preferences-review = Repaso
preferences-answer-keys = Teclas de resposta
preferences-distractions = Distraccións
preferences-minimalist-mode = Modo minimalista
preferences-minimalist-mode-tooltip = Simplifica e compacta a interface
preferences-editing = Edición
preferences-browsing = Explorador
preferences-default-deck = Baralla predeterminada
preferences-account = Conta do AnkiWeb
preferences-note = Aviso
preferences-scheduler = Planificador
preferences-user-interface = Interface de usuario
preferences-import-export = Importar/Exportar
preferences-network-timeout = Tempo de espera da rede
preferences-reset-window-sizes = Restabelecer o tamaño das xanelas
preferences-reset-window-sizes-complete = Restabelecéronse os tamaños e localizacións das xanelas.
preferences-third-party-services = Servizos de terceiros
preferences-third-party-description = Os servizos de terceiros non están vinculados nin avalados polo Anki. Algúns destes servizos poden ser de pago.

## URL scheme related

preferences-url-schemes = Protocolos URL
preferences-url-scheme-prompt = Protocolos de URL permitidos (separados por espazos):
preferences-url-scheme-allow-once = Permitir esta vez
preferences-url-scheme-always-allow = Permitir sempre

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = Básica
preferences-reviewer = Pantalla de repaso
preferences-media = Multimedia
preferences-not-logged-in = Non iniciaches sesión no AnkiWeb.
