profiles-anki-could-not-rename-your-profile = Anki non puido renomear o teu perfil porque non puido renomear o cartafol do perfil no disco. Por favor asegúrese de que ten permisos para escribir en Documents/Anki e non hai outros programas tentando acceder aos seus cartafoles de perfil, e entón ténteo de novo.
profiles-folder-already-exists = Xa existe o cartafol
profiles-open = Abrir
profiles-please-remove-the-folder-and = Por favor elimine o cartafol { $val } e ténteo de novo.
profiles-profiles = Perfiles
profiles-quit = Saír
profiles-user-1 = Usuario 1
profiles-creating-backup = Creando copia de seguranza...
profiles-backup-created = Creouse unha copia de seguranza.
