#!/usr/bin/env python

import os, sys
# system-wide install
sys.path.insert(0, "/usr/share/anki")
sys.path.insert(0, "/usr/share/anki/libanki")
# running from extracted folder
base = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, base)
sys.path.insert(0, os.path.join(base, "libanki"))
# or git
sys.path.insert(0, os.path.join(base, "..", "libanki"))
# start
import  aqt
aqt.run()
