adding-add-shortcut-ctrlandenter = Дадаць (спалучэнне клавіш: ctrl+enter)
adding-added = Дададзена
adding-discard-current-input = Адхіліць упісаны тэкст?
adding-keep-editing = Працягнуць рэдагаванне
adding-edit = Рэдагаваць "{ $val }"
adding-history = Гісторыя
adding-note-deleted = (Нататка выдалена)
adding-shortcut = Спалучэнне клавіш: { $val }
adding-the-first-field-is-empty = Першае поле пустое.
adding-you-have-a-cloze-deletion-note = У вас нататка з прабеламі, але вы не дадалі запаўненні прабелаў. Працягнуць?
adding-cloze-outside-cloze-notetype = Запаўненне прабела можа ўжывацца толькі для нататак з прабеламі.
adding-cloze-outside-cloze-field = Запаўненне прабела можа ўжывацца толькі на палях, якія ўжываюць фільтр «cloze:». Звычайна гэта першае поле.
