card-stats-added = 추가됨
card-stats-first-review = 첫 복습
card-stats-latest-review = 최근 복습
card-stats-interval = 복습간격
card-stats-ease = ease
card-stats-review-count = 복습횟수
card-stats-lapse-count = 실패
card-stats-average-time = 평균 시간
card-stats-total-time = 전체 시간
card-stats-new-card-position = 위치
card-stats-card-template = 카드 유형
card-stats-note-type = 노트 유형
card-stats-deck-name = 덱
card-stats-preset = 사전 설정
card-stats-note-id = 노트 ID
card-stats-card-id = 카드 ID
card-stats-review-log-rating = 평가
card-stats-review-log-type = 유형
card-stats-review-log-date = 날짜
card-stats-review-log-time-taken = 시간
card-stats-review-log-type-learn = 학습
card-stats-review-log-type-review = 복습
card-stats-review-log-type-relearn = 재학습
card-stats-review-log-type-filtered = 필터됨
card-stats-review-log-type-manual = 수동
card-stats-review-log-type-rescheduled = 일정 재조정됨
card-stats-review-log-elapsed-time = 소요된 시간
card-stats-no-card = (표시할 카드가 없습니다.)
card-stats-custom-data = 사용자 정의(커스텀) 데이터
card-stats-fsrs-stability = 안정성
card-stats-fsrs-difficulty = 난이도
card-stats-fsrs-retrievability = 검색 가능성
card-stats-fsrs-forgetting-curve-title = 망각 곡선(망각 커브)
card-stats-fsrs-forgetting-curve-first-week = 첫 주
card-stats-fsrs-forgetting-curve-first-month = 첫 달
card-stats-fsrs-forgetting-curve-first-year = 첫 해
card-stats-fsrs-forgetting-curve-all-time = 모든 시간

## Window Titles

card-stats-current-card = 현재 카드 ({ $context })
card-stats-previous-card = 이전 카드 ({ $context })
