editing-actual-size = 실제 크기 전환
editing-add-media = 미디어 넣기
editing-align-left = 왼쪽으로 정렬
editing-align-right = 오른쪽으로 정렬
editing-an-error-occurred-while-opening = { $val }를 여는 동안 에러가 발생하였습니다.
editing-attach-picturesaudiovideo = 사진/오디오/둥영상 첨부
editing-bold-text = 볼드 글씨
editing-cards = 카드
editing-center = 중앙
editing-change-color = 색상 변경
editing-cloze-deletion = 빈칸 뚫기
editing-cloze-deletion-repeat = 빈칸 뚫기 (동일 카드)
editing-copy-image = 이미지 복사
editing-couldnt-record-audio-have-you-installed = 오디오를 녹음할 수 없음. 'lame'을 설치하겠습니까?
editing-customize-card-templates = 카드 템플릿 수정
editing-customize-fields = 필드 맞춤 설정
editing-cut = 잘라내기
editing-double-click-image = 이미지 더블 클릭
editing-double-click-to-expand = 펼치려면 더블 클릭
editing-double-click-to-collapse = 접으려면 더블 클릭
editing-edit-current = 현재 카드 편집
editing-edit-html = HTML 편집
editing-fields = 필드
editing-float-left = 왼쪽 정렬
editing-float-right = 오른쪽 정렬
editing-float-none = 정렬 없음
editing-indent = 들여쓰기
editing-italic-text = 기울임 글씨
editing-jump-to-tags-with-ctrlandshiftandt = Ctrl+Shift+T를 눌러 태그로 이동
editing-justify = 양쪽 정렬
editing-latex = LaTeX
editing-latex-equation = LaTeX 공식
editing-latex-math-env = LaTeX 수학 환경.
editing-mathjax-block = MathJax 공간
editing-mathjax-chemistry = MathJax 화학
editing-mathjax-inline = MathJax 인라인
editing-mathjax-placeholder = 수락하려면 { $accept }를 누르고, 새 줄은 { $newline }을 누르세요.
editing-media = 미디어
editing-open-image = 이미지 열기
editing-show-in-folder = 폴더에 표시
editing-ordered-list = 순차적인 목록
editing-outdent = 내여쓰기
editing-paste = 붙여넣기
editing-record-audio = 오디오 녹음
editing-remove-formatting = 글씨 포맷 제거
editing-restore-original-size = 원본 크기 복원
editing-select-remove-formatting = 제거할 형식 선택
editing-show-duplicates = 중복된 항목 보기
editing-subscript = 아래 첨자
editing-superscript = 위 첨자
editing-tags = 태그
editing-tags-add = 태그 추가
editing-tags-copy = 태그 복사
editing-tags-remove = 태그 삭제
editing-tags-select-all = 태그 모두 선택
editing-text-color = 텍스트 색상
editing-text-highlight-color = 텍스트 하이라이트 색상
editing-to-make-a-cloze-deletion-on = 이미 존재하는 노트에 빈칸 뚫기를 만들려면, 편집>노트 유형 변경을 통해서 빈칸(cloze) 유형으로 먼저 변경해야합니다.
editing-toggle-html-editor = HTML 편집기 전환
editing-toggle-visual-editor = 보이는 편집기 전환
editing-toggle-sticky = sticky 전환
editing-expand = 펼치기
editing-collapse = 접기
editing-expand-field = 필드 펼치기
editing-collapse-field = 필드 접기
editing-underline-text = 밑줄 글씨
editing-unordered-list = 비순차적인 목록
editing-warning-cloze-deletions-will-not-work = 빈칸 뚫기는 화면 위쪽에서 유형을 빈칸(Cloze)으로 선택해야만 동작합니다.
editing-mathjax-preview = MathJax 미리보기
editing-shrink-images = 이미지 줄여보기
editing-close-html-tags = HTML 태그 자동 완성
editing-from-clipboard = 클립보드에서
editing-alignment = 정렬
editing-equations = 균등화
editing-no-image-found-on-clipboard = 클립보드에서 이미지를 찾을 수 없습니다.
editing-image-occlusion-mode = Image Occlusion 모드
editing-image-occlusion-zoom-out = 축소
editing-image-occlusion-zoom-in = 확대
editing-image-occlusion-zoom-reset = 확대축소 초기화
editing-image-occlusion-toggle-translucent = 투명도 전환
editing-image-occlusion-delete = 삭제
editing-image-occlusion-duplicate = 복제
editing-image-occlusion-group = 그룹 선택
editing-image-occlusion-ungroup = 그룹 해제
editing-image-occlusion-select-all = 전체 선택전체 선택
editing-image-occlusion-alignment = 정렬
editing-image-occlusion-align-left = 왼쪽 정렬
editing-image-occlusion-align-h-center = 수평 중앙 정렬
editing-image-occlusion-align-right = 우측 정렬
editing-image-occlusion-align-top = 상단 정렬
editing-image-occlusion-align-v-center = 수직 중앙 정렬
editing-image-occlusion-align-bottom = 하단 정렬
editing-image-occlusion-select-tool = 선택
editing-image-occlusion-zoom-tool = 확대
editing-image-occlusion-rectangle-tool = 사각형
editing-image-occlusion-ellipse-tool = 타원
editing-image-occlusion-polygon-tool = 다각형
editing-image-occlusion-text-tool = 텍스트
editing-image-occlusion-toggle-mask-editor = 마스크 편집기 전환
editing-image-occlusion-reset = Image Occlusion 초기화
editing-image-occlusion-confirm-reset = image occlusion을 초기화하시겠습니까?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML 편집기
