profiles-anki-could-not-read-your-profile = 프로필 자료를 읽을 수 없었슨니다. 윈도우 크기와 싱크를 위한 로그인 정보가 사라졌습니다.
profiles-anki-could-not-rename-your-profile = Anki가 하드디스크에 있는 프로필 폴더의 이름을 바꿀 수 없습니다. 내 문서/Anki 폴더에 쓰기 권한을 가지고 있는지 확인하고, 다른 프로그램이 프로필 폴더를 접근 중은 아닌지 확인한 후 다시 시도하세요.
profiles-folder-already-exists = 이미 존재하는 폴더입니다.
profiles-open = 열기
profiles-open-backup = 백업 열기...
profiles-please-remove-the-folder-and = { $val } 폴더를 삭제한 후 다시 시도해 주세요.
profiles-profile-corrupt = 오류 있는 프로파일
profiles-profiles = 프로필
profiles-quit = 닫기
profiles-user-1 = 사용자 1
profiles-confirm-lang-choice = Anki를 정말 { $lang }로 사용하시겠습니까?
profiles-could-not-create-data-folder = Anki의 데이터 폴더를 만들 수 없습니다. 설명서의 파일 위치 섹션을 참조해서 해당 위치가 읽기 전용이 아닌지 확인해주세요.
profiles-prefs-corrupt-title = 손상된 개인설정
profiles-prefs-file-is-corrupt = Anki의 prefs21.db 파일이 손상되어 다시 생성되었습니다. 여러 프로필을 사용했다면, 동일한 이름으로 다시 추가해서 카드를 복구하세요.
profiles-profile-does-not-exist = 요청한 프로필을 찾을 수 없습니다.
profiles-creating-backup = 백업하는 중...
profiles-backup-created = 백업을 만들었습니다.
profiles-backup-creation-failed = 백업을 만들지 못했습니다. { $reason }
profiles-backup-unchanged = 전에 백업한 뒤에 변경 사항이 없습니다.
