qt-accel-about = ھەققىدە(&A)
qt-accel-about-mac = Anki ھەققىدە…
qt-accel-cards = كارتا(&C)
qt-accel-check-database = ساندان تەكشۈر(&C)
qt-accel-check-media = ۋاسىتە تەكشۈر(&M)
qt-accel-edit = تەھرىر(&E)
qt-accel-exit = چېكىن(&X)
qt-accel-export = چىقار(&E)…
qt-accel-export-notes = خاتىرە چىقار(&E)
qt-accel-file = ھۆججەت(&F)
qt-accel-filter = سۈزگۈچ(&T)
qt-accel-find = ئىزدە(&F)
qt-accel-find-and-replace = ئىزدە ۋە ئالماشتۇر(&P)…
qt-accel-find-duplicates = تەكرارلانغاننى ئىزدە(&D)…
qt-accel-go = يۆتكەل(&G)
qt-accel-guide = يېتەكچى(&G)
qt-accel-help = ياردەم(&H)
qt-accel-import = ئەكىر(&I)…
qt-accel-info = ئۇچۇر(&I)…
qt-accel-invert-selection = ئەكسىچە تاللا(&I)
qt-accel-next-card = كېيىنكى كارتا(&N)
qt-accel-note = خاتىرە(&o)
qt-accel-notes = خاتىرە(&N)
qt-accel-preferences = مايىللىق(&P)
qt-accel-previous-card = ئالدىنقى كارتا(&P)
qt-accel-select-all = ھەممىنى تاللا(&A)
qt-accel-select-notes = خاتىرە تاللا(&N)
qt-accel-support-anki = Anki نى قوللاش(&S)
qt-accel-switch-profile = تەرجىمىھال ئالماشتۇر(&S)
qt-accel-tools = قورال(&T)
qt-accel-undo = يېنىۋال(&U)
qt-accel-redo = تەكرارلا(&R)
qt-accel-set-due-date = مۆھلەت چېسلا تەڭشەك(&D)…
qt-accel-forget = ئەسلىگە قايتۇر(&R)
qt-accel-view = كۆرۈنۈش(&V)
qt-accel-full-screen = پۈتۈن ئېكران ئاچ/ياپ(&F)
qt-accel-layout = جايلاشتۇر(&L)
qt-accel-layout-auto = ئۆزلۈكىدىن(&A)
qt-accel-layout-vertical = بويىغا(&V)
qt-accel-layout-horizontal = توغرىسىغا(&H)
qt-accel-zoom-in = يېقىنلات(&I)
qt-accel-zoom-out = يىراقلات(&O)
qt-accel-reset-zoom = ئەسلىگە قايتۇر(&R)
qt-accel-toggle-sidebar = يان بالداقنى ئالماشتۇر
qt-accel-zoom-editor-in = تەھرىرلىگۈچنى يېقىنلات(&I)
qt-accel-zoom-editor-out = تەھرىرلىگۈچنى يىراقلات(&O)
qt-accel-create-backup = زاپاس قۇر(&B)
qt-accel-load-backup = زاپاسنى ئەسلىگە كەلتۈر(&R)
qt-accel-upgrade-downgrade = يۈكسەل/تۆۋەنلەت
