decks-add-new-deck-ctrlandn = Adăugă pachet nou (Ctrl+N)
decks-build = Construieşte
decks-cards-selected-by = carduri selectate de
decks-create-deck = Creează pachet
decks-custom-steps-in-minutes = Pași personalizați (în minute)
decks-deck = Pachet
decks-decreasing-intervals = Intervale descrescătoare
decks-delete-deck = Ştergere pachet
decks-enable-second-filter = Activează al doilea filtru
decks-filter = Filtru:
decks-filter-2 = Filtru 2
decks-get-shared = Partajează
decks-import-file = Importă fișier
decks-increasing-intervals = Intervale crescătoare
decks-latest-added-first = Ultimele adăugate mai întâi
decks-limit-to = Limitează la
decks-minutes = minute
decks-most-lapses = Cele mai multe greșeli
decks-new-deck-name = Nume nou pentru pachet:
decks-no-deck = [fără pachet]
decks-oldest-seen-first = Cele mai vechi văzute primele
decks-order-added = Ordine de adăugare
decks-order-due = Ordine dată scadentă
decks-please-select-something = Te rog să selectezi ceva.
decks-random = Aleator
decks-relative-overdueness = Întârziere relativă
decks-repeat-failed-cards-after = Repetă cărțile eșuate după
decks-reschedule-cards-based-on-my-answers = Reprogramează cărțile pe baza răspunsurilor mele din acest pachet
decks-study = Studiază
decks-study-deck = Studiază pachet
decks-filtered-deck-search-empty = Niciun card nu corespunde căutării furnizate. Este posibil ca unele carduri să fi fost excluse deoarece se află într-un pachet filtrat diferit sau sunt suspendate.
decks-unmovable-cards = Afișează cardurile excluse
# The count of cards waiting to be reviewed
decks-review-header = Programate
decks-learn-header = Memorare
