editing-actual-size = Comută dimensiunea reală
editing-add-media = Adaugă fişier multimedia
editing-align-left = Aliniază stânga
editing-align-right = Aliniază dreapta
editing-an-error-occurred-while-opening = A apărut o eroare la deschiderea { $val }
editing-attach-picturesaudiovideo = Ataşează imagini/audio/video
editing-bold-text = Text îngroşat
editing-cards = Carduri
editing-center = Centrat
editing-change-color = Schimbă culoarea
editing-cloze-deletion = Ascundere tip ”cloze”
editing-couldnt-record-audio-have-you-installed = Nu s-a putut înregistra sunetul. Verifică dacă ai instalat "lame".
editing-customize-card-templates = Personalizează șabloanele de carduri
editing-customize-fields = Personalizează câmpurile
editing-cut = Tăiere
editing-edit-current = Editează curenta
editing-edit-html = Editează HTML
editing-fields = Câmpuri
editing-float-left = Mişcă la stânga
editing-float-right = Mişcă la dreapta
editing-float-none = Nu mişca
editing-indent = Măreşte indent-ul
editing-italic-text = Text italic
editing-jump-to-tags-with-ctrlandshiftandt = Salt la marcaje cu Ctrl+Shift+T
editing-justify = Aliniere stânga-dreapta (Justify)
editing-latex = LaTeX
editing-latex-equation = Ecuație LaTeX
editing-latex-math-env = Mediu matematic LaTex
editing-mathjax-placeholder = Apasă { $accept } pentru a accepta, { $newline } pentru o nouă linie.
editing-media = Media
editing-ordered-list = Listă ordonată
editing-outdent = Redu indentarea
editing-paste = Lipește
editing-record-audio = Înregistrează audio
editing-remove-formatting = Eliminare formatare
editing-show-duplicates = Arată dublurile
editing-subscript = Indice
editing-superscript = Superscript
editing-tags = Marcaje
editing-tags-add = Adaugă marcaj
editing-tags-copy = Copiază marcaje
editing-tags-remove = Elimină marcaje
editing-tags-select-all = Selectează toate marcajele
editing-text-color = Culoarea textului
editing-text-highlight-color = Culoarea de evidențiere a textului
editing-to-make-a-cloze-deletion-on = Pentru a face o ascundere cloze pe o notiţă existentă, trebuie să o schimbi mai întâi la tipul ”cloze”, prin „Notiţe> Schimbați tip notă”.
editing-toggle-html-editor = Comută editorul HTML
editing-toggle-sticky = Comută modul ”lipicios”
editing-toggle-visual-editor = Comută editorul vizual
editing-underline-text = Subliniază textul
editing-unordered-list = Listă neordonată
editing-warning-cloze-deletions-will-not-work = Atenție, ascunderile cloze nu vor funcționa până când nu comuţi la tipul Cloze în meniul de mai sus.

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Editor HTML
editing-set-text-color = Stabileşte culoarea textului
editing-set-text-highlight-color = Stabileşte culoarea de evidențiere a textului
