profiles-anki-could-not-read-your-profile = Anki nu a putut citi datele de profil. Dimensiunile ferestrelor și detaliile de conectare pentru sincronizare au fost uitate.
profiles-anki-could-not-rename-your-profile = Anki nu a putut redenumi profilul dvs. deoarece nu a putut redenumi folderul de profil de pe disc. Asigurați-vă că aveți permisiunea de a scrie în Documents/Anki și că niciun alt program nu vă accesează folderele de profil, apoi încercați din nou.
profiles-folder-already-exists = Dosarul există deja.
profiles-open = Deschide
profiles-open-backup = Deschide Backup...
profiles-please-remove-the-folder-and = Vă rugăm să eliminați folderul { $val } și să încercați din nou.
profiles-profile-corrupt = Profil corupt
profiles-profiles = Profiluri
profiles-quit = Părăsește
profiles-user-1 = Utilizator 1
profiles-confirm-lang-choice = Sigur doriți să afișați interfața lui Anki în { $lang }?
profiles-could-not-create-data-folder = Anki nu și-a putut crea folderul de date. Consultați secțiunea Locații fișiere din manual și asigurați-vă că locația nu este doar pentru citire.
profiles-prefs-corrupt-title = Preferințe corupte
profiles-prefs-file-is-corrupt = Fișierul prefs21.db al lui Anki a fost corupt și a fost recreat. Dacă utilizați mai multe profiluri, adăugați-le înapoi folosind aceleași nume pentru a vă recupera cardurile.
profiles-profile-does-not-exist = Profilul solicitat nu există.
profiles-creating-backup = Se crează copie de rezervă...
