adding-add-shortcut-ctrlandenter = Magdagdag (shortcut: ctrl+enter)
adding-added = Mga nadagdag na
adding-close-and-lose-current-input = Mawawala ang current input mo kapag sinara mo ito. Sure ka ba?
adding-edit = I-edit ang
adding-history = Kasaysayan
adding-note-deleted = (Na-delete ang note)
adding-shortcut = Shortcut:
adding-the-first-field-is-empty = Walang laman iyong unang field.
adding-you-have-a-cloze-deletion-note = Meron kang cloze notetype pero hindi ka pa nakakagawa ng kahit anong cloze deletion. Tuloy ba?
adding-cloze-outside-cloze-notetype = Ang Cloze deletion ay magagamit lang sa mga cloze notetype.
adding-cloze-outside-cloze-field = Ang Cloze deletion ay magagamit lang sa mga field na ginagamit ang 'cloze:' na filter. Unang field pa lang ito.
