decks-add-new-deck-ctrlandn = Magdagdag ng bagong deck (Ctrl+N)
decks-build = Build
decks-cards-selected-by = mga card na napili ng
decks-create-deck = Gumawa ng deck
decks-custom-steps-in-minutes = Mga custom na step (ilang minuto)
decks-deck = Deck
decks-decreasing-intervals = Nababawasang mga interval
decks-delete-deck = I-delete ang deck
decks-enable-second-filter = I-enable ang pangalawang filter
decks-filter = Filter:
decks-filter-2 = Filter 2
decks-get-shared = Magbahagi ng deck
decks-import-file = Mag-import ng file
decks-increasing-intervals = Tumataas na mga interval
decks-latest-added-first = Latest ang unang nadagdag
decks-limit-to = I-limit sa
decks-minutes = mga minuto
decks-most-lapses = Karamihan ng mga lapse
decks-new-deck-name = Pangalan ng bagong deck:
decks-no-deck = [walang deck]
decks-oldest-seen-first = Pinakaluma ang makikita
decks-order-added = Nadagdag na ang order
decks-order-due = Due na order
decks-please-select-something = Pumili ka muna.
decks-random = Random
decks-relative-overdueness = Relative na pagka-overdue
decks-repeat-failed-cards-after = Uliting ang mga failed card pagkatapos
decks-reschedule-cards-based-on-my-answers = I-reschedule ang mga card base sa mga sagot ko sa deck na ito
decks-study = Mag-aral
decks-study-deck = Study Deck
decks-filtered-deck-search-empty = Walang card ang tumugma sa binigay na search. Ang ilang card ay baka na-exclude dahil nasa ibang filtered deck na ang mga ito, o na-suspend.
decks-unmovable-cards = Ipakita ang kahit anong excluded na card
decks-learn-header = Aralin
