profiles-anki-could-not-read-your-profile = Hindi mabasa ng Anki ang profile data mo. Nakalimutan ang window sizes at ang mga detalye ng sync login mo.
profiles-anki-could-not-rename-your-profile = Hindi ma-rename ng Anki ang profile mo dahil hindi nito ma-rename ang profile folder sa disk. Pakisigurado na may permission kang mag-write sa Documents/Anki at walang ibang program ang nakaka-access ng profile folders mo, saka subukang muli.
profiles-folder-already-exists = Meron nang folder nito.
profiles-open = Buksan
profiles-open-backup = Buksan ang Backup...
profiles-please-remove-the-folder-and = Pakitanggal ng folder na { $val } at subukang muli.
profiles-profile-corrupt = Corrupt ang Profile
profiles-profiles = Mga Profile
profiles-quit = Umalis
profiles-user-1 = User 1
profiles-confirm-lang-choice = Sure ka ba na gusto mong i-display ang interface ng Anki sa { $lang }?
profiles-could-not-create-data-folder = Hindi magawa ng Anki ang data folder nito. Pakitingnan ang File Locations section ng manwal, at siguraduhin na ang location ay hindi read-only.
profiles-prefs-corrupt-title = Corrupt ang Preferences
profiles-prefs-file-is-corrupt = Ang prefs21.db file ng Anki ay corrupt at nagaya. Kung gumagamit ka dati ng maraming profile,   mababalik sila gamit ang parehas na mga pangalan sa pag-recover ng mga card.
profiles-profile-does-not-exist = Hindi nag-e-exist ang Requested Profile.
profiles-creating-backup = Ginagawa ang Backup...
profiles-backup-created = Nagawa na ang Backup.
profiles-backup-creation-failed = Pumalya ang paggawa ng Backup: { $reason }
profiles-backup-unchanged = Walang pagbabago mula noong huling backup.
