qt-accel-about = Anki について (&A)
qt-accel-about-mac = Ankiについて...
qt-accel-cards = カード(&C)
qt-accel-check-database = データベースをチェック (&C)
qt-accel-check-media = メディアをチェック
qt-accel-edit = 編集 (&E)
qt-accel-exit = 終了 (&X)
qt-accel-export = エクスポート (&E)
qt-accel-export-notes = ノートをエクスポート (&E)...
qt-accel-file = ファイル (&F)
qt-accel-filter = フィルター (&T)
qt-accel-find = 検索 (&F)
qt-accel-find-and-replace = 検索して置換 (&P)...
qt-accel-find-duplicates = 重複を検索 (&D)...
qt-accel-go = 移動 (&G)
qt-accel-guide = ガイド (&G)
qt-accel-help = ヘルプ (&H)
qt-accel-import = インポート (&I)
qt-accel-info = カード情報
qt-accel-invert-selection = 選択を反転 (&I)
qt-accel-next-card = 次のカード (&N)
qt-accel-note = ノート (&O)
qt-accel-notes = ノート(&N)
qt-accel-preferences = 設定(&P)
qt-accel-previous-card = 前のカード (&P)
qt-accel-select-all = すべてを選択 (&A)
qt-accel-select-notes = ノートを選択 (&N)
qt-accel-support-anki = Anki への支援 (&S)
qt-accel-switch-profile = プロファイルを切り替える (&S)
qt-accel-tools = ツール (&T)
qt-accel-undo = 元に戻す (&U)
qt-accel-redo = やり直す (&R)
qt-accel-set-due-date = 期日を指定 (&D)...
qt-accel-forget = リセット (&R)
qt-accel-view = 表示 (&V)
qt-accel-full-screen = 全画面表示 (&F)
qt-accel-layout = エディタの配置 (&L)
qt-accel-layout-auto = 自動調整 (&A)
qt-accel-layout-vertical = テーブルの下側 (&V)
qt-accel-layout-horizontal = テーブルの右側 (&H)
qt-accel-zoom-in = 拡大 (&I)
qt-accel-zoom-out = 縮小 (&O)
qt-accel-reset-zoom = 拡大縮小をリセット (&R)
qt-accel-toggle-sidebar = サイドバー表示を切り替える
qt-accel-zoom-editor-in = エディタを拡大 (&I)
qt-accel-zoom-editor-out = エディタを縮小 (&O)
qt-accel-create-backup = バックアップを作成 (&B)
qt-accel-load-backup = バックアップから復元 (&R)
qt-accel-upgrade-downgrade = アップグレード／ダウングレード
