qt-accel-about = &കുറിച്ച്
qt-accel-about-mac = അങ്കിയെക്കുറിച്ച്...
qt-accel-cards = &കാർഡുകൾ
qt-accel-check-database = &ഡാറ്റാബേസ് പരിശോധിക്കുക
qt-accel-check-media = &മീഡിയ പരിശോധിക്കുക
qt-accel-edit = &തിരുത്തുക
qt-accel-exit = പു&റത്ത്
qt-accel-export = &കയറ്റുമതി ചെയ്യുക ...
qt-accel-export-notes = &കുറിപ്പുകൾ എക്‌സ്‌പോർട്ടുചെയ്യുക...
qt-accel-file = &ഫയൽ
qt-accel-filter = ഫിൽ&റ്റർ
qt-accel-find = &കണ്ടെത്തുക
qt-accel-find-and-replace = കണ്ടെത്തി മാറ്റിസ്ഥാ&പിക്കുക
qt-accel-find-duplicates = &തനിപ്പകർപ്പുകൾ കണ്ടെത്തുക
qt-accel-go = &പോകൂ
qt-accel-guide = &വഴികാട്ടി ...
qt-accel-help = &സഹായം
qt-accel-import = &ഇറക്കുമതി ചെയ്യുക...
qt-accel-info = &വിവരം...
qt-accel-invert-selection = &തിരഞ്ഞെടുപ്പ് വിപരീതമാക്കുക
qt-accel-next-card = &അടുത്ത കാർഡ്
qt-accel-note = കു&റിപ്പ്
qt-accel-notes = &കുറിപ്പുകൾ
qt-accel-preferences = &മുൻഗണനകൾ
qt-accel-previous-card = &മുമ്പത്തെ കാർഡ്
qt-accel-select-all = &എല്ലാം തിരഞ്ഞെടുക്കുക
qt-accel-select-notes = &കുറിപ്പുകൾ തിരഞ്ഞെടുക്കുക
qt-accel-support-anki = Anki-യെ &പിന്തുണയ്ക്കുക ...
qt-accel-switch-profile = പ്രൊഫൈൽ &സ്വിച്ചുചെയ്യുക
qt-accel-tools = &ഉപകരണങ്ങൾ
qt-accel-undo = &പഴയപടിയാക്കുക
qt-accel-redo = &പുനര്‍നിര്‍വ്വഹിക്കുക
qt-accel-set-due-date = &നിശ്ചിത തീയതി സജ്ജമാക്കുക
qt-accel-forget = &മറക്കുക
qt-accel-view = &കാണുക
qt-accel-full-screen = &ഫുൾ സ്ക്രീൻ മാറ്റുക
qt-accel-layout = &ലേഔട്ട്
qt-accel-layout-auto = &ഓട്ടോ
qt-accel-layout-vertical = &വെർട്ടിക്കൽ
qt-accel-layout-horizontal = &ഹൊറിസോണ്ടൽ
qt-accel-zoom-in = സൂം &ഇൻ
qt-accel-zoom-out = സൂം &ഔട്ട്
qt-accel-reset-zoom = സൂം &റീസെറ്റ് ചെയ്യുക
qt-accel-toggle-sidebar = സൈഡ്ബാർ മാറ്റുക
qt-accel-zoom-editor-in = എഡിറ്റർ സൂം &ഇൻ
qt-accel-zoom-editor-out = എഡിറ്റർ സൂം &ഔട്ട്
qt-accel-create-backup = &ബാക്കപ്പ് തയ്യാറാക്കുക
qt-accel-load-backup = ബാക്കപ്പിലേക്ക് &തിരിച്ചുപോവുക
qt-accel-upgrade-downgrade = അപ്‌ഗ്രേഡ്/ഡൗൺഗ്രേഡ്
