adding-add-shortcut-ctrlandenter = Добавить запись (Ctrl+Enter)
adding-added = Успешно добавлено
adding-discard-current-input = Отказаться от введенных данных?
adding-keep-editing = Продолжить редактирование
adding-edit = Редактировать "{ $val }"
adding-history = История
adding-note-deleted = (запись удалена)
adding-shortcut = Горячая клавиша: { $val }
adding-the-first-field-is-empty = Первое поле пусто.
adding-you-have-a-cloze-deletion-note = Тип записи - дополнить пропуск, но вы не сделали пропусков. Продолжить?
adding-cloze-outside-cloze-notetype = Пропуски можно использовать только в типах записей с пропусками.
adding-cloze-outside-cloze-field = "Пробелы" может использоваться только для полей с фильтром "Заполнить пробелы". Обычно это первое поле.
