editing-actual-size = Переключить размер
editing-add-media = Добавить медиафайл
editing-align-left = Выровнять по левому краю
editing-align-right = Выровнять по правому краю
editing-an-error-occurred-while-opening = При открытии { $val } произошла ошибка
editing-attach-picturesaudiovideo = Прикрепить изображение/аудиофайл/видео
editing-bold-text = Жирный шрифт
editing-cards = Карточки
editing-center = Центр
editing-change-color = Изменить цвет
editing-cloze-deletion = Заполнить пропуск (новая карточка)
editing-cloze-deletion-repeat = Заполнить пропуск (та же карточка)
editing-copy-image = Копировать изображение
editing-couldnt-record-audio-have-you-installed = Не получается записать звук. У вас установлен "lame"?
editing-customize-card-templates = Настроить шаблоны карточек
editing-customize-fields = Изменить поля
editing-cut = Вырезать
editing-double-click-image = щёлкните дважды на картинку
editing-double-click-to-expand = (щёлкните дважды, чтобы увеличить)
editing-double-click-to-collapse = Щелкните дважды чтобы свернуть
editing-edit-current = Редактировать
editing-edit-html = Редактировать HTML
editing-fields = Поля
editing-float-left = Слева
editing-float-right = Справа
editing-float-none = Выключить обтекание
editing-indent = Увеличить отступ
editing-italic-text = Курсив
editing-jump-to-tags-with-ctrlandshiftandt = Перейти к меткам (Ctrl+Shift+T)
editing-justify = Выровнять
editing-latex = LaTeX
editing-latex-equation = Формула LaTeX
editing-latex-math-env = Окружение LaTeX
editing-mathjax-block = MathJax с выключкой
editing-mathjax-chemistry = MathJax для химии
editing-mathjax-inline = MathJax в строке
editing-mathjax-placeholder = Нажмите { $accept } для подтверждения или { $newline } для новой строки
editing-media = Медиафайлы
editing-open-image = Открыть изображение
editing-show-in-folder = Показать в папке
editing-ordered-list = Упорядоченный список
editing-outdent = Сократить отступ
editing-paste = Вставить
editing-record-audio = Записать аудиофайл
editing-remove-formatting = Удалить форматирование
editing-restore-original-size = Восстановить размер
editing-select-remove-formatting = Выбрать форматирование для удаления
editing-show-duplicates = Показать повторы
editing-subscript = Подстрочный знак
editing-superscript = Надстрочный знак
editing-tags = Метки
editing-tags-add = Добавить метку
editing-tags-copy = Копировать метку
editing-tags-remove = Удалить метки
editing-tags-select-all = Выбрать все метки
editing-text-color = Цвет текста
editing-text-highlight-color = Цвет выделения текста
editing-to-make-a-cloze-deletion-on = Чтобы добавить заполнение пропусков к существующей записи, необходимо сначала изменить её тип на «Задание с пропусками», выбрав «Записи» — «Сменить тип записи».
editing-toggle-html-editor = HTML-редактор
editing-toggle-visual-editor = Визуальный редактор
editing-toggle-sticky = Сохранять значение
editing-expand = Развернуть
editing-collapse = Свернуть
editing-expand-field = Развернуть поле
editing-collapse-field = Свернуть поле
editing-underline-text = Подчеркивание
editing-unordered-list = Неупорядоченный список
editing-warning-cloze-deletions-will-not-work = Внимание! Заполнение пропусков не будет работать, пока вы не измените тип карточки на «Пропуски».
editing-mathjax-preview = Предпросмотр MathJax
editing-shrink-images = Уменьшить изображения
editing-close-html-tags = Закрывать теги HTML
editing-from-clipboard = Из буфера обмена
editing-alignment = Выравнивание
editing-equations = Уравнения
editing-no-image-found-on-clipboard = В буфере обмена не найдено картики
editing-image-occlusion-mode = Режим скрытия части изображений
editing-image-occlusion-zoom-out = Отдалить
editing-image-occlusion-zoom-in = Приблизить
editing-image-occlusion-zoom-reset = Сбросить приближение
editing-image-occlusion-toggle-translucent = включить/выключить полупрозрачность
editing-image-occlusion-delete = Удалить
editing-image-occlusion-duplicate = Создать копию
editing-image-occlusion-group = Выбрать группу
editing-image-occlusion-ungroup = Распустить группу
editing-image-occlusion-select-all = Выделить всё
editing-image-occlusion-alignment = Выравнивание
editing-image-occlusion-align-left = Выравнивание по левому краю
editing-image-occlusion-align-h-center = Выровнять центры по горизонтали
editing-image-occlusion-align-right = Выравнивание по правому краю
editing-image-occlusion-align-top = Выравнивание по центру сверха
editing-image-occlusion-align-v-center = Выровнять центры по вертикали
editing-image-occlusion-align-bottom = Выравнивание по низу
editing-image-occlusion-select-tool = Выбрать
editing-image-occlusion-zoom-tool = Увеличить/Уменьшить
editing-image-occlusion-rectangle-tool = Прямоугольник
editing-image-occlusion-ellipse-tool = Овал
editing-image-occlusion-polygon-tool = Многоугольник
editing-image-occlusion-text-tool = Текст
editing-image-occlusion-fill-tool = Заполнить цветом
editing-image-occlusion-toggle-mask-editor = Переключатель изменения маски
editing-image-occlusion-reset = Удалить сделанные скрытия части картинки
editing-image-occlusion-confirm-reset = Вы уверены, что хотите удалить сделанные скрытия части картинки?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Редактор HTML
