profiles-anki-could-not-read-your-profile = Anki не смогла прочесть ваш профиль. Размеры окон и учётная запись сброшены.
profiles-anki-could-not-rename-your-profile = Anki не смогла переименовать ваш профиль, потому что не смогла переименовать папку на диске. Проверьте, что у вас права записи в «Документы» и папку Anki и что другие программы не используют эти папку. Потом попробуйте снова.
profiles-folder-already-exists = Папка уже существует.
profiles-open = Открыть
profiles-open-backup = Открыть резервную копию...
profiles-please-remove-the-folder-and = Удалите папку { $val } и попробуйте снова.
profiles-profile-corrupt = Профиль повреждён
profiles-profiles = Профили
profiles-quit = Выйти
profiles-user-1 = 1-й пользователь
profiles-confirm-lang-choice = Вы точно хотите переключить язык интерфейса Anki на { $lang }?
profiles-could-not-create-data-folder = Anki не смогла создать свою папку данных. Пожалуйста, ознакомьтесь с разделом "Местоположение файлов" в руководстве и убедитесь, что местоположение не "только для чтения".
profiles-prefs-corrupt-title = Настройки повреждены
profiles-prefs-file-is-corrupt = Файл Anki pres21.db был повреждён и восстановлен. Если вы использовали несколько профилей, пожалуйста, добавьте их обратно, используя те же имена для восстановления карточек.
profiles-profile-does-not-exist = Запрошенный профиль не существует
profiles-creating-backup = Создание резервной копии...
profiles-backup-created = Резервная копия создана.
profiles-backup-creation-failed = Не удалось создать резервную копию: { $reason }
profiles-backup-unchanged = Нет изменений с последнего раза
