// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

import mdiAlignHorizontalCenter_ from "@mdi/svg/svg/align-horizontal-center.svg";
import mdiAlignHorizontalLeft_ from "@mdi/svg/svg/align-horizontal-left.svg";
import mdiAlignHorizontalRight_ from "@mdi/svg/svg/align-horizontal-right.svg";
import mdiAlignVerticalBottom_ from "@mdi/svg/svg/align-vertical-bottom.svg";
import mdiAlignVerticalCenter_ from "@mdi/svg/svg/align-vertical-center.svg";
import mdiAlignVerticalTop_ from "@mdi/svg/svg/align-vertical-top.svg";
import mdiChevronDown_ from "@mdi/svg/svg/chevron-down.svg";
import mdiClose_ from "@mdi/svg/svg/close.svg";
import mdiCodeTags_ from "@mdi/svg/svg/code-tags.svg";
import mdiCopy_ from "@mdi/svg/svg/content-copy.svg";
import mdiCursorDefaultOutline_ from "@mdi/svg/svg/cursor-default-outline.svg";
import mdiDeleteOutline_ from "@mdi/svg/svg/delete-outline.svg";
import mdiEllipseOutline_ from "@mdi/svg/svg/ellipse-outline.svg";
import mdiEye_ from "@mdi/svg/svg/eye.svg";
import mdiFormatAlignCenter_ from "@mdi/svg/svg/format-align-center.svg";
import mdiFormatBold_ from "@mdi/svg/svg/format-bold.svg";
import mdiFormatItalic_ from "@mdi/svg/svg/format-italic.svg";
import mdiFormatUnderline_ from "@mdi/svg/svg/format-underline.svg";
import mdiGroup_ from "@mdi/svg/svg/group.svg";
import mdiZoomReset_ from "@mdi/svg/svg/magnify-expand.svg";
import mdiZoomOut_ from "@mdi/svg/svg/magnify-minus-outline.svg";
import mdiZoomIn_ from "@mdi/svg/svg/magnify-plus-outline.svg";
import mdiMagnifyScan_ from "@mdi/svg/svg/magnify-scan.svg";
import mdiRectangleOutline_ from "@mdi/svg/svg/rectangle-outline.svg";
import mdiRedo_ from "@mdi/svg/svg/redo.svg";
import mdiRefresh_ from "@mdi/svg/svg/refresh.svg";
import mdiSelectAll_ from "@mdi/svg/svg/select-all.svg";
import mdiSquare_ from "@mdi/svg/svg/square.svg";
import mdiTextBox_ from "@mdi/svg/svg/text-box.svg";
import mdiUndo_ from "@mdi/svg/svg/undo.svg";
import mdiUnfoldMoreHorizontal_ from "@mdi/svg/svg/unfold-more-horizontal.svg";
import mdiUngroup_ from "@mdi/svg/svg/ungroup.svg";
import mdiVectorPolygonVariant_ from "@mdi/svg/svg/vector-polygon-variant.svg";
import mdiViewDashboard_ from "@mdi/svg/svg/view-dashboard.svg";

import { imageLink } from "$lib/components/icons";

export const mdiAlignHorizontalCenter = imageLink(mdiAlignHorizontalCenter_);
export const mdiAlignHorizontalLeft = imageLink(mdiAlignHorizontalLeft_);
export const mdiAlignHorizontalRight = imageLink(mdiAlignHorizontalRight_);
export const mdiAlignVerticalBottom = imageLink(mdiAlignVerticalBottom_);
export const mdiAlignVerticalCenter = imageLink(mdiAlignVerticalCenter_);
export const mdiAlignVerticalTop = imageLink(mdiAlignVerticalTop_);
export const mdiChevronDown = imageLink(mdiChevronDown_);
export const mdiClose = imageLink(mdiClose_);
export const mdiCodeTags = imageLink(mdiCodeTags_);
export const mdiCopy = imageLink(mdiCopy_);
export const mdiCursorDefaultOutline = imageLink(mdiCursorDefaultOutline_);
export const mdiDeleteOutline = imageLink(mdiDeleteOutline_);
export const mdiEllipseOutline = imageLink(mdiEllipseOutline_);
export const mdiEye = imageLink(mdiEye_);
export const mdiFormatAlignCenter = imageLink(mdiFormatAlignCenter_);
export const mdiFormatBold = imageLink(mdiFormatBold_);
export const mdiFormatItalic = imageLink(mdiFormatItalic_);
export const mdiFormatUnderline = imageLink(mdiFormatUnderline_);
export const mdiGroup = imageLink(mdiGroup_);
export const mdiZoomReset = imageLink(mdiZoomReset_);
export const mdiZoomOut = imageLink(mdiZoomOut_);
export const mdiZoomIn = imageLink(mdiZoomIn_);
export const mdiMagnifyScan = imageLink(mdiMagnifyScan_);
export const mdiRectangleOutline = imageLink(mdiRectangleOutline_);
export const mdiRedo = imageLink(mdiRedo_);
export const mdiRefresh = imageLink(mdiRefresh_);
export const mdiSelectAll = imageLink(mdiSelectAll_);
export const mdiSquare = imageLink(mdiSquare_);
export const mdiTextBox = imageLink(mdiTextBox_);
export const mdiUndo = imageLink(mdiUndo_);
export const mdiUnfoldMoreHorizontal = imageLink(mdiUnfoldMoreHorizontal_);
export const mdiUngroup = imageLink(mdiUngroup_);
export const mdiVectorPolygonVariant = imageLink(mdiVectorPolygonVariant_);
export const mdiViewDashboard = imageLink(mdiViewDashboard_);
