card-stats-added = Aggiunta
card-stats-first-review = Prima ripetizione
card-stats-latest-review = Ripetizione più recente
card-stats-interval = Intervallo
card-stats-ease = Facilità
card-stats-review-count = Ripetizioni
card-stats-lapse-count = Errori
card-stats-average-time = Durata media
card-stats-total-time = Durata totale
card-stats-new-card-position = Posizione
card-stats-card-template = Tipo di carta
card-stats-note-type = Tipo di nota
card-stats-deck-name = Mazzo
card-stats-preset = Preimpostazione
card-stats-note-id = ID nota
card-stats-card-id = ID carta
card-stats-review-log-rating = Valutazione
card-stats-review-log-type = Tipo
card-stats-review-log-date = Data
card-stats-review-log-time-taken = Durata
card-stats-review-log-type-learn = In apprendimento
card-stats-review-log-type-review = Ripasso
card-stats-review-log-type-relearn = In riapprendimento
card-stats-review-log-type-filtered = Filtrato
card-stats-review-log-type-manual = Manuale
card-stats-review-log-type-rescheduled = Ripianificate
card-stats-review-log-elapsed-time = Tempo trascorso
card-stats-no-card = (Nessuna carta da visualizzare.)
card-stats-custom-data = Dati personalizzati
card-stats-fsrs-stability = Stabilità
card-stats-fsrs-difficulty = Difficoltà
card-stats-fsrs-retrievability = Rammentabilità
card-stats-fsrs-forgetting-curve-title = Curva dell'oblio (dimenticanza nel tempo)
card-stats-fsrs-forgetting-curve-first-week = Prima settimana
card-stats-fsrs-forgetting-curve-first-month = Primo mese
card-stats-fsrs-forgetting-curve-first-year = Primo anno
card-stats-fsrs-forgetting-curve-all-time = Tutto il periodo
card-stats-fsrs-forgetting-curve-probability-of-recalling = Probabilità di richiamo
card-stats-fsrs-forgetting-curve-desired-retention = Ritenzione desiderata

## Window Titles

card-stats-current-card = Carta attuale ({ $context })
card-stats-previous-card = Carta precedente ({ $context })
