decks-add-new-deck-ctrlandn = Aggiungi un nuovo mazzo (Ctrl+N)
decks-build = Crea
decks-cards-selected-by = carte selezionate per
decks-create-deck = Crea mazzo
decks_create_even_if_empty = Crea/aggiorna questo mazzo anche se vuoto
decks-custom-steps-in-minutes = Passi personalizzati (in minuti)
decks-deck = Mazzo
decks-decreasing-intervals = Intervalli decrescenti
decks-delete-deck = Elimina mazzo
decks-enable-second-filter = Abilita secondo filtro
decks-filter = Filtro:
decks-filter-2 = Filtro 2
decks-get-shared = Ottieni mazzi condivisi
decks-import-file = Importa file
decks-increasing-intervals = Intervalli crescenti
decks-latest-added-first = Dapprima aggiunte più recentemente
decks-limit-to = Limita a
decks-minutes = minuti
decks-most-lapses = Maggior numero di errori
decks-new-deck-name = Nome del nuovo mazzo:
decks-no-deck = [nessun mazzo]
decks-oldest-seen-first = Più vecchie visualizzate per prime
decks-order-added = Ordine di aggiunta
decks-order-due = Ordine di scadenza
decks-please-select-something = Per piacere, seleziona qualcosa.
decks-random = Casuale
decks-relative-overdueness = Ritardo relativo
decks-repeat-failed-cards-after = Ripeti carte sbagliate dopo
# e.g. "Delay for Again", "Delay for Hard", "Delay for Good"
decks-delay-for-button = Intervallo per { $button }
decks-reschedule-cards-based-on-my-answers = Ripianifica le carte considerando le mie risposte in questo mazzo
decks-study = Studia
decks-study-deck = Studia mazzo
decks-filtered-deck-search-empty = Nessuna carta corrisponde ai criteri di ricerca forniti. Alcune carte potrebbero essere state escluse poiché si trovano in un altro mazzo filtrato, o sono sospese.
decks-unmovable-cards = Mostra le carte escluse
decks-learn-header = Impara
# The count of cards waiting to be reviewed
decks-review-header = Ripasso
decks-zero-minutes-hint = (0 = riporta la carta al mazzo originale)
