sync-wrong-pass = आन्कीवेब आयडी किंव्हा पासवर्ड चुकीचा होता; पुन्हा प्रयत्न करून बघा.
sync-cancel-button = रद्द करा
sync-checking = तपासत आहे.....
sync-ankiweb-id-label = आन्कीवेब आयडी:
sync-password-label = परवलीचा शब्द:
sync-connecting = जोडणी करत आहे...
