adding-add-shortcut-ctrlandenter = Aldoni (fulmoklavo: stira+eniga)
adding-added = Aldonita
adding-discard-current-input = Forĵeti nunan enigon?
adding-keep-editing = Daŭrigi redaktadon
adding-edit = Redakti "{ $val }"
adding-history = Antaŭaĵo
adding-note-deleted = (Noto estas forigita)
adding-shortcut = Fulmoklavo: { $val }
adding-the-first-field-is-empty = La unua kampo estas malplena.
adding-you-have-a-cloze-deletion-note = Vi elektis la nototipon truteksto, sed ne faris truojn. Daŭrigi?
adding-cloze-outside-cloze-notetype = Truoj estas uzeblaj nur en trutekstaj nototipoj.
adding-cloze-outside-cloze-field = Truoj estas nur uzeblaj en kampoj, kiuj uzas la filtrilon 'cloze:'.Tio ordinare estas la unua kampo.
