editing-actual-size = Baskuligi veran grandon
editing-add-media = Aldoni aŭdvidaĵon
editing-align-left = Ĝisrandigi maldekstren
editing-align-right = Ĝisrandigi dekstren
editing-an-error-occurred-while-opening = Okazis eraro dum malfermo de { $val }
editing-attach-picturesaudiovideo = Aldoni bildon/sonon/filmeton
editing-bold-text = Grasa teksto
editing-cards = Kartoj
editing-center = Centrigi
editing-change-color = Ŝanĝi koloron
editing-cloze-deletion = Truo en teksto (nova karto)
editing-cloze-deletion-repeat = Truo en teksto (la sama karto)
editing-copy-image = Kopii bildon
editing-couldnt-record-audio-have-you-installed = Ne povis registri sonon. Ĉu vi instalis la programon “lame”?
editing-customize-card-templates = Alĝustigi kartoŝablonojn
editing-customize-fields = Alĝustigi kampojn
editing-cut = Eltondi
editing-double-click-image = duoble alklaku bildon
editing-double-click-to-expand = duoble alklaku por etendi
editing-double-click-to-collapse = duoble alklaku por maletendi
editing-edit-current = Redakti nunan
editing-edit-html = Redakti HTML
editing-fields = Kampoj
editing-float-left = Alkroĉi maldekstre
editing-float-right = Alkroĉi dekstre
editing-float-none = Ne alkroĉi
editing-indent = Pliigi krommarĝenon
editing-italic-text = Kursiva teksto
editing-jump-to-tags-with-ctrlandshiftandt = Salti al etikedoj per Stir’+Majusklig’+T
editing-justify = Ĝisrandigi ambaŭflanken
editing-latex = LaTeX
editing-latex-equation = Formulo LaTeX
editing-latex-math-env = Matematika ĉirkaŭaĵo LaTeX
editing-mathjax-block = Bloko MathJax
editing-mathjax-chemistry = Ĥemia formulo MathJax
editing-mathjax-inline = Enlinia MathJax
editing-mathjax-placeholder = Premu la klavon { $accept } por akcepti aŭ { $newline } por enmeti linion.
editing-media = Aŭdvidaĵo
editing-open-image = Malfermi bildon
editing-show-in-folder = Montri en dosierujo
editing-ordered-list = Ordigita listo
editing-outdent = Etigi krommarĝenon
editing-paste = Alglui
editing-record-audio = Registri sonon
editing-remove-formatting = Forviŝi tekstaranĝon
editing-restore-original-size = Restarigi originalan grandon
editing-select-remove-formatting = Selekte forviŝi tekstaranĝon
editing-show-duplicates = Montri duoblaĵojn
editing-subscript = Malalta skribo
editing-superscript = Alta skribo
editing-tags = Etikedoj
editing-tags-add = Aldoni etikedon
editing-tags-copy = Kopii etikedojn
editing-tags-remove = Forigi etikedojn
editing-tags-select-all = Elekti ĉiujn etikedojn
editing-text-color = Koloro de teksto
editing-text-highlight-color = Koloro de sign-emfazo
editing-to-make-a-cloze-deletion-on = Por krei truon en teksto de la ekzista noto, unue ŝanĝu ĝian nototipon al “Truteksto” per la menuo Noto → Ŝanĝi nototipon.
editing-toggle-html-editor = Baskuligi HTML-redaktilon
editing-toggle-visual-editor = Baskuligi pervidan redaktilon
editing-toggle-sticky = Baskuligi alpinglitan
editing-expand = Etendi
editing-collapse = Maletendi
editing-expand-field = Etendi kampon
editing-collapse-field = Maletendi kampon
editing-underline-text = Substrekita teksto
editing-unordered-list = Neordigita listo
editing-warning-cloze-deletions-will-not-work = Averto! Truoj en teksto ne funkcios, ĝis vi ŝanĝos la nototipon al “Truteksto”.
editing-mathjax-preview = Antaŭmontri MathJax
editing-shrink-images = Etigi bildojn
editing-close-html-tags = Aŭtomate fermi HTML-etikedojn
editing-from-clipboard = El tondujo
editing-alignment = Ĝisrandigo
editing-equations = Formuloj
editing-no-image-found-on-clipboard = En tondujo estas neniu bildo.
editing-image-occlusion-mode = Reĝimo de vualado
editing-image-occlusion-zoom-out = Malgrandigi
editing-image-occlusion-zoom-in = Pligrandigi
editing-image-occlusion-zoom-reset = Nuligi pligrandigon
editing-image-occlusion-toggle-translucent = Baskuligi travideblon
editing-image-occlusion-delete = Forigi
editing-image-occlusion-duplicate = Duobligi
editing-image-occlusion-group = Grupigi elektitajn
editing-image-occlusion-ungroup = Malgrupigi elektitajn
editing-image-occlusion-select-all = Elekti ĉiujn
editing-image-occlusion-alignment = Ĝisrandigo
editing-image-occlusion-align-left = Ĝisrandigi maldekstren
editing-image-occlusion-align-h-center = Centrigi horizontale
editing-image-occlusion-align-right = Ĝisrandigi dekstren
editing-image-occlusion-align-top = Ĝisrandigi supren
editing-image-occlusion-align-v-center = Centrigi vertikale
editing-image-occlusion-align-bottom = Ĝisrandigi malsupren
editing-image-occlusion-select-tool = Elekti
editing-image-occlusion-zoom-tool = Pligrandigi
editing-image-occlusion-rectangle-tool = Ortangulo
editing-image-occlusion-ellipse-tool = Elipso
editing-image-occlusion-polygon-tool = Plurangulo
editing-image-occlusion-text-tool = Teksto
editing-image-occlusion-fill-tool = Plenigi per koloro
editing-image-occlusion-toggle-mask-editor = Baskuligi redaktilon de masko
editing-image-occlusion-reset = Nuligi vualon de bildo
editing-image-occlusion-confirm-reset = Ĉu vi certe volas nuligi tiun ĉi vualon de bildo?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML-redaktilo
