custom-study-cards = kaarte
custom-study-cards-from-the-deck = kaarte van die pak
custom-study-choose-tags = Kies Etikette
custom-study-custom-study-session = Pasmaker studie sessie
custom-study-due-cards-only = Uitstaande kaarte alleenlik
custom-study-increase-todays-new-card-limit = Verhoog vandag se nuwe kaart limiet
custom-study-increase-todays-new-card-limit-by = Verhoog vandag se nuwe kaart limiet met
custom-study-increase-todays-review-card-limit = Verhoog vandag se hersienings kaart limiet
custom-study-increase-todays-review-limit-by = Verhoog vandag se hersienings limiet met
custom-study-new-cards-only = Alleenlik nuwe kaarte
custom-study-no-cards-matched-the-criteria-you = Geen kaarte stem ooreen met die kriteria wat u verskaf het nie.
custom-study-preview-new-cards = Voorskou van nuwe kaarte
custom-study-preview-new-cards-added-in-the = Voorskou van nuwe kaarte bygevoeg in die laaste
custom-study-require-one-or-more-of-these = Vereis een of meer van hierdie etikette:
custom-study-review-ahead = Hersien vooruit
custom-study-review-ahead-by = Hersien vooruit met
custom-study-review-cards-forgotten-in-last = Hersien vergete kaarte in die laaste
custom-study-review-forgotten-cards = Hersien vergete kaarte
custom-study-select = Selekteer
custom-study-select-tags-to-exclude = Selekteer etikette om uit te sluit:
custom-study-selective-study = Selektiewe Studie
custom-study-study-by-card-state-or-tag = Studeer deur kaart status of kategorie
