fields-add-field = Voeg Veld By
fields-delete-field-from = Skrap veld van { $val }?
fields-editing-font = Font wysiging
fields-field = Veld:
fields-field-name = Veld naam:
fields-fields-for = Velde vir { $val }
fields-new-position-1 = Nuwe posisie (1 ... { $val } ):
fields-notes-require-at-least-one-field = Notas vereis ten minste een veld.
fields-remember-last-input-when-adding = Onthou die laaste toevoer wanneer bygevoeg word
fields-reverse-text-direction-rtl = Teenoorgestelde teks rigting (RNL)
fields-size = Grootte:
fields-sort-by-this-field-in-the = Sorteer met hierdie veld in die leser
fields-that-field-name-is-already-used = Die veld naam is reeds gebruik.
