notetypes-front-field = Voorkant
notetypes-back-field = Terug
notetypes-add-reverse-field = Voeg Keersy By
notetypes-text-field = Teks
notetypes-basic-name = Basies
notetypes-basic-reversed-name = Basiese (en omgekeerde kaart)
notetypes-basic-optional-reversed-name = Basiese (opsioneel omgekeerde kaart)
notetypes-card-2-name = Kaart 2
notetypes-card-1-name = Kaart 1
notetypes-add = Voeg by: { $val }
notetypes-add-note-type = Voeg Nota Tipe By
notetypes-cards = Kaarte...
notetypes-clone = Kloon: { $val }
notetypes-copy = { $val } kopie
notetypes-delete-this-note-type-and-all = Skrap hierdie nota tipe en al sy kaarte?
notetypes-delete-this-unused-note-type = Skrap hierdie ongebruikte nota tipe?
notetypes-fields = Velde ...
notetypes-footer = Voetskrif
notetypes-header = Kopskrif
notetypes-note-types = Nota Tipes
notetypes-options = Opsies...
notetypes-please-add-another-note-type-first = Voeg asseblief eers 'n ander nota tipe by.
notetypes-type = Tipe
