editing-actual-size = Gerçek boyutu aç/kapat
editing-add-media = Ortam Ekle
editing-align-left = Sola hizala
editing-align-right = Sağa hizala
editing-an-error-occurred-while-opening = { $val } 'i açarken bir hata oluştu.
editing-attach-picturesaudiovideo = Resim/ses/video iliştir
editing-bold-text = Kalın metin
editing-cards = Kartlar
editing-change-color = Rengi değiştir
editing-copy-image = Resmi kopyala
editing-couldnt-record-audio-have-you-installed = Ses kaydı yapılamadı. "lame"i yüklediniz mi?
editing-cut = Kes
editing-double-click-image = resmi çift tıklama
editing-double-click-to-expand = genişletmek için çift tıklama
editing-double-click-to-collapse = daraltmak için çift tıklama
editing-edit-current = Geçerli olanı düzenle
editing-edit-html = HTML'yi düzenle
editing-fields = Alanlar
editing-italic-text = İtalik metin
editing-jump-to-tags-with-ctrlandshiftandt = Ctrl+Shift+T ile etiketlere geçiş yapın
editing-latex = LaTeX
editing-latex-equation = LaTeX eşitliği
editing-latex-math-env = LaTeX matematik ort.
editing-mathjax-block = MathJax öbeği
editing-mathjax-chemistry = MathJax kimyası
editing-mathjax-inline = Satır içi MathJax
editing-media = İçerik
editing-open-image = Resmi aç
editing-show-in-folder = Klasörde göster
editing-outdent = Girintiyi azalt
editing-paste = Yapıştır
editing-record-audio = Ses kaydet
editing-restore-original-size = Eski boyutuna geri döndür
editing-show-duplicates = Yinelenenleri Göster
editing-tags = Etiketler
editing-tags-add = Etiket ekle
editing-tags-copy = Etiketleri kopyala
editing-tags-remove = Etiketleri kaldır
editing-tags-select-all = Tüm etiketleri seç
editing-text-color = Metin rengi
editing-text-highlight-color = Metin vurgu rengi
editing-toggle-html-editor = HTML Düzenleyiciyi Aç/Kapat
editing-toggle-visual-editor = Görsel Düzenleyiciyi Aç/Kapat
editing-toggle-sticky = Yapışkanlığı Aç/Kapat
editing-expand = Genişlet
editing-collapse = Daralt
editing-expand-field = Alanı genişlet
editing-collapse-field = Alanı daralt
editing-underline-text = Metini altını çiz
editing-unordered-list = Sıralanmamış liste
editing-mathjax-preview = MathJax Önizlemesi
editing-close-html-tags = HTML etiketlerini otomatik olarak kapat
editing-from-clipboard = Panodan
editing-alignment = Hizlama
editing-image-occlusion-zoom-out = Uzaklaştır
editing-image-occlusion-zoom-in = Yakınlaştır
editing-image-occlusion-toggle-translucent = Yarı Saydamlığı Aç/Kapat
editing-image-occlusion-delete = Sil
editing-image-occlusion-duplicate = Kopya oluştur
editing-image-occlusion-group = Grup Seçimi
editing-image-occlusion-select-all = Tümünü Seç
editing-image-occlusion-alignment = Hizlama
editing-image-occlusion-align-left = Sola Hizala
editing-image-occlusion-align-h-center = Yatay Ortalara Hizala
editing-image-occlusion-align-right = Sağa Hizala
editing-image-occlusion-align-top = Üste Hizala
editing-image-occlusion-align-v-center = Dikey Ortalara Hizala
editing-image-occlusion-align-bottom = Alta Hizala
editing-image-occlusion-select-tool = Seç
editing-image-occlusion-rectangle-tool = Dikdörtgen
editing-image-occlusion-ellipse-tool = Oval
editing-image-occlusion-polygon-tool = Çokgen
editing-image-occlusion-text-tool = Metin
editing-image-occlusion-fill-tool = Renkle Doldur
editing-image-occlusion-toggle-mask-editor = Örtü Düzenleyicisini Aç/Kapat

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML Düzenleyici
