preferences-automatically-sync-on-profile-openclose = Açma/kapama anında profili otomatik olarak senkronize et
preferences-backups = Yedekler
preferences-change-deck-depending-on-note-type = Not türüne göre desteyi değiştir
preferences-changes-will-take-effect-when-you = Değişiklikler, Anki'yi yeniden başlattığınızda etkili olacaktır.
preferences-language = Dil
preferences-interrupt-current-audio-when-answering = Cevap verirken mevcut sesi kes
preferences-learn-ahead-limit = Önceden öğrenme sınırı
preferences-mins = dk
preferences-network = Ağ
preferences-next-day-starts-at = Ertesi gün başlar
preferences-on-next-sync-force-changes-in = Bir sonraki senkronizasyonda değişiklikleri tek yönlü yap
preferences-paste-clipboard-images-as-png = Pano resmini PNG olarak yapıştır
preferences-generate-latex-images-automatically = LaTeX resimleri oluşturun (güvenlik riski)
preferences-latex-generation-disabled = Tercihlerde LaTeX resim oluşturma özelliği devre dışı bırakıldı.
preferences-periodically-sync-media = Ortamı periyodik olarak senkronize edin
preferences-please-restart-anki-to-complete-language = Dil değişikliğini tamamlamak için lütfen Anki'yi yeniden başlatın.
preferences-preferences = Tercihler
preferences-scheduling = Yeniden Planlama
preferences-show-next-review-time-above-answer = Cevap düğmelerinin üstünde sonraki gözden geçirme süresini göster
preferences-spacebar-rates-card = Boşluk tuşu (veya enter) da kartın cevabını gösterir
preferences-show-play-buttons-on-cards-with = Sesli kartlarda oynatma düğmelerini göster
preferences-show-remaining-card-count = Kalan kart sayısını göster
preferences-some-settings-will-take-effect-after = Bazı ayarlar Anki'yi yeniden başlattığınızdan sonra etkili olacaktır.
preferences-tab-synchronisation = Senkronizasyon
preferences-synchronize-audio-and-images-too = Ses ve resimleri de senkronize edin
preferences-login-successful-sync-now = Giriş başarılı. Tercihler kaydedilip senkronizasyon yapılsın mı?
preferences-timebox-time-limit = Zaman sınırı
preferences-user-interface-size = Kullanıcı arayüzü boyutu
preferences-you-can-restore-backups-via-fileswitch = Yedeklemeleri Dosya > Profil Değiştir yoluyla geri yükleyebilirsiniz.
preferences-default-search-text = Varsayılan arama metni
preferences-default-search-text-example = örn. "deck:current"
preferences-theme = Tema
preferences-theme-follow-system = Sistemi Takip Et
preferences-theme-light = Açık
preferences-theme-dark = Koyu
preferences-v3-scheduler = V3 planlayıcı
preferences-check-for-updates = Program güncellemelerini kontrol et
preferences-daily-backups = Saklanacak günlük yedeklemeler:
preferences-weekly-backups = Saklanacak haftalık yedeklemeler:
preferences-monthly-backups = Saklanacak aylık yedeklemeler:
preferences-minutes-between-backups = Otomatik yedeklemeler arasındaki dakika:
preferences-reduce-motion = Hareketi azalt
preferences-reduce-motion-tooltip = Kullanıcı arayüzünün çeşitli animasyonlarını ve geçişlerini devre dışı bırakın
preferences-custom-sync-url-disclaimer = İleri düzey kullanıcılar için - lütfen kılavuza bakın
preferences-hide-top-bar-during-review = Gözden geçirme sırasında üst çubuğu gizle
preferences-hide-bottom-bar-during-review = Gözden geçirme sırasında alt çubuğu gizle
preferences-always = Her Zaman
preferences-full-screen-only = Yalnızca tam ekran
preferences-appearance = Görünüm
preferences-general = Genel
preferences-style = Stil
preferences-review = Gözden Geçirme
preferences-answer-keys = Cevap anahtarları
preferences-minimalist-mode = Minimalist mod
preferences-minimalist-mode-tooltip = Arayüzü daha kompakt/daha sade hale getirin
preferences-browsing = Göz Atma
preferences-default-deck = Varsayılan deste
preferences-account = AnkiWeb Hesabı
preferences-note = Not
preferences-scheduler = Planlayıcı
preferences-user-interface = Kullanıcı arayüzü
preferences-import-export = İçe/Dışa Aktarma
preferences-network-timeout = Ağ zaman aşımı
preferences-reset-window-sizes = Pencere Boyutlarını Sıfırla
preferences-reset-window-sizes-complete = Pencere boyutları ve konumları sıfırlandı.
preferences-shortcut-placeholder = Kullanılmayan bir kısayol tuşu girin veya devre dışı bırakmak için boş bırakın.
preferences-third-party-services = Üçüncü Taraf Hizmetleri
preferences-ankihub-intro = AnkiHub, ortak çalışmaya dayalı deste düzenleme ve ek çalışma araçları sunar. Bazı özelliklere erişmek için ücretli abonelik gereklidir.
preferences-third-party-description = Üçüncü taraf hizmetleri Anki ile bağlantılı değildir ve Anki tarafından desteklenmemektedir. Bu hizmetlerin kullanımı ücretli olabilir.

## URL scheme related

preferences-url-scheme-allow-once = Bir Kez İzin Ver
preferences-url-scheme-always-allow = Her Zaman İzin Ver

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = Temel
preferences-media = İçerik
