profiles-anki-could-not-read-your-profile = Anki profil verilerini okuyamadı. Pencere büyüklüğü ve senkronize oturum detayları unutuldu.
profiles-anki-could-not-rename-your-profile = Anki, disk üzerindeki profil klasörünü yeniden adlandıramadığı için profilinizi yeniden adlandıramadı. Lütfen Documents / Anki'ye yazma izninizin olduğundan ve diğer hiçbir programın profil klasörünüze erişemediğinden emin olduktan sonra tekrar deneyin.
profiles-folder-already-exists = Klasör zaten mevcut.
profiles-open = Aç
profiles-open-backup = Yedek Aç...
profiles-please-remove-the-folder-and = Lütfen { $val } klasörünü kaldır ve tekrar dene.
profiles-profile-corrupt = Profil Bozuk
profiles-profiles = Profiller
profiles-quit = Çık
profiles-user-1 = Kullanıcı 1
profiles-confirm-lang-choice = Anki'nin arayüzünü { $lang } dilinde görüntülemek istediğinden emin misin?
profiles-could-not-create-data-folder = Anki, veri klasörünü oluşturamadı. Lütfen kılavuzun Dosya Konumları bölümüne bakın ve konumun salt okunur olmadığından emin olun.
profiles-prefs-corrupt-title = Tercihler Bozuk
profiles-prefs-file-is-corrupt = Anki'nin prefs21.db dosyası bozuldu ve yeniden oluşturuldu. Birden fazla profil kullanıyorsanız, kartlarınızı kurtarmak için lütfen aynı adları kullanarak profillerinizi tekrar ekleyin.
profiles-profile-does-not-exist = İstenilen profil yok.
profiles-creating-backup = Yedek Oluşturuluyor...
profiles-backup-created = Yedekleme yaratıldı.
profiles-backup-creation-failed = Yedekleme yaratımı başarısız: { $reason }
profiles-backup-unchanged = En sonki yedeklemeden itibaren değişim yok.
