editing-actual-size = Початковий розмір
editing-add-media = Додати медіа-файл
editing-align-left = За лівим краєм
editing-align-right = За правим краєм
editing-an-error-occurred-while-opening = Помилка під час відкриття { $val }
editing-attach-picturesaudiovideo = Додати зображення/аудіо/відео
editing-bold-text = Жирний текст
editing-cards = Картки
editing-center = По центру
editing-change-color = Змінити колір
editing-cloze-deletion = Закритий текст (нова картка)
editing-cloze-deletion-repeat = Закритий текст (та сама картка)
editing-copy-image = Копіюватися зображення
editing-couldnt-record-audio-have-you-installed = Не вдається записати звук. Чи встановлено у Вас «lame»?
editing-customize-card-templates = Змінити шаблон картки
editing-customize-fields = Змінити поля
editing-cut = Вирізати
editing-double-click-image = клацніть на зображенні двічі
editing-double-click-to-expand = Натисніть двічі, щоб показати
editing-double-click-to-collapse = Натисніть двічі, щоб приховати
editing-edit-current = Редагування картки
editing-edit-html = Редагувати HTML
editing-fields = Поля
editing-float-left = До лівого краю
editing-float-right = До правого краю
editing-float-none = Не пересовувати
editing-indent = Збільшити відступ
editing-italic-text = Курсив
editing-jump-to-tags-with-ctrlandshiftandt = Перейти до міток з  Ctrl+Shift+T
editing-justify = За шириною
editing-latex = LaTeX
editing-latex-equation = Рівняння LaTeX
editing-latex-math-env = Математичне оточення LaTeX
editing-mathjax-block = MathJax блок
editing-mathjax-chemistry = MathJax для хімії
editing-mathjax-inline = MathJax в рядку
editing-mathjax-placeholder = Натисніть { $accept } щоб закінчити введення, { $newline } для вставки нового рядка.
editing-media = Медіа-файли
editing-open-image = Відкрити зображення
editing-show-in-folder = Показати у теці
editing-ordered-list = Впорядкований список
editing-outdent = Зменшити відступ
editing-paste = Вставити
editing-record-audio = Записати авдіо
editing-remove-formatting = Видалити форматування
editing-restore-original-size = Повернути початковий розмір
editing-select-remove-formatting = Оберіть форматування до видалення
editing-show-duplicates = Показати дублікати
editing-subscript = Нижній індекс
editing-superscript = Верхній індекс
editing-tags = Мітки
editing-tags-add = Додати мітку
editing-tags-copy = Копіювати мітки
editing-tags-remove = Видалити мітки
editing-tags-select-all = Обрати всі мітки
editing-text-color = Колір тексту
editing-text-highlight-color = Колір підсвічення тексту
editing-to-make-a-cloze-deletion-on = Для створення картки з тестом з пробілами по існуючій нотатці, спочатку потрібно змінити її тип на тип тесту з пробілами командою "Редагування>Змінити тип нотатки..."
editing-toggle-html-editor = Перемикач HTML редактора
editing-toggle-visual-editor = Перемикач візуального редактора
editing-toggle-sticky = Перемикач прикріплення
editing-expand = Показати
editing-collapse = Приховати
editing-expand-field = Показати поле
editing-collapse-field = Приховати поле
editing-underline-text = Підкреслений текст
editing-unordered-list = Невпорядкований список
editing-warning-cloze-deletions-will-not-work = Увага! Тести з пробілами не спрацюють, поки ви не зміните тип вгорі на Тест з пробілами.
editing-mathjax-preview = Передперегляд MathJax
editing-shrink-images = Зменшити зображення
editing-close-html-tags = Автоматично закривати HTML теґи
editing-from-clipboard = З буфера обміну
editing-alignment = Вирівняти
editing-equations = Формули
editing-no-image-found-on-clipboard = У буфері обміну нема зображення.
editing-image-occlusion-mode = Режим закриття зображення
editing-image-occlusion-zoom-out = Зменшити
editing-image-occlusion-zoom-in = Збільшити
editing-image-occlusion-zoom-reset = Відновити масштаб
editing-image-occlusion-toggle-translucent = Перемкнути напівпрозорість
editing-image-occlusion-delete = Видалити
editing-image-occlusion-duplicate = Дублювати
editing-image-occlusion-group = Об'єднати
editing-image-occlusion-ungroup = Роз'єднати
editing-image-occlusion-select-all = Вибрати все
editing-image-occlusion-alignment = Вирівняти
editing-image-occlusion-align-left = За лівим краєм
editing-image-occlusion-align-h-center = Відцентрувати горизонтально
editing-image-occlusion-align-right = За правим краєм
editing-image-occlusion-align-top = За верхнім краєм
editing-image-occlusion-align-v-center = Відцентрувати вертикально
editing-image-occlusion-align-bottom = За нижнім краєм
editing-image-occlusion-select-tool = Вибрати
editing-image-occlusion-zoom-tool = Масштаб
editing-image-occlusion-rectangle-tool = Прямокутник
editing-image-occlusion-ellipse-tool = Овал
editing-image-occlusion-polygon-tool = Багатокутник
editing-image-occlusion-text-tool = Текст
editing-image-occlusion-fill-tool = Заповнити кольором
editing-image-occlusion-toggle-mask-editor = Редактор масок
editing-image-occlusion-reset = Скасувати закриття зображення
editing-image-occlusion-confirm-reset = Ви справді хочете скасувати закриття зображення?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Редактор HTML
