qt-accel-about = &حول
qt-accel-about-mac = حول أنكي...
qt-accel-cards = &بطاقات
qt-accel-check-database = فحص &قاعدة البيانات
qt-accel-check-media = فحص ال&وسائط
qt-accel-edit = &تحرير
qt-accel-exit = &خروج
qt-accel-export = ت&صدير...
qt-accel-export-notes = &تصدير ملحوظات...
qt-accel-file = &ملف
qt-accel-filter = &فلترة
qt-accel-find = &بحث
qt-accel-find-and-replace = بحث واستبد&ال...
qt-accel-find-duplicates = بحث عن &ملحوظات مكررة...
qt-accel-go = &ذهاب
qt-accel-guide = &تعليمات
qt-accel-help = م&ساعدة
qt-accel-import = &استيراد...
qt-accel-info = &معلومات...
qt-accel-invert-selection = &عكس المحدد
qt-accel-next-card = &البطاقة التالية
qt-accel-note = م&لحوظة
qt-accel-notes = &ملحوظات
qt-accel-preferences = &تفضيلات...
qt-accel-previous-card = &البطاقة السابقة
qt-accel-select-all = تحديد ال&كل
qt-accel-select-notes = تحديد ال&ملحوظات
qt-accel-support-anki = &ادعم أنكي
qt-accel-switch-profile = &تبديل الملف الشخصي
qt-accel-tools = أ&دوات
qt-accel-undo = &تراجع
qt-accel-redo = إعادة ت&طبيق
qt-accel-set-due-date = ضبط &تاريخ الاستحقاق...
qt-accel-forget = &تصفير
qt-accel-view = &عرض
qt-accel-full-screen = تفعيل/إيقاف &وضع ملء الشاشة
qt-accel-layout = &تصميم
qt-accel-layout-auto = تل&قائي
qt-accel-layout-vertical = &عمودي
qt-accel-layout-horizontal = &أفقي
qt-accel-zoom-in = ت&كبير
qt-accel-zoom-out = ت&صغير
qt-accel-reset-zoom = إعادة &ضبط مستوى التكبير
qt-accel-toggle-sidebar = إظهار/إخفاء الشريط الجانبي
qt-accel-zoom-editor-in = تك&بير المحرر
qt-accel-zoom-editor-out = تص&غير المحرر
qt-accel-create-backup = إنشاء &نسخة احتياطية
qt-accel-load-backup = &استرجاع نسخة احتياطية
qt-accel-upgrade-downgrade = تحديث/تخفيض
