actions-add = Erantsi
actions-cancel = Utzi
actions-choose = Aukeratu
actions-close = Itxi
actions-copy = Kopiatu
actions-create-copy = Sortu kopia
actions-custom-study = Ikasketa pertsonalizatua
actions-decks = Sortak
actions-delete = Ezabatu
actions-export = Esportatu
actions-filter = Iragazi
actions-help = Laguntza
actions-import = Inportatu
actions-manage = Kudeatu...
actions-name = Izena:
actions-new = Berriak
actions-new-name = Izen berria:
actions-options = Aukerak
actions-options-for = { $val }-(r)en aukerak
actions-preview = Aurrebista
actions-rebuild = Berreraiki
actions-rename = Berrizendatu
actions-rename-deck = Berrizendatu sorta
actions-rename-tag = Berrizendatu etiketa
actions-rename-with-parents = Berrizendatu gurasoekin
actions-remove-tag = Kendu etiketa
actions-replay-audio = Grabaketa berriro jarri
actions-reposition = Aldatu posizioz
actions-save = Gorde
actions-search = Bilatu
actions-select = Hautatu
actions-shortcut-key = Tekla bizkor: { $val }
actions-suspend-card = Eten txartela
actions-set-due-date = Ezarri berrikuste-data
actions-answer-card = Erantzun txartela
actions-add-deck = Gehitu sorta
actions-add-note = Gehitu oharra
actions-update-tag = Eguneratu etiketa
actions-update-note = Eguneratu oharra
actions-update-card = Eguneratu txartela
actions-update-deck = Eguneratu sorta
actions-forget-card = Ahaztu txartela
actions-build-filtered-deck = Sortu sorta
actions-add-notetype = Gehitu ohar-mota
actions-remove-notetype = Kendu ohar-mota
actions-update-notetype = Eguneratu ohar-mota
actions-update-config = Eguneratu konfigurazioa
actions-card-info = Txartelaren informazioa
actions-previous-card-info = Aurreko txartelaren informazioa
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = Ekintza hau ez da bateragarria zure sistemarekin.

## Flags

actions-flag-number = { $number }. bandera
actions-flag-red = Gorria
actions-flag-orange = Laranja
actions-flag-green = Berdea
actions-flag-blue = Urdina
actions-flag-pink = Arrosa
actions-flag-turquoise = Turkesa
actions-flag-purple = Morea
actions-set-flag = Ezarri bandera
actions-processing = Prozesatzen...
