preferences-automatically-sync-on-profile-openclose = Automatikoki sinkronizatu profila ireki/ixterakoan
preferences-backups = Babeskopiak
preferences-backups2 = segurtasun kopiak
preferences-backupsanki-will-create-a-backup-of = <b>Babeskopiak</b><br>Anki-k zure bildumaren babeskopia bat sortuko du ixten edo sinkronizatzen den bakoitzean.
preferences-basic = Oinarrizkoa
preferences-change-deck-depending-on-note-type = Aldatu karta-sorta nota-motaren arabera
preferences-hours-past-midnight = gauerdiaren ondoko orduak
preferences-interface-language = Interfazeko hizkuntza
preferences-keep = Gorde
preferences-learn-ahead-limit = muga arte ikasi
preferences-mins = minutu
preferences-network = Sarea
preferences-next-day-starts-at = noiz hasi da hurrengo eguna?
preferences-note-media-is-not-backed-up = Oharra : Euskarri ez du babeskopiarik. Mesedez, zure Anki direktorioko aldizkako babeskopia sortu badaezpada
preferences-on-next-sync-force-changes-in = datorren sinkronizatzean, norabide bateko aldaketak ezarri
preferences-paste-clipboard-images-as-png = PNG legez papergainekoko irudiak erantsi
preferences-please-restart-anki-to-complete-language = Mesedez, berriabazi Anki hizkuntzako aldaketa osatzeko
preferences-preferences = Hobespenak
preferences-scheduling = Berreplanifikatu
preferences-show-next-review-time-above-answer = botoiaren gainean hurrengo berrikuspen eguna erakutsi
preferences-show-remaining-card-count-during-review = Berrikuspen honetan falta diren karten kopurua erakutsi
preferences-some-settings-will-take-effect-after = Doikuntza batzuk Anki berrabiarazi ondoren baliozkoak izango dira
preferences-synchronisation = <b>Sinkronizazioa</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Sinkronizazioa</b><br> Ez dago unean gaituta; klikatu leiho nagusiko sinkronizatu botoia gaitzeko.
preferences-synchronize-audio-and-images-too = Soinuak eta irudiak ere sinkronizatu
preferences-timebox-time-limit = Denbora muga
preferences-when-adding-default-to-current-deck = gehitzen denean, sorta azkena lehenetsia da
