preferences-automatically-sync-on-profile-openclose = Déan sioncronú go huathoibríoch nuair a dhúntar/osclaítear próifíl
preferences-backups = Cóipeanna Cúltaca
preferences-change-deck-depending-on-note-type = Athraigh paca de réir an chineál nóta
preferences-changes-will-take-effect-when-you = Tiocfaidh na athruithe i bhfeidhm nuair a atosófar Anki.
preferences-hours-past-midnight = uaire tar éis mheán oíche
preferences-language = Teanga
preferences-interrupt-current-audio-when-answering = Bris isteach ar fhuaim chun freagra a thabhairt
preferences-learn-ahead-limit = Srian 'Foghlaim roimh am'
preferences-mins = nóim
preferences-network = Líonra
preferences-next-day-starts-at = Tosaíonn an chéad lá eile ag
preferences-media-is-not-backed-up = Ní dhéantar cóip chúltaca de do mheáin. Ar fhaitíos na bhfaitíos, déan cúltacú rialta den fhillteán Anki.
preferences-on-next-sync-force-changes-in = An chéad sioncronú eile: athruithe i dtreo áirithe amháin
preferences-paste-clipboard-images-as-png = Greamaigh íomhánna gearrthaisce mar PNG
preferences-paste-without-shift-key-strips-formatting = Baintear an formáidiú nuair nach ngreamaítear agus SHIFT á bhrú
preferences-periodically-sync-media = Sioncronaigh meáin go tréimhsiúil
preferences-please-restart-anki-to-complete-language = Atosaigh Anki chun athrú teanga a chríochnú.
preferences-preferences = Roghanna
preferences-scheduling = Sceidealú
preferences-show-learning-cards-with-larger-steps = Taispeáin cártaí atá á bhfoghlaim fós ach céimeanna níos mó i gceist leo i dtosach
preferences-show-next-review-time-above-answer = Taispeáin am don chéad athbhreithniú eile thuas ar na cnaipí freagartha
preferences-spacebar-rates-card = Freagraítear leis an spásbharra
preferences-show-play-buttons-on-cards-with = Taispeáin cnaipe 'seinn' ar chártaí le fuaim
preferences-show-remaining-card-count = Taispeáin líon na gcártaí atá fágtha
preferences-some-settings-will-take-effect-after = Tiocfaidh socruithe áirithe i bhfeidhm nuair a atosófar Anki.
preferences-tab-synchronisation = Sioncronú
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Sioncronú</b><br> Níl sioncronú ar fáil faoi láthair; cliceáil an cnaipe 'Sioncronú' sa phríomhfhuinneog chun é a chur ar fáil.
preferences-synchronize-audio-and-images-too = Sioncronaigh fuaim agus iomhánna freisin
preferences-timebox-time-limit = Teorainn ama don tréimhse shocraithe
preferences-user-interface-size = Méid an chomhéadain
preferences-when-adding-default-to-current-deck = Cuir cártaí nua leis an bpaca atá oscailte mar réamhshocrú
preferences-you-can-restore-backups-via-fileswitch = Chun cóipeanna cúltaca a thabhairt ar ais: Comhad>Athraigh Próifíl
preferences-legacy-timezone-handling = Seanchóras oibrithe na n-amchrios (lochtach, ach éigeantach do leaganacha AnkiDroid <= 2.14)
preferences-default-search-text = Buntéacs cuardaigh
preferences-default-search-text-example = m.s. 'desk:current'
preferences-theme = Modh
preferences-theme-follow-system = Réir an Ghléis
preferences-theme-light = Sorcha
preferences-theme-dark = Dorcha
preferences-v3-scheduler = Sceidealú LGN3
preferences-ignore-accents-in-search = Ná bactar le haicinn sa chuardach (níos moille)
preferences-backup-explanation =
    Déanann Anki cóipeanna cúltaca de do chnuasach go rialta. Agus na cóipeanna sin
    níos sine ná 2 lá, tosófar ag scriosadh cuid díobh chun spás a choinneáil saor.
preferences-daily-backups = Cóipeanna cúltaca laethúla le coinneáil:
preferences-weekly-backups = Cóipeanna cúltaca seachtanúla le coinneáil:
preferences-monthly-backups = Cóipeanna cúltaca míosúla le coinneáil:
preferences-minutes-between-backups = Achar (nóim.) idir cúltacuithe uathoibríocha:
preferences-reduce-motion = Maolaigh gluaiseacht
preferences-reduce-motion-tooltip = Díchumasaigh beochaintí agus trasnálacha áirithe an chomhéadain
preferences-hide-top-bar-during-review = Ná taispeántar an barra uachtair le linn athbhreithnithe
preferences-hide-bottom-bar-during-review = Ná taispeántar an barra íochtair le linn athbhreithnithe
preferences-always = I gcónaí
preferences-full-screen-only = Lánscáileán amháin
preferences-appearance = Cuma
preferences-general = Ginearálta
preferences-style = Amharc
preferences-review = Athbhreithnithe
preferences-distractions = Rudaí Seachtracha
preferences-minimalist-mode = Modh íostach
preferences-editing = Cur in Eagar
preferences-browsing = Brabhsáil
preferences-default-deck = Paca réamhshocraithe
preferences-account = Cuntais AnkiWeb
preferences-note = Nótaí
preferences-scheduler = Sceidealú
preferences-user-interface = Comhéadan
preferences-import-export = Iompórtáil/Easpórtáil

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = Bunúsach
preferences-reviewer = NO NEED TO TRANSLATE
preferences-media = NO NEED TO TRANSLATE
