#!/bin/bash

set -eu -o pipefail ${SHELLFLAGS}

out=../aqt_data/locale/qt
mkdir -p "$out"

qtTranslations="$(python -c "from PyQt5.QtCore import *; import sys; sys.stdout.write(QLibraryInfo.location(QLibraryInfo.TranslationsPath))")"

case "$(uname -s)" in
    CYGWIN*|MINGW*|MSYS*)
        qtTranslations="$(cygpath -u "${qtTranslations}")"
        ;;
esac

rsync -a "$qtTranslations/" "$out/"
