#!/bin/bash

set -eu -o pipefail ${SHELLFLAGS}

echo "Downloading latest translations..."

if [ ! -d repo ]; then
  git clone https://github.com/ankitects/anki-desktop-i18n repo
fi

(cd repo && git pull)
