profiles-anki-could-not-read-your-profile = O Anki não pôde ler seus dados de perfil. Os tamanhos das janelas e seus detalhes de login de sincronização foram esquecidos.
profiles-anki-could-not-rename-your-profile = O Anki não poderia alterar o nome do perfil porque não poderia alterar o nome da pasta de perfil no disco. Por favor, verifique se você possuir a permissão de escrita ao Arquivos/Anki e outros programas não estiver acessando as pastas de perfil, em seguida, tente novamente.
profiles-folder-already-exists = A pasta já existe.
profiles-open = Abrir
profiles-open-backup = Abrir cópia de segurança...
profiles-please-remove-the-folder-and = Por favor. remova a pasta { $val } e tente novamente.
profiles-profile-corrupt = Perfil Corrompido
profiles-profiles = Usuários
profiles-quit = Sair
profiles-user-1 = Usuário 1
profiles-confirm-lang-choice = Tem certeza de que deseja exibir a interface do Anki em { $lang }?
profiles-could-not-create-data-folder = O Anki não conseguiu criar sua pasta de dados. Consulte a seção 'Locais dos Arquivos' do manual e certifique-se de que o local não seja somente leitura.
profiles-prefs-corrupt-title = Preferências Corrompidas
profiles-prefs-file-is-corrupt = O arquivo 'prefs21.db' do Anki estava corrompido e foi recriado. Se você estava usando vários perfis, adicione-os novamente usando os mesmos nomes para recuperar seus cartões.
profiles-profile-does-not-exist = O perfil solicitado não existe.
profiles-creating-backup = Criando cópia de segurança...
profiles-backup-created = Cópia de segurança criada.
profiles-backup-creation-failed = Falha ao criar cópia de segurança: { $reason }
profiles-backup-unchanged = Nenhuma alteração desde o último backup.
