profiles-anki-could-not-read-your-profile = Anki kunde inte läsa profildatan. Fönsterstorlekar och inloggningsdetaljer för synkronisering har försummats.
profiles-anki-could-not-rename-your-profile = Anki kunde inte byta namnet på din profil eftersom den inte kunde byta namnet på profilmappen på hårddisken. Säkerställ att du har skrivbefogenheter till Dokument/Anki och att inga andra program försöker komma åt dina profilmappar, och försök sedan igen.
profiles-folder-already-exists = Katalogen finns redan.
profiles-open = Öppna
profiles-open-backup = Öppna säkerhetskopia
profiles-please-remove-the-folder-and = Radera mappen { $val } och försök igen.
profiles-profile-corrupt = Profil korrupt
profiles-profiles = Profiler
profiles-quit = Avsluta
profiles-user-1 = Användare 1
profiles-confirm-lang-choice = Är du säker på att du vill visa Ankis gränssnitt på { $lang }?
profiles-could-not-create-data-folder = Anki kunde inte skapa dess datamapp. Var god se Filsökvägar-sektionen av manualen och försäkra att sökvägen inte är skrivskyddad.
profiles-prefs-corrupt-title = Preferenser korrupta
profiles-prefs-file-is-corrupt = Anki-filen prefs21.db var korrupt och har återskapats. Om flera profiler användes, var god lägg till dem med samma namn för att återvinna korten.
profiles-profile-does-not-exist = Begärd profil existerar inte
profiles-creating-backup = Skapar säkerhetskopia ...
profiles-backup-created = Säkerhetskopia skapad.
profiles-backup-creation-failed = Säkerhetskopiering misslyckades: { $reason }
profiles-backup-unchanged = Inga ändringar sedan den senaste säkerhetskopieringen.
