actions-add = Cuir Leis
actions-all-selected = Gach rud roghnaithe
actions-any-selected = A bhfuil roghnaithe
actions-cancel = Cealaigh
actions-choose = Roghnaigh
actions-close = Dún
actions-copy = Cóipeáil
actions-create-copy = Déan Cóip
actions-custom-study = Staidéar ar Leith
actions-decks = Pacaí
actions-decrement-value = Laghdaítear faoi
actions-delete = Scrios
actions-export = Easpórtáil
actions-filter = Scagaire
actions-help = Cabhair
actions-increment-value = Méadaítear faoi
actions-import = Iompórtáil
actions-manage = Bainistigh...
actions-name = Ainm:
actions-new = Nua
actions-new-name = Ainm nua:
actions-options = Roghanna
actions-options-for = Roghanna do { $val }
actions-preview = Réamhamharc
actions-rebuild = Tóg arís
actions-rename = Athainmnigh
actions-rename-deck = Athainmnigh Paca
actions-rename-tag = Athainmnigh Clib
actions-rename-with-parents = Athainmnigh le Mórphaca
actions-remove-tag = Bain Clib
actions-replay-audio = Cas Fuaim Arís
actions-reposition = Bog
actions-save = Sábháil
actions-search = Cuardaigh
actions-select = Roghnaigh
actions-shortcut-key = Cnaipe aicearra: { $val }
actions-suspend-card = Cuir Cárta ar Fionraí
actions-set-due-date = Socraigh Dáta Staidéir
actions-answer-card = Freagair Cárta
actions-unbury-unsuspend = Tarraing Amach/Bain as Fionraí
actions-add-deck = Cuir Paca leis
actions-add-note = Cuir Nóta leis
actions-update-tag = Nuashonraigh Clib
actions-update-note = Nuashonraigh Nóta
actions-update-card = Nuashonraigh Cárta
actions-update-deck = Nuashonraigh Paca
actions-forget-card = Lig Cárta i nDearmad
actions-build-filtered-deck = Tiomsaigh Paca
actions-add-notetype = Cuir Cineál Nótaí Leis
actions-remove-notetype = Bain Cineál Nótaí
actions-update-notetype = Nuashonraigh Cineál Nótaí
actions-update-config = Nuashonraigh Cumraíocht
actions-card-info = Sonraí Cárta
actions-previous-card-info = Sonraí an Cárta Roimhe
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...

## Flags

actions-flag-number = Bratach { $number }
actions-flag-red = Dearg
actions-flag-orange = Buí
actions-flag-green = Glas uaine
actions-flag-blue = Gorm
actions-flag-pink = Bándearg
actions-flag-turquoise = Gormghlas
actions-flag-purple = Corcra
actions-set-flag = Socraigh Bratach
actions-nothing-to-undo = Gan dada le cealú
actions-nothing-to-redo = Gan dada le hathdhéanamh
actions-auto-advance = Ar Aghaidh go hUathoibríoch
actions-processing = Ag próiseáil...
