decks-add-new-deck-ctrlandn = Cuir Paca Nua Leis (Ctrl+N)
decks-build = Leagan
decks-cards-selected-by = cártaí roghnaithe de réir
decks-create-deck = Cruthaigh Paca
decks-custom-steps-in-minutes = Céimeanna saincheaptha (nóiméid)
decks-deck = Paca
decks-decreasing-intervals = Eatraimh ag dul i laghad
decks-delete-deck = Scrios Paca
decks-enable-second-filter = Cur scagaire eile i bhfeidhm
decks-filter = Scagaire:
decks-filter-2 = Scagaire 2
decks-get-shared = Pacaí Roinnte
decks-import-file = Iompórtáil Comhad
decks-increasing-intervals = Eatraimh ag dul i méid
decks-latest-added-first = Taispeáin cártaí is úire i dtosach
decks-limit-to = Srian:
decks-minutes = nóiméad
decks-most-lapses = Líon is mó de chlistí
decks-new-deck-name = Ainm an phaca nua:
decks-no-deck = [gan phaca]
decks-oldest-seen-first = Is sine i dtosach
decks-order-added = Ord úire
decks-order-due = Ord 'le staidéar'
decks-please-select-something = Roghnaigh rud éigin.
decks-random = Randamach
decks-relative-overdueness = De réir deireanaí
decks-repeat-failed-cards-after = Athdhéan cártaí mícheart tar éis
decks-reschedule-cards-based-on-my-answers = Athsceidealaigh cártaí de réir freagraí don phaca seo
decks-study = Déan staidéar
decks-study-deck = Paca Staidéir
decks-filtered-deck-search-empty = Níl aon cárta ann a thagann leis an gcuardach. D'fhéadfadh gur fágadh roinnt cártaí as an áireamh de dheasca iad a bheith ar fionraí nó mar chuid de phaca scagtha eile.
decks-unmovable-cards = Taispeáin aon chárta a fágadh as
decks-learn-header = Foghlaim
# The count of cards waiting to be reviewed
decks-review-header = Le staidéar
