fields-add-field = Cuir Réimse Leis
fields-delete-field-from = Scrios réimse ó { $val }?
fields-editing-font = Clófhoireann Eagarthóireachta
fields-field = Réimse:
fields-field-name = Ainm réimse:
fields-description = Cur síos
fields-description-placeholder = An méid a thaispeánfar in aice le hainm an réimse agus tú i mbun eagarthóireachta
fields-fields-for = Réimsí do { $val }
fields-font = Clófoireann:
fields-new-position-1 = Áit nua (1...{ $val }):
fields-notes-require-at-least-one-field = Teastaíonn réimse amháin (ar a laghad) i nótaí.
fields-reverse-text-direction-rtl = Cas an téacs droim ar ais
fields-collapse-by-default = Réamhshocraigh díleathnú
fields-html-by-default = Réamhshocraigh oibriú an eagarthóra HTML
fields-size = Méid:
fields-sort-by-this-field-in-the = Bíodh an réimse seo mar bhunús sórtála sa bhrabhsálaí
fields-that-field-name-is-already-used = Tá an t-ainm sin ar réimse eile cheana féin.
fields-name-first-letter-not-valid = Níor cheart go mbeadh #, ^ nó / ag tús ainm an réimse.
fields-name-invalid-letter = Ná cuirtear :, ", { "{" } ná { "}" }  in ainm réimse ar bith.
