profiles-anki-could-not-read-your-profile = Níor éirigh le Anki sonraí do phróifíle a léamh. Tá méid na bhfuinneog agus do chuid dintiúr sioncronaithe dearmadta.
profiles-anki-could-not-rename-your-profile = Níor éirigh le Anki an phróifíl a athainmniú, de bharr nárbh fhéidir an fillteán próifíle a athainmniú ar do ríomhaire. Déan cinnte go bhfuil cead scríofa comhaid agat ar Documents/Anki agus nach bhfuil bogearra ar bith eile ag obair le do chuid fillteáin phróifíle. Ansin bain triail eile as.
profiles-folder-already-exists = Fillteán ann cheana féin.
profiles-open = Oscail
profiles-open-backup = Oscail Cúltacú...
profiles-please-remove-the-folder-and = Bain an fillteán { $val } agus bain triail eile as.
profiles-profile-corrupt = Próifíl Truaillithe
profiles-profiles = Próifílí
profiles-quit = Scoir
profiles-user-1 = Úsáideoir 1
profiles-confirm-lang-choice = An bhfuil tú cinnte gur mian leat go mbeadh comhéadan Anki á thaispeáint as { $lang }?
profiles-could-not-create-data-folder = Níor éirigh le hAnki fillteán dá chuid sonraí féin a chruthú. Breathnaigh ar 'Suíomh na gComhad' sa lámhleabhar agus déan cinnte nach cead léite amháin atá agat ar an suíomh cuí.
profiles-prefs-corrupt-title = Roghanna Truaillithe
profiles-prefs-file-is-corrupt = Bhí an comhad prefs21.db de chuid Anki truaillithe agus rinneadh é a athchruthú. Dá mba rud é go raibh tú ag obair le níos mó ná próifíl amháin, cuir leis arís iad agus an t-ainm céanna orthu agus a bhí chun do chuid cártaí a athshlánú.
profiles-profile-does-not-exist = Níl a leithéid de phróifíl ann.
profiles-creating-backup = Cóip chúltaca á déanamh...
profiles-backup-created = Cóip chúltacha déanta.
profiles-backup-creation-failed = Theip ar chúltacú: { $reason }
profiles-backup-unchanged = Gan athrú ón gcúltacú deireanach.
