actions-add = Legg til
actions-all-selected = Alle valgte
actions-any-selected = Enhver valgt
actions-cancel = Avbryt
actions-choose = Velg
actions-close = Lukk
actions-copy = Kopier
actions-create-copy = Lag kopi
actions-custom-study = Brukertilpasset studie
actions-decks = Kortstokker
actions-decrement-value = Reduser verdi
actions-delete = Slett
actions-export = Eksporter
actions-filter = Filter
actions-help = Hjelp
actions-increment-value = Øk verdi
actions-import = Importere
actions-manage = Behandle...
actions-name = Navn:
actions-new = Ny
actions-new-name = Nytt navn:
actions-options = Alternativer
actions-options-for = Alternativer for { $val }
actions-preview = Forhåndsvisning
actions-rebuild = Gjenoppbygg
actions-rename = Endre navn
actions-rename-deck = Endre navn på kortstokk
actions-rename-tag = Endre navn på etikett
actions-rename-with-parents = Endre navn inkludert overordnede
actions-remove-tag = Fjern etikett
actions-replay-audio = Spill av lyd igjen
actions-reposition = Reposisjoner
actions-save = Lagre
actions-search = Søk
actions-select = Velg
actions-shortcut-key = Hurtigtast: { $val }
actions-suspend-card = Utvis kort
actions-set-due-date = Velg forfallstid
actions-answer-card = Besvar kort
actions-unbury-unsuspend = Grav opp/fjern utvisning
actions-add-deck = Legg til kortstokk
actions-add-note = Legg til note
actions-update-tag = Oppdater etikett
actions-update-note = Oppdater note
actions-update-card = Oppdater kort
actions-update-deck = Oppdater kortstokk
actions-forget-card = Glem kort
actions-build-filtered-deck = Bygg kortstokk
actions-add-notetype = Legg til note-type
actions-remove-notetype = Fjern note-type
actions-update-notetype = Oppdater note-type
actions-update-config = Endre oppsett
actions-card-info = Kortinformasjon
actions-previous-card-info = Forrige korts informasjon
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = Denne handlingen er ikke støttet av ditt system enda

## Flags

actions-flag-number = Flagg { $number }
actions-flag-red = Rød
actions-flag-orange = Oransje
actions-flag-green = Grønn
actions-flag-blue = Blå
actions-flag-pink = Rosa
actions-flag-turquoise = Turkis
actions-flag-purple = Lilla
actions-set-flag = Tilføy flagg
actions-processing = Behandler...
