qt-accel-about = &O programie...
qt-accel-about-mac = O Anki...
qt-accel-cards = &Karty
qt-accel-check-database = &Sprawdź bazę danych
qt-accel-check-media = Sprawdź &pliki...
qt-accel-edit = &Edytuj
qt-accel-exit = Z&akończ
qt-accel-export = &Eksportuj...
qt-accel-export-notes = &Eksportuj notatki...
qt-accel-file = &Plik
qt-accel-filter = Fil&truj
qt-accel-find = &Wyszukaj
qt-accel-find-and-replace = Znajdź i za&mień...
qt-accel-find-duplicates = Znajdź &duplikaty...
qt-accel-go = &Idź
qt-accel-guide = &Poradnik...
qt-accel-help = &Pomoc
qt-accel-import = &Importuj...
qt-accel-info = &Informacje...
qt-accel-invert-selection = &Odwróć zaznaczenie
qt-accel-next-card = &Następna karta
qt-accel-note = N&otatka
qt-accel-notes = &Notatki
qt-accel-preferences = &Ustawienia...
qt-accel-previous-card = &Poprzednia karta
qt-accel-select-all = Zaznacz &wszystko
qt-accel-select-notes = Wybierz &notatki
qt-accel-support-anki = &Wesprzyj Anki...
qt-accel-switch-profile = &Przełącz profil
qt-accel-tools = &Narzędzia
qt-accel-undo = &Cofnij
qt-accel-redo = &Ponów
qt-accel-set-due-date = Ustaw &Termin...
qt-accel-forget = &Zresetuj
qt-accel-view = &Widok
qt-accel-full-screen = Włącz/wyłącz &pełny ekran
qt-accel-layout = &Układ
qt-accel-layout-auto = &Automatyczny
qt-accel-layout-vertical = &Pionowy
qt-accel-layout-horizontal = &Poziomy
qt-accel-zoom-in = Powiększ
qt-accel-zoom-out = Pomniejsz
qt-accel-reset-zoom = &Domyślne powiększenie
qt-accel-toggle-sidebar = Pokaż/ukryj pasek boczny
qt-accel-zoom-editor-in = Powiększ &edytor
qt-accel-zoom-editor-out = Pomniejsz &edytor
qt-accel-create-backup = Utwórz &kopię zapasową
qt-accel-load-backup = &Przywróć kopię zapasową
qt-accel-upgrade-downgrade = Aktualizacja/cofnięcie wersji
