qt-misc-addons = Aldonaĵoj
qt-misc-all-cards-notes-and-media-for = Ĉiuj kartoj, notoj, kaj aŭdovidaĵoj al ĉi tiu profilo estos forigitaj. Ĉu vi certas?
qt-misc-anki-updatedanki-has-been-released = <h1>Anki ĝisdatigita</h1>Anki { $val } estas eldonita.<br><br>
qt-misc-automatic-syncing-and-backups-have-been = Aŭtomata samtempigo kaj sekurkopioj estas malvalidigitaj dum la restaŭrado. Por revalidigi ilin, fermi la profilon aŭ relanĉi Anki.
qt-misc-backing-up = Kreado de sekurkopioj...
qt-misc-browse = Foliumi
qt-misc-change-note-type-ctrlandn = Ŝanĝi nototipon (Ctrl+N)
qt-misc-check-the-files-in-the-media = Kontroli la dosierojn en la aŭdovidaĵo-dosierujo
qt-misc-choose-deck = Elekti kartaron
qt-misc-choose-note-type = Elekti nototipon
qt-misc-closing = Fermado...
qt-misc-configure-interface-language-and-options = Agordi interfacan lingvon kaj opciojn
qt-misc-copy-to-clipboard = Kopii al la tondujo
qt-misc-create-filtered-deck = Krei filtritan kartaron...
qt-misc-debug-console = Sencimiga konzolo
qt-misc-deck-will-be-imported-when-a = La kartaro estos enportita, kiam profilo estas malfermita.
qt-misc-default = Defaŭlta
qt-misc-empty-cards = Malplenaj kartoj...
qt-misc-error-during-startup = Eraro dum lanĉo: { $val }
qt-misc-filtered-deck = { $val }-a filtrita kartaro
qt-misc-ignore-this-update = Ignori ĉi tiun ĝisdatigon
qt-misc-in-order-to-ensure-your-collection = Por senerare interŝanĝi vian kolekton inter aparatoj, la horloĝo de via komputilo devas esti ĝuste agordita. La horloĝo povas esti malĝusta, eĉ se ĝi montras la ĝustan tempon.  Bonvolu kontroli la jenajn tempoagordojn:  - atm/ptm - tago, monato kaj jaro - horzono - somera aŭ vintra tempo  Diferenco disde la ĝusta tempo: { $val }.
qt-misc-invalid-property-found-on-card-please = Malvalidaj ecoj estas trovitaj sur karto. Bonvolu uzi la menueron Iloj>Kontroli datumbazon. Se la problemo daŭras aŭ reaperas, turni vin al la subteno-retpaĝo.
qt-misc-loading = Ŝarĝado...
qt-misc-manage = Administri
qt-misc-manage-note-types = Administri nototipojn
qt-misc-name-exists = La nomo jam ekzistas.
qt-misc-non-unicode-text = <neunikoda teksto>
qt-misc-optimizing = Optimumigado...
qt-misc-please-connect-a-microphone-and-ensure = Bonvolu konekti mikrofonon kaj certigu ke neniuj aliaj programoj uzas la sonilon.
qt-misc-please-ensure-a-profile-is-open = Bonvolu kontroli, ĉu profilo estas malferma kaj Anki ne estas okupata. Poste reprovu ĝin.
qt-misc-please-select-1-card = (bonvole elektu unu karton)
qt-misc-please-select-a-deck = Bonvolu elekti kartaron.
qt-misc-please-use-fileimport-to-import-this = Bonvolu uzi la menueron Dosiero>Enporti por enporti ĉi tiun dosieron.
qt-misc-processing = Laborado...
qt-misc-replace-your-collection-with-an-earlier = Ĉu vi volas anstataŭigi vian kolekton per antaŭa sekurkopio?
qt-misc-resume-now = Daŭrigi nun
qt-misc-revert-to-backup = Reiri al la stato de sekurkopio
qt-misc-reverted-to-state-prior-to = Reirita al stato antaŭ '{ $val }'.
qt-misc-shift-key-was-held-down-skipping = La supra registrumo estis premita. Preterpaso de aŭtomata samtempigo kaj ŝarĝo de aldonaĵoj.
qt-misc-shortcut-key-left-arrow = Fulmoklavo: sago maldekstren
qt-misc-shortcut-key-right-arrow-or-enter = Fulmoklavo: sago dekstren aŭ enenklavo
qt-misc-stats = Statistikoj
qt-misc-study-deck = &Lernkartaro...
qt-misc-sync = Samtempigi
qt-misc-target-deck-ctrlandd = Celkartaro (Ctrl+D)
qt-misc-the-following-character-can-not-be = Ĉi tiu signo estas neuzebla: { $val }
qt-misc-the-requested-change-will-require-a = La petita modifo necesigos tutan alŝuton de la datumbazo, kiam vi venontfoje samtempigos vian kolekton. Se ŝanĝoj troviĝas sur aliaj aparatoj, kiuj ankoraŭ ne estis samtempigitaj, tiuj ŝanĝoj perdiĝos. Ĉu vi volas daŭrigi?
qt-misc-there-must-be-at-least-one = Devas esti almenaŭ unu profilo.
qt-misc-this-file-exists-are-you-sure = Tiu dosiero ekzistas. Ĉu vi volas anstataŭigi ĝin?
qt-misc-unable-to-access-anki-media-folder = La aŭdovidaĵa dosierujo de Anki estas neatingebla. La atingopermeso al la labora dosierujo eble estas malĝusta.
qt-misc-unable-to-move-existing-file-to = Ne eblas movi la ekzistantan dosieron en la rubujon - bonvolu provi restartigi vian komputilon.
qt-misc-undo = Malfari
qt-misc-undo2 = &Malfari { $val }n
qt-misc-unexpected-response-code = Neatendita responda kodo: { $val }
qt-misc-waiting-for-editing-to-finish = Atendado por la fino de redakto.
qt-misc-would-you-like-to-download-it = Ĉu vi volas elŝuti ĝin nun?
qt-misc-your-collection-file-appears-to-be = Via kolektodosiero ŝajne estas difektohava. Tio povas okazi kiam dosiero estas kopiita aŭ movita dum Anki estas malferma aŭ kiam la kolekto troviĝas sur reta aŭ nuba disko. Se problemoj daŭras post restartigo de via komputilo, bonvolu malfermi aŭtomatan sekurkopion en la profilmenuo.
qt-misc-your-computers-storage-may-be-full = La memoro de via komputilo eble estas plena. Bonvolu forigi kelkajn nebezonatajn dosierojn kaj reprovi ĝin.
qt-misc-your-firewall-or-antivirus-program-is = Via fajroŝirmilo aŭ senvirusigilo malhelpas Anki krei konekton al si mem. Bonvolu aldoni escepton por Anki.
qt-misc-second = { $count ->
    [one] { $count } sekundo
   *[other] { $count } sekundoj
  }
