editing-actual-size = Afficher la taille réelle
editing-add-media = Ajouter des médias
editing-align-left = Aligner à gauche
editing-align-right = Aligner à droite
editing-an-error-occurred-while-opening = Une erreur est survenue lors de l’ouverture de { $val }
editing-attach-picturesaudiovideo = Joindre des images/fichiers audios/vidéos
editing-bold-text = Texte en gras
editing-cards = Cartes
editing-center = Centre
editing-change-color = Changer de couleur
editing-cloze-deletion = Texte à trous (nouvelle carte)
editing-cloze-deletion-repeat = Texte à trous (même carte)
editing-copy-image = Copier l'image
editing-couldnt-record-audio-have-you-installed = Impossible d’enregistrer le son. Avez-vous installé 'lame' ?
editing-customize-card-templates = Personnaliser les modèles de carte
editing-customize-fields = Personnaliser les champs
editing-cut = Couper
editing-double-click-image = double-cliquer sur l'image
editing-double-click-to-expand = (double-cliquer pour étendre)
editing-double-click-to-collapse = double-cliquer pour réduire
editing-edit-current = Modifier la carte en cours
editing-edit-html = Modifier le HTML
editing-fields = Champs
editing-float-left = Flottement à gauche
editing-float-right = Flottement à droite
editing-float-none = Pas de flottement
editing-indent = Augmenter l'indentation
editing-italic-text = Italique
editing-jump-to-tags-with-ctrlandshiftandt = Aller aux étiquettes avec Ctrl+Shift+T
editing-justify = Justifié
editing-latex = LaTeX
editing-latex-equation = Équation LaTeX
editing-latex-math-env = Env. math. LaTeX
editing-mathjax-block = Bloc de MathJax
editing-mathjax-chemistry = MathJax chimie
editing-mathjax-inline = MathJax en ligne
editing-mathjax-placeholder = Appuyez sur { $accept } pour accepter, { $newline } pour une nouvelle ligne.
editing-media = Médias
editing-open-image = Ouvrir l'image
editing-show-in-folder = Afficher dans le dossier
editing-ordered-list = Liste ordonée
editing-outdent = Diminuer l'indentation
editing-paste = Coller
editing-record-audio = Enregistrer l'audio
editing-remove-formatting = Supprimer le formatage
editing-restore-original-size = Restaurer la taille d'origine
editing-select-remove-formatting = Sélectionnez le formatage à supprimer
editing-show-duplicates = Afficher les doublons
editing-subscript = Indice
editing-superscript = Exposant
editing-tags = Étiquettes
editing-tags-add = Ajouter une étiquette
editing-tags-copy = Copier des étiquettes
editing-tags-remove = Enlever des étiquettes
editing-tags-select-all = Sélectionner des étiquettes
editing-text-color = Couleur du texte
editing-text-highlight-color = Couleur de la surbrillance du texte
editing-to-make-a-cloze-deletion-on = Pour faire d’une carte déjà existante, un texte à trous, il faut passer par « Édition > Modifier le type de la note » et choisir « Texte à trous ».
editing-toggle-html-editor = Afficher l'éditeur HTML
editing-toggle-visual-editor = Afficher l'éditeur visuel
editing-toggle-sticky = Utiliser l'épingle
editing-expand = Étendre
editing-collapse = Réduire
editing-expand-field = Développer le champ
editing-collapse-field = Réduire le champ
editing-underline-text = Souligné
editing-unordered-list = Liste non ordonnée
editing-warning-cloze-deletions-will-not-work = Attention, le texte à trous ne fonctionnera pas tant que vous ne changez pas le type de carte en « Texte à trous » (en haut de la fenêtre).
editing-mathjax-preview = Aperçu MathJax
editing-shrink-images = Rétrécir les images
editing-close-html-tags = Fermer automatiquement les tags HTML
editing-from-clipboard = Depuis le Presse-Papier
editing-alignment = Alignement
editing-equations = Équations
editing-no-image-found-on-clipboard = Aucune image trouvée dans le Presse-Papier
editing-image-occlusion-mode = Mode schéma à remplir
editing-image-occlusion-zoom-out = Dézoomer
editing-image-occlusion-zoom-in = Zoomer
editing-image-occlusion-zoom-reset = Zoom par défaut
editing-image-occlusion-toggle-translucent = Changer l'opacité
editing-image-occlusion-delete = Supprimer
editing-image-occlusion-duplicate = Dupliquer
editing-image-occlusion-group = Grouper la sélection
editing-image-occlusion-ungroup = Dégrouper la sélection
editing-image-occlusion-select-all = Tout sélectionner
editing-image-occlusion-alignment = Alignement
editing-image-occlusion-align-left = Aligner à gauche
editing-image-occlusion-align-h-center = Aligner les centres horizontaux
editing-image-occlusion-align-right = Aligner à droite
editing-image-occlusion-align-top = Aligner le haut
editing-image-occlusion-align-v-center = Aligner les centres verticaux
editing-image-occlusion-align-bottom = Aligner le bas
editing-image-occlusion-select-tool = Sélectionner
editing-image-occlusion-zoom-tool = Zoom
editing-image-occlusion-rectangle-tool = Rectangle
editing-image-occlusion-ellipse-tool = Ellipse
editing-image-occlusion-polygon-tool = Polygone
editing-image-occlusion-text-tool = Texte
editing-image-occlusion-fill-tool = Remplir avec une couleur
editing-image-occlusion-toggle-mask-editor = Basculer l'éditeur de masques.
editing-image-occlusion-reset = Réinitialiser le schéma à remplir
editing-image-occlusion-confirm-reset = Êtes-vous sûr de vouloir réinitialiser ce schéma à remplir?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Éditeur HTML
