qt-accel-about = &Tungkol
qt-accel-cards = &Mga Card
qt-accel-check-database = &Tingnan ang database
qt-accel-check-media = Tingnan &Media
qt-accel-edit = &I-edit
qt-accel-exit = E&xit
qt-accel-export = &I-export...
qt-accel-export-notes = &I-export ang mga note...
qt-accel-file = &File
qt-accel-filter = Fil&ter
qt-accel-find = &Hanapin
qt-accel-find-and-replace = Hanapin at Pa&litan
qt-accel-find-duplicates = Maghanap ng &duplicate...
qt-accel-go = &Pumunta
qt-accel-guide = &Gabay
qt-accel-help = &Tulong
qt-accel-import = &I-import...
qt-accel-info = &Info...
qt-accel-invert-selection = &I-invert ang selection
qt-accel-next-card = &Susunod na card
qt-accel-note = N&ote
qt-accel-notes = &Mga Note
qt-accel-preferences = &Mga Preference
qt-accel-previous-card = &Nakaraang card
qt-accel-select-all = Piliin l&ahat
qt-accel-select-notes = Piliin ang mga &Notes
qt-accel-support-anki = &Suportahan ang Anki
qt-accel-switch-profile = Magpalit ng Profile (&S)
qt-accel-tools = Mga Kagami&tan
qt-accel-undo = i-&Undo
qt-accel-redo = Ulitin (&R)
qt-accel-set-due-date = Magtak&da ng takdang araw
qt-accel-forget = I-&reset
qt-accel-view = Tignan (&V)
qt-accel-full-screen = $Buong screen
qt-accel-layout = &Layout
qt-accel-layout-auto = &Auto
qt-accel-layout-vertical = Patayo (&V)
qt-accel-layout-horizontal = Pa&halang
qt-accel-zoom-in = Palak&ihin
qt-accel-zoom-out = Paliitin (&O)
qt-accel-reset-zoom = I-&reset ang Zoom
qt-accel-zoom-editor-in = Zoom Editor &In
qt-accel-zoom-editor-out = Zoom Editor &Out
qt-accel-create-backup = Gumawa ng &Backup
qt-accel-load-backup = Ibalik mula sa Backup (&R)
