qt-accel-about = &O programu...
qt-accel-cards = &Kartice
qt-accel-check-database = &Preveri podatkovno bazo
qt-accel-check-media = Preveri &medijske datoteke
qt-accel-edit = &Uredi
qt-accel-exit = I&zhod
qt-accel-export = &Izvozi...
qt-accel-export-notes = &Izvozi zapiske
qt-accel-file = &Datoteka
qt-accel-filter = &Filter
qt-accel-find = &Najdi
qt-accel-find-and-replace = Na&jdi in zamenjaj...
qt-accel-find-duplicates = Poišči &dvojnike...
qt-accel-go = &Pojdi
qt-accel-guide = &Vodnik...
qt-accel-help = &Pomoč
qt-accel-import = &Uvozi...
qt-accel-info = &Info
qt-accel-invert-selection = Preo&brni izbor
qt-accel-next-card = &Naslednja kartica
qt-accel-note = &Zapisek
qt-accel-notes = &Zapiski
qt-accel-preferences = &Nastavitve...
qt-accel-previous-card = &Prejšnja kartica
qt-accel-select-all = Izberi &vse
qt-accel-select-notes = Izberi &zapiske
qt-accel-support-anki = &Podpri Anki...
qt-accel-switch-profile = Zamenjaj &profil
qt-accel-tools = &Orodja
qt-accel-undo = &Razveljavi
qt-accel-redo = Ponovno &uveljavi
qt-accel-set-due-date = Nastavi &datum poteka
qt-accel-forget = &Pozabi
qt-accel-view = &Pogled
qt-accel-full-screen = Preklopi &celoten zaslon
qt-accel-layout = &Postavitev
qt-accel-layout-auto = &Avtomatično
qt-accel-layout-vertical = &Navpično
qt-accel-layout-horizontal = &Vodoravno
qt-accel-zoom-in = &Približaj
qt-accel-zoom-out = &Oddalji
qt-accel-reset-zoom = &Ponastavi zoom
qt-accel-zoom-editor-in = &Približaj urejevalnik
qt-accel-zoom-editor-out = &Oddalji urejevalnik
qt-accel-create-backup = Ustvari &rezervno kopijo
