fields-add-field = Προσθήκη πεδίου
fields-delete-field-from = Διαγραφή πεδίου από  { $val };
fields-editing-font = Επεξεργασία Γραμματοσειράς
fields-field = Πεδίο:
fields-field-name = Όνομα πεδίου:
fields-description = Περιγραφή
fields-description-placeholder = Το κείμενο που εμφανίζεται στο πεδίο όταν είναι άδειο
fields-fields-for = Πεδία για { $val }
fields-font = Γραμματοσειρά
fields-new-position-1 = Νέα θέση (1...{ $val }):
fields-notes-require-at-least-one-field = Οι σημειώσεις απαιτούν τουλάχιστον ένα πεδίο.
fields-reverse-text-direction-rtl = Αντιστροφή κατεύθυνσης κειμένου (RTL)
fields-collapse-by-default = Σύμπτυξη ως προεπιλογή
fields-html-by-default = Χρήση επεξεργαστή HTML ως προεπιλογή
fields-size = Μέγεθος:
fields-sort-by-this-field-in-the = Ταξινόμηση κατά αυτού του πεδίου στον περιηγητή
fields-that-field-name-is-already-used = Αυτό το όνομα αρχείου έχει ήδη χρησιμοποιηθεί.
fields-name-first-letter-not-valid = Το όνομα πεδίου δεν πρέπει να αρχίζει με #, ^ ή /.
fields-name-invalid-letter = Το όνομα πεδίου δεν πρέπει να περιέχει :, ", { "{" } ή { "}" }.
fields-field-is-required = Αυτό είναι ένα απαιτούμενο πεδίο και δεν μπορεί να διαγραφεί.
