qt-accel-about = &Σχετικά...
qt-accel-about-mac = Σχετικά με το Anki...
qt-accel-cards = &Κάρτες
qt-accel-check-database = &Έλεγχος βάσης δεδομένων
qt-accel-check-media = Έλεγχος &πολυμέσων
qt-accel-edit = &Επεξεργασία
qt-accel-exit = Έ&ξοδος
qt-accel-export = &Εξαγωγή...
qt-accel-export-notes = &Εξαγωγή σημειώσεων...
qt-accel-file = &Αρχείο
qt-accel-filter = Φίλ&τρο
qt-accel-find = &Αναζήτηση
qt-accel-find-and-replace = Εύρεση και &αντικατάσταση
qt-accel-find-duplicates = Εύρεση &διπλότυπων...
qt-accel-go = &Προς
qt-accel-guide = &Εγχειρίδιο...
qt-accel-help = &Βοήθεια
qt-accel-import = &Εισαγωγή...
qt-accel-info = &Πληροφορίες...
qt-accel-invert-selection = &Αντιστροφή επιλογής
qt-accel-next-card = &Επόμενη Κάρτα
qt-accel-note = Σ&ημείωση
qt-accel-notes = &Σημειώσεις
qt-accel-preferences = &Προτιμήσεις...
qt-accel-previous-card = &Προηγούμενη Κάρτα
qt-accel-select-all = Επιλογή &όλων
qt-accel-select-notes = Επιλογή &σημειώσεων
qt-accel-support-anki = &Υποστήξη του Anki...
qt-accel-switch-profile = &Αλλαγή προφίλ
qt-accel-tools = &Εργαλεία
qt-accel-undo = &Αναίρεση
qt-accel-redo = &Ακύρωση αναίρεσης
qt-accel-set-due-date = Ορισμός &Προθεσμίας...
qt-accel-forget = &Επαναφορά
qt-accel-view = &Προβολή
qt-accel-full-screen = Ενεργοποίηση &πλήρους οθόνης
qt-accel-layout = &Διάταξη
qt-accel-layout-auto = &Αυτόματα
qt-accel-layout-vertical = &Κάθετα
qt-accel-layout-horizontal = &Οριζόντια
qt-accel-zoom-in = &Μεγέθυνση
qt-accel-zoom-out = &Σμίκρυνση
qt-accel-reset-zoom = &Επαναφορά ζουμ
qt-accel-toggle-sidebar = Εναλλαγή πλευρικής μπάρας
qt-accel-zoom-editor-in = &Μεγέθυνση επεξεργαστή
qt-accel-zoom-editor-out = &Σμίκρυνση επεξεργαστή
qt-accel-create-backup = Δημιουργία &αντιγράφου ασφαλείας
qt-accel-load-backup = &Επαναφορά σε αντίγραφο ασφαλείας
qt-accel-upgrade-downgrade = Αναβάθμιση/Υποβάθμιση
