qt-accel-about = À &propos...
qt-accel-about-mac = À propos d'Anki...
qt-accel-cards = &Cartes
qt-accel-check-database = &Vérifier l’intégrité de la base de données
qt-accel-check-media = Vérifier les &médias...
qt-accel-edit = Éditio&n
qt-accel-exit = &Quitter
qt-accel-export = &Exporter...
qt-accel-export-notes = Exporter les notes...
qt-accel-file = &Fichier
qt-accel-filter = Fil&trer
qt-accel-find = &Chercher
qt-accel-find-and-replace = &Chercher et remplacer...
qt-accel-find-duplicates = Chercher un &doublon...
qt-accel-go = &Déplacement
qt-accel-guide = &Manuel en ligne
qt-accel-help = Aid&e
qt-accel-import = &Importer...
qt-accel-info = &Info...
qt-accel-invert-selection = &Inverser la sélection
qt-accel-next-card = Carte &suivante
qt-accel-note = N&ote
qt-accel-notes = &Notes
qt-accel-preferences = &Préférences...
qt-accel-previous-card = Carte &précédente
qt-accel-select-all = &Tout sélectionner
qt-accel-select-notes = Sélectionner
qt-accel-support-anki = &Soutenir Anki...
qt-accel-switch-profile = &Changer de profil
qt-accel-tools = &Outils
qt-accel-undo = A&nnuler
qt-accel-redo = &Avancer
qt-accel-set-due-date = Définir une &date d’échéance
qt-accel-forget = &Oublier
qt-accel-view = &Affichage
qt-accel-full-screen = Basculer en &Plein écran
qt-accel-layout = &Mise en page
qt-accel-layout-auto = &Automatique
qt-accel-layout-vertical = &Vertical
qt-accel-layout-horizontal = &Horizontal
qt-accel-zoom-in = &Zoomer
qt-accel-zoom-out = &Dézoomer
qt-accel-reset-zoom = Zoom par défau&t
qt-accel-toggle-sidebar = Afficher/Masquer la barre latérale
qt-accel-zoom-editor-in = &Zoomer l'éditeur
qt-accel-zoom-editor-out = &Dézoomer l'éditeur
qt-accel-create-backup = Créer une &Sauvegarde
qt-accel-load-backup = &Charger la sauvegarde
qt-accel-upgrade-downgrade = Mettre à niveau / Rétrograder
