#!/bin/bash
#
# Build and install into the launcher venv

set -e

./build.sh
if [[ "$OSTYPE" == "darwin"* ]]; then
    export VIRTUAL_ENV=$HOME/Library/Application\ Support/AnkiProgramFiles/.venv
else
    export VIRTUAL_ENV=$HOME/.local/share/AnkiProgramFiles/.venv
fi
../../out/extracted/uv/uv pip install dist/*.whl
 
