editing-actual-size = Växla faktisk storlek
editing-add-media = Lägg till media
editing-align-left = Justera vänster
editing-align-right = Justera höger
editing-an-error-occurred-while-opening = Ett fel uppstod vid öppning av { $val }
editing-attach-picturesaudiovideo = Bifoga bilder/ljud/video
editing-bold-text = Fetstil
editing-cards = Kort
editing-center = Center
editing-change-color = Byt färg
editing-cloze-deletion = Textlucka (nytt kort)
editing-cloze-deletion-repeat = Textlucka (samma kort)
editing-copy-image = Kopiera bild
editing-couldnt-record-audio-have-you-installed = Kunde inte spela in. Har du installerat "lame"?
editing-customize-card-templates = Anpassa kortmallar
editing-customize-fields = Anpassa fält
editing-cut = Klipp
editing-double-click-image = dubbelklicka bild
editing-double-click-to-expand = dubbelklicka för att expandera
editing-double-click-to-collapse = dubbelklicka för att minimera
editing-edit-current = Redigera Nuvarande
editing-edit-html = Redigera HTML
editing-fields = Fält
editing-float-left = Sväva till vänster
editing-float-right = Sväva till höger
editing-float-none = Sväva ej
editing-indent = Öka indrag
editing-italic-text = Kursiv text
editing-jump-to-tags-with-ctrlandshiftandt = Hoppa till etiketter med Ctrl+Shift+T
editing-justify = Justera
editing-latex = LaTeX
editing-latex-equation = LaTeX-ekvation
editing-latex-math-env = Matematik-miljö för LaTeX
editing-mathjax-block = MathJax-block
editing-mathjax-chemistry = MathJax kemi
editing-mathjax-inline = MathJax infogad
editing-mathjax-placeholder = Tryck { $accept } för att godkänna, { $newline } för radbrytning.
editing-media = Media
editing-open-image = Öppna bild
editing-show-in-folder = Visa i katalog
editing-ordered-list = Sorterad lista
editing-outdent = Minska indrag
editing-paste = Klistra in
editing-record-audio = Spela in ljud
editing-remove-formatting = Ta bort formattering
editing-restore-original-size = Återställ ursprunglig storlek
editing-select-remove-formatting = Välj formattering att ta bort
editing-show-duplicates = Visa dubletter
editing-subscript = Nedsänkt
editing-superscript = Upphöjd
editing-tags = Etiketter
editing-tags-add = Lägg till etikett
editing-tags-copy = Kopiera etiketter
editing-tags-remove = Ta bort etiketter
editing-tags-select-all = Markera alla etiketter
editing-text-color = Textfärg
editing-text-highlight-color = Överstrykningsfärg
editing-to-make-a-cloze-deletion-on = För att göra en existerande not till en lucktext måste du ändra korttypen till 'Lucktext' först, via Redigera>Ändra nottyp.
editing-toggle-html-editor = Växla HTML-redigerare
editing-toggle-visual-editor = Växla visuell redigerare
editing-toggle-sticky = Växla klibbig
editing-expand = Expandera
editing-collapse = Minimera
editing-expand-field = Expandera fält
editing-collapse-field = Minimera fält
editing-underline-text = Understryk text
editing-unordered-list = Oordnad lista
editing-warning-cloze-deletions-will-not-work = Varning, luckorna visas bara som en lucktext om korttypen är inställd på 'Lucktext'
editing-mathjax-preview = MathJax-förhandsvisning
editing-shrink-images = Krymp bilder
editing-close-html-tags = Stäng HTML-taggar automatiskt
editing-from-clipboard = Från urklipp
editing-alignment = Justering
editing-equations = Ekvationer
editing-no-image-found-on-clipboard = Ingen bild hittad i urklipp.
editing-image-occlusion-mode = Bildskymning
editing-image-occlusion-zoom-out = Zooma ut
editing-image-occlusion-zoom-in = Zooma in
editing-image-occlusion-zoom-reset = Återställ zoom
editing-image-occlusion-toggle-translucent = Växla genomskinlighet
editing-image-occlusion-delete = Ta bort
editing-image-occlusion-duplicate = Duplicera
editing-image-occlusion-group = Gruppera markering
editing-image-occlusion-ungroup = Avgruppera markering
editing-image-occlusion-select-all = Markera alla
editing-image-occlusion-alignment = Justering
editing-image-occlusion-align-left = Justera vänster
editing-image-occlusion-align-h-center = Justera vågrätt mitt
editing-image-occlusion-align-right = Justera höger
editing-image-occlusion-align-top = Justera överkant
editing-image-occlusion-align-v-center = Justera lodrät mitt
editing-image-occlusion-align-bottom = Justera underkant
editing-image-occlusion-select-tool = Välj
editing-image-occlusion-zoom-tool = Zoom
editing-image-occlusion-rectangle-tool = Rektangel
editing-image-occlusion-ellipse-tool = Ellips
editing-image-occlusion-polygon-tool = Polygon
editing-image-occlusion-text-tool = Text
editing-image-occlusion-fill-tool = Fyll med färg
editing-image-occlusion-toggle-mask-editor = Växla maskeringsredigerare
editing-image-occlusion-reset = Återställ bildskymning
editing-image-occlusion-confirm-reset = Är du säker på att du vill återställa denna bildskymning?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML-redigerare
