editing-actual-size = Нақты өлшемді қосу/өшіру
editing-add-media = Медиа Қосу
editing-align-left = Солға туралау
editing-align-right = Оңға туралау
editing-an-error-occurred-while-opening = { $val } ашу кезінде қате орын алды
editing-attach-picturesaudiovideo = Кескін/аудио/бейне салу
editing-bold-text = Қалың мәтін
editing-cards = Карталар
editing-center = Орта
editing-change-color = Түсті ауыстыру
editing-cloze-deletion = Саңылау толтыру (жаңа карта)
editing-cloze-deletion-repeat = Саңылау толтыру (сол карта)
editing-copy-image = Кескінді көшіру
editing-couldnt-record-audio-have-you-installed = Дыбыс жазылмады. 'lame' бағдарламасын орнаттыңыз ба?
editing-customize-card-templates = Карта Үлгісін Баптау
editing-customize-fields = Өрістерді Баптау
editing-cut = Кесу
editing-double-click-image = Суретті екі рет шерту
editing-double-click-to-expand = Жаю үшін екі рет шертіңіз
editing-double-click-to-collapse = Жию үшін екі рет шертіңіз
editing-edit-current = Ағымдағыны Өңдеу
editing-edit-html = HTML Өңдеу
editing-fields = Өрістер
editing-float-left = Солға қалқыту
editing-float-right = Оң қалқыту
editing-float-none = Қалқытпау
editing-indent = Шегіністі арттыру
editing-italic-text = Көлбеу мәтін
editing-jump-to-tags-with-ctrlandshiftandt = Ctrl+Shift+T қолданып тамғаларға өту
editing-justify = Ені бойынша туралау
editing-latex = LaTeX
editing-latex-equation = LaTeX теңдеуі
editing-latex-math-env = LaTeX ортасы
editing-mathjax-block = MathJax блогі
editing-mathjax-chemistry = MathJax химия
editing-mathjax-inline = Жоларалық MathJax
editing-mathjax-placeholder = Қабылдау үшін { $accept } басыңыз, жаңа жол үшін { $newline } басыңыз.
editing-media = Медиа
editing-open-image = Кескінді ашу
editing-show-in-folder = Қалтада көрсету
editing-ordered-list = Реттелген тізім
editing-outdent = Шегіністі азайту
editing-paste = Қою
editing-record-audio = Аудио жазу
editing-remove-formatting = Пішімдеуді жою\
editing-restore-original-size = Өлшемді қалпына келтіру
editing-select-remove-formatting = Жоятын пішімдеуді таңдау
editing-show-duplicates = Телнұсқаларды Көрсету
editing-subscript = Төменгі индекс
editing-superscript = Жоғарғы индекс
editing-tags = Тамғалар
editing-tags-add = Тамға қосу
editing-tags-copy = Тамғаларды көшіру
editing-tags-remove = Тамғаларды жою
editing-tags-select-all = Барлық тамғаны бөлшектеу
editing-text-color = Мәтін түсі
editing-text-highlight-color = Мәтінді бөлектеу түсі
editing-to-make-a-cloze-deletion-on = Бар жазбаға саңылау қосу үшін 'Жазбалар>Жазба Түрін Ауыстыру' арқылы оның түрін саңылау толтыруға ауыстыру қажет
editing-toggle-html-editor = HTML Редакторын Қосу/Өшіру
editing-toggle-visual-editor = Бейне Редакторын Қосу/Өшіру
editing-toggle-sticky = Бекітуді қосу/өшіру
editing-expand = Жаю
editing-collapse = Жию
editing-expand-field = Өрісті жаю
editing-collapse-field = Өрісті жию
editing-underline-text = Мәтіннің астын сызу
editing-unordered-list = Реттелмеген тізім
editing-warning-cloze-deletions-will-not-work = Ескерту, жоғарғы бөліктегі түрді Саңылау толтыруға ауыстырмасаңыз саңылау толтырулар жұмыс істемейді,
editing-mathjax-preview = MathJax алдын ала қарау
editing-shrink-images = Кесіндерді кішірейту
editing-close-html-tags = HTML тамғаларын автоматты түрде жабу
editing-from-clipboard = Буферден
editing-alignment = Туралау
editing-equations = Теңдеулер
editing-no-image-found-on-clipboard = Буферден кескін табылмады
editing-image-occlusion-mode = Кескін Бүркемесі Режимі
editing-image-occlusion-zoom-out = Кішілеу
editing-image-occlusion-zoom-in = Ірілеу
editing-image-occlusion-zoom-reset = Өлшемді Қалпына Келтіру
editing-image-occlusion-toggle-translucent = Шаламөлдiрлiкті Қосу/Өшіру
editing-image-occlusion-delete = Жою
editing-image-occlusion-duplicate = Телнұсқа жасау
editing-image-occlusion-group = Таңдауды Топтастыру
editing-image-occlusion-ungroup = Таңдауды Топсыздандыру
editing-image-occlusion-select-all = Бәрін Таңдау
editing-image-occlusion-alignment = Туралау
editing-image-occlusion-align-left = Солға Туралау
editing-image-occlusion-align-h-center = Көлденең Ортаны Туралау
editing-image-occlusion-align-right = Оңға Туралау
editing-image-occlusion-align-top = Үстіге Туралау
editing-image-occlusion-align-v-center = Тік ортаны туралау
editing-image-occlusion-align-bottom = Астына Туралау
editing-image-occlusion-select-tool = Бөлшектеу
editing-image-occlusion-zoom-tool = Өлшем
editing-image-occlusion-rectangle-tool = тіктөртбұрыш
editing-image-occlusion-ellipse-tool = Эллипс
editing-image-occlusion-polygon-tool = Көпбұрыш
editing-image-occlusion-text-tool = Мәтін
editing-image-occlusion-fill-tool = Түспен толтыру
editing-image-occlusion-toggle-mask-editor = Перде Редакторын Қосу/Өшіру
editing-image-occlusion-reset = Кескін Бүркемесін Қалпына Келтіру
editing-image-occlusion-confirm-reset = Бұл кескін бүркемесін қалпына келтіргіңіз келетініне сенімдісіз бе?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML Редакторы
