decks-add-new-deck-ctrlandn = افزودن دسته جدید (Ctrl+N)
decks-build = ایجاد کردن
decks-cards-selected-by = کارت | ترتیب نمایش:
decks-create-deck = ایجاد دسته
decks_create_even_if_empty = حتی اگر خالی باشد، این دسته را ایجاد/به‌روزرسانی کنید
decks-custom-steps-in-minutes = قدم‌های سفارشی (دقیقه)
decks-deck = دسته
decks-decreasing-intervals = کاهش بازه‌های زمانی
decks-delete-deck = حذف دسته
decks-enable-second-filter = فعال‌سازی فیلتر ثانویه
decks-filter = فیلتر:
decks-filter-2 = فیلتر 2
decks-get-shared = دریافت دسته‌های اشتراکی
decks-import-file = وارد کردن فایل
decks-increasing-intervals = افزایش بازه‌های زمانی
decks-latest-added-first = آخرین اضافه شده در ابتدا قرار بگیرد
decks-limit-to = محدود به
decks-minutes = دقیقه
decks-most-lapses = بیشترین اشتباه
decks-new-deck-name = نام جدید دسته:
decks-no-deck = [بدون دسته]
decks-oldest-seen-first = آخرین دیده شده در ابتدا
decks-order-added = بر اساس زمان افزودن کارت
decks-order-due = بر اساس موعد مرور
decks-please-select-something = لطفاً چیزی انتخاب کنید.
decks-random = تصادفی
decks-relative-overdueness = تأخیر نسبی
decks-repeat-failed-cards-after = تکرار کارت‌های ناموفق بعد از
# e.g. "Delay for Again", "Delay for Hard", "Delay for Good"
decks-delay-for-button = تاخیر برای { $button }
decks-reschedule-cards-based-on-my-answers = کارت‌ها بر اساس پاسخ من در این دسته زمانبندی شود
decks-study = مطالعه
decks-study-deck = مطالعۀ دسته
decks-filtered-deck-search-empty = هیچ کارتی مطابق با جستجوی شما پیدا نشد. ممکن است برخی از کارت‌ها به دلیل اینکه در دسته فیلتر شده دیگری قرار دارند یا معلق شده‌اند از نتیجه جستجو خارج شده باشند.
decks-unmovable-cards = نمایش همه کارت‌های صرف نظر شده
decks-learn-header = یادگیری
# The count of cards waiting to be reviewed
decks-review-header = مرور
decks-zero-minutes-hint = (0: بازگشت کارت به دسته اصلی)
