editing-actual-size = تغییر اندازه واقعی
editing-add-media = افزودن رسانه
editing-align-left = چینش چپ
editing-align-right = چینش راست
editing-an-error-occurred-while-opening = یک خطا هنگام باز کردن رخ داده است { $val }
editing-attach-picturesaudiovideo = پیوست کردن عکس/صدا/فیلم
editing-bold-text = متن پررنگ (بولد)
editing-cards = کارت‌ها
editing-center = مرکز
editing-change-color = تغییر رنگ
editing-cloze-deletion = جاخالی
editing-cloze-deletion-repeat = بستن حذف (کارت یکسان)
editing-copy-image = تصویر را کپی کنید
editing-couldnt-record-audio-have-you-installed = ضبط صدا ممکن نیست. آیا ‘lame’ را نصب کرده‌اید؟
editing-customize-card-templates = شخصی‌سازی قالب کارت
editing-customize-fields = شخصی‌سازی فیلدها
editing-cut = برش
editing-double-click-image = روی تصویر دوبار کلیک کنید
editing-double-click-to-expand = برای بزرگ شدن دوبار کلیک کنید
editing-double-click-to-collapse = برای جمع کردن دوبار کلیک کنید
editing-edit-current = ویرایش فعلی
editing-edit-html = ویرایش HTML
editing-fields = فیلدها
editing-float-left = شناور به سمت چپ
editing-float-right = شناور به سمت راست
editing-float-none = بدون شناور
editing-indent = افزایش فاصله
editing-italic-text = متن کج (ایتالیک)
editing-jump-to-tags-with-ctrlandshiftandt = رفتن به برچسب‌ها ‫با کنترل+شیفت+T
editing-justify = هم‌تراز کردن
editing-latex = LaTeX
editing-latex-equation = معادله LaTeX
editing-latex-math-env = محیط ریاضی LaTeX.
editing-mathjax-block = بلوک MathJax
editing-mathjax-chemistry = فرمول شیمی MathJax
editing-mathjax-inline = ‫MathJax درون خطی
editing-mathjax-placeholder = برای پذیرش { $accept }و برای خط جدید { $newline } را فشار دهید.
editing-media = رسانه
editing-ordered-list = لیست مرتب
editing-outdent = کاهش فاصله
editing-paste = جاگذاری
editing-record-audio = ضبط صدا
editing-remove-formatting = حذف تزئین
editing-restore-original-size = بازیابی اندازه اصلی
editing-select-remove-formatting = قالب بندی را برای حذف انتخاب کنید
editing-show-duplicates = نمایش تکراریها
editing-subscript = ‏‏پایین نویس
editing-superscript = پایین نویس
editing-tags = برچسب‌ها
editing-tags-add = اضافه کردن تگ
editing-tags-copy = کپی کردن تگ
editing-tags-remove = پاک کردن تگها
editing-tags-select-all = انتخاب همه تگ ها
editing-text-color = رنگ متن
editing-text-highlight-color = رنگ هایلایت متن
editing-to-make-a-cloze-deletion-on = برای ایجاد جاخالی روی یادداشت موجود، اول باید نوع یادداشت را از مسیر 'یادداشت‌ها>تغییر نوع یادداشت' تغییر دهید
editing-toggle-html-editor = تغییر ادیتور HTML
editing-toggle-visual-editor = ویرایشگر تصویری را تغییر دهید
editing-toggle-sticky = تغییر وضعیت چسبان
editing-expand = بازکردن
editing-collapse = بستن
editing-expand-field = باز کردن فیلد
editing-collapse-field = بستن فیلد
editing-underline-text = خط کشیدن زیر متن
editing-unordered-list = لیست بدون ترتیب
editing-warning-cloze-deletions-will-not-work = اخطار، جای خالی تا وقتی که شما نوع را از بالا به جای خالی تغییر ندهید بطور صحیح کار نخواهد کرد.
editing-mathjax-preview = پیش نمایش MathJax
editing-shrink-images = کوچک کردن تصاویر
editing-close-html-tags = بستن خودکار برچسب های HTML
editing-from-clipboard = از کلیپ بورد
editing-alignment = تراز کردن
editing-equations = معادلات
editing-no-image-found-on-clipboard = هیچ تصویری در کلیپ بورد یافت نشد.
editing-image-occlusion-mode = حالت انسداد تصویر
editing-image-occlusion-zoom-out = کوچکنمایی
editing-image-occlusion-zoom-in = بزرگنمایی
editing-image-occlusion-zoom-reset = بازنشانی زوم
editing-image-occlusion-toggle-translucent = شفافیت را تغییر دهید
editing-image-occlusion-delete = حذف
editing-image-occlusion-duplicate = تکرار
editing-image-occlusion-group = انتخاب گروهی
editing-image-occlusion-ungroup = انتخاب غیر گروهی
editing-image-occlusion-select-all = انتخاب همه
editing-image-occlusion-alignment = تراز کردن
editing-image-occlusion-align-left = تراز به چپ
editing-image-occlusion-align-h-center = تراز به مرکز افقی
editing-image-occlusion-align-right = تراز به راست
editing-image-occlusion-align-top = تراز به بالا
editing-image-occlusion-align-v-center = تراز به مرکز عمودی
editing-image-occlusion-align-bottom = تراز به پایین
editing-image-occlusion-select-tool = برگزیدن
editing-image-occlusion-zoom-tool = بزرگنمایی
editing-image-occlusion-rectangle-tool = مستطیل
editing-image-occlusion-ellipse-tool = بیضی
editing-image-occlusion-polygon-tool = چند ضلعی
editing-image-occlusion-text-tool = متن
editing-image-occlusion-toggle-mask-editor = ویرایشگر پوشش را تغییر دهید
editing-image-occlusion-reset = بازنشانی انسداد تصویر
editing-image-occlusion-confirm-reset = آیا مطمئن هستید که می خواهید این انسداد تصویر را بازنشانی کنید؟

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = ویرایشگر HTML
