preferences-automatically-sync-on-profile-openclose = همگام‌سازی خودکار با بازکردن/بستن پروفایل.
preferences-backups = پشتیبان‌ها
preferences-change-deck-depending-on-note-type = تغییر دسته براساس نوع یادداشت
preferences-changes-will-take-effect-when-you = تغییرات بعد از اینکه شمال آنکی را ری‌استارت کردید اعمال خواهند شد.
preferences-hours-past-midnight = ساعت از نیمه شب گذشته
preferences-language = زبان
preferences-interrupt-current-audio-when-answering = توقف پخش صدا هنگام نمایش پاسخ
preferences-learn-ahead-limit = حد مطالعه پیش از موعد
preferences-mins = دقیقه
preferences-network = شبکه
preferences-next-day-starts-at = شروع روز جدید در
preferences-media-is-not-backed-up = رسانه پشتیبان گیری نمی شود. لطفاً یک نسخه پشتیبان دوره ای از پوشه آنکی خود ایجاد کنید تا ایمن باشید.
preferences-on-next-sync-force-changes-in = در همگام‌سازی بعدی، اجباراً در یک دستور تغییر بده
preferences-paste-clipboard-images-as-png = تصویر حافظه موقت به عنوان PNG جاگذاری شود
preferences-paste-without-shift-key-strips-formatting = جاگذاری بدون نگه داشتن کلید شیفت تزئینات فایل را از بین می‌برد
preferences-generate-latex-images-automatically = ایجاد تصاویر لاتک (خطر امنیتی)
preferences-latex-generation-disabled = تولید تصویر لاتک در تنظیمات غیرفعال است.
preferences-periodically-sync-media = همگام‌سازی رسانه به‌صورت دوره‌ای
preferences-please-restart-anki-to-complete-language = لطفاً برای نهایی‌سازی تغییر زبان آنکی را ری‌استارت کنید.
preferences-preferences = تنظیمات
preferences-scheduling = زمانبندی
preferences-show-learning-cards-with-larger-steps = کارت‌های در مرحلۀ یادگیری با قدم‌های بزرگتر را قبل از مرورها نشان بده
preferences-show-next-review-time-above-answer = زمان مرور بعدی را در بالای دکمه پاسخ نشان بده
preferences-spacebar-rates-card = دکمه فاصله (یا اینتر) نیز کارت را پاسخ می دهد
preferences-show-play-buttons-on-cards-with = دکمۀ پخش را روی کارت‌های دارای صدا نشان بده
preferences-show-remaining-card-count = نمایش تعداد کارت باقی مانده
preferences-some-settings-will-take-effect-after = برخی از تغییرات پس از اینکه انکی دوباره شروع شد اعمال خواهند شد.
preferences-tab-synchronisation = همگام سازی
preferences-synchronize-audio-and-images-too = تصاویر و صوت نیز یکپارچه شوند
preferences-login-successful-sync-now = ورود با موفقیت انجام شد. اکنون تنظیمات ذخیره و همگام‌سازی شود؟
preferences-timebox-time-limit = بازۀ زمانی هشدار مطالعه
preferences-user-interface-size = اندازۀ رابط کاربری
preferences-when-adding-default-to-current-deck = هنگام افزدون کارت جدید، دسته فعلی به عنوان پیش فرض باشد
preferences-you-can-restore-backups-via-fileswitch = شما می‌توانید فایل‌های پشتیبان را از مسیر فایل>تغییر پروفایل بازگردانی کنید.
preferences-legacy-timezone-handling = مدیریت بازه زمانی قدیمی (دارای باگ، ولی برای AnkiDroid قدیمی‌تر از 2.14 ضروری است)
preferences-default-search-text = متن جستجوی پیش فرض
preferences-default-search-text-example = به عنوان مثال 'deck:current '
preferences-theme = طرح
preferences-theme-follow-system = سیستم را دنبال کنید
preferences-theme-light = روشن
preferences-theme-dark = تاریک
preferences-v3-scheduler = زمانبندی V3
preferences-check-for-updates = به روز رسانی برنامه بررسی شود
preferences-ignore-accents-in-search = نادیده گرفتن لهجه ها در جستجو (کندتر)
preferences-backup-explanation =
    آنکی به صورت دوره ای از مجموعه شما نسخه پشتیبان تهیه می کند. پس از گذشت بیش از 2 روز از نسخه پشتیبان،
    آنکی برای آزاد کردن فضای دیسک شروع به حذف برخی از آنها می کند.
preferences-daily-backups = پشتیبان گیری روزانه برای نگهداری:
preferences-weekly-backups = پشتیبان گیری هفتگی برای نگهداری:
preferences-monthly-backups = پشتیبان گیری ماهانه برای نگهداری:
preferences-minutes-between-backups = دقایق بین پشتیبان گیری خودکار:
preferences-reduce-motion = کاهش حرکت
preferences-reduce-motion-tooltip = انیمیشن ها و انتقال های مختلف رابط کاربری را غیرفعال کنید
preferences-custom-sync-url = سرور همگام با میزبانی خود
preferences-custom-sync-url-disclaimer = برای کاربران پیشرفته - لطفا به دفترچه راهنما مراجعه کنید
preferences-hide-top-bar-during-review = پنهان کردن نوار بالا در حین بازبینی
preferences-hide-bottom-bar-during-review = پنهان کردن نوار پایین در حین بازبینی
preferences-always = همیشه
preferences-full-screen-only = فقط تمام صفحه
preferences-appearance = شکل ظاهری
preferences-general = عمومی
preferences-style = استایل
preferences-review = مرور
preferences-answer-keys = کلیدهای پاسخ
preferences-distractions = حواس پرتی ها
preferences-minimalist-mode = حالت مینیمالیست
preferences-minimalist-mode-tooltip = رابط را جمع و جورتر کنید
preferences-editing = در حال ویرایش
preferences-browsing = مرور
preferences-default-deck = دسته پیش فرض
preferences-account = حساب AnkiWeb
preferences-note = یادداشت
preferences-scheduler = زمانبندی
preferences-user-interface = رابط کاربری
preferences-import-export = ورود/خروج
preferences-network-timeout = پایان مهلت زمانی شبکه
preferences-reset-window-sizes = بازیابی سایز پنجره ها
preferences-reset-window-sizes-complete = مکان و سایز پنجره ها بازیابی شد.
preferences-shortcut-placeholder = یک کلید میانبر استفاده نشده وارد کنید یا برای غیرفعال کردن آن را خالی بگذارید.
preferences-third-party-services = سرویس های شخص ثالث
preferences-ankihub-not-logged-in = در حال حاضر به AnkiHub وارد نشده‌اید.
preferences-ankiweb-intro = AnkiWeb یک سرویس رایگان است که به شما امکان می دهد داده های فلش کارت خود را در بین دستگاه های خود همگام نگه دارید و در صورت خراب شدن یا گم شدن دستگاه، راهی برای بازیابی اطلاعات ارائه می دهد.
preferences-ankihub-intro = AnkiHub ویرایش مشترک دسته ها و ابزارهای مطالعه اضافی را فراهم می کند. برای دسترسی به برخی ویژگی‌ها به اشتراک پولی نیاز است.
preferences-third-party-description = خدمات شخص ثالث، غیروابسته به آنکی هستند و توسط آنکی تایید نمی شوند. استفاده از این خدمات ممکن است نیاز به پرداخت داشته باشد.

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = پایه
preferences-reviewer = بازبینی کننده
preferences-media = رسانه
preferences-not-logged-in = در حال حاضر به AnkiWeb وارد نشده اید.
