decks-add-new-deck-ctrlandn = ନୂତନ ଡେକ୍ ଯୋଡ଼ନ୍ତୁ (Ctrl+N)
decks-build = ନିର୍ମାଣ କରନ୍ତୁ
decks-cards-selected-by = ଏହି ଆଧାରରେ ପତ୍ରଗୁଡ଼ିକ ଚୟନ କରାଯାଏ
decks-create-deck = ଡେକ୍ ସୃଷ୍ଟି କରନ୍ତୁ
decks-custom-steps-in-minutes = କଷ୍ଟମ୍ ପାହୁଣ୍ଡ (ମିନିଟ୍ ରେ)
decks-deck = ଡେକ୍
decks-decreasing-intervals = କମୁଥିବା ଅନ୍ତରାଳ
decks-delete-deck = ଡେକ୍ ବିଲୋପ କରନ୍ତୁ
decks-enable-second-filter = ଦ୍ୱିତୀୟ ଶୋଧକ ସକ୍ଷମ କରନ୍ତୁ
decks-filter = ଶୋଧକ:
decks-filter-2 = ଶୋଧକ 2
decks-get-shared = ଅଂଶୀଦାର ହୋଇଥିବା ଡେକ୍ ପାଆନ୍ତୁ
decks-import-file = ଫାଇଲ୍ ଆମଦାନୀ କରନ୍ତୁ
decks-increasing-intervals = ବଢ଼ୁଥିବା ଅନ୍ତରାଳ
decks-latest-added-first = ସର୍ବଶେଷରେ ଯୋଡ଼ା ଯାଇଥିବା ପ୍ରଥମେ
decks-limit-to = ଏତିକିରେ ସୀମିତ ରଖ
decks-minutes = ମିନିଟ୍
decks-most-lapses = ସବୁଠୁ ଅଧିକ ଲାପ୍ସ ହୋଇଥିବା
decks-name-for-deck = ଡେକ୍ ପାଇଁ ନାମ:
decks-new-deck-name = ନୂତନ ଡେକ୍ ନାମ:
decks-no-deck = [ଡେକ୍ ନାହିଁ]
decks-oldest-seen-first = ପ୍ରଥମେ ସର୍ବପୁରାତନ
decks-order-added = ଯୋଡ଼ାଯିବା କ୍ରମାନୁସାରେ
decks-order-due = ଧାର୍ଯ୍ୟ କ୍ରମାନୁସାରେ
decks-please-select-something = ଦୟାକରି କିଛି ଚୟନ କରନ୍ତୁ।
decks-random = ଅନିୟମିତ
decks-relative-overdueness = ଆପେକ୍ଷିକ ଅତ୍ୟଧିକତା
decks-study = ଅଧ୍ୟୟନ
decks-study-deck = ଅଧ୍ୟୟନ ଡେକ୍
decks-filtered-deck-search-empty = ପ୍ରଦତ୍ତ ସନ୍ଧାନ ସହିତ କୌଣସି ପତ୍ର ମେଳ ଖାଉ ନାହିଁ। କିଛି ପତ୍ର କୁ ବାଦ ଦିଆଯାଇଥାଇପାରେ କାରଣ ସେଗୁଡ଼ିକ ଏକ ଭିନ୍ନ ଶୋଧିତ ତାସଖଣ୍ଡ ରେ ଅଛି, କିମ୍ୱା ନିଲମ୍ବିତ ହୋଇଅଛି।
decks-unmovable-cards = ସବୁ ବହିଷ୍କୃତ ପତ୍ର ଦେଖାନ୍ତୁ
# The count of cards waiting to be reviewed
decks-review-header = ବାକି ଅଛି
decks-learn-header = ଶିଖୁଛନ୍ତି
