actions-add = jmina
actions-blue-flag = blanu lanci tcita
actions-cancel = sisti
actions-choose = cuxna
actions-close = mipri
actions-copy = fukra'e
actions-custom-study = macnu tadni
actions-decks = karda selcmi
actions-delete = vimcu
actions-export = barbei
actions-filter = julne
actions-green-flag = crino lanci tcita
actions-help = sidju
actions-import = nerbei
actions-manage = nu jitro
actions-name = cmene
actions-new = cnino
actions-new-name = basti fi lo ka cmene
actions-options = te tcimi'e
actions-options-for = te tcimi'e je cu srana la'o zoi. { $val } .zoi
actions-orange-flag = narju lanci tcita
actions-preview = purzga
actions-rebuild = za'u re'u zbasu
actions-red-flag = xunre lanci tcita
actions-rename = basti fi lo ka cmene
actions-rename-deck = basti fi lo ka cmene lo karda selcmi
actions-replay-audio = nu za'u re'u snavi
actions-reposition = nu basti lo se pormoi
actions-save = rejgau
actions-search = sisku
actions-suspend-card = mipri pa karda
actions-processing = .i ca'o gunka
