editing-add-media = jmina pa ganvi
editing-an-error-occurred-while-opening = .i da nabmi fi lo nu samymo'i la'o zoi. { $val } .zoi
editing-attach-picturesaudiovideo-f3 = jmina pa pixra ja pa snavi ja pa vidvi (F3)
editing-bold-text-ctrlandb = rotsu (Ctrl+B)
editing-cards = karda
editing-change-colour-f8 = basti fi lo ka se skari (F8)
editing-cloze-deletion-ctrlandshiftandc = cipra mipri (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = .i ka'e nai rejgau lo snavei .i ko ci'erse'a la'o zoi. lame .zoi
editing-cut = nu vicra'e
editing-edit-current = nu lo se cuxna cu binxo
editing-edit-html = nu basti lo lerpoi be bau la .xetmel.
editing-fields = datnyvau
editing-html-editor = tutci lo nu basti lo lerpoi be bau la .xetmel.
editing-latex = la .latex.
editing-latex-equation = du la .latex. ku mesko
editing-latex-math-env = du la .latex. ku sepli mesko
editing-media = te ganvi
editing-paste = nu fukpu'i
editing-record-audio-f5 = nu rejgau pa snavei (F5)
editing-set-foreground-colour-f7 = basti fi lo ka se skari lo crane (F7)
editing-show-duplicates = liste lo'i mintu
editing-tags = tcita
