preferences-automatically-sync-on-profile-openclose = nu zmiku lo nu datni sarxe kei lo nu samymo'i jo nai to'e samymo'i pa pilno datni
preferences-backups = nurfu'i
preferences-backups2 = nurfu'i
preferences-backupsanki-will-create-a-backup-of = <b>nurfu'i</b><br>.i la .ankis. cu cupra lo nurfu'i be lo do karda selcmi selcmi co'a ro nu to'e samymo'i ri kei je ro nu ri co'a datni sarxe
preferences-basic = sampu
preferences-change-deck-depending-on-note-type = nu muvdu lo karda selcmi poi drata vau ji'u lo karda datni klesi
preferences-changes-will-take-effect-when-you = .i binxo mo'u lo nu do za'u re'u katcygau lo .ankis.
preferences-hardware-acceleration-faster-may-cause-display = samca'a sutra to zmadu fi lo ka sutra .i kakne lo ka rinka pa jvinu nabmi toi
preferences-interface-language = bangu pa sazycimde
preferences-keep = ralte
preferences-mins = mentu
preferences-network = se tcana
preferences-next-day-starts-at = tcika lo nu lo djedi cu cfari
preferences-night-mode = nicte jvinu
preferences-note-media-is-not-backed-up = .i ju'i do no da zmiku nurfu'i lo te ganvi .i ko di'i macnu cupra lo nurfu'i be lo datnyveimei pe la .ankis.
preferences-paste-clipboard-images-as-png = nu ro se fukpu'i poi pixra cu me la me py ny gy.
preferences-please-restart-anki-to-complete-language = .i ko za'u re'u katcygau la .ankis. no'au rinka lo nu mo'u bangu basygau
preferences-preferences = te tcimi'e
preferences-scheduling = basti fi lo ka tcika
preferences-show-next-review-time-above-answer = nu lo bavla'i ke te morji temci cu visycu'i fi lo nu ri gapru lo te spuda batkyuidje
preferences-synchronisation = <b>nu co'a datni sarxe</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>nu co'a datni sarxe</b><br> .i ca ganda .i lo nu da te cabra fi lo nu co'a datni sarxe kei batkyuidje cu rinka lo nu katci
