profiles-anki-could-not-read-your-profile = Anki nemohl přečíst vaše profilová data. Velikosti oken a vaše přihlašovací informace k synchronizaci byly zapomenuty.
profiles-anki-could-not-rename-your-profile = Anki nemohl přejmenovat Váš profil, protože nešlo přejmenovat složku profilu na disku. Oveřte si, zda máte právo pro zápis do složky Dokumenty/Anki a žádný jiný program právě nepoužívá složku Vašeho profilu a zkuste to znova.
profiles-folder-already-exists = Adresář již existuje.
profiles-open = Otevřít
profiles-open-backup = Otevřít zálohu...
profiles-please-remove-the-folder-and = Odstraňte prosím složku { $val } a zkuste to znova.
profiles-profile-corrupt = Poškozený profil
profiles-profiles = Profily
profiles-quit = Ukončit
profiles-user-1 = Uživatel 1
profiles-confirm-lang-choice = Opravdu si přejete zobrazit rozhraní Anki v { $lang }?
profiles-could-not-create-data-folder = Anki nemohlo vytvořit svou datovou složku. Prosím přečtěte si v manuálu část Umístění souborů a ujistěte se, že umístění není jen pro čtení.
profiles-prefs-corrupt-title = Nastavení poškozeno
profiles-prefs-file-is-corrupt = Anki soubor prefs21.db byl poškozen a byl znovu vytvořen. Jestliže jste používali více profilů, prosím přidejte je zpět tak, že použijete stejné názvy, abyste obnovili vaše karty.
profiles-profile-does-not-exist = Požadovaný profil neexistuje.
profiles-creating-backup = Vytváří se záloha...
profiles-backup-created = Záloha vytvořena.
profiles-backup-creation-failed = Vytváření zálohy selhalo: { $reason }
profiles-backup-unchanged = Žádné změny od poslední zálohy.
