card-stats-added = تاريخ الإضافة
card-stats-first-review = أول مراجعة
card-stats-latest-review = آخر مراجعة
card-stats-interval = الفاصل الزمني
card-stats-ease = سهولة
card-stats-review-count = مراجعات
card-stats-lapse-count = سقطات
card-stats-average-time = معدل الوقت
card-stats-total-time = الوقت الكلي
card-stats-new-card-position = الموضع
card-stats-card-template = نوع البطاقة
card-stats-note-type = نوع الملحوظة
card-stats-deck-name = رزمة
card-stats-preset = مجموعة الخيارات
card-stats-note-id = مُعرّف الملحوظة
card-stats-card-id = مُعرّف البطاقة
card-stats-review-log-rating = التقييم
card-stats-review-log-type = النوع
card-stats-review-log-date = التاريخ
card-stats-review-log-time-taken = الوقت
card-stats-review-log-type-learn = في طور التعلم
card-stats-review-log-type-review = مراجعة
card-stats-review-log-type-relearn = في طور إعادة التعلم
card-stats-review-log-type-filtered = مفلتر
card-stats-review-log-type-manual = يدوي
card-stats-review-log-type-rescheduled = معاد جدولتها
card-stats-review-log-elapsed-time = الوقت الماضي
card-stats-no-card = (لا توجد بطاقة لعرضها.)
card-stats-custom-data = بيانات مخصصة
card-stats-fsrs-stability = استقرار
card-stats-fsrs-difficulty = صعوبة
card-stats-fsrs-retrievability = إمكانية الاسترجاع
card-stats-fsrs-forgetting-curve-title = منحنى النسيان
card-stats-fsrs-forgetting-curve-first-week = الأسبوع الأول
card-stats-fsrs-forgetting-curve-first-month = الشهر الأول
card-stats-fsrs-forgetting-curve-first-year = السنة الأولى
card-stats-fsrs-forgetting-curve-all-time = كل الوقت
card-stats-fsrs-forgetting-curve-probability-of-recalling = احتمالية الاسترجاع
card-stats-fsrs-forgetting-curve-desired-retention = معدل التذكر المرغوب فيه

## Window Titles

card-stats-current-card = البطاقة الحالية ({ $context })
card-stats-previous-card = البطاقة السابقة ({ $context })
