editing-actual-size = ضبط الحجم الفعلي
editing-add-media = إضافة وسائط
editing-align-left = محاذاة إلى اليسار
editing-align-right = محاذاة إلى اليمين
editing-an-error-occurred-while-opening = حدث خطأ عند فتح { $val }
editing-attach-picturesaudiovideo = ألحق صور/ملفات صوتية/فيديو
editing-bold-text = خط غامق
editing-cards = البطاقات
editing-center = محاذاة إلى الوسط
editing-change-color = تغيير اللون
editing-cloze-deletion = ملء فراغات
editing-cloze-deletion-repeat = ملء الفراغات (البطاقة نفسها)
editing-copy-image = نسخ الصورة
editing-couldnt-record-audio-have-you-installed = لا يمكن تسجيل الصوت. هل نصبّت 'lame'؟
editing-customize-card-templates = تخصيص قوالب البطاقات
editing-customize-fields = خصص الحقول
editing-cut = قص
editing-double-click-image = انقر نقرتين على الصورة
editing-double-click-to-expand = انقر نقرتين للإسدال
editing-double-click-to-collapse = انقر نقرتين للطي
editing-edit-current = تحرير البطاقة الحالية
editing-edit-html = تحرير HTML
editing-fields = الحقول
editing-float-left = محاذاة لليسار
editing-float-right = محاذاة لليمين
editing-float-none = لا محاذاة
editing-indent = زيادة الإزاحة
editing-italic-text = خط مائل
editing-jump-to-tags-with-ctrlandshiftandt = انتقل إلى الوسوم باستخدام Ctrl+Shift+T
editing-justify = محاذاة
editing-latex = LaTeX
editing-latex-equation = معادلة LaTeX
editing-latex-math-env = بيئة LaTeX الرياضية
editing-mathjax-block = كتلة MathJax
editing-mathjax-chemistry = MathJax كيمياء
editing-mathjax-inline = MathJax مضمَّن
editing-mathjax-placeholder = اضغط { $accept } للموافقة، { $newline } لإضافة سطر جديد.
editing-media = وسائط
editing-open-image = فتح الصورة
editing-show-in-folder = إظهار في المجلد
editing-ordered-list = قائمة مرقمة
editing-outdent = خفض الإزاحة
editing-paste = لصق
editing-record-audio = تسجيل صوت
editing-remove-formatting = إزالة التنسيق
editing-restore-original-size = استعادة الحجم الأصلي
editing-select-remove-formatting = حدد التنسيق الذي تريد حذفه
editing-show-duplicates = إظهار الملحوظات المكررة
editing-subscript = خط تحتي
editing-superscript = خط فوقي
editing-tags = وسوم
editing-tags-add = أضف وسمًا
editing-tags-copy = نسخ الوسوم
editing-tags-remove = حذف الوسوم
editing-tags-select-all = تحديد كل الوسوم
editing-text-color = لون النص
editing-text-highlight-color = لون تظليل النص
editing-to-make-a-cloze-deletion-on = لصنع عبارة ملء فراغات في ملحوظة موجودة، عليك تغيير نوعها إلى نوع ملء الفراغات أولًا، عبر 'ملحوظات>تغيير نوع الملحوظة'
editing-toggle-html-editor = تفعيل محرر HTML أو إيقافه
editing-toggle-visual-editor = تفعيل المحرر المرئي أو إيقافه
editing-toggle-sticky = تفعيل/إيقاف ثبات النص
editing-expand = إسدال
editing-collapse = طي
editing-expand-field = إسدال الحقل
editing-collapse-field = طي الحقل
editing-underline-text = تسطير النص
editing-unordered-list = قائمة غير مرقمة
editing-warning-cloze-deletions-will-not-work = تحذير، عبارات ملء الفراغات لن تعمل حتى تغيّر النوع في الأعلى إلى نوع ملء الفراغات.
editing-mathjax-preview = معاينة MathJax
editing-shrink-images = تقليص الصور
editing-close-html-tags = إغلاق وسوم HTML تلقائيًا
editing-from-clipboard = من الحافظة
editing-alignment = محاذاة
editing-equations = معادلات
editing-no-image-found-on-clipboard = لم يتم العثور على صورة في الحافظة.
editing-image-occlusion-mode = وضع صورة معماة
editing-image-occlusion-zoom-out = تصغير
editing-image-occlusion-zoom-in = تكبير
editing-image-occlusion-zoom-reset = إعادة ضبط مستوى التكبير
editing-image-occlusion-toggle-translucent = تبديل الشفافية
editing-image-occlusion-delete = حذف
editing-image-occlusion-duplicate = تكرير
editing-image-occlusion-group = تجميع العناصر
editing-image-occlusion-ungroup = فك تجميع العناصر
editing-image-occlusion-select-all = تحديد الكل
editing-image-occlusion-alignment = محاذاة
editing-image-occlusion-align-left = محاذاة إلى اليسار
editing-image-occlusion-align-h-center = توسيط أفقيًا
editing-image-occlusion-align-right = محاذاة إلى اليمين
editing-image-occlusion-align-top = محاذاة إلى الأعلى
editing-image-occlusion-align-v-center = توسيط عموديًا
editing-image-occlusion-align-bottom = محاذاة إلى الأسفل
editing-image-occlusion-select-tool = تحديد
editing-image-occlusion-zoom-tool = مستوى التكبير
editing-image-occlusion-rectangle-tool = مستطيل
editing-image-occlusion-ellipse-tool = شكل بيضاوي
editing-image-occlusion-polygon-tool = مضلع
editing-image-occlusion-text-tool = نص
editing-image-occlusion-fill-tool = تلوين
editing-image-occlusion-toggle-mask-editor = إظهار/إخفاء محرر التعتيم
editing-image-occlusion-reset = إعادة ضبط الصورة المعماة
editing-image-occlusion-confirm-reset = هل أنت متأكد من أنك تريد إعادة ضبط صورة التعتيم هذه؟

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = محرر HTML
