decks-add-new-deck-ctrlandn = Erantsi sorta berria (Ktrl+N)
decks-build = Eraiki
decks-cards-selected-by = txartel. Aukeratzeko irizpidea:
decks-create-deck = Sortu sorta
decks-custom-steps-in-minutes = Urrats pertsonalizatuak (minututan)
decks-deck = Sorta
decks-decreasing-intervals = Tarteak beherantz
decks-delete-deck = Ezabatu sorta
decks-enable-second-filter = Gaitu bigarren iragazkia
decks-filter = Iragazkia:
decks-filter-2 = 2. iragazkia
decks-get-shared = Lortu partekatua
decks-import-file = Inportatu fitxategia
decks-increasing-intervals = Tarteak gorantz
decks-latest-added-first = Erantsitako azkenak lehenik
decks-limit-to = Mugatu hona:
decks-minutes = minutu
decks-most-lapses = Hutsegite gehien dutenak
decks-new-deck-name = Sorta berriaren izena:
decks-no-deck = [sortarik ez]
decks-oldest-seen-first = Aspaldi ikusitakoak lehenik
decks-order-added = Erantsitako ordena
decks-order-due = Berrikuste-dataren arabera
decks-please-select-something = Aukeratu zerbait.
decks-random = Ausazkoa
decks-relative-overdueness = Atzerapen erlatiboa
decks-repeat-failed-cards-after = Errepikatu huts egindakoak tarte honen ondoren:
decks-reschedule-cards-based-on-my-answers = Birprogramatu txartelak nire sorta honetako erantzunen arabera
decks-study = Ikasi
decks-study-deck = Ikasi sorta
decks-filtered-deck-search-empty = Bilaketarekin bat datorren txartelik ez. Baliteke txartel batzuk baztertu izana beste iragazitako sorta batean daudelako edo etenda daudelako.
decks-unmovable-cards = Erakutsi baztertutako txartelak
decks-review-header = Zor izanda
decks-learn-header = Ikasi
