notetypes-front-field = Aurrea
notetypes-back-field = Atzera
notetypes-add-reverse-field = Erantsi alderantzizkoa
notetypes-text-field = Testua
notetypes-basic-name = Oinarrizkoa
notetypes-basic-reversed-name = Oinarrizko (eta alderantzizko karta)
notetypes-basic-optional-reversed-name = Oinarrizko( aukerako alderantzizko karta)
notetypes-cloze-name = hutsuneak betetzea
notetypes-card-2-name = bigarren karta
notetypes-card-1-name = 1 karta
notetypes-add = Erantsi: { $val }
notetypes-add-note-type = Erantsi ohar mota
notetypes-cards = Kartak...
notetypes-clone = Klonatu: { $val }
notetypes-copy = { $val }-ren kopia
notetypes-delete-this-note-type-and-all = Ezabatu ohar-mota hau eta bere karta guztiak?
notetypes-delete-this-unused-note-type = Erabili gabeko ohar-mota hau ezabatu?
notetypes-fields = Eremuak...
notetypes-footer = Oina
notetypes-header = Goiburua
notetypes-note-types = ohar-motak
notetypes-options = Aukerak...
notetypes-please-add-another-note-type-first = Mesedez, erantsi beste ohar mota bat lehenik
notetypes-type = Mota
