qt-accel-about = &About
qt-accel-about-mac = About Anki...
qt-accel-cards = &Cards
qt-accel-check-database = &Check Database
qt-accel-check-media = Check &Media
qt-accel-edit = &Edit
qt-accel-exit = E&xit
qt-accel-export = &Export...
qt-accel-export-notes = &Export Notes...
qt-accel-file = &File
qt-accel-filter = Fil&ter
qt-accel-find = &Find
qt-accel-find-and-replace = Find and Re&place...
qt-accel-find-duplicates = Find &Duplicates...
qt-accel-go = &Go
qt-accel-guide = &Guide
qt-accel-help = &Help
qt-accel-import = &Import...
qt-accel-info = &Info...
qt-accel-invert-selection = &Invert Selection
qt-accel-next-card = &Next Card
qt-accel-note = N&ote
qt-accel-notes = &Notes
qt-accel-preferences = &Preferences
qt-accel-previous-card = &Previous Card
qt-accel-select-all = Select &All
qt-accel-select-notes = Select &Notes
qt-accel-support-anki = &Support Anki
qt-accel-switch-profile = &Switch Profile
qt-accel-tools = &Tools
qt-accel-undo = &Undo
qt-accel-redo = &Redo
qt-accel-set-due-date = Set &Due Date...
qt-accel-forget = &Reset
qt-accel-view = &View
qt-accel-full-screen = Toggle &Full Screen
qt-accel-layout = &Layout
qt-accel-layout-auto = &Auto
qt-accel-layout-vertical = &Vertical
qt-accel-layout-horizontal = &Horizontal
qt-accel-zoom-in = Zoom &In
qt-accel-zoom-out = Zoom &Out
qt-accel-reset-zoom = &Reset Zoom
qt-accel-toggle-sidebar = Toggle Sidebar
qt-accel-zoom-editor-in = Zoom Editor &In
qt-accel-zoom-editor-out = Zoom Editor &Out
qt-accel-create-backup = Create &Backup
qt-accel-load-backup = &Revert to Backup
qt-accel-upgrade-downgrade = Upgrade/Downgrade
