decks-add-new-deck-ctrlandn = Lisää uusi pakka (Ctrl + N)
decks-build = Kokoa
decks-cards-selected-by = korttiin, jotka on valittu perusteella
decks-create-deck = Luo pakka
decks_create_even_if_empty = Luo/päivitä tämä pakka, vaikka se olisi tyhjä
decks-custom-steps-in-minutes = Mukautetut askeleet (minuuteissa)
decks-deck = Pakka
decks-decreasing-intervals = Kertausvälien mukaan laskevassa järjestyksessä
decks-delete-deck = Poista pakka
decks-enable-second-filter = Käytä toista suodatinta
decks-filter = Suodatin:
decks-filter-2 = Suodatin 2
decks-get-shared = Hanki jaettu pakka
decks-import-file = Tuo tiedosto
decks-increasing-intervals = Kertausvälien mukaan kasvavassa järjestyksessä
decks-latest-added-first = Lisäyspäivämäärän mukaan, uusin ensin
decks-limit-to = Rajoita
decks-minutes = minuuttia
decks-most-lapses = Eniten virheitä
decks-new-deck-name = Uuden pakan nimi:
decks-no-deck = [ei pakkaa]
decks-oldest-seen-first = Oppimispäivämäärän mukaan, vanhin ensin
decks-order-added = Lisäysjärjestyksen mukaan
decks-order-due = Erääntymisjärjestyksen mukaan
decks-please-select-something = Valitse jotain.
decks-random = Satunnainen
decks-relative-overdueness = Suhteellinen erääntyneisyys
decks-repeat-failed-cards-after = Toista väärin vastatut kortit, kun on kulunut
# e.g. "Delay for Again", "Delay for Hard", "Delay for Good"
decks-delay-for-button = Viive vastaustyypille { $button }
decks-reschedule-cards-based-on-my-answers = Ajasta kortit uudestaan perustuen vastauksiini tässä pakassa
decks-study = Opiskele
decks-study-deck = Opiskele pakkaa
decks-filtered-deck-search-empty = Yksikään kortti ei vastannut annettua hakua. Jotkin kortit on saatettu jättää pois, koska ne ovat eri suodatetussa pakassa tai ne on hyllytetty.
decks-unmovable-cards = Näytä kaikki poissuljetut kortit
decks-learn-header = Opittavat
# The count of cards waiting to be reviewed
decks-review-header = Erääntyneet
decks-zero-minutes-hint = (0 = palauta kortti alkuperäiseen pakkaan)
