profiles-anki-could-not-read-your-profile = Anki ei voinut lukea profiilisi tietoja. Ikkunoiden koot ja synkronoinnin sisäänkirjautumistiedot on unohdettu.
profiles-anki-could-not-rename-your-profile = Anki ei voinut nimetä profiiliasi uudelleen, koska se ei voinut nimetä uudelleen levylle tallennettua profiilikansiota. Varmista, että sinulla kirjoitusoikeudet kansioon Documents/Anki eivätkä mitkään muut ohjelmat käytä profiilikansioitasi, ja yritä sitten uudelleen.
profiles-folder-already-exists = Kansio on jo olemassa
profiles-open = Avaa
profiles-open-backup = Avaa varmuuskopio...
profiles-please-remove-the-folder-and = Poista kansio { $val } ja yritä uudelleen.
profiles-profile-corrupt = Viallinen profiili
profiles-profiles = Profiilit
profiles-quit = Lopeta
profiles-user-1 = Käyttäjä 1
profiles-confirm-lang-choice = Oletko varma, että haluat näyttää Ankin käyttöliittymän kielellä { $lang }?
profiles-could-not-create-data-folder = Anki ei pystynyt luomaan datakansiotaan. Tutustu käyttöoppaan Tiedostojen sijainnit -osioon ja varmista, että sijaintiin on kirjoitusoikeudet.
profiles-prefs-corrupt-title = Vialliset asetukset
profiles-prefs-file-is-corrupt = Ankin prefs21.db-tiedosto oli vioittunut ja se on luotu uudelleen. Jos käytit useita profiileja, lisää ne takaisin samoilla nimillä, jotta voit palauttaa korttisi.
profiles-profile-does-not-exist = Haettua profiilia ei ole olemassa.
profiles-creating-backup = Luodaan varmuuskopiota...
profiles-backup-created = Varmuuskopio luotu.
profiles-backup-creation-failed = Varmuuskopion luominen epäonnistui: { $reason }
profiles-backup-unchanged = Ei muutoksia viimeisimmän varmuuskopion jälkeen.
