qt-accel-about = &Tietoja...
qt-accel-about-mac = Tietoja Ankista...
qt-accel-cards = &Kortit
qt-accel-check-database = &Tarkista tietokanta
qt-accel-check-media = Tarkista &mediatiedostot
qt-accel-edit = &Muokkaa
qt-accel-exit = &Lopeta
qt-accel-export = &Vie...
qt-accel-export-notes = &Vie muistiinpanot...
qt-accel-file = &Tiedosto
qt-accel-filter = Suoda&ta
qt-accel-find = &Etsi
qt-accel-find-and-replace = &Etsi ja korvaa...
qt-accel-find-duplicates = Etsi &kaksoiskappaleet...
qt-accel-go = &Siirry
qt-accel-guide = &Käyttöohje
qt-accel-help = &Ohje
qt-accel-import = &Tuo...
qt-accel-info = &Tiedot...
qt-accel-invert-selection = &Käänteinen valinta
qt-accel-next-card = &Seuraava kortti
qt-accel-note = Muistiinpan&o
qt-accel-notes = &Muistiinpanot
qt-accel-preferences = &Asetukset
qt-accel-previous-card = &Edellinen kortti
qt-accel-select-all = Valitse &kaikki
qt-accel-select-notes = Valitse &muistiinpanot
qt-accel-support-anki = &Tue Ankia
qt-accel-switch-profile = &Vaihda profiilia
qt-accel-tools = T&yökalut
qt-accel-undo = &Kumoa
qt-accel-redo = &Tee uudelleen
qt-accel-set-due-date = Aseta &eräpäivä...
qt-accel-forget = &Unohda
qt-accel-view = &Näytä
qt-accel-full-screen = &Koko näyttö
qt-accel-layout = &Asettelu
qt-accel-layout-auto = &Automaattinen
qt-accel-layout-vertical = &Pystysuuntainen
qt-accel-layout-horizontal = &Vaakasuuntainen
qt-accel-zoom-in = &Lähennä
qt-accel-zoom-out = L&oitonna
qt-accel-reset-zoom = &Todellinen koko
qt-accel-toggle-sidebar = Näytä/piilota sivupalkki
qt-accel-zoom-editor-in = &Lähennä muokkausnäkymää
qt-accel-zoom-editor-out = &Loitonna muokkausnäkymää
qt-accel-create-backup = Luo &varmuuskopio
qt-accel-load-backup = &Palauta varmuuskopio
qt-accel-upgrade-downgrade = Päivitä/Palauta aiempi versio
