qt-accel-about = &Maidir Le...
qt-accel-cards = &Cártaí
qt-accel-check-database = Seiceáil an &Bunachar Sonraí
qt-accel-check-media = Seiceáil &Meáin...
qt-accel-edit = Cuir in &eagar
qt-accel-exit = &Scoir
qt-accel-export = &Easpórtáil...
qt-accel-export-notes = &Easpórtáil Nótaí...
qt-accel-file = &Comhad
qt-accel-filter = Sca&gaire
qt-accel-find = &Aimsigh
qt-accel-find-and-replace = Aimsigh agus Athchui&r...
qt-accel-find-duplicates = Aimsigh &Dúblaigh...
qt-accel-go = &Téigh
qt-accel-guide = &Treoir...
qt-accel-help = Ca&bhair
qt-accel-import = &Iompórtáil...
qt-accel-info = &Eolas...
qt-accel-invert-selection = &Malartaigh a bhFuil Roghnaithe
qt-accel-next-card = &Céad Cárta Eile
qt-accel-note = &Nóta
qt-accel-notes = &Nótaí
qt-accel-preferences = &Sainroghanna...
qt-accel-previous-card = Cárta &Roimhe Seo
qt-accel-select-all = Roghnaigh &Uile
qt-accel-select-notes = Roghnaigh &Nótaí
qt-accel-support-anki = &Cabhraigh le hAnki...
qt-accel-switch-profile = &Athraigh Próifíl
qt-accel-tools = &Uirlisí
qt-accel-undo = &Cealaigh
qt-accel-redo = At&hdhéan
qt-accel-set-due-date = Socraigh &Dáta Staidéir
qt-accel-forget = &Lig i nDearmad
qt-accel-view = &Breathnaigh
qt-accel-full-screen = Scoránaigh &Lánscáileán
qt-accel-layout = &Leagan amach
qt-accel-layout-auto = &Uathoibríoch
qt-accel-layout-vertical = &Ingearach
qt-accel-layout-horizontal = &Cothrománach
qt-accel-zoom-in = Zúmáil &Isteach
qt-accel-zoom-out = Zúmáil &Amach
qt-accel-reset-zoom = &Bain Zúmáil
qt-accel-zoom-editor-in = Athraigh Zúmáil &Isteach
qt-accel-zoom-editor-out = Athraigh Zúmáil &Amach
qt-accel-create-backup = Déan @Cóip Chúltaca
