exporting-all-decks = Semua Dek
exporting-anki-20-deck = Dek Anki 2.0
exporting-anki-collection-package = Paket Koleksi Anki
exporting-anki-deck-package = Paket Dek Anki
exporting-cards-in-plain-text = Kartu-kartu dalam teks biasa
exporting-collection = koleksi
exporting-collection-exported = Koleksi diekspor.
exporting-colpkg-too-new = Harap perbarui Anki ke versi terbaru, lalu impor kembali file .colpkg/.apkg.
exporting-couldnt-save-file = Tidak dapat menyimpan file: { $val }
exporting-export = Mengekspor...
exporting-export-format = <b>Format ekspor</b>:
exporting-include = <b>Sertakan</b>:
exporting-include-html-and-media-references = Sertakan HTML dan referensi media
exporting-include-media = Sertakan media
exporting-include-scheduling-information = Sertakan informasi penjadwalan
exporting-include-deck-configs = Sertakan preset-preset dek
exporting-include-tags = Sertakan tag
exporting-support-older-anki-versions = Dukungan untuk versi Anki yang lebih lama (lebih lambat/ukuran file lebih besar)
exporting-notes-in-plain-text = Catatan-catatan dalam teks biasa
exporting-selected-notes = Catatan dipilih
exporting-card-exported = { $count } kartu telah diekspor.
exporting-exported-media-file = { $count } file media telah diekspor.
exporting-note-exported = { $count } catatan telah diekspor.
exporting-exporting-file = Mengekspor file...
exporting-processed-media-files = { $count } media files telah diproses...
exporting-include-deck = Sertakan nama dek
exporting-include-notetype = Sertakan nama jenis catatan
exporting-include-guid = Sertakan pengidentifikasi unik
