card-stats-added = Ավելացվել է
card-stats-first-review = Առաջին ցուցադրություն
card-stats-latest-review = Վերջին կրկնություն
card-stats-interval = Ժամանակամիջոց
card-stats-ease = Հեշտություն
card-stats-review-count = Կրկնություններ
card-stats-lapse-count = Մոռացված
card-stats-average-time = Միջին ժամանակը
card-stats-total-time = Ընդհանուր ժամանակը
card-stats-new-card-position = Հերթ
card-stats-card-template = Քարտի տեսակ
card-stats-note-type = Գրառման տեսակ
card-stats-deck-name = Կապուկ
card-stats-note-id = Գրառման ID
card-stats-card-id = Քարտի ID
card-stats-review-log-rating = Գնահատական
card-stats-review-log-type = Տեսակ
card-stats-review-log-date = Ամսաթիվ
card-stats-review-log-time-taken = Ժամ
card-stats-review-log-type-learn = Սովորելու ժամանակը
card-stats-review-log-type-review = Կրկնություն
card-stats-review-log-type-relearn = Վերասովորվողները
card-stats-review-log-type-filtered = Զտված
card-stats-review-log-type-rescheduled = Տեղափոխել
