custom-study-all-cards-in-random-order-dont = Բոլոր քարտերը պատահական հերթականությամբ (չվերահերթագրել)
custom-study-all-review-cards-in-random-order = Բոլոր կրկնվող քարտերը պատահական հերթականությամբ
custom-study-cards = քարտ
custom-study-cards-from-the-deck = քարտ կապուկից
custom-study-choose-tags = Ընտրել պիտակները
custom-study-custom-study-session = Ուսուցման լրացուցիչ աշխատաշրջան
custom-study-due-cards-only = Միայն կրկնելիք քարտերը
custom-study-increase-todays-new-card-limit = Բարձրացնել նոր քարտերի սահմանափակման այսօրվա շեմը
custom-study-increase-todays-new-card-limit-by = Բարձրացնել նոր քարտերի սահմանափակման այսօրվա շեմը այսքանով՝
custom-study-increase-todays-review-card-limit = Բարձրացնել կրկնվող քարտերի սահմանափակման այսօրվա շեմը
custom-study-increase-todays-review-limit-by = Բարձրացնել կրկնվող քարտերի սահմանափակման այսօրվա շեմը այսքանով՝
custom-study-new-cards-in-deck-over-today = Սահմանափակման այսօրվա շեմը գերազանցող կապուկի նոր քարտերը՝ { $val }
custom-study-new-cards-only = Միայն նոր քարտերը
custom-study-no-cards-matched-the-criteria-you = Նշված չափանիշներին համապատասխանող քարտեր չկան:
custom-study-ok = ԼԱՎ
custom-study-preview-new-cards = Նոր քարտերի նախատեսք
custom-study-preview-new-cards-added-in-the = Անցյալում ավելացված նոր քարտերի նախատեսք
custom-study-require-one-or-more-of-these = Հարկավոր են այս պիտակներից մեկը կամ մի քանիսը՝
custom-study-review-ahead = Առաջ կրկնել (օրական սահմանափակումից դուրս)
custom-study-review-ahead-by = Այսքանով առաջ կրկնել՝
custom-study-review-cards-forgotten-in-last = Անցյալում մոռացված քարտերը կրկնել
custom-study-review-forgotten-cards = Կրկնել մոռացված քարտերը
custom-study-reviews-due-in-deck-over-today = Կապուկի սահմանափակման այսօրվա շեմը գերազանցող կրկնելիք՝ { $val }
custom-study-select = Ընտրել
custom-study-select-tags-to-exclude = Ընտրեք բացառվելիք պիտակները՝
custom-study-selective-study = Ընտրողական ուսուցում
custom-study-study-by-card-state-or-tag = Սովորել ըստ քարտի կարգավիճակի կամ պիտակի
