notetypes-front-field = Հարց
notetypes-back-field = Պատասխան
notetypes-add-reverse-field = Ավելացնել հետադարձում
notetypes-text-field = Գրվածք
notetypes-basic-name = Հիմնական
notetypes-basic-reversed-name = Հիմնական (+ հետադարձ քարտերը)
notetypes-basic-optional-reversed-name = Հիմնական (հետադարձը ըստ ընտրության)
notetypes-cloze-name = Բացթողումներ
notetypes-basic-type-answer-name = Հիմնական (մուտքագրեք պատասխանը)
notetypes-card-2-name = Քարտ 2
notetypes-card-1-name = Քարտ 1
notetypes-add = Ավելացնել՝ { $val }
notetypes-add-note-type = Ավելացնել գրառման տեսակ
notetypes-cards = Քարտեր...
notetypes-clone = Կրկնօրինակել՝ { $val }
notetypes-copy = { $val } պատճեն
notetypes-create-scalable-images-with-dvisvgm = Ստեղծել սանդղելի պատկերներ dvisvgm-ով
notetypes-delete-this-note-type-and-all = Ջնջե՞լ գրառման այս տեսակը և նրա բոլոր քարտերը:
notetypes-delete-this-unused-note-type = Ջնջե՞լ գրառման այս չօգտագործվող տեսակը:
notetypes-fields = Դաշտեր...
notetypes-footer = Ներքևի տող
notetypes-header = Գլխագիր
notetypes-note-types = Գրառման տեսակներ
notetypes-options = Ընտրանքներ...
notetypes-please-add-another-note-type-first = Սկզբում ավելացրեք գրառման այլ տեսակ:
notetypes-type = Տեսակ
