custom-study-cards = карти
custom-study-cards-from-the-deck = карти от тестето
custom-study-choose-tags = Избор на етикети
custom-study-custom-study-session = Учене извън програмата
custom-study-due-cards-only = O
custom-study-increase-todays-new-card-limit = Увеличаване на днешния лимит за нови карти
custom-study-increase-todays-new-card-limit-by = Увеличаване на днешния лимит за нови карти с
custom-study-increase-todays-review-card-limit = Увеличаване на днешния лимит за карти за преговор
custom-study-increase-todays-review-limit-by = Увеличаване на днешния лимит за карти за преговор с
custom-study-new-cards-only = Само нови карти
custom-study-no-cards-matched-the-criteria-you = Нямаше карти, отговарящи на условията.
custom-study-ok = ОК
custom-study-preview-new-cards = Предварителен преглед на новите карти
custom-study-preview-new-cards-added-in-the = Преглед на новите карти, добавени през последните
custom-study-require-one-or-more-of-these = Включване на един или повече етикети сред тези:
custom-study-review-ahead = Преглеждане на бъдещи карти
custom-study-review-ahead-by = Преглеждане на бъдещи карти с
custom-study-review-cards-forgotten-in-last = Преговор на забравените карти през последните
custom-study-review-forgotten-cards = Преговор на забравени карти
custom-study-select = Избиране
custom-study-select-tags-to-exclude = Избор на етикети за изключване:
custom-study-selective-study = Избирателно учене
custom-study-study-by-card-state-or-tag = Учене според състоянието или етикетите на картите
