editing-add-media = Добавяне на медийни файлове
editing-an-error-occurred-while-opening = Възникна грешка при отварянето на { $val }
editing-cards = Карти
editing-cut = Изрязване
editing-edit-current = Редактиране на текущата
editing-edit-html = Редактиране на HTML
editing-fields = Полета
editing-html-editor = HTML редактор
editing-jump-to-tags-with-ctrlandshiftandt = Прескачане към етикетите с Ctrl+Shift+T
editing-latex-equation = LaTeX уравнение
editing-media = Медийни файлове
editing-paste = Поставяне
editing-show-duplicates = Показване на повторенията
editing-tags = Етикети
