fields-add-field = Добавяне на поле
fields-delete-field-from = Изтриване на поле от { $val }?
fields-editing-font = Промяна на шрифта:
fields-field = Поле:
fields-field-name = Име на полето:
fields-fields-for = Полета за { $val }
fields-font = Шрифт:
fields-new-position-1 = Нова позиция (1...{ $val }):
fields-notes-require-at-least-one-field = Бележките изискват поне едно поле
fields-remember-last-input-when-adding = Запомняне на последния текст при добавяне
fields-reverse-text-direction-rtl = Обърната посока на текста (RTL, отдясно наляво)
fields-size = Размер:
fields-sort-by-this-field-in-the = Сортиране по това поле в браузъра
fields-that-field-name-is-already-used = Това име на поле е вече използвано.
