notetypes-front-field = Лицева част
notetypes-back-field = Гръб
notetypes-add-reverse-field = Добавяне на обратната карта
notetypes-text-field = Текст
notetypes-basic-name = Основен
notetypes-basic-reversed-name = Основна (и обърната карта)
notetypes-basic-optional-reversed-name = Основна (+ обърната карта по избор)
notetypes-card-2-name = Карта 1
notetypes-card-1-name = Карта 1
notetypes-add = Добавяне: { $val }
notetypes-add-note-type = Добавяне на тип на бележка
notetypes-cards = Карти
notetypes-clone = Клониране: { $val }
notetypes-copy = { $val } копиране
notetypes-delete-this-note-type-and-all = Изтриване на този тип бележки и всичките карти в него?
notetypes-delete-this-unused-note-type = Изтриване на този неизползван тип бележки?
notetypes-fields = Полета
notetypes-header = Заглавна част
notetypes-note-types = Типове бележки
notetypes-options = Опции...
notetypes-please-add-another-note-type-first = Моля, първо добавете друг тип бележка.
