preferences-automatically-sync-on-profile-openclose = Автоматична синхронизаци при отваряне/затваряне на профила
preferences-backups = Резервни копия
preferences-backups2 = резервни копия
preferences-backupsanki-will-create-a-backup-of = <b>Резервни копия</b><br> създават се всеки път, когато затворите или синхронизирате Anki.
preferences-basic = Основен
preferences-change-deck-depending-on-note-type = Промяна на тестето в зависимост от типа на бележката.
preferences-hours-past-midnight = часа след полунощ
preferences-interface-language = Език на програмата:
preferences-keep = Запазване на
preferences-learn-ahead-limit = Ограничение на ученето напред
preferences-mins = мин.
preferences-network = Мрежа
preferences-next-day-starts-at = Следващият ден започва
preferences-note-media-is-not-backed-up = Внимание: медийните файлове нямат резервни копия. Създавайте периодично резерни копия на директорията на Anki за по-сигурно.
preferences-on-next-sync-force-changes-in = Еднопосочно качване на промените при следващо синхронизиране.
preferences-paste-clipboard-images-as-png = Поставяна на изображения от клипборда като PNG.
preferences-please-restart-anki-to-complete-language = Рестартирайте Anki за завършване на избора на език.
preferences-preferences = Предпочитания
preferences-show-next-review-time-above-answer = Показване на следващото време за преговор над бутоните за отговор
preferences-show-remaining-card-count-during-review = Показване на броя оставащи карти по време на преглед
preferences-some-settings-will-take-effect-after = Някои настройки ще влязат в сила след рестартиране на Anki
preferences-synchronisation = <b>Синхронизиране</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Синхронизиране</b><br>
preferences-synchronize-audio-and-images-too = Синхронизиране също и на аудио файловете и изображенията
preferences-when-adding-default-to-current-deck = При добавяне, по подразбиране на се използва текущото тесте.
