sync-media-check-required = Възникна проблем при синхронизирането на медийните файлове. Използвайте Инструменти->Проверка на медийните файлове, след това синхронизирайте отново за поправяне на проблема.
sync-wrong-pass = AnkiWeb ID или паролата са грешни; моля, опитайте отново.
sync-download-from-ankiweb = Изтегляне от AnkiWeb
sync-upload-to-ankiweb = Качване в AnkiWeb
sync-cancel-button = Отказ
sync-downloading-from-ankiweb = Изтегля се от AnkiWeb...
sync-uploading-to-ankiweb = Качване в AnkiWeb...
sync-syncing = Синхронизиране...
sync-checking = Проверява се...
sync-password-label = Парола:
sync-account-required =
    <h1>Необходим е профил</h1>
    За синхронизиране на колекциите е необходим безплатен профил. Моля <a href="{ $link }">регистрирайте се</a> и  въведете данните си по-долу след това.
sync-connecting = Свързване...
