adding-add-shortcut-ctrlandenter = 追加（ショートカット: ctrl+enter）
adding-added = 追加しました
adding-discard-current-input = 現在の編集を破棄しますか？
adding-keep-editing = 編集を続ける
adding-edit = 「{ $val }」を編集
adding-history = 履歴
adding-note-deleted = (ノートを削除しました)
adding-shortcut = ショートカット: { $val }
adding-the-first-field-is-empty = 最初のフィールドが空欄です。
adding-you-have-a-cloze-deletion-note = 穴埋め問題用のノートタイプを使用していますが、穴埋め問題用の範囲がまだ指定されていません。このままの状態でカードを追加してもよろしいですか？
adding-cloze-outside-cloze-notetype = 穴埋め問題機能は穴埋め問題用のノートタイプでのみ使用できます。
adding-cloze-outside-cloze-field = 穴埋め問題機能は「cloze:」（穴埋め問題）フィルターを使用しているフィールドでのみ使用できます。多くの場合、最初のフィールドがそれに該当します。
