editing-actual-size = 実寸表示[エディタの幅が上限] / コンパクト表示  の切り替え
editing-add-media = メディアを追加
editing-align-left = 左寄り
editing-align-right = 右寄り
editing-an-error-occurred-while-opening = { $val } を開いた時にエラーが発生しました。
editing-attach-picturesaudiovideo = メディア(画像/音声/動画)を追加
editing-bold-text = 太字
editing-cards = カード
editing-center = 中央
editing-change-color = 色を変更
editing-cloze-deletion = 穴埋め問題
editing-cloze-deletion-repeat = 穴埋め問題 (同じカード )
editing-copy-image = 画像をコピー
editing-couldnt-record-audio-have-you-installed = 音声を録音できませんでした。LAMEをインストールしていますか？
editing-customize-card-templates = カードテンプレートをカスタマイズ
editing-customize-fields = フィールドをカスタマイズ
editing-cut = カット
editing-double-click-image = 画像をダブルクリック
editing-double-click-to-expand = ダブルクリックで実寸表示
editing-double-click-to-collapse = ダブルクリックで折りたたむ
editing-edit-current = 現在のノートを編集
editing-edit-html = HTML を編集
editing-fields = フィールド
editing-float-left = 左寄せ配置（後に続く内容は右側に回り込ませる）
editing-float-right = 右寄せ配置（後に続く内容は左側に回り込ませる）
editing-float-none = 左右への配置指定なし（後に続く内容の回り込みもなし）
editing-indent = インデントを増やす
editing-italic-text = イタリック
editing-jump-to-tags-with-ctrlandshiftandt = Ctrl+Shift+T でタグフィールドに移動します。
editing-justify = 両端揃え
editing-latex = LaTeX
editing-latex-equation = LaTeX インライン数式
editing-latex-math-env = LaTeX ディスプレイ数式
editing-mathjax-block = MathJax ブロック数式
editing-mathjax-chemistry = MathJax 化学式
editing-mathjax-inline = MathJax インライン数式
editing-mathjax-placeholder = 受け入れる場合は { $accept } を、改行する場合は { $newline } を押してください。
editing-media = メディア
editing-open-image = 画像を開く
editing-show-in-folder = フォルダに表示
editing-ordered-list = リスト（順序あり）
editing-outdent = インデントを減らす
editing-paste = 貼り付け
editing-record-audio = 音声を録音
editing-remove-formatting = 書式を取り除く
editing-restore-original-size = 元のサイズにリセット
editing-select-remove-formatting = 削除する書式を選択
editing-show-duplicates = 重複しているカード/ノートをテーブルに表示
editing-subscript = 下付き文字
editing-superscript = 上付き文字
editing-tags = タグ
editing-tags-add = タグを追加
editing-tags-copy = タグをコピー
editing-tags-remove = タグをはずす
editing-tags-select-all = すべてのタグを選択
editing-text-color = 文字色
editing-text-highlight-color = 文字の背景色
editing-to-make-a-cloze-deletion-on = このノートに穴埋め問題を作るには、まず今のノートタイプを穴埋め問題用のノートタイプに変更する必要があります。[ノート] > [ノートタイプを変更] から、穴埋め問題用のノートタイプを選択してください。
editing-toggle-html-editor = HTMLエディタを表示
editing-toggle-visual-editor = ビジュアルエディタを表示/非表示
editing-toggle-sticky = この内容を固定
editing-expand = 展開
editing-collapse = 折りたたむ
editing-expand-field = フィールドを展開
editing-collapse-field = フィールドを折りたたむ
editing-underline-text = 下線を追加
editing-unordered-list = リスト（順序なし）
editing-warning-cloze-deletions-will-not-work = 注意: 穴埋め問題は上部にある「ノートタイプ」の設定を「穴埋め問題」タイプに変更するまで機能しません。
editing-mathjax-preview = MathJaxによる数式をプレビュー
editing-shrink-images = 画像をコンパクトなサイズで表示
editing-close-html-tags = HTMLの終了タグを自動で付ける
editing-from-clipboard = クリップボードから
editing-alignment = 配置
editing-equations = 数式
editing-no-image-found-on-clipboard = クリップボードに画像が見つかりません。
editing-image-occlusion-mode = 作成するカードの種類を選択
editing-image-occlusion-zoom-out = 縮小
editing-image-occlusion-zoom-in = 拡大
editing-image-occlusion-zoom-reset = 拡大縮小をリセット
editing-image-occlusion-toggle-translucent = マスク半透明表示の切り替え
editing-image-occlusion-delete = 削除
editing-image-occlusion-duplicate = 複製
editing-image-occlusion-group = 選択対象をグループ化
editing-image-occlusion-ungroup = 選択対象のグループ化を解除
editing-image-occlusion-select-all = すべて選択
editing-image-occlusion-alignment = 選択対象を整列
editing-image-occlusion-align-left = 左揃え
editing-image-occlusion-align-h-center = 左右方向の中央揃え
editing-image-occlusion-align-right = 右揃え
editing-image-occlusion-align-top = 上揃え
editing-image-occlusion-align-v-center = 上下方向の中央揃え
editing-image-occlusion-align-bottom = 下揃え
editing-image-occlusion-select-tool = 選択
editing-image-occlusion-zoom-tool = 画像表示のサイズ・位置の調整
editing-image-occlusion-rectangle-tool = 矩形マスク
editing-image-occlusion-ellipse-tool = 楕円形マスク
editing-image-occlusion-polygon-tool = 多角形マスク
editing-image-occlusion-text-tool = 文字
editing-image-occlusion-fill-tool = 選択した色でマスクを塗りつぶし
editing-image-occlusion-toggle-mask-editor = マスクエディタを表示
editing-image-occlusion-reset = この画像穴埋め問題をリセット
editing-image-occlusion-confirm-reset = 画像を選択する前の初期状態（画像選択用の画面）にリセットします。現在の画像上に追加したマスクや文字だけでなく、その画像自体を表示しなくなります。本当によろしいですか？

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTMLエディタ
