empty-cards-for-note-type = { $notetype } の白紙カード：
empty-cards-count-line = { $existing_count }枚中{ $empty_count }枚のカードが白紙（{ $template_names }）
empty-cards-window-title = 白紙カード
empty-cards-preserve-notes-checkbox = 有効なカードのないノートを保持する
empty-cards-delete-button = 削除
empty-cards-not-found = 白紙カードはありません。
empty-cards-deleted-count = { $cards }枚のカードを削除しました。
empty-cards-delete-empty-cards = 白紙カードを削除
empty-cards-delete-empty-notes = 白紙ノートを削除
empty-cards-deleting = 削除中...
