profiles-anki-could-not-read-your-profile = プロファイルデータを読み込むことができません。ウィンドウサイズと同期のためのログイン詳細が除去されています。
profiles-anki-could-not-rename-your-profile = プロファイルの名前を変更できませんでした。ディスク上のプロファイルフォルダの名前が変更できないためです。Documents/Anki フォルダへの書き込み権限を設定していて、他のプログラムからプロファイルフォルダへアクセスしていないことを確認してから、もう一度実行してください。
profiles-folder-already-exists = 使用済みのフォルダー名です。
profiles-open = 開く
profiles-open-backup = バックアップを開く...
profiles-please-remove-the-folder-and = フォルダー { $val } を削除してから、もう一度実行してください。
profiles-profile-corrupt = プロファイルの破損
profiles-profiles = プロファイル
profiles-quit = 終了
profiles-user-1 = ユーザー 1
profiles-confirm-lang-choice = Ankiのインターフェイスを{ $lang }で表示します。本当によろしいですか？
profiles-could-not-create-data-folder = データフォルダを作成することができませんでした。マニュアルの「ファイルの場所」の項目に目を通し、その場所が読み取り専用になっていないか確認してください。
profiles-prefs-corrupt-title = 設定の破損
profiles-prefs-file-is-corrupt = Ankiのprefs21.dbファイルが破損していたため再作成しました。複数のプロファイルをお持ちだった場合は、同じ名前を使用してそれらを再び追加しカードを復旧してください。
profiles-profile-does-not-exist = 要求されたプロファイルは存在しません。
profiles-creating-backup = バックアップを作成中…
profiles-backup-created = バックアップを作成しました。
profiles-backup-creation-failed = バックアップの作成に失敗しました: { $reason }
profiles-backup-unchanged = 直近のバックアップから変更がありません。
