decks-add-new-deck-ctrlandn = Tilføj nyt kortsæt (Ctrl+N)
decks-build = Byg
decks-cards-selected-by = kort udvalgt af
decks-create-deck = Opret kortsæt
decks-custom-steps-in-minutes = Brugertilpasset trin (i minutter)
decks-deck = Kortsæt
decks-decreasing-intervals = Aftagende intervaller
decks-delete-deck = Slet kortsæt
decks-enable-second-filter = Aktivér sekundært filter
decks-filter = Filter:
decks-filter-2 = Filter 2
decks-get-shared = Hent delte
decks-import-file = Importer fil
decks-increasing-intervals = Intervallerne øges
decks-latest-added-first = Seneste tilføjes først
decks-limit-to = Begræns til
decks-minutes = minutter
decks-most-lapses = Flest omgange
decks-new-deck-name = Nyt kortsætnavn:
decks-no-deck = [intet kortsæt]
decks-oldest-seen-first = Ældste set først
decks-order-added = Tilføjede rækkefølge
decks-order-due = Fristorden
decks-please-select-something = Vælg venligst et eller andet.
decks-random = Tilfældig
decks-relative-overdueness = Relativ overskridelse
decks-repeat-failed-cards-after = Repertér fejlsvarede kort efter
decks-reschedule-cards-based-on-my-answers = Planlæg kort påny baseret på mine svar i denne kortsæt
decks-study = Studér
decks-study-deck = Studér kortsæt
decks-filtered-deck-search-empty = Ingen kort matchede søgningen. Nogle kort kan eventuelt blevet exkluderet, fordi de hører til en anden filtrerer kortbunke, eller suspenderet.
decks-unmovable-cards = Vis exkluderede kort
decks-review-header = I dag
decks-learn-header = Lær
