profiles-anki-could-not-read-your-profile = Anki kunne ikke læse din profildata. Vinduesstørrelser og dine detailjer til synkroniserings-login er evt. blevet glemt.
profiles-anki-could-not-rename-your-profile = Anki kunne ikke omdøbe din profil, fordi den ikke kunne omdøbe profilmappen på disken. Sørg venligst for at du har rettigheder til at skrive til Dokumenter/Anki, samt at andre programmer ikke tilgår dine profilmapper - forsøg dernæst igen.
profiles-folder-already-exists = Mappe findes allerede.
profiles-open = Åbn
profiles-open-backup = Åbn Backup...
profiles-please-remove-the-folder-and = Fjern venligst mappen { $val } og forsøg igen.
profiles-profile-corrupt = Korrupt profil
profiles-profiles = Profiler
profiles-quit = Afslut
profiles-user-1 = Bruger 1
profiles-confirm-lang-choice = Er du sikker på at vise Anki's interface på { $lang }?
profiles-could-not-create-data-folder = Anki kunne ikke danne data-mappen. Vær venlig og kig i File Location-sektionen i manualen, og sikr, at placeringen ikke er kun til forlæsning.
profiles-prefs-corrupt-title = Korrupte indstillinger
profiles-prefs-file-is-corrupt = Anki's prefs21.db-fil var korrupt og er blevet genskabt. Hvis du brugte flere probiler, vær venlig og tilføj dem igen vved at bruge de samme navne, for at genskabe dine kort.
profiles-profile-does-not-exist = Den ønskede profil eksisterer ikke.
profiles-creating-backup = Danner Backup...
profiles-backup-created = Backup lavet.
profiles-backup-creation-failed = Backup mislykkedes: { $reason }
profiles-backup-unchanged = Ingen ændringer siden sidste backup.
