decks-add-new-deck-ctrlandn = Thêm Bộ thẻ Mới (Ctrl+N)
decks-build = Tạo
decks-cards-selected-by = thẻ được chọn theo
decks-create-deck = Tạo Bộ thẻ
decks_create_even_if_empty = Tạo/cập nhật bộ thẻ này ngay cả khi trống
decks-custom-steps-in-minutes = Bước tùy chỉnh (phút)
decks-deck = Bộ thẻ
decks-decreasing-intervals = Khoảng cách giảm dần
decks-delete-deck = Xóa Bộ thẻ
decks-enable-second-filter = Bật bộ lọc thứ hai
decks-filter = Lọc:
decks-filter-2 = Lọc 2
decks-get-shared = Lấy Bộ thẻ Chia sẻ
decks-import-file = Nhập Tập tin
decks-increasing-intervals = Khoảng cách tăng dần
decks-latest-added-first = Thẻ thêm mới nhất trước
decks-limit-to = Giới hạn trong
decks-minutes = phút
decks-most-lapses = Nhiều lần hỏng nhất
decks-new-deck-name = Tên bộ thẻ mới:
decks-no-deck = [không có bộ thẻ]
decks-oldest-seen-first = Thẻ lâu nhất trước
decks-order-added = Thứ tự thêm vào
decks-order-due = Thứ tự đến hạn
decks-please-select-something = Xin vui lòng chọn một cái gì đó.
decks-random = Ngẫu nhiên
decks-relative-overdueness = Tình trạng đến hạn liên quan
decks-repeat-failed-cards-after = Lặp lại các thẻ thất bại sau
# e.g. "Delay for Again", "Delay for Hard", "Delay for Good"
decks-delay-for-button = Trì hoãn cho { $button }
decks-reschedule-cards-based-on-my-answers = Lập lịch lại thẻ các dựa trên cách tôi trả lời ở bộ thẻ này
decks-study = Học tập
decks-study-deck = Học Bộ thẻ
decks-filtered-deck-search-empty = Không có thẻ nào phù hợp với nội dung được cung cấp. Một số thẻ có thể đã bị loại trừ vì chúng nằm trong một bộ thẻ đã lọc khác hoặc đã bị ngừng.
decks-unmovable-cards = Hiển thị bất kỳ thẻ nào bị loại trừ
decks-learn-header = Học
# The count of cards waiting to be reviewed
decks-review-header = Đến hạn
decks-zero-minutes-hint = (0 = trả thẻ về bộ thẻ gốc)
