qt-accel-about = &O
qt-accel-about-mac = O Anki...
qt-accel-cards = &Kartice
qt-accel-check-database = &Provjeri bazu podataka
qt-accel-check-media = Provjeri &Medije
qt-accel-edit = &Uredi
qt-accel-exit = I&zlaz
qt-accel-export = &Izvoz…
qt-accel-export-notes = &Izvoz bilješki...
qt-accel-file = &Datoteka
qt-accel-filter = Fil&ter
qt-accel-find = &Traži
qt-accel-find-and-replace = &Pronađi i zamijeni...
qt-accel-find-duplicates = Pronađi &duplikate...
qt-accel-go = &Idi
qt-accel-guide = &Vodič...
qt-accel-help = &Pomoć
qt-accel-import = &Uvoz…
qt-accel-info = &Informacije...
qt-accel-invert-selection = Obrn&i odabir
qt-accel-next-card = Sljedeća kartica...
qt-accel-note = &Bilješka
qt-accel-notes = &Bilješke
qt-accel-preferences = &Postavke...
qt-accel-previous-card = &Prethodna kartica
qt-accel-select-all = Od&aberi sve
qt-accel-select-notes = Odaberi &bilješke
qt-accel-support-anki = &Podrži Anki...
qt-accel-switch-profile = &Promijeni profil
qt-accel-tools = &Alati
qt-accel-undo = &Poništi
qt-accel-redo = &Ponovi
qt-accel-forget = &Resetiraj
qt-accel-view = &Pogled
qt-accel-full-screen = Prebaci na &cijeli zaslon
qt-accel-layout = &Izgled
qt-accel-layout-auto = &Auto
qt-accel-layout-vertical = &Vertikalno
qt-accel-layout-horizontal = &Horizontalno
qt-accel-zoom-in = Zumiraj &unutra
qt-accel-zoom-out = Zumiraj &van
qt-accel-reset-zoom = &Poništi zumiranje
qt-accel-toggle-sidebar = Uključi/isključi bočnu traku
qt-accel-zoom-editor-in = Uvećaj &uređivač
qt-accel-zoom-editor-out = Smanji &uređivač
qt-accel-create-backup = Napravi &sigurnosnu kopiju
qt-accel-load-backup = &Vrati na sigurnosnu kopiju
qt-accel-upgrade-downgrade = Nadogradnja/smanjivanje
