qt-misc-all-cards-notes-and-media-for = Alle kaarten, aantekeningen en media voor dit profiel zullen worden verwijderd. Weet u het zeker?
qt-misc-anki-updatedanki-has-been-released = <h1>Update Anki</h1>Anki { $val } is beschikbaar.<br><br>
qt-misc-automatic-syncing-and-backups-have-been = Automatische synchronisatie en back-ups zijn uitgeschakeld tijdens het herstellen. Om ze weer in te schakelen, sluit het profiel of start Anki opnieuw.
qt-misc-backing-up = Aanmaak van back-up...
qt-misc-browse = Bladeren
qt-misc-change-note-type-ctrlandn = Aantekeningstype veranderen (Ctrl+N)
qt-misc-check-the-files-in-the-media = Bestanden in de media-map controleren
qt-misc-choose-deck = Set selecteren
qt-misc-choose-note-type = Aantekeningstype selecteren
qt-misc-closing = Sluitend...
qt-misc-configure-interface-language-and-options = Interfacetaal en -instellingen configureren
qt-misc-copy-to-clipboard = Kopiëren naar het klembord
qt-misc-create-filtered-deck = Gefilterde set aanmaken...
qt-misc-debug-console = Debug console
qt-misc-deck-will-be-imported-when-a = Set zal geïmporteerd worden zodra een profiel wordt geopend.
qt-misc-default = Standaard
qt-misc-empty-cards = Lege kaarten...
qt-misc-error-during-startup = Fout tijdens opstarten: { $val }
qt-misc-filtered-deck = Gefilterde set { $val }
qt-misc-ignore-this-update = Deze update negeren
qt-misc-in-order-to-ensure-your-collection = Om ervoor te zorgen dat uw collectie correct werkt wanneer u ze verplaatst naar een ander toestel vereist Anki dat de interne klok van uw computer correct ingesteld is. Ook als uw systeem de correcte lokale tijd weergeeft kan de interne klok fout ingesteld zijn.  Ga naar de tijdsinstellingen van uw computer en controleer het volgende:  - AM/PM - Klokdrift - Dag, maand en jaar - Tijdszone - Zomer-/wintertijd  Afwijking ten opzichte van correcte tijd: { $val }.
qt-misc-invalid-property-found-on-card-please = Kaart heeft ongeldige eigenschap. Gebruik Hulpmiddelen>Database controleren. Indien het probleem zich opnieuw voordoet, contacteer de supportwebsite.
qt-misc-loading = Bezig met laden…
qt-misc-manage = Beheren
qt-misc-manage-note-types = Aantekeningstype beheren
qt-misc-name-exists = Naam bestaat.
qt-misc-non-unicode-text = <niet-unicode tekst>
qt-misc-optimizing = Bezig met optimaliseren...
qt-misc-please-connect-a-microphone-and-ensure = Gelieve een microfoon aan te sluiten, en ervoor te zorgen dat geen andere programma's gebruikmaken van het geluidsapparaat.
qt-misc-please-ensure-a-profile-is-open = Controleer dat een profiel is geopend en dat Anki niet bezig is, en probeer opnieuw.
qt-misc-please-select-1-card = (kies 1 kaart)
qt-misc-please-select-a-deck = Gelieve een set te selecteren.
qt-misc-please-use-fileimport-to-import-this = Gelieve Bestand->Importeren te gebruiken om dit bestand te importeren.
qt-misc-processing = Bezig met verwerken...
qt-misc-replace-your-collection-with-an-earlier = Uw verzameling door een eerdere back-up vervangen?
qt-misc-resume-now = Nu hervatten
qt-misc-revert-to-backup = Naar back-up terugzetten
qt-misc-reverted-to-state-prior-to = Herzet naar de staat vóór '{ $val }'.
qt-misc-shift-key-was-held-down-skipping = De shift-toets was ingedrukt. Automatisch synchroniseren en laden van add-ons wordt overgeslagen.
qt-misc-shortcut-key-left-arrow = Sneltoets: Linkerpijl
qt-misc-shortcut-key-right-arrow-or-enter = Sneltoets: Rechterpijl of Enter
qt-misc-stats = Statistieken
qt-misc-study-deck = Kaarten in set studeren...
qt-misc-sync = Synchroniseren
qt-misc-target-deck-ctrlandd = Doelset (Ctrl+D)
qt-misc-the-following-character-can-not-be = Het volgende karakter mag niet gebruikt worden: { $val }
qt-misc-the-requested-change-will-require-a = Voor deze verandering is het nodig om bij de volgende synchronisatie de hele database op te laden. Als er op een ander apparaat nog herhalingen of andere veranderingen zijn die nog niet gesynchroniseerd zijn, dan zullen deze verloren gaan. Doorgaan?
qt-misc-there-must-be-at-least-one = Er moet minstens één profiel bestaan.
qt-misc-this-file-exists-are-you-sure = Dit bestand bestaat. Bent u zeker dat u het wil overschrijven?
qt-misc-unable-to-access-anki-media-folder = Geen toegang tot de mediamap van Anki. De toegangsrechten tot de tijdelijke map van uw systeem zijn mogelijk onjuist.
qt-misc-unable-to-move-existing-file-to = Het bestaande bestand kon niet naar de prullenbak verplaatst worden - probeer uw computer opnieuw op te starten.
qt-misc-undo = Ongedaan maken
qt-misc-undo2 = { $val } ongedaan maken
qt-misc-unexpected-response-code = Onverwachte reactie code: { $val }
qt-misc-waiting-for-editing-to-finish = Aan het wachten tot u klaar bent met bewerken.
qt-misc-would-you-like-to-download-it = Wilt u het nu downloaden?
qt-misc-your-collection-file-appears-to-be = Uw verzamelingsbestand lijkt beschadigd te zijn. Dit kan gebeuren wanneer het bestand gekopieerd of verplaatst wordt terwijl Anki open is, of wanneer de verzameling opgeslagen is op een netwerk- of cloudstation. Als het probleem zich blijft voordoen nadat u uw computer opnieuw hebt opgestart, open een automatische back-up via het profielscherm.
qt-misc-your-computers-storage-may-be-full = De opslagruimte van uw computer is mogelijk vol. Verwijder enkele overbodige bestanden en probeer opnieuw.
qt-misc-your-firewall-or-antivirus-program-is = Uw firewall of antivirusprogramma verhindert dat Anki verbinding maakt met zichzelf. Gelieve een uitzondering te maken voor Anki.
qt-misc-second = { $count ->
    [one] { $count } seconde
   *[other] { $count } seconden
  }
