editing-actual-size = Activa/desactiva la mida real
editing-add-media = Afegeix fitxers multimèdia
editing-align-left = Alinea a l'esquerra
editing-align-right = Alinea a la dreta
editing-an-error-occurred-while-opening = No s’ha pogut obrir { $val }
editing-attach-picturesaudiovideo = Afegeix imatges, so o vídeo
editing-bold-text = Text en negreta
editing-cards = Targetes
editing-center = Centrar
editing-change-color = Canvia el color
editing-cloze-deletion = Text amb buits (nova targeta)
editing-cloze-deletion-repeat = Text amb buits (mateixa targeta)
editing-copy-image = Copia la imatge
editing-couldnt-record-audio-have-you-installed = No s'ha pogut enregistrar el so. Heu instal·lat «lame»?
editing-customize-card-templates = Personalitza les plantilles de targeta
editing-customize-fields = Personalitza els camps
editing-cut = Talla
editing-double-click-image = feu doble clic en la imatge
editing-double-click-to-expand = (feu doble clic per a expandir)
editing-double-click-to-collapse = feu doble clic per a reduir
editing-edit-current = Edita l'actual
editing-edit-html = Edita l'HTML
editing-fields = Camps
editing-float-left = Flotant a l'esquerra
editing-float-right = Flotant a la dreta
editing-float-none = No flotant
editing-indent = Augmenta el sagnat
editing-italic-text = Text en cursiva
editing-jump-to-tags-with-ctrlandshiftandt = Salta a les etiquetes amb Ctrl+Shift+T
editing-justify = Justifica
editing-latex = LaTeX
editing-latex-equation = Equació LaTeX
editing-latex-math-env = Entorn matemàtic LaTeX
editing-mathjax-block = Bloc de MathJax
editing-mathjax-chemistry = Química MathJax
editing-mathjax-inline = MathJax en línia
editing-mathjax-placeholder = Premeu { $accept } per a acceptar i { $newline } per a afegir una nova línia.
editing-media = Multimèdia
editing-open-image = Obre la imatge
editing-show-in-folder = Mostra a la carpeta
editing-ordered-list = Llista ordenada
editing-outdent = Redueix el sagnat
editing-paste = Enganxa
editing-record-audio = Enregistra un so
editing-remove-formatting = Suprimeix el format
editing-restore-original-size = Restaura la mida original
editing-select-remove-formatting = Seleccioneu el format que voleu suprimir
editing-show-duplicates = Mostra'n els duplicats
editing-subscript = Subíndexs
editing-superscript = Superíndexs
editing-tags = Etiquetes
editing-tags-add = Afegeix una etiqueta
editing-tags-copy = Copia les etiquetes
editing-tags-remove = Suprimeix les etiquetes
editing-tags-select-all = Selecciona totes les etiquetes
editing-text-color = Color del text
editing-text-highlight-color = Color de ressaltat del text
editing-to-make-a-cloze-deletion-on = Si voleu crear buits en una nota existent, primer heu de canviar a un tipus de nota amb buits des del menú «Edita > Canvia el tipus de nota».
editing-toggle-html-editor = Activa/desactiva l’editor HTML
editing-toggle-visual-editor = Activa/desactiva l’editor visual
editing-toggle-sticky = Activa/desactiva l’ancoratge del text
editing-expand = Expandeix
editing-collapse = Redueix
editing-expand-field = Expandeix el camp
editing-collapse-field = Redueix el camp
editing-underline-text = Text subratllat
editing-unordered-list = Llista desordenada
editing-warning-cloze-deletions-will-not-work = Aneu amb compte: els buits no funcionaran fins que canvieu el tipus de nota a «Text amb buits».
editing-mathjax-preview = Previsualitza el MathJax
editing-shrink-images = Redueix les imatges
editing-close-html-tags = Tanca les etiquetes HTML automàticament
editing-from-clipboard = Des del porta-retalls
editing-alignment = Alineació
editing-equations = Equacions
editing-no-image-found-on-clipboard = No s’ha trobat cap imatge en el porta-retalls.
editing-image-occlusion-mode = Mode d’oclusió d’imatges
editing-image-occlusion-zoom-out = Redueix
editing-image-occlusion-zoom-in = Amplia
editing-image-occlusion-zoom-reset = Reestableix el zoom
editing-image-occlusion-toggle-translucent = Activa/desactiva la transparència
editing-image-occlusion-delete = Suprimeix
editing-image-occlusion-duplicate = Duplica
editing-image-occlusion-group = Agrupa la selecció
editing-image-occlusion-ungroup = Desagrupa la selecció
editing-image-occlusion-select-all = Selecciona-ho tot
editing-image-occlusion-alignment = Alineació
editing-image-occlusion-align-left = Alinea a l’esquerra
editing-image-occlusion-align-h-center = Alinea horitzontalment
editing-image-occlusion-align-right = Alinea a la dreta
editing-image-occlusion-align-top = Alinea a la part superior
editing-image-occlusion-align-v-center = Alinea verticalment
editing-image-occlusion-align-bottom = Alinea a la part inferior
editing-image-occlusion-select-tool = Selecciona
editing-image-occlusion-zoom-tool = Zoom
editing-image-occlusion-rectangle-tool = Rectangle
editing-image-occlusion-ellipse-tool = El·lipsi
editing-image-occlusion-polygon-tool = Polígon
editing-image-occlusion-text-tool = Text
editing-image-occlusion-fill-tool = Omple
editing-image-occlusion-toggle-mask-editor = Activa/desactiva l’editor de màscara
editing-image-occlusion-reset = Reinicia l’oclusió d’imatges
editing-image-occlusion-confirm-reset = Segur que voleu reiniciar aquesta oclusió d’imatges?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Editor HTML
