card-stats-added = Adicionado
card-stats-first-review = Primeira Revisão
card-stats-latest-review = Revisão mais recente
card-stats-interval = Intervalo
card-stats-ease = Facilidade
card-stats-review-count = Revisões
card-stats-lapse-count = Erros
card-stats-average-time = Tempo médio
card-stats-total-time = Tempo Total
card-stats-new-card-position = Posição
card-stats-card-template = Tipo do Cartão
card-stats-note-type = Tipo de Nota
card-stats-deck-name = Baralho
card-stats-preset = Predefinição
card-stats-note-id = ID da Nota
card-stats-card-id = ID do Cartão
card-stats-review-log-rating = Classificação
card-stats-review-log-type = Tipo
card-stats-review-log-date = Data
card-stats-review-log-time-taken = Tempo
card-stats-review-log-type-learn = Aprender
card-stats-review-log-type-review = Revisão
card-stats-review-log-type-relearn = Reaprender
card-stats-review-log-type-filtered = Filtrado
card-stats-review-log-type-manual = Manual
card-stats-review-log-type-rescheduled = Reagendado
card-stats-review-log-elapsed-time = Tempo Decorrido
card-stats-no-card = (Nenhum cartão para exibir.)
card-stats-custom-data = Dados Customizados
card-stats-fsrs-stability = Estabilidade
card-stats-fsrs-difficulty = Dificuldade
card-stats-fsrs-retrievability = Recuperabilidade
card-stats-fsrs-forgetting-curve-title = Curva de Esquecimento
card-stats-fsrs-forgetting-curve-first-week = Primeira Semana
card-stats-fsrs-forgetting-curve-first-month = Primeiro mês
card-stats-fsrs-forgetting-curve-first-year = Primeiro Ano
card-stats-fsrs-forgetting-curve-all-time = Todo o Período
card-stats-fsrs-forgetting-curve-probability-of-recalling = Probabilidade de Relembrar
card-stats-fsrs-forgetting-curve-desired-retention = Retenção Desejada

## Window Titles

card-stats-current-card = Cartão Atual ({ $context })
card-stats-previous-card = Cartão Anterior ({ $context })
