editing-actual-size = Alternar tamanho real
editing-add-media = Adicionar Mídia
editing-align-left = Alinhar à esquerda
editing-align-right = Alinhar à direita
editing-an-error-occurred-while-opening = Ocorreu um erro ao abrir { $val }
editing-attach-picturesaudiovideo = Anexar imagens/áudio/vídeo
editing-bold-text = Texto em negrito
editing-cards = Cartões
editing-center = Centro
editing-change-color = Mudar a cor
editing-cloze-deletion = Omissão de palavras (novo cartão)
editing-cloze-deletion-repeat = Omissão de palavras (mesmo cartão)
editing-copy-image = Copiar imagem
editing-couldnt-record-audio-have-you-installed = Não foi possível efetuar a gravação de áudio. Você já tentou instalar o pacote "lame" da sua distribuição?
editing-customize-card-templates = Personalizar Modelos de Cartão
editing-customize-fields = Personalizar Campos
editing-cut = Recortar
editing-double-click-image = clique duas vezes na imagem
editing-double-click-to-expand = (clique duas vezes para expandir)
editing-double-click-to-collapse = Clique duplo para recolher
editing-edit-current = Editar Atual
editing-edit-html = Editar HTML
editing-fields = Campos
editing-float-left = Flutuante à esquerda
editing-float-right = Flutuante à direita
editing-float-none = Não flutuante
editing-indent = Aumentar a identação
editing-italic-text = Texto em itálico
editing-jump-to-tags-with-ctrlandshiftandt = Ir para etiquetas com Ctrl+Shift+T
editing-justify = Justificar
editing-latex = LaTeX
editing-latex-equation = Equação LaTeX
editing-latex-math-env = Matemática LaTeX
editing-mathjax-block = bloco MathJax
editing-mathjax-chemistry = Utilizar formato de entrada MathJax para equações químicas
editing-mathjax-inline = MathJax em linha
editing-mathjax-placeholder = Pressione { $accept } para aceitar, { $newline } para nova linha.
editing-media = Mídia
editing-open-image = Abrir Imagem
editing-show-in-folder = Mostrar na pasta
editing-ordered-list = Lista ordenada
editing-outdent = Diminuir a identação
editing-paste = Colar
editing-record-audio = Gravar áudio
editing-remove-formatting = Remover formatação
editing-restore-original-size = Restaurar o tamanho original
editing-select-remove-formatting = Selecione a formatação para remover
editing-show-duplicates = Mostrar Duplicatas
editing-subscript = Subscrito
editing-superscript = Sobrescrito
editing-tags = Etiquetas
editing-tags-add = Adicionar etiquetas
editing-tags-copy = Copiar etiquetas
editing-tags-remove = Remover etiquetas
editing-tags-select-all = Selecionar todas etiquetas
editing-text-color = Cor do texto
editing-text-highlight-color = Cor de destaque do texto
editing-to-make-a-cloze-deletion-on = Para omitir palavras em uma nota existente, você precisa mudá-la para o tipo Omissão de Palavras primeiro, em 'Editar>Mudar Tipo de Nota'
editing-toggle-html-editor = Editor de HTML
editing-toggle-visual-editor = Editor Visual
editing-toggle-sticky = Fixar/Desafixar
editing-expand = Expandir
editing-collapse = Recolher
editing-expand-field = Expandir campo
editing-collapse-field = Diminuir campo
editing-underline-text = Sublinhar texto
editing-unordered-list = Lista não-ordenada
editing-warning-cloze-deletions-will-not-work = Atenção, omissões de palavras não funcionarão até que você mude o tipo na parte superior para Omissão de Palavras.
editing-mathjax-preview = Visualização do MathJax
editing-shrink-images = Reduzir Imagens
editing-close-html-tags = Fechar automaticamente a tag HTML
editing-from-clipboard = Da Área de Transferência
editing-alignment = Alinhamento
editing-equations = Equações
editing-no-image-found-on-clipboard = Não foi encontrada nenhuma imagem na área de transferência
editing-image-occlusion-mode = Modo de Oclusão de Imagem
editing-image-occlusion-zoom-out = Reduzir Zoom
editing-image-occlusion-zoom-in = Ampliar Zoom
editing-image-occlusion-zoom-reset = Redefinir Zoom
editing-image-occlusion-toggle-translucent = Translucidez
editing-image-occlusion-delete = Excluir
editing-image-occlusion-duplicate = Duplicar
editing-image-occlusion-group = Agrupar Seleção
editing-image-occlusion-ungroup = Desagrupar Seleção
editing-image-occlusion-select-all = Selecionar Tudo
editing-image-occlusion-alignment = Alinhamento
editing-image-occlusion-align-left = Alinhar à Esquerda
editing-image-occlusion-align-h-center = Centralizar Horizontalmente
editing-image-occlusion-align-right = Alinhar à Direita
editing-image-occlusion-align-top = Alinhar ao Topo
editing-image-occlusion-align-v-center = Centralizar Verticalmente
editing-image-occlusion-align-bottom = Alinhar Abaixo
editing-image-occlusion-select-tool = Selecionar
editing-image-occlusion-zoom-tool = Zoom
editing-image-occlusion-rectangle-tool = Retângulo
editing-image-occlusion-ellipse-tool = Elipse
editing-image-occlusion-polygon-tool = Polígono
editing-image-occlusion-text-tool = Texto
editing-image-occlusion-fill-tool = Preencher com cor
editing-image-occlusion-toggle-mask-editor = Editor de Máscara
editing-image-occlusion-reset = Redefinir Ocultação de Imagem
editing-image-occlusion-confirm-reset = Você tem certeza de que quer redefinir esta oclusão de imagem?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Editor HTML
