// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: anki/decks.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Anki_Decks_DeckId: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var did: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_Decks_DeckIds: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var dids: [Int64] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_Decks_Deck: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: Int64 {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  public var name: String {
    get {return _storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  public var mtimeSecs: Int64 {
    get {return _storage._mtimeSecs}
    set {_uniqueStorage()._mtimeSecs = newValue}
  }

  public var usn: Int32 {
    get {return _storage._usn}
    set {_uniqueStorage()._usn = newValue}
  }

  public var common: Anki_Decks_Deck.Common {
    get {return _storage._common ?? Anki_Decks_Deck.Common()}
    set {_uniqueStorage()._common = newValue}
  }
  /// Returns true if `common` has been explicitly set.
  public var hasCommon: Bool {return _storage._common != nil}
  /// Clears the value of `common`. Subsequent reads from it will return its default value.
  public mutating func clearCommon() {_uniqueStorage()._common = nil}

  /// the specifics are inlined here when sending data to clients,
  /// as otherwise an extra level of indirection would be required
  public var kind: OneOf_Kind? {
    get {return _storage._kind}
    set {_uniqueStorage()._kind = newValue}
  }

  public var normal: Anki_Decks_Deck.Normal {
    get {
      if case .normal(let v)? = _storage._kind {return v}
      return Anki_Decks_Deck.Normal()
    }
    set {_uniqueStorage()._kind = .normal(newValue)}
  }

  public var filtered: Anki_Decks_Deck.Filtered {
    get {
      if case .filtered(let v)? = _storage._kind {return v}
      return Anki_Decks_Deck.Filtered()
    }
    set {_uniqueStorage()._kind = .filtered(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// the specifics are inlined here when sending data to clients,
  /// as otherwise an extra level of indirection would be required
  public enum OneOf_Kind: Equatable, Sendable {
    case normal(Anki_Decks_Deck.Normal)
    case filtered(Anki_Decks_Deck.Filtered)

  }

  public struct Common: @unchecked Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var studyCollapsed: Bool = false

    public var browserCollapsed: Bool = false

    public var lastDayStudied: UInt32 = 0

    public var newStudied: Int32 = 0

    public var reviewStudied: Int32 = 0

    public var millisecondsStudied: Int32 = 0

    /// previously set in the v1 scheduler,
    /// but not currently used for anything
    public var learningStudied: Int32 = 0

    public var other: Data = Data()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct Normal: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var configID: Int64 = 0

    public var extendNew: UInt32 = 0

    public var extendReview: UInt32 = 0

    public var description_p: String = String()

    public var markdownDescription: Bool = false

    public var reviewLimit: UInt32 {
      get {return _reviewLimit ?? 0}
      set {_reviewLimit = newValue}
    }
    /// Returns true if `reviewLimit` has been explicitly set.
    public var hasReviewLimit: Bool {return self._reviewLimit != nil}
    /// Clears the value of `reviewLimit`. Subsequent reads from it will return its default value.
    public mutating func clearReviewLimit() {self._reviewLimit = nil}

    public var newLimit: UInt32 {
      get {return _newLimit ?? 0}
      set {_newLimit = newValue}
    }
    /// Returns true if `newLimit` has been explicitly set.
    public var hasNewLimit: Bool {return self._newLimit != nil}
    /// Clears the value of `newLimit`. Subsequent reads from it will return its default value.
    public mutating func clearNewLimit() {self._newLimit = nil}

    public var reviewLimitToday: Anki_Decks_Deck.Normal.DayLimit {
      get {return _reviewLimitToday ?? Anki_Decks_Deck.Normal.DayLimit()}
      set {_reviewLimitToday = newValue}
    }
    /// Returns true if `reviewLimitToday` has been explicitly set.
    public var hasReviewLimitToday: Bool {return self._reviewLimitToday != nil}
    /// Clears the value of `reviewLimitToday`. Subsequent reads from it will return its default value.
    public mutating func clearReviewLimitToday() {self._reviewLimitToday = nil}

    public var newLimitToday: Anki_Decks_Deck.Normal.DayLimit {
      get {return _newLimitToday ?? Anki_Decks_Deck.Normal.DayLimit()}
      set {_newLimitToday = newValue}
    }
    /// Returns true if `newLimitToday` has been explicitly set.
    public var hasNewLimitToday: Bool {return self._newLimitToday != nil}
    /// Clears the value of `newLimitToday`. Subsequent reads from it will return its default value.
    public mutating func clearNewLimitToday() {self._newLimitToday = nil}

    /// Deck-specific desired retention override
    public var desiredRetention: Float {
      get {return _desiredRetention ?? 0}
      set {_desiredRetention = newValue}
    }
    /// Returns true if `desiredRetention` has been explicitly set.
    public var hasDesiredRetention: Bool {return self._desiredRetention != nil}
    /// Clears the value of `desiredRetention`. Subsequent reads from it will return its default value.
    public mutating func clearDesiredRetention() {self._desiredRetention = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public struct DayLimit: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      public var limit: UInt32 = 0

      public var today: UInt32 = 0

      public var unknownFields = SwiftProtobuf.UnknownStorage()

      public init() {}
    }

    public init() {}

    fileprivate var _reviewLimit: UInt32? = nil
    fileprivate var _newLimit: UInt32? = nil
    fileprivate var _reviewLimitToday: Anki_Decks_Deck.Normal.DayLimit? = nil
    fileprivate var _newLimitToday: Anki_Decks_Deck.Normal.DayLimit? = nil
    fileprivate var _desiredRetention: Float? = nil
  }

  public struct Filtered: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var reschedule: Bool = false

    public var searchTerms: [Anki_Decks_Deck.Filtered.SearchTerm] = []

    /// v1 scheduler only
    public var delays: [Float] = []

    /// v2 and old v3 scheduler only
    public var previewDelay: UInt32 = 0

    /// recent v3 scheduler only; 0 means card will be returned
    public var previewAgainSecs: UInt32 = 0

    /// recent v3 scheduler only; 0 means card will be returned
    public var previewHardSecs: UInt32 = 0

    /// recent v3 scheduler only; 0 means card will be returned
    public var previewGoodSecs: UInt32 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public struct SearchTerm: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      public var search: String = String()

      public var limit: UInt32 = 0

      public var order: Anki_Decks_Deck.Filtered.SearchTerm.Order = .oldestReviewedFirst

      public var unknownFields = SwiftProtobuf.UnknownStorage()

      public enum Order: SwiftProtobuf.Enum, Swift.CaseIterable {
        public typealias RawValue = Int
        case oldestReviewedFirst // = 0
        case random // = 1
        case intervalsAscending // = 2
        case intervalsDescending // = 3
        case lapses // = 4
        case added // = 5
        case due // = 6
        case reverseAdded // = 7
        case retrievabilityAscending // = 8
        case retrievabilityDescending // = 9
        case relativeOverdueness // = 10
        case UNRECOGNIZED(Int)

        public init() {
          self = .oldestReviewedFirst
        }

        public init?(rawValue: Int) {
          switch rawValue {
          case 0: self = .oldestReviewedFirst
          case 1: self = .random
          case 2: self = .intervalsAscending
          case 3: self = .intervalsDescending
          case 4: self = .lapses
          case 5: self = .added
          case 6: self = .due
          case 7: self = .reverseAdded
          case 8: self = .retrievabilityAscending
          case 9: self = .retrievabilityDescending
          case 10: self = .relativeOverdueness
          default: self = .UNRECOGNIZED(rawValue)
          }
        }

        public var rawValue: Int {
          switch self {
          case .oldestReviewedFirst: return 0
          case .random: return 1
          case .intervalsAscending: return 2
          case .intervalsDescending: return 3
          case .lapses: return 4
          case .added: return 5
          case .due: return 6
          case .reverseAdded: return 7
          case .retrievabilityAscending: return 8
          case .retrievabilityDescending: return 9
          case .relativeOverdueness: return 10
          case .UNRECOGNIZED(let i): return i
          }
        }

        // The compiler won't synthesize support with the UNRECOGNIZED case.
        public static let allCases: [Anki_Decks_Deck.Filtered.SearchTerm.Order] = [
          .oldestReviewedFirst,
          .random,
          .intervalsAscending,
          .intervalsDescending,
          .lapses,
          .added,
          .due,
          .reverseAdded,
          .retrievabilityAscending,
          .retrievabilityDescending,
          .relativeOverdueness,
        ]

      }

      public init() {}
    }

    public init() {}
  }

  /// a container to store the deck specifics in the DB
  /// as a tagged enum
  public struct KindContainer: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var kind: Anki_Decks_Deck.KindContainer.OneOf_Kind? = nil

    public var normal: Anki_Decks_Deck.Normal {
      get {
        if case .normal(let v)? = kind {return v}
        return Anki_Decks_Deck.Normal()
      }
      set {kind = .normal(newValue)}
    }

    public var filtered: Anki_Decks_Deck.Filtered {
      get {
        if case .filtered(let v)? = kind {return v}
        return Anki_Decks_Deck.Filtered()
      }
      set {kind = .filtered(newValue)}
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public enum OneOf_Kind: Equatable, Sendable {
      case normal(Anki_Decks_Deck.Normal)
      case filtered(Anki_Decks_Deck.Filtered)

    }

    public init() {}
  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Anki_Decks_AddOrUpdateDeckLegacyRequest: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deck: Data = Data()

  public var preserveUsnAndMtime: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_Decks_DeckTreeRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// if non-zero, counts for the provided timestamp will be included
  public var now: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_Decks_DeckTreeNode: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deckID: Int64 = 0

  public var name: String = String()

  public var level: UInt32 = 0

  public var collapsed: Bool = false

  /// counts after adding children+applying limits
  public var reviewCount: UInt32 = 0

  public var learnCount: UInt32 = 0

  public var newCount: UInt32 = 0

  /// card counts without children or limits applied
  public var intradayLearning: UInt32 = 0

  public var interdayLearningUncapped: UInt32 = 0

  public var newUncapped: UInt32 = 0

  public var reviewUncapped: UInt32 = 0

  public var totalInDeck: UInt32 = 0

  /// with children, without any limits
  public var totalIncludingChildren: UInt32 = 0

  public var filtered: Bool = false

  /// low index so key can be packed into a byte, but at bottom
  /// to make debug output easier to read
  public var children: [Anki_Decks_DeckTreeNode] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_Decks_SetDeckCollapsedRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deckID: Int64 = 0

  public var collapsed: Bool = false

  public var scope: Anki_Decks_SetDeckCollapsedRequest.Scope = .reviewer

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Scope: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case reviewer // = 0
    case browser // = 1
    case UNRECOGNIZED(Int)

    public init() {
      self = .reviewer
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .reviewer
      case 1: self = .browser
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .reviewer: return 0
      case .browser: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Anki_Decks_SetDeckCollapsedRequest.Scope] = [
      .reviewer,
      .browser,
    ]

  }

  public init() {}
}

public struct Anki_Decks_GetDeckNamesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var skipEmptyDefault: Bool = false

  /// if unset, implies skip_empty_default
  public var includeFiltered: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_Decks_DeckNames: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var entries: [Anki_Decks_DeckNameId] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_Decks_DeckNameId: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: Int64 = 0

  public var name: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_Decks_ReparentDecksRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deckIds: [Int64] = []

  public var newParent: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_Decks_RenameDeckRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deckID: Int64 = 0

  public var newName: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_Decks_FilteredDeckForUpdate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: Int64 = 0

  public var name: String = String()

  public var config: Anki_Decks_Deck.Filtered {
    get {return _config ?? Anki_Decks_Deck.Filtered()}
    set {_config = newValue}
  }
  /// Returns true if `config` has been explicitly set.
  public var hasConfig: Bool {return self._config != nil}
  /// Clears the value of `config`. Subsequent reads from it will return its default value.
  public mutating func clearConfig() {self._config = nil}

  public var allowEmpty: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _config: Anki_Decks_Deck.Filtered? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "anki.decks"

extension Anki_Decks_DeckId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeckId"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "did"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.did) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.did != 0 {
      try visitor.visitSingularInt64Field(value: self.did, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Decks_DeckId, rhs: Anki_Decks_DeckId) -> Bool {
    if lhs.did != rhs.did {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Decks_DeckIds: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeckIds"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "dids"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedInt64Field(value: &self.dids) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.dids.isEmpty {
      try visitor.visitPackedInt64Field(value: self.dids, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Decks_DeckIds, rhs: Anki_Decks_DeckIds) -> Bool {
    if lhs.dids != rhs.dids {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Decks_Deck: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Deck"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "name"),
    3: .standard(proto: "mtime_secs"),
    4: .same(proto: "usn"),
    5: .same(proto: "common"),
    6: .same(proto: "normal"),
    7: .same(proto: "filtered"),
  ]

  fileprivate class _StorageClass {
    var _id: Int64 = 0
    var _name: String = String()
    var _mtimeSecs: Int64 = 0
    var _usn: Int32 = 0
    var _common: Anki_Decks_Deck.Common? = nil
    var _kind: Anki_Decks_Deck.OneOf_Kind?

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _name = source._name
      _mtimeSecs = source._mtimeSecs
      _usn = source._usn
      _common = source._common
      _kind = source._kind
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularInt64Field(value: &_storage._id) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 3: try { try decoder.decodeSingularInt64Field(value: &_storage._mtimeSecs) }()
        case 4: try { try decoder.decodeSingularInt32Field(value: &_storage._usn) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._common) }()
        case 6: try {
          var v: Anki_Decks_Deck.Normal?
          var hadOneofValue = false
          if let current = _storage._kind {
            hadOneofValue = true
            if case .normal(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._kind = .normal(v)
          }
        }()
        case 7: try {
          var v: Anki_Decks_Deck.Filtered?
          var hadOneofValue = false
          if let current = _storage._kind {
            hadOneofValue = true
            if case .filtered(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._kind = .filtered(v)
          }
        }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._id != 0 {
        try visitor.visitSingularInt64Field(value: _storage._id, fieldNumber: 1)
      }
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 2)
      }
      if _storage._mtimeSecs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._mtimeSecs, fieldNumber: 3)
      }
      if _storage._usn != 0 {
        try visitor.visitSingularInt32Field(value: _storage._usn, fieldNumber: 4)
      }
      try { if let v = _storage._common {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      switch _storage._kind {
      case .normal?: try {
        guard case .normal(let v)? = _storage._kind else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      }()
      case .filtered?: try {
        guard case .filtered(let v)? = _storage._kind else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      }()
      case nil: break
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Decks_Deck, rhs: Anki_Decks_Deck) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._mtimeSecs != rhs_storage._mtimeSecs {return false}
        if _storage._usn != rhs_storage._usn {return false}
        if _storage._common != rhs_storage._common {return false}
        if _storage._kind != rhs_storage._kind {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Decks_Deck.Common: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Anki_Decks_Deck.protoMessageName + ".Common"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "study_collapsed"),
    2: .standard(proto: "browser_collapsed"),
    3: .standard(proto: "last_day_studied"),
    4: .standard(proto: "new_studied"),
    5: .standard(proto: "review_studied"),
    7: .standard(proto: "milliseconds_studied"),
    6: .standard(proto: "learning_studied"),
    255: .same(proto: "other"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.studyCollapsed) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.browserCollapsed) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.lastDayStudied) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.newStudied) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.reviewStudied) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.learningStudied) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.millisecondsStudied) }()
      case 255: try { try decoder.decodeSingularBytesField(value: &self.other) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.studyCollapsed != false {
      try visitor.visitSingularBoolField(value: self.studyCollapsed, fieldNumber: 1)
    }
    if self.browserCollapsed != false {
      try visitor.visitSingularBoolField(value: self.browserCollapsed, fieldNumber: 2)
    }
    if self.lastDayStudied != 0 {
      try visitor.visitSingularUInt32Field(value: self.lastDayStudied, fieldNumber: 3)
    }
    if self.newStudied != 0 {
      try visitor.visitSingularInt32Field(value: self.newStudied, fieldNumber: 4)
    }
    if self.reviewStudied != 0 {
      try visitor.visitSingularInt32Field(value: self.reviewStudied, fieldNumber: 5)
    }
    if self.learningStudied != 0 {
      try visitor.visitSingularInt32Field(value: self.learningStudied, fieldNumber: 6)
    }
    if self.millisecondsStudied != 0 {
      try visitor.visitSingularInt32Field(value: self.millisecondsStudied, fieldNumber: 7)
    }
    if !self.other.isEmpty {
      try visitor.visitSingularBytesField(value: self.other, fieldNumber: 255)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Decks_Deck.Common, rhs: Anki_Decks_Deck.Common) -> Bool {
    if lhs.studyCollapsed != rhs.studyCollapsed {return false}
    if lhs.browserCollapsed != rhs.browserCollapsed {return false}
    if lhs.lastDayStudied != rhs.lastDayStudied {return false}
    if lhs.newStudied != rhs.newStudied {return false}
    if lhs.reviewStudied != rhs.reviewStudied {return false}
    if lhs.millisecondsStudied != rhs.millisecondsStudied {return false}
    if lhs.learningStudied != rhs.learningStudied {return false}
    if lhs.other != rhs.other {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Decks_Deck.Normal: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Anki_Decks_Deck.protoMessageName + ".Normal"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "config_id"),
    2: .standard(proto: "extend_new"),
    3: .standard(proto: "extend_review"),
    4: .same(proto: "description"),
    5: .standard(proto: "markdown_description"),
    6: .standard(proto: "review_limit"),
    7: .standard(proto: "new_limit"),
    8: .standard(proto: "review_limit_today"),
    9: .standard(proto: "new_limit_today"),
    10: .standard(proto: "desired_retention"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.configID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.extendNew) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.extendReview) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.description_p) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.markdownDescription) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self._reviewLimit) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self._newLimit) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._reviewLimitToday) }()
      case 9: try { try decoder.decodeSingularMessageField(value: &self._newLimitToday) }()
      case 10: try { try decoder.decodeSingularFloatField(value: &self._desiredRetention) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.configID != 0 {
      try visitor.visitSingularInt64Field(value: self.configID, fieldNumber: 1)
    }
    if self.extendNew != 0 {
      try visitor.visitSingularUInt32Field(value: self.extendNew, fieldNumber: 2)
    }
    if self.extendReview != 0 {
      try visitor.visitSingularUInt32Field(value: self.extendReview, fieldNumber: 3)
    }
    if !self.description_p.isEmpty {
      try visitor.visitSingularStringField(value: self.description_p, fieldNumber: 4)
    }
    if self.markdownDescription != false {
      try visitor.visitSingularBoolField(value: self.markdownDescription, fieldNumber: 5)
    }
    try { if let v = self._reviewLimit {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._newLimit {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._reviewLimitToday {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._newLimitToday {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._desiredRetention {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 10)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Decks_Deck.Normal, rhs: Anki_Decks_Deck.Normal) -> Bool {
    if lhs.configID != rhs.configID {return false}
    if lhs.extendNew != rhs.extendNew {return false}
    if lhs.extendReview != rhs.extendReview {return false}
    if lhs.description_p != rhs.description_p {return false}
    if lhs.markdownDescription != rhs.markdownDescription {return false}
    if lhs._reviewLimit != rhs._reviewLimit {return false}
    if lhs._newLimit != rhs._newLimit {return false}
    if lhs._reviewLimitToday != rhs._reviewLimitToday {return false}
    if lhs._newLimitToday != rhs._newLimitToday {return false}
    if lhs._desiredRetention != rhs._desiredRetention {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Decks_Deck.Normal.DayLimit: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Anki_Decks_Deck.Normal.protoMessageName + ".DayLimit"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "limit"),
    2: .same(proto: "today"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.limit) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.today) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.limit != 0 {
      try visitor.visitSingularUInt32Field(value: self.limit, fieldNumber: 1)
    }
    if self.today != 0 {
      try visitor.visitSingularUInt32Field(value: self.today, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Decks_Deck.Normal.DayLimit, rhs: Anki_Decks_Deck.Normal.DayLimit) -> Bool {
    if lhs.limit != rhs.limit {return false}
    if lhs.today != rhs.today {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Decks_Deck.Filtered: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Anki_Decks_Deck.protoMessageName + ".Filtered"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "reschedule"),
    2: .standard(proto: "search_terms"),
    3: .same(proto: "delays"),
    4: .standard(proto: "preview_delay"),
    7: .standard(proto: "preview_again_secs"),
    5: .standard(proto: "preview_hard_secs"),
    6: .standard(proto: "preview_good_secs"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.reschedule) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.searchTerms) }()
      case 3: try { try decoder.decodeRepeatedFloatField(value: &self.delays) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.previewDelay) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.previewHardSecs) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.previewGoodSecs) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self.previewAgainSecs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.reschedule != false {
      try visitor.visitSingularBoolField(value: self.reschedule, fieldNumber: 1)
    }
    if !self.searchTerms.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.searchTerms, fieldNumber: 2)
    }
    if !self.delays.isEmpty {
      try visitor.visitPackedFloatField(value: self.delays, fieldNumber: 3)
    }
    if self.previewDelay != 0 {
      try visitor.visitSingularUInt32Field(value: self.previewDelay, fieldNumber: 4)
    }
    if self.previewHardSecs != 0 {
      try visitor.visitSingularUInt32Field(value: self.previewHardSecs, fieldNumber: 5)
    }
    if self.previewGoodSecs != 0 {
      try visitor.visitSingularUInt32Field(value: self.previewGoodSecs, fieldNumber: 6)
    }
    if self.previewAgainSecs != 0 {
      try visitor.visitSingularUInt32Field(value: self.previewAgainSecs, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Decks_Deck.Filtered, rhs: Anki_Decks_Deck.Filtered) -> Bool {
    if lhs.reschedule != rhs.reschedule {return false}
    if lhs.searchTerms != rhs.searchTerms {return false}
    if lhs.delays != rhs.delays {return false}
    if lhs.previewDelay != rhs.previewDelay {return false}
    if lhs.previewAgainSecs != rhs.previewAgainSecs {return false}
    if lhs.previewHardSecs != rhs.previewHardSecs {return false}
    if lhs.previewGoodSecs != rhs.previewGoodSecs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Decks_Deck.Filtered.SearchTerm: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Anki_Decks_Deck.Filtered.protoMessageName + ".SearchTerm"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "search"),
    2: .same(proto: "limit"),
    3: .same(proto: "order"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.search) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.limit) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.order) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.search.isEmpty {
      try visitor.visitSingularStringField(value: self.search, fieldNumber: 1)
    }
    if self.limit != 0 {
      try visitor.visitSingularUInt32Field(value: self.limit, fieldNumber: 2)
    }
    if self.order != .oldestReviewedFirst {
      try visitor.visitSingularEnumField(value: self.order, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Decks_Deck.Filtered.SearchTerm, rhs: Anki_Decks_Deck.Filtered.SearchTerm) -> Bool {
    if lhs.search != rhs.search {return false}
    if lhs.limit != rhs.limit {return false}
    if lhs.order != rhs.order {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Decks_Deck.Filtered.SearchTerm.Order: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "OLDEST_REVIEWED_FIRST"),
    1: .same(proto: "RANDOM"),
    2: .same(proto: "INTERVALS_ASCENDING"),
    3: .same(proto: "INTERVALS_DESCENDING"),
    4: .same(proto: "LAPSES"),
    5: .same(proto: "ADDED"),
    6: .same(proto: "DUE"),
    7: .same(proto: "REVERSE_ADDED"),
    8: .same(proto: "RETRIEVABILITY_ASCENDING"),
    9: .same(proto: "RETRIEVABILITY_DESCENDING"),
    10: .same(proto: "RELATIVE_OVERDUENESS"),
  ]
}

extension Anki_Decks_Deck.KindContainer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Anki_Decks_Deck.protoMessageName + ".KindContainer"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "normal"),
    2: .same(proto: "filtered"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Anki_Decks_Deck.Normal?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .normal(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .normal(v)
        }
      }()
      case 2: try {
        var v: Anki_Decks_Deck.Filtered?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .filtered(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .filtered(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.kind {
    case .normal?: try {
      guard case .normal(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .filtered?: try {
      guard case .filtered(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Decks_Deck.KindContainer, rhs: Anki_Decks_Deck.KindContainer) -> Bool {
    if lhs.kind != rhs.kind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Decks_AddOrUpdateDeckLegacyRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AddOrUpdateDeckLegacyRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "deck"),
    2: .standard(proto: "preserve_usn_and_mtime"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.deck) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.preserveUsnAndMtime) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.deck.isEmpty {
      try visitor.visitSingularBytesField(value: self.deck, fieldNumber: 1)
    }
    if self.preserveUsnAndMtime != false {
      try visitor.visitSingularBoolField(value: self.preserveUsnAndMtime, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Decks_AddOrUpdateDeckLegacyRequest, rhs: Anki_Decks_AddOrUpdateDeckLegacyRequest) -> Bool {
    if lhs.deck != rhs.deck {return false}
    if lhs.preserveUsnAndMtime != rhs.preserveUsnAndMtime {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Decks_DeckTreeRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeckTreeRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "now"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.now) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.now != 0 {
      try visitor.visitSingularInt64Field(value: self.now, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Decks_DeckTreeRequest, rhs: Anki_Decks_DeckTreeRequest) -> Bool {
    if lhs.now != rhs.now {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Decks_DeckTreeNode: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeckTreeNode"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "deck_id"),
    2: .same(proto: "name"),
    4: .same(proto: "level"),
    5: .same(proto: "collapsed"),
    6: .standard(proto: "review_count"),
    7: .standard(proto: "learn_count"),
    8: .standard(proto: "new_count"),
    9: .standard(proto: "intraday_learning"),
    10: .standard(proto: "interday_learning_uncapped"),
    11: .standard(proto: "new_uncapped"),
    12: .standard(proto: "review_uncapped"),
    13: .standard(proto: "total_in_deck"),
    14: .standard(proto: "total_including_children"),
    16: .same(proto: "filtered"),
    3: .same(proto: "children"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.deckID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.children) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.level) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.collapsed) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.reviewCount) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self.learnCount) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self.newCount) }()
      case 9: try { try decoder.decodeSingularUInt32Field(value: &self.intradayLearning) }()
      case 10: try { try decoder.decodeSingularUInt32Field(value: &self.interdayLearningUncapped) }()
      case 11: try { try decoder.decodeSingularUInt32Field(value: &self.newUncapped) }()
      case 12: try { try decoder.decodeSingularUInt32Field(value: &self.reviewUncapped) }()
      case 13: try { try decoder.decodeSingularUInt32Field(value: &self.totalInDeck) }()
      case 14: try { try decoder.decodeSingularUInt32Field(value: &self.totalIncludingChildren) }()
      case 16: try { try decoder.decodeSingularBoolField(value: &self.filtered) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.deckID != 0 {
      try visitor.visitSingularInt64Field(value: self.deckID, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.children.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.children, fieldNumber: 3)
    }
    if self.level != 0 {
      try visitor.visitSingularUInt32Field(value: self.level, fieldNumber: 4)
    }
    if self.collapsed != false {
      try visitor.visitSingularBoolField(value: self.collapsed, fieldNumber: 5)
    }
    if self.reviewCount != 0 {
      try visitor.visitSingularUInt32Field(value: self.reviewCount, fieldNumber: 6)
    }
    if self.learnCount != 0 {
      try visitor.visitSingularUInt32Field(value: self.learnCount, fieldNumber: 7)
    }
    if self.newCount != 0 {
      try visitor.visitSingularUInt32Field(value: self.newCount, fieldNumber: 8)
    }
    if self.intradayLearning != 0 {
      try visitor.visitSingularUInt32Field(value: self.intradayLearning, fieldNumber: 9)
    }
    if self.interdayLearningUncapped != 0 {
      try visitor.visitSingularUInt32Field(value: self.interdayLearningUncapped, fieldNumber: 10)
    }
    if self.newUncapped != 0 {
      try visitor.visitSingularUInt32Field(value: self.newUncapped, fieldNumber: 11)
    }
    if self.reviewUncapped != 0 {
      try visitor.visitSingularUInt32Field(value: self.reviewUncapped, fieldNumber: 12)
    }
    if self.totalInDeck != 0 {
      try visitor.visitSingularUInt32Field(value: self.totalInDeck, fieldNumber: 13)
    }
    if self.totalIncludingChildren != 0 {
      try visitor.visitSingularUInt32Field(value: self.totalIncludingChildren, fieldNumber: 14)
    }
    if self.filtered != false {
      try visitor.visitSingularBoolField(value: self.filtered, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Decks_DeckTreeNode, rhs: Anki_Decks_DeckTreeNode) -> Bool {
    if lhs.deckID != rhs.deckID {return false}
    if lhs.name != rhs.name {return false}
    if lhs.level != rhs.level {return false}
    if lhs.collapsed != rhs.collapsed {return false}
    if lhs.reviewCount != rhs.reviewCount {return false}
    if lhs.learnCount != rhs.learnCount {return false}
    if lhs.newCount != rhs.newCount {return false}
    if lhs.intradayLearning != rhs.intradayLearning {return false}
    if lhs.interdayLearningUncapped != rhs.interdayLearningUncapped {return false}
    if lhs.newUncapped != rhs.newUncapped {return false}
    if lhs.reviewUncapped != rhs.reviewUncapped {return false}
    if lhs.totalInDeck != rhs.totalInDeck {return false}
    if lhs.totalIncludingChildren != rhs.totalIncludingChildren {return false}
    if lhs.filtered != rhs.filtered {return false}
    if lhs.children != rhs.children {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Decks_SetDeckCollapsedRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SetDeckCollapsedRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "deck_id"),
    2: .same(proto: "collapsed"),
    3: .same(proto: "scope"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.deckID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.collapsed) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.scope) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.deckID != 0 {
      try visitor.visitSingularInt64Field(value: self.deckID, fieldNumber: 1)
    }
    if self.collapsed != false {
      try visitor.visitSingularBoolField(value: self.collapsed, fieldNumber: 2)
    }
    if self.scope != .reviewer {
      try visitor.visitSingularEnumField(value: self.scope, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Decks_SetDeckCollapsedRequest, rhs: Anki_Decks_SetDeckCollapsedRequest) -> Bool {
    if lhs.deckID != rhs.deckID {return false}
    if lhs.collapsed != rhs.collapsed {return false}
    if lhs.scope != rhs.scope {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Decks_SetDeckCollapsedRequest.Scope: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "REVIEWER"),
    1: .same(proto: "BROWSER"),
  ]
}

extension Anki_Decks_GetDeckNamesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetDeckNamesRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "skip_empty_default"),
    2: .standard(proto: "include_filtered"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.skipEmptyDefault) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.includeFiltered) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.skipEmptyDefault != false {
      try visitor.visitSingularBoolField(value: self.skipEmptyDefault, fieldNumber: 1)
    }
    if self.includeFiltered != false {
      try visitor.visitSingularBoolField(value: self.includeFiltered, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Decks_GetDeckNamesRequest, rhs: Anki_Decks_GetDeckNamesRequest) -> Bool {
    if lhs.skipEmptyDefault != rhs.skipEmptyDefault {return false}
    if lhs.includeFiltered != rhs.includeFiltered {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Decks_DeckNames: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeckNames"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "entries"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.entries) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.entries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.entries, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Decks_DeckNames, rhs: Anki_Decks_DeckNames) -> Bool {
    if lhs.entries != rhs.entries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Decks_DeckNameId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeckNameId"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "name"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularInt64Field(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Decks_DeckNameId, rhs: Anki_Decks_DeckNameId) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Decks_ReparentDecksRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ReparentDecksRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "deck_ids"),
    2: .standard(proto: "new_parent"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedInt64Field(value: &self.deckIds) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.newParent) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.deckIds.isEmpty {
      try visitor.visitPackedInt64Field(value: self.deckIds, fieldNumber: 1)
    }
    if self.newParent != 0 {
      try visitor.visitSingularInt64Field(value: self.newParent, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Decks_ReparentDecksRequest, rhs: Anki_Decks_ReparentDecksRequest) -> Bool {
    if lhs.deckIds != rhs.deckIds {return false}
    if lhs.newParent != rhs.newParent {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Decks_RenameDeckRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RenameDeckRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "deck_id"),
    2: .standard(proto: "new_name"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.deckID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.newName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.deckID != 0 {
      try visitor.visitSingularInt64Field(value: self.deckID, fieldNumber: 1)
    }
    if !self.newName.isEmpty {
      try visitor.visitSingularStringField(value: self.newName, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Decks_RenameDeckRequest, rhs: Anki_Decks_RenameDeckRequest) -> Bool {
    if lhs.deckID != rhs.deckID {return false}
    if lhs.newName != rhs.newName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Decks_FilteredDeckForUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FilteredDeckForUpdate"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "name"),
    3: .same(proto: "config"),
    4: .standard(proto: "allow_empty"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._config) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.allowEmpty) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.id != 0 {
      try visitor.visitSingularInt64Field(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    try { if let v = self._config {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.allowEmpty != false {
      try visitor.visitSingularBoolField(value: self.allowEmpty, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Decks_FilteredDeckForUpdate, rhs: Anki_Decks_FilteredDeckForUpdate) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs._config != rhs._config {return false}
    if lhs.allowEmpty != rhs.allowEmpty {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
