// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: anki/deck_config.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Anki_DeckConfig_UpdateDeckConfigsMode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case normal // = 0
  case applyToChildren // = 1
  case computeAllParams // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .normal
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .normal
    case 1: self = .applyToChildren
    case 2: self = .computeAllParams
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .normal: return 0
    case .applyToChildren: return 1
    case .computeAllParams: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Anki_DeckConfig_UpdateDeckConfigsMode] = [
    .normal,
    .applyToChildren,
    .computeAllParams,
  ]

}

public struct Anki_DeckConfig_DeckConfigId: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var dcid: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_DeckConfig_GetRetentionWorkloadRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var w: [Float] = []

  public var search: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_DeckConfig_GetRetentionWorkloadResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var costs: Dictionary<UInt32,Float> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_DeckConfig_GetIgnoredBeforeCountRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var ignoreRevlogsBeforeDate: String = String()

  public var search: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_DeckConfig_GetIgnoredBeforeCountResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var included: UInt64 = 0

  public var total: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_DeckConfig_DeckConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: Int64 = 0

  public var name: String = String()

  public var mtimeSecs: Int64 = 0

  public var usn: Int32 = 0

  public var config: Anki_DeckConfig_DeckConfig.Config {
    get {return _config ?? Anki_DeckConfig_DeckConfig.Config()}
    set {_config = newValue}
  }
  /// Returns true if `config` has been explicitly set.
  public var hasConfig: Bool {return self._config != nil}
  /// Clears the value of `config`. Subsequent reads from it will return its default value.
  public mutating func clearConfig() {self._config = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public struct Config: @unchecked Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var learnSteps: [Float] {
      get {return _storage._learnSteps}
      set {_uniqueStorage()._learnSteps = newValue}
    }

    public var relearnSteps: [Float] {
      get {return _storage._relearnSteps}
      set {_uniqueStorage()._relearnSteps = newValue}
    }

    public var fsrsParams4: [Float] {
      get {return _storage._fsrsParams4}
      set {_uniqueStorage()._fsrsParams4 = newValue}
    }

    public var fsrsParams5: [Float] {
      get {return _storage._fsrsParams5}
      set {_uniqueStorage()._fsrsParams5 = newValue}
    }

    public var fsrsParams6: [Float] {
      get {return _storage._fsrsParams6}
      set {_uniqueStorage()._fsrsParams6 = newValue}
    }

    public var newPerDay: UInt32 {
      get {return _storage._newPerDay}
      set {_uniqueStorage()._newPerDay = newValue}
    }

    public var reviewsPerDay: UInt32 {
      get {return _storage._reviewsPerDay}
      set {_uniqueStorage()._reviewsPerDay = newValue}
    }

    /// not currently used
    public var newPerDayMinimum: UInt32 {
      get {return _storage._newPerDayMinimum}
      set {_uniqueStorage()._newPerDayMinimum = newValue}
    }

    public var initialEase: Float {
      get {return _storage._initialEase}
      set {_uniqueStorage()._initialEase = newValue}
    }

    public var easyMultiplier: Float {
      get {return _storage._easyMultiplier}
      set {_uniqueStorage()._easyMultiplier = newValue}
    }

    public var hardMultiplier: Float {
      get {return _storage._hardMultiplier}
      set {_uniqueStorage()._hardMultiplier = newValue}
    }

    public var lapseMultiplier: Float {
      get {return _storage._lapseMultiplier}
      set {_uniqueStorage()._lapseMultiplier = newValue}
    }

    public var intervalMultiplier: Float {
      get {return _storage._intervalMultiplier}
      set {_uniqueStorage()._intervalMultiplier = newValue}
    }

    public var maximumReviewInterval: UInt32 {
      get {return _storage._maximumReviewInterval}
      set {_uniqueStorage()._maximumReviewInterval = newValue}
    }

    public var minimumLapseInterval: UInt32 {
      get {return _storage._minimumLapseInterval}
      set {_uniqueStorage()._minimumLapseInterval = newValue}
    }

    public var graduatingIntervalGood: UInt32 {
      get {return _storage._graduatingIntervalGood}
      set {_uniqueStorage()._graduatingIntervalGood = newValue}
    }

    public var graduatingIntervalEasy: UInt32 {
      get {return _storage._graduatingIntervalEasy}
      set {_uniqueStorage()._graduatingIntervalEasy = newValue}
    }

    public var newCardInsertOrder: Anki_DeckConfig_DeckConfig.Config.NewCardInsertOrder {
      get {return _storage._newCardInsertOrder}
      set {_uniqueStorage()._newCardInsertOrder = newValue}
    }

    public var newCardGatherPriority: Anki_DeckConfig_DeckConfig.Config.NewCardGatherPriority {
      get {return _storage._newCardGatherPriority}
      set {_uniqueStorage()._newCardGatherPriority = newValue}
    }

    public var newCardSortOrder: Anki_DeckConfig_DeckConfig.Config.NewCardSortOrder {
      get {return _storage._newCardSortOrder}
      set {_uniqueStorage()._newCardSortOrder = newValue}
    }

    public var newMix: Anki_DeckConfig_DeckConfig.Config.ReviewMix {
      get {return _storage._newMix}
      set {_uniqueStorage()._newMix = newValue}
    }

    public var reviewOrder: Anki_DeckConfig_DeckConfig.Config.ReviewCardOrder {
      get {return _storage._reviewOrder}
      set {_uniqueStorage()._reviewOrder = newValue}
    }

    public var interdayLearningMix: Anki_DeckConfig_DeckConfig.Config.ReviewMix {
      get {return _storage._interdayLearningMix}
      set {_uniqueStorage()._interdayLearningMix = newValue}
    }

    public var leechAction: Anki_DeckConfig_DeckConfig.Config.LeechAction {
      get {return _storage._leechAction}
      set {_uniqueStorage()._leechAction = newValue}
    }

    public var leechThreshold: UInt32 {
      get {return _storage._leechThreshold}
      set {_uniqueStorage()._leechThreshold = newValue}
    }

    public var disableAutoplay: Bool {
      get {return _storage._disableAutoplay}
      set {_uniqueStorage()._disableAutoplay = newValue}
    }

    public var capAnswerTimeToSecs: UInt32 {
      get {return _storage._capAnswerTimeToSecs}
      set {_uniqueStorage()._capAnswerTimeToSecs = newValue}
    }

    public var showTimer: Bool {
      get {return _storage._showTimer}
      set {_uniqueStorage()._showTimer = newValue}
    }

    public var stopTimerOnAnswer: Bool {
      get {return _storage._stopTimerOnAnswer}
      set {_uniqueStorage()._stopTimerOnAnswer = newValue}
    }

    public var secondsToShowQuestion: Float {
      get {return _storage._secondsToShowQuestion}
      set {_uniqueStorage()._secondsToShowQuestion = newValue}
    }

    public var secondsToShowAnswer: Float {
      get {return _storage._secondsToShowAnswer}
      set {_uniqueStorage()._secondsToShowAnswer = newValue}
    }

    public var questionAction: Anki_DeckConfig_DeckConfig.Config.QuestionAction {
      get {return _storage._questionAction}
      set {_uniqueStorage()._questionAction = newValue}
    }

    public var answerAction: Anki_DeckConfig_DeckConfig.Config.AnswerAction {
      get {return _storage._answerAction}
      set {_uniqueStorage()._answerAction = newValue}
    }

    public var waitForAudio: Bool {
      get {return _storage._waitForAudio}
      set {_uniqueStorage()._waitForAudio = newValue}
    }

    public var skipQuestionWhenReplayingAnswer: Bool {
      get {return _storage._skipQuestionWhenReplayingAnswer}
      set {_uniqueStorage()._skipQuestionWhenReplayingAnswer = newValue}
    }

    public var buryNew: Bool {
      get {return _storage._buryNew}
      set {_uniqueStorage()._buryNew = newValue}
    }

    public var buryReviews: Bool {
      get {return _storage._buryReviews}
      set {_uniqueStorage()._buryReviews = newValue}
    }

    public var buryInterdayLearning: Bool {
      get {return _storage._buryInterdayLearning}
      set {_uniqueStorage()._buryInterdayLearning = newValue}
    }

    /// for fsrs
    public var desiredRetention: Float {
      get {return _storage._desiredRetention}
      set {_uniqueStorage()._desiredRetention = newValue}
    }

    public var ignoreRevlogsBeforeDate: String {
      get {return _storage._ignoreRevlogsBeforeDate}
      set {_uniqueStorage()._ignoreRevlogsBeforeDate = newValue}
    }

    public var easyDaysPercentages: [Float] {
      get {return _storage._easyDaysPercentages}
      set {_uniqueStorage()._easyDaysPercentages = newValue}
    }

    public var historicalRetention: Float {
      get {return _storage._historicalRetention}
      set {_uniqueStorage()._historicalRetention = newValue}
    }

    public var paramSearch: String {
      get {return _storage._paramSearch}
      set {_uniqueStorage()._paramSearch = newValue}
    }

    public var other: Data {
      get {return _storage._other}
      set {_uniqueStorage()._other = newValue}
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public enum NewCardInsertOrder: SwiftProtobuf.Enum, Swift.CaseIterable {
      public typealias RawValue = Int
      case due // = 0
      case random // = 1
      case UNRECOGNIZED(Int)

      public init() {
        self = .due
      }

      public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .due
        case 1: self = .random
        default: self = .UNRECOGNIZED(rawValue)
        }
      }

      public var rawValue: Int {
        switch self {
        case .due: return 0
        case .random: return 1
        case .UNRECOGNIZED(let i): return i
        }
      }

      // The compiler won't synthesize support with the UNRECOGNIZED case.
      public static let allCases: [Anki_DeckConfig_DeckConfig.Config.NewCardInsertOrder] = [
        .due,
        .random,
      ]

    }

    public enum NewCardGatherPriority: SwiftProtobuf.Enum, Swift.CaseIterable {
      public typealias RawValue = Int

      /// Decks in alphabetical order (preorder), then ascending position.
      /// Siblings are consecutive, provided they have the same position.
      case deck // = 0

      /// Notes are randomly picked from each deck in alphabetical order.
      /// Siblings are consecutive, provided they have the same position.
      case deckThenRandomNotes // = 5

      /// Ascending position.
      /// Siblings are consecutive, provided they have the same position.
      case lowestPosition // = 1

      /// Descending position.
      /// Siblings are consecutive, provided they have the same position.
      case highestPosition // = 2

      /// Siblings are consecutive.
      case randomNotes // = 3

      /// Siblings are neither grouped nor ordered.
      case randomCards // = 4
      case UNRECOGNIZED(Int)

      public init() {
        self = .deck
      }

      public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .deck
        case 1: self = .lowestPosition
        case 2: self = .highestPosition
        case 3: self = .randomNotes
        case 4: self = .randomCards
        case 5: self = .deckThenRandomNotes
        default: self = .UNRECOGNIZED(rawValue)
        }
      }

      public var rawValue: Int {
        switch self {
        case .deck: return 0
        case .lowestPosition: return 1
        case .highestPosition: return 2
        case .randomNotes: return 3
        case .randomCards: return 4
        case .deckThenRandomNotes: return 5
        case .UNRECOGNIZED(let i): return i
        }
      }

      // The compiler won't synthesize support with the UNRECOGNIZED case.
      public static let allCases: [Anki_DeckConfig_DeckConfig.Config.NewCardGatherPriority] = [
        .deck,
        .deckThenRandomNotes,
        .lowestPosition,
        .highestPosition,
        .randomNotes,
        .randomCards,
      ]

    }

    public enum NewCardSortOrder: SwiftProtobuf.Enum, Swift.CaseIterable {
      public typealias RawValue = Int

      /// Ascending card template ordinal.
      /// For a given ordinal, cards appear in gather order.
      case template // = 0

      /// Preserves original gather order (eg deck order).
      case noSort // = 1

      /// Ascending card template ordinal.
      /// For a given ordinal, cards appear in random order.
      case templateThenRandom // = 2

      /// Random note order. For a given note, cards appear in template order.
      case randomNoteThenTemplate // = 3

      /// Fully randomized order.
      case randomCard // = 4
      case UNRECOGNIZED(Int)

      public init() {
        self = .template
      }

      public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .template
        case 1: self = .noSort
        case 2: self = .templateThenRandom
        case 3: self = .randomNoteThenTemplate
        case 4: self = .randomCard
        default: self = .UNRECOGNIZED(rawValue)
        }
      }

      public var rawValue: Int {
        switch self {
        case .template: return 0
        case .noSort: return 1
        case .templateThenRandom: return 2
        case .randomNoteThenTemplate: return 3
        case .randomCard: return 4
        case .UNRECOGNIZED(let i): return i
        }
      }

      // The compiler won't synthesize support with the UNRECOGNIZED case.
      public static let allCases: [Anki_DeckConfig_DeckConfig.Config.NewCardSortOrder] = [
        .template,
        .noSort,
        .templateThenRandom,
        .randomNoteThenTemplate,
        .randomCard,
      ]

    }

    public enum ReviewCardOrder: SwiftProtobuf.Enum, Swift.CaseIterable {
      public typealias RawValue = Int
      case day // = 0
      case dayThenDeck // = 1
      case deckThenDay // = 2
      case intervalsAscending // = 3
      case intervalsDescending // = 4
      case easeAscending // = 5
      case easeDescending // = 6
      case retrievabilityAscending // = 7
      case retrievabilityDescending // = 11
      case relativeOverdueness // = 12
      case random // = 8
      case added // = 9
      case reverseAdded // = 10
      case UNRECOGNIZED(Int)

      public init() {
        self = .day
      }

      public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .day
        case 1: self = .dayThenDeck
        case 2: self = .deckThenDay
        case 3: self = .intervalsAscending
        case 4: self = .intervalsDescending
        case 5: self = .easeAscending
        case 6: self = .easeDescending
        case 7: self = .retrievabilityAscending
        case 8: self = .random
        case 9: self = .added
        case 10: self = .reverseAdded
        case 11: self = .retrievabilityDescending
        case 12: self = .relativeOverdueness
        default: self = .UNRECOGNIZED(rawValue)
        }
      }

      public var rawValue: Int {
        switch self {
        case .day: return 0
        case .dayThenDeck: return 1
        case .deckThenDay: return 2
        case .intervalsAscending: return 3
        case .intervalsDescending: return 4
        case .easeAscending: return 5
        case .easeDescending: return 6
        case .retrievabilityAscending: return 7
        case .random: return 8
        case .added: return 9
        case .reverseAdded: return 10
        case .retrievabilityDescending: return 11
        case .relativeOverdueness: return 12
        case .UNRECOGNIZED(let i): return i
        }
      }

      // The compiler won't synthesize support with the UNRECOGNIZED case.
      public static let allCases: [Anki_DeckConfig_DeckConfig.Config.ReviewCardOrder] = [
        .day,
        .dayThenDeck,
        .deckThenDay,
        .intervalsAscending,
        .intervalsDescending,
        .easeAscending,
        .easeDescending,
        .retrievabilityAscending,
        .retrievabilityDescending,
        .relativeOverdueness,
        .random,
        .added,
        .reverseAdded,
      ]

    }

    public enum ReviewMix: SwiftProtobuf.Enum, Swift.CaseIterable {
      public typealias RawValue = Int
      case mixWithReviews // = 0
      case afterReviews // = 1
      case beforeReviews // = 2
      case UNRECOGNIZED(Int)

      public init() {
        self = .mixWithReviews
      }

      public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .mixWithReviews
        case 1: self = .afterReviews
        case 2: self = .beforeReviews
        default: self = .UNRECOGNIZED(rawValue)
        }
      }

      public var rawValue: Int {
        switch self {
        case .mixWithReviews: return 0
        case .afterReviews: return 1
        case .beforeReviews: return 2
        case .UNRECOGNIZED(let i): return i
        }
      }

      // The compiler won't synthesize support with the UNRECOGNIZED case.
      public static let allCases: [Anki_DeckConfig_DeckConfig.Config.ReviewMix] = [
        .mixWithReviews,
        .afterReviews,
        .beforeReviews,
      ]

    }

    public enum LeechAction: SwiftProtobuf.Enum, Swift.CaseIterable {
      public typealias RawValue = Int
      case suspend // = 0
      case tagOnly // = 1
      case UNRECOGNIZED(Int)

      public init() {
        self = .suspend
      }

      public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .suspend
        case 1: self = .tagOnly
        default: self = .UNRECOGNIZED(rawValue)
        }
      }

      public var rawValue: Int {
        switch self {
        case .suspend: return 0
        case .tagOnly: return 1
        case .UNRECOGNIZED(let i): return i
        }
      }

      // The compiler won't synthesize support with the UNRECOGNIZED case.
      public static let allCases: [Anki_DeckConfig_DeckConfig.Config.LeechAction] = [
        .suspend,
        .tagOnly,
      ]

    }

    public enum AnswerAction: SwiftProtobuf.Enum, Swift.CaseIterable {
      public typealias RawValue = Int
      case buryCard // = 0
      case answerAgain // = 1
      case answerGood // = 2
      case answerHard // = 3
      case showReminder // = 4
      case UNRECOGNIZED(Int)

      public init() {
        self = .buryCard
      }

      public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .buryCard
        case 1: self = .answerAgain
        case 2: self = .answerGood
        case 3: self = .answerHard
        case 4: self = .showReminder
        default: self = .UNRECOGNIZED(rawValue)
        }
      }

      public var rawValue: Int {
        switch self {
        case .buryCard: return 0
        case .answerAgain: return 1
        case .answerGood: return 2
        case .answerHard: return 3
        case .showReminder: return 4
        case .UNRECOGNIZED(let i): return i
        }
      }

      // The compiler won't synthesize support with the UNRECOGNIZED case.
      public static let allCases: [Anki_DeckConfig_DeckConfig.Config.AnswerAction] = [
        .buryCard,
        .answerAgain,
        .answerGood,
        .answerHard,
        .showReminder,
      ]

    }

    public enum QuestionAction: SwiftProtobuf.Enum, Swift.CaseIterable {
      public typealias RawValue = Int
      case showAnswer // = 0
      case showReminder // = 1
      case UNRECOGNIZED(Int)

      public init() {
        self = .showAnswer
      }

      public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .showAnswer
        case 1: self = .showReminder
        default: self = .UNRECOGNIZED(rawValue)
        }
      }

      public var rawValue: Int {
        switch self {
        case .showAnswer: return 0
        case .showReminder: return 1
        case .UNRECOGNIZED(let i): return i
        }
      }

      // The compiler won't synthesize support with the UNRECOGNIZED case.
      public static let allCases: [Anki_DeckConfig_DeckConfig.Config.QuestionAction] = [
        .showAnswer,
        .showReminder,
      ]

    }

    public init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
  }

  public init() {}

  fileprivate var _config: Anki_DeckConfig_DeckConfig.Config? = nil
}

public struct Anki_DeckConfig_DeckConfigsForUpdate: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var allConfig: [Anki_DeckConfig_DeckConfigsForUpdate.ConfigWithExtra] {
    get {return _storage._allConfig}
    set {_uniqueStorage()._allConfig = newValue}
  }

  public var currentDeck: Anki_DeckConfig_DeckConfigsForUpdate.CurrentDeck {
    get {return _storage._currentDeck ?? Anki_DeckConfig_DeckConfigsForUpdate.CurrentDeck()}
    set {_uniqueStorage()._currentDeck = newValue}
  }
  /// Returns true if `currentDeck` has been explicitly set.
  public var hasCurrentDeck: Bool {return _storage._currentDeck != nil}
  /// Clears the value of `currentDeck`. Subsequent reads from it will return its default value.
  public mutating func clearCurrentDeck() {_uniqueStorage()._currentDeck = nil}

  public var defaults: Anki_DeckConfig_DeckConfig {
    get {return _storage._defaults ?? Anki_DeckConfig_DeckConfig()}
    set {_uniqueStorage()._defaults = newValue}
  }
  /// Returns true if `defaults` has been explicitly set.
  public var hasDefaults: Bool {return _storage._defaults != nil}
  /// Clears the value of `defaults`. Subsequent reads from it will return its default value.
  public mutating func clearDefaults() {_uniqueStorage()._defaults = nil}

  public var schemaModified: Bool {
    get {return _storage._schemaModified}
    set {_uniqueStorage()._schemaModified = newValue}
  }

  /// only applies to v3 scheduler
  public var cardStateCustomizer: String {
    get {return _storage._cardStateCustomizer}
    set {_uniqueStorage()._cardStateCustomizer = newValue}
  }

  /// only applies to v3 scheduler
  public var newCardsIgnoreReviewLimit: Bool {
    get {return _storage._newCardsIgnoreReviewLimit}
    set {_uniqueStorage()._newCardsIgnoreReviewLimit = newValue}
  }

  public var fsrs: Bool {
    get {return _storage._fsrs}
    set {_uniqueStorage()._fsrs = newValue}
  }

  public var fsrsHealthCheck: Bool {
    get {return _storage._fsrsHealthCheck}
    set {_uniqueStorage()._fsrsHealthCheck = newValue}
  }

  public var fsrsLegacyEvaluate: Bool {
    get {return _storage._fsrsLegacyEvaluate}
    set {_uniqueStorage()._fsrsLegacyEvaluate = newValue}
  }

  public var applyAllParentLimits: Bool {
    get {return _storage._applyAllParentLimits}
    set {_uniqueStorage()._applyAllParentLimits = newValue}
  }

  public var daysSinceLastFsrsOptimize: UInt32 {
    get {return _storage._daysSinceLastFsrsOptimize}
    set {_uniqueStorage()._daysSinceLastFsrsOptimize = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public struct ConfigWithExtra: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var config: Anki_DeckConfig_DeckConfig {
      get {return _config ?? Anki_DeckConfig_DeckConfig()}
      set {_config = newValue}
    }
    /// Returns true if `config` has been explicitly set.
    public var hasConfig: Bool {return self._config != nil}
    /// Clears the value of `config`. Subsequent reads from it will return its default value.
    public mutating func clearConfig() {self._config = nil}

    public var useCount: UInt32 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _config: Anki_DeckConfig_DeckConfig? = nil
  }

  public struct CurrentDeck: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var name: String = String()

    public var configID: Int64 = 0

    public var parentConfigIds: [Int64] = []

    public var limits: Anki_DeckConfig_DeckConfigsForUpdate.CurrentDeck.Limits {
      get {return _limits ?? Anki_DeckConfig_DeckConfigsForUpdate.CurrentDeck.Limits()}
      set {_limits = newValue}
    }
    /// Returns true if `limits` has been explicitly set.
    public var hasLimits: Bool {return self._limits != nil}
    /// Clears the value of `limits`. Subsequent reads from it will return its default value.
    public mutating func clearLimits() {self._limits = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public struct Limits: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      public var review: UInt32 {
        get {return _review ?? 0}
        set {_review = newValue}
      }
      /// Returns true if `review` has been explicitly set.
      public var hasReview: Bool {return self._review != nil}
      /// Clears the value of `review`. Subsequent reads from it will return its default value.
      public mutating func clearReview() {self._review = nil}

      public var new: UInt32 {
        get {return _new ?? 0}
        set {_new = newValue}
      }
      /// Returns true if `new` has been explicitly set.
      public var hasNew: Bool {return self._new != nil}
      /// Clears the value of `new`. Subsequent reads from it will return its default value.
      public mutating func clearNew() {self._new = nil}

      public var reviewToday: UInt32 {
        get {return _reviewToday ?? 0}
        set {_reviewToday = newValue}
      }
      /// Returns true if `reviewToday` has been explicitly set.
      public var hasReviewToday: Bool {return self._reviewToday != nil}
      /// Clears the value of `reviewToday`. Subsequent reads from it will return its default value.
      public mutating func clearReviewToday() {self._reviewToday = nil}

      public var newToday: UInt32 {
        get {return _newToday ?? 0}
        set {_newToday = newValue}
      }
      /// Returns true if `newToday` has been explicitly set.
      public var hasNewToday: Bool {return self._newToday != nil}
      /// Clears the value of `newToday`. Subsequent reads from it will return its default value.
      public mutating func clearNewToday() {self._newToday = nil}

      /// Whether review_today applies to today or a past day.
      public var reviewTodayActive: Bool = false

      /// Whether new_today applies to today or a past day.
      public var newTodayActive: Bool = false

      /// Deck-specific desired retention override
      public var desiredRetention: Float {
        get {return _desiredRetention ?? 0}
        set {_desiredRetention = newValue}
      }
      /// Returns true if `desiredRetention` has been explicitly set.
      public var hasDesiredRetention: Bool {return self._desiredRetention != nil}
      /// Clears the value of `desiredRetention`. Subsequent reads from it will return its default value.
      public mutating func clearDesiredRetention() {self._desiredRetention = nil}

      public var unknownFields = SwiftProtobuf.UnknownStorage()

      public init() {}

      fileprivate var _review: UInt32? = nil
      fileprivate var _new: UInt32? = nil
      fileprivate var _reviewToday: UInt32? = nil
      fileprivate var _newToday: UInt32? = nil
      fileprivate var _desiredRetention: Float? = nil
    }

    public init() {}

    fileprivate var _limits: Anki_DeckConfig_DeckConfigsForUpdate.CurrentDeck.Limits? = nil
  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Anki_DeckConfig_UpdateDeckConfigsRequest: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var targetDeckID: Int64 {
    get {return _storage._targetDeckID}
    set {_uniqueStorage()._targetDeckID = newValue}
  }

  //// Unchanged, non-selected configs can be omitted. Deck will
  //// be set to whichever entry comes last.
  public var configs: [Anki_DeckConfig_DeckConfig] {
    get {return _storage._configs}
    set {_uniqueStorage()._configs = newValue}
  }

  public var removedConfigIds: [Int64] {
    get {return _storage._removedConfigIds}
    set {_uniqueStorage()._removedConfigIds = newValue}
  }

  public var mode: Anki_DeckConfig_UpdateDeckConfigsMode {
    get {return _storage._mode}
    set {_uniqueStorage()._mode = newValue}
  }

  public var cardStateCustomizer: String {
    get {return _storage._cardStateCustomizer}
    set {_uniqueStorage()._cardStateCustomizer = newValue}
  }

  public var limits: Anki_DeckConfig_DeckConfigsForUpdate.CurrentDeck.Limits {
    get {return _storage._limits ?? Anki_DeckConfig_DeckConfigsForUpdate.CurrentDeck.Limits()}
    set {_uniqueStorage()._limits = newValue}
  }
  /// Returns true if `limits` has been explicitly set.
  public var hasLimits: Bool {return _storage._limits != nil}
  /// Clears the value of `limits`. Subsequent reads from it will return its default value.
  public mutating func clearLimits() {_uniqueStorage()._limits = nil}

  public var newCardsIgnoreReviewLimit: Bool {
    get {return _storage._newCardsIgnoreReviewLimit}
    set {_uniqueStorage()._newCardsIgnoreReviewLimit = newValue}
  }

  public var fsrs: Bool {
    get {return _storage._fsrs}
    set {_uniqueStorage()._fsrs = newValue}
  }

  public var applyAllParentLimits: Bool {
    get {return _storage._applyAllParentLimits}
    set {_uniqueStorage()._applyAllParentLimits = newValue}
  }

  public var fsrsReschedule: Bool {
    get {return _storage._fsrsReschedule}
    set {_uniqueStorage()._fsrsReschedule = newValue}
  }

  public var fsrsHealthCheck: Bool {
    get {return _storage._fsrsHealthCheck}
    set {_uniqueStorage()._fsrsHealthCheck = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "anki.deck_config"

extension Anki_DeckConfig_UpdateDeckConfigsMode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UPDATE_DECK_CONFIGS_MODE_NORMAL"),
    1: .same(proto: "UPDATE_DECK_CONFIGS_MODE_APPLY_TO_CHILDREN"),
    2: .same(proto: "UPDATE_DECK_CONFIGS_MODE_COMPUTE_ALL_PARAMS"),
  ]
}

extension Anki_DeckConfig_DeckConfigId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeckConfigId"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "dcid"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.dcid) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.dcid != 0 {
      try visitor.visitSingularInt64Field(value: self.dcid, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_DeckConfig_DeckConfigId, rhs: Anki_DeckConfig_DeckConfigId) -> Bool {
    if lhs.dcid != rhs.dcid {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_DeckConfig_GetRetentionWorkloadRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetRetentionWorkloadRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "w"),
    2: .same(proto: "search"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedFloatField(value: &self.w) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.search) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.w.isEmpty {
      try visitor.visitPackedFloatField(value: self.w, fieldNumber: 1)
    }
    if !self.search.isEmpty {
      try visitor.visitSingularStringField(value: self.search, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_DeckConfig_GetRetentionWorkloadRequest, rhs: Anki_DeckConfig_GetRetentionWorkloadRequest) -> Bool {
    if lhs.w != rhs.w {return false}
    if lhs.search != rhs.search {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_DeckConfig_GetRetentionWorkloadResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetRetentionWorkloadResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "costs"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt32,SwiftProtobuf.ProtobufFloat>.self, value: &self.costs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.costs.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt32,SwiftProtobuf.ProtobufFloat>.self, value: self.costs, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_DeckConfig_GetRetentionWorkloadResponse, rhs: Anki_DeckConfig_GetRetentionWorkloadResponse) -> Bool {
    if lhs.costs != rhs.costs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_DeckConfig_GetIgnoredBeforeCountRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetIgnoredBeforeCountRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "ignore_revlogs_before_date"),
    2: .same(proto: "search"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.ignoreRevlogsBeforeDate) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.search) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.ignoreRevlogsBeforeDate.isEmpty {
      try visitor.visitSingularStringField(value: self.ignoreRevlogsBeforeDate, fieldNumber: 1)
    }
    if !self.search.isEmpty {
      try visitor.visitSingularStringField(value: self.search, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_DeckConfig_GetIgnoredBeforeCountRequest, rhs: Anki_DeckConfig_GetIgnoredBeforeCountRequest) -> Bool {
    if lhs.ignoreRevlogsBeforeDate != rhs.ignoreRevlogsBeforeDate {return false}
    if lhs.search != rhs.search {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_DeckConfig_GetIgnoredBeforeCountResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetIgnoredBeforeCountResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "included"),
    2: .same(proto: "total"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.included) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.total) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.included != 0 {
      try visitor.visitSingularUInt64Field(value: self.included, fieldNumber: 1)
    }
    if self.total != 0 {
      try visitor.visitSingularUInt64Field(value: self.total, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_DeckConfig_GetIgnoredBeforeCountResponse, rhs: Anki_DeckConfig_GetIgnoredBeforeCountResponse) -> Bool {
    if lhs.included != rhs.included {return false}
    if lhs.total != rhs.total {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_DeckConfig_DeckConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeckConfig"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "name"),
    3: .standard(proto: "mtime_secs"),
    4: .same(proto: "usn"),
    5: .same(proto: "config"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.mtimeSecs) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.usn) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._config) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.id != 0 {
      try visitor.visitSingularInt64Field(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if self.mtimeSecs != 0 {
      try visitor.visitSingularInt64Field(value: self.mtimeSecs, fieldNumber: 3)
    }
    if self.usn != 0 {
      try visitor.visitSingularInt32Field(value: self.usn, fieldNumber: 4)
    }
    try { if let v = self._config {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_DeckConfig_DeckConfig, rhs: Anki_DeckConfig_DeckConfig) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.mtimeSecs != rhs.mtimeSecs {return false}
    if lhs.usn != rhs.usn {return false}
    if lhs._config != rhs._config {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_DeckConfig_DeckConfig.Config: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Anki_DeckConfig_DeckConfig.protoMessageName + ".Config"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "learn_steps"),
    2: .standard(proto: "relearn_steps"),
    3: .standard(proto: "fsrs_params_4"),
    5: .standard(proto: "fsrs_params_5"),
    6: .standard(proto: "fsrs_params_6"),
    9: .standard(proto: "new_per_day"),
    10: .standard(proto: "reviews_per_day"),
    35: .standard(proto: "new_per_day_minimum"),
    11: .standard(proto: "initial_ease"),
    12: .standard(proto: "easy_multiplier"),
    13: .standard(proto: "hard_multiplier"),
    14: .standard(proto: "lapse_multiplier"),
    15: .standard(proto: "interval_multiplier"),
    16: .standard(proto: "maximum_review_interval"),
    17: .standard(proto: "minimum_lapse_interval"),
    18: .standard(proto: "graduating_interval_good"),
    19: .standard(proto: "graduating_interval_easy"),
    20: .standard(proto: "new_card_insert_order"),
    34: .standard(proto: "new_card_gather_priority"),
    32: .standard(proto: "new_card_sort_order"),
    30: .standard(proto: "new_mix"),
    33: .standard(proto: "review_order"),
    31: .standard(proto: "interday_learning_mix"),
    21: .standard(proto: "leech_action"),
    22: .standard(proto: "leech_threshold"),
    23: .standard(proto: "disable_autoplay"),
    24: .standard(proto: "cap_answer_time_to_secs"),
    25: .standard(proto: "show_timer"),
    38: .standard(proto: "stop_timer_on_answer"),
    41: .standard(proto: "seconds_to_show_question"),
    42: .standard(proto: "seconds_to_show_answer"),
    36: .standard(proto: "question_action"),
    43: .standard(proto: "answer_action"),
    44: .standard(proto: "wait_for_audio"),
    26: .standard(proto: "skip_question_when_replaying_answer"),
    27: .standard(proto: "bury_new"),
    28: .standard(proto: "bury_reviews"),
    29: .standard(proto: "bury_interday_learning"),
    37: .standard(proto: "desired_retention"),
    46: .standard(proto: "ignore_revlogs_before_date"),
    4: .standard(proto: "easy_days_percentages"),
    40: .standard(proto: "historical_retention"),
    45: .standard(proto: "param_search"),
    255: .same(proto: "other"),
  ]

  fileprivate class _StorageClass {
    var _learnSteps: [Float] = []
    var _relearnSteps: [Float] = []
    var _fsrsParams4: [Float] = []
    var _fsrsParams5: [Float] = []
    var _fsrsParams6: [Float] = []
    var _newPerDay: UInt32 = 0
    var _reviewsPerDay: UInt32 = 0
    var _newPerDayMinimum: UInt32 = 0
    var _initialEase: Float = 0
    var _easyMultiplier: Float = 0
    var _hardMultiplier: Float = 0
    var _lapseMultiplier: Float = 0
    var _intervalMultiplier: Float = 0
    var _maximumReviewInterval: UInt32 = 0
    var _minimumLapseInterval: UInt32 = 0
    var _graduatingIntervalGood: UInt32 = 0
    var _graduatingIntervalEasy: UInt32 = 0
    var _newCardInsertOrder: Anki_DeckConfig_DeckConfig.Config.NewCardInsertOrder = .due
    var _newCardGatherPriority: Anki_DeckConfig_DeckConfig.Config.NewCardGatherPriority = .deck
    var _newCardSortOrder: Anki_DeckConfig_DeckConfig.Config.NewCardSortOrder = .template
    var _newMix: Anki_DeckConfig_DeckConfig.Config.ReviewMix = .mixWithReviews
    var _reviewOrder: Anki_DeckConfig_DeckConfig.Config.ReviewCardOrder = .day
    var _interdayLearningMix: Anki_DeckConfig_DeckConfig.Config.ReviewMix = .mixWithReviews
    var _leechAction: Anki_DeckConfig_DeckConfig.Config.LeechAction = .suspend
    var _leechThreshold: UInt32 = 0
    var _disableAutoplay: Bool = false
    var _capAnswerTimeToSecs: UInt32 = 0
    var _showTimer: Bool = false
    var _stopTimerOnAnswer: Bool = false
    var _secondsToShowQuestion: Float = 0
    var _secondsToShowAnswer: Float = 0
    var _questionAction: Anki_DeckConfig_DeckConfig.Config.QuestionAction = .showAnswer
    var _answerAction: Anki_DeckConfig_DeckConfig.Config.AnswerAction = .buryCard
    var _waitForAudio: Bool = false
    var _skipQuestionWhenReplayingAnswer: Bool = false
    var _buryNew: Bool = false
    var _buryReviews: Bool = false
    var _buryInterdayLearning: Bool = false
    var _desiredRetention: Float = 0
    var _ignoreRevlogsBeforeDate: String = String()
    var _easyDaysPercentages: [Float] = []
    var _historicalRetention: Float = 0
    var _paramSearch: String = String()
    var _other: Data = Data()

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _learnSteps = source._learnSteps
      _relearnSteps = source._relearnSteps
      _fsrsParams4 = source._fsrsParams4
      _fsrsParams5 = source._fsrsParams5
      _fsrsParams6 = source._fsrsParams6
      _newPerDay = source._newPerDay
      _reviewsPerDay = source._reviewsPerDay
      _newPerDayMinimum = source._newPerDayMinimum
      _initialEase = source._initialEase
      _easyMultiplier = source._easyMultiplier
      _hardMultiplier = source._hardMultiplier
      _lapseMultiplier = source._lapseMultiplier
      _intervalMultiplier = source._intervalMultiplier
      _maximumReviewInterval = source._maximumReviewInterval
      _minimumLapseInterval = source._minimumLapseInterval
      _graduatingIntervalGood = source._graduatingIntervalGood
      _graduatingIntervalEasy = source._graduatingIntervalEasy
      _newCardInsertOrder = source._newCardInsertOrder
      _newCardGatherPriority = source._newCardGatherPriority
      _newCardSortOrder = source._newCardSortOrder
      _newMix = source._newMix
      _reviewOrder = source._reviewOrder
      _interdayLearningMix = source._interdayLearningMix
      _leechAction = source._leechAction
      _leechThreshold = source._leechThreshold
      _disableAutoplay = source._disableAutoplay
      _capAnswerTimeToSecs = source._capAnswerTimeToSecs
      _showTimer = source._showTimer
      _stopTimerOnAnswer = source._stopTimerOnAnswer
      _secondsToShowQuestion = source._secondsToShowQuestion
      _secondsToShowAnswer = source._secondsToShowAnswer
      _questionAction = source._questionAction
      _answerAction = source._answerAction
      _waitForAudio = source._waitForAudio
      _skipQuestionWhenReplayingAnswer = source._skipQuestionWhenReplayingAnswer
      _buryNew = source._buryNew
      _buryReviews = source._buryReviews
      _buryInterdayLearning = source._buryInterdayLearning
      _desiredRetention = source._desiredRetention
      _ignoreRevlogsBeforeDate = source._ignoreRevlogsBeforeDate
      _easyDaysPercentages = source._easyDaysPercentages
      _historicalRetention = source._historicalRetention
      _paramSearch = source._paramSearch
      _other = source._other
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeRepeatedFloatField(value: &_storage._learnSteps) }()
        case 2: try { try decoder.decodeRepeatedFloatField(value: &_storage._relearnSteps) }()
        case 3: try { try decoder.decodeRepeatedFloatField(value: &_storage._fsrsParams4) }()
        case 4: try { try decoder.decodeRepeatedFloatField(value: &_storage._easyDaysPercentages) }()
        case 5: try { try decoder.decodeRepeatedFloatField(value: &_storage._fsrsParams5) }()
        case 6: try { try decoder.decodeRepeatedFloatField(value: &_storage._fsrsParams6) }()
        case 9: try { try decoder.decodeSingularUInt32Field(value: &_storage._newPerDay) }()
        case 10: try { try decoder.decodeSingularUInt32Field(value: &_storage._reviewsPerDay) }()
        case 11: try { try decoder.decodeSingularFloatField(value: &_storage._initialEase) }()
        case 12: try { try decoder.decodeSingularFloatField(value: &_storage._easyMultiplier) }()
        case 13: try { try decoder.decodeSingularFloatField(value: &_storage._hardMultiplier) }()
        case 14: try { try decoder.decodeSingularFloatField(value: &_storage._lapseMultiplier) }()
        case 15: try { try decoder.decodeSingularFloatField(value: &_storage._intervalMultiplier) }()
        case 16: try { try decoder.decodeSingularUInt32Field(value: &_storage._maximumReviewInterval) }()
        case 17: try { try decoder.decodeSingularUInt32Field(value: &_storage._minimumLapseInterval) }()
        case 18: try { try decoder.decodeSingularUInt32Field(value: &_storage._graduatingIntervalGood) }()
        case 19: try { try decoder.decodeSingularUInt32Field(value: &_storage._graduatingIntervalEasy) }()
        case 20: try { try decoder.decodeSingularEnumField(value: &_storage._newCardInsertOrder) }()
        case 21: try { try decoder.decodeSingularEnumField(value: &_storage._leechAction) }()
        case 22: try { try decoder.decodeSingularUInt32Field(value: &_storage._leechThreshold) }()
        case 23: try { try decoder.decodeSingularBoolField(value: &_storage._disableAutoplay) }()
        case 24: try { try decoder.decodeSingularUInt32Field(value: &_storage._capAnswerTimeToSecs) }()
        case 25: try { try decoder.decodeSingularBoolField(value: &_storage._showTimer) }()
        case 26: try { try decoder.decodeSingularBoolField(value: &_storage._skipQuestionWhenReplayingAnswer) }()
        case 27: try { try decoder.decodeSingularBoolField(value: &_storage._buryNew) }()
        case 28: try { try decoder.decodeSingularBoolField(value: &_storage._buryReviews) }()
        case 29: try { try decoder.decodeSingularBoolField(value: &_storage._buryInterdayLearning) }()
        case 30: try { try decoder.decodeSingularEnumField(value: &_storage._newMix) }()
        case 31: try { try decoder.decodeSingularEnumField(value: &_storage._interdayLearningMix) }()
        case 32: try { try decoder.decodeSingularEnumField(value: &_storage._newCardSortOrder) }()
        case 33: try { try decoder.decodeSingularEnumField(value: &_storage._reviewOrder) }()
        case 34: try { try decoder.decodeSingularEnumField(value: &_storage._newCardGatherPriority) }()
        case 35: try { try decoder.decodeSingularUInt32Field(value: &_storage._newPerDayMinimum) }()
        case 36: try { try decoder.decodeSingularEnumField(value: &_storage._questionAction) }()
        case 37: try { try decoder.decodeSingularFloatField(value: &_storage._desiredRetention) }()
        case 38: try { try decoder.decodeSingularBoolField(value: &_storage._stopTimerOnAnswer) }()
        case 40: try { try decoder.decodeSingularFloatField(value: &_storage._historicalRetention) }()
        case 41: try { try decoder.decodeSingularFloatField(value: &_storage._secondsToShowQuestion) }()
        case 42: try { try decoder.decodeSingularFloatField(value: &_storage._secondsToShowAnswer) }()
        case 43: try { try decoder.decodeSingularEnumField(value: &_storage._answerAction) }()
        case 44: try { try decoder.decodeSingularBoolField(value: &_storage._waitForAudio) }()
        case 45: try { try decoder.decodeSingularStringField(value: &_storage._paramSearch) }()
        case 46: try { try decoder.decodeSingularStringField(value: &_storage._ignoreRevlogsBeforeDate) }()
        case 255: try { try decoder.decodeSingularBytesField(value: &_storage._other) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._learnSteps.isEmpty {
        try visitor.visitPackedFloatField(value: _storage._learnSteps, fieldNumber: 1)
      }
      if !_storage._relearnSteps.isEmpty {
        try visitor.visitPackedFloatField(value: _storage._relearnSteps, fieldNumber: 2)
      }
      if !_storage._fsrsParams4.isEmpty {
        try visitor.visitPackedFloatField(value: _storage._fsrsParams4, fieldNumber: 3)
      }
      if !_storage._easyDaysPercentages.isEmpty {
        try visitor.visitPackedFloatField(value: _storage._easyDaysPercentages, fieldNumber: 4)
      }
      if !_storage._fsrsParams5.isEmpty {
        try visitor.visitPackedFloatField(value: _storage._fsrsParams5, fieldNumber: 5)
      }
      if !_storage._fsrsParams6.isEmpty {
        try visitor.visitPackedFloatField(value: _storage._fsrsParams6, fieldNumber: 6)
      }
      if _storage._newPerDay != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._newPerDay, fieldNumber: 9)
      }
      if _storage._reviewsPerDay != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._reviewsPerDay, fieldNumber: 10)
      }
      if _storage._initialEase.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._initialEase, fieldNumber: 11)
      }
      if _storage._easyMultiplier.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._easyMultiplier, fieldNumber: 12)
      }
      if _storage._hardMultiplier.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._hardMultiplier, fieldNumber: 13)
      }
      if _storage._lapseMultiplier.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._lapseMultiplier, fieldNumber: 14)
      }
      if _storage._intervalMultiplier.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._intervalMultiplier, fieldNumber: 15)
      }
      if _storage._maximumReviewInterval != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._maximumReviewInterval, fieldNumber: 16)
      }
      if _storage._minimumLapseInterval != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._minimumLapseInterval, fieldNumber: 17)
      }
      if _storage._graduatingIntervalGood != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._graduatingIntervalGood, fieldNumber: 18)
      }
      if _storage._graduatingIntervalEasy != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._graduatingIntervalEasy, fieldNumber: 19)
      }
      if _storage._newCardInsertOrder != .due {
        try visitor.visitSingularEnumField(value: _storage._newCardInsertOrder, fieldNumber: 20)
      }
      if _storage._leechAction != .suspend {
        try visitor.visitSingularEnumField(value: _storage._leechAction, fieldNumber: 21)
      }
      if _storage._leechThreshold != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._leechThreshold, fieldNumber: 22)
      }
      if _storage._disableAutoplay != false {
        try visitor.visitSingularBoolField(value: _storage._disableAutoplay, fieldNumber: 23)
      }
      if _storage._capAnswerTimeToSecs != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._capAnswerTimeToSecs, fieldNumber: 24)
      }
      if _storage._showTimer != false {
        try visitor.visitSingularBoolField(value: _storage._showTimer, fieldNumber: 25)
      }
      if _storage._skipQuestionWhenReplayingAnswer != false {
        try visitor.visitSingularBoolField(value: _storage._skipQuestionWhenReplayingAnswer, fieldNumber: 26)
      }
      if _storage._buryNew != false {
        try visitor.visitSingularBoolField(value: _storage._buryNew, fieldNumber: 27)
      }
      if _storage._buryReviews != false {
        try visitor.visitSingularBoolField(value: _storage._buryReviews, fieldNumber: 28)
      }
      if _storage._buryInterdayLearning != false {
        try visitor.visitSingularBoolField(value: _storage._buryInterdayLearning, fieldNumber: 29)
      }
      if _storage._newMix != .mixWithReviews {
        try visitor.visitSingularEnumField(value: _storage._newMix, fieldNumber: 30)
      }
      if _storage._interdayLearningMix != .mixWithReviews {
        try visitor.visitSingularEnumField(value: _storage._interdayLearningMix, fieldNumber: 31)
      }
      if _storage._newCardSortOrder != .template {
        try visitor.visitSingularEnumField(value: _storage._newCardSortOrder, fieldNumber: 32)
      }
      if _storage._reviewOrder != .day {
        try visitor.visitSingularEnumField(value: _storage._reviewOrder, fieldNumber: 33)
      }
      if _storage._newCardGatherPriority != .deck {
        try visitor.visitSingularEnumField(value: _storage._newCardGatherPriority, fieldNumber: 34)
      }
      if _storage._newPerDayMinimum != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._newPerDayMinimum, fieldNumber: 35)
      }
      if _storage._questionAction != .showAnswer {
        try visitor.visitSingularEnumField(value: _storage._questionAction, fieldNumber: 36)
      }
      if _storage._desiredRetention.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._desiredRetention, fieldNumber: 37)
      }
      if _storage._stopTimerOnAnswer != false {
        try visitor.visitSingularBoolField(value: _storage._stopTimerOnAnswer, fieldNumber: 38)
      }
      if _storage._historicalRetention.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._historicalRetention, fieldNumber: 40)
      }
      if _storage._secondsToShowQuestion.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._secondsToShowQuestion, fieldNumber: 41)
      }
      if _storage._secondsToShowAnswer.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._secondsToShowAnswer, fieldNumber: 42)
      }
      if _storage._answerAction != .buryCard {
        try visitor.visitSingularEnumField(value: _storage._answerAction, fieldNumber: 43)
      }
      if _storage._waitForAudio != false {
        try visitor.visitSingularBoolField(value: _storage._waitForAudio, fieldNumber: 44)
      }
      if !_storage._paramSearch.isEmpty {
        try visitor.visitSingularStringField(value: _storage._paramSearch, fieldNumber: 45)
      }
      if !_storage._ignoreRevlogsBeforeDate.isEmpty {
        try visitor.visitSingularStringField(value: _storage._ignoreRevlogsBeforeDate, fieldNumber: 46)
      }
      if !_storage._other.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._other, fieldNumber: 255)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_DeckConfig_DeckConfig.Config, rhs: Anki_DeckConfig_DeckConfig.Config) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._learnSteps != rhs_storage._learnSteps {return false}
        if _storage._relearnSteps != rhs_storage._relearnSteps {return false}
        if _storage._fsrsParams4 != rhs_storage._fsrsParams4 {return false}
        if _storage._fsrsParams5 != rhs_storage._fsrsParams5 {return false}
        if _storage._fsrsParams6 != rhs_storage._fsrsParams6 {return false}
        if _storage._newPerDay != rhs_storage._newPerDay {return false}
        if _storage._reviewsPerDay != rhs_storage._reviewsPerDay {return false}
        if _storage._newPerDayMinimum != rhs_storage._newPerDayMinimum {return false}
        if _storage._initialEase != rhs_storage._initialEase {return false}
        if _storage._easyMultiplier != rhs_storage._easyMultiplier {return false}
        if _storage._hardMultiplier != rhs_storage._hardMultiplier {return false}
        if _storage._lapseMultiplier != rhs_storage._lapseMultiplier {return false}
        if _storage._intervalMultiplier != rhs_storage._intervalMultiplier {return false}
        if _storage._maximumReviewInterval != rhs_storage._maximumReviewInterval {return false}
        if _storage._minimumLapseInterval != rhs_storage._minimumLapseInterval {return false}
        if _storage._graduatingIntervalGood != rhs_storage._graduatingIntervalGood {return false}
        if _storage._graduatingIntervalEasy != rhs_storage._graduatingIntervalEasy {return false}
        if _storage._newCardInsertOrder != rhs_storage._newCardInsertOrder {return false}
        if _storage._newCardGatherPriority != rhs_storage._newCardGatherPriority {return false}
        if _storage._newCardSortOrder != rhs_storage._newCardSortOrder {return false}
        if _storage._newMix != rhs_storage._newMix {return false}
        if _storage._reviewOrder != rhs_storage._reviewOrder {return false}
        if _storage._interdayLearningMix != rhs_storage._interdayLearningMix {return false}
        if _storage._leechAction != rhs_storage._leechAction {return false}
        if _storage._leechThreshold != rhs_storage._leechThreshold {return false}
        if _storage._disableAutoplay != rhs_storage._disableAutoplay {return false}
        if _storage._capAnswerTimeToSecs != rhs_storage._capAnswerTimeToSecs {return false}
        if _storage._showTimer != rhs_storage._showTimer {return false}
        if _storage._stopTimerOnAnswer != rhs_storage._stopTimerOnAnswer {return false}
        if _storage._secondsToShowQuestion != rhs_storage._secondsToShowQuestion {return false}
        if _storage._secondsToShowAnswer != rhs_storage._secondsToShowAnswer {return false}
        if _storage._questionAction != rhs_storage._questionAction {return false}
        if _storage._answerAction != rhs_storage._answerAction {return false}
        if _storage._waitForAudio != rhs_storage._waitForAudio {return false}
        if _storage._skipQuestionWhenReplayingAnswer != rhs_storage._skipQuestionWhenReplayingAnswer {return false}
        if _storage._buryNew != rhs_storage._buryNew {return false}
        if _storage._buryReviews != rhs_storage._buryReviews {return false}
        if _storage._buryInterdayLearning != rhs_storage._buryInterdayLearning {return false}
        if _storage._desiredRetention != rhs_storage._desiredRetention {return false}
        if _storage._ignoreRevlogsBeforeDate != rhs_storage._ignoreRevlogsBeforeDate {return false}
        if _storage._easyDaysPercentages != rhs_storage._easyDaysPercentages {return false}
        if _storage._historicalRetention != rhs_storage._historicalRetention {return false}
        if _storage._paramSearch != rhs_storage._paramSearch {return false}
        if _storage._other != rhs_storage._other {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_DeckConfig_DeckConfig.Config.NewCardInsertOrder: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "NEW_CARD_INSERT_ORDER_DUE"),
    1: .same(proto: "NEW_CARD_INSERT_ORDER_RANDOM"),
  ]
}

extension Anki_DeckConfig_DeckConfig.Config.NewCardGatherPriority: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "NEW_CARD_GATHER_PRIORITY_DECK"),
    1: .same(proto: "NEW_CARD_GATHER_PRIORITY_LOWEST_POSITION"),
    2: .same(proto: "NEW_CARD_GATHER_PRIORITY_HIGHEST_POSITION"),
    3: .same(proto: "NEW_CARD_GATHER_PRIORITY_RANDOM_NOTES"),
    4: .same(proto: "NEW_CARD_GATHER_PRIORITY_RANDOM_CARDS"),
    5: .same(proto: "NEW_CARD_GATHER_PRIORITY_DECK_THEN_RANDOM_NOTES"),
  ]
}

extension Anki_DeckConfig_DeckConfig.Config.NewCardSortOrder: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "NEW_CARD_SORT_ORDER_TEMPLATE"),
    1: .same(proto: "NEW_CARD_SORT_ORDER_NO_SORT"),
    2: .same(proto: "NEW_CARD_SORT_ORDER_TEMPLATE_THEN_RANDOM"),
    3: .same(proto: "NEW_CARD_SORT_ORDER_RANDOM_NOTE_THEN_TEMPLATE"),
    4: .same(proto: "NEW_CARD_SORT_ORDER_RANDOM_CARD"),
  ]
}

extension Anki_DeckConfig_DeckConfig.Config.ReviewCardOrder: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "REVIEW_CARD_ORDER_DAY"),
    1: .same(proto: "REVIEW_CARD_ORDER_DAY_THEN_DECK"),
    2: .same(proto: "REVIEW_CARD_ORDER_DECK_THEN_DAY"),
    3: .same(proto: "REVIEW_CARD_ORDER_INTERVALS_ASCENDING"),
    4: .same(proto: "REVIEW_CARD_ORDER_INTERVALS_DESCENDING"),
    5: .same(proto: "REVIEW_CARD_ORDER_EASE_ASCENDING"),
    6: .same(proto: "REVIEW_CARD_ORDER_EASE_DESCENDING"),
    7: .same(proto: "REVIEW_CARD_ORDER_RETRIEVABILITY_ASCENDING"),
    8: .same(proto: "REVIEW_CARD_ORDER_RANDOM"),
    9: .same(proto: "REVIEW_CARD_ORDER_ADDED"),
    10: .same(proto: "REVIEW_CARD_ORDER_REVERSE_ADDED"),
    11: .same(proto: "REVIEW_CARD_ORDER_RETRIEVABILITY_DESCENDING"),
    12: .same(proto: "REVIEW_CARD_ORDER_RELATIVE_OVERDUENESS"),
  ]
}

extension Anki_DeckConfig_DeckConfig.Config.ReviewMix: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "REVIEW_MIX_MIX_WITH_REVIEWS"),
    1: .same(proto: "REVIEW_MIX_AFTER_REVIEWS"),
    2: .same(proto: "REVIEW_MIX_BEFORE_REVIEWS"),
  ]
}

extension Anki_DeckConfig_DeckConfig.Config.LeechAction: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "LEECH_ACTION_SUSPEND"),
    1: .same(proto: "LEECH_ACTION_TAG_ONLY"),
  ]
}

extension Anki_DeckConfig_DeckConfig.Config.AnswerAction: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "ANSWER_ACTION_BURY_CARD"),
    1: .same(proto: "ANSWER_ACTION_ANSWER_AGAIN"),
    2: .same(proto: "ANSWER_ACTION_ANSWER_GOOD"),
    3: .same(proto: "ANSWER_ACTION_ANSWER_HARD"),
    4: .same(proto: "ANSWER_ACTION_SHOW_REMINDER"),
  ]
}

extension Anki_DeckConfig_DeckConfig.Config.QuestionAction: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "QUESTION_ACTION_SHOW_ANSWER"),
    1: .same(proto: "QUESTION_ACTION_SHOW_REMINDER"),
  ]
}

extension Anki_DeckConfig_DeckConfigsForUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeckConfigsForUpdate"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "all_config"),
    2: .standard(proto: "current_deck"),
    3: .same(proto: "defaults"),
    4: .standard(proto: "schema_modified"),
    6: .standard(proto: "card_state_customizer"),
    7: .standard(proto: "new_cards_ignore_review_limit"),
    8: .same(proto: "fsrs"),
    11: .standard(proto: "fsrs_health_check"),
    12: .standard(proto: "fsrs_legacy_evaluate"),
    9: .standard(proto: "apply_all_parent_limits"),
    10: .standard(proto: "days_since_last_fsrs_optimize"),
  ]

  fileprivate class _StorageClass {
    var _allConfig: [Anki_DeckConfig_DeckConfigsForUpdate.ConfigWithExtra] = []
    var _currentDeck: Anki_DeckConfig_DeckConfigsForUpdate.CurrentDeck? = nil
    var _defaults: Anki_DeckConfig_DeckConfig? = nil
    var _schemaModified: Bool = false
    var _cardStateCustomizer: String = String()
    var _newCardsIgnoreReviewLimit: Bool = false
    var _fsrs: Bool = false
    var _fsrsHealthCheck: Bool = false
    var _fsrsLegacyEvaluate: Bool = false
    var _applyAllParentLimits: Bool = false
    var _daysSinceLastFsrsOptimize: UInt32 = 0

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _allConfig = source._allConfig
      _currentDeck = source._currentDeck
      _defaults = source._defaults
      _schemaModified = source._schemaModified
      _cardStateCustomizer = source._cardStateCustomizer
      _newCardsIgnoreReviewLimit = source._newCardsIgnoreReviewLimit
      _fsrs = source._fsrs
      _fsrsHealthCheck = source._fsrsHealthCheck
      _fsrsLegacyEvaluate = source._fsrsLegacyEvaluate
      _applyAllParentLimits = source._applyAllParentLimits
      _daysSinceLastFsrsOptimize = source._daysSinceLastFsrsOptimize
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeRepeatedMessageField(value: &_storage._allConfig) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._currentDeck) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._defaults) }()
        case 4: try { try decoder.decodeSingularBoolField(value: &_storage._schemaModified) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._cardStateCustomizer) }()
        case 7: try { try decoder.decodeSingularBoolField(value: &_storage._newCardsIgnoreReviewLimit) }()
        case 8: try { try decoder.decodeSingularBoolField(value: &_storage._fsrs) }()
        case 9: try { try decoder.decodeSingularBoolField(value: &_storage._applyAllParentLimits) }()
        case 10: try { try decoder.decodeSingularUInt32Field(value: &_storage._daysSinceLastFsrsOptimize) }()
        case 11: try { try decoder.decodeSingularBoolField(value: &_storage._fsrsHealthCheck) }()
        case 12: try { try decoder.decodeSingularBoolField(value: &_storage._fsrsLegacyEvaluate) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._allConfig.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._allConfig, fieldNumber: 1)
      }
      try { if let v = _storage._currentDeck {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._defaults {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      if _storage._schemaModified != false {
        try visitor.visitSingularBoolField(value: _storage._schemaModified, fieldNumber: 4)
      }
      if !_storage._cardStateCustomizer.isEmpty {
        try visitor.visitSingularStringField(value: _storage._cardStateCustomizer, fieldNumber: 6)
      }
      if _storage._newCardsIgnoreReviewLimit != false {
        try visitor.visitSingularBoolField(value: _storage._newCardsIgnoreReviewLimit, fieldNumber: 7)
      }
      if _storage._fsrs != false {
        try visitor.visitSingularBoolField(value: _storage._fsrs, fieldNumber: 8)
      }
      if _storage._applyAllParentLimits != false {
        try visitor.visitSingularBoolField(value: _storage._applyAllParentLimits, fieldNumber: 9)
      }
      if _storage._daysSinceLastFsrsOptimize != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._daysSinceLastFsrsOptimize, fieldNumber: 10)
      }
      if _storage._fsrsHealthCheck != false {
        try visitor.visitSingularBoolField(value: _storage._fsrsHealthCheck, fieldNumber: 11)
      }
      if _storage._fsrsLegacyEvaluate != false {
        try visitor.visitSingularBoolField(value: _storage._fsrsLegacyEvaluate, fieldNumber: 12)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_DeckConfig_DeckConfigsForUpdate, rhs: Anki_DeckConfig_DeckConfigsForUpdate) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._allConfig != rhs_storage._allConfig {return false}
        if _storage._currentDeck != rhs_storage._currentDeck {return false}
        if _storage._defaults != rhs_storage._defaults {return false}
        if _storage._schemaModified != rhs_storage._schemaModified {return false}
        if _storage._cardStateCustomizer != rhs_storage._cardStateCustomizer {return false}
        if _storage._newCardsIgnoreReviewLimit != rhs_storage._newCardsIgnoreReviewLimit {return false}
        if _storage._fsrs != rhs_storage._fsrs {return false}
        if _storage._fsrsHealthCheck != rhs_storage._fsrsHealthCheck {return false}
        if _storage._fsrsLegacyEvaluate != rhs_storage._fsrsLegacyEvaluate {return false}
        if _storage._applyAllParentLimits != rhs_storage._applyAllParentLimits {return false}
        if _storage._daysSinceLastFsrsOptimize != rhs_storage._daysSinceLastFsrsOptimize {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_DeckConfig_DeckConfigsForUpdate.ConfigWithExtra: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Anki_DeckConfig_DeckConfigsForUpdate.protoMessageName + ".ConfigWithExtra"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "config"),
    2: .standard(proto: "use_count"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._config) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.useCount) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._config {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.useCount != 0 {
      try visitor.visitSingularUInt32Field(value: self.useCount, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_DeckConfig_DeckConfigsForUpdate.ConfigWithExtra, rhs: Anki_DeckConfig_DeckConfigsForUpdate.ConfigWithExtra) -> Bool {
    if lhs._config != rhs._config {return false}
    if lhs.useCount != rhs.useCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_DeckConfig_DeckConfigsForUpdate.CurrentDeck: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Anki_DeckConfig_DeckConfigsForUpdate.protoMessageName + ".CurrentDeck"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "name"),
    2: .standard(proto: "config_id"),
    3: .standard(proto: "parent_config_ids"),
    4: .same(proto: "limits"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.configID) }()
      case 3: try { try decoder.decodeRepeatedInt64Field(value: &self.parentConfigIds) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._limits) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.configID != 0 {
      try visitor.visitSingularInt64Field(value: self.configID, fieldNumber: 2)
    }
    if !self.parentConfigIds.isEmpty {
      try visitor.visitPackedInt64Field(value: self.parentConfigIds, fieldNumber: 3)
    }
    try { if let v = self._limits {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_DeckConfig_DeckConfigsForUpdate.CurrentDeck, rhs: Anki_DeckConfig_DeckConfigsForUpdate.CurrentDeck) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.configID != rhs.configID {return false}
    if lhs.parentConfigIds != rhs.parentConfigIds {return false}
    if lhs._limits != rhs._limits {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_DeckConfig_DeckConfigsForUpdate.CurrentDeck.Limits: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Anki_DeckConfig_DeckConfigsForUpdate.CurrentDeck.protoMessageName + ".Limits"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "review"),
    2: .same(proto: "new"),
    3: .standard(proto: "review_today"),
    4: .standard(proto: "new_today"),
    5: .standard(proto: "review_today_active"),
    6: .standard(proto: "new_today_active"),
    7: .standard(proto: "desired_retention"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._review) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self._new) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self._reviewToday) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self._newToday) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.reviewTodayActive) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.newTodayActive) }()
      case 7: try { try decoder.decodeSingularFloatField(value: &self._desiredRetention) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._review {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._new {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._reviewToday {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._newToday {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 4)
    } }()
    if self.reviewTodayActive != false {
      try visitor.visitSingularBoolField(value: self.reviewTodayActive, fieldNumber: 5)
    }
    if self.newTodayActive != false {
      try visitor.visitSingularBoolField(value: self.newTodayActive, fieldNumber: 6)
    }
    try { if let v = self._desiredRetention {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_DeckConfig_DeckConfigsForUpdate.CurrentDeck.Limits, rhs: Anki_DeckConfig_DeckConfigsForUpdate.CurrentDeck.Limits) -> Bool {
    if lhs._review != rhs._review {return false}
    if lhs._new != rhs._new {return false}
    if lhs._reviewToday != rhs._reviewToday {return false}
    if lhs._newToday != rhs._newToday {return false}
    if lhs.reviewTodayActive != rhs.reviewTodayActive {return false}
    if lhs.newTodayActive != rhs.newTodayActive {return false}
    if lhs._desiredRetention != rhs._desiredRetention {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_DeckConfig_UpdateDeckConfigsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UpdateDeckConfigsRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "target_deck_id"),
    2: .same(proto: "configs"),
    3: .standard(proto: "removed_config_ids"),
    4: .same(proto: "mode"),
    5: .standard(proto: "card_state_customizer"),
    6: .same(proto: "limits"),
    7: .standard(proto: "new_cards_ignore_review_limit"),
    8: .same(proto: "fsrs"),
    9: .standard(proto: "apply_all_parent_limits"),
    10: .standard(proto: "fsrs_reschedule"),
    11: .standard(proto: "fsrs_health_check"),
  ]

  fileprivate class _StorageClass {
    var _targetDeckID: Int64 = 0
    var _configs: [Anki_DeckConfig_DeckConfig] = []
    var _removedConfigIds: [Int64] = []
    var _mode: Anki_DeckConfig_UpdateDeckConfigsMode = .normal
    var _cardStateCustomizer: String = String()
    var _limits: Anki_DeckConfig_DeckConfigsForUpdate.CurrentDeck.Limits? = nil
    var _newCardsIgnoreReviewLimit: Bool = false
    var _fsrs: Bool = false
    var _applyAllParentLimits: Bool = false
    var _fsrsReschedule: Bool = false
    var _fsrsHealthCheck: Bool = false

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _targetDeckID = source._targetDeckID
      _configs = source._configs
      _removedConfigIds = source._removedConfigIds
      _mode = source._mode
      _cardStateCustomizer = source._cardStateCustomizer
      _limits = source._limits
      _newCardsIgnoreReviewLimit = source._newCardsIgnoreReviewLimit
      _fsrs = source._fsrs
      _applyAllParentLimits = source._applyAllParentLimits
      _fsrsReschedule = source._fsrsReschedule
      _fsrsHealthCheck = source._fsrsHealthCheck
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularInt64Field(value: &_storage._targetDeckID) }()
        case 2: try { try decoder.decodeRepeatedMessageField(value: &_storage._configs) }()
        case 3: try { try decoder.decodeRepeatedInt64Field(value: &_storage._removedConfigIds) }()
        case 4: try { try decoder.decodeSingularEnumField(value: &_storage._mode) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._cardStateCustomizer) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._limits) }()
        case 7: try { try decoder.decodeSingularBoolField(value: &_storage._newCardsIgnoreReviewLimit) }()
        case 8: try { try decoder.decodeSingularBoolField(value: &_storage._fsrs) }()
        case 9: try { try decoder.decodeSingularBoolField(value: &_storage._applyAllParentLimits) }()
        case 10: try { try decoder.decodeSingularBoolField(value: &_storage._fsrsReschedule) }()
        case 11: try { try decoder.decodeSingularBoolField(value: &_storage._fsrsHealthCheck) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._targetDeckID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._targetDeckID, fieldNumber: 1)
      }
      if !_storage._configs.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._configs, fieldNumber: 2)
      }
      if !_storage._removedConfigIds.isEmpty {
        try visitor.visitPackedInt64Field(value: _storage._removedConfigIds, fieldNumber: 3)
      }
      if _storage._mode != .normal {
        try visitor.visitSingularEnumField(value: _storage._mode, fieldNumber: 4)
      }
      if !_storage._cardStateCustomizer.isEmpty {
        try visitor.visitSingularStringField(value: _storage._cardStateCustomizer, fieldNumber: 5)
      }
      try { if let v = _storage._limits {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      if _storage._newCardsIgnoreReviewLimit != false {
        try visitor.visitSingularBoolField(value: _storage._newCardsIgnoreReviewLimit, fieldNumber: 7)
      }
      if _storage._fsrs != false {
        try visitor.visitSingularBoolField(value: _storage._fsrs, fieldNumber: 8)
      }
      if _storage._applyAllParentLimits != false {
        try visitor.visitSingularBoolField(value: _storage._applyAllParentLimits, fieldNumber: 9)
      }
      if _storage._fsrsReschedule != false {
        try visitor.visitSingularBoolField(value: _storage._fsrsReschedule, fieldNumber: 10)
      }
      if _storage._fsrsHealthCheck != false {
        try visitor.visitSingularBoolField(value: _storage._fsrsHealthCheck, fieldNumber: 11)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_DeckConfig_UpdateDeckConfigsRequest, rhs: Anki_DeckConfig_UpdateDeckConfigsRequest) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._targetDeckID != rhs_storage._targetDeckID {return false}
        if _storage._configs != rhs_storage._configs {return false}
        if _storage._removedConfigIds != rhs_storage._removedConfigIds {return false}
        if _storage._mode != rhs_storage._mode {return false}
        if _storage._cardStateCustomizer != rhs_storage._cardStateCustomizer {return false}
        if _storage._limits != rhs_storage._limits {return false}
        if _storage._newCardsIgnoreReviewLimit != rhs_storage._newCardsIgnoreReviewLimit {return false}
        if _storage._fsrs != rhs_storage._fsrs {return false}
        if _storage._applyAllParentLimits != rhs_storage._applyAllParentLimits {return false}
        if _storage._fsrsReschedule != rhs_storage._fsrsReschedule {return false}
        if _storage._fsrsHealthCheck != rhs_storage._fsrsHealthCheck {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
