// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: anki/image_occlusion.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Anki_ImageOcclusion_GetImageForOcclusionRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var path: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_ImageOcclusion_GetImageForOcclusionResponse: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var data: Data = Data()

  public var name: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_ImageOcclusion_AddImageOcclusionNoteRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var imagePath: String = String()

  public var occlusions: String = String()

  public var header: String = String()

  public var backExtra: String = String()

  public var tags: [String] = []

  public var notetypeID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_ImageOcclusion_GetImageOcclusionNoteRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var noteID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_ImageOcclusion_GetImageOcclusionNoteResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var value: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.OneOf_Value? = nil

  public var note: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionNote {
    get {
      if case .note(let v)? = value {return v}
      return Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionNote()
    }
    set {value = .note(newValue)}
  }

  public var error: String {
    get {
      if case .error(let v)? = value {return v}
      return String()
    }
    set {value = .error(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Value: Equatable, Sendable {
    case note(Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionNote)
    case error(String)

  }

  public struct ImageOcclusionProperty: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var name: String = String()

    public var value: String = String()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct ImageOcclusionShape: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var shape: String = String()

    public var properties: [Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionProperty] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct ImageOcclusion: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var shapes: [Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionShape] = []

    public var ordinal: UInt32 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct ImageOcclusionNote: @unchecked Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var imageData: Data = Data()

    public var occlusions: [Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusion] = []

    public var header: String = String()

    public var backExtra: String = String()

    public var tags: [String] = []

    public var imageFileName: String = String()

    public var occludeInactive: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public init() {}
}

public struct Anki_ImageOcclusion_UpdateImageOcclusionNoteRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var noteID: Int64 = 0

  public var occlusions: String = String()

  public var header: String = String()

  public var backExtra: String = String()

  public var tags: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_ImageOcclusion_GetImageOcclusionFieldsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var notetypeID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_ImageOcclusion_GetImageOcclusionFieldsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var fields: Anki_ImageOcclusion_ImageOcclusionFieldIndexes {
    get {return _fields ?? Anki_ImageOcclusion_ImageOcclusionFieldIndexes()}
    set {_fields = newValue}
  }
  /// Returns true if `fields` has been explicitly set.
  public var hasFields: Bool {return self._fields != nil}
  /// Clears the value of `fields`. Subsequent reads from it will return its default value.
  public mutating func clearFields() {self._fields = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _fields: Anki_ImageOcclusion_ImageOcclusionFieldIndexes? = nil
}

public struct Anki_ImageOcclusion_ImageOcclusionFieldIndexes: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var occlusions: UInt32 = 0

  public var image: UInt32 = 0

  public var header: UInt32 = 0

  public var backExtra: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "anki.image_occlusion"

extension Anki_ImageOcclusion_GetImageForOcclusionRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetImageForOcclusionRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "path"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.path) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.path.isEmpty {
      try visitor.visitSingularStringField(value: self.path, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_ImageOcclusion_GetImageForOcclusionRequest, rhs: Anki_ImageOcclusion_GetImageForOcclusionRequest) -> Bool {
    if lhs.path != rhs.path {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_ImageOcclusion_GetImageForOcclusionResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetImageForOcclusionResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "data"),
    2: .same(proto: "name"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.data) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.data.isEmpty {
      try visitor.visitSingularBytesField(value: self.data, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_ImageOcclusion_GetImageForOcclusionResponse, rhs: Anki_ImageOcclusion_GetImageForOcclusionResponse) -> Bool {
    if lhs.data != rhs.data {return false}
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_ImageOcclusion_AddImageOcclusionNoteRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AddImageOcclusionNoteRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "image_path"),
    2: .same(proto: "occlusions"),
    3: .same(proto: "header"),
    4: .standard(proto: "back_extra"),
    5: .same(proto: "tags"),
    6: .standard(proto: "notetype_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.imagePath) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.occlusions) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.header) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.backExtra) }()
      case 5: try { try decoder.decodeRepeatedStringField(value: &self.tags) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self.notetypeID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.imagePath.isEmpty {
      try visitor.visitSingularStringField(value: self.imagePath, fieldNumber: 1)
    }
    if !self.occlusions.isEmpty {
      try visitor.visitSingularStringField(value: self.occlusions, fieldNumber: 2)
    }
    if !self.header.isEmpty {
      try visitor.visitSingularStringField(value: self.header, fieldNumber: 3)
    }
    if !self.backExtra.isEmpty {
      try visitor.visitSingularStringField(value: self.backExtra, fieldNumber: 4)
    }
    if !self.tags.isEmpty {
      try visitor.visitRepeatedStringField(value: self.tags, fieldNumber: 5)
    }
    if self.notetypeID != 0 {
      try visitor.visitSingularInt64Field(value: self.notetypeID, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_ImageOcclusion_AddImageOcclusionNoteRequest, rhs: Anki_ImageOcclusion_AddImageOcclusionNoteRequest) -> Bool {
    if lhs.imagePath != rhs.imagePath {return false}
    if lhs.occlusions != rhs.occlusions {return false}
    if lhs.header != rhs.header {return false}
    if lhs.backExtra != rhs.backExtra {return false}
    if lhs.tags != rhs.tags {return false}
    if lhs.notetypeID != rhs.notetypeID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_ImageOcclusion_GetImageOcclusionNoteRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetImageOcclusionNoteRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "note_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.noteID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.noteID != 0 {
      try visitor.visitSingularInt64Field(value: self.noteID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_ImageOcclusion_GetImageOcclusionNoteRequest, rhs: Anki_ImageOcclusion_GetImageOcclusionNoteRequest) -> Bool {
    if lhs.noteID != rhs.noteID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_ImageOcclusion_GetImageOcclusionNoteResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetImageOcclusionNoteResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "note"),
    2: .same(proto: "error"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionNote?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .note(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .note(v)
        }
      }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .error(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.value {
    case .note?: try {
      guard case .note(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .error?: try {
      guard case .error(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse, rhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionProperty: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Anki_ImageOcclusion_GetImageOcclusionNoteResponse.protoMessageName + ".ImageOcclusionProperty"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "name"),
    2: .same(proto: "value"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.value) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.value.isEmpty {
      try visitor.visitSingularStringField(value: self.value, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionProperty, rhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionProperty) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionShape: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Anki_ImageOcclusion_GetImageOcclusionNoteResponse.protoMessageName + ".ImageOcclusionShape"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "shape"),
    2: .same(proto: "properties"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.shape) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.properties) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.shape.isEmpty {
      try visitor.visitSingularStringField(value: self.shape, fieldNumber: 1)
    }
    if !self.properties.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.properties, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionShape, rhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionShape) -> Bool {
    if lhs.shape != rhs.shape {return false}
    if lhs.properties != rhs.properties {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusion: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Anki_ImageOcclusion_GetImageOcclusionNoteResponse.protoMessageName + ".ImageOcclusion"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "shapes"),
    2: .same(proto: "ordinal"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.shapes) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.ordinal) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.shapes.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.shapes, fieldNumber: 1)
    }
    if self.ordinal != 0 {
      try visitor.visitSingularUInt32Field(value: self.ordinal, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusion, rhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusion) -> Bool {
    if lhs.shapes != rhs.shapes {return false}
    if lhs.ordinal != rhs.ordinal {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionNote: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Anki_ImageOcclusion_GetImageOcclusionNoteResponse.protoMessageName + ".ImageOcclusionNote"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "image_data"),
    2: .same(proto: "occlusions"),
    3: .same(proto: "header"),
    4: .standard(proto: "back_extra"),
    5: .same(proto: "tags"),
    6: .standard(proto: "image_file_name"),
    7: .standard(proto: "occlude_inactive"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.imageData) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.occlusions) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.header) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.backExtra) }()
      case 5: try { try decoder.decodeRepeatedStringField(value: &self.tags) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.imageFileName) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.occludeInactive) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.imageData.isEmpty {
      try visitor.visitSingularBytesField(value: self.imageData, fieldNumber: 1)
    }
    if !self.occlusions.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.occlusions, fieldNumber: 2)
    }
    if !self.header.isEmpty {
      try visitor.visitSingularStringField(value: self.header, fieldNumber: 3)
    }
    if !self.backExtra.isEmpty {
      try visitor.visitSingularStringField(value: self.backExtra, fieldNumber: 4)
    }
    if !self.tags.isEmpty {
      try visitor.visitRepeatedStringField(value: self.tags, fieldNumber: 5)
    }
    if !self.imageFileName.isEmpty {
      try visitor.visitSingularStringField(value: self.imageFileName, fieldNumber: 6)
    }
    if self.occludeInactive != false {
      try visitor.visitSingularBoolField(value: self.occludeInactive, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionNote, rhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionNote) -> Bool {
    if lhs.imageData != rhs.imageData {return false}
    if lhs.occlusions != rhs.occlusions {return false}
    if lhs.header != rhs.header {return false}
    if lhs.backExtra != rhs.backExtra {return false}
    if lhs.tags != rhs.tags {return false}
    if lhs.imageFileName != rhs.imageFileName {return false}
    if lhs.occludeInactive != rhs.occludeInactive {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_ImageOcclusion_UpdateImageOcclusionNoteRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UpdateImageOcclusionNoteRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "note_id"),
    2: .same(proto: "occlusions"),
    3: .same(proto: "header"),
    4: .standard(proto: "back_extra"),
    5: .same(proto: "tags"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.noteID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.occlusions) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.header) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.backExtra) }()
      case 5: try { try decoder.decodeRepeatedStringField(value: &self.tags) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.noteID != 0 {
      try visitor.visitSingularInt64Field(value: self.noteID, fieldNumber: 1)
    }
    if !self.occlusions.isEmpty {
      try visitor.visitSingularStringField(value: self.occlusions, fieldNumber: 2)
    }
    if !self.header.isEmpty {
      try visitor.visitSingularStringField(value: self.header, fieldNumber: 3)
    }
    if !self.backExtra.isEmpty {
      try visitor.visitSingularStringField(value: self.backExtra, fieldNumber: 4)
    }
    if !self.tags.isEmpty {
      try visitor.visitRepeatedStringField(value: self.tags, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_ImageOcclusion_UpdateImageOcclusionNoteRequest, rhs: Anki_ImageOcclusion_UpdateImageOcclusionNoteRequest) -> Bool {
    if lhs.noteID != rhs.noteID {return false}
    if lhs.occlusions != rhs.occlusions {return false}
    if lhs.header != rhs.header {return false}
    if lhs.backExtra != rhs.backExtra {return false}
    if lhs.tags != rhs.tags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_ImageOcclusion_GetImageOcclusionFieldsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetImageOcclusionFieldsRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "notetype_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.notetypeID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.notetypeID != 0 {
      try visitor.visitSingularInt64Field(value: self.notetypeID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_ImageOcclusion_GetImageOcclusionFieldsRequest, rhs: Anki_ImageOcclusion_GetImageOcclusionFieldsRequest) -> Bool {
    if lhs.notetypeID != rhs.notetypeID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_ImageOcclusion_GetImageOcclusionFieldsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetImageOcclusionFieldsResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "fields"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._fields) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._fields {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_ImageOcclusion_GetImageOcclusionFieldsResponse, rhs: Anki_ImageOcclusion_GetImageOcclusionFieldsResponse) -> Bool {
    if lhs._fields != rhs._fields {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_ImageOcclusion_ImageOcclusionFieldIndexes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ImageOcclusionFieldIndexes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "occlusions"),
    2: .same(proto: "image"),
    3: .same(proto: "header"),
    4: .standard(proto: "back_extra"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.occlusions) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.image) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.header) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.backExtra) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.occlusions != 0 {
      try visitor.visitSingularUInt32Field(value: self.occlusions, fieldNumber: 1)
    }
    if self.image != 0 {
      try visitor.visitSingularUInt32Field(value: self.image, fieldNumber: 2)
    }
    if self.header != 0 {
      try visitor.visitSingularUInt32Field(value: self.header, fieldNumber: 3)
    }
    if self.backExtra != 0 {
      try visitor.visitSingularUInt32Field(value: self.backExtra, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_ImageOcclusion_ImageOcclusionFieldIndexes, rhs: Anki_ImageOcclusion_ImageOcclusionFieldIndexes) -> Bool {
    if lhs.occlusions != rhs.occlusions {return false}
    if lhs.image != rhs.image {return false}
    if lhs.header != rhs.header {return false}
    if lhs.backExtra != rhs.backExtra {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
