// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: anki/links.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Anki_Links_HelpPageLinkRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var page: Anki_Links_HelpPageLinkRequest.HelpPage = .noteType

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum HelpPage: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case noteType // = 0
    case browsing // = 1
    case browsingFindAndReplace // = 2
    case browsingNotesMenu // = 3
    case keyboardShortcuts // = 4
    case editing // = 5
    case addingCardAndNote // = 6
    case addingANoteType // = 7
    case latex // = 8
    case preferences // = 9
    case index // = 10
    case templates // = 11
    case filteredDeck // = 12
    case importing // = 13
    case customizingFields // = 14
    case deckOptions // = 15
    case editingFeatures // = 16
    case fullScreenIssue // = 17
    case cardTypeDuplicate // = 18
    case cardTypeNoFrontField // = 19
    case cardTypeMissingCloze // = 20
    case troubleshooting // = 21
    case cardTypeTemplateError // = 22
    case UNRECOGNIZED(Int)

    public init() {
      self = .noteType
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .noteType
      case 1: self = .browsing
      case 2: self = .browsingFindAndReplace
      case 3: self = .browsingNotesMenu
      case 4: self = .keyboardShortcuts
      case 5: self = .editing
      case 6: self = .addingCardAndNote
      case 7: self = .addingANoteType
      case 8: self = .latex
      case 9: self = .preferences
      case 10: self = .index
      case 11: self = .templates
      case 12: self = .filteredDeck
      case 13: self = .importing
      case 14: self = .customizingFields
      case 15: self = .deckOptions
      case 16: self = .editingFeatures
      case 17: self = .fullScreenIssue
      case 18: self = .cardTypeDuplicate
      case 19: self = .cardTypeNoFrontField
      case 20: self = .cardTypeMissingCloze
      case 21: self = .troubleshooting
      case 22: self = .cardTypeTemplateError
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .noteType: return 0
      case .browsing: return 1
      case .browsingFindAndReplace: return 2
      case .browsingNotesMenu: return 3
      case .keyboardShortcuts: return 4
      case .editing: return 5
      case .addingCardAndNote: return 6
      case .addingANoteType: return 7
      case .latex: return 8
      case .preferences: return 9
      case .index: return 10
      case .templates: return 11
      case .filteredDeck: return 12
      case .importing: return 13
      case .customizingFields: return 14
      case .deckOptions: return 15
      case .editingFeatures: return 16
      case .fullScreenIssue: return 17
      case .cardTypeDuplicate: return 18
      case .cardTypeNoFrontField: return 19
      case .cardTypeMissingCloze: return 20
      case .troubleshooting: return 21
      case .cardTypeTemplateError: return 22
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Anki_Links_HelpPageLinkRequest.HelpPage] = [
      .noteType,
      .browsing,
      .browsingFindAndReplace,
      .browsingNotesMenu,
      .keyboardShortcuts,
      .editing,
      .addingCardAndNote,
      .addingANoteType,
      .latex,
      .preferences,
      .index,
      .templates,
      .filteredDeck,
      .importing,
      .customizingFields,
      .deckOptions,
      .editingFeatures,
      .fullScreenIssue,
      .cardTypeDuplicate,
      .cardTypeNoFrontField,
      .cardTypeMissingCloze,
      .troubleshooting,
      .cardTypeTemplateError,
    ]

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "anki.links"

extension Anki_Links_HelpPageLinkRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HelpPageLinkRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "page"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.page) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.page != .noteType {
      try visitor.visitSingularEnumField(value: self.page, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Links_HelpPageLinkRequest, rhs: Anki_Links_HelpPageLinkRequest) -> Bool {
    if lhs.page != rhs.page {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Links_HelpPageLinkRequest.HelpPage: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "NOTE_TYPE"),
    1: .same(proto: "BROWSING"),
    2: .same(proto: "BROWSING_FIND_AND_REPLACE"),
    3: .same(proto: "BROWSING_NOTES_MENU"),
    4: .same(proto: "KEYBOARD_SHORTCUTS"),
    5: .same(proto: "EDITING"),
    6: .same(proto: "ADDING_CARD_AND_NOTE"),
    7: .same(proto: "ADDING_A_NOTE_TYPE"),
    8: .same(proto: "LATEX"),
    9: .same(proto: "PREFERENCES"),
    10: .same(proto: "INDEX"),
    11: .same(proto: "TEMPLATES"),
    12: .same(proto: "FILTERED_DECK"),
    13: .same(proto: "IMPORTING"),
    14: .same(proto: "CUSTOMIZING_FIELDS"),
    15: .same(proto: "DECK_OPTIONS"),
    16: .same(proto: "EDITING_FEATURES"),
    17: .same(proto: "FULL_SCREEN_ISSUE"),
    18: .same(proto: "CARD_TYPE_DUPLICATE"),
    19: .same(proto: "CARD_TYPE_NO_FRONT_FIELD"),
    20: .same(proto: "CARD_TYPE_MISSING_CLOZE"),
    21: .same(proto: "TROUBLESHOOTING"),
    22: .same(proto: "CARD_TYPE_TEMPLATE_ERROR"),
  ]
}
