// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: anki/sync.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Anki_Sync_SyncAuth: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var hkey: String = String()

  public var endpoint: String {
    get {return _endpoint ?? String()}
    set {_endpoint = newValue}
  }
  /// Returns true if `endpoint` has been explicitly set.
  public var hasEndpoint: Bool {return self._endpoint != nil}
  /// Clears the value of `endpoint`. Subsequent reads from it will return its default value.
  public mutating func clearEndpoint() {self._endpoint = nil}

  public var ioTimeoutSecs: UInt32 {
    get {return _ioTimeoutSecs ?? 0}
    set {_ioTimeoutSecs = newValue}
  }
  /// Returns true if `ioTimeoutSecs` has been explicitly set.
  public var hasIoTimeoutSecs: Bool {return self._ioTimeoutSecs != nil}
  /// Clears the value of `ioTimeoutSecs`. Subsequent reads from it will return its default value.
  public mutating func clearIoTimeoutSecs() {self._ioTimeoutSecs = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _endpoint: String? = nil
  fileprivate var _ioTimeoutSecs: UInt32? = nil
}

public struct Anki_Sync_SyncLoginRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var username: String = String()

  public var password: String = String()

  public var endpoint: String {
    get {return _endpoint ?? String()}
    set {_endpoint = newValue}
  }
  /// Returns true if `endpoint` has been explicitly set.
  public var hasEndpoint: Bool {return self._endpoint != nil}
  /// Clears the value of `endpoint`. Subsequent reads from it will return its default value.
  public mutating func clearEndpoint() {self._endpoint = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _endpoint: String? = nil
}

public struct Anki_Sync_SyncStatusResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var required: Anki_Sync_SyncStatusResponse.Required = .noChanges

  public var newEndpoint: String {
    get {return _newEndpoint ?? String()}
    set {_newEndpoint = newValue}
  }
  /// Returns true if `newEndpoint` has been explicitly set.
  public var hasNewEndpoint: Bool {return self._newEndpoint != nil}
  /// Clears the value of `newEndpoint`. Subsequent reads from it will return its default value.
  public mutating func clearNewEndpoint() {self._newEndpoint = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Required: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case noChanges // = 0
    case normalSync // = 1
    case fullSync // = 2
    case UNRECOGNIZED(Int)

    public init() {
      self = .noChanges
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .noChanges
      case 1: self = .normalSync
      case 2: self = .fullSync
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .noChanges: return 0
      case .normalSync: return 1
      case .fullSync: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Anki_Sync_SyncStatusResponse.Required] = [
      .noChanges,
      .normalSync,
      .fullSync,
    ]

  }

  public init() {}

  fileprivate var _newEndpoint: String? = nil
}

public struct Anki_Sync_SyncCollectionRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var auth: Anki_Sync_SyncAuth {
    get {return _auth ?? Anki_Sync_SyncAuth()}
    set {_auth = newValue}
  }
  /// Returns true if `auth` has been explicitly set.
  public var hasAuth: Bool {return self._auth != nil}
  /// Clears the value of `auth`. Subsequent reads from it will return its default value.
  public mutating func clearAuth() {self._auth = nil}

  public var syncMedia: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _auth: Anki_Sync_SyncAuth? = nil
}

public struct Anki_Sync_SyncCollectionResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var hostNumber: UInt32 = 0

  public var serverMessage: String = String()

  public var required: Anki_Sync_SyncCollectionResponse.ChangesRequired = .noChanges

  public var newEndpoint: String {
    get {return _newEndpoint ?? String()}
    set {_newEndpoint = newValue}
  }
  /// Returns true if `newEndpoint` has been explicitly set.
  public var hasNewEndpoint: Bool {return self._newEndpoint != nil}
  /// Clears the value of `newEndpoint`. Subsequent reads from it will return its default value.
  public mutating func clearNewEndpoint() {self._newEndpoint = nil}

  public var serverMediaUsn: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum ChangesRequired: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case noChanges // = 0
    case normalSync // = 1
    case fullSync // = 2

    /// local collection has no cards; upload not an option
    case fullDownload // = 3

    /// remote collection has no cards; download not an option
    case fullUpload // = 4
    case UNRECOGNIZED(Int)

    public init() {
      self = .noChanges
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .noChanges
      case 1: self = .normalSync
      case 2: self = .fullSync
      case 3: self = .fullDownload
      case 4: self = .fullUpload
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .noChanges: return 0
      case .normalSync: return 1
      case .fullSync: return 2
      case .fullDownload: return 3
      case .fullUpload: return 4
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Anki_Sync_SyncCollectionResponse.ChangesRequired] = [
      .noChanges,
      .normalSync,
      .fullSync,
      .fullDownload,
      .fullUpload,
    ]

  }

  public init() {}

  fileprivate var _newEndpoint: String? = nil
}

public struct Anki_Sync_MediaSyncStatusResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var active: Bool = false

  public var progress: Anki_Sync_MediaSyncProgress {
    get {return _progress ?? Anki_Sync_MediaSyncProgress()}
    set {_progress = newValue}
  }
  /// Returns true if `progress` has been explicitly set.
  public var hasProgress: Bool {return self._progress != nil}
  /// Clears the value of `progress`. Subsequent reads from it will return its default value.
  public mutating func clearProgress() {self._progress = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _progress: Anki_Sync_MediaSyncProgress? = nil
}

public struct Anki_Sync_MediaSyncProgress: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var checked: String = String()

  public var added: String = String()

  public var removed: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Anki_Sync_FullUploadOrDownloadRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var auth: Anki_Sync_SyncAuth {
    get {return _auth ?? Anki_Sync_SyncAuth()}
    set {_auth = newValue}
  }
  /// Returns true if `auth` has been explicitly set.
  public var hasAuth: Bool {return self._auth != nil}
  /// Clears the value of `auth`. Subsequent reads from it will return its default value.
  public mutating func clearAuth() {self._auth = nil}

  public var upload: Bool = false

  /// if not provided, media syncing will be skipped
  public var serverUsn: Int32 {
    get {return _serverUsn ?? 0}
    set {_serverUsn = newValue}
  }
  /// Returns true if `serverUsn` has been explicitly set.
  public var hasServerUsn: Bool {return self._serverUsn != nil}
  /// Clears the value of `serverUsn`. Subsequent reads from it will return its default value.
  public mutating func clearServerUsn() {self._serverUsn = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _auth: Anki_Sync_SyncAuth? = nil
  fileprivate var _serverUsn: Int32? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "anki.sync"

extension Anki_Sync_SyncAuth: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SyncAuth"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "hkey"),
    2: .same(proto: "endpoint"),
    3: .standard(proto: "io_timeout_secs"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.hkey) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._endpoint) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self._ioTimeoutSecs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.hkey.isEmpty {
      try visitor.visitSingularStringField(value: self.hkey, fieldNumber: 1)
    }
    try { if let v = self._endpoint {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._ioTimeoutSecs {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Sync_SyncAuth, rhs: Anki_Sync_SyncAuth) -> Bool {
    if lhs.hkey != rhs.hkey {return false}
    if lhs._endpoint != rhs._endpoint {return false}
    if lhs._ioTimeoutSecs != rhs._ioTimeoutSecs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Sync_SyncLoginRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SyncLoginRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "username"),
    2: .same(proto: "password"),
    3: .same(proto: "endpoint"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.username) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.password) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._endpoint) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.username.isEmpty {
      try visitor.visitSingularStringField(value: self.username, fieldNumber: 1)
    }
    if !self.password.isEmpty {
      try visitor.visitSingularStringField(value: self.password, fieldNumber: 2)
    }
    try { if let v = self._endpoint {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Sync_SyncLoginRequest, rhs: Anki_Sync_SyncLoginRequest) -> Bool {
    if lhs.username != rhs.username {return false}
    if lhs.password != rhs.password {return false}
    if lhs._endpoint != rhs._endpoint {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Sync_SyncStatusResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SyncStatusResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "required"),
    4: .standard(proto: "new_endpoint"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.required) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._newEndpoint) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.required != .noChanges {
      try visitor.visitSingularEnumField(value: self.required, fieldNumber: 1)
    }
    try { if let v = self._newEndpoint {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Sync_SyncStatusResponse, rhs: Anki_Sync_SyncStatusResponse) -> Bool {
    if lhs.required != rhs.required {return false}
    if lhs._newEndpoint != rhs._newEndpoint {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Sync_SyncStatusResponse.Required: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "NO_CHANGES"),
    1: .same(proto: "NORMAL_SYNC"),
    2: .same(proto: "FULL_SYNC"),
  ]
}

extension Anki_Sync_SyncCollectionRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SyncCollectionRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "auth"),
    2: .standard(proto: "sync_media"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._auth) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.syncMedia) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._auth {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.syncMedia != false {
      try visitor.visitSingularBoolField(value: self.syncMedia, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Sync_SyncCollectionRequest, rhs: Anki_Sync_SyncCollectionRequest) -> Bool {
    if lhs._auth != rhs._auth {return false}
    if lhs.syncMedia != rhs.syncMedia {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Sync_SyncCollectionResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SyncCollectionResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "host_number"),
    2: .standard(proto: "server_message"),
    3: .same(proto: "required"),
    4: .standard(proto: "new_endpoint"),
    5: .standard(proto: "server_media_usn"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.hostNumber) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.serverMessage) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.required) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._newEndpoint) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.serverMediaUsn) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.hostNumber != 0 {
      try visitor.visitSingularUInt32Field(value: self.hostNumber, fieldNumber: 1)
    }
    if !self.serverMessage.isEmpty {
      try visitor.visitSingularStringField(value: self.serverMessage, fieldNumber: 2)
    }
    if self.required != .noChanges {
      try visitor.visitSingularEnumField(value: self.required, fieldNumber: 3)
    }
    try { if let v = self._newEndpoint {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    if self.serverMediaUsn != 0 {
      try visitor.visitSingularInt32Field(value: self.serverMediaUsn, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Sync_SyncCollectionResponse, rhs: Anki_Sync_SyncCollectionResponse) -> Bool {
    if lhs.hostNumber != rhs.hostNumber {return false}
    if lhs.serverMessage != rhs.serverMessage {return false}
    if lhs.required != rhs.required {return false}
    if lhs._newEndpoint != rhs._newEndpoint {return false}
    if lhs.serverMediaUsn != rhs.serverMediaUsn {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Sync_SyncCollectionResponse.ChangesRequired: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "NO_CHANGES"),
    1: .same(proto: "NORMAL_SYNC"),
    2: .same(proto: "FULL_SYNC"),
    3: .same(proto: "FULL_DOWNLOAD"),
    4: .same(proto: "FULL_UPLOAD"),
  ]
}

extension Anki_Sync_MediaSyncStatusResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MediaSyncStatusResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "active"),
    2: .same(proto: "progress"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.active) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._progress) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.active != false {
      try visitor.visitSingularBoolField(value: self.active, fieldNumber: 1)
    }
    try { if let v = self._progress {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Sync_MediaSyncStatusResponse, rhs: Anki_Sync_MediaSyncStatusResponse) -> Bool {
    if lhs.active != rhs.active {return false}
    if lhs._progress != rhs._progress {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Sync_MediaSyncProgress: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MediaSyncProgress"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "checked"),
    2: .same(proto: "added"),
    3: .same(proto: "removed"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.checked) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.added) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.removed) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.checked.isEmpty {
      try visitor.visitSingularStringField(value: self.checked, fieldNumber: 1)
    }
    if !self.added.isEmpty {
      try visitor.visitSingularStringField(value: self.added, fieldNumber: 2)
    }
    if !self.removed.isEmpty {
      try visitor.visitSingularStringField(value: self.removed, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Sync_MediaSyncProgress, rhs: Anki_Sync_MediaSyncProgress) -> Bool {
    if lhs.checked != rhs.checked {return false}
    if lhs.added != rhs.added {return false}
    if lhs.removed != rhs.removed {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Anki_Sync_FullUploadOrDownloadRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FullUploadOrDownloadRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "auth"),
    2: .same(proto: "upload"),
    3: .standard(proto: "server_usn"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._auth) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.upload) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._serverUsn) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._auth {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.upload != false {
      try visitor.visitSingularBoolField(value: self.upload, fieldNumber: 2)
    }
    try { if let v = self._serverUsn {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anki_Sync_FullUploadOrDownloadRequest, rhs: Anki_Sync_FullUploadOrDownloadRequest) -> Bool {
    if lhs._auth != rhs._auth {return false}
    if lhs.upload != rhs.upload {return false}
    if lhs._serverUsn != rhs._serverUsn {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
