qt-accel-about = &Informazioni...
qt-accel-about-mac = Informazioni su Anki...
qt-accel-cards = &Carte
qt-accel-check-database = &Controlla database
qt-accel-check-media = Controlla file &Multimediali...
qt-accel-edit = &Modifica
qt-accel-exit = Es&ci
qt-accel-export = &Esporta...
qt-accel-export-notes = &Esporta le Note...
qt-accel-file = &File
qt-accel-filter = Fil&tro
qt-accel-find = &Trova
qt-accel-find-and-replace = Trova e &sostituisci...
qt-accel-find-duplicates = Trova &duplicati...
qt-accel-go = &Vai
qt-accel-guide = &Guida...
qt-accel-help = &Aiuto
qt-accel-import = &Importa...
qt-accel-info = &Informazioni...
qt-accel-invert-selection = &Inverti selezione
qt-accel-next-card = Carta segue&nte
qt-accel-note = N&ota
qt-accel-notes = &Note
qt-accel-preferences = &Preferenze...
qt-accel-previous-card = Carta &precedente
qt-accel-select-all = Seleziona &tutto
qt-accel-select-notes = Seleziona &note
qt-accel-support-anki = &Supporta Anki...
qt-accel-switch-profile = &Cambia profilo
qt-accel-tools = &Strumenti
qt-accel-undo = &Annulla
qt-accel-redo = &Ripristina
qt-accel-set-due-date = Imposta data di &Scadenza...
qt-accel-forget = &Dimentica
qt-accel-view = &Visualizza
qt-accel-full-screen = Attiva &Schermo Intero
qt-accel-layout = &Layout
qt-accel-layout-auto = &Automatico
qt-accel-layout-vertical = &Verticale
qt-accel-layout-horizontal = &Orizzontale
qt-accel-zoom-in = &Aumenta Zoom
qt-accel-zoom-out = &Diminuisci Zoom
qt-accel-reset-zoom = &Ripristina Zoom
qt-accel-toggle-sidebar = Attiva/disattiva barra laterale
qt-accel-zoom-editor-in = &Aumenta Zoom (Editor)
qt-accel-zoom-editor-out = &Diminuisci Zoom (Editor)
qt-accel-create-backup = Crea &Backup
qt-accel-load-backup = &Ripristina da Backup
qt-accel-upgrade-downgrade = Effettua upgrade/downgrade
