qt-accel-about = &Giới thiệu...
qt-accel-about-mac = Giới thiệu về Anki...
qt-accel-cards = &Thẻ
qt-accel-check-database = &Kiểm tra cơ sở dữ liệu
qt-accel-check-media = Kiểm tra &Phương tiện...
qt-accel-edit = &Chỉnh sửa
qt-accel-exit = &Thoát
qt-accel-export = &Xuất...
qt-accel-export-notes = &Xuất Phiếu...
qt-accel-file = &Tập tin
qt-accel-filter = Lọc&Bộ lọc
qt-accel-find = &Tìm
qt-accel-find-and-replace = Tìm và Th&ay...
qt-accel-find-duplicates = Tìm Thẻ t&rùng...
qt-accel-go = &Tới
qt-accel-guide = &Hướng dẫn...
qt-accel-help = &Giúp đỡ
qt-accel-import = &Nhập...
qt-accel-info = &Thông tin...
qt-accel-invert-selection = Đả&o Chọn
qt-accel-next-card = &Thẻ Kế
qt-accel-note = &Ghi chú
qt-accel-notes = &Phiếu
qt-accel-preferences = &Tùy chỉnh
qt-accel-previous-card = &Thẻ Trước
qt-accel-select-all = Chọn &Hết
qt-accel-select-notes = Chọn &Phiếu
qt-accel-support-anki = &Ủng hộ Anki...
qt-accel-switch-profile = &Đổi hồ sơ cá nhân
qt-accel-tools = &Công cụ
qt-accel-undo = &Hoàn tác
qt-accel-redo = &Làm lại
qt-accel-set-due-date = Ngày&Đặt ngày đến hạn
qt-accel-forget = &Quên
qt-accel-view = &Xem
qt-accel-full-screen = Bất tắt &Toàn màn hình
qt-accel-layout = &Cấu trúc
qt-accel-layout-auto = &Tự động
qt-accel-layout-vertical = &Dọc
qt-accel-layout-horizontal = &Ngang
qt-accel-zoom-in = Phóng &to
qt-accel-zoom-out = Phóng &nhỏ
qt-accel-reset-zoom = &Đặt lại phóng to nhỏ
qt-accel-toggle-sidebar = Bật tắt Thanh bên
qt-accel-zoom-editor-in = Phóng &to biên tập
qt-accel-zoom-editor-out = Phóng &nhỏ biên tập
qt-accel-create-backup = Tạo &Bản sao
qt-accel-load-backup = &Quay lại Bản sao
qt-accel-upgrade-downgrade = Nâng cấp/Hạ cấp
