from typing import Any

def buildhash(*args, **kwargs) -> Any: ...
def open_backend(*args, **kwargs) -> Any: ...

class Backend:
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    def command(self, *args, **kwargs) -> Any: ...
    def db_command(self, *args, **kwargs) -> Any: ...
