editing-actual-size = איבערשליסן פֿאַקטישע גרייס
editing-add-media = צולייגן מעדיע
editing-align-left = אױסגלײַכן די שורות אױף לינקס
editing-align-right = אױסגלײַכן די שורות אױף רעכטס
editing-an-error-occurred-while-opening = אַ טעות איז פֿירגעקומען בעטן עפֿענען { $val }
editing-attach-picturesaudiovideo = בײַלייגן בילדער / אוידיאָ / ווידעאָ
editing-bold-text = פֿעטע אותיות
editing-cards = קאַרטלעך
editing-center = צענטער
editing-change-color = אויסבײַטן קאָליר
editing-cloze-deletion = שפּאַלט אויסמעקונג (נײַ קאַרטל)
editing-cloze-deletion-repeat = שפּאַלט אויסמעקונג (זעלבע קאַרטל)
editing-copy-image = קאָפּירן בילד
editing-couldnt-record-audio-have-you-installed = מ׳האָט נישט געקענט רעקאָרדירן אוידיאָ. האָסט אַרײַנגעלאָדן 'lame'?
editing-customize-card-templates = צופּאַסן מוסטער-קאַרטלעך
editing-customize-fields = צופּאַסן פֿעלדער
editing-cut = אויסשנײַדן
editing-double-click-image = געבן בילד אַ טאָפּלקוועטש
editing-double-click-to-expand = געבן אַ טאָפּלקוועטש כּדי צו צעוויקלען
editing-double-click-to-collapse = געבן אַ טאָפּלקוועטש כּדי צו צונויפֿוויקלען
editing-edit-current = צופּאַסן יעצטיקס
editing-edit-html = צופּאַסן HTML
editing-fields = פֿעלדער
editing-float-left = פֿלאָטן אויף לינקס
editing-float-right = פֿלאָטן אויף רעכטס
editing-float-none = קיין פֿלאָט
editing-indent = פֿאַרגרעסערן אײַנרוק
editing-italic-text = קורסיוו
editing-jump-to-tags-with-ctrlandshiftandt = צושפּרינגען צו צעטלען מיט Ctrl+Shift+T
editing-justify = אױסגלײַכן שורות
editing-latex = LaTeX
editing-latex-equation = LaTeX גלײַכונג
editing-latex-math-env = LaTeX מאַטעמאַטיק קאָנווערט
editing-mathjax-block = MathJax קעסטל
editing-mathjax-chemistry = MathJax כעמיע
editing-mathjax-inline = MathJax אַרײַן-שורה
editing-mathjax-placeholder = קוועטש { $accept } כּדי אָנצונעמען, { $newline } אויף אַ נײַער שורה.
editing-media = מעדיע
editing-open-image = עפֿענען בילד
editing-show-in-folder = אַנטפּלעקן אין פּאַפּקע
editing-ordered-list = אויסגע׳סדר׳טע רשימה
editing-outdent = פֿאַרקלענערן אײַנרוק
editing-paste = אַרײַנקלעפּן
editing-record-audio = רעקאָרדירן אוידיאָ
editing-remove-formatting = צונעמען פֿאָרמאַטירונג
editing-restore-original-size = אויפֿריכטן אָריגינעלע גרייס
editing-select-remove-formatting = אויסקלײַבן פֿאָרמאַטירונג וואָס צוצונעמען
editing-show-duplicates = ווײַזן דופּליקאַטן
editing-subscript = סובסקריפּט
editing-superscript = איבערשריפֿט
editing-tags = צעטלען
editing-tags-add = צושטעלן צעטל
editing-tags-copy = אָפּקאָפּירן צעטלען
editing-tags-remove = צונעמען צעטלען
editing-tags-select-all = אויסקלײַבן אַלע צעטלען
editing-text-color = טעקסט-קאָליר
editing-text-highlight-color = הינטערגרונט-קאָליר
editing-to-make-a-cloze-deletion-on = כּדי צו שאַפֿן אַ שפּאַלט אויסמעקונג אין אַ שוין געשאַפֿענע נאָטיץ, קודם מוז מען בײַטן אים אין אַ שפּאַלט גרופּע, דורך 'נאָטיצן > איבערבײַטן נאָטיצגרופּע'.
editing-toggle-html-editor = איבערסליסן HTML שאַפֿער
editing-toggle-visual-editor = אויסשליסן זעשאַפֿער
editing-toggle-sticky = אויסשליסן קלעפּיק
editing-expand = צעוויקלען
editing-collapse = צונויפֿוויקלען
editing-expand-field = צעוויקלען פֿעלד
editing-collapse-field = צונויפֿוויקלען פֿעלד
editing-underline-text = אונטערשטרײַכן רשימה
editing-unordered-list = נישט-אויסגע׳סדר׳טע רשימה
editing-warning-cloze-deletions-will-not-work = היט זיך: שפּאַלט אויסמעקונגען וועלן נישט אַרבעטן ביז דו וועסט אויסבײַטן דעם סאָרט פון אויבן ביזן שפּאַלט.
editing-mathjax-preview = MathJax פֿאָרויסווײַז
editing-shrink-images = פֿאַרקלענערן בילדער
editing-close-html-tags = שליסן אויטאָמאַטיש HTML צעטלען
editing-from-clipboard = פון קליפּבאָורד
editing-alignment = אויסגלײַך
editing-equations = גלײַכונגען
editing-no-image-found-on-clipboard = קיין בילד נישט געפֿונען אינעם קליפּבאָורד.
editing-image-occlusion-mode = בילד- אָקליזיע מאָדוס
editing-image-occlusion-zoom-out = אויסזומירן
editing-image-occlusion-zoom-in = אײַנזומירן
editing-image-occlusion-zoom-reset = אײַנשטעלן זום אויף ס׳נײַ
editing-image-occlusion-toggle-translucent = איבערשליסן דורכלײַכטיקייט
editing-image-occlusion-delete = אָפּמעקן
editing-image-occlusion-duplicate = דופּליקירן
editing-image-occlusion-group = גרופּירן אָפּקלײַב
editing-image-occlusion-ungroup = צענעמען גרופּירטן אָפּקלײַב
editing-image-occlusion-select-all = אויסקלײַבן אַלץ
editing-image-occlusion-alignment = אויסגלײַך
editing-image-occlusion-align-left = אױסגלײַכן די שורות אױף לינקס
editing-image-occlusion-align-h-center = אויסגלײַכן האָריזאָנטאַלע מיטלפּונקטן
editing-image-occlusion-align-right = אױסגלײַכן די שורות אױף רעכטס
editing-image-occlusion-align-top = אויסגלײַכן אויבנס
editing-image-occlusion-align-v-center = אויסגלײַכן ווערטיקאַלע מיטלפּונקטן
editing-image-occlusion-align-bottom = אויסגלײַכן אונטנס
editing-image-occlusion-select-tool = אויסקלײַבן
editing-image-occlusion-zoom-tool = זומירן
editing-image-occlusion-rectangle-tool = גראָדעק
editing-image-occlusion-ellipse-tool = עליפּס
editing-image-occlusion-polygon-tool = פּאָליגאָן
editing-image-occlusion-text-tool = טעקסט
editing-image-occlusion-fill-tool = באַפֿאַרבן
editing-image-occlusion-toggle-mask-editor = איבערסליסן מאַסקע שאַפֿער
editing-image-occlusion-reset = אײַנשטעלן בילד-אָקליזיע אויף ס׳נײַ
editing-image-occlusion-confirm-reset = ביסט זיכער, אַז דו ווילסט אײַנשטעלן אָט די בילד-אָקליזיע אויף ס׳נײַ?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML שאַפֿער
