adding-add-shortcut-ctrlandenter = Toevoegen (sneltoets: ctrl+enter)
adding-added = Toegevoegd
adding-discard-current-input = Huidige invoer verwijderen?
adding-keep-editing = Blijf bewerken
adding-edit = Bewerk "{ $val }"
adding-history = Geschiedenis
adding-note-deleted = (Aantekening verwijderd)
adding-shortcut = Sneltoets: { $val }
adding-the-first-field-is-empty = Het eerste veld is leeg.
adding-you-have-a-cloze-deletion-note = U hebt een cloze aantekeningstype, maar u heeft nog geen clozes gecreëerd. Verdergaan?
