notetypes-front-field = Voorkant
notetypes-back-field = Achterkant
notetypes-add-reverse-field = Omgekeerde toevoegen
notetypes-text-field = Tekst
notetypes-basic-name = Basis
notetypes-basic-reversed-name = Basis (en omgekeerde kaart)
notetypes-basic-optional-reversed-name = Basis (omgekeerde kaart optioneel)
notetypes-basic-type-answer-name = Basisch (typ het antwoord in)
notetypes-card-2-name = Kaart 2
notetypes-card-1-name = Kaart 1
notetypes-add = Toevoegen: { $val }
notetypes-add-note-type = Aantekeningstype toevoegen
notetypes-cards = Kaarten...
notetypes-clone = Dupliceer: { $val }
notetypes-copy = { $val } kopiëren
notetypes-create-scalable-images-with-dvisvgm = Schaalbare afbeeldingen met dvisvgm aanmaken
notetypes-delete-this-note-type-and-all = Wilt u dit aantekeningstype en alle bijbehorende kaarten verwijderen?
notetypes-delete-this-unused-note-type = Wilt u dit ongebruikte aantekeningstype verwijderen?
notetypes-fields = Velden...
notetypes-footer = Voettekst
notetypes-header = Koptekst
notetypes-note-types = Aantekeningstypes
notetypes-options = Instellingen…
notetypes-please-add-another-note-type-first = Gelieve eerst een ander aantekeningstype toe te voegen.
