profiles-anki-could-not-read-your-profile = Anki kon uw profielgegevens niet lezen. De venstergrootten en uw sync-logingegevens vergeten.
profiles-anki-could-not-rename-your-profile = Anki kon uw profiel niet hernoemen omdat het de profielmap niet kon hernoemen. Controleer of u schrijfrechten heeft op de map Documenten/Anki en of deze map niet in gebruik is, en probeer het opnieuw.
profiles-folder-already-exists = Map bestaat al.
profiles-open = Openen
profiles-open-backup = Open back-up...
profiles-please-remove-the-folder-and = Probeer de map { $val } te verwijderen en probeer opnieuw.
profiles-profile-corrupt = Profiel corrupt
profiles-profiles = Profielen
profiles-quit = Beëindigen
profiles-user-1 = Gebruiker 1
