qt-accel-about = درباره...
qt-accel-about-mac = درباره‌‌‌ٔ انکی...
qt-accel-cards = کارت‌ها
qt-accel-check-database = بررسی دیتابیس
qt-accel-check-media = بررسی رسانه ...
qt-accel-edit = ویرایش
qt-accel-exit = خروج
qt-accel-export = صادرکردن...
qt-accel-export-notes = صادر کردن یادداشت‌ها...
qt-accel-file = فایل
qt-accel-filter = فیلتر
qt-accel-find = جستجو
qt-accel-find-and-replace = یافتن و جایگزین نمودن...
qt-accel-find-duplicates = یافتن تکراری‌ها...
qt-accel-go = برو‌
qt-accel-guide = راهنما...
qt-accel-help = کمک‌
qt-accel-import = وارد کردن...
qt-accel-info = اطلاعات...
qt-accel-invert-selection = وارونه کردن انتخاب شده‌ها
qt-accel-next-card = کارت بعدی
qt-accel-note = یادداشت
qt-accel-notes = یادداشت‌ها
qt-accel-preferences = تنظیمات...
qt-accel-previous-card = کارت قبلی
qt-accel-select-all = انتخاب همه
qt-accel-select-notes = انتخاب یادداشت‌ها
qt-accel-support-anki = پشتیبانی از آنکی...
qt-accel-switch-profile = تغییر پروفایل
qt-accel-tools = ابزارها
qt-accel-undo = برگرداندن
qt-accel-redo = انجام دوباره
qt-accel-set-due-date = انتخاب موعد مرور
qt-accel-forget = فراموش کردن
qt-accel-view = نما
qt-accel-full-screen = فعال کردن تمام صفحه
qt-accel-layout = چیدمان
qt-accel-layout-auto = خودکار
qt-accel-layout-vertical = عمودی
qt-accel-layout-horizontal = افقی
qt-accel-zoom-in = بزرگ کردن
qt-accel-zoom-out = کوچک کردن
qt-accel-reset-zoom = برگرداندن بزرگنمایی
qt-accel-toggle-sidebar = نمایش/مخفی‌کردن نوار کناری
qt-accel-zoom-editor-in = بزرگ کردن ویرایشگر
qt-accel-zoom-editor-out = کوچک کردن ویرایشگر
qt-accel-create-backup = ایجاد پیشتیبان
qt-accel-load-backup = و بازگردانی نسخهٔ پشتیبان
qt-accel-upgrade-downgrade = ارتقا/کاهش
