"use client";

import { useEffect, useMemo, useState } from "react";

import { browseNotes, deleteNote, setCardStatus, updateNote } from "@/lib/db/client";
import type { BrowseNotesResult, BrowserCard, BrowserNote, DeckSummary } from "@/lib/db/types";

function errorMessage(error: unknown) {
  return error instanceof Error ? error.message : String(error);
}

function modifiedDate(seconds: number) {
  return new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(seconds * 1000));
}

function stateLabel(card: BrowserCard) {
  if (card.status === "suspended") return "Suspended";
  if (card.status === "buried") return "Buried";
  return ({ new: "New", learning: "Learning", review: "Review", relearning: "Relearning" })[card.state];
}

export function CardBrowser({ decks, onCollectionChanged }: {
  decks: DeckSummary[];
  onCollectionChanged: () => Promise<void>;
}) {
  const [query, setQuery] = useState("");
  const [deckId, setDeckId] = useState("");
  const [result, setResult] = useState<BrowseNotesResult | null>(null);
  const [selected, setSelected] = useState<BrowserNote | null>(null);
  const [fields, setFields] = useState<string[]>([]);
  const [tags, setTags] = useState("");
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [busyCardId, setBusyCardId] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);

  const selectedDeckId = useMemo(() => deckId ? Number(deckId) : null, [deckId]);

  const load = async (offset = 0, append = false) => {
    setLoading(true);
    setError(null);
    try {
      const next = await browseNotes(query, selectedDeckId, offset);
      setResult((current) => append && current
        ? { ...next, notes: [...current.notes, ...next.notes] }
        : next);
    } catch (error) {
      setError(errorMessage(error));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    let cancelled = false;
    void browseNotes("", null, 0).then((initial) => {
      if (!cancelled) setResult(initial);
    }).catch((error) => {
      if (!cancelled) setError(errorMessage(error));
    }).finally(() => {
      if (!cancelled) setLoading(false);
    });
    return () => { cancelled = true; };
  }, []);

  const chooseNote = (note: BrowserNote) => {
    setSelected(note);
    setFields([...note.fields]);
    setTags(note.tags.join(" "));
    setError(null);
    setNotice(null);
  };

  const search = (event: React.FormEvent) => {
    event.preventDefault();
    setSelected(null);
    setNotice(null);
    void load();
  };

  const save = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!selected || busy) return;
    setBusy(true);
    setError(null);
    try {
      await updateNote(selected.id, fields, tags.split(/[\s,]+/).filter(Boolean));
      setSelected(null);
      setNotice("Note saved.");
      await Promise.all([load(), onCollectionChanged()]);
    } catch (error) {
      setError(errorMessage(error));
    } finally {
      setBusy(false);
    }
  };

  const remove = async () => {
    if (!selected || busy || !window.confirm("Delete this note and all cards generated by it? This cannot be undone.")) return;
    setBusy(true);
    setError(null);
    try {
      await deleteNote(selected.id);
      setSelected(null);
      setNotice("Note deleted.");
      await Promise.all([load(), onCollectionChanged()]);
    } catch (error) {
      setError(errorMessage(error));
    } finally {
      setBusy(false);
    }
  };

  const changeCardStatus = async (card: BrowserCard, status: BrowserCard["status"]) => {
    if (busyCardId !== null) return;
    setBusyCardId(card.id);
    setError(null);
    try {
      await setCardStatus(card.id, status);
      const update = (note: BrowserNote) => ({
        ...note,
        cards: note.cards.map((candidate) => candidate.id === card.id ? { ...candidate, status } : candidate)
      });
      setSelected((current) => current ? update(current) : current);
      setResult((current) => current ? { ...current, notes: current.notes.map(update) } : current);
      await onCollectionChanged();
    } catch (error) {
      setError(errorMessage(error));
    } finally {
      setBusyCardId(null);
    }
  };

  if (selected) {
    return (
      <section className="browser-editor">
        <div className="browser-editor-heading">
          <button className="back-to-results" type="button" disabled={busy} onClick={() => { setSelected(null); setError(null); }}>‹ Results</button>
          <span>{selected.notetypeName}</span>
        </div>
        <form className="panel form-panel" onSubmit={save}>
          <div className="form-heading"><strong>Edit note</strong><span>Modified {modifiedDate(selected.modified)}</span></div>
          {selected.fieldNames.map((name, index) => (
            <div className="field-editor" key={`${selected.id}-${index}`}>
              <label htmlFor={`browser-field-${index}`}>{name}</label>
              <textarea id={`browser-field-${index}`} rows={index === 0 ? 5 : 4} value={fields[index] ?? ""}
                onChange={(event) => setFields((current) => current.map((value, fieldIndex) => fieldIndex === index ? event.target.value : value))} />
            </div>
          ))}
          <label htmlFor="browser-tags">Tags</label>
          <input id="browser-tags" value={tags} onChange={(event) => setTags(event.target.value)}
            placeholder="Separate tags with spaces" />
          <p className="muted browser-raw-help">Imported formatting is stored as HTML. Existing markup and media references are preserved unless you edit them.</p>
          {error && <p className="form-error" role="alert">{error}</p>}
          <div className="browser-save-actions">
            <button className="primary-button" type="submit" disabled={busy || !fields[0]?.trim()}>{busy ? "Saving…" : "Save note"}</button>
            <button className="danger-button" type="button" disabled={busy} onClick={() => void remove()}>Delete note</button>
          </div>
        </form>

        <section className="panel browser-cards" aria-label="Cards generated by this note">
          <div className="form-heading"><strong>Cards</strong><span>{selected.cards.length}</span></div>
          {selected.cards.map((card) => (
            <article className="browser-card" key={card.id}>
              <div>
                <strong>{card.templateName}</strong>
                <span>{card.deckName} · {stateLabel(card)} · {card.reviews} reviews</span>
              </div>
              <div className="browser-card-actions">
                {card.status === "active" ? <>
                  <button type="button" disabled={busyCardId !== null} onClick={() => void changeCardStatus(card, "suspended")}>Suspend</button>
                  <button type="button" disabled={busyCardId !== null} onClick={() => void changeCardStatus(card, "buried")}>Bury</button>
                </> : <>
                  <button type="button" disabled={busyCardId !== null} onClick={() => void changeCardStatus(card, "active")}>
                    {card.status === "buried" ? "Unbury" : "Resume"}
                  </button>
                  {card.status === "buried"
                    ? <button type="button" disabled={busyCardId !== null} onClick={() => void changeCardStatus(card, "suspended")}>Suspend</button>
                    : <button type="button" disabled={busyCardId !== null} onClick={() => void changeCardStatus(card, "buried")}>Bury</button>}
                </>}
              </div>
            </article>
          ))}
        </section>
      </section>
    );
  }

  return (
    <section className="card-browser">
      <form className="panel browser-search" onSubmit={search}>
        <label htmlFor="browser-query">Search cards and notes</label>
        <div className="browser-search-row">
          <input id="browser-query" type="search" value={query} maxLength={200}
            onChange={(event) => setQuery(event.target.value)} placeholder="Text or tag" />
          <button className="primary-button" type="submit" disabled={loading}>{loading ? "Loading…" : "Search"}</button>
        </div>
        <label htmlFor="browser-deck">Deck</label>
        <select id="browser-deck" value={deckId} onChange={(event) => setDeckId(event.target.value)}>
          <option value="">All decks</option>
          {decks.map((deck) => <option key={deck.id} value={deck.id}>{deck.name}</option>)}
        </select>
      </form>

      {error && <p className="panel form-error" role="alert">{error}</p>}
      {notice && <p className="panel browser-notice" role="status">{notice}</p>}
      {result && <div className="browser-result-heading">
        <strong>{result.total.toLocaleString()} {result.total === 1 ? "note" : "notes"}</strong>
        <span className="muted">Newest edits first</span>
      </div>}
      {result?.notes.length === 0 && !loading && <div className="panel browser-empty"><strong>No matching notes</strong><span className="muted">Try different text or choose another deck.</span></div>}
      <div className="browser-note-list">
        {result?.notes.map((note) => {
          const deckNames = [...new Set(note.cards.map((card) => card.deckName))];
          const inactive = note.cards.filter((card) => card.status !== "active").length;
          return (
            <button className="browser-note-row" type="button" key={note.id} onClick={() => chooseNote(note)}>
              <span className="browser-note-preview">{note.preview}</span>
              <span className="browser-note-meta">{note.notetypeName} · {deckNames.join(", ") || "No cards"} · {note.cards.length} {note.cards.length === 1 ? "card" : "cards"}</span>
              {note.tags.length > 0 && <span className="browser-note-tags">{note.tags.map((tag) => <span key={tag}>{tag}</span>)}</span>}
              {inactive > 0 && <span className="browser-inactive">{inactive} suspended/buried</span>}
            </button>
          );
        })}
      </div>
      {result?.hasMore && <button className="secondary-button browser-load-more" type="button" disabled={loading}
        onClick={() => void load(result.notes.length, true)}>{loading ? "Loading…" : "Load more"}</button>}
    </section>
  );
}
