editing-actual-size = Tunjukkan ukuran sebenarnya (On/Off)
editing-add-media = Tambahkan Media
editing-align-left = Sejajarkan ke kiri
editing-align-right = Sejajarkan ke kanan
editing-an-error-occurred-while-opening = Terjadi eror saat membuka { $val }
editing-attach-picturesaudiovideo = Lampirkan gambar/audio/video
editing-bold-text = Teks cetak tebal
editing-cards = Kartu-kartu
editing-center = Tengah
editing-change-color = Ubah warna
editing-cloze-deletion = Penghapusan rumpang (kartu baru)
editing-cloze-deletion-repeat = Penghapusan rumpang (kartu yang sama)
editing-copy-image = Salin gambar
editing-couldnt-record-audio-have-you-installed = Tidak dapat merekam audio. Apakah Anda sudah menginstal 'lame'?
editing-customize-card-templates = Sesuaikan Templat Kartu
editing-customize-fields = Sesuaikan bidang
editing-cut = Potong
editing-double-click-image = gambar klik dua kali
editing-double-click-to-expand = klik dua kali untuk memperluas
editing-double-click-to-collapse = klik dua kali untuk menutup
editing-edit-current = Ubah Saat ini
editing-edit-html = Ubah HTML
editing-fields = Bidang
editing-float-left = Mengapung ke kiri
editing-float-right = Mengapung ke kanan
editing-float-none = Tidak mengapung
editing-indent = Tambah inden
editing-italic-text = Teks miring
editing-jump-to-tags-with-ctrlandshiftandt = Langsung menuju tag dengan Ctrl+Shift+T
editing-justify = Ratakan
editing-latex = LaTeX
editing-latex-equation = Persamaan LaTeX
editing-latex-math-env = Lingkungan matematika LaTeX.
editing-mathjax-block = Blok MathJax
editing-mathjax-chemistry = Kimia MathJax
editing-mathjax-inline = MathJax inline
editing-mathjax-placeholder = Tekan { $accept } untuk menerima, { $newline } untuk baris baru.
editing-media = Media
editing-open-image = Buka gambar
editing-show-in-folder = Tunjukkan foldernya
editing-ordered-list = Daftar terurut
editing-outdent = Kurangi inden
editing-paste = Tempel
editing-record-audio = Rekam audio
editing-remove-formatting = Hapus format
editing-restore-original-size = Kembalikan ke ukuran semula
editing-select-remove-formatting = Pilih format yang ingin dihapus
editing-show-duplicates = Tunjukkan Duplikat
editing-subscript = Subscript
editing-superscript = Superscript
editing-tags = Tag
editing-tags-add = Tambahkan tag
editing-tags-copy = Salin tag
editing-tags-remove = Hapus tag
editing-tags-select-all = Pilih semua tag
editing-text-color = Warna teks
editing-text-highlight-color = Warna teks yang disorot
editing-to-make-a-cloze-deletion-on = Untuk membuat penghapusan rumpang pada catatan yang sudah ada, Anda perlu mengubahnya ke tipe rumpang terlebih dahulu, melalui 'Catatan > Ubah Tipe Catatan'.
editing-toggle-html-editor = Aktifkan HTML Editor
editing-toggle-visual-editor = Aktifkan Visual Editor
editing-toggle-sticky = Alihkan tetap
editing-expand = Perluas
editing-collapse = Tutup
editing-expand-field = Perluas bidang
editing-collapse-field = Tutup bidang
editing-underline-text = Garisbawahi teks
editing-unordered-list = Daftar tidak terurut
editing-warning-cloze-deletions-will-not-work = Peringatan, penghapusan rumpang tidak akan berfungsi sampai Anda mengubah tipe di bagian atas menjadi rumpang.
editing-mathjax-preview = Pratinjau MathJax
editing-shrink-images = Perkecil gambar
editing-close-html-tags = Tutup otomatis tag HTML
editing-from-clipboard = Dari papan klip
editing-alignment = Penyelarasan
editing-equations = Persamaan
editing-no-image-found-on-clipboard = Tidak ada gambar yang ditemukan di papan klip.
editing-image-occlusion-mode = Mode Oklusi Gambar
editing-image-occlusion-zoom-out = Perkecil
editing-image-occlusion-zoom-in = Perbesar
editing-image-occlusion-zoom-reset = Reset tampilan
editing-image-occlusion-toggle-translucent = Aktifkan Transparansi
editing-image-occlusion-delete = Hapus
editing-image-occlusion-duplicate = Duplikat
editing-image-occlusion-group = Pemilihan grup
editing-image-occlusion-ungroup = Pemilihan pembubaran grup
editing-image-occlusion-select-all = Pilih semua
editing-image-occlusion-alignment = Penyelarasan
editing-image-occlusion-align-left = Sejajarkan ke kiri
editing-image-occlusion-align-h-center = Sejajarkan Pusat Horizontal
editing-image-occlusion-align-right = Sejajarkan ke kanan
editing-image-occlusion-align-top = Sejajarkan ke atas
editing-image-occlusion-align-v-center = Sejajarkan Pusat Vertikal
editing-image-occlusion-align-bottom = Sejajarkan ke bawah
editing-image-occlusion-select-tool = PilihPilih
editing-image-occlusion-zoom-tool = Zoom
editing-image-occlusion-rectangle-tool = Persegi panjang
editing-image-occlusion-ellipse-tool = Elips
editing-image-occlusion-polygon-tool = Segi banyak
editing-image-occlusion-text-tool = Teks
editing-image-occlusion-fill-tool = Penuhi dengan warna
editing-image-occlusion-toggle-mask-editor = Aktifkan Mask Editor
editing-image-occlusion-reset = Atur Ulang Oklusi Gambar
editing-image-occlusion-confirm-reset = Apakah Anda yakin ingin mengatur ulang oklusi gambar ini?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML Editor
