profiles-anki-could-not-read-your-profile = Anki tidak dapat membaca data profil Anda. Ukuran jendela dan detail sinkronisasi login Anda telah dilupakan.
profiles-anki-could-not-rename-your-profile = Anki tidak dapat merubah nama profil Anda karena anki tidak dapat mengakses folder profil di media penyimpanan perangkat anda. Harap pastikan Anda memiliki izin untuk melakukan perubahan ke folder Documents/Anki dan tidak ada program selain Anki yang sedang mengakses profil folder Anda, lalu coba lagi.
profiles-folder-already-exists = Folder sudah ada.
profiles-open = Buka
profiles-open-backup = Buka cadangan...
profiles-please-remove-the-folder-and = Harap hapus folder { $val } lalu coba lagi.
profiles-profile-corrupt = Profil korup
profiles-profiles = Profil
profiles-quit = Keluar
profiles-user-1 = Pengguna 1
profiles-confirm-lang-choice = Apakah kamu yakin untuk mengubah bahasa tampilan Antarmuka Anki ke Bahasa { $lang }?
profiles-could-not-create-data-folder = Tidak dapat membuat folder data Anki. Harap lihat panduan manual bagian File Locations, dan pastikan lokasi folder tersebut tidak diatur ke hanya-baca (read-only).
profiles-prefs-corrupt-title = Preferensi korup.
profiles-prefs-file-is-corrupt = Salah file Anki yaitu prefs21.db mengalami kerusakan dan telah dibuat ulang. Jika kamu menggunakan profil lebih dari satu, harap tambah kembali profil yang hilang menggunakan nama yang sama untuk memulihkan kartu Anda yang hilang.
profiles-profile-does-not-exist = Profil yang diminta tidak ada.
profiles-creating-backup = Membuat cadangan...
profiles-backup-created = Cadangan telah dibuat.
profiles-backup-creation-failed = Cadangan gagal dibuat: { $reason }
profiles-backup-unchanged = Tidak ada perubahan semenjak cadangan terakhir.
