#!/usr/bin/env bash

set -e

html="$1"

outdir="out/coverage/typescript"
YARN="out/extracted/node/bin/yarn"

mkdir -p "$outdir"

ANKI_COVERAGE_HTML="${html:+1}" "$YARN" vitest:once \
    --coverage.enabled true \
    --coverage.provider=v8 \
    --coverage.reportsDirectory="../$outdir" \
    --coverage.thresholds.lines=5

if [ "$html" = "--html" ]; then
    echo "TypeScript coverage report: $outdir/index.html"
fi
