qt-accel-about = &A prepaus...
qt-accel-browse-and-install = &Percórrer e Installar...
qt-accel-cards = &Cartas
qt-accel-check-database = &Verificar la basa de donadas
qt-accel-check-media = Verificacion dels &mèdias...
qt-accel-edit = &Editar
qt-accel-exit = &Quitar
qt-accel-export = &Exportar...
qt-accel-file = &Fichièr
qt-accel-find = &Recercar
qt-accel-go = &Anar
qt-accel-guide = &Manual en linha (en anglés)
qt-accel-help = A&juda
qt-accel-import = &Importar…
qt-accel-info = &Info
qt-accel-invert-selection = &Inversar la seleccion
qt-accel-next-card = Carta &seguenta
qt-accel-notes = &Nòtas
qt-accel-open-addons-folder = Dobrir lo dorsièr dels empeutons
qt-accel-preferences = &Preferéncias...
qt-accel-previous-card = Carta &precedenta
qt-accel-reschedule = To&rnar planificar…
qt-accel-select-all = Seleccionar &tot
qt-accel-support-anki = &Far un don
qt-accel-switch-profile = &Cambiar de perfil
qt-accel-tools = &Aisinas
qt-accel-undo = &Anullar
