#!/bin/bash

set -e

# check author has added themselves to CONTRIBUTORS
echo "--- Checking CONTRIBUTORS"
.buildkite/linux/check_contributors

test -z "$STATE" && STATE=/state
BAZEL="bazel --output_user_root=$STATE/bazel --output_base=$STATE/bazel/anki"
BUILDARGS="--config=ci --disk_cache=$STATE/bazel/disk --repository_cache=$STATE/bazel/repo"

echo "+++ Building and testing"

# move existing node_modules into tree
test -e $STATE/node_modules && mv $STATE/node_modules .

$BAZEL test $BUILDARGS ... //rslib/linkchecker

echo "--- Running lints"
python tools/copyright_headers.py

echo "--- Cleanup"
# if tests succeed, back up node_modules folder
mv node_modules $STATE/
