adding-add-shortcut-ctrlandenter = जोड़ें (शॉर्टकट: ctrl+enter)
adding-added = जोड़े गए
adding-close-and-lose-current-input = बंद करें और वर्तमान इनपुट खो दें?
adding-edit = संपादित करें "{ $val }"
adding-history = इतिहास
adding-note-deleted = (नोट हटा दिया गया)
adding-shortcut = शॉर्टकट: { $val }
adding-the-first-field-is-empty = पहला क्षेत्र खाली है।
adding-you-have-a-cloze-deletion-note = आपके पास एक क्लोज नोटटाइप है लेकिन आपने कोई क्लोज डिलीट नहीं किया है। आगे बढ़ना?
adding-cloze-outside-cloze-notetype = क्लोज़ विलोपन का उपयोग केवल क्लोज़ नोटटाइप पर ही किया जा सकता है।
adding-cloze-outside-cloze-field = क्लोज़ हटाने का उपयोग केवल उन फ़ील्ड में किया जा सकता है जो 'क्लोज़:' फ़िल्टर का उपयोग करते हैं। यह आमतौर पर पहला क्षेत्र है।
