actions-add = Pridať
actions-blue-flag = Modrý príznak
actions-cancel = Zrušiť
actions-choose = Vybrať
actions-close = Zatvoriť
actions-copy = Kopírovať
actions-custom-study = Vlastné štúdium
actions-decks = Balíčky
actions-delete = Odstrániť
actions-export = Exportovať
actions-filter = Filtrovať
actions-green-flag = Zelený príznak
actions-help = Pomocník
actions-import = Importovať
actions-manage = Spravovať...
actions-name = Názov:
actions-new = Nové
actions-new-name = Nový názov:
actions-options = Nastavenia
actions-options-for = Nastavenia pre { $val }
actions-orange-flag = Oranžový príznak
actions-preview = Náhľad
actions-rebuild = Znovu zostaviť
actions-red-flag = Červený príznak
actions-rename = Premenovať
actions-rename-deck = Premenovať balíček
actions-replay-audio = Prehrať zvuk
actions-reposition = Zmeniť poradie
actions-save = Uložiť
actions-search = Hľadať
actions-shortcut-key = Klávesová skratka: { $val }
actions-suspend-card = Dať kartu bokom
actions-processing = Spracováva sa...
