card-stats-added = Pridané
card-stats-first-review = Prvé opakovanie
card-stats-latest-review = Posledné opakovanie
card-stats-ease = Jednoduchosť
card-stats-review-count = Opakovania
card-stats-lapse-count = Zabudnuté
card-stats-average-time = Priemerný čas
card-stats-total-time = Celkový čas
card-stats-new-card-position = Pozícia
card-stats-card-template = Typ karty
card-stats-note-type = Typ poznámky
card-stats-deck-name = Balíček
card-stats-note-id = ID poznámky
card-stats-card-id = ID karty
card-stats-review-log-rating = Hodnotenie
card-stats-review-log-type = Typ
card-stats-review-log-date = Dátum
card-stats-review-log-time-taken = Čas
card-stats-review-log-type-learn = Učené
card-stats-review-log-type-review = Opakovať
card-stats-review-log-type-relearn = Zabudnuté
card-stats-review-log-type-filtered = Filtrované:
card-stats-review-log-type-rescheduled = Preplánovať
