custom-study-all-cards-in-random-order-dont = Všetky kartičky v náhodnom poradí (neprehadzovať)
custom-study-all-review-cards-in-random-order = Všetky kartičky na opakovanie v náhodnom poradí
custom-study-cards = kariet
custom-study-cards-from-the-deck = kariet z balíčka
custom-study-choose-tags = Vybrať štítky
custom-study-custom-study-session = Vlastné štúdium
custom-study-due-cards-only = Iba karty na skúšanie
custom-study-increase-todays-new-card-limit = Zvýšiť dnešný limit nových kariet
custom-study-increase-todays-new-card-limit-by = Zvýšiť dnešný limit nových kariet o
custom-study-increase-todays-review-card-limit = Zvýšiť dnešný limit opakovaných kariet
custom-study-increase-todays-review-limit-by = Zvýšiť dnešný limit opakovaných kariet o
custom-study-new-cards-in-deck-over-today = Nové karty v balíčku prevyšujúce dnešný limit: { $val }
custom-study-new-cards-only = Iba nové karty
custom-study-no-cards-matched-the-criteria-you = Žiadna karta nezodpovedá zadaným kritériam.
custom-study-ok = OK
custom-study-preview-new-cards = Náhľad nových kariet
custom-study-preview-new-cards-added-in-the = Náhľad nových kariet pridaných za posledných
custom-study-require-one-or-more-of-these = Vyžadovať jeden alebo viac z týchto štítkov:
custom-study-review-ahead = Opakovať dopredu
custom-study-review-ahead-by = Opakovať dopredu o
custom-study-review-cards-forgotten-in-last = Zopakovať karty zabudnuté za posledných
custom-study-review-forgotten-cards = Opakovať zabudnuté karty
custom-study-reviews-due-in-deck-over-today = Nevybavené opakovania v balíčku nad dnešný limit: { $val }
custom-study-select = Vybrať
custom-study-select-tags-to-exclude = Vynechať štítky:
custom-study-selective-study = Vlastné štúdium
custom-study-study-by-card-state-or-tag = Študovať podľa stavu karty alebo štítku
