preferences-anki-21-scheduler-beta = Anki 2.1 plánovač (beta)
preferences-automatically-sync-on-profile-openclose = Automaticky synchronizovať pri otvorení a zavretí profilu
preferences-backups = Zálohy
preferences-backups2 = záloh
preferences-backupsanki-will-create-a-backup-of = <b>Zálohy</b><br>Anki vytvorí zálohu vašej zbierky pri každom zatvorení alebo synchronizácii.
preferences-basic = Základný
preferences-change-deck-depending-on-note-type = Zmeniť balíček podľa typu poznámky
preferences-changes-will-take-effect-when-you = Zmeny sa prejavia až po reštartovaní Anki.
preferences-hardware-acceleration-faster-may-cause-display = Hardvérová akcelerácia (rýchlejšie, môže spôsobiť problémy so zobrazením)
preferences-hours-past-midnight = hodín po polnoci
preferences-interface-language = Jazyk rozhrania:
preferences-interrupt-current-audio-when-answering = Po odpovedi prerušiť aktuálne prehrávaný zvuk
preferences-keep = Ponechať
preferences-learn-ahead-limit = Učiť sa skôr, do
preferences-mins = min
preferences-network = Sieť
preferences-next-day-starts-at = Ďalší deň začína o
preferences-night-mode = Nočný režim
preferences-note-media-is-not-backed-up = Upozornenie: Médiá nie sú zálohované. Prosím, vytvorte pre istotu pravidelné zálohovanie vášho Anki priečinka.
preferences-on-next-sync-force-changes-in = Pri ďalšej synchronizácii vynútiť zmeny jedným smerom
preferences-paste-clipboard-images-as-png = Vložiť obrázok zo schránky ako PNG
preferences-paste-without-shift-key-strips-formatting = Vložiť bez klávesu shift bez formátovania
preferences-please-restart-anki-to-complete-language = Pre dokončenie zmeny jazyka, prosím, Anki reštartujte.
preferences-preferences = Nastavenia
preferences-scheduling = Preplánovať
preferences-show-learning-cards-with-larger-steps = Zobraziť karty na učenie s väčšími krokmi pred opakovaniami
preferences-show-next-review-time-above-answer = Zobraziť čas budúceho opakovania nad tlačidlami odpovedí
preferences-show-play-buttons-on-cards-with = Zobrazovať tlačidlá prehrávania na kartách, ktoré obsahujú zvuk
preferences-show-remaining-card-count-during-review = Zobrazovať počet zostávajúcich kariet počas opakovania
preferences-some-settings-will-take-effect-after = Niektoré nastavenia sa prejavia až po reštarte Anki.
preferences-synchronisation = <b>Synchronizácia</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Synchronizácia</b><br> Nie je momentálne povolená. Povolíte ju kliknutím na tlačidlo 'Synchronizácia' v hlavnom okne.
preferences-synchronize-audio-and-images-too = Synchronizovať zvuk aj obrázky
preferences-this-will-reset-any-cards-in = Týmto obnovíte všetky karty v procese učenia, vyprázdnite filtrované balíky a zmeníte verziu plánovača. Pokračovať?
preferences-timebox-time-limit = Limit pre časový box
preferences-user-interface-size = Veľkosť používateľského rozhrania
preferences-when-adding-default-to-current-deck = Pri pridávaní je automaticky nastavený aktuálny balíček
preferences-you-can-restore-backups-via-fileswitch = Môžete obnoviť zo zálohy pomocou Súbor>Prepnúť profil.
