custom-study-all-cards-in-random-order-dont = porsi lo cunso lu'i ro karda to na basti fi lo ka tcika toi
custom-study-all-review-cards-in-random-order = porsi lo cunso lo selcmi be ro karda poi na'e cnino
custom-study-cards = lo karda
custom-study-cards-from-the-deck = karda pe lo karda selcmi
custom-study-choose-tags = cuxna pa se tcita
custom-study-custom-study-session = macnu tadni
custom-study-due-cards-only = karda je cu morji jai se bilga po'o
custom-study-increase-todays-new-card-limit = stika lo cabdei jimte be lo se zilkancu be lo'i karda poi cnino
custom-study-increase-todays-new-card-limit-by = .i stika lo cabdei jimte be lo se zilkancu be lo'i karda poi cnino vau li
custom-study-increase-todays-review-card-limit = stika lo cabdei jimte be lo se zilkancu be lo'i karda poi morji jai se bilga
custom-study-increase-todays-review-limit-by = .i stika lo cabdei jimte be lo se zilkancu be lo'i karda poi morji jai se bilga vau li
custom-study-new-cards-only = cnino
custom-study-no-cards-matched-the-criteria-you = .i no karda ckaji lo se sisku
custom-study-ok = .i'e
custom-study-preview-new-cards = purzga ro karda poi cnino
custom-study-preview-new-cards-added-in-the = purzga lo karda poi cnino poi se jmina ca lo ro moi
custom-study-require-one-or-more-of-these = nu nitcu lo ka su'o da pe di'e tcita ce'u
custom-study-review-forgotten-cards = nu tadni lo karda poi te tolmo'i
custom-study-select = cuxna
custom-study-select-tags-to-exclude = nu nitcu lo ka no da pe di'e tcita ce'u
