notetypes-front-field = crane
notetypes-back-field = trixe
notetypes-add-reverse-field = jmina lo fatne
notetypes-basic-name = sampu
notetypes-cloze-name = mipri cipra
notetypes-basic-type-answer-name = sampu je cu nitcu lo nu do samci'a lo te spuda
notetypes-card-2-name = re moi lo'i karda klesi
notetypes-card-1-name = pa moi lo'i karda klesi
notetypes-add = jmina la'o zoi. { $val } .zoi
notetypes-add-note-type = jmina pa karda datni klesi
notetypes-cards = karda klesi
notetypes-clone = ve fukpi la'o zoi. { $val } .zoi
notetypes-copy = { $val } fukpi
notetypes-delete-this-note-type-and-all = .i pa da poi karda datni klesi zo'u xu do djica lo nu vimcu da je ro karda pe da
notetypes-delete-this-unused-note-type = .i pa da poi karda datni klesi je cu se pilno no da zo'u xu do djica lo nu vimcu da
notetypes-fields = datnyvau
notetypes-footer = lo fanmo
notetypes-header = galraipau
notetypes-note-types = karda datni klesi
notetypes-options = te tcimi'e
notetypes-type = klesi
