qt-misc-addon-will-be-installed-when-a = .i samtcise'a da ba lo nu samymo'i pa pilno datni
qt-misc-addons = se samtcise'a
qt-misc-all-cards-notes-and-media-for = .i ba vimcu ro karda je ro karda datni je ro ganvi vu'o pe lo pilno datni .i xu do birti
qt-misc-anki-updatedanki-has-been-released = <h1>.i la .ankis. cu cnino</h1>.i la .ankis. xi { $val } co'a gubni<br><br>
qt-misc-automatic-syncing-and-backups-have-been = .i ca'o lo nu cikre cu ganda lo ka ce'u datni sarxe zmiku ja cu zmiku cupra lo nurfu'i .i lo nu za'u re'u katci cu se rinka lo nu to'e samymo'i lo pilno datni ja lo nu za'u re'u katcygau la .ankis.
qt-misc-backing-up = .i ca'o cupra pa nurfu'i
qt-misc-browse = liste
qt-misc-change-note-type-ctrlandn = basti fi lo ka karda datni klesi (Ctrl+N)
qt-misc-check-the-files-in-the-media = nu cipcta lo datnyvei poi se datnyveimei lo srana be lo ganvi
qt-misc-choose-deck = cuxna pa karda selcmi
qt-misc-choose-note-type = cuxna pa karda datni klesi
qt-misc-closing = .i ca'o mipri
qt-misc-configure-interface-language-and-options = nu tcimi'e fi tu'a lo sazycimde je lo bangu be lo sazycimde
qt-misc-copy-to-clipboard = fukra'e
qt-misc-create-filtered-deck = zbasu pa se julne karda selcmi
qt-misc-debug-console = samcfisisku tutci
qt-misc-deck-will-be-imported-when-a = .i nerbei pa karda selcmi ba lo nu samymo'i pa pilno datni
qt-misc-empty-cards = karda je cu kunti
qt-misc-error-during-startup = .i la'e di'e nabmi fi lo nu katcygau { $val }
qt-misc-filtered-deck = { $val } moi lo'i se julne karda selcmi
qt-misc-loading = .i ca'o samymo'i
qt-misc-manage = nu jitro
qt-misc-manage-note-types = nu jitro lo karda datni klesi
qt-misc-name-exists = .i lo cmene xa'o zasti
qt-misc-non-unicode-text = sei sa'a na'e me la .iunikod. ku lerpoi
qt-misc-please-connect-a-microphone-and-ensure = .i ko jongau pa snaveitci goi sy. .i ko birti lo du'u no samtci poi drata ca'o pilno sy.
qt-misc-please-ensure-a-profile-is-open = .i ko birti lo du'u ga je mo'u samymo'i pa pilno datni gi la .ankis. na'e zuktce kei ce'o cu za'u re'u troci
qt-misc-please-select-1-card = .i ko cuxna pa je nai za'u pa karda
qt-misc-please-select-a-deck = .i ko cuxna pa karda selcmi
qt-misc-please-use-fileimport-to-import-this = .i do bilga lo ka ce'u terca'a la nu nerbei pe la datnyvau vau noi rinka lo nu nerbei lo datnyvau
qt-misc-processing = .i ca'o gunka
qt-misc-replace-your-collection-with-an-earlier = .i xu do djica lo nu pa nurfu'i cu basti lo ca karda selcmi selcmi
qt-misc-resume-now = co'u denpa
qt-misc-revert-to-backup = pa nurfu'i cu basti
qt-misc-reverted-to-state-prior-to = .i mo'u xruti fo la'o zoi. { $val } .zoi
qt-misc-segoe-ui = "Segoe UI"
qt-misc-shift-key-was-held-down-skipping = .i la'o zoi. Shift .zoi katci .i ca'o na zmiku lo nu datni sarxe ja cu samymo'i lo se samtcise'a
qt-misc-stats = datni
qt-misc-study-deck = tadni pa karda selcmi
qt-misc-sync = datni sarxe
qt-misc-there-must-be-at-least-one = .i sarcu fa lo du'u da pilno datni
qt-misc-this-file-exists-are-you-sure = .i pa datnyvei cu mintu .i xu do birti lo du'u do djica lo nu basti dy.
qt-misc-undo = xruti
qt-misc-undo2 = xruti fo la'o zoi. { $val } .zoi
qt-misc-waiting-for-editing-to-finish = .i ca'o denpa lo nu mo'u basygau
qt-misc-would-you-like-to-download-it = .i xu do djica lo du'u ca kibycpa
qt-misc-your-collection-file-appears-to-be = .i lo do karda selcmi selcmi datnyvei cu simlu lo ka ce'u spofu .i ky sy sy dy. kakne ri lo ka ca lo nu la .ankis. cu katci kei ce'u se fukpu'i ja cu se muvgau ja lo ka vreji ce'u fo pa samseltcana co'e ja pa kibro co'e .i ga na ja lo nabmi cu renvi lo nu do krefu katci lo do skami gi do bilga lo ka gau ce'u samymo'i pa zmiku nurfu'i pe lo pilno datni
qt-misc-second = { $count ->
   *[other] snidu li { $count }
  }
