qt-accel-about = &אודות...
qt-accel-about-mac = אודות אנקי...
qt-accel-cards = &כרטיסים
qt-accel-check-database = &בדוק מסד נתונים
qt-accel-check-media = בדוק &מדיה...
qt-accel-edit = &עריכה
qt-accel-exit = י&ציאה
qt-accel-export = &ייצוא...
qt-accel-export-notes = &ייצא רשומות
qt-accel-file = &קובץ
qt-accel-filter = ס&נן
qt-accel-find = &חיפוש
qt-accel-find-and-replace = חיפוש וה&חלפה...
qt-accel-find-duplicates = איתור &כפילויות...
qt-accel-go = &עבור אל
qt-accel-guide = &מדריך...
qt-accel-help = &עזרה
qt-accel-import = &ייבוא...
qt-accel-info = &מידע...
qt-accel-invert-selection = &הפוך בחירה
qt-accel-next-card = &כרטיס הבא
qt-accel-note = ה&ערה
qt-accel-notes = &רשומות
qt-accel-preferences = &העדפות...
qt-accel-previous-card = &כרטיס קודם
qt-accel-select-all = בחר &הכל
qt-accel-select-notes = בחר &רשומות
qt-accel-support-anki = &תמוך ב-Anki...‏
qt-accel-switch-profile = &החלף משתמש
qt-accel-tools = &כלים
qt-accel-undo = &בטל
qt-accel-redo = ובצע שוב
qt-accel-set-due-date = ה&גדר תאריך יעד...
qt-accel-forget = ש&כח
qt-accel-view = &תצוגה
qt-accel-full-screen = &מצב חלון/ מסך מלא
qt-accel-layout = &סדר תצוגה
qt-accel-layout-auto = &אוטומטי
qt-accel-layout-vertical = &לאורך
qt-accel-layout-horizontal = &לרוחב
qt-accel-zoom-in = &הגדל תצוגה
qt-accel-zoom-out = הקטן &תצוגה
qt-accel-reset-zoom = &אפס גודל תצוגה
qt-accel-toggle-sidebar = הפעל/כבה סרגל צד
qt-accel-zoom-editor-in = הגדל &תצוגת עורך
qt-accel-zoom-editor-out = &הקטן תצוגת עורך
qt-accel-create-backup = יצירת &גיבוי
qt-accel-load-backup = &חזור לגיבוי
qt-accel-upgrade-downgrade = שדרוג/שדרוג לאחור
