qt-accel-about = &Тиркеме жөнүндө...
qt-accel-about-mac = Anki жөнүндө
qt-accel-cards = &Карталар
qt-accel-check-database = &Базаны текшерүү
qt-accel-check-media = &Медианы текшерүү
qt-accel-edit = &Түзөтүү
qt-accel-exit = Чы&гуу
qt-accel-export = &Экспорттоо...
qt-accel-export-notes = &Эскертмелерди экспорттоо...
qt-accel-file = &Файл
qt-accel-filter = Филь&тр
qt-accel-find = &Издөө
qt-accel-find-and-replace = Табуу жана &алмаштыруу...
qt-accel-find-duplicates = &Дубликаттарды табуу...
qt-accel-go = &Өтүү
qt-accel-guide = &Колдонмо
qt-accel-help = &Жардам
qt-accel-import = &Импорттоо...
qt-accel-info = &Маалымат...
qt-accel-invert-selection = Тандоону &тескерилөө
qt-accel-next-card = &Кийинки карта
qt-accel-note = &Эскертме
qt-accel-notes = &Эскертмелер
qt-accel-preferences = &Жөндөөлөр
qt-accel-previous-card = &Мурунку карта
qt-accel-select-all = &Баарын тандоо
qt-accel-select-notes = Эскертмелерди &тандоо
qt-accel-support-anki = Anki'ни &колдоо
qt-accel-switch-profile = &Профилди которуу
qt-accel-tools = &Аспаптар
qt-accel-undo = &Артка кайтаруу
qt-accel-redo = &Алдыга кайтаруу
qt-accel-set-due-date = Аткаруу &мөөнөтүн коюу...
qt-accel-forget = &Баштапкы абалга кайтаруу
qt-accel-view = &Көрүнүш
qt-accel-full-screen = &Толук экранга которуу
qt-accel-layout = &Жайгашуу
qt-accel-layout-auto = &Авто
qt-accel-layout-vertical = &Вертикалдуу
qt-accel-layout-horizontal = &Горизонталдуу
qt-accel-zoom-in = &Чоңойтуу
qt-accel-zoom-out = &Кичирейтүү
qt-accel-reset-zoom = Масштабды &баштапкы абалга келтирүү
qt-accel-toggle-sidebar = Каптал тилкени которуу
qt-accel-zoom-editor-in = Редакторду чоңо&йтуу
qt-accel-zoom-editor-out = Редакторду &кичирейтүү
qt-accel-create-backup = Камдык &көчүрмө түзүү
qt-accel-load-backup = Камдык көчүрмөгө &кайтаруу
qt-accel-upgrade-downgrade = Жаңыртуу/Эски версияга кайтуу
