qt-accel-about = &О программе…
qt-accel-about-mac = Об Anki...
qt-accel-cards = &Карточки
qt-accel-check-database = &Проверить базу данных
qt-accel-check-media = Проверить &медиафайлы...
qt-accel-edit = &Редактирование
qt-accel-exit = &Выход
qt-accel-export = &Экспортировать…
qt-accel-export-notes = &Экспортировать записи...
qt-accel-file = &Файл
qt-accel-filter = Филь&тр
qt-accel-find = &Найти
qt-accel-find-and-replace = &Найти и заменить...
qt-accel-find-duplicates = Найти &повторы...
qt-accel-go = Пе&рейти
qt-accel-guide = &Руководство…
qt-accel-help = &Справка
qt-accel-import = &Импортировать…
qt-accel-info = &Информация...
qt-accel-invert-selection = &Инвертировать выделение
qt-accel-next-card = &Следующая карточка
qt-accel-note = &Запись
qt-accel-notes = &Записи
qt-accel-preferences = &Настройки…
qt-accel-previous-card = &Предыдущая карточка
qt-accel-select-all = &Выделить всё
qt-accel-select-notes = Выбрать &записи
qt-accel-support-anki = &Поддержать Anki…
qt-accel-switch-profile = Сменить профиль
qt-accel-tools = &Инструменты
qt-accel-undo = &Отменить
qt-accel-redo = &Повторить
qt-accel-set-due-date = Задать срок...
qt-accel-forget = &Сбросить...
qt-accel-view = &Вид
qt-accel-full-screen = &Полный экран
qt-accel-layout = &Макет
qt-accel-layout-auto = &Авто
qt-accel-layout-vertical = &Вертикальный
qt-accel-layout-horizontal = &Горизонтальный
qt-accel-zoom-in = &Приблизить
qt-accel-zoom-out = &Отдалить
qt-accel-reset-zoom = &Сбросить приближение
qt-accel-toggle-sidebar = Боковая панель
qt-accel-zoom-editor-in = &Приблизить редактор
qt-accel-zoom-editor-out = &Отдалить редактор
qt-accel-create-backup = Создать &резервную копию
qt-accel-load-backup = В&озврат к резервной копии
qt-accel-upgrade-downgrade = Повышение/понижение
