profiles-anki-could-not-read-your-profile = Anki no ha pogut consultar les dades del vostre perfil. S'han oblidat les mides de les finestres i la informació d'accés de la sincronizació.
profiles-anki-could-not-rename-your-profile = Anki no ha pogut reanomenar el vostre perfil, atès que no ha pogut canviar el nom de la carpeta del perfil en el disc. Assegureu-vos que teniu permís d'escriptura a Documents/Anki i que no hi ha cap altre programa accedint-hi i torneu-ho a intantar.
profiles-folder-already-exists = Aquesta carpeta ja existeix.
profiles-open = Obre
profiles-open-backup = Obre una còpia de seguretat…
profiles-please-remove-the-folder-and = Elimineu la carpeta { $val } i torneu-ho a intentar.
profiles-profile-corrupt = Perfil malmès
profiles-profiles = Perfils
profiles-quit = Surt
profiles-user-1 = Usuari 1
profiles-confirm-lang-choice = Segur que voleu mostrar la interfície d’Anki en { $lang }?
profiles-could-not-create-data-folder = Anki no ha pogut crear la vostra carpeta de dades. Consulteu la secció «Ubicacions de fitxers» del manual i assegureu-vos que la ubicació no sigui de només lectura.
profiles-prefs-corrupt-title = Preferències malmeses
profiles-prefs-file-is-corrupt = El fitxer prefs21.db d'Anki estava malmès i s'ha tornat a creat. Si utilitzeu diversos perfils, torneu-los a afegir amb els mateixos noms per a recuperar les vostres targetes.
profiles-profile-does-not-exist = El perfil sol·licitat no existeix.
profiles-creating-backup = S'està creant una còpia de seguretat…
profiles-backup-created = S'ha creat una còpia de seguretat
profiles-backup-creation-failed = La creació de la còpia de seguretat ha fallat: { $reason }
profiles-backup-unchanged = No hi ha hagut canvis des de l'última còpia de seguretat.
