actions-add = Adaugă
actions-all-selected = Toate Selectate
actions-any-selected = Oricare Selectată
actions-cancel = Anulare
actions-choose = Alege
actions-close = Închide
actions-copy = Copiază
actions-create-copy = Crează o Copie
actions-custom-study = Studiu personalizat
actions-decks = Pachete
actions-delete = Șterge
actions-export = Exportă
actions-filter = Filtrează
actions-help = Ajutor
actions-import = Importă
actions-manage = Administrare...
actions-name = Nume:
actions-new = Nou
actions-new-name = Nume nou:
actions-options = Opțiuni
actions-options-for = Opțiuni pentru { $val }
actions-preview = Previzualizare
actions-rebuild = Reconstruiește
actions-rename = Redenumește
actions-rename-deck = Redenumește pachet
actions-rename-tag = Redenumește Marcaj
actions-rename-with-parents = Redenumește cu Părinți
actions-remove-tag = Elimină Marcaj
actions-replay-audio = Repetă Audio
actions-reposition = Repoziționează
actions-save = Salvează
actions-search = Caută
actions-select = Selectează
actions-shortcut-key = Tastă(e) de comandă rapidă
actions-suspend-card = Suspendă cadrul
actions-set-due-date = Stabilește dată scadentă
actions-answer-card = Fișă de răspuns
actions-unbury-unsuspend = Dezgroapă/Anulează Suspendarea
actions-add-deck = Adaugă Pachet
actions-add-note = Adaugă Notiță
actions-update-tag = Actualizează Marcaj
actions-update-note = Actualizează Notiță
actions-update-card = Actualizează cardul
actions-update-deck = Actualizează Pachet
actions-forget-card = Uită cardul
actions-build-filtered-deck = Construiește Pachet
actions-add-notetype = Adaugă tip-card
actions-remove-notetype = Elimină tip-card
actions-update-notetype = Actualizează tip-card
actions-update-config = Actualizează Configurarea
actions-card-info = Informații card
actions-previous-card-info = Informațiile cardului anterior
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = Această acțiune nu este acceptată în prezent pe sistemul tău.

## Flags

actions-flag-number = Fanion
actions-flag-red = Roșu
actions-flag-orange = Portocaliu
actions-flag-green = Verde
actions-flag-blue = Albastru
actions-flag-pink = Roz
actions-flag-turquoise = Turcoaz
actions-flag-purple = Violet
actions-set-flag = Setează Fanion
actions-nothing-to-undo = Nimic de anulat
actions-nothing-to-redo = Nimic de refăcut
actions-auto-advance = Avansare automată
actions-processing = Se procesează...
