preferences-automatically-sync-on-profile-openclose = Sincronizare automată la deschiderea / închiderea profilului
preferences-backups = Salvări de siguranță
preferences-backups2 = copii de rezervă
preferences-backupsanki-will-create-a-backup-of = <b> Backup </ b> <br> Anki va crea o copie de rezervă a colecției de fiecare dată când este închisă sau sincronizată.
preferences-basic = De bază
preferences-change-deck-depending-on-note-type = Schimbă pachetul în funcție de tipul notei
preferences-changes-will-take-effect-when-you = Modificările vor intra în vigoare când repornești Anki.
preferences-hours-past-midnight = ore trecute de miezul nopții
preferences-interface-language = Limba interfeței:
preferences-interrupt-current-audio-when-answering = Întrerupe sunetul curent când se răspunde
preferences-keep = Păstrează
preferences-learn-ahead-limit = Limita de sus pentru cele învățate
preferences-mins = minute
preferences-network = Rețea
preferences-next-day-starts-at = Ziua următoare începe la
preferences-night-mode = Modul noapte
preferences-note-media-is-not-backed-up = Notă: Nu se face backup pentru conținut media. Vă rugăm să creați o copie de rezervă periodică a folderului dvs. Anki pentru a fi în siguranță.
preferences-on-next-sync-force-changes-in = La următoarea sincronizare, forțează schimbări într-o direcție
preferences-paste-clipboard-images-as-png = Lipiți imagini din clipboard ca PNG
preferences-paste-without-shift-key-strips-formatting = Lipiți fără formatarea benzilor de taste Shift
preferences-periodically-sync-media = Sincronizează periodic media
preferences-please-restart-anki-to-complete-language = Vă rugăm să reporniți Anki pentru a finaliza schimbarea limbii.
preferences-preferences = Preferințe
preferences-scheduling = Re-planifică
preferences-show-learning-cards-with-larger-steps = Afișați carduri de învățare cu pași mai mari înainte de recapitulări
preferences-show-next-review-time-above-answer = Afișați ora următoarei revizuiri deasupra butoanelor de răspuns
preferences-show-play-buttons-on-cards-with = Afișați butoanele de redare pe cardurile cu sunet
preferences-show-remaining-card-count-during-review = Afișați numărul de carduri rămase în timpul examinării
preferences-some-settings-will-take-effect-after = Unele configurări vor intra în vigoare după ce reporniți Anki
preferences-synchronisation = <b>Sincronizare</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Sincronizare</b><br> În acest moment sincronizarea nu este activată; apasă pe butonul de sincronizare din fereastra principală.
preferences-synchronize-audio-and-images-too = Sincronizarea fişierelor audio şi a imaginilor
preferences-timebox-time-limit = Limită de timp pentru timebox
preferences-user-interface-size = Dimensiunea interfeței cu utilizatorul
preferences-when-adding-default-to-current-deck = Când adăugați, implicit la pachetul curent
preferences-you-can-restore-backups-via-fileswitch = Puteți restabili copiile de siguranță prin Fișier>Comutați profil.
preferences-legacy-timezone-handling = Gestionarea fusului orar vechi (cu bug-uri, dar necesar pentru AnkiDroid <= 2.14)
preferences-default-search-text = Text de căutare implicit
preferences-theme-label = Temă: { $theme }
preferences-theme-follow-system = Pastrează tema sistemului
preferences-theme-light = Luminos
preferences-theme-dark = Întunecat
preferences-ignore-accents-in-search = Ignorați accentele în căutare (mai lent)
preferences-backup-explanation =
    Anki face periodic copii de rezervă ale colecției tale când aceasta este închisă. După ce backup-urile au mai mult de 2 zile,
    Anki va începe să elimine unele dintre ele pentru a elibera spațiu pe disc.
preferences-daily-backups = Backup-uri zilnice de păstrat:
preferences-weekly-backups = Backup-uri săptămânale de păstrat:
preferences-monthly-backups = Backup-uri lunare de păstrat:
preferences-theme = Temă
preferences-editing = Editare
