editing-add-media = Pridať médiá
editing-an-error-occurred-while-opening = Pri otváraní { $val } došlo k chybe
editing-attach-picturesaudiovideo-f3 = Pripojiť obrázky/zvuk/video (F3)
editing-bold-text-ctrlandb = Tučný text (Ctrl+B)
editing-cards = Karty
editing-change-colour-f8 = Zmeniť farbu (F8)
editing-cloze-deletion-ctrlandshiftandc = Doplňovačka (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = Nebolo možné nahrať zvuk. Máte nainštalovaný „lame“?
editing-customize-card-templates-ctrlandl = Prispôsobiť šablóny kariet (Ctrl+L)
editing-customize-fields = Prispôsobiť pole
editing-cut = Vystrihnúť
editing-edit-current = Upraviť aktuálnu
editing-edit-html = Upraviť HTML
editing-fields = Polia
editing-html-editor = HTML editor
editing-italic-text-ctrlandi = Kurzíva (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = Skočiť na štítky pomocou Ctrl+Shift+T
editing-latex = LaTeX
editing-latex-equation = Rovnica v LaTeXu
editing-latex-math-env = Mat. prostredie LaTeX
editing-mathjax-block = Block MathJax
editing-mathjax-chemistry = MathJax chémia
editing-mathjax-inline = MathJax inline
editing-media = Médiá
editing-paste = Prilepiť
editing-record-audio-f5 = Nahrať zvuk (F5)
editing-remove-formatting-ctrlandr = Odstrániť formátovanie (Ctrl+R)
editing-set-foreground-colour-f7 = Nastaviť fabru popredia (F7)
editing-show-duplicates = Zobraziť duplikáty
editing-subscript-ctrland = Dolný index (Ctrl+=)
editing-superscript-ctrlandand = Horný index (Ctrl++)
editing-tags = Štítky
editing-to-make-a-cloze-deletion-on = Ak chcete vytvoriť doplňovačku z existujúcej poznámky, musíte najprv zmeniť jej typ na doplňovačku pomocou Upraviť->Zmeniť typ poznámky.
editing-underline-text-ctrlandu = Podčiarknutý text (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = Upozornenie: doplňovačky nebudú fungovať, pokiaľ nezmeníte typ hore na Doplňovačka.
