fields-add-field = Pridať pole
fields-delete-field-from = Odstrániť pole z { $val }?
fields-editing-font = Úprava písma
fields-field = Pole:
fields-field-name = Názov poľa:
fields-fields-for = Polia pre { $val }
fields-font = Písmo:
fields-new-position-1 = Nová pozícia (1...{ $val }):
fields-notes-require-at-least-one-field = Poznámky vyžadujú aspoň jedno pole.
fields-remember-last-input-when-adding = Pri pridávaní si pamätať posledný vstup
fields-reverse-text-direction-rtl = Text sprava doľava (RTL - right to left)
fields-size = Veľkosť:
fields-sort-by-this-field-in-the = Zoradiť podľa tohto poľa v prehliadači
fields-that-field-name-is-already-used = Pole s takým názvom už existuje.
