notetypes-front-field = Predná strana
notetypes-back-field = Späť
notetypes-add-reverse-field = Pridať zadnú stranu karty
notetypes-basic-name = Základný
notetypes-basic-reversed-name = Základný (plus obrátená karta)
notetypes-basic-optional-reversed-name = Základný (plus voliteľná obrátená karta)
notetypes-cloze-name = Doplňovačka
notetypes-card-2-name = Karta 2
notetypes-card-1-name = Karta 1
notetypes-add = Pridať: { $val }
notetypes-add-note-type = Pridať typ poznámky
notetypes-cards = Karty...
notetypes-clone = Naklonovať: { $val }
notetypes-copy = { $val } kópia
notetypes-create-scalable-images-with-dvisvgm = Vytvárajte škálovateľné obrázky s dvisvgm
notetypes-delete-this-note-type-and-all = Odstrániť tento typ poznámky a všetky jeho karty?
notetypes-delete-this-unused-note-type = Odstrániť tento nevyužitý typ poznámky?
notetypes-fields = Polia...
notetypes-footer = Päta
notetypes-header = Hlavička
notetypes-note-types = Typy poznámok
notetypes-options = Nastavenia...
notetypes-please-add-another-note-type-first = Najprv, prosím, pridajte ďalší typ poznámky.
notetypes-type = Typ
