adding-add-shortcut-ctrlandenter = 추가 (단축키: ctrl+enter)
adding-added = 추가됨
adding-discard-current-input = 현재 입력을 버릴까요?
adding-keep-editing = 편집을 계속하기
adding-edit = "{ $val }" 수정하기
adding-history = 이력
adding-note-deleted = (노트 삭제됨)
adding-shortcut = 단축키: { $val }
adding-the-first-field-is-empty = 첫번째 필드가 비어있습니다.
adding-you-have-a-cloze-deletion-note = 빈칸뚫기 유형의 노트를 선택했지만 빈칸을 뚫지 않았습니다. 계속 진행할까요?
adding-cloze-outside-cloze-notetype = 빈칸뚫기는 빈칸뚫기 유형의 노트에서만 가능합니다.
adding-cloze-outside-cloze-field = 빈칸뚫기는 'cloze:' 필터를 사용하는 필드 내에서만 가능합니다. 일반적으로는 첫번째 필드입니다.
