fields-add-field = 필드 추가
fields-delete-field-from = { $val }에서 필드를 삭제할까요?
fields-editing-font = 글꼴
fields-field = 필드:
fields-field-name = 필드 이름:
fields-description = 설명
fields-description-placeholder = 필드가 비어있을 때 표시할 임시 텍스트
fields-fields-for = { $val }의 필드
fields-font = 글꼴:
fields-new-position-1 = 새 위치 (1...{ $val }):
fields-notes-require-at-least-one-field = 노트는 적어도 하나 이상의 필드가 필요합니다.
fields-reverse-text-direction-rtl = 글씨 좌우 뒤집기 (RTL)
fields-collapse-by-default = 기본적으로 접어놓기
fields-html-by-default = 기본적으로 HTML 편집기 사용하기
fields-size = 크기:
fields-sort-by-this-field-in-the = 탐색기에서 이 필드를 기준으로 정렬
fields-that-field-name-is-already-used = 이미 사용 중인 필드 이름입니다.
fields-name-first-letter-not-valid = 필드 이름은 #^/로 시작할 수 없습니다.
fields-name-invalid-letter = 필드 이름에 ,"{ "{" }{ "}" }를 입력할 수 없습니다.
