preferences-automatically-sync-on-profile-openclose = 프로필을 열고 닫을 때 자동 동기화
preferences-backups = 백업
preferences-change-deck-depending-on-note-type = 노트 유형에 따라 덱 변경
preferences-changes-will-take-effect-when-you = 변경 사항은 Anki를 재시작한 뒤 적용됩니다.
preferences-hours-past-midnight = 시간 뒤
preferences-language = 언어
preferences-interrupt-current-audio-when-answering = 응답 할 때 현재 오디오 재생 중단
preferences-learn-ahead-limit = 앞당겨 공부하기 제한
preferences-mins = 분
preferences-network = 동기화
preferences-next-day-starts-at = 하루가 시작하는 시각은 자정으로부터
preferences-media-is-not-backed-up = 미디어가 백업되지 않았습니다. 안전을 위해 Anki 폴더를 주기적으로 백업하세요.
preferences-on-next-sync-force-changes-in = 다음 동기화 때, 한 방향으로만 변경 사항 적용하기
preferences-paste-clipboard-images-as-png = 클립보드에 있는 이미지를 PNG 형식으로 붙여넣기
preferences-paste-without-shift-key-strips-formatting = Shift 키를 뗀 상태라면 서식 없이 붙여넣기
preferences-generate-latex-images-automatically = LaTex 이미지 생성 (보안 위험)
preferences-latex-generation-disabled = LaTeX 이미지 생성 기능이 설정에서 비활성화되어 있습니다.
preferences-periodically-sync-media = 주기적으로 미디어 동기화하기
preferences-please-restart-anki-to-complete-language = 바뀐 언어 설정을 적용하려면 Anki를 재시작해 주세요.
preferences-preferences = 환경 설정
preferences-scheduling = 일정 재조정
preferences-show-learning-cards-with-larger-steps = 복습하기 전 더 높은 단계의 학습 카드 보여주기
preferences-show-next-review-time-above-answer = 답 버튼 위에 다음 복습 시점 표시
preferences-spacebar-rates-card = 스페이스바 (혹은 엔터)로 카드 답하기
preferences-show-play-buttons-on-cards-with = 카드에 오디오와 함께 재생 버튼 보이기
preferences-show-remaining-card-count = 남은 카드 수 보이기
preferences-some-settings-will-take-effect-after = 일부 사항은 Anki를 다시 시작한 뒤 적용됩니다.
preferences-tab-synchronisation = 동기화
preferences-synchronize-audio-and-images-too = 오디오와 이미지 동기화
preferences-login-successful-sync-now = 로그인 성공. 설정을 저장하고 동기화하시겠습니까?
preferences-timebox-time-limit = 시간 제한
preferences-user-interface-size = UI 크기
preferences-when-adding-default-to-current-deck = 기본적으로 카드를 현재 덱에 추가하기
preferences-you-can-restore-backups-via-fileswitch = 파일>프로필 전환을 통해 백업을 복구할 수 있습니다.
preferences-legacy-timezone-handling = 레거시 시간대 처리 (버그가 있지만 AnkiDroid의 2.14 버전 이하에서 필요)
preferences-default-search-text = 기본 검색어
preferences-default-search-text-example = 예시로 'deck:current '
preferences-theme = 테마
preferences-theme-follow-system = 시스템 설정대로
preferences-theme-light = 밝게
preferences-theme-dark = 어둡게
preferences-v3-scheduler = V3 스케줄러
preferences-check-for-updates = 프로그램 업데이트 확인
preferences-ignore-accents-in-search = 검색어에서 구분 기호 무시하기 (느림)
preferences-backup-explanation =
    Anki는 정기적으로 컬렉션을 백업합니다. 백업이 2일 이상 되었다면
    Anki는 디스크 공간을 확보하기 위해 백업 중 일부를 제거하기 시작합니다.
preferences-daily-backups = 저장할 일일 백업:
preferences-weekly-backups = 저장할 주간 백업:
preferences-monthly-backups = 저장할 월간 백업:
preferences-minutes-between-backups = 자동 백업 간의 시간(분):
preferences-reduce-motion = 시각적 효과 줄이기
preferences-reduce-motion-tooltip = UI에서 다양한 애니메이션이나 전환 효과 등을 비활성화합니다.
preferences-custom-sync-url = 셀프 호스트 동기화 서버
preferences-custom-sync-url-disclaimer = 고급 사용자용 - 메뉴얼을 확인해주세요
preferences-hide-top-bar-during-review = 리뷰 중 상단 바 숨기기
preferences-hide-bottom-bar-during-review = 리뷰 중 하단 바 숨기기
preferences-always = 항상
preferences-full-screen-only = 전체화면에서만
preferences-appearance = 모습
preferences-general = 일반
preferences-style = 스타일
preferences-review = 복습
preferences-answer-keys = 답변 단축키
preferences-minimalist-mode = 미니멀리스트 모드
preferences-editing = 편집
preferences-browsing = 탐색
preferences-default-deck = 기본 덱
preferences-account = AnkiWeb 계정
preferences-note = 노트
preferences-scheduler = 스케줄러
preferences-user-interface = 유저 인터페이스
preferences-import-export = 불러오기/내보내기
preferences-network-timeout = 네트워크 연결시간 초과
preferences-reset-window-sizes = 창 크기 초기화
preferences-reset-window-sizes-complete = 창 크기와 위치가 초기화 되었습니다.
preferences-shortcut-placeholder = 새로운 단축키를 입력하거나, 비활성화하려면 빈 칸으로 설정하세요.
preferences-third-party-services = 외부 서비스
preferences-ankihub-not-logged-in = 현재 AnkiHub에 로그인하지 않았습니다.
preferences-ankiweb-intro = AnkiWeb은 플래시카드 데이터를 여러 기기 간에 동기화할 수 있게 해주는 무료 서비스이며, 기기가 고장 나거나 분실됐을 때 데이터를 복구할 수 있는 방법도 제공합니다.
preferences-ankihub-intro = AnkiHub은 공동으로 덱을 편집할 수 있는 기능과 추가 학습 도구를 제공합니다. 일부 기능은 유료 구독이 필요합니다.
preferences-third-party-description = 서드파티 서비스는 Anki와 제휴되어 있지 않으며, Anki의 보증을 받지 않습니다. 이러한 서비스를 이용하려면 비용이 발생할 수 있습니다.

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = Basic
preferences-media = 미디어
preferences-not-logged-in = 현재 AnkiWeb에 로그인하지 않았습니다.
