adding-add-shortcut-ctrlandenter = 添加（快捷键：Ctrl+Enter）
adding-added = 已添加
adding-discard-current-input = 是否放弃当前输入？
adding-keep-editing = 继续编辑
adding-edit = 编辑「{ $val }」
adding-history = 最近添加
adding-note-deleted = （笔记已删除）
adding-shortcut = 快捷键：{ $val }
adding-the-first-field-is-empty = 首字段为空。
adding-you-have-a-cloze-deletion-note = 您选择的是填空题笔记模板，但尚未设置填空。是否继续？
adding-cloze-outside-cloze-notetype = 仅填空题笔记模板可以设置填空。
adding-cloze-outside-cloze-field = 仅含有「cloze:」筛选器的字段可以设置填空。一般是首字段。
