decks-add-new-deck-ctrlandn = 添加新的牌组
decks-build = 创建筛选牌组
decks-cards-selected-by = 张卡片，选择方式
decks-create-deck = 创建牌组
decks_create_even_if_empty = 创建/更新此牌组，即使其为空。
decks-custom-steps-in-minutes = 自定义步幅（以分钟计）
decks-deck = 牌组
decks-decreasing-intervals = 间隔由大到小
decks-delete-deck = 删除牌组
decks-enable-second-filter = 启用第 2 筛选器
decks-filter = 筛选：
decks-filter-2 = 第 2 筛选器
decks-get-shared = 获取牌组
decks-import-file = 导入文件
decks-increasing-intervals = 间隔由小到大
decks-latest-added-first = 最后添加的优先
decks-limit-to = 上限
decks-minutes = 分钟
decks-most-lapses = 遗忘次数由大到小
decks-new-deck-name = 新牌组名称：
decks-no-deck = [无牌组]
decks-oldest-seen-first = 最早查看的优先
decks-order-added = 按添加顺序
decks-order-due = 按到期顺序
decks-please-select-something = 请选择一个牌组。
decks-random = 乱序
decks-relative-overdueness = 按相对超期程度
decks-repeat-failed-cards-after = 之后重复「重来」的间隔
# e.g. "Delay for Again", "Delay for Hard", "Delay for Good"
decks-delay-for-button = 「{ $button }」的间隔
decks-reschedule-cards-based-on-my-answers = 基于此牌组的回答情况，对卡片重新排程。
decks-study = 学习
decks-study-deck = 学习牌组
decks-filtered-deck-search-empty = 没有符合搜索条件的卡片。不同筛选牌组中的卡片和已暂停的卡片可能已被排除。
decks-unmovable-cards = 显示所有已被排除的卡片
decks-learn-header = 学习中
# The count of cards waiting to be reviewed
decks-review-header = 待复习
decks-zero-minutes-hint = （0 = 将卡片放回原牌组）
