editing-actual-size = 打开/关闭以实际尺寸展示
editing-add-media = 添加媒体文件
editing-align-left = 左对齐
editing-align-right = 右对齐
editing-an-error-occurred-while-opening = 打开 { $val } 时发生错误
editing-attach-picturesaudiovideo = 附加图片/音频/视频
editing-bold-text = 粗体
editing-cards = 卡片
editing-center = 居中对齐
editing-change-color = 更改颜色
editing-cloze-deletion = 填空（新增卡片）
editing-cloze-deletion-repeat = 设置填空（相同卡片）
editing-copy-image = 复制图片
editing-couldnt-record-audio-have-you-installed = 无法录制音频。请检查是否已安装「lame」？
editing-customize-card-templates = 自定义卡片内容模板
editing-customize-fields = 自定义字段
editing-cut = 剪切
editing-double-click-image = 双击图片
editing-double-click-to-expand = 双击展开
editing-double-click-to-collapse = 双击折叠
editing-edit-current = 编辑当前
editing-edit-html = 编辑 HTML
editing-fields = 字段
editing-float-left = 向左浮动
editing-float-right = 向右浮动
editing-float-none = 不浮动
editing-indent = 增加缩进
editing-italic-text = 斜体
editing-jump-to-tags-with-ctrlandshiftandt = 使用 Ctrl+Shift+T 跳到标签
editing-justify = 两端对齐
editing-latex = LaTeX
editing-latex-equation = LaTeX 公式
editing-latex-math-env = LaTeX 数学环境
editing-mathjax-block = MathJax 行间公式
editing-mathjax-chemistry = MathJax 化学
editing-mathjax-inline = MathJax 行内公式
editing-mathjax-placeholder = 按 { $accept } 以保存，按 { $newline } 以换行。
editing-media = 媒体
editing-open-image = 打开图片
editing-show-in-folder = 在文件夹中显示
editing-ordered-list = 有序列表
editing-outdent = 减少缩进
editing-paste = 粘贴
editing-record-audio = 录制音频
editing-remove-formatting = 清除格式
editing-restore-original-size = 恢复原始大小
editing-select-remove-formatting = 选择要清除的格式
editing-show-duplicates = 查看重复的卡片
editing-subscript = 下标
editing-superscript = 上标
editing-tags = 标签
editing-tags-add = 添加标签
editing-tags-copy = 复制标签
editing-tags-remove = 删除标签
editing-tags-select-all = 全选标签
editing-text-color = 文字颜色
editing-text-highlight-color = 高亮文本
editing-to-make-a-cloze-deletion-on = 若要在现有笔记上设置填空，请通过「笔记」>「更改笔记模板」将笔记模板修改为填空题笔记模板。
editing-toggle-html-editor = 打开/关闭 HTML 编辑器
editing-toggle-visual-editor = 打开/关闭可视化编辑器
editing-toggle-sticky = 固定/取消固定
editing-expand = 展开
editing-collapse = 折叠
editing-expand-field = 拓展字段
editing-collapse-field = 折叠字段
editing-underline-text = 下划线
editing-unordered-list = 无序列表
editing-warning-cloze-deletions-will-not-work = 警告，在您将笔记模板修改为填空题笔记模板前，您设置的填空不会生效。
editing-mathjax-preview = MathJax 预览
editing-shrink-images = 缩小图像
editing-close-html-tags = 自闭合 HTML 标签
editing-from-clipboard = 从剪贴板
editing-alignment = 对齐
editing-equations = 公式
editing-no-image-found-on-clipboard = 未在剪贴板上找到图像。
editing-image-occlusion-mode = 图片遮盖模式
editing-image-occlusion-zoom-out = 缩小
editing-image-occlusion-zoom-in = 放大
editing-image-occlusion-zoom-reset = 重置缩放
editing-image-occlusion-toggle-translucent = 切换半透明显示
editing-image-occlusion-delete = 删除
editing-image-occlusion-duplicate = 复制
editing-image-occlusion-group = 组合
editing-image-occlusion-ungroup = 取消组合
editing-image-occlusion-select-all = 全选
editing-image-occlusion-alignment = 对齐
editing-image-occlusion-align-left = 靠左对齐
editing-image-occlusion-align-h-center = 水平居中
editing-image-occlusion-align-right = 靠右对齐
editing-image-occlusion-align-top = 顶端对齐
editing-image-occlusion-align-v-center = 垂直居中
editing-image-occlusion-align-bottom = 底端对齐
editing-image-occlusion-select-tool = 选择
editing-image-occlusion-zoom-tool = 缩放
editing-image-occlusion-rectangle-tool = 矩形
editing-image-occlusion-ellipse-tool = 椭圆形
editing-image-occlusion-polygon-tool = 多边形
editing-image-occlusion-text-tool = 文本
editing-image-occlusion-fill-tool = 填充颜色
editing-image-occlusion-toggle-mask-editor = 切换图片遮盖编辑器
editing-image-occlusion-reset = 重置图片遮盖
editing-image-occlusion-confirm-reset = 您确定要重置图片遮盖吗？

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML 编辑器
