preferences-automatically-sync-on-profile-openclose = 账户启动和关闭时自动同步
preferences-backups = 备份
preferences-change-deck-depending-on-note-type = 添加卡片时，根据笔记模板自动选择牌组
preferences-changes-will-take-effect-when-you = 修改将在重启 Anki 后生效。
preferences-hours-past-midnight = 时
preferences-language = 语言
preferences-interrupt-current-audio-when-answering = 回答卡片时停止播放当前音频
preferences-learn-ahead-limit = 提前学习的上限
preferences-mins = 分钟
preferences-network = 同步
preferences-next-day-starts-at = 次日起点
preferences-media-is-not-backed-up = 媒体文件不会被备份，为确保安全请定期备份 Anki 文件夹。
preferences-on-next-sync-force-changes-in = 下次同步时，强制单向覆盖
preferences-paste-clipboard-images-as-png = 以 PNG 格式粘贴图片
preferences-paste-without-shift-key-strips-formatting = 若粘贴时未按住 Shift 键，则清除文本格式
preferences-generate-latex-images-automatically = 生成 LaTeX 图片（有安全风险）
preferences-latex-generation-disabled = LaTeX 图片生成已在设置中禁用。
preferences-periodically-sync-media = 定期同步媒体文件
preferences-please-restart-anki-to-complete-language = 请重启 Anki 以完成语言切换
preferences-preferences = 设置
preferences-scheduling = 计划
preferences-show-learning-cards-with-larger-steps = 在复习前展示步伐更长且处于学习中的卡牌
preferences-show-next-review-time-above-answer = 在回答按钮上显示下次复习时间
preferences-spacebar-rates-card = 将空格键（或回车键）用于评估卡片
preferences-show-play-buttons-on-cards-with = 卡片上显示音频播放按钮
preferences-show-remaining-card-count = 显示剩余卡片数量
preferences-some-settings-will-take-effect-after = 部分设置将在重启 Anki 后生效
preferences-tab-synchronisation = 同步
preferences-synchronize-audio-and-images-too = 同时同步音频和图片
preferences-login-successful-sync-now = 登录成功。是否要保存设置并立即同步？
preferences-timebox-time-limit = 提醒指定时间内的学习卡片数
preferences-user-interface-size = 界面缩放
preferences-when-adding-default-to-current-deck = 添加卡片时，默认加入当前牌组
preferences-you-can-restore-backups-via-fileswitch = 可通过「文件」>「切换账户」恢复备份。
preferences-legacy-timezone-handling = 旧版时区处理方式（有问题，但 AnkiDroid 2.14 及以下版本必须使用）
preferences-default-search-text = 默认搜索文本
preferences-default-search-text-example = 例如：'deck:current '
preferences-theme = 主题
preferences-theme-follow-system = 跟随系统
preferences-theme-light = 浅色
preferences-theme-dark = 深色
preferences-v3-scheduler = 启用 V3 排程算法
preferences-check-for-updates = 检查程序更新
preferences-ignore-accents-in-search = 搜索时忽略重音（速度较慢）
preferences-backup-explanation = Anki 将自动备份您的集合。但为节省磁盘空间，将自动删除超过 2 天的备份。
preferences-daily-backups = 要保留的每日备份数量：
preferences-weekly-backups = 要保留的每周备份数量：
preferences-monthly-backups = 要保留的每月备份数量：
preferences-minutes-between-backups = 自动备份的间隔时间（分钟）：
preferences-reduce-motion = 减少动效
preferences-reduce-motion-tooltip = 禁用用户界面的所有动画和过渡。
preferences-custom-sync-url = 自托管同步服务器
preferences-custom-sync-url-disclaimer = 供进阶用户使用（详情请参阅使用手册）
preferences-hide-top-bar-during-review = 复习时隐藏顶栏
preferences-hide-bottom-bar-during-review = 复习时隐藏底栏
preferences-always = 总是
preferences-full-screen-only = 仅全屏
preferences-appearance = 显示
preferences-general = 通用
preferences-style = 风格
preferences-review = 复习
preferences-answer-keys = 回答按键
preferences-distractions = 专心
preferences-minimalist-mode = 极简模式
preferences-minimalist-mode-tooltip = 使界面更紧凑/简约
preferences-editing = 编辑
preferences-browsing = 浏览
preferences-default-deck = 默认牌组
preferences-account = AnkiWeb 账号
preferences-note = 注意
preferences-scheduler = 排程
preferences-user-interface = 用户界面
preferences-import-export = 导入/导出
preferences-network-timeout = 网络超时
preferences-reset-window-sizes = 重置窗口大小
preferences-reset-window-sizes-complete = 已重置窗口位置和大小。
preferences-shortcut-placeholder = 输入一个未使用的快捷键，或者留空已停用
preferences-third-party-services = 第三方服务
preferences-ankihub-not-logged-in = 当前未登录 AnkiHub。
preferences-ankiweb-intro = AnkiWeb 是一项免费服务，可让您在设备之间保持抽认卡数据同步，并提供在设备损坏或丢失时恢复数据的方法。
preferences-ankihub-intro = AnkiHub 提供协作牌组编辑和其他学习工具。需要付费订阅才能访问某些功能。
preferences-third-party-description = 第三方服务不隶属于 Anki，也不受 Anki 认可。使用这些服务可能需要付费。

## URL scheme related

preferences-url-schemes = URL 协议
preferences-url-scheme-prompt = 允许的 URL 模式（用空格分隔）：
preferences-url-scheme-warning =
    已拦截尝试打开的链接 `{ $link }`，该操作可能存在安全风险。
    若您信任牌组作者并希望继续操作，可将 `{ $scheme }` 添加到允许的 URL 模式中。
preferences-url-scheme-allow-once = 仅允许一次
preferences-url-scheme-always-allow = 始终允许

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = 基本
preferences-reviewer = 复习者
preferences-media = 媒体
preferences-not-logged-in = 当前未登录 AnkiWeb。
