profiles-anki-could-not-read-your-profile = Anki 无法读取您的资料数据。窗口大小和您的同步登录细节已丢失。
profiles-anki-could-not-rename-your-profile = 因为 Anki 不能重命名你的配置文件夹，所以不能重命名你的配置文件。请确定你有文档/Anki 文件夹的写权限，同时没有其它程序正在访问你的配置文件目录后，再重试。
profiles-folder-already-exists = 文件夹已存在。
profiles-open = 打开
profiles-open-backup = 打开备份…
profiles-please-remove-the-folder-and = 请删除目录 { $val } 后再重试。
profiles-profile-corrupt = 账户损坏。
profiles-profiles = 账户
profiles-quit = 退出
profiles-user-1 = 账户 1
profiles-confirm-lang-choice = 确定要以 { $lang } 来显示 Anki 的界面吗？
profiles-could-not-create-data-folder = 无法建立保存 Anki 数据的文件夹。请参考帮助文档中的「文件位置」（File Locations）一节，并确保该位置 Anki 有写入权限。
profiles-prefs-corrupt-title = 设置损坏
profiles-prefs-file-is-corrupt = Anki 的 prefs21.db 文件已损坏并被重新建立。若您使用过多个配置文件，新增相同名称的配置文件即可恢复您的卡片。
profiles-profile-does-not-exist = 请求的账户不存在
profiles-creating-backup = 正在创建备份…
profiles-backup-created = 备份已创建。
profiles-backup-creation-failed = 备份创建失败：{ $reason }
profiles-backup-unchanged = 上次备份后无变更。
