qt-accel-about = &Sobre o Anki
qt-accel-about-mac = Sobre o Anki...
qt-accel-cards = &Tarxetas
qt-accel-check-database = &Comprobar base de datos
qt-accel-check-media = Comprobar &multimedia
qt-accel-edit = &Editar
qt-accel-exit = &Saír
qt-accel-export = Exportar...
qt-accel-export-notes = &Exportar notas...
qt-accel-file = &Ficheiro
qt-accel-filter = &Filtrar
qt-accel-find = &Buscar
qt-accel-find-and-replace = Buscar e &substituír
qt-accel-find-duplicates = &Buscar duplicados...
qt-accel-go = &Ir
qt-accel-guide = &Manual
qt-accel-help = &Axuda
qt-accel-import = Importar...
qt-accel-info = &Información...
qt-accel-invert-selection = &Inverter a selección
qt-accel-next-card = &Seguinte tarxeta
qt-accel-note = &Nota
qt-accel-notes = Notas
qt-accel-preferences = &Preferencias
qt-accel-previous-card = &Tarxeta anterior
qt-accel-select-all = Seleccionar &todo
qt-accel-select-notes = Seleccionar &notas
qt-accel-support-anki = &Apoiar o Anki
qt-accel-switch-profile = Cambiar perfil
qt-accel-tools = Fe&rramentas
qt-accel-undo = &Desfacer
qt-accel-redo = %Refacer
qt-accel-set-due-date = Programar &data...
qt-accel-forget = &Reiniciar
qt-accel-view = &Ver
qt-accel-full-screen = Alternar &pantalla completa
qt-accel-layout = &Disposición
qt-accel-layout-auto = &Automático
qt-accel-layout-vertical = &Vertical
qt-accel-layout-horizontal = &Horizontal
qt-accel-zoom-in = &Ampliar zoom
qt-accel-zoom-out = &Reducir zoom
qt-accel-reset-zoom = &Restabelecer zoom
qt-accel-toggle-sidebar = Alternar barra lateral
qt-accel-zoom-editor-in = &Ampliar zoom do editor
qt-accel-zoom-editor-out = &Reducir zoom do editor
qt-accel-create-backup = Crear unha &copia de seguranza
qt-accel-load-backup = &Restaurar unha copia de seguranza
qt-accel-upgrade-downgrade = Actualizar/reverter
