editing-actual-size = Preklopi dejansko velikost
editing-add-media = Dodaj večpredstavnostno datoteko
editing-align-left = Poravnaj levo
editing-align-right = Poravnaj desno
editing-an-error-occurred-while-opening = Pri odpiranju { $val } je prišlo do napake
editing-attach-picturesaudiovideo = Pripni slike/avdio/video
editing-bold-text = Krepko besedilo
editing-cards = Kartice
editing-center = Na sredino
editing-change-color = Spremeni barvo
editing-cloze-deletion = Zapora podatka (nove kartice)
editing-cloze-deletion-repeat = Zapora podatka (ista kartica)
editing-couldnt-record-audio-have-you-installed = Ni bilo možno posneti zvoka. Ali ste namestili 'lame'?
editing-customize-card-templates = Prilagodi predloge kartic
editing-customize-fields = Prilagodi polja
editing-cut = Izreži
editing-double-click-image = dvoklikni sliko
editing-double-click-to-expand = dvoklikni za razširitev
editing-double-click-to-collapse = dvoklikni za skrčenje
editing-edit-current = Uredi trenutno
editing-edit-html = Uredi HTML
editing-fields = Polja
editing-float-left = Postavi levo
editing-float-right = Postavi desno
editing-float-none = Brez postavitve
editing-indent = Povečaj odmik
editing-italic-text = Ležeče besedilo
editing-jump-to-tags-with-ctrlandshiftandt = Skoči na oznako s Ctrl+Shift+T
editing-justify = Obojestransko
editing-latex = LaTeX
editing-latex-equation = LaTeX enačba
editing-latex-math-env = LaTeX matematična spr.
editing-mathjax-block = MathJax blok
editing-mathjax-chemistry = MathJax kemija
editing-mathjax-inline = MathJax v vrstici
editing-mathjax-placeholder = Klikni { $accept } za sprejem, { $newline } za novo vrstico.
editing-media = Večpredstavnostna datoteka
editing-ordered-list = Urejen seznam
editing-outdent = Zmanjšaj odmik
editing-paste = Prilepi
editing-record-audio = Posnemi zvok
editing-remove-formatting = Odstrani oblikovanje
editing-restore-original-size = Ponastavi originalno velikost
editing-select-remove-formatting = Izberite oblikovanje, ki bo odstranjeno
editing-show-duplicates = Prikaži dvojnike
editing-subscript = Podpisano
editing-superscript = Nadpisano
editing-tags = Oznake
editing-tags-add = Dodaj oznako
editing-tags-copy = Kopiraj oznake
editing-tags-remove = Odstrani oznake
editing-tags-select-all = Izberi vse oznake
editing-text-color = Barva besedila
editing-text-highlight-color = Barva oznake besedila
editing-to-make-a-cloze-deletion-on = Za izdelavo zapore besedila na obstoječem zapisku, ga morate najprej spremeniti v tip zapore besedila, preko 'Zapiski>Spremeni tip zapiska'
editing-toggle-html-editor = Preklopi urejevalnik HTML
editing-toggle-visual-editor = Preklopi vizualni urejevalnik
editing-toggle-sticky = Preklopi lepljivost
editing-expand-field = Razširi polje
editing-collapse-field = Skrči polje
editing-underline-text = Podčrtaj besedilo
editing-unordered-list = Neurejen seznam
editing-warning-cloze-deletions-will-not-work = Opozorilo: zapore besedila ne bodo delovale, dokler ne spremenite tipa na vrhu v Zaporo besedila.
editing-mathjax-preview = MathJax predogled
editing-shrink-images = Skrči slike
editing-close-html-tags = Samodejno zaključi HTML oznake

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Urejevalnik HTML
