qt-accel-about = &Névjegy...
qt-accel-cards = &Kártyák
qt-accel-check-database = &Adatbázis ellenőrzése
qt-accel-check-media = &Média ellenőrzése...
qt-accel-edit = &Szerkesztés
qt-accel-exit = &Kilépés
qt-accel-export = &Exportálás...
qt-accel-export-notes = &Jegyzetek exportálása...
qt-accel-file = &Fájl
qt-accel-filter = Szűrő
qt-accel-find = &Keresés
qt-accel-find-and-replace = &Keresés és csere...
qt-accel-find-duplicates = &Azonosak keresése...
qt-accel-go = &Ugrás
qt-accel-guide = &Útmutató...
qt-accel-help = &Súgó
qt-accel-import = &Importálás...
qt-accel-info = &Információ...
qt-accel-invert-selection = Kijelölés meg&fordítása
qt-accel-next-card = K&övetkező kártya
qt-accel-note = &Jegyzet
qt-accel-notes = &Jegyzetek
qt-accel-preferences = &Testreszabás...
qt-accel-previous-card = &Előző kártya
qt-accel-select-all = &Összes kijelölése
qt-accel-select-notes = &Jegyzet kiválasztása
qt-accel-support-anki = Az &Anki támogatása...
qt-accel-switch-profile = &Profilváltás
qt-accel-tools = &Eszközök
qt-accel-undo = &Visszavonás
qt-accel-redo = mégis
qt-accel-set-due-date = Az esedékesség beállítása
qt-accel-forget = alaphelyzetbe állítás
qt-accel-view = megtekintés
qt-accel-full-screen = Toggle &Teljes képernyő
qt-accel-layout = &elrendezés
qt-accel-layout-auto = &Automatikus
qt-accel-layout-vertical = &Függőleges
qt-accel-layout-horizontal = & Vízszintes
qt-accel-zoom-in = Nagyítás
qt-accel-zoom-out = kisebbítés
qt-accel-reset-zoom = Zoomolás visszaállítása
qt-accel-zoom-editor-in = Nagyítás a szerkesztőben
qt-accel-zoom-editor-out = Kicsinyítés a szerkesztőben
qt-accel-create-backup = Biztonsági mentés létrehozása
