[package]
name = "ankirspy"
version = "0.1.0"
edition = "2018"
authors = ["Ankitects Pty Ltd and contributors"]

[dependencies]
anki = { path = "../lib-rust" }

[dependencies.pyo3]
version = "0.8.0"
features = ["extension-module"]

[lib]
name = "ankirspy"
crate-type = ["cdylib"]
