preferences-automatically-sync-on-profile-openclose = 打開/關閉設定檔時自動同步
preferences-backups = 備份
preferences-change-deck-depending-on-note-type = 依筆記類型自動選擇牌組
preferences-changes-will-take-effect-when-you = 更動將在重新啟動 Anki 後生效。
preferences-hours-past-midnight = 時
preferences-language = 語言
preferences-interrupt-current-audio-when-answering = 回答後中斷正在播放的音訊
preferences-learn-ahead-limit = 提前學習上限
preferences-mins = 分鐘
preferences-network = 網路
preferences-next-day-starts-at = 次日始於
preferences-media-is-not-backed-up = 媒體檔不會被備份。為防止遺失資料，請定期手動備份 Anki 資料夾。
preferences-on-next-sync-force-changes-in = 下次同步時，強制單向更動
preferences-paste-clipboard-images-as-png = 將剪貼板影像轉換為 PNG 格式
preferences-paste-without-shift-key-strips-formatting = 自動清除文字格式（按住 Shift 鍵來保留格式）
preferences-generate-latex-images-automatically = 產生 LaTeX 影像（安全風險）
preferences-latex-generation-disabled = LaTeX 影像產生已在偏好設定中被停用。
preferences-periodically-sync-media = 定期同步媒體
preferences-please-restart-anki-to-complete-language = 請重新啟動 Anki 來完成語言更動。
preferences-preferences = 偏好設定
preferences-scheduling = 排程
preferences-show-learning-cards-with-larger-steps = 先顯示學習階段比複習卡間隔更長的學習中卡片
preferences-show-next-review-time-above-answer = 在回答按鈕上顯示下次複習時間
preferences-spacebar-rates-card = 使用空白鍵/Enter 鍵回答卡片
preferences-show-play-buttons-on-cards-with = 在卡片上顯示音訊播放按鈕
preferences-show-remaining-card-count = 顯示剩餘卡片數量
preferences-some-settings-will-take-effect-after = 部分設定在重新啟動 Anki 後才會生效。
preferences-tab-synchronisation = 同步
preferences-synchronize-audio-and-images-too = 同步音訊與影像
preferences-login-successful-sync-now = 登入成功。要儲存偏好設定並立即同步嗎？
preferences-timebox-time-limit = 限時學習時長
preferences-user-interface-size = 使用者介面大小
preferences-when-adding-default-to-current-deck = 新增筆記時，預設加入當前牌組
preferences-you-can-restore-backups-via-fileswitch = 你可以透過「檔案」>「切換設定檔」來回復備份。
preferences-legacy-timezone-handling = 舊版時區處理（易出錯，但停用後與 AnkiDroid 2.14 及以下版本不相容）
preferences-default-search-text = 預設搜尋條件
preferences-default-search-text-example = 例如「deck:current」
preferences-theme = 佈景主題
preferences-theme-follow-system = 跟隨系統設定
preferences-theme-light = 淺色
preferences-theme-dark = 深色
preferences-v3-scheduler = V3 排程器
preferences-check-for-updates = 檢查程式更新
preferences-ignore-accents-in-search = 搜尋時忽略字母的變音符號（速度較慢）
preferences-backup-explanation = Anki 會定期備份你的集合。為節省硬碟空間，超過 2 天以前建立的備份將有一部分會被自動刪除。
preferences-daily-backups = 每日保留備份數量：
preferences-weekly-backups = 每週保留備份數量：
preferences-monthly-backups = 每月保留備份數量：
preferences-minutes-between-backups = 自動備份間隔（分鐘）：
preferences-reduce-motion = 減少動態效果
preferences-reduce-motion-tooltip = 停用多種使用者介面中的動畫和過場效果
preferences-custom-sync-url = 自託管同步伺服器
preferences-custom-sync-url-disclaimer = 供進階使用者使用 — 請參閱使用手冊
preferences-hide-top-bar-during-review = 複習時隱藏頂部列
preferences-hide-bottom-bar-during-review = 複習時隱藏底部列
preferences-always = 總是
preferences-full-screen-only = 僅限全螢幕
preferences-appearance = 外觀
preferences-general = 一般
preferences-style = 樣式
preferences-review = 複習
preferences-answer-keys = 回答按鍵
preferences-distractions = 減少干擾
preferences-minimalist-mode = 極簡模式
preferences-minimalist-mode-tooltip = 使介面更加緊湊/簡約
preferences-editing = 編輯
preferences-browsing = 瀏覽
preferences-default-deck = 預設牌組
preferences-account = AnkiWeb 帳號
preferences-note = 附註
preferences-scheduler = 排程器
preferences-user-interface = 使用者介面
preferences-import-export = 匯入/匯出
preferences-network-timeout = 網路逾時
preferences-reset-window-sizes = 重設視窗大小
preferences-reset-window-sizes-complete = 已重設視窗大小及位置。
preferences-shortcut-placeholder = 輸入一個未使用的快速鍵，或留空以停用。
preferences-third-party-services = 第三方服務
preferences-ankihub-not-logged-in = 未登入 AnkiHub。
preferences-ankiweb-intro = 你可以使用 AnkiWeb 來跨裝置同步卡片，裝置損毀或遺失時也可以輕鬆還原資料。使用 AnkiWeb 無需付費。
preferences-ankihub-intro = AnkiHub 可以合作編輯牌組，並提供其他學習工具。部分功能需付費訂閱。
preferences-third-party-description = Anki 與第三方服務無合作關係，不予擔保。使用這些服務可能需要付費。

## URL scheme related

preferences-url-schemes = URL Schemes
preferences-url-scheme-prompt = 允許的 URL Schemes（以空格分隔）：
preferences-url-scheme-warning =
    已阻止開啟 `{ $link }`，可能存在安全性問題。
    
    如果你信任牌組作者，請在「允許的 URL Schemes」中加入 `{ $scheme }` 以繼續開啟。
preferences-url-scheme-allow-once = 允許一次
preferences-url-scheme-always-allow = 總是允許

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = 基本
preferences-media = 媒體
preferences-not-logged-in = 未登入 AnkiWeb。
