profiles-anki-could-not-read-your-profile = Anki 無法讀取你的設定檔資料。視窗大小和你的同步登入詳細資訊已遺失。
profiles-anki-could-not-rename-your-profile = Anki 無法重新命名硬碟上的設定檔資料夾，因此無法重新命名設定檔。請確認你有寫入 Document/Anki 的權限、沒有其他程式正在讀取此資料夾，然後再試一次。
profiles-folder-already-exists = 資料夾已存在。
profiles-open = 打開
profiles-open-backup = 打開備份...
profiles-please-remove-the-folder-and = 請移除資料夾「{ $val }」然後再試一次。
profiles-profile-corrupt = 設定檔損毀
profiles-profiles = 設定檔
profiles-quit = 離開
profiles-user-1 = 使用者 1
profiles-confirm-lang-choice = 確定要將 Anki 的介面語言改為{ $lang }嗎？
profiles-could-not-create-data-folder = 無法建立資料夾來儲存 Anki 資料。請參閱使用手冊中的〈檔案位置〉(File Locations) 章節，並確保該位置不為唯讀。
profiles-prefs-corrupt-title = 偏好設定損毀
profiles-prefs-file-is-corrupt = Anki 已重新建立損毀的 prefs21.db 檔案。若你曾使用多個設定檔，請新增一個與原來名稱相同的設定檔來回復卡片。
profiles-profile-does-not-exist = 要求的設定檔不存在。
profiles-creating-backup = 正在建立備份...
profiles-backup-created = 已建立備份。
profiles-backup-creation-failed = 備份建立失敗：{ $reason }
profiles-backup-unchanged = 上次備份後沒有更動。
