editing-actual-size = Чыныгы өлчөмүнө которуу
editing-add-media = Медиа кошуу
editing-align-left = Солго түздөө
editing-align-right = Оңго түздөө
editing-an-error-occurred-while-opening = { $val } ачууда ката кетти
editing-attach-picturesaudiovideo = Сүрөт/аудио/видео тиркөө
editing-bold-text = Калың текст
editing-cards = Карталар
editing-center = Ортого
editing-change-color = Түсүн өзгөртүү
editing-cloze-deletion = Жашыруун сөз (жаңы карта)
editing-cloze-deletion-repeat = Жашыруун сөз (ошол эле карта)
editing-copy-image = Сүрөттү көчүрүү
editing-couldnt-record-audio-have-you-installed = Аудио жаздыруу мүмкүн болбоду. 'lame' орноттуңузбу?
editing-customize-card-templates = Карта калыптарын ыңгайлаштыруу
editing-customize-fields = Талааларды ыңгайлаштыруу
editing-cut = Кесип алуу
editing-double-click-image = сүрөттү эки жолу басуу
editing-double-click-to-expand = жайуу үчүн эки жолу басыңыз
editing-double-click-to-collapse = жыйноо үчүн эки жолу басыңыз
editing-edit-current = Учурдагыны түзөтүү
editing-edit-html = HTML'ди түзөтүү
editing-fields = Талаалар
editing-float-left = Солго жылдыруу
editing-float-right = Оңго жылдыруу
editing-float-none = Жылдырбоо
editing-indent = Чыгууну көбөйтүү
editing-italic-text = Жантык текст
editing-jump-to-tags-with-ctrlandshiftandt = Ctrl+Shift+T менен тегдерге өтүү
editing-justify = Эки жакка теңдөө
editing-latex = LaTeX
editing-latex-equation = LaTeX теңдемеси
editing-latex-math-env = LaTeX математикалык чөйрөсү
editing-mathjax-block = Mathjax блогу
editing-mathjax-chemistry = Mathjax химия
editing-mathjax-inline = Mathjax сап ичинде
editing-mathjax-placeholder = Кабыл алуу үчүн { $accept } басыңыз, жаңы сап үчүн { $newline }.
editing-media = Медиа
editing-open-image = Сүрөттү ачуу
editing-show-in-folder = Папкада көрсөтүү
editing-ordered-list = Иреттелген тизме
editing-outdent = Чыгууну азайтуу
editing-paste = Чаптоо
editing-record-audio = Аудио жаздыруу
editing-remove-formatting = Форматтоону алып салуу
editing-restore-original-size = Баштапкы өлчөмүн калыбына келтирүү
editing-select-remove-formatting = Алып салынуучу форматтоону тандоо
editing-show-duplicates = Дубликаттарды көрсөтүү
editing-subscript = Астыңкы индекс
editing-superscript = Үстүңкү индекс
editing-tags = Тегдер
editing-tags-add = Тег кошуу
editing-tags-copy = Тегдерди көчүрүү
editing-tags-remove = Тегдерди алып салуу
editing-tags-select-all = Бардык тегдерди тандоо
editing-text-color = Тексттин түсү
editing-text-highlight-color = Текстти белгилөө түсү
editing-to-make-a-cloze-deletion-on = Учурдагы эскертмеде жашыруун сөз түзүү үчүн, адегенде аны 'Эскертмелер>Эскертме түрүн өзгөртүү' аркылуу жашыруун сөздүү түргө которуу керек
editing-toggle-html-editor = HTML редакторун которуу
editing-toggle-visual-editor = Визуалдык редакторду которуу
editing-toggle-sticky = Жабышчаактыкты которуу
editing-expand = Жайуу
editing-collapse = Жыйноо
editing-expand-field = Талааны жайуу
editing-collapse-field = Талааны жыйноо
editing-underline-text = Тексттин астын сызуу
editing-unordered-list = Иреттелбеген тизме
editing-warning-cloze-deletions-will-not-work = Эскертүү, жашыруун сөздөр жогорудагы түрдү "Жашыруун сөз" режимине котормоюнча иштебейт.
editing-mathjax-preview = Mathjax алдын ала кароо
editing-shrink-images = Сүрөттөрдү кичирейтүү
editing-close-html-tags = HTML тегдерин авто-жабуу
editing-from-clipboard = Алмашуу буферинен
editing-alignment = Түздөө
editing-equations = Теңдемелер
editing-no-image-found-on-clipboard = Алмашуу буферинде сүрөт табылган жок.
editing-image-occlusion-mode = Сүрөттү жабуу режими
editing-image-occlusion-zoom-out = Кичирейтүү
editing-image-occlusion-zoom-in = Чоңойтуу
editing-image-occlusion-zoom-reset = Масштабды баштапкы абалга келтирүү
editing-image-occlusion-toggle-translucent = Тунуктукту которуу
editing-image-occlusion-delete = Өчүрүү
editing-image-occlusion-duplicate = Дубликаттоо
editing-image-occlusion-group = Тандоону топтоо
editing-image-occlusion-ungroup = Топтон чыгаруу
editing-image-occlusion-select-all = Баарын тандоо
editing-image-occlusion-alignment = Түздөө
editing-image-occlusion-align-left = Солго түздөө
editing-image-occlusion-align-h-center = Горизонталдуу борборлор боюнча түздөө
editing-image-occlusion-align-right = Оңго түздөө
editing-image-occlusion-align-top = Жогору түздөө
editing-image-occlusion-align-v-center = Вертикалдуу борборлор боюнча түздөө
editing-image-occlusion-align-bottom = Төмөн түздөө
editing-image-occlusion-select-tool = Тандоо
editing-image-occlusion-zoom-tool = Масштаб
editing-image-occlusion-rectangle-tool = Тик бурчтук
editing-image-occlusion-ellipse-tool = Эллипс
editing-image-occlusion-polygon-tool = Көп бурчтук
editing-image-occlusion-text-tool = Текст
editing-image-occlusion-fill-tool = Түс менен толтуруу
editing-image-occlusion-toggle-mask-editor = Маска редакторун которуу
editing-image-occlusion-reset = Сүрөттөгү жашырууларды баштапкы абалга келтирүү
editing-image-occlusion-confirm-reset = Бул сүрөттү жабууну баштапкы абалга келтирүүгө ишенесизби?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML редактору
