qt-accel-about = &Quant a…
qt-accel-about-mac = Sobre Anki…
qt-accel-cards = &Targetes
qt-accel-check-database = &Comprova la base de dades
qt-accel-check-media = Comprova &els fitxers multimèdia
qt-accel-edit = &Edita
qt-accel-exit = &Surt
qt-accel-export = &Exporta…
qt-accel-export-notes = &Exporta les notes…
qt-accel-file = &Fitxer
qt-accel-filter = Fil&tra
qt-accel-find = &Cerca
qt-accel-find-and-replace = Cerca i reemplaça…
qt-accel-find-duplicates = Cerca’n &de duplicades…
qt-accel-go = &Ves
qt-accel-guide = &Manual
qt-accel-help = &Ajuda
qt-accel-import = &Importa…
qt-accel-info = &Informació…
qt-accel-invert-selection = &Inverteix la selecció
qt-accel-next-card = &Targeta següent
qt-accel-note = N&ota
qt-accel-notes = &Notes
qt-accel-preferences = &Preferències
qt-accel-previous-card = Targeta &anterior
qt-accel-select-all = Selecciona-ho &tot
qt-accel-select-notes = Selecciona &les notes
qt-accel-support-anki = &Dona suport a Anki…
qt-accel-switch-profile = &Canvia de perfil
qt-accel-tools = &Eines
qt-accel-undo = &Desfés
qt-accel-redo = &Refés
qt-accel-set-due-date = Defineix una &data de venciment…
qt-accel-forget = &Oblida
qt-accel-view = &Mostra
qt-accel-full-screen = Activa/desactiva la &pantalla completa
qt-accel-layout = &Disposició
qt-accel-layout-auto = &Automàtic
qt-accel-layout-vertical = &Vertical
qt-accel-layout-horizontal = &Horitzontal
qt-accel-zoom-in = &Amplia
qt-accel-zoom-out = &Redueix
qt-accel-reset-zoom = &Reestableix el zoom
qt-accel-toggle-sidebar = Activa/desactiva la barra lateral
qt-accel-zoom-editor-in = &Apropa l'editor
qt-accel-zoom-editor-out = &Redueix l’editor
qt-accel-create-backup = Fes una còpia de seguretat
qt-accel-load-backup = &Restaura una còpia de seguretat
qt-accel-upgrade-downgrade = Puja/baixa de versió
