notetypes-front-field = Лице
notetypes-back-field = Наличје
notetypes-add-reverse-field = Додај повратак
notetypes-text-field = Текст
notetypes-basic-name = Основно
notetypes-basic-reversed-name = Основна (и обратне карте)
notetypes-basic-optional-reversed-name = Основна (обратне по избору)
notetypes-cloze-name = Пропусти
notetypes-card-2-name = Карта 2
notetypes-card-1-name = Карта 1
notetypes-add = Додај: { $val }
notetypes-add-note-type = Додај тип белешке
notetypes-cards = Карте...
notetypes-clone = Клонирај: { $val }
notetypes-copy = { $val } копија
notetypes-delete-this-note-type-and-all = Да избришем овај тип белешке и све карте тог типа?
notetypes-delete-this-unused-note-type = Да избришем овај некоришћени тип белешке?
notetypes-fields = Поља...
notetypes-footer = Zaglavlje
notetypes-header = Заглавље
notetypes-note-types = Тип бележака
notetypes-options = Опције...
notetypes-please-add-another-note-type-first = Најпре додај нову врсту белешке.
notetypes-type = Тип
