preferences-automatically-sync-on-profile-openclose = Аутоматски синхронизуј при отварању/затварању профила
preferences-backups = Резервне копије
preferences-backups2 = резерве
preferences-backupsanki-will-create-a-backup-of = <b>Резервне копије</b><br>Anki ће направити резервну копију  колекције при сваком затварању и синхронизацији.
preferences-basic = Основно
preferences-change-deck-depending-on-note-type = Промени шпил зависно од типа белешке
preferences-hours-past-midnight = часова после поноћи
preferences-interface-language = Језик сучеља:
preferences-keep = Сачувај до
preferences-learn-ahead-limit = Научи да ограничиш
preferences-mins = мин.
preferences-network = Мрежа
preferences-next-day-starts-at = Нови дан почиње од
preferences-note-media-is-not-backed-up = Пажња: датотеке стављене на карте се не копирају. За сваки случај, повремено направите резервне копије своје фасцикле Anki.
preferences-on-next-sync-force-changes-in = При следећој синхронизацији, значење се мења у једном смеру
preferences-paste-clipboard-images-as-png = Налепи слику из међумеморије као PNG
preferences-preferences = Подешавања
preferences-scheduling = Измени редослед
preferences-show-next-review-time-above-answer = Прикажи време следећег понављања над дугмадима са одговорима
preferences-show-remaining-card-count-during-review = Приказуј број преосталих карата током понављања
preferences-some-settings-will-take-effect-after = Нека подешавања ће почети деловати тек када поново покренете Anki.
preferences-synchronisation = <b>Синхронизација</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Синхронизација</b><br> Искључена је; да бисте је укључили, кликните на дугме синхронизације у главном прозору.
preferences-synchronize-audio-and-images-too = Синхронизуј такође звуке и слике
preferences-timebox-time-limit = Временско ограничење
preferences-when-adding-default-to-current-deck = Подразумевано ставити направљено у текући шпил
