decks-add-new-deck-ctrlandn = Dodaj nową talię (Ctrl+N)
decks-build = Buduj
decks-cards-selected-by = Wybrane karty:
decks-create-deck = Utwórz talię
decks_create_even_if_empty = Utwórz/uaktualnij tę talię nawet gdy jest pusta
decks-custom-steps-in-minutes = Własne kroki (w minutach)
decks-deck = Talia
decks-decreasing-intervals = Malejące przerwy
decks-delete-deck = Usuń talię
decks-enable-second-filter = Włącz drugi filtr
decks-filter = Filtr:
decks-filter-2 = Filtr 2
decks-get-shared = Pobierz gotową
decks-import-file = Importuj plik
decks-increasing-intervals = Rosnące przerwy
decks-latest-added-first = Najpierw ostatnio dodane
decks-limit-to = Ogranicz do
decks-minutes = minut
decks-most-lapses = Najwięcej pomyłek
decks-new-deck-name = Nowa nazwa talii:
decks-no-deck = [brak talii]
decks-oldest-seen-first = Najpierw najstarsze
decks-order-added = W kolejności dodania
decks-order-due = W kolejności oczekiwania
decks-please-select-something = Należy wybrać co najmniej jeden element.
decks-random = Losowa
decks-relative-overdueness = Według względnego spóźnienia
decks-repeat-failed-cards-after = Powtórz karty z błędną odpowiedzią po
# e.g. "Delay for Again", "Delay for Hard", "Delay for Good"
decks-delay-for-button = Przerwa dla przycisku { $button }
decks-reschedule-cards-based-on-my-answers = Zmień plan na podstawie odpowiedzi w tej talii
decks-study = Nauka
decks-study-deck = Nauka talii
decks-filtered-deck-search-empty = Nie znaleziono kart zgodnych z wyszukiwaniem. Wyszukiwanie niektórych kart może być wykluczone ponieważ są one zawieszone lub znajdują się w innej talii filtrowanej.
decks-unmovable-cards = Pokaż jakiekolwiek wykluczone karty
decks-learn-header = Uczone
# The count of cards waiting to be reviewed
decks-review-header = Oczekujące
decks-zero-minutes-hint = (0 = zwróć kartę do oryginalnej talii)
