profiles-anki-could-not-read-your-profile = Anki nie było w stanie odczytać twoich danych profilowych. Rozmiar okna i dane logowania do synchronizacji zostały zapomniane.
profiles-anki-could-not-rename-your-profile = Anki nie było w stanie zmienić nazwę Twojego profilu, ponieważ nie udało się zmienić nazwy folderu z profilem na dysku. Upewnij się, że masz uprawnienia do zapisu do Dokumenty/Anki i że żadne inne programy nie korzystają z folderów profilu, a następnie spróbuj ponownie.
profiles-folder-already-exists = Folder już istnieje.
profiles-open = Otwórz
profiles-open-backup = Otwórz kopię zapasową...
profiles-please-remove-the-folder-and = Usuń folder { $val } i spróbuj ponownie.
profiles-profile-corrupt = Profil uszkodzony
profiles-profiles = Profile
profiles-quit = Zamknij
profiles-user-1 = Użytkownik 1
profiles-confirm-lang-choice = Czy na pewno chcesz wyświetlać interfejs Anki w tym języku: { $lang }?
profiles-could-not-create-data-folder = Anki nie mogło utworzyć folderu z danymi. Zobacz rozdział „Lokalizacja plików” w instrukcji i upewni się, że lokalizacja ta nie jest ustawiona jako „tylko do odczytu”.
profiles-prefs-corrupt-title = Ustawienia uszkodzone
profiles-prefs-file-is-corrupt = Plik Anki prefs21.db był uszkodzony i został utworzony ponownie. Jeśli korzystałeś z wielu profilów dodaj je ponownie używając tych samych nazw, aby odzyskać karty.
profiles-profile-does-not-exist = Żądany profil nie istnieje.
profiles-creating-backup = Tworzenie kopii zapasowej...
profiles-backup-created = Utworzono kopię zapasową.
profiles-backup-creation-failed = Nie udało się utworzyć kopii zapasowej: { $reason }
profiles-backup-unchanged = Nie ma zmian od ostatniej kopii zapasowych.
