qt-accel-about = &וועגן
qt-accel-about-mac = וועגן „אַנקי״…
qt-accel-cards = &קאַרטלעך
qt-accel-check-database = &באַטראַכטן דאַטן-באַזע
qt-accel-check-media = באַטראַכטן &מעדיע
qt-accel-edit = &בײַטן
qt-accel-exit = אַ&רויס
qt-accel-export = &אַרויספֿירן…
qt-accel-export-notes = &אַרויספֿירן נאָטיצן
qt-accel-file = &טעקע
qt-accel-filter = פֿיל&טרירן
qt-accel-find = &זוכן
qt-accel-find-and-replace = זוכן און פֿאַר&בײַטן…
qt-accel-find-duplicates = זוכן &דופּליקאַטן…
qt-accel-go = &גיין
qt-accel-guide = &וועגווײַזער
qt-accel-help = &הילף
qt-accel-import = &אַרײַנפֿירן…
qt-accel-info = &ידיעות…
qt-accel-invert-selection = &איבערדרייען אָפּקלײַב
qt-accel-next-card = &נעקסטיקע קאַרטל
qt-accel-note = נ&אָטיץ
qt-accel-notes = &נאָטיצן
qt-accel-preferences = &אויסוואַלן
qt-accel-previous-card = &פֿריערדיקע קאַרטל
qt-accel-select-all = אויסקלײַבן &אַלע
qt-accel-select-notes = אויסגעקליבענע &נאָטיצן
qt-accel-support-anki = &שטיצן אַנקי
qt-accel-switch-profile = &אויסבײַטן פּראָפֿיל
qt-accel-tools = &מכשירים
qt-accel-undo = &אַנולירן
qt-accel-redo = &איבערמאַכן
qt-accel-set-due-date = שטעלן &טערמין
qt-accel-forget = &אײַנשטעלן אויף ס׳נײַ
qt-accel-view = &אויסבליק
qt-accel-full-screen = איבערשליסן &פֿולער-עקראָן
qt-accel-layout = &אויסשטעל
qt-accel-layout-auto = &אויטאָ
qt-accel-layout-vertical = &ווערטיקאַל
qt-accel-layout-horizontal = &האָריזאָנטאַל
qt-accel-zoom-in = &אײַנזומירן
qt-accel-zoom-out = &אויסזומירן
qt-accel-reset-zoom = &אײַנשטעלן זום אויף ס׳נײַ
qt-accel-toggle-sidebar = איבערשליסן זײַט-קעסטל
qt-accel-zoom-editor-in = אײַנזומירן &רעדאַקטירער
qt-accel-zoom-editor-out = אויסזומירן &רעדאַקטירער
qt-accel-create-backup = שאַפֿן &רעזערוו-קאָפּיע
qt-accel-load-backup = &צוריקציִען אין אַ רעזערוו-קאָפּיע
qt-accel-upgrade-downgrade = פֿאָרויסרוקן / צוריקרוקן אַנקי-נוסח
