name: Checks

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up protoc
        uses: Arduino/actions/setup-protoc@master
      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: Run checks
        run: |
          (cd .. && git clone https://github.com/ankitects/anki-proto.git)
          (cd .. && git clone https://github.com/ankitects/anki-lib-rust.git)
          make check BUILDFLAGS=""
