actions-add = Tambah
actions-all-selected = Semua terpilih
actions-any-selected = Mana-mana terpilih
actions-cancel = Batal
actions-choose = Pilih
actions-close = Tutup
actions-copy = Salin
actions-create-copy = Cipta Salinan
actions-custom-study = Ulang Kaji Tersuai
actions-decks = Dek
actions-decrement-value = Turun nilai
actions-delete = Padam
actions-export = Eksport
actions-filter = Tapis
actions-help = Bantuan
actions-increment-value = Naik nilai
actions-import = Import
actions-manage = Uruskan...
actions-name = Nama:
actions-new = Baru
actions-new-name = Nama baru:
actions-options = Tetapan
actions-options-for = Tetapan untuk { $val }
actions-preview = Pratonton
actions-rebuild = Bina semula
actions-rename = Nama Semula
actions-rename-deck = Nama Semula Dek
actions-rename-tag = Nama Semula Tag
actions-rename-with-parents = Nama Semula termasuk Induk
actions-remove-tag = Buang Tag
actions-replay-audio = Main Semula Audio
actions-reposition = Alih Posisi
actions-save = Simpan
actions-search = Cari
actions-select = Pilih
actions-shortcut-key = Kekunci pintasan: { $val }
actions-suspend-card = Bekukan Kad
actions-set-due-date = Tetapkan Tarikh Tunggakan
actions-answer-card = Jawab Kad
actions-unbury-unsuspend = Tampil/Aktifkan
actions-add-deck = Tambah Dek
actions-add-note = Tambah Nota
actions-update-tag = Kemas Kini Tag
actions-update-note = Kemas Kini Nota
actions-update-card = Kemas Kini Kad
actions-update-deck = Kemas Kini Dek
actions-forget-card = Lupakan Kad
actions-build-filtered-deck = Bina Dek
actions-add-notetype = Tambah Jenis Nota
actions-remove-notetype = Buang Jenis Nota
actions-update-notetype = Kemas Kini Jenis Nota
actions-update-config = Kemas Kini Tetapan
actions-card-info = Info Kad
actions-previous-card-info = Info Kad Sebelumnya
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-fullscreen-unsupported = Mod skrin penuh tidak disokong oleh driver video anda. Cuba tukar kepada yang lain daripada skrin tetapan.

## Flags

actions-flag-number = Tanda { $number }
actions-flag-red = Merah
actions-flag-orange = Jingga
actions-flag-green = Hijau
actions-flag-blue = Biru
actions-flag-pink = Merah Jambu
actions-flag-turquoise = Firus
actions-flag-purple = Ungu
actions-set-flag = Tetap Tanda
actions-nothing-to-undo = Tiada untuk dibuat asal
actions-nothing-to-redo = Tiada untuk dibuat semula
