qt-accel-about = datni
qt-accel-browse-and-install = nu purci catlu je cu ci'erse'a
qt-accel-cards = karda
qt-accel-check-database = nu cipcta lo datni vasru
qt-accel-check-media = nu cipcta lo ganvi
qt-accel-edit = binxo
qt-accel-exit = sisti
qt-accel-export = barbei
qt-accel-export-notes = barbei lo karda datni
qt-accel-file = datnyvei
qt-accel-filter = julne
qt-accel-find = sisku
qt-accel-find-and-replace = sisku je cu basygau
qt-accel-find-duplicates = sisku lo ka mintu
qt-accel-go = nu klama
qt-accel-guide = djunoi
qt-accel-help = sidju
qt-accel-import = nerbei
qt-accel-info = datni
qt-accel-invert-selection = nu lo se cuxna cu se basti lo fatne
qt-accel-next-card = bavla'i fi lo'i karda
qt-accel-note = karda datni
qt-accel-notes = karda datni
qt-accel-open-addons-folder = nu catlu lo se samtcise'a datnyveimei
qt-accel-preferences = te tcimi'e
qt-accel-previous-card = prula'i fi lo'i karda
qt-accel-reschedule = basti fi lo ka tcika
qt-accel-select-all = cuxna ro da
qt-accel-select-notes = cuxna pa karda datni
qt-accel-support-anki = nu rupsra lo favgau be la .ankis.
qt-accel-switch-profile = samymo'i pa pilno datni poi drata
qt-accel-tools = tutci
qt-accel-undo = xruti
