qt-accel-about = &Tentang
qt-accel-about-mac = Tentang Anki...
qt-accel-cards = &Kartu-kartu
qt-accel-check-database = &Periksa Basis Data
qt-accel-check-media = Periksa &Media
qt-accel-edit = &Ubah
qt-accel-exit = &Keluar
qt-accel-export = &Ekspor...
qt-accel-export-notes = &Ekspor catatan...
qt-accel-file = &File
qt-accel-filter = Fil&ter
qt-accel-find = &Temukan
qt-accel-find-and-replace = Temukan dan Gan&ti...
qt-accel-find-duplicates = Temukan &Duplikat...
qt-accel-go = &Cari
qt-accel-guide = &Panduan
qt-accel-help = &Bantuan
qt-accel-import = &Impor
qt-accel-info = &Info
qt-accel-invert-selection = &Balikkan Pilihan
qt-accel-next-card = &Kartu Berikutnya
qt-accel-note = &Catatan
qt-accel-notes = &Catatan-catatan
qt-accel-preferences = &Preferensi
qt-accel-previous-card = &Kartu Sebelumnya
qt-accel-select-all = Pilih &Semua
qt-accel-select-notes = Pilih &Catatan
qt-accel-support-anki = &Dukung Anki
qt-accel-switch-profile = &Ganti Profil
qt-accel-tools = &Alat
qt-accel-undo = &Urungkan
qt-accel-redo = &Ulangi
qt-accel-set-due-date = Atur &Jatuh tempo...
qt-accel-forget = &Atur ulang
qt-accel-view = &Tampilan
qt-accel-full-screen = Aktifkan &Full Screen
qt-accel-layout = &Tata letak
qt-accel-layout-auto = &Otomatis
qt-accel-layout-vertical = &Vertikal
qt-accel-layout-horizontal = &Horizontal
qt-accel-zoom-in = Per&besar
qt-accel-zoom-out = Per&kecil
qt-accel-reset-zoom = Atur ulang &Zoom
qt-accel-toggle-sidebar = Aktifkan Bilah Sisi
qt-accel-zoom-editor-in = Zoom Editor Per&besar
qt-accel-zoom-editor-out = Zoom Editor Per&kecil
qt-accel-create-backup = Buat &Cadangan
qt-accel-load-backup = &Kembalikan ke Cadangan
qt-accel-upgrade-downgrade = Upgrade/Downgrade
