editing-actual-size = Activar/desactivar tamaño real
editing-add-media = Añadir archivos multimedia
editing-align-left = Alinear a la izquierda
editing-align-right = Alinear a la derecha
editing-an-error-occurred-while-opening = Ocurrió un error al abrir { $val }
editing-attach-picturesaudiovideo = Adjuntar imágenes/audio/video
editing-bold-text = Texto en negrita
editing-cards = Tarjetas
editing-center = Centrar
editing-change-color = Cambiar el color
editing-cloze-deletion = Respuesta anidada (nueva tarjeta)
editing-cloze-deletion-repeat = Respuesta anidada (misma tarjeta)
editing-copy-image = Copiar imagen
editing-couldnt-record-audio-have-you-installed = No se pudo grabar el audio. ¿Tienes instalado “lame”?
editing-customize-card-templates = Personalizar plantillas de tarjetas
editing-customize-fields = Personalizar campos
editing-cut = Cortar
editing-double-click-image = Haga doble clic en la imagen
editing-double-click-to-expand = doble clic para expandir
editing-double-click-to-collapse = doble clic para colapsar
editing-edit-current = Editar actual
editing-edit-html = Editar HTML
editing-fields = Campos
editing-float-left = Flotar a la izquierda
editing-float-right = Flotar a la derecha
editing-float-none = No flotar
editing-indent = Aumentar la sangría
editing-italic-text = Texto en cursiva
editing-jump-to-tags-with-ctrlandshiftandt = Saltar a etiquetas con Ctrl+Mayús+T
editing-justify = Justificar
editing-latex = LaTeX
editing-latex-equation = Ecuación LaTeX
editing-latex-math-env = Entorno matemático LaTeX
editing-mathjax-block = Bloque de MathJax
editing-mathjax-chemistry = Química MathJax
editing-mathjax-inline = MathJax en línea
editing-mathjax-placeholder = Presiona { $accept } para aceptar, { $newline } para una nueva línea.
editing-media = Multimedia
editing-open-image = Abrir imagen
editing-show-in-folder = Mostrar en carpeta
editing-ordered-list = Lista numerada
editing-outdent = Disminuir la sangría
editing-paste = Pegar
editing-record-audio = Grabar audio
editing-remove-formatting = Limpiar formato
editing-restore-original-size = Restaurar tamaño original
editing-select-remove-formatting = Seleccionar formato para eliminar
editing-show-duplicates = Mostrar duplicadas
editing-subscript = Subíndice
editing-superscript = Superíndice
editing-tags = Etiquetas
editing-tags-add = Agregar etiqueta
editing-tags-copy = Copiar etiquetas
editing-tags-remove = Remover etiquetas
editing-tags-select-all = Seleccionar todas las etiquetas
editing-text-color = Color de texto
editing-text-highlight-color = Color de resaltado de texto
editing-to-make-a-cloze-deletion-on = Para crear preguntas anidadas en una nota existente, primero debe cambiarla a un tipo de nota de respuesta anidada, mediante “Editar → Cambiar tipo de nota”.
editing-toggle-html-editor = Activar/desactivar editor HTML
editing-toggle-visual-editor = Ocultar/mostrar editor visual
editing-toggle-sticky = Activar/desactivar anclaje del texto
editing-expand = Expandir
editing-collapse = Colapsar
editing-expand-field = Expandir campo
editing-collapse-field = Colapsar campo
editing-underline-text = Subrayar texto
editing-unordered-list = Lista con viñetas
editing-warning-cloze-deletions-will-not-work = Cuidado, los nidos no funcionarán a menos que cambies el tipo de nota a respuesta anidada.
editing-mathjax-preview = Vista previa MathJax
editing-shrink-images = Reducir imágenes
editing-close-html-tags = Cerrar automáticamente etiquetas HTML
editing-from-clipboard = Desde el portapapeles
editing-alignment = Alineación
editing-equations = Ecuaciones
editing-no-image-found-on-clipboard = No se encontró una imagen en el portapapeles.
editing-image-occlusion-mode = Modo de oclusión de imagen
editing-image-occlusion-zoom-out = Reducir zoom
editing-image-occlusion-zoom-in = Ampliar zoom
editing-image-occlusion-zoom-reset = Reestablecer zoom
editing-image-occlusion-toggle-translucent = Activar/desactivar la transparencia
editing-image-occlusion-delete = Eliminar
editing-image-occlusion-duplicate = Duplicar
editing-image-occlusion-group = Agrupar la selección
editing-image-occlusion-ungroup = Desagrupar la selección
editing-image-occlusion-select-all = Seleccionar todo
editing-image-occlusion-alignment = Alineación
editing-image-occlusion-align-left = Alinear a la izquierda
editing-image-occlusion-align-h-center = Centrar horizontalmente
editing-image-occlusion-align-right = Alinear a la derecha
editing-image-occlusion-align-top = Alinear hacia arriba
editing-image-occlusion-align-v-center = Centrar verticalmente
editing-image-occlusion-align-bottom = Alinear hacia abajo
editing-image-occlusion-select-tool = Seleccionar
editing-image-occlusion-zoom-tool = Zoom
editing-image-occlusion-rectangle-tool = Rectángulo
editing-image-occlusion-ellipse-tool = Elipse
editing-image-occlusion-polygon-tool = Polígono
editing-image-occlusion-text-tool = Texto
editing-image-occlusion-fill-tool = Llenar con color
editing-image-occlusion-toggle-mask-editor = Activar/desactivar el editor de máscara
editing-image-occlusion-reset = Reiniciar la oclusión de imagen
editing-image-occlusion-confirm-reset = ¿Estás seguro de querer reiniciar esta oclusión de imagen?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Editor HTML
