actions-add = Add
actions-all-selected = All selected
actions-any-selected = Any selected
actions-blue-flag = Blue Flag
actions-cancel = Cancel
actions-choose = Choose
actions-close = Close
actions-copy = Copy
actions-custom-study = Custom Study
actions-decks = Decks
actions-delete = Delete
actions-export = Export
actions-filter = Filter
actions-green-flag = Green Flag
actions-help = Help
actions-import = Import
actions-manage = Manage...
actions-name = Name:
actions-new = New
actions-new-name = New name:
actions-options = Options
actions-options-for = Options for { $val }
actions-orange-flag = Orange Flag
actions-preview = Preview
actions-rebuild = Rebuild
actions-red-flag = Red Flag
actions-rename = Rename
actions-rename-deck = Rename Deck
actions-rename-tag = Rename Tag
actions-remove-tag = Remove Tag
actions-replay-audio = Replay Audio
actions-reposition = Reposition
actions-save = Save
actions-search = Search
actions-select = Select
actions-shortcut-key = Shortcut key: { $val }
actions-suspend-card = Suspend Card
actions-set-due-date = Set Due Date
actions-forget = Forget
actions-answer-card = Answer Card
actions-unbury-unsuspend = Unbury/Unsuspend
actions-add-deck = Add Deck
actions-add-note = Add Note
actions-update-tag = Update Tag
actions-update-note = Update Note
actions-update-card = Update Card
actions-update-deck = Update Deck
actions-forget-card = Forget Card
actions-set-flag = Set Flag
actions-build-filtered-deck = Build Deck
actions-expand-collapse = Expand/Collapse
actions-add-notetype = Add Notetype
actions-remove-notetype = Remove Notetype
actions-update-notetype = Update Notetype
