actions-add = Add
actions-blue-flag = Blue Flag
actions-cancel = Cancel
actions-choose = Choose
actions-close = Close
actions-copy = Copy
actions-custom-study = Custom Study
actions-decks = Decks
actions-delete = Delete
actions-export = Export
actions-filter = Filter
actions-green-flag = Green Flag
actions-help = Help
actions-import = Import
actions-manage = Manage...
actions-name = Name:
actions-new = New
actions-new-name = New name:
actions-options = Options
actions-options-for = Options for { $val }
actions-orange-flag = Orange Flag
actions-preview = Preview
actions-rebuild = Rebuild
actions-red-flag = Red Flag
actions-rename = Rename
actions-rename-deck = Rename Deck
actions-rename-tag = Rename Tag
actions-replay-audio = Replay Audio
actions-reposition = Reposition
actions-save = Save
actions-search = Search
actions-shortcut-key = Shortcut key: { $val }
actions-suspend-card = Suspend Card
