browsing-add-notes = Add Notes...
browsing-add-tags = Add Tags
browsing-add-tags2 = Add Tags...
browsing-addon = Add-on
browsing-all-card-types = All Card Types
browsing-all-fields = All Fields
browsing-answer = Answer
browsing-any-cards-mapped-to-nothing-will = Any cards mapped to nothing will be deleted. If a note has no remaining cards, it will be lost. Are you sure you want to continue?
browsing-any-flag = Any Flag
browsing-browser-appearance = Browser Appearance
browsing-browser-options = Browser Options
browsing-buried = Buried
browsing-card = Card
browsing-card-list = Card List
browsing-card-state = Card State
browsing-cards-cant-be-manually-moved-into = Cards can't be manually moved into a filtered deck.
browsing-change-deck = Change Deck
browsing-change-deck2 = Change Deck...
browsing-change-note-type = Change Note Type
browsing-change-note-type2 = Change Note Type...
browsing-change-to = Change { $val } to:
browsing-clear-unused = Clear Unused
browsing-clear-unused-tags = Clear Unused Tags
browsing-created = Created
browsing-ctrlandshiftande = Ctrl+Shift+E
browsing-current-deck = Current Deck
browsing-current-note-type = Current note type:
browsing-delete-notes = Delete Notes
browsing-delete-tags = Delete Tags
browsing-duplicate = duplicate
browsing-ease = Ease
browsing-end = End
browsing-enter-tags-to-add = Enter tags to add:
browsing-enter-tags-to-delete = Enter tags to delete:
browsing-filtered = (filtered)
browsing-find = <b>Find</b>:
browsing-find-and-replace = Find and Replace
browsing-find-duplicates = Find Duplicates
browsing-first-card = First Card
browsing-flag = Flag
browsing-font = <b>Font</b>:
browsing-font-size = <b>Font Size</b>:
browsing-found-as-across-bs = Found { $part } across { $whole }.
browsing-home = Home
browsing-ignore-case = Ignore case
browsing-in = <b>In</b>:
browsing-interval = Interval
browsing-last-card = Last Card
browsing-learning = (learning)
browsing-line-size = <b>Line Size</b>:
browsing-manage-note-types = Manage Note Types...
browsing-move-cards = Move Cards
browsing-move-cards-to-deck = Move cards to deck:
browsing-nd-names = { $num }: { $name }
browsing-new = (new)
browsing-new-note-type = New note type:
browsing-no-flag = No Flag
browsing-note = Note
browsing-notes-tagged = Notes tagged.
browsing-nothing = Nothing
browsing-only-new-cards-can-be-repositioned = Only new cards can be repositioned.
browsing-optional-filter = Optional filter:
browsing-override-back-template = Override back template:
browsing-override-font = Override font:
browsing-override-front-template = Override front template:
browsing-please-give-your-filter-a-name = Please give your filter a name:
browsing-please-select-cards-from-only-one = Please select cards from only one note type.
browsing-preview-selected-card = Preview Selected Card ({ $val })
browsing-question = Question
browsing-queue-bottom = Queue bottom: { $val }
browsing-queue-top = Queue top: { $val }
browsing-randomize-order = Randomize order
browsing-remove-current-filter = Remove Current Filter...
browsing-remove-from-your-saved-searches = Remove { $val } from your saved searches?
browsing-remove-tags = Remove Tags...
browsing-replace-with = <b>Replace With</b>:
browsing-reposition = Reposition...
browsing-reposition-new-cards = Reposition New Cards
browsing-reschedule = Reschedule
browsing-save-current-filter = Save Current Filter...
browsing-search-bar-hint = Search cards/notes (type text, then press Enter)
browsing-search-in = Search in:
browsing-search-within-formatting-slow = Search within formatting (slow)
browsing-shift-position-of-existing-cards = Shift position of existing cards
browsing-sidebar = Sidebar
browsing-sidebar-filter = Sidebar filter
browsing-sort-field = Sort Field
browsing-sorting-on-this-column-is-not = Sorting on this column is not supported. Please choose another.
browsing-start-position = Start position:
browsing-step = Step:
browsing-suspended = Suspended
browsing-tag-duplicates = Tag Duplicates
browsing-tag-rename-warning-empty = You can't rename a tag that has no notes.
browsing-target-field = Target field:
browsing-toggle-mark = Toggle Mark
browsing-toggle-suspend = Toggle Suspend
browsing-treat-input-as-regular-expression = Treat input as regular expression
browsing-whole-collection = Whole Collection
browsing-you-must-have-at-least-one = You must have at least one column.
browsing-group =
    { $count ->
        [one] { $count } group
       *[other] { $count } groups
    }
browsing-note-count =
    { $count ->
        [one] { $count } note
       *[other] { $count } notes
    }
browsing-note-deleted =
    { $count ->
        [one] { $count } note deleted.
       *[other] { $count } notes deleted.
    }
browsing-window-title = Browse ({ $selected } of { $total } cards selected)
browsing-sidebar-expand-children = Expand Children
browsing-sidebar-collapse-children = Collapse Children
browsing-sidebar-decks = Decks
browsing-sidebar-tags = Tags
browsing-sidebar-notetypes = Note Types
browsing-sidebar-saved-searches = Saved Searches
browsing-sidebar-save-current-search = Save Current Search
browsing-sidebar-card-state = Card State
browsing-sidebar-flags = Flags
browsing-today = Today
browsing-studied-today = Studied
browsing-added-today = Added
browsing-again-today = Again
browsing-edited-today = Edited
browsing-sidebar-due-today = Due
browsing-sidebar-untagged = Untagged
