card-stats-added = Added
card-stats-first-review = First Review
card-stats-latest-review = Latest Review
card-stats-interval = Interval
card-stats-ease = Ease
card-stats-review-count = Reviews
card-stats-lapse-count = Lapses
card-stats-average-time = Average Time
card-stats-total-time = Total Time
card-stats-new-card-position = Position
card-stats-card-template = Card Type
card-stats-note-type = Note Type
card-stats-deck-name = Deck
card-stats-preset = Preset
card-stats-note-id = Note ID
card-stats-card-id = Card ID
card-stats-review-log-rating = Rating
card-stats-review-log-type = Type
card-stats-review-log-date = Date
card-stats-review-log-time-taken = Time
card-stats-review-log-type-learn = Learn
card-stats-review-log-type-review = Review
card-stats-review-log-type-relearn = Relearn
card-stats-review-log-type-filtered = Filtered
card-stats-review-log-type-manual = Manual
card-stats-review-log-type-rescheduled = Rescheduled
card-stats-review-log-elapsed-time = Elapsed Time
card-stats-no-card = (No card to display.)
card-stats-custom-data = Custom Data
card-stats-fsrs-stability = Stability
card-stats-fsrs-difficulty = Difficulty
card-stats-fsrs-retrievability = Retrievability
card-stats-fsrs-forgetting-curve-title = Forgetting Curve
card-stats-fsrs-forgetting-curve-first-week = First Week
card-stats-fsrs-forgetting-curve-first-month = First Month
card-stats-fsrs-forgetting-curve-first-year = First Year
card-stats-fsrs-forgetting-curve-all-time = All Time
card-stats-fsrs-forgetting-curve-probability-of-recalling = Probability of Recall
card-stats-fsrs-forgetting-curve-desired-retention = Desired Retention

## Window Titles

card-stats-current-card = Current Card ({ $context })
card-stats-previous-card = Previous Card ({ $context })
