custom-study-must-rename-deck = Please rename the existing Custom Study deck first.
custom-study-all-cards-in-random-order-dont = All cards in random order (don't reschedule)
custom-study-all-review-cards-in-random-order = All review cards in random order
custom-study-cards = cards
custom-study-cards-from-the-deck = cards from the deck
custom-study-choose-tags = Choose Tags
custom-study-custom-study-session = Custom Study Session
custom-study-due-cards-only = Due cards only
custom-study-increase-todays-new-card-limit = Increase today's new card limit
custom-study-increase-todays-new-card-limit-by = Increase today's new card limit by
custom-study-increase-todays-review-card-limit = Increase today's review card limit
custom-study-increase-todays-review-limit-by = Increase today's review limit by
custom-study-new-cards-in-deck-over-today = New cards in deck over today limit: { $val }
custom-study-new-cards-only = New cards only
custom-study-no-cards-matched-the-criteria-you = No cards matched the criteria you provided.
custom-study-ok = OK
custom-study-preview-new-cards = Preview new cards
custom-study-preview-new-cards-added-in-the = Preview new cards added in the last
custom-study-require-one-or-more-of-these = Require one or more of these tags:
custom-study-review-ahead = Review ahead
custom-study-review-ahead-by = Review ahead by
custom-study-review-cards-forgotten-in-last = Review cards forgotten in last
custom-study-review-forgotten-cards = Review forgotten cards
custom-study-reviews-due-in-deck-over-today = Reviews due in deck over today limit: { $val }
custom-study-select = Select
custom-study-select-tags-to-exclude = Select tags to exclude:
custom-study-selective-study = Selective Study
custom-study-study-by-card-state-or-tag = Study by card state or tag
