editing-add-media = Add Media
editing-align-left = Align left
editing-align-right = Align right
editing-an-error-occurred-while-opening = An error occurred while opening { $val }
editing-attach-picturesaudiovideo = Attach pictures/audio/video
editing-bold-text = Bold text
editing-cards = Cards
editing-center = Center
editing-change-color = Change color
editing-cloze-deletion = Cloze deletion
editing-couldnt-record-audio-have-you-installed = Couldn't record audio. Have you installed 'lame'?
editing-customize-card-templates = Customize Card Templates
editing-customize-fields = Customize Fields
editing-cut = Cut
editing-edit-current = Edit Current
editing-edit-html = Edit HTML
editing-fields = Fields
editing-html-editor = HTML Editor
editing-indent = Increase indent
editing-italic-text = Italic text
editing-jump-to-tags-with-ctrlandshiftandt = Jump to tags with Ctrl+Shift+T
editing-justify = Justify
editing-latex = LaTeX
editing-latex-equation = LaTeX equation
editing-latex-math-env = LaTeX math env.
editing-mathjax-block = MathJax block
editing-mathjax-chemistry = MathJax chemistry
editing-mathjax-inline = MathJax inline
editing-media = Media
editing-ordered-list = Ordered list
editing-outdent = Decrease indent
editing-paste = Paste
editing-record-audio = Record audio
editing-remove-formatting = Remove formatting
editing-set-text-color = Set text color
editing-set-text-highlight-color = Set text highlight color
editing-show-duplicates = Show Duplicates
editing-subscript = Subscript
editing-superscript = Superscript
editing-tags = Tags
editing-to-make-a-cloze-deletion-on = To make a cloze deletion on an existing note, you need to change it to a cloze type first, via 'Notes>Change Note Type'
editing-toggle-sticky = Toggle sticky
editing-underline-text = Underline text
editing-unordered-list = Unordered list
editing-warning-cloze-deletions-will-not-work = Warning, cloze deletions will not work until you switch the type at the top to Cloze.

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-bold-text-ctrlandb = Bold text (Ctrl+B)
editing-italic-text-ctrlandi = Italic text (Ctrl+I)
editing-underline-text-ctrlandu = Underline text (Ctrl+U)
editing-subscript-ctrland = Subscript (Ctrl+=)
editing-superscript-ctrlandand = Superscript (Ctrl++)
editing-remove-formatting-ctrlandr = Remove formatting (Ctrl+R)
editing-record-audio-f5 = Record audio (F5)
editing-attach-picturesaudiovideo-f3 = Attach pictures/audio/video (F3)
editing-cloze-deletion-ctrlandshiftandc = Cloze deletion (Ctrl+Shift+C)
editing-change-colour-f8 = Change colour (F8)
editing-set-foreground-colour-f7 = Set foreground colour (F7)
editing-customize-card-templates-ctrlandl = Customize Card Templates (Ctrl+L)
editing-set-foreground-color = Set foreground color
