editing-actual-size = Toggle actual size
editing-add-media = Add Media
editing-align-left = Align left
editing-align-right = Align right
editing-an-error-occurred-while-opening = An error occurred while opening { $val }
editing-attach-picturesaudiovideo = Attach pictures/audio/video
editing-bold-text = Bold text
editing-cards = Cards
editing-center = Center
editing-change-color = Change color
editing-cloze-deletion = Cloze deletion (new card)
editing-cloze-deletion-repeat = Cloze deletion (same card)
editing-copy-image = Copy image
editing-couldnt-record-audio-have-you-installed = Couldn't record audio. Have you installed 'lame'?
editing-customize-card-templates = Customize Card Templates
editing-customize-fields = Customize Fields
editing-cut = Cut
editing-double-click-image = double-click image
editing-double-click-to-expand = double-click to expand
editing-double-click-to-collapse = double-click to collapse
editing-edit-current = Edit Current
editing-edit-html = Edit HTML
editing-fields = Fields
editing-float-left = Float left
editing-float-right = Float right
editing-float-none = No float
editing-indent = Increase indent
editing-italic-text = Italic text
editing-jump-to-tags-with-ctrlandshiftandt = Jump to tags with Ctrl+Shift+T
editing-justify = Justify
editing-latex = LaTeX
editing-latex-equation = LaTeX equation
editing-latex-math-env = LaTeX math env.
editing-mathjax-block = MathJax block
editing-mathjax-chemistry = MathJax chemistry
editing-mathjax-inline = MathJax inline
editing-mathjax-placeholder = Press { $accept } to accept, { $newline } for new line.
editing-media = Media
editing-open-image = Open image
editing-show-in-folder = Show in folder
editing-ordered-list = Ordered list
editing-outdent = Decrease indent
editing-paste = Paste
editing-record-audio = Record audio
editing-remove-formatting = Remove formatting
editing-restore-original-size = Restore original size
editing-select-remove-formatting = Select formatting to remove
editing-show-duplicates = Show Duplicates
editing-subscript = Subscript
editing-superscript = Superscript
editing-tags = Tags
editing-tags-add = Add tag
editing-tags-copy = Copy tags
editing-tags-remove = Remove tags
editing-tags-select-all = Select all tags
editing-text-color = Text color
editing-text-highlight-color = Text highlight color
editing-to-make-a-cloze-deletion-on = To make a cloze deletion on an existing note, you need to change it to a cloze type first, via 'Notes>Change Note Type'
editing-toggle-html-editor = Toggle HTML Editor
editing-toggle-visual-editor = Toggle Visual Editor
editing-toggle-sticky = Toggle sticky
editing-expand = Expand
editing-collapse = Collapse
editing-expand-field = Expand field
editing-collapse-field = Collapse field
editing-underline-text = Underline text
editing-unordered-list = Unordered list
editing-warning-cloze-deletions-will-not-work = Warning, cloze deletions will not work until you switch the type at the top to Cloze.
editing-mathjax-preview = MathJax Preview
editing-shrink-images = Shrink Images
editing-close-html-tags = Auto-close HTML tags
editing-tags-show-full = Show full tags
editing-tags-show-compact = Show compact tags
editing-from-clipboard = From Clipboard
editing-alignment = Alignment
editing-equations = Equations
editing-no-image-found-on-clipboard = No image found on clipboard.
editing-image-occlusion-mode = Image Occlusion Mode
editing-image-occlusion-zoom-out = Zoom Out
editing-image-occlusion-zoom-in = Zoom In
editing-image-occlusion-zoom-reset = Reset Zoom
editing-image-occlusion-toggle-translucent = Toggle Translucency
editing-image-occlusion-delete = Delete
editing-image-occlusion-duplicate = Duplicate
editing-image-occlusion-group = Group Selection
editing-image-occlusion-ungroup = Ungroup Selection
editing-image-occlusion-select-all = Select All
editing-image-occlusion-alignment = Alignment
editing-image-occlusion-align-left = Align Left
editing-image-occlusion-align-h-center = Align Horizontal Centers
editing-image-occlusion-align-right = Align Right
editing-image-occlusion-align-top = Align Top
editing-image-occlusion-align-v-center = Align Vertical Centers
editing-image-occlusion-align-bottom = Align Bottom
editing-image-occlusion-select-tool = Select
editing-image-occlusion-zoom-tool = Zoom
editing-image-occlusion-rectangle-tool = Rectangle
editing-image-occlusion-ellipse-tool = Ellipse
editing-image-occlusion-polygon-tool = Polygon
editing-image-occlusion-text-tool = Text
editing-image-occlusion-fill-tool = Fill with colour
editing-image-occlusion-toggle-mask-editor = Toggle Mask Editor
editing-image-occlusion-reset = Reset Image Occlusion
editing-image-occlusion-confirm-reset = Are you sure you want to reset this image occlusion?
 
## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML Editor
