fields-add-field = Add Field
fields-delete-field-from = Delete field from { $val }?
fields-editing-font = Editing Font
fields-field = Field:
fields-field-name = Field name:
fields-fields-for = Fields for { $val }
fields-font = Font:
fields-new-position-1 = New position (1...{ $val }):
fields-notes-require-at-least-one-field = Notes require at least one field.
fields-remember-last-input-when-adding = Remember last input when adding
fields-reverse-text-direction-rtl = Reverse text direction (RTL)
fields-size = Size:
fields-sort-by-this-field-in-the = Sort by this field in the browser
fields-that-field-name-is-already-used = That field name is already used.
fields-name-first-letter-not-valid = The field name should not start with #, ^ or /.
fields-name-invalid-letter = The field name should not contain :, ", { "{" } or { "}" }.
