launcher-title = Anki Launcher
launcher-press-enter-to-install = Press the Enter/Return key on your keyboard to install or update Anki.
launcher-press-enter-to-start = Press enter to start Anki.
launcher-anki-will-start-shortly = Anki will start shortly.
launcher-you-can-close-this-window = You can close this window.
launcher-updating-anki = Updating Anki...
launcher-latest-anki = Install Latest Anki (default)
launcher-choose-a-version = Choose a version
launcher-sync-project-changes = Sync project changes
launcher-keep-existing-version = Keep existing version ({ $current })
launcher-revert-to-previous = Revert to previous version ({ $prev })
launcher-allow-betas = Allow betas: { $state }
launcher-on = on
launcher-off = off
launcher-cache-downloads = Cache downloads: { $state }
launcher-download-mirror = Download mirror: { $state }
launcher-uninstall = Uninstall Anki
launcher-invalid-input = Invalid input. Please try again.
launcher-latest-releases = Latest releases: { $releases }
launcher-enter-the-version-you-want = Enter the version you want to install:
launcher-versions-before-cant-be-installed = Versions before 2.1.50 can't be installed.
launcher-invalid-version = Invalid version.
launcher-unable-to-check-for-versions = Unable to check for Anki versions. Please check your internet connection.
launcher-checking-for-updates = Checking for updates...
launcher-uninstall-confirm = Uninstall Anki's program files
launcher-uninstall-cancelled = Uninstall cancelled.
launcher-program-files-removed = Program files removed.
launcher-remove-all-profiles-confirm = Remove all profiles/cards?
launcher-user-data-removed = User data removed.
launcher-download-mirror-options = Download mirror options:
launcher-mirror-no-mirror = No mirror
launcher-mirror-china = China
launcher-mirror-disabled = Mirror disabled.
launcher-mirror-china-enabled = China mirror enabled.
launcher-beta-releases-enabled = Beta releases enabled.
launcher-beta-releases-disabled = Beta releases disabled.
launcher-download-caching-enabled = Download caching enabled.
launcher-download-caching-disabled = Download caching disabled and cache cleared.

# TODO: dedup
launcher-language = Language
launcher-latest-anki-version = Install Latest Anki ({ $version })
launcher-allow-betas-toggle = Allow betas
launcher-use-mirror =  Download mirror
launcher-download-caching = Download caching
launcher-advanced = Advanced
launcher-output = Output
launcher-syncing = Syncing
launcher-failed-to-sync = Failed to sync!
launcher-loading = Loading
launcher-loading-versions = Loading versions
lauuncher-failed-to-load-versions = Failed to load versions!
launcher-error-details = Error details
launcher-will-close-in = Launcher will close in { $count }
launcher-anki-is-warming-up = Anki is preparing to run
launcher-this-may-take = This may take a few minutes. Please wait
launcher-os-unsupported = Unsupported OS
launcher-unknown-error = Unknown error
launcher-remove-profiles-warning = This will irreversibly delete all of your Anki flashcards and media!
launcher-uninstall-confirm-and-remove-profiles = Uninstall Anki's program files and remove profiles
launcher-uninstalling = Uninstalling
launcher-failed-to-uninstall = Failed to uninstall!
launcher-uninstall-complete = Anki has been uninstalled
launcher-uninstall-action-needed = Action needed to finish uninstalling!
launcher-uninstall-unix = To finish uninstalling, run '{ $path }'
launcher-uninstall-mac = Please manually drag Anki.app to the trash to complete uninstall.
launcher-uninstall-win-not-found = Windows uninstaller not found 
launcher-uninstall-win-not-found-extra = You may need to uninstall via Windows Settings > Apps.
launcher-uninstall-win-failed = Failed to launch uninstaller
launcher-uninstall-win-failed-extra = You can manually run: { $path }
