profiles-anki-could-not-read-your-profile = Anki could not read your profile data. Window sizes and your sync login details have been forgotten.
profiles-anki-could-not-rename-your-profile = Anki could not rename your profile because it could not rename the profile folder on disk. Please ensure you have permission to write to Documents/Anki and no other programs are accessing your profile folders, then try again.
profiles-folder-already-exists = Folder already exists.
profiles-open = Open
profiles-open-backup = Open Backup...
profiles-please-remove-the-folder-and = Please remove the folder { $val } and try again.
profiles-profile-corrupt = Profile Corrupt
profiles-profiles = Profiles
profiles-quit = Quit
profiles-user-1 = User 1
profiles-confirm-lang-choice = Are you sure you wish to display Anki's interface in { $lang }?
profiles-could-not-create-data-folder = Anki could not create its data folder. Please see the File Locations section of the manual, and ensure that location is not read-only.
profiles-prefs-corrupt-title = Preferences Corrupt
profiles-prefs-file-is-corrupt = Anki's prefs21.db file was corrupt and has been recreated. If you were using multiple profiles, please add them back using the same names to recover your cards.
profiles-profile-does-not-exist = Requested profile does not exist.
profiles-creating-backup = Creating Backup...
profiles-backup-created = Backup created.
profiles-backup-creation-failed = Backup creation failed: { $reason }
profiles-backup-unchanged = No changes since latest backup.
