actions-add = Ավելացնել
actions-blue-flag = Կապույտ դրոշ
actions-cancel = Չեղարկել
actions-choose = Ընտրել
actions-close = Փակել
actions-copy = Պատճենել
actions-custom-study = Լրացուցիչ ուսուցում
actions-decks = Կապուկներ
actions-delete = Ջնջել
actions-export = Արտահանել
actions-filter = Զտիչ
actions-green-flag = Կանաչ դրոշ
actions-help = Օգնություն
actions-import = Ներմուծել
actions-manage = Կարգավորել...
actions-name = Անվանում՝
actions-new = Նոր
actions-new-name = Նոր անվանում՝
actions-options = Ընտրանքներ
actions-options-for = Ընտրանքներ { $val }-ի համար
actions-orange-flag = Նարնջագույն դրոշ
actions-preview = Նախատեսք
actions-rebuild = Վերակառուցել
actions-red-flag = Կարմիր դրոշ
actions-rename = Վերանվանել
actions-rename-deck = Վերանվանել կապուկը
actions-replay-audio = Կրկին նվագարկել ձայնանյութը
actions-reposition = Վերատեղադրել
actions-save = Պահել
actions-search = Որոնում
actions-shortcut-key = Ստեղանաշարի ստեղնը՝ { $val }
actions-suspend-card = Հեռացնել քարտը
actions-processing = Մշակում...
