adding-add-shortcut-ctrlandenter = Ավելացնել (կարճատ՝ ctrl+enter)
adding-added = Ավելացվել է
adding-close-and-lose-current-input = Փակել և կորցնե՞լ ընթացիկ ներածումը:
adding-edit = Խմբագրել "{ $val }"
adding-history = Պատմություն
adding-note-deleted = (Գրառումը ջնջված է)
adding-shortcut = Կարճատ՝ { $val }
adding-the-first-field-is-empty = Առաջին դաշտը դատարկ է:
adding-you-have-a-cloze-deletion-note = Գրառման տեսակը՝ բացթողումների լրացում է ընտրված , բայց Դուք ոչ մի բացթողում չեք լրացրել: Շարունակե՞լ:
