editing-add-media = Ավելացնել մեդիա
editing-an-error-occurred-while-opening = Սխալ տեղի ունեցավ { $val } բացելիս
editing-attach-picturesaudiovideo-f3 = Կցեք պատկերներ/ձայնանիշքեր/տեսանյութեր (F3)
editing-bold-text-ctrlandb = Թավ գրվածք (Ctrl+B)
editing-cards = Քարտեր
editing-change-colour-f8 = Փոխել գույնը (F8)
editing-cloze-deletion-ctrlandshiftandc = Բացթողումների ջնջում (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = Չհաջողվեց գրել ձայնը: Դուք տեղադրե՞լ եք «lame»-ը:
editing-customize-card-templates-ctrlandl = Կարգավորել քարտերի կաղապարները (Ctrl+L)
editing-customize-fields = Կարգավորել դաշտերը
editing-cut = Կտրել
editing-edit-current = Խմբագրել ընթացիկը
editing-edit-html = Խմբագրել HTML
editing-fields = Դաշտեր
editing-html-editor = HTML խմբագրիչ
editing-italic-text-ctrlandi = Շեղագիր գրվածք (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = Անցնել պիտակներին Ctrl+Shift+T
editing-latex-equation = LaTeX հավասարում
editing-latex-math-env = LaTeX մաթ. միջավայր
editing-mathjax-block = MathJax բլոկային
editing-mathjax-chemistry = MathJax քիմիական
editing-mathjax-inline = MathJax ներտողային
editing-media = Մեդիա
editing-paste = Փակցնել
editing-record-audio-f5 = Ձայնագրել ձայնը (F5)
editing-remove-formatting-ctrlandr = Հեռացնել ձևաչափումը (Ctrl+R)
editing-set-foreground-colour-f7 = Ընտրել առջևքի գույնը (F7)
editing-show-duplicates = Ցուցադրել կրկնօրինակները
editing-subscript-ctrland = Վարգիր (Ctrl+=)
editing-superscript-ctrlandand = Վերգիր (Ctrl++)
editing-tags = Պիտակներ
editing-to-make-a-cloze-deletion-on = Առկա գրառման բացթողումների լրացումը ավելացնելու համար պետք է նրա տեսակը փոխել «բացթողումների», ընտրելով Խմբագրել>Փոխել գրառման տեսակը:
editing-underline-text-ctrlandu = Ընդգծված գրառում (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = Զգուշացում. Բացթողումների լրացումը չի աշխատի մինչև վերևում չփոխեք տեսակը «Բացթողումների»-ի:
