preferences-automatically-sync-on-profile-openclose = Ինքնաշխատորեն համաժամեցնել հատկագիրը բացելիս/փակելիս
preferences-backups = Պահուստներ
preferences-backups2 = պահուստ
preferences-backupsanki-will-create-a-backup-of = <b>Պահուստներ</b><br>Յուրաքանչյուր անգամ Anki-ն փակելիս կամ համաժամեցնելիս ծրագիրը կստեղծի հավաքածուի պահուստ:
preferences-basic = Հիմնական
preferences-change-deck-depending-on-note-type = Փոխել կապուկը կախված գրառման տեսակից
preferences-changes-will-take-effect-when-you = Փոփոխությունները կկատարվեն Anki-ն վերամեկնարկելուց հետո:
preferences-hardware-acceleration-faster-may-cause-display = Սարքային արագացում (ավելի արագ է, հնարավոր են ցուցադրման խնդիրներ)
preferences-hours-past-midnight = ժամ հետո
preferences-interface-language = Միջերեսի լեզուն՝
preferences-keep = Պահել մինչև
preferences-learn-ahead-limit = Արտահերթ սովորելու սահմանափակում
preferences-mins = րոպե
preferences-network = Համաժամեցում
preferences-next-day-starts-at = Հաջորդ օրը սկսում է կեսգիշերից
preferences-night-mode = Գիշերային գործելաձև
preferences-note-media-is-not-backed-up = Նկատառում՝ Մեդիան պահուստավորված չէ: Ստեղծեք Anki-ի պանակի պարբերական պահուստավորումը ապահովության համար:
preferences-on-next-sync-force-changes-in = Հաջորդ համաժամեցման ժամանակ վերագրել մեկ ուղղությունով
preferences-paste-clipboard-images-as-png = Փակցնել սեղմատախտակի պատկերները իբրև PNG
preferences-please-restart-anki-to-complete-language = Վերագործարկեք Anki-ն լեզվի փոփոխությունը ուժի մեջ մտնելու համար:
preferences-preferences = Նախընտրություններ
preferences-scheduling = Վերահերթագրել
preferences-show-learning-cards-with-larger-steps = Ցուցադրել ավելի մեծ քայլերով ուսուցանվող քարտերը կրկնություններից առաջ
preferences-show-next-review-time-above-answer = Ցուցադրել հաջորդ կրկնության ժամանակը պատասխանի կոճակների վերևում
preferences-show-remaining-card-count-during-review = Կրկնելիս ցուցադրել մնացած քարտերի քանակը
preferences-some-settings-will-take-effect-after = Որոշ կարգավորումներ ուժի մեջ կմտնեն Anki-ն վերագործարկելուց հետո:
preferences-synchronisation = <b>Համաժամեցում</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Համաժամեցում</b><br> Այժմ անջատված է. միացնելու համար կտտացրեք գլխավոր պատուհանի համաժամեցման կոճակի վրա:
preferences-synchronize-audio-and-images-too = Ձայնանյութերը ու պատկերները նույնպես համաժամեցնել
preferences-this-will-reset-any-cards-in = Սա կվերակայի ուսուցանվող բոլոր քարտերը, կմաքրի զտված կապուկները և կփոխի հերթագրիչի տարբերակը: Շարունակե՞լ:
preferences-timebox-time-limit = Ժամանակի սահմանափակում
preferences-user-interface-size = Օգտվողի միջերեսի չափսը
preferences-when-adding-default-to-current-deck = Սկզբնադրորեն ավելացնել ընթացիկ կապուկի մեջ
