#!/bin/bash

set -e

test -e WORKSPACE || (
    echo "Run from project root"
    exit 1
)

rm -rf bazel-dist
bazel build -c opt --@io_bazel_rules_rust//worker:use_worker=False dist
tar xvf bazel-bin/dist.tar
