#!/bin/bash
#
# Start Anki with the data folder pointed at bazel-bin,
# which is useful when developing TS pages on a Mac.
#
# The pages can be accessed by, eg surfing to
# http://localhost:40000/_anki/pages/deckconfig.html

ANKI_DATA_FOLDER=$(pwd)/bazel-bin/qt/aqt/data \
  QTWEBENGINE_REMOTE_DEBUGGING=8080 \
  ANKI_API_PORT=40000 ANKIDEV=1 ./run
