adding-add-shortcut-ctrlandenter = Pievienot (īsinājumtaustiņi: ctrl+enter)
adding-added = Pievienota
adding-discard-current-input = Atmest pašreizējo ievadi?
adding-keep-editing = Turpināt labošanu
adding-edit = Labot „{ $val }”
adding-history = Vēsture
adding-note-deleted = (Piezīme izdzēsta)
adding-shortcut = Īsinājumtaustiņi: { $val }
adding-the-first-field-is-empty = Pirmais lauks ir tukšs.
adding-you-have-a-cloze-deletion-note = Tev ir atstarpju aizpildīšanas (cloze) piezīmju veids, bet neesi izveidojis nevienu atstarpi. Vai turpināt?
adding-cloze-outside-cloze-notetype = Atstarpju aizpildīšana (cloze) darbojas tikai ar atstarpju piezīmju tipiem.
adding-cloze-outside-cloze-field = Atstarpju aizpildīšanu (cloze) var izmantot tikai laukos ar „cloze:” filtru. Parasti tas ir pirmais lauks.
