studying-again = Vēlreiz
studying-card-suspended = Kartīte atlikta.
studying-card-was-a-leech = Kartīte bija izsūcoša.
studying-continue = Turpināt
studying-delete-note = Izdzēst piezīmi
studying-easy = Viegli
studying-edit = Labot
studying-finish = Pabeigt
studying-good = Labi
studying-hard = Grūti
studying-it-has-been-suspended = Tā tika atlikta.
studying-more = Vairāk
studying-note-suspended = Piezīme atlikta.
studying-suspend = Atlikt
studying-suspend-note = Atlikt piezīmi
studying-question-time-elapsed = Jautājuma laiks beidzies
studying-answer-time-elapsed = Atbildes laiks beidzies
