editing-actual-size = Til/fra faktisk størrelse
editing-add-media = Tilføj medie
editing-align-left = Venstrejusteret
editing-align-right = Højrejusteret
editing-an-error-occurred-while-opening = Der opstod en fejl under åbning af { $val }
editing-attach-picturesaudiovideo = Vedhæft billeder/lyd/video
editing-bold-text = Fed skrift
editing-cards = Kort
editing-center = Center
editing-change-color = Skift farve
editing-cloze-deletion = Cloze-fjernelse (nyt kort)
editing-cloze-deletion-repeat = Cloze-fjernelse (samme kort)
editing-couldnt-record-audio-have-you-installed = Kan ikke optage lyd. Har du installeret 'lame'?
editing-customize-card-templates = Brugertilpassede kort-skabeloner
editing-customize-fields = Tilpas felter
editing-cut = Klip
editing-double-click-image = Dobbelklik billede
editing-double-click-to-expand = Dobbelklik til at forstørre
editing-double-click-to-collapse = Dobbelklik til at minimere
editing-edit-current = Rediger nuværende
editing-edit-html = Rediger HTML
editing-fields = Felter
editing-float-left = Flyd til venstre
editing-float-right = Flyd til højre
editing-float-none = Ingen flyd
editing-indent = Øg indrykning
editing-italic-text = Kursiv tekst
editing-jump-to-tags-with-ctrlandshiftandt = Spring til mærker med Ctrl+Skift+T
editing-justify = Lige margener
editing-latex = LaTeX
editing-latex-equation = LaTeX-ligning
editing-latex-math-env = Matematik-miljø for LaTeX
editing-mathjax-block = MathJax blokke
editing-mathjax-chemistry = MathJax kemi
editing-mathjax-inline = MathJax inline
editing-mathjax-placeholder = Tryk { $accept } for at acceptere, { $newline } for en ny linje.
editing-media = Medie
editing-ordered-list = Ordnet liste
editing-outdent = Reducer indrykning
editing-paste = Indsæt
editing-record-audio = Indspil lyd
editing-remove-formatting = Fjern formattering
editing-restore-original-size = Gendan til oprindelig størrelse
editing-select-remove-formatting = Vælg formattering som skal fjernes
editing-show-duplicates = Vis dubletter
editing-subscript = Subscript
editing-superscript = Superscript
editing-tags = Mærker
editing-tags-add = Tilføj tag
editing-tags-copy = Kopiér tag
editing-tags-remove = Fjern tag
editing-tags-select-all = Vælg alle tags
editing-text-color = Tekstfarve
editing-text-highlight-color = Farve på highlighted text
editing-to-make-a-cloze-deletion-on = For at lave en cloze-sletning på en eksisterende note, så skal du først ændre den til en cloze-type, via Redigér>Skift notetype.
editing-toggle-html-editor = Til/fra HTML editor
editing-toggle-visual-editor = Til/fra visual editor
editing-toggle-sticky = Til/fra klistret
editing-expand-field = Expandér felt
editing-collapse-field = Kollabér felt
editing-underline-text = Understreget tekst
editing-unordered-list = Ikke-numreret liste
editing-warning-cloze-deletions-will-not-work = Advarsel, cloze-sletninger vil ikke fungere før du skifter typen i toppen til Cloze.
editing-mathjax-preview = MathJax forhåndsvisning
editing-shrink-images = Formindsk billeder
editing-close-html-tags = Luk automatisk HTML-tags

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML Editor
