fields-add-field = Tilføj felt
fields-delete-field-from = Slet felt fra { $val }?
fields-editing-font = Redigerende font
fields-field = Felt:
fields-field-name = Feltnavn:
fields-description = Beskrivelse
fields-description-placeholder = Tekst at vise inde i feltet når det er tomt
fields-fields-for = Felter for { $val }
fields-font = Skrift:
fields-new-position-1 = Ny position (1...{ $val }):
fields-notes-require-at-least-one-field = Noter kræver mindst ét felt.
fields-reverse-text-direction-rtl = Modsat tekstretning (RTL)
fields-collapse-by-default = Kollabér som standard
fields-html-by-default = Brug HTML-editor som standard
fields-size = Størrelse:
fields-sort-by-this-field-in-the = Sorter efter dette felt i browseren
fields-that-field-name-is-already-used = Det feltnavn er allerede brugt.
fields-name-first-letter-not-valid = Feltnavnet må ikke begynde med #, ^ or /.
fields-name-invalid-letter = Feltnavnet må ikkke indholde :, ", { "{" } or { "}" }.
