qt-accel-about = &За програмата...
qt-accel-check-media = Проверка на медийните файлове
qt-accel-edit = &Редактиране
qt-accel-exit = &Изход
qt-accel-export = &Експортиране...
qt-accel-file = &Файл
qt-accel-find = &Търсене
qt-accel-find-and-replace = Търсене и заместване
qt-accel-find-duplicates = &Търсене на дубликати
qt-accel-go = &Действия
qt-accel-guide = &Ръководство...
qt-accel-help = &Помощ
qt-accel-import = &Импортиране...
qt-accel-invert-selection = &Обръщане на избора
qt-accel-next-card = &Следваща карта
qt-accel-note = Бележка
qt-accel-open-addons-folder = &Отваряне на папката с добавки
qt-accel-preferences = &Настройки
qt-accel-previous-card = &Предишна карта
qt-accel-reschedule = Промяна на &разписанието
qt-accel-select-all = Избери всички
qt-accel-select-notes = Избор на бележки
qt-accel-support-anki = Подпомагане на Anki
qt-accel-tools = &Инструменти
qt-accel-undo = &Отмяна
