custom-study-must-rename-deck = ആദ്യം നിലവിലുള്ള ഇഷ്ടാനുസൃത പഠന ഡെക്കിന്റെ പേര് മാറ്റുക.
custom-study-all-cards-in-random-order-dont = എല്ലാ കാർഡുകളും ക്രമരഹിതമായി (വീണ്ടും ഷെഡ്യൂൾ ചെയ്യരുത്)
custom-study-all-review-cards-in-random-order = എല്ലാ അവലോകന കാർഡുകളും ക്രമരഹിതമായി
custom-study-cards = കാർഡുകൾ
custom-study-cards-from-the-deck = ഡെക്കിൽ നിന്നുമുള്ള കാർഡുകൾ
custom-study-choose-tags = ടാഗുകൾ തിരഞ്ഞെടുക്കുക
custom-study-custom-study-session = ഇഛാനുസൃതമായ പഠന സെഷൻ
custom-study-due-cards-only = ഡ്യൂ ആയ കാർഡുകൾ മാത്രം
custom-study-increase-todays-new-card-limit = ഇന്നത്തെ പുതിയ കാർഡ് പരിധി വർദ്ധിപ്പിക്കുക
custom-study-increase-todays-new-card-limit-by = ഇന്നത്തെ പുതിയ കാർഡ് പരിധി വർദ്ധിപ്പിക്കുക
custom-study-increase-todays-review-card-limit = ഇന്നത്തെ അവലോകന കാർഡ് പരിധി വർദ്ധിപ്പിക്കുക
custom-study-increase-todays-review-limit-by = ഇന്നത്തെ അവലോകന പരിധി വർദ്ധിപ്പിക്കുക
custom-study-new-cards-in-deck-over-today = ഇന്നത്തെ പരിധിക്കു പുറത്തുള്ള പുതിയ കാർഡുകൾ: { $val }
custom-study-new-cards-only = പുതിയ കാർഡുകൾ മാത്രം
custom-study-no-cards-matched-the-criteria-you = നിങ്ങൾ നൽകിയ മാനദണ്ഡങ്ങളുമായി കാർഡുകളൊന്നും പൊരുത്തപ്പെടുന്നില്ല.
custom-study-ok = ശരി
custom-study-preview-new-cards = പുതിയ കാർഡുകൾ പ്രിവ്യൂ ചെയ്യുക
custom-study-preview-new-cards-added-in-the = അവസാനം ചേർത്ത പുതിയ കാർഡുകൾ പ്രിവ്യൂ ചെയ്യുക
custom-study-require-one-or-more-of-these = ഈ ടാഗുകളിൽ ഒന്നോ അതിലധികമോ ആവശ്യമാണ്:
custom-study-review-ahead = നേരത്തെ അവലോകനം നടത്തുക
custom-study-review-ahead-by = മുന്നോട്ട് അവലോകനം ചെയ്യുക
custom-study-review-cards-forgotten-in-last = അവലോകന കാർഡുകൾ അവസാനം മറന്നു
custom-study-review-forgotten-cards = മറന്ന കാർഡുകൾ അവലോകനം ചെയ്യുക
custom-study-reviews-due-in-deck-over-today = ഇന്നത്തെ പരിധിക്ക് മുകളിലുള്ള അവലോകനങ്ങൾ: { $val }
custom-study-select = തിരഞ്ഞെടുക്കുക
custom-study-select-tags-to-exclude = ഒഴിവാക്കേണ്ട ടാഗുകൾ തിരഞ്ഞെടുക്കുക:
custom-study-selective-study = സെലക്ടീവ് പഠനം
custom-study-study-by-card-state-or-tag = കാർഡിന്റെ അവസ്ഥയോ ടാഗോ അടിസ്ഥാനമാക്കി പഠിക്കുക
