decks-add-new-deck-ctrlandn = പുതിയ ഡെക്ക് ചേർക്കുക
decks-build = നിർമിക്കുക
decks-cards-selected-by = കാർഡുകൾ തിരഞ്ഞെടുത്തതിന്റെ അടിസ്ഥാനം
decks-create-deck = ഡെക്ക് സൃഷ്ടിക്കുക
decks-custom-steps-in-minutes = ഇസ്താനുസൃതമായ ഘട്ടങ്ങൾ (മിനിറ്റുകൾക്കുള്ളിൽ)
decks-deck = ഡെക്ക്
decks-decreasing-intervals = താഴ്ന്ന ഇടവേളകളിൽ
decks-delete-deck = ഡെക്ക് ഇല്ലാതാക്കുക
decks-enable-second-filter = രണ്ടാമത്തെ ഫിൽറ്റർ പ്രാപ്തമാക്കുക
decks-filter = ഫിൽറ്റർ:
decks-filter-2 = ഫിൽറ്റർ 2
decks-get-shared = പങ്കിട്ടതു ലഭ്യമാക്കുക
decks-import-file = ഫയൽ ഇറക്കുമതി ചെയ്യുക
decks-increasing-intervals = ഉയരുന്ന ഇടവേളകൾ
decks-latest-added-first = പുതുതായി ചേർത്തത് ആദ്യം
decks-limit-to = ഒതുക്കുക
decks-minutes = മിനിറ്റുകള്‍
decks-most-lapses = ഏറ്റവും കൂടുതൽ വീഴ്ചകൾ
decks-name-for-deck = ഡെക്കിനു വേണ്ടിയുള്ള പേര്:
decks-new-deck-name = ഡെക്കിന്റെ പുതിയ പേര്:
decks-no-deck = [ഡെക്ക് ഇല്ല]
decks-oldest-seen-first = ഏറ്റവും പഴയത് ആദ്യം കാണുക
decks-order-added = ക്രമം ചേർത്തു
decks-order-due = ഓർഡർ നൽകേണ്ടതാണ്
decks-please-select-something = ദയവായി എന്തെങ്കിലും തിരഞ്ഞെടുക്കുക.
decks-random = ക്രമരഹിതം
decks-relative-overdueness = ആപേക്ഷിക അമിതത്വം
decks-repeat-failed-cards-after = പരാജയപ്പെട്ട കാർഡുകൾ പിന്നീട് ആവർത്തിക്കുക
decks-reschedule-cards-based-on-my-answers = ഈ ഡെക്കിലെ എന്റെ ഉത്തരങ്ങളെ അടിസ്ഥാനമാക്കി കാർഡുകൾ വീണ്ടും ഷെഡ്യൂൾ ചെയ്യുക
decks-study = പഠനം
decks-study-deck = ഡെക്ക് പഠിക്കുക
decks-filtered-deck-search-empty = നൽകിയ തിരയലുമായി കാർഡുകളൊന്നും പൊരുത്തപ്പെടുന്നില്ല. ചില കാർഡുകൾ മറ്റൊരു ഫിൽട്ടർ ചെയ്ത ഡെക്കിലുള്ളതിനാലോ താൽക്കാലികമായി നിർത്തിവച്ചിരിക്കുന്നതിനാലോ ഒഴിവാക്കപ്പെട്ടിരിക്കാം.
decks-unmovable-cards = ഒഴിവാക്കിയ ഏതെങ്കിലും കാർഡുകൾ കാണിക്കുക
# The count of cards waiting to be reviewed
decks-review-header = അവസാന തീയതി
decks-learn-header = പഠിക്കുക
