editing-add-media = മീഡിയ ചേർക്കുക
editing-align-left = ഇടത്തേക്ക് വിന്യസിക്കുക
editing-align-right = വലത്തേക്ക് വിന്യസിക്കുക
editing-an-error-occurred-while-opening = { $val } തുറക്കുമ്പോൾ ഒരു പിശക് സംഭവിച്ചു
editing-attach-picturesaudiovideo = ചിത്രങ്ങൾ / ഓഡിയോ / വീഡിയോ അറ്റാച്ചുചെയ്യുക
editing-bold-text = ബോൾഡ് ലിഖിതം
editing-cards = കാർഡുകൾ
editing-center = മധ്യഭാഗം
editing-change-color = നിറം മാറ്റുക
editing-cloze-deletion = ക്ലോസ് ഇല്ലാതാക്കൽ
editing-couldnt-record-audio-have-you-installed = ഓഡിയോ റെക്കോർഡുചെയ്യാനായില്ല. നിങ്ങൾ 'lame' ഇൻസ്റ്റാൾ ചെയ്തിട്ടുണ്ടോ?
editing-customize-card-templates = കാർഡ് ടെംപ്ലേറ്റുകൾ ഇച്ഛാനുസൃതമാക്കുക
editing-customize-fields = മണ്ഡലങ്ങൾ ഇഷ്‌ടാനുസൃതമാക്കുക
editing-cut = കത്രിക്കുക
editing-edit-current = നിലവിലുള്ളത് ചിട്ടപ്പെടുത്തുക
editing-edit-html = HTML എഡിറ്റുചെയ്യുക
editing-fields = മണ്ഡലങ്ങള്‍
editing-html-editor = HTML എഡിറ്റർ
editing-indent = ഇൻഡന്റ് വർദ്ധിപ്പിക്കുക
editing-italic-text = ഇറ്റാലിക് വാചകം
editing-jump-to-tags-with-ctrlandshiftandt = Ctrl + Shift + T ഉപയോഗിച്ച് ടാഗുകളിലേക്ക് പോകുക
editing-justify = സമീകരിക്കുക
editing-latex = LaTeX
editing-latex-equation = LaTeX സമവാക്യം
editing-latex-math-env = LaTeX മാത്ത് എൻവ്.
editing-mathjax-block = MathJax ബ്ലോക്ക്
editing-mathjax-chemistry = MathJax രസതന്ത്രം
editing-mathjax-inline = MathJax ഇൻലൈൻ
editing-media = മീഡിയ
editing-ordered-list = ക്രമപ്രകാരമുള്ള പട്ടിക
editing-outdent = ഇൻഡന്റ് കുറയ്‌ക്കുക
editing-paste = പതിക്കുക
editing-record-audio = ഓഡിയോ റെക്കോർഡു ചെയ്യുക
editing-remove-formatting = ഫോർമാറ്റിംഗ് നീക്കം ചെയ്യുക
editing-set-foreground-color = മുൻഭാഗത്തിന്റെ നിറം സജ്ജമാക്കുക
editing-show-duplicates = തനിപ്പകർപ്പുകൾ കാണിക്കുക
editing-subscript = സബ്സ്ക്രിപ്റ്റ്
editing-superscript = സൂപ്പര്‍സ്ക്രിപ്റ്റ്
editing-tags = ടാഗുകൾ
editing-to-make-a-cloze-deletion-on = നിലവിലുള്ള ഒരു കുറിപ്പിൽ ഒരു ക്ലോസ് ഇല്ലാതാക്കാൻ, നിങ്ങൾ ആദ്യം 'കുറിപ്പുകൾ> കുറിപ്പ് തരം മാറ്റുക' വഴി ഒരു ക്ലോസ് തരത്തിലേക്ക് മാറ്റേണ്ടതുണ്ട്.
editing-underline-text = വാചകം അടിവരയിടുക
editing-unordered-list = ക്രമീകരിക്കാത്ത പട്ടിക
editing-warning-cloze-deletions-will-not-work = മുന്നറിയിപ്പ്, മുകളിലുള്ള തരം ക്ലോസിലേക്ക് മാറ്റുന്നതുവരെ ക്ലോസ് ഇല്ലാതാക്കലുകൾ പ്രവർത്തിക്കില്ല.

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-bold-text-ctrlandb = ബോൾഡ് വാചകം (Ctrl+B)
editing-italic-text-ctrlandi = ഇറ്റാലിക് വാചകം (Ctrl+I)
editing-underline-text-ctrlandu = വാചകം അടിവരയിടുക (Ctrl+U)
editing-subscript-ctrland = സബ്സ്ക്രിപ്റ്റ് (Ctrl+=)
editing-superscript-ctrlandand = സൂപ്പർസ്ക്രിപ്റ്റ് (Ctrl++)
editing-remove-formatting-ctrlandr = ഫോർമാറ്റിംഗ് നീക്കംചെയ്യുക (Ctrl+R)
editing-record-audio-f5 = ഓഡിയോ റെക്കോർഡു ചെയ്യുക (F5)
editing-attach-picturesaudiovideo-f3 = ചിത്രങ്ങൾ / ഓഡിയോ / വീഡിയോ അറ്റാച്ചുചെയ്യുക (F3)
editing-cloze-deletion-ctrlandshiftandc = ക്ലോസ് ഇല്ലാതാക്കൽ (Ctrl+Shift+C)
editing-change-colour-f8 = നിറം മാറ്റുക (F8)
editing-set-foreground-colour-f7 = മുൻഭാഗത്തിന്റെ നിറം സജ്ജമാക്കുക (F7)
editing-customize-card-templates-ctrlandl = കാർഡ് ടെംപ്ലേറ്റുകൾ ഇച്ഛാനുസൃതമാക്കുക (Ctrl+L)
