browsing-add-notes = Жазба қосу...
browsing-add-tags2 = Тамға қосу...
browsing-add-to-selected-notes = Бөлшектенген жазбаларға қосу
browsing-remove-from-selected-notes = Бөлшектенген жазбалардан жою
browsing-addon = Қондырма
browsing-all-fields = Барлық өріс
browsing-answer = Жауап
browsing-any-flag = Кез келген жалау
browsing-average-ease = Орташа жеңілдік
browsing-average-interval = Орташа аралық
browsing-browser-appearance = Шолғыш көрінісі
browsing-browser-options = Шолғыш баптаулары
browsing-buried = Тығылған
browsing-card = Карта
browsing-cards = Карталар
browsing-card-list = Карталар тізімі
browsing-cards-cant-be-manually-moved-into = Карталарды сүзілген колодаға қолмен жылжыта алмайсыз.
browsing-cards-deleted =
    { $count ->
       *[other] { $count } карта табылды
    }
browsing-cards-deleted-with-deckname = { $deck_name } колодасынан { $count } карта жойылды.
browsing-change-deck = Колоданы Ауыстыру
browsing-change-deck2 = Колоданы Ауыстыру...
browsing-change-note-type = Жазба түрін ауыстыру
# Action in a context menu (right mouse-click on a card type)
browsing-change-note-type2 = Жазба түрін ауыстыру...
browsing-change-notetype = Жазба түрін ауыстыру
browsing-clear-unused-tags = Пайдаланылмайтын тамғаларды жою
browsing-confirm-saved-search-overwrite = { $name } деген сақталған іздеу бар. Қайта жазғыңыз келе ме?
browsing-created = Жасалған
browsing-current-deck = Ағымдағы колода
browsing-current-note-type = Ағымдығы жазба түрі:
browsing-delete-notes = Жойылған Жазбалар
browsing-duplicate = телнұсқа
browsing-ease = Жеңілдік
browsing-enter-tags-to-add = Қосатын тамғалар енгізіңіз:
browsing-enter-tags-to-delete = Жоятын тамғалар енгізіңіз:
browsing-filtered = (сүзілген)
browsing-find = <b>Табу</b>:
browsing-find-and-replace = Табу және Ауыстыру
browsing-find-duplicates = Телнұсқаларды Табу
browsing-first-card = Бірінші Карта
browsing-flag = Жалау
browsing-font = <b>Қаріп</b>:
browsing-font-size = <b>Қаріп Өлшемі</b>:
browsing-found-as-across-bs = { $whole } ішінен { $part } табылды.
browsing-ignore-case = Регистрді елемеу
browsing-in = <b>Ішінде</b>
browsing-interval = Аралық
browsing-last-card = Соңғы Карта
browsing-learning = (оқылуда)
browsing-line-size = <b>Жол Биіктігі</b>
browsing-manage-note-types = Жазба Түрлерін Басқару
browsing-move-cards = Карта Жылжыту
browsing-move-cards-to-deck = Карталарды колодаға жылжыту:
browsing-new = (жаңа)
browsing-new-note-type = Жаңа жазба түрі:
browsing-no-flag = Жалау жоқ
browsing-no-selection = Карта не жазба бөлшектенбеген.
browsing-note = Жазба
browsing-notes = Жазбалар
browsing-optional-filter = Ерікті сүзгі:
browsing-override-back-template = Артқы үлгіні басып өту:
browsing-override-font = Қаріпті басып өту:
browsing-override-front-template = Алдыңғы үлгіні басып өту:
browsing-please-give-your-filter-a-name = Сүзгіңізді атаңыз:
browsing-preview-selected-card = Бөлшектенген Картаны ({ $val }) Көру
browsing-question = Сұрақ
browsing-queue-bottom = Кезектің аяғы: { $val }
browsing-queue-top = Кезектің басы: { $val }
browsing-randomize-order = Ретті кездейсоқ ету
browsing-remove-tags = Тамғаларды жою...
browsing-replace-with = <b>Осыға Ауыстыру</b>:
browsing-reposition = Жылжыту...
browsing-reposition-new-cards = Жаңа Карталарды Жылжыту
browsing-reschedule = Қайта Жоспарлау
browsing-search-bar-hint = Карта/жазба іздеу (мәтінді енгізіп Enter басыңыз)
browsing-search-in = Іздеу орны:
browsing-search-within-formatting-slow = Пішімдеумен іздеу (баяу)
browsing-select-deck = Колоданы Бөлшектеу
browsing-selected-notes-only = Тек бөлшектенген жазбалар
browsing-shift-position-of-existing-cards = Бар карталарды ығыстыру
browsing-sidebar = Бүйірлік Үстел
browsing-sidebar-filter = Бүйірлік Үстел сүзгісі
# The field that is used for sorting (sort is an adjective here, not a verb)
browsing-sort-field = Сұрыптау Өрісі
browsing-sorting-on-this-column-is-not = Осы бағанмен сұрыптау мүмкін емес. Басқасын таңдаңыз.
browsing-start-position = Бастауы:
browsing-step = Қадам:
browsing-suspended = Кідіртілген
browsing-tag-duplicates = Телнұсқаларды Тамғалау
browsing-tag-rename-warning-empty = Жазбасыз тамғанын атауын өңдей алмайсыз.
browsing-target-field = Нысана өрісі:
browsing-toggle-bury = Тығу/Қайтару
browsing-toggle-showing-cards-notes = Карта мен жазбаларды көрсету
browsing-toggle-mark = Белгілеу/Белгісіздеу
browsing-toggle-suspend = Кідірту/Тірілту
browsing-treat-input-as-regular-expression = Жай өрнек ретінде енгізу
browsing-update-saved-search = Ағымдағы Іздеумен Жаңарту
browsing-whole-collection = Бүкіл Жинақ
browsing-window-title-notes = Қарау ({ $total } жазбаның { $selected }-і/ы бөлшектенген)
browsing-you-must-have-at-least-one = Кем дегенде бір баған болу керек.
browsing-group = { $count } топ
browsing-note-count = { $count } жазба
browsing-notes-updated = { $count } жазба жаңартылды.
browsing-cards-updated = { $count } карта жаңартылды.
browsing-window-title = Қарау ({ $total } картаның { $selected }-і/ы бөлшектенген)
browsing-sidebar-expand = Жаю
browsing-sidebar-collapse = Жию
browsing-sidebar-expand-children = Туындыларын жаю
browsing-sidebar-collapse-children = Туындыларын жию
browsing-sidebar-decks = Колодалар
browsing-sidebar-tags = Тамғалар
browsing-sidebar-notetypes = Жазба Түрлері
browsing-sidebar-saved-searches = Сақталған Іздеулер
browsing-sidebar-save-current-search = Ағымдағы Іздеуді Сақтау
browsing-sidebar-card-state = Карта күйі
browsing-sidebar-flags = Жалаулар
browsing-today = Бүгін
browsing-tooltip-card-modified = Картаны соңғы өңдеу уақыты (қайталаулар, жалау мен колода өзгерістері есептенген)
browsing-tooltip-note-modified = Жазбаны соңғы өңдеу уақыты (қайталаулар, жалауша мен колода өзгерістері есептенген)
browsing-tooltip-card = Картаның үлгісінің атауы
browsing-tooltip-cards = Жазбадағы карталар саны
browsing-tooltip-notetype = Жазбаның түрінің атауы
browsing-tooltip-question = Картаның алды. Карта үлгісі редакторында баптай аласыз.
browsing-tooltip-answer = Картаның арты. Карта үлгісі редакторында баптай аласыз.
browsing-studied-today = Оқылған
browsing-added-today = Қосылған
browsing-again-today = Қайтадан
browsing-edited-today = Өңделген
browsing-sidebar-first-review = Бірінші Қайталау
browsing-sidebar-rescheduled = Қайта Жоспарланды
browsing-sidebar-due-today = Бүгінге
browsing-sidebar-untagged = Тамғаланбаған
browsing-sidebar-overdue = Мерізімі өткен
browsing-row-deleted = (жойылған)
browsing-removed-unused-tags-count = Қолданылмайтын { $count } тамға жойылды.
browsing-changed-new-position = { $count } карта жылжытылды.
browsing-reparented-decks = { $count } қайта аталды.
browsing-sidebar-card-state-review = Қайталау

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

# Exactly one character representing 'Cards'; should differ from browsing-note-initial.
browsing-card-initial = К
# Exactly one character representing 'Notes'; should differ from browsing-card-initial.
browsing-note-initial = Ж
