profiles-anki-could-not-read-your-profile = Anki профиль ақпаратыңызды оқи алмады. Терезе өлшемдері және үйлестіруге кіру деректері ұмытылды.
profiles-anki-could-not-rename-your-profile = Anki профиліңіздің атын өзгерте алмады, себебі дисктегі профиль қалтасын қайта атай алмады. Documents қалтасына жазуға рұқсатыңыз бар екеніне көз жеткізіңіз. Anki және басқа бағдарламалар профиль қалталарыңызға кірмейтініне көз жеткізіп, қайтадан көріңіз.
profiles-folder-already-exists = Қалта онсыз да бар.
profiles-open = Ашу
profiles-open-backup = Сақтық Көшірмені Ашу...
profiles-please-remove-the-folder-and = { $val } қалтасын жойып қайталаңыз.
profiles-profile-corrupt = Профиль Бүлінген
profiles-profiles = Профилдер
profiles-quit = Шығу
profiles-user-1 = 1 Қолданушы
profiles-confirm-lang-choice = Anki интерфейсін { $lang } тілінде көрсетуге сенімдісіз бе?
profiles-could-not-create-data-folder = Anki деректер қалтасын жасай алмады. Нұсқаулықтағы File Locations бөліміне өтіп, ол орын тек оқу емес екеніне көз жеткізіңіз.
profiles-prefs-corrupt-title = Бапталымдар Бүлінген
profiles-prefs-file-is-corrupt = Anki-дің prefs21.db файлы бүлінген және қайта жасалды. Егер бірнеше профильді қолданған болсаңыз, карталарыңызды қалпына келтіру үшін сол профиль атауларымен қайта қосыңыз.
profiles-profile-does-not-exist = Сұранған профиль жоқ.
profiles-creating-backup = Сақтық Көшірме Жасау...
profiles-backup-created = Сақтық көшірме жасалды.
profiles-backup-creation-failed = Сақтық көшірме жасалмады: { $reason }
profiles-backup-unchanged = Соңғы сақтық көшірмеден бері өзгерістер жоқ.
