actions-add = Dodaj
actions-all-selected = Vsi izbrani
actions-any-selected = Katerikoli izbrani
actions-cancel = Prekliči
actions-choose = Izberi
actions-close = Zapri
actions-copy = Kopiraj
actions-create-copy = Ustvari kopijo
actions-custom-study = Ponavljanje po meri
actions-decks = Zbirke kartic
actions-decrement-value = Zmanjšaj vrednost
actions-delete = Izbriši
actions-export = Izvoz
actions-filter = Filtriraj
actions-help = Pomoč
actions-increment-value = Povišaj vrednost
actions-import = Uvoz
actions-manage = Upravljaj...
actions-name = Ime:
actions-new = Novo
actions-new-name = Novo ime:
actions-options = Možnosti
actions-options-for = Možnosti za { $val }
actions-preview = Predogled
actions-rebuild = Ponovno zgradi
actions-rename = Preimenuj
actions-rename-deck = Preimenuj paket
actions-rename-tag = Preimenuj oznako
actions-rename-with-parents = Preimeniuj z nadrejenimi
actions-remove-tag = Odstrani oznako
actions-replay-audio = Znova predvajaj zvok
actions-reposition = Prestavi
actions-save = Shrani
actions-search = Iskanje
actions-select = Izberi
actions-shortcut-key = Bližnjica: { $val }
actions-suspend-card = Odloži kartico
actions-set-due-date = Nastavi datum poteka
actions-answer-card = Kartica z odgovorom
actions-unbury-unsuspend = Izkoplji/Odstrani iz suspendiranih
actions-add-deck = Dodaj zbirko
actions-add-note = Dodaj zapis
actions-update-tag = Posodobi oznako
actions-update-note = Posodobi zapis
actions-update-card = Posodobi kartico
actions-update-deck = Posodobi zbirko kartic
actions-forget-card = Pozabi kartico
actions-build-filtered-deck = Izdelaj zbirko
actions-add-notetype = Dodaj tip zapiska
actions-remove-notetype = Odstrani tip zapiska
actions-update-notetype = Posodobi tip zapiska
actions-update-config = Posodobi nastavitev
actions-card-info = Podatki kartice
actions-previous-card-info = Podatki prejšnje kartice
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = Te akcije vaš sistem trenutno ne podpira.

## Flags

actions-flag-number = Označi z zastavico { $number }
actions-flag-red = Rdeča
actions-flag-orange = Oranžna
actions-flag-green = Zelena
actions-flag-blue = Modra
actions-flag-pink = Roza
actions-flag-turquoise = Turkizna
actions-flag-purple = Vijolična
actions-set-flag = Nastavi zastavico
actions-processing = V obdelavi ...
