adding-add-shortcut-ctrlandenter = Dodaj (bližnjica: Ctrl+Enter)
adding-added = Dodano
adding-close-and-lose-current-input = Zapri in razveljavi trenutni vnos?
adding-edit = Uredi "{ $val }"
adding-history = Zgodovina
adding-note-deleted = (Izbrisan zapisek)
adding-shortcut = Bližnjica:{ $val }
adding-the-first-field-is-empty = Prvo polje je prazno.
adding-you-have-a-cloze-deletion-note = Izbran tip zapiska je z zaporo podatka (cloze), vendar je niste ustvarili. Nadaljujem?
adding-cloze-outside-cloze-notetype = Zaporo lahko ustvarite samo na tipu zapiska z zaporo podatka.
adding-cloze-outside-cloze-field = Zaporo lahko uporabite le v poljih, ki uporabljajo filter 'zapora podatka:'. Običajno je to prvo polje.
