decks-add-new-deck-ctrlandn = Dodaj nov paket (Ctrl+N)
decks-build = Zgradi
decks-cards-selected-by = kartice izbrane od
decks-create-deck = Ustvari paket
decks-custom-steps-in-minutes = Koraki po izbiri (v minutah)
decks-deck = Zbirka
decks-decreasing-intervals = Padajoči intervali
decks-delete-deck = Izbriši zbirko kartic
decks-enable-second-filter = Omogoči še en filter
decks-filter = Filter:
decks-filter-2 = Filter 2
decks-get-shared = Naloži javne zbirke
decks-import-file = Uvozi datoteko
decks-increasing-intervals = Vedno večji intervali
decks-latest-added-first = Najnovejše dodane prve
decks-limit-to = Omeji na
decks-minutes = minute
decks-most-lapses = Največ spodrsljajev
decks-new-deck-name = Novo ime zbirke:
decks-no-deck = [ni paketa]
decks-oldest-seen-first = Najprej vidne najstarejše
decks-order-added = Uredi dodane
decks-order-due = Uredi zapadle
decks-please-select-something = Izberite nekaj.
decks-random = Naključno
decks-relative-overdueness = Relativen potek roka
decks-repeat-failed-cards-after = Ponovi kartice po
decks-reschedule-cards-based-on-my-answers = Prerazporedi kartice glede na moje odgovore v tem paketu
decks-study = Študiraj
decks-study-deck = Paket za učenje
decks-filtered-deck-search-empty = Z iskalnim pogojem se ne ujema nobena kartica. Nekatere kartice so lahko izključene iz iskanja ker so v drugi filtrirani zbirki ali pa so suspendirane.
decks-unmovable-cards = Pokaži izločene kartice
# The count of cards waiting to be reviewed
decks-review-header = Preteklih
decks-learn-header = Učenje
