fields-add-field = Dodaj polje
fields-delete-field-from = Izbrišem polje iz { $val }?
fields-editing-font = Urejanje pisave
fields-field = Polje:
fields-field-name = Ime polja:
fields-description = Opis
fields-description-placeholder = Besedilo, ki naj se izpiše v polju, ko je prazno
fields-fields-for = Polja za { $val }
fields-font = Pisava:
fields-new-position-1 = Novo mesto (1...{ $val }):
fields-notes-require-at-least-one-field = Zapiski zahtevajo vsaj eno polje.
fields-reverse-text-direction-rtl = Obratna smer besedila (RTL)
fields-collapse-by-default = Privzeto skrči
fields-html-by-default = Privzeto uporabi HTML urejevalnik
fields-size = Velikost:
fields-sort-by-this-field-in-the = Uredi po tem polju v brskalniku
fields-that-field-name-is-already-used = To ime polja je že uporabljeno.
fields-name-first-letter-not-valid = Ime polja se ne sme začeti z #, ^ ali /.
fields-name-invalid-letter = Ime polja ne sme vsebovati :, ", { "{" } ali { "}" }.
