preferences-automatically-sync-on-profile-openclose = Pri odpiranju/zapiranju profila samodejno sinhroniziraj
preferences-backups = Varnostne kopije
preferences-basic = Osnovno
preferences-change-deck-depending-on-note-type = Spremeni paket glede na tip zapiska
preferences-changes-will-take-effect-when-you = Spremembe bodo stopile v veljavo po ponovnem zagonu Ankija.
preferences-hours-past-midnight = ur od polnoči
preferences-interface-language = Jezik vmesnika:
preferences-interrupt-current-audio-when-answering = Pri odgovarjanju prekini trenutni zvok
preferences-learn-ahead-limit = Omejitev učenja vnaprej
preferences-mins = minut
preferences-network = Omrežje
preferences-next-day-starts-at = Naslednji dan se začne ob
preferences-note-media-is-not-backed-up = Opozorilo: Medijske datoteke nimajo varnostne kopije. Priporočamo, da občasno naredite varnostno kopijo mape Anki.
preferences-on-next-sync-force-changes-in = Pri naslednji sinhronizaciji vsili spremembe v eni smeri
preferences-paste-clipboard-images-as-png = Prilepi slike z odložišča kot PNG
preferences-paste-without-shift-key-strips-formatting = Lepljenje brez tipke Shift prilepi brez oblikovanja
preferences-periodically-sync-media = Periodično sinhroniziraj medijske datoteke
preferences-please-restart-anki-to-complete-language = Za spremembo jezika ponovno zaženite Anki.
preferences-preferences = Možnosti
preferences-scheduling = Določi nov razpored
preferences-show-learning-cards-with-larger-steps = Pred ponovitvami pokaži kartice z večjimi koraki med ponovitvami
preferences-show-next-review-time-above-answer = Pokaži čas za naslednji pregled nad gumbi za odgovore
preferences-show-play-buttons-on-cards-with = Na karticah z zvokom prikaži gumb "Predvajaj"
preferences-show-remaining-card-count-during-review = Pokaži število preostalih kartic med pregledom
preferences-some-settings-will-take-effect-after = Nekatere nastavitve bodo pričele delovati po ponovnem zagonu Ankija.
preferences-synchronisation = <b>Sinhronizacija</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Sinhronizacija</b><br> Ni trenutno omogočena; Omogočite jo s klikom na gumb Sinhroniziraj v glavnem oknu.
preferences-synchronize-audio-and-images-too = Sinhroniziraj tudi zvok in slike
preferences-timebox-time-limit = Časovna omejitev
preferences-user-interface-size = Velikost uporabniškega vmesnika
preferences-when-adding-default-to-current-deck = Med dodajanjem naj bo privzet trenutni paket
preferences-you-can-restore-backups-via-fileswitch = Rezervne kopije lahko obnovite preko Datoteka>Zamenjaj profil.
preferences-legacy-timezone-handling = Vgrajeno urejanje časovnega pasu (zatikajoče, vendar zahtevano za AnkiDroid <= 2.14)
preferences-default-search-text = Privzet iskalni pojem
preferences-default-search-text-example = npr. 'deck:current'
preferences-theme-label = Tema: { $theme }
preferences-theme-follow-system = Sledi sistemski
preferences-theme-light = Svetla
preferences-theme-dark = Temna
preferences-v3-scheduler = Razporejevalnik V3
preferences-ignore-accents-in-search = Spreglej naglase pri iskanju (počasnejše)
preferences-backup-explanation =
    Anki periodično varnostno kopira vašo kolekcijo. Ko so rezervne kopije starejše od 2 dni,
    jih Anki samodejno odstranjuje za varčevanje s prostorom na disku.
preferences-daily-backups = Obdrži toliko dnevnih rezervnih kopij:
preferences-weekly-backups = Obdrži toliko tedenskih rezervnih kopij:
preferences-monthly-backups = Obdrži toliko mesečnih rezervnih kopij:
preferences-minutes-between-backups = Čas v minutah med samodejnim ustvarjanjem rezervne kopije:
preferences-reduce-motion = Zmanjšaj premike
preferences-reduce-motion-tooltip = Onemogoči animacije in prehode v uporabniškem vmesniku
