profiles-anki-could-not-read-your-profile = Anki ni mogel dostopati do podatkov vašega profila. Velikosti oken in vpisni podatki za sinhronizacijo so bili izbrisani.
profiles-anki-could-not-rename-your-profile = Anki ni mogel preimenovati vašega profila, ker ni mogel preimenovati profilne mape na disku. Prosimo, zagotovite, da ima Anki dovoljenje za spreminjanje mape Documents/Anki, in da drugi programi ne dostopajo do te mape. Nato poskusite znova.
profiles-folder-already-exists = Mapa že obstaja.
profiles-open = Odpri
profiles-open-backup = Odpri rezervno kopijo...
profiles-please-remove-the-folder-and = Prosimo, odstranite mapo { $val } in poskusite znova.
profiles-profile-corrupt = Podatki profila so okvarjeni
profiles-profiles = Profili
profiles-quit = Zapri
profiles-user-1 = Uporabnik 1
profiles-confirm-lang-choice = Ali ste prepričani, da želite uporabniški vmesnik programa Anki prikazovati v { $lang }?
profiles-could-not-create-data-folder = Anki ni mogel ustvariti mape za hrambo podatkov. Prosimo, preglejte priročnik za del "File Locations" in poskrbite, da lokacija mape ni označena samo za branje.
profiles-prefs-corrupt-title = Nastavitve so v okvari.
profiles-prefs-file-is-corrupt = Datoteka prefs21.db je bila okvarjena in ponovno ustvarjena. Če ste uporabljali več profilov, jih dodajte znova z istimi imeni, da obnovite svoje kartice.
profiles-profile-does-not-exist = Zahtevani profil ne obstaja.
profiles-creating-backup = Izdelava rezervne kopije...
profiles-backup-created = Rezervna kopija je bila ustvarjena.
profiles-backup-creation-failed = Izdelava rezervne kopije je spodletela: { $reason }
profiles-backup-unchanged = Od zadnje izdelave rezervne kopije ni bilo sprememb.
