editing-actual-size = Haqiqiy oʻlchamini yoqish/oʻchirish
editing-add-media = Media fayl qoʻshish
editing-align-left = Chapga tenglashtirish
editing-align-right = Oʻngga tenglashtirish
editing-an-error-occurred-while-opening = { $val } ni ochishda xatolik yuz berdi
editing-attach-picturesaudiovideo = Rasm/audio/video biriktirish
editing-bold-text = Qalin matn
editing-cards = Kartalar
editing-center = Markaz
editing-change-color = Rangini oʻzgartirish
editing-cloze-deletion = Boʻshliqni toʻldirish (yangi karta)
editing-cloze-deletion-repeat = Boʻshliqni toʻldirish (oʻsha karta)
editing-copy-image = Rasmdan nusxa olish
editing-couldnt-record-audio-have-you-installed = Audioni yozib boʻlmadi. 'lame'ni oʻrnatganmisiz?
editing-customize-card-templates = Karta shablonlarini moslashtirish
editing-customize-fields = Maydonlarni moslashtirish
editing-cut = Qirqish
editing-double-click-image = Rasmni ikki marta bosing
editing-double-click-to-expand = Kattalashtirish uchun ikki marta bosing
editing-double-click-to-collapse = Yigʻish uchun ikki marta bosing
editing-edit-current = Joriyni tahrirlash
editing-edit-html = HTMLʻni tahrirlash
editing-fields = Maydonlar
editing-float-left = Chapga joylashtirish
editing-float-right = Oʻngga joylashtirish
editing-float-none = Joyida qoldirish
editing-indent = Xatboshini oshirish
editing-italic-text = Kursiv matn
editing-jump-to-tags-with-ctrlandshiftandt = Ctrl+Shift+T orqali teglarga oʻtish
editing-justify = Eni boʻyicha tenglashtirish
editing-latex = LaTeX
editing-latex-equation = LaTeX tenglama
editing-latex-math-env = LaTeX matematika muhiti
editing-mathjax-block = MathJax bloki
editing-mathjax-chemistry = MathJax kimyo
editing-mathjax-inline = MathJax qator ichida
editing-mathjax-placeholder = Qabul qilish uchun { $accept } bosing, yangi qator uchun { $newline } bosing.
editing-media = Media fayl
editing-open-image = Rasm ochish
editing-show-in-folder = Jildda koʻrsatish
editing-ordered-list = Tartiblangan roʻyxat
editing-outdent = Xatboshini kamaytirish
editing-paste = Qoʻyish
editing-record-audio = Audioni yozib olish
editing-remove-formatting = Formatlashni oʻchirish
editing-restore-original-size = Original oʻlchamiga qaytarish
editing-select-remove-formatting = Oʻchirish uchun formatlashni tanlang
editing-show-duplicates = Nusxalarni koʻrsatish
editing-subscript = Satr osti
editing-superscript = Satr usti
editing-tags = Teglar
editing-tags-add = Teg qoʻshish
editing-tags-copy = Teglardan nusxa olish
editing-tags-remove = Teglarni olib tashlash
editing-tags-select-all = Barcha teglarni tanlash
editing-text-color = Matn rangi
editing-text-highlight-color = Matn belgilash rangi
editing-to-make-a-cloze-deletion-on = Mavjud qaydga toʻldiriladigan boʻshliqni qoʻshish uchun avval uni "Qaydlar>Qayd turini oʻzgartirish" orqali boʻshliqni toʻldirish turiga oʻzgartirishingiz kerak.
editing-toggle-html-editor = HTML muharririni yoqish/oʻchirish
editing-toggle-visual-editor = Vizual muharrirni yoqish/oʻchirish
editing-toggle-sticky = Yopishtirishni yoqish/oʻchirish
editing-expand = Yoyish
editing-collapse = Yigʻish
editing-expand-field = Maydonni yoyish
editing-collapse-field = Maydonni yigʻish
editing-underline-text = Matn tagiga chizish
editing-unordered-list = Tartiblanmagan roʻyxat
editing-warning-cloze-deletions-will-not-work = Ogohlantirish: qayd turini boʻshliqni toʻldirishga almashtirmaguningizcha, boʻshliqni toʻldirish ishlamaydi.
editing-mathjax-preview = MathJax namunasi
editing-shrink-images = Rasmlarni kichiklashtirish
editing-close-html-tags = HTML teglarini avtomatik tarzda yopish
editing-from-clipboard = Buferdan
editing-alignment = Tenglashtirish
editing-equations = Tenglamalar
editing-no-image-found-on-clipboard = Buferda rasm topilmadi.
editing-image-occlusion-mode = Toʻsiqli rasm rejimi
editing-image-occlusion-zoom-out = Kichiklashtirish
editing-image-occlusion-zoom-in = Kattalashtirish
editing-image-occlusion-zoom-reset = Masshtabni qayta tiklash
editing-image-occlusion-toggle-translucent = Shaffoflikni yoqish/oʻchirish
editing-image-occlusion-delete = Oʻchirish
editing-image-occlusion-duplicate = Nusxalash
editing-image-occlusion-group = Tanlanganlarni guruhlash
editing-image-occlusion-ungroup = Tanlanganlarni ajratish
editing-image-occlusion-select-all = Barchasini tanlash
editing-image-occlusion-alignment = Tenglashtirish
editing-image-occlusion-align-left = Chapga tenglashtirish
editing-image-occlusion-align-h-center = Gorizontal markzalarga tenglashtirish
editing-image-occlusion-align-right = Oʻngga tenglashtirish
editing-image-occlusion-align-top = Yuqoriga tenglashtirish
editing-image-occlusion-align-v-center = Vertikal markazlarga tenglashtirish
editing-image-occlusion-align-bottom = Pastga tenglashtirish
editing-image-occlusion-select-tool = Tanlash
editing-image-occlusion-zoom-tool = Masshtab
editing-image-occlusion-rectangle-tool = Toʻrtburchak
editing-image-occlusion-ellipse-tool = Ellips
editing-image-occlusion-polygon-tool = Koʻpburchak
editing-image-occlusion-text-tool = Matn
editing-image-occlusion-fill-tool = Rang bilan toʻldirish
editing-image-occlusion-toggle-mask-editor = Niqob muharririni yoqish/oʻchirish
editing-image-occlusion-reset = Rasm toʻsiqlarini asliga qaytarish
editing-image-occlusion-confirm-reset = Bu rasmdagi toʻsiqlarni rostdan ham asliga qaytarmoqchimisiz?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML muharriri
