profiles-anki-could-not-read-your-profile = Anki profil maʼlumotlaringizni oʻqiy olmadi. Oyna oʻlchamlari va sinxronlashga kirish maʻlumotlari unutildi.
profiles-anki-could-not-rename-your-profile = Anki profilingiz nomini oʻzgartira olmadi, chunki u diskdagi profil jild nomini oʻzgartira olmadi. Documents/Ankiʼga yozish uchun ruxsatingiz borligiga ishonch hosil qiling va boshqa dasturlar sizning profilingiz jildlariga kirmayotganiga ishonch hosil qiling, soʻng qayta urinib koʻring.
profiles-folder-already-exists = Jild allaqachon mavjud.
profiles-open = Ochish
profiles-open-backup = Zaxira nusxasini ochish...
profiles-please-remove-the-folder-and = { $val } jildini oʻchirib qayta urinib koʻring.
profiles-profile-corrupt = Profil buzilgan
profiles-profiles = Profillar
profiles-quit = Chiqish
profiles-user-1 = Foydalanuvchi 1
profiles-confirm-lang-choice = Rostdan ham Anki interfeysini { $lang } tilida koʻrsatmoqchimisiz?
profiles-could-not-create-data-folder = Anki oʻzining maʼlumotlar jildini yarata olmadi. Qoʻllanmaning File Locations boʻlimiga qarang va joylashuv faqat oʻqish uchun emasligiga ishonch hosil qiling.
profiles-prefs-corrupt-title = Sozlamalar buzilgan
profiles-prefs-file-is-corrupt = Ankiʼning prefs21.db fayli buzilgan va qayta yaratildi. Agar siz bir nechta profildan foydalangan boʻlsangiz, kartalaringizni tiklash uchun ularni bir xil nomlari bilan qayta qoʻshing.
profiles-profile-does-not-exist = Soʻralgan profil mavjud emas.
profiles-creating-backup = Zaxira yaratilmoqda...
profiles-backup-created = Zaxira yaratildi.
profiles-backup-creation-failed = Zaxirani yaratib boʻlmadi: { $reason }
profiles-backup-unchanged = Oxirgi zaxiradan beri oʻzgarishlar yoʻq.
