actions-add = Добавяне
actions-cancel = Отказ
actions-choose = Избиране
actions-close = Затвори
actions-copy = Копиране
actions-custom-study = Учене извън програмата
actions-decks = Тестета
actions-delete = Изтриване
actions-export = Експортиране
actions-filter = Филтър
actions-help = Помощ
actions-import = Импортиране
actions-name = Име:
actions-new = Нови
actions-new-name = Ново име:
actions-options = Опции
actions-options-for = Опции за { $val }
actions-preview = Предварителен преглед
actions-rebuild = Прегенериране
actions-rename = Преименуване
actions-rename-deck = Преименуване на тестето
actions-replay-audio = Повторно стартиране на аудиото
actions-reposition = Разместване
actions-search = Търсене
actions-shortcut-key = Бутон за бърз достъп: { $val }
actions-processing = Обработка…
