card-stats-added = Добавени
card-stats-first-review = Първи преговор
card-stats-latest-review = Най-скорошен преговор
card-stats-interval = Интервал
card-stats-ease = Лекота
card-stats-review-count = Прегледи
card-stats-average-time = Средно време
card-stats-total-time = Общо време
card-stats-new-card-position = Позиция
card-stats-card-template = Тип карта
card-stats-note-type = Тип бележка
card-stats-deck-name = Тесте
card-stats-note-id = Идентификатор на бележката
card-stats-card-id = Идентификатор на картата
card-stats-review-log-rating = Рейтинг
card-stats-review-log-date = Дата
card-stats-review-log-time-taken = Време
card-stats-review-log-type-learn = Учене
card-stats-review-log-type-relearn = Повторно научени
