editing-actual-size = 切換以實際尺寸顯示
editing-add-media = 新增媒體
editing-align-left = 靠左對齊
editing-align-right = 靠右對齊
editing-an-error-occurred-while-opening = 打開 { $val } 時發生錯誤
editing-attach-picturesaudiovideo = 加入圖片/音訊/影片
editing-bold-text = 粗體
editing-cards = 卡片
editing-center = 置中
editing-change-color = 更改顏色
editing-cloze-deletion = 克漏字空格（新卡片）
editing-cloze-deletion-repeat = 克漏字空格（相同卡片）
editing-copy-image = 複製影像
editing-couldnt-record-audio-have-you-installed = 無法錄製音訊。請檢查是否已安裝「lame」。
editing-customize-card-templates = 自訂卡片模板
editing-customize-fields = 自訂欄位
editing-cut = 剪下
editing-double-click-image = 按兩下影像
editing-double-click-to-expand = （按兩下以展開）
editing-double-click-to-collapse = 按兩下以摺疊
editing-edit-current = 編輯當前卡片
editing-edit-html = 編輯 HTML
editing-fields = 欄位
editing-float-left = 向左浮動
editing-float-right = 向右浮動
editing-float-none = 無浮動
editing-indent = 增加縮排
editing-italic-text = 斜體
editing-jump-to-tags-with-ctrlandshiftandt = 跳至標籤 (Ctrl+Shift+T)
editing-justify = 左右對齊
editing-latex = LaTeX
editing-latex-equation = LaTeX 方程式
editing-latex-math-env = LaTeX 數學環境
editing-mathjax-block = MathJax 區塊
editing-mathjax-chemistry = MathJax 化學
editing-mathjax-inline = MathJax 行內
editing-mathjax-placeholder = 按下 { $accept } 接受，{ $newline } 換行。
editing-media = 媒體
editing-open-image = 打開影像
editing-show-in-folder = 在資料夾中顯示
editing-ordered-list = 有序清單
editing-outdent = 減少縮排
editing-paste = 貼上
editing-record-audio = 錄製音訊
editing-remove-formatting = 移除格式
editing-restore-original-size = 回復原始大小
editing-select-remove-formatting = 選取要移除的格式
editing-show-duplicates = 顯示重複項目
editing-subscript = 下標
editing-superscript = 上標
editing-tags = 標籤
editing-tags-add = 加入標籤
editing-tags-copy = 複製標籤
editing-tags-remove = 移除標籤
editing-tags-select-all = 選取所有標籤
editing-text-color = 文字顏色
editing-text-highlight-color = 重點文字顏色
editing-to-make-a-cloze-deletion-on = 要在現有的筆記上建立克漏字空格，請先透過「筆記」>「更改筆記類型」將其改為任意克漏字類型。
editing-toggle-html-editor = 切換 HTML 編輯器
editing-toggle-visual-editor = 切換視覺化編輯器
editing-toggle-sticky = 切換凍結欄位
editing-expand = 展開
editing-collapse = 摺疊
editing-expand-field = 展開欄位
editing-collapse-field = 摺疊欄位
editing-underline-text = 底線
editing-unordered-list = 無序清單
editing-warning-cloze-deletions-will-not-work = 警告，請在上方將類型改為克漏字，否則克漏字空格將不會生效。
editing-mathjax-preview = MathJax 預覽
editing-shrink-images = 縮小影像
editing-close-html-tags = 自動閉合 HTML 標籤
editing-from-clipboard = 從剪貼板
editing-alignment = 對齊
editing-equations = 方程式
editing-no-image-found-on-clipboard = 在剪貼板中找不到影像。
editing-image-occlusion-mode = 影像遮擋模式
editing-image-occlusion-zoom-out = 縮小
editing-image-occlusion-zoom-in = 放大
editing-image-occlusion-zoom-reset = 重置縮放
editing-image-occlusion-toggle-translucent = 切換半透明
editing-image-occlusion-delete = 刪除
editing-image-occlusion-duplicate = 複製
editing-image-occlusion-group = 群組
editing-image-occlusion-ungroup = 取消群組
editing-image-occlusion-select-all = 選取全部
editing-image-occlusion-alignment = 對齊
editing-image-occlusion-align-left = 靠左對齊
editing-image-occlusion-align-h-center = 水平置中
editing-image-occlusion-align-right = 靠右對齊
editing-image-occlusion-align-top = 靠上對齊
editing-image-occlusion-align-v-center = 垂直置中
editing-image-occlusion-align-bottom = 靠下對齊
editing-image-occlusion-select-tool = 選取
editing-image-occlusion-zoom-tool = 縮放
editing-image-occlusion-rectangle-tool = 矩形
editing-image-occlusion-ellipse-tool = 橢圓形
editing-image-occlusion-polygon-tool = 多邊形
editing-image-occlusion-text-tool = 文字
editing-image-occlusion-fill-tool = 填充顏色
editing-image-occlusion-toggle-mask-editor = 切換遮罩編輯器
editing-image-occlusion-reset = 重置影像遮擋
editing-image-occlusion-confirm-reset = 確定要重置這個影像遮擋嗎？

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML 編輯器
