editing-add-media = เพิ่มสื่อ
editing-align-left = จัดชิดซ้าย
editing-align-right = จัดชิดขวา
editing-an-error-occurred-while-opening = เกิดข้อผิดพลาดระหว่างเปิด { $val }
editing-attach-picturesaudiovideo = แนบภาพ/เสียง/วีดีโอ
editing-bold-text = ตัวหนา
editing-cards = การ์ด
editing-change-color = เปลี่ยนสี
editing-copy-image = คัดลอกภาพ
editing-customize-card-templates = ปรับแต่งแม่แบบการ์ด
editing-customize-fields = ปรับแต่งช่องข้อมูล
editing-cut = ตัด
editing-edit-current = แก้ไขการ์ดปัจจุบัน
editing-edit-html = แก้ไข HTML
editing-fields = ช่องข้อมูล
editing-italic-text = ตัวเอียง
editing-latex = LaTeX
editing-latex-equation = สมการ LaTeX
editing-media = สื่อ
editing-open-image = เปิดรูป
editing-show-in-folder = แสดงในโฟลเดอร์
editing-ordered-list = รายการเรียงลำดับ
editing-paste = วาง
editing-record-audio = อัดเสียง
editing-remove-formatting = นำการจัดหน้าออก
editing-restore-original-size = คืนขนาดเดิม
editing-select-remove-formatting = เลือกการจัดหน้าที่จะเอาออก
editing-show-duplicates = แสดงค่าซ้ำ
editing-subscript = ตัวห้อย
editing-superscript = ตัวยก
editing-tags = แท็ก
editing-tags-add = เพิ่มแท็ก
editing-tags-copy = คัดลอกแท็ก
editing-tags-remove = นำแท็กออก
editing-tags-select-all = เลือกแท็กทั้งหมด
editing-text-color = สีของข้อความ
editing-expand = ขยาย
editing-collapse = ย่อ
editing-expand-field = ขยายช่องข้อมูล
editing-collapse-field = ย่อช่องข้อมูล
editing-underline-text = ขีดเส้นใต้
editing-unordered-list = รายการไม่เรียงลำดับ
editing-mathjax-preview = แสดงตัวอย่าง MathJax
editing-close-html-tags = ใส่แท็กปิดของ HTML โดยอัตโนมัติ
editing-equations = สมการ
editing-image-occlusion-delete = ลบ
editing-image-occlusion-select-all = เลือกทั้งหมด
editing-image-occlusion-align-left = จัดชิดซ้าย
editing-image-occlusion-align-right = จัดชิดขวา
editing-image-occlusion-select-tool = เลือก
editing-image-occlusion-text-tool = ข้อความ

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = เครื่องมือแก้ไข HTML
