card-stats-added = Προστέθηκε
card-stats-first-review = Πρώτη επανάληψη
card-stats-latest-review = Τελευταία επανάληψη
card-stats-interval = Διάστημα
card-stats-ease = Ευκολία
card-stats-review-count = Επαναλήψεις
card-stats-lapse-count = Ολισθήματα
card-stats-average-time = Μέσος χρόνος
card-stats-total-time = Συνολικός χρόνος
card-stats-new-card-position = Θέση
card-stats-card-template = Τύπος κάρτας
card-stats-note-type = Τύπος σημείωσης
card-stats-deck-name = Τράπουλα
card-stats-preset = Προεπιλογή
card-stats-note-id = ID σημείωσης
card-stats-card-id = ID κάρτας
card-stats-review-log-rating = Αξιολόγηση
card-stats-review-log-type = Τύπος
card-stats-review-log-date = Ημερομηνία
card-stats-review-log-time-taken = Χρόνος
card-stats-review-log-type-learn = Μελέτη
card-stats-review-log-type-review = Επανάληψη
card-stats-review-log-type-relearn = Επανεκμάθηση
card-stats-review-log-type-filtered = Φιλτραρισμένο
card-stats-review-log-type-manual = Χειροκίνητα
card-stats-review-log-type-rescheduled = Επαναπρογραμματισμένες
card-stats-review-log-elapsed-time = Παρελθόν Χρόνος
card-stats-no-card = (Καμία κάρτα προς προβολή.)
card-stats-custom-data = Προσαρμοσμένα δεδομένα
card-stats-fsrs-stability = Σταθερότητα
card-stats-fsrs-difficulty = Δυσκολία
card-stats-fsrs-retrievability = Ανακτησιμότητα
card-stats-fsrs-forgetting-curve-title = Καμπύλη λήθης
card-stats-fsrs-forgetting-curve-first-week = Πρώτη εβδομάδα
card-stats-fsrs-forgetting-curve-first-month = Πρώτος μήνας
card-stats-fsrs-forgetting-curve-first-year = Πρώτο έτος
card-stats-fsrs-forgetting-curve-all-time = Συνολικός χρόνος
card-stats-fsrs-forgetting-curve-probability-of-recalling = Πιθανότητα Ανάκλησης
card-stats-fsrs-forgetting-curve-desired-retention = Επιθυμητή Ανάκληση

## Window Titles

card-stats-current-card = Τρέχουσα κάρτα ({ $context })
card-stats-previous-card = Προηγούμενη κάρτα ({ $context })
