profiles-anki-could-not-read-your-profile = To Anki δεν μπόρεσε να διαβάσει τα δεδομένα του προφίλ σας. Το μέγεθος των παραθύρων και οι πληροφορίες σύνδεσής σας έχουν ξεχαστεί.
profiles-anki-could-not-rename-your-profile = To Anki δεν μπόρεσε να μετονομάσει το προφίλ σας επειδή δεν μπόρεσε να μετονομάσει τον φάκελο του προφίλ στον δίσκο. Παρακαλώ βεβαιωθείτε ότι έχετε άδεια να γράψετε στο Έγγραφα/Anki και ότι κανένα άλλο πρόγραμμα δεν έχει πρόσβαση στους φακέλους του προφίλ σας και μετά ξαναπροσπαθήστε.
profiles-folder-already-exists = Ο φάκελος υπάρχει ήδη.
profiles-open = Άνοιγμα
profiles-open-backup = Άνοιγμα αντιγράφου ασφαλείας...
profiles-please-remove-the-folder-and = Παρακαλώ αφαιρέστε τον φάκελο { $val } και δοκιμάστε ξανά.
profiles-profile-corrupt = Κατεστραμμένο προφίλ
profiles-profiles = Προφίλ
profiles-quit = Κλείσιμο
profiles-user-1 = Χρήστης 1
profiles-confirm-lang-choice = Είστε σίγουροι ότι εποθυμείτε την προβολή του γραφικού περιβάλλοντος του Anki στα { $lang };
profiles-could-not-create-data-folder = Το Anki δεν μπόρεσε να δημιουργήσει αυτόν τον φάκελο δεδομένων. Παρακαλώ δείτε την ενότητα File Locations στο εγχειρίδιο και βεβαιωθείτε ότι η τοποθεσία δεν είναι μόνο για ανάγνωση.
profiles-prefs-corrupt-title = Aλλοιωμένες Προτιμήσεις
profiles-prefs-file-is-corrupt = Το αρχείο Anki prefs21.db ήταν κατεστραμμένο και έχει ξαναδημιουργηθεί. Αν χρησιμοποιούσατε πολλαπλά προφίλ, παρακαλώ προσθέστε τα ξανά χρησιμοποιώντας τα ίδια ονόματα για να ανακτήσετε τις κάρτες σας.
profiles-profile-does-not-exist = Το συγκεκριμένο προφίλ δεν υπάρχει.
profiles-creating-backup = Δημιουργώντας αντίγραφο ασφαλείας...
profiles-backup-created = Το αντίγραφο δημιουργήθηκε.
profiles-backup-creation-failed = Η δημιουργία αντιγράφου ασφαλείας απέτυχε: { $reason }
profiles-backup-unchanged = Καμία αλλαγή από το τελευταίο αντίγραφο ασφαλείας.
