actions-add = Rnu
actions-blue-flag = Anay amidadi
actions-cancel = Sefsex
actions-choose = Fren
actions-close = Mdel
actions-copy = Nɣel
actions-custom-study = Tazrawt tudmawant
actions-decks = Ikemmusen
actions-delete = Kkes
actions-export = Sifeḍ
actions-filter = Sizdeg
actions-green-flag = Anay azegzaw
actions-help = Tallelt
actions-import = Kter
actions-manage = Sefrek...
actions-new = Rnu
actions-new-name = Isem amaynut:
actions-options = Iɣewwaṛen
actions-preview = Taskant
actions-rename = Beddel isem
actions-save = Sekles
actions-search = Nadi
actions-processing = Asesfer n { $val }
