adding-add-shortcut-ctrlandenter = הוספה (קיצור מקשים: ctrl+enter)
adding-added = נוספו
adding-discard-current-input = לסגור מבלי לשמור את התוכן הנוכחי?
adding-keep-editing = המשך עריכה
adding-edit = ערוך את "{ $val }"
adding-history = היסטוריה
adding-note-deleted = (רשומה נמחקה)
adding-shortcut = קיצור דרך: { $val }
adding-the-first-field-is-empty = השדה הראשון ריק.
adding-you-have-a-cloze-deletion-note = סוג הרשומה הוא השלמת החסר, אך אין שום חסר להשלמה. להמשיך?
adding-cloze-outside-cloze-notetype = ניתן להשתמש באפשרות השלם את החסר רק על רשומות מסוג השלם את החסר.
adding-cloze-outside-cloze-field = ניתן להשתמש בהשלם את החסר רק בשדות המשתמשים במסנן 'השלם את החסר:'. בדרך כלל זהו השדה הראשון.
