profiles-anki-could-not-read-your-profile = Anki לא הצליח לקרוא את נתוני הפרופיל שלך. ממדי החלון ופרטי התחברות הסנכרון שלך נשכחו.
profiles-anki-could-not-rename-your-profile = Anki לא הצליח לשנות את שם הפרופיל שלך בגלל שהוא לא הצליח לשנות את שם תיקיית הפרופיל על הדיסק. אנא וודא שיש לך הרשאת כתיבה ל-Documents/Anki ושום תוכנות אחרות לא ניגשות לתיקיות הפרופיל שלך, ולאחר מכן נסה שנית.
profiles-folder-already-exists = תיקייה כבר קיימת.
profiles-open = פתח
profiles-open-backup = פתח גיבוי...
profiles-please-remove-the-folder-and = מחק את התיקייה { $val } ונסה שוב.
profiles-profile-corrupt = הפרופיל פגום
profiles-profiles = פרופילים
profiles-quit = יציאה
profiles-user-1 = משתמש 1
profiles-confirm-lang-choice = האם אתה בטוח שברצונך להציג את הממשק של Anki בשפה ה{ $lang }?
profiles-could-not-create-data-folder = לא ניתן ליצור את תיקיית הנתונים, יש לוודא שהתיקייה אינה מוגדרת לקריאה בלבד. (מיקומי התיקיות מפורטים במדריך למשתמש).
profiles-prefs-corrupt-title = קובץ ההעדפות פגום
profiles-prefs-file-is-corrupt = הקובץ prefs21.db נמצא פגום ולכן נוצר מחדש. אם היו לכם מספר פרופילי משתמש, צרו אותם מחדש באותם השמות כדי לשחזר את הכרטיסים.
profiles-profile-does-not-exist = הפרופיל המבוקש לא נמצא.
profiles-creating-backup = יוצר גיבוי...
profiles-backup-created = הגיבוי נוצר בהצלחה.
profiles-backup-creation-failed = הגיבוי נכשל:{ $reason }
profiles-backup-unchanged = אין שינויים מהגיבוי האחרון.
