profiles-anki-could-not-read-your-profile = Az Ankinak nem sikerült beolvasnia a profiladataidat. A beállított ablakméretek és a szinkronizálás bejelentkezési adatai törlődtek.
profiles-anki-could-not-rename-your-profile = Az Anki nem tudta átnevezni a profilodat, mert a profil mappája nem nevezhető át a merevlemezen. Ellenőrizd, van-e írási jogosultságod a Documents/Anki mappához, és hogy más program használja-e a profilmappáidat, majd próbáld újra!
profiles-folder-already-exists = A mappa már létezik.
profiles-open = Megnyitás
profiles-open-backup = Biztonsági mentés megnyitása...
profiles-please-remove-the-folder-and = Töröld a(z) { $val } mappát, majd próbáld újra!
profiles-profile-corrupt = Sérült profil
profiles-profiles = Profilok
profiles-quit = Kilépés
profiles-user-1 = 1. felhasználó
profiles-confirm-lang-choice = Biztosan átállítod az Ankit { $lang } nyelvre?
profiles-could-not-create-data-folder = Adatmappa létrehozása sikertelen. Keresd fel a kézikönyv File Locations fejezetét, és győződj meg róla, hogy a célmappához van írási jogosultságod!
profiles-prefs-corrupt-title = Sérült hivatkozások
profiles-prefs-file-is-corrupt = Az Anki prefs21.db állománya sérült, és újra lett generálva. Amennyiben több profilt is használtál, add hozzá őket az eredeti nevükkel, hogy hozzáférj a kártyáidhoz.
profiles-profile-does-not-exist = A profil nem létezik.
profiles-creating-backup = Biztonsági mentés...
profiles-backup-created = Sikeres biztonsági mentés.
profiles-backup-creation-failed = Biztonsági mentés sikertelen: { $reason }
profiles-backup-unchanged = A legutóbbi biztonsági mentés óta nem történt változtatás.
