actions-add = Magdagdag
actions-all-selected = Napili lahat
actions-any-selected = Kahit alin sa napili
actions-cancel = I-cancel
actions-choose = Piliin
actions-close = Isara
actions-copy = I-copy
actions-create-copy = Gumawa ng copy
actions-custom-study = Custom Study
actions-decks = Mga Deck
actions-decrement-value = Halaga ng pagbabawas
actions-delete = I-delete
actions-export = I-export
actions-filter = I-filter
actions-help = Humingi ng tulong
actions-increment-value = Halaga ng pagdagdag
actions-import = I-import
actions-manage = Asikasuhin...
actions-name = Pangalan:
actions-new = Gumawa ng bago
actions-new-name = Pangalan ng bago:
actions-options = Mga Option
actions-options-for = Mga Option para sa
actions-preview = I-preview
actions-rebuild = I-rebuild
actions-rename = I-rename
actions-rename-deck = I-rename ang Deck
actions-rename-tag = I-rename ang Tag
actions-rename-with-parents = I-rename pati ang mga Parent
actions-remove-tag = Tanggalin ang Tag
actions-replay-audio = I-replay ang audio
actions-reposition = Baguhin ang puwesto
actions-save = I-save
actions-search = Mag-search
actions-select = Pumili
actions-shortcut-key = Pipindutin para sa shortcut:
actions-suspend-card = I-suspend ang card
actions-set-due-date = I-set ang Due Date
actions-answer-card = Sagutin ang card
actions-unbury-unsuspend = I-unbury o unsuspend ang card
actions-add-deck = Magdagdag ng Deck
actions-add-note = Magdagdag ng Note
actions-update-tag = I-update ang Tag
actions-update-note = I-update ang Note
actions-update-card = I-update ang Card
actions-update-deck = I-update ang Deck
actions-forget-card = Limutin ang Card
actions-build-filtered-deck = I-build ang Deck
actions-add-notetype = Magdagdag ng Notetype
actions-remove-notetype = Tanggalin ang Notetype
actions-update-notetype = I-update ang Notetype
actions-update-config = I-update ang Config
actions-card-info = Card Info
actions-previous-card-info = Info ng nakaraang card
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = ...
actions-currently-unsupported = Ang kilos na ito ay kasalukuyang hindi kaya ng sistema mo.

## Flags

actions-flag-number = Flag
actions-flag-red = Pula
actions-flag-orange = Kahel
actions-flag-green = Berde
actions-flag-blue = Asul
actions-flag-pink = Rosas
actions-flag-turquoise = Turquoise
actions-flag-purple = Lila
actions-set-flag = Mag-set ng Flag
actions-nothing-to-undo = Walang ia-undo
actions-nothing-to-redo = Walang ire-redo
actions-auto-advance = Auto Advance
actions-processing = Pinoproseso...
