editing-actual-size = I-toggle ang actual na laki
editing-add-media = Magdagdag ng media
editing-align-left = I-align sa kaliwa
editing-align-right = I-align sa kanan
editing-an-error-occurred-while-opening = Nagka-error habang binubuksan { $val }
editing-attach-picturesaudiovideo = Mag-attach ng mga retrato/audio/video
editing-bold-text = Bold na text
editing-cards = Mga Card
editing-center = Igitna
editing-change-color = Baguhin ang kulay
editing-cloze-deletion = Cloze deletion (bagong card)
editing-cloze-deletion-repeat = Cloze deletion (parehas na card)
editing-couldnt-record-audio-have-you-installed = Hindi maka-record ng audio. Na-install mo na ba ang 'lame'?
editing-customize-card-templates = I-customize ang mga Card Template
editing-customize-fields = I-customize ang mga Field
editing-cut = I-cut
editing-double-click-image = I-double click ang retrato
editing-double-click-to-expand = I-double-click para ma-expand
editing-double-click-to-collapse = I-double-click para ma-collapse
editing-edit-current = I-edit ang kasalukuyan
editing-edit-html = I-edit ang HTML
editing-fields = Mga Field
editing-float-left = Palutangin sa kaliwa
editing-float-right = Palutangin sa kanan
editing-float-none = Huwag ipalutang
editing-indent = Dagdagan ang indent
editing-italic-text = Italic na text
editing-jump-to-tags-with-ctrlandshiftandt = Laktawan ang mga tag gamit ang Ctrl+Shift+T
editing-justify = I-justify
editing-latex = LaTeX
editing-latex-equation = LaTex na equation
editing-latex-math-env = mathematical environment ng LaTeX
editing-mathjax-block = block ng MathJax
editing-mathjax-chemistry = kemistri ng MathJax
editing-mathjax-inline = inline ng MathJax
editing-mathjax-placeholder = Pindutin ang { $accept } para i-accept, at { $newline } para sa bagong line.
editing-media = Media
editing-ordered-list = Naka-order na listahan
editing-outdent = Bawasang ang indent
editing-paste = I-paste
editing-record-audio = Mag-record ng audio
editing-remove-formatting = Tanggalin ang formatting
editing-restore-original-size = I-restore ang orihinal na laki
editing-select-remove-formatting = Pumili ng formatting na tatanggalin
editing-show-duplicates = Ipakita ang mga duplicate
editing-subscript = Subscript
editing-superscript = Superscript
editing-tags = Mga Tag
editing-tags-add = Magdagdag ng tag
editing-tags-copy = Kopyahin ang mga tag
editing-tags-remove = Tanggalin ang mga tag
editing-tags-select-all = Piliin ang lahat ng mga tag
editing-text-color = Kulay ng text
editing-text-highlight-color = Kulay ng highlight ng text
editing-to-make-a-cloze-deletion-on = Para gumawa ng cloze deletion sa isang existing note, kailangan muna itong gawing cloze type, sa 'Notes>Change Note Type'
editing-toggle-html-editor = I-toggle ang HTML Editor
editing-toggle-visual-editor = I-toggle ang Visual na Editor
editing-toggle-sticky = I-toggle ang sticky
editing-expand = I-expand
editing-collapse = I-collapse
editing-expand-field = I-expand ang field
editing-collapse-field = I-collapse ang field
editing-underline-text = Salungguhitan ang text
editing-unordered-list = Listang hindi naka-order
editing-warning-cloze-deletions-will-not-work = Babala, hindi gagana ang cloze deletion hanggang i-switch sa Cloze ang type sa taas.
editing-mathjax-preview = Preview ng MathJax
editing-shrink-images = Paliitin ang mga retrato
editing-close-html-tags = Automatic na isara ang mga HTML tag
editing-from-clipboard = Mula sa Clipboard
editing-alignment = Pagkaka-align
editing-equations = Mga Equation

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Editor ng HTML
