editing-actual-size = In tatsächlicher Größe anzeigen/nicht anzeigen
editing-add-media = Medien hinzufügen
editing-align-left = Links ausrichten
editing-align-right = Rechts ausrichten
editing-an-error-occurred-while-opening = Beim Öffnen von { $val } ist ein Fehler aufgetreten
editing-attach-picturesaudiovideo = Bilder/Audio/Video anfügen
editing-bold-text = Fett ausgezeichneter Text
editing-cards = Karten
editing-center = Zentrieren
editing-change-color = Farbe ändern
editing-cloze-deletion = Lückentext (neue Karte)
editing-cloze-deletion-repeat = Lückentext (selbe Karte)
editing-copy-image = Bild kopieren
editing-couldnt-record-audio-have-you-installed = Die Audioaufnahme konnte nicht durchgeführt werden. Haben Sie die Software 'lame' installiert?
editing-customize-card-templates = Kartenvorlagen anpassen
editing-customize-fields = Felder anpassen
editing-cut = Ausschneiden
editing-double-click-image = Bild doppelklicken
editing-double-click-to-expand = (zum Erweitern doppelklicken)
editing-double-click-to-collapse = Zum Einklappen doppelklicken
editing-edit-current = Angezeigte Karte bearbeiten
editing-edit-html = HTML eingeben
editing-fields = Felder
editing-float-left = Nach links gleiten
editing-float-right = Nach rechts gleiten
editing-float-none = Nicht gleiten
editing-indent = Einrückung vergrößern
editing-italic-text = Kursiver Text
editing-jump-to-tags-with-ctrlandshiftandt = Mit Strg+Umschalt+T zu den Schlagwörtern springen
editing-justify = Blocktext
editing-latex = LaTeX
editing-latex-equation = LaTeX-Formel
editing-latex-math-env = LaTeX-Mathematikumgebung
editing-mathjax-block = Abgesetzes MathJax-Element
editing-mathjax-chemistry = MathJax-Chemieformel
editing-mathjax-inline = Inzeiliges MathJax-Element
editing-mathjax-placeholder = Zum Akzeptieren { $accept } drücken, für eine neue Zeile { $newline } drücken
editing-media = Medien
editing-open-image = Bild öffnen
editing-show-in-folder = Im Ordner anzeigen
editing-ordered-list = Geordnete Liste
editing-outdent = Einrückung verringern
editing-paste = Einfügen
editing-record-audio = Audio aufnehmen
editing-remove-formatting = Formatierung löschen
editing-restore-original-size = Originalgröße wiederherstellen
editing-select-remove-formatting = Zu löschende Formatierung auswählen
editing-show-duplicates = Duplikate anzeigen
editing-subscript = Tiefstellen
editing-superscript = Hochstellen
editing-tags = Schlagwörter
editing-tags-add = Schlagwort hinzufügen
editing-tags-copy = Schlagwörter kopieren
editing-tags-remove = Schlagwörter entfernen
editing-tags-select-all = Alle Schlagwörter auswählen
editing-text-color = Textfarbe
editing-text-highlight-color = Texthervorhebungsfarbe
editing-to-make-a-cloze-deletion-on = Um einen Lückentext zu einer bereits vorhandenen Notiz hinzuzufügen, muss dieser erst der Notiztyp Lückentext zugewiesen werden. Dazu wählen Sie oben links in diesem Menü: 'Bearbeiten > Notiztyp ändern'
editing-toggle-html-editor = HTML-Editor ein-/ausschalten
editing-toggle-visual-editor = Optischen Editor ein-/ausschalten
editing-toggle-sticky = Beibehalten ein-/ausschalten
editing-expand = Ausklappen
editing-collapse = Einklappen
editing-expand-field = Feld ausklappen
editing-collapse-field = Feld einklappen
editing-underline-text = Text unterstreichen
editing-unordered-list = Ungeordnete Liste
editing-warning-cloze-deletions-will-not-work = Achtung! Lückentext wird nur korrekt angezeigt, wenn oben als Notiztyp »Lückentext« gewählt wird.
editing-mathjax-preview = MathJax-Vorschau
editing-shrink-images = Bilder verkleinern
editing-close-html-tags = HTML-Tags automatisch schließen
editing-from-clipboard = Aus der Zwischenablage
editing-alignment = Ausrichtung
editing-equations = Gleichungen
editing-no-image-found-on-clipboard = Kein Bild in der Zwischenablage gefunden
editing-image-occlusion-mode = Bildverdeckungsmodus
editing-image-occlusion-zoom-out = Herauszoomen
editing-image-occlusion-zoom-in = Hineinzoomen
editing-image-occlusion-zoom-reset = Zoom zurücksetzen
editing-image-occlusion-toggle-translucent = Transparenz ein-/ausschalten
editing-image-occlusion-delete = Löschen
editing-image-occlusion-duplicate = Duplizieren
editing-image-occlusion-group = Gruppieren
editing-image-occlusion-ungroup = Gruppierung aufheben
editing-image-occlusion-select-all = Alle auswählen
editing-image-occlusion-alignment = Ausrichtung
editing-image-occlusion-align-left = Links ausrichten
editing-image-occlusion-align-h-center = Horizontal zentrieren
editing-image-occlusion-align-right = Rechts ausrichten
editing-image-occlusion-align-top = Oben ausrichten
editing-image-occlusion-align-v-center = Vertikal zentrieren
editing-image-occlusion-align-bottom = Unten ausrichten
editing-image-occlusion-select-tool = Auswählen
editing-image-occlusion-zoom-tool = Zoom
editing-image-occlusion-rectangle-tool = Rechteck
editing-image-occlusion-ellipse-tool = Ellipse
editing-image-occlusion-polygon-tool = Vieleck
editing-image-occlusion-text-tool = Text
editing-image-occlusion-fill-tool = Mit Farbe füllen
editing-image-occlusion-toggle-mask-editor = Maskeneditor ein-/ausschalten
editing-image-occlusion-reset = Bildverdeckung zurücksetzen
editing-image-occlusion-confirm-reset = Sind Sie sicher, dass Sie diese Bildverdeckung zurücksetzen wollen?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML-Editor
