profiles-anki-could-not-read-your-profile = Anki kann Benutzerprofil nicht lesen. Persönliche Einstellungen wurden nicht übernommen.
profiles-anki-could-not-rename-your-profile = Anki konnte Ihr Benutzerprofil nicht umbenennen, weil es den Benutzerprofilordner nicht umbenennen konnte. Bitte stellen Sie sicher, dass sie Schreibberechtigung auf Dokumente/Anki haben und kein anderes Programm auf Ihren Benutzerprofilordner zugreift und versuchen Sie es dann erneut.
profiles-folder-already-exists = Der Ordner existiert bereits.
profiles-open = &Öffnen
profiles-open-backup = Sicherungskopie öffnen …
profiles-please-remove-the-folder-and = Bitte den Ordner { $val } löschen und erneut versuchen.
profiles-profile-corrupt = Benutzerprofil defekt
profiles-profiles = Benutzerprofile
profiles-quit = Beenden
profiles-user-1 = Benutzer 1
profiles-confirm-lang-choice = Sind Sie sich sicher, dass Sie die Benutzeroberfläche von Anki in { $lang } anzeigen möchten?
profiles-could-not-create-data-folder = Anki konnte seinen Datenordner nicht erstellen. Bitte schlagen Sie in dem Abschnitt für Dateispeicherorte im Handbuch nach und stellen Sie sicher, dass auf den Speicherort auch mit Schreibberechtigung zugegriffen werden kann.
profiles-prefs-corrupt-title = Einstellungen fehlerhaft
profiles-prefs-file-is-corrupt = Die Anki-Datei pref21.db war fehlerhaft und wurde neu erstellt. Wenn Sie mehrere Benutzerprofile verwendet haben, dann fügen Sie diese bitte wieder mit den gleichen Namen zu, um Ihre Karten wiederherzustellen.
profiles-profile-does-not-exist = Das angeforderte Benutzerprofil existiert nicht.
profiles-creating-backup = Sicherungskopie wird erstellt …
profiles-backup-created = Sicherungskopie wurde erstellt.
profiles-backup-creation-failed = Erstellung der Sicherungskopie fehlgeschlagen: { $reason }
profiles-backup-unchanged = Keine Änderungen seit der letzten Sicherungskopie.
