card-stats-added = Lisätty
card-stats-first-review = Ensimmäinen kertaus
card-stats-latest-review = Viimeisin kertaus
card-stats-interval = Kertausväli
card-stats-ease = Helppous
card-stats-review-count = Kertaukset
card-stats-lapse-count = Virheet
card-stats-average-time = Vastausnopeus
card-stats-total-time = Kokonaisaika
card-stats-new-card-position = Sijainti
card-stats-card-template = Kortin tyyppi
card-stats-note-type = Muistiinpanotyyppi
card-stats-deck-name = Pakka
card-stats-preset = Esiasetus
card-stats-note-id = Muistiinpanon tunnus
card-stats-card-id = Kortin tunnus
card-stats-review-log-rating = Luokitus
card-stats-review-log-type = Tyyppi
card-stats-review-log-date = Päivämäärä
card-stats-review-log-time-taken = Aika
card-stats-review-log-type-learn = Opittavat
card-stats-review-log-type-review = Kertaus
card-stats-review-log-type-relearn = Uudelleen opittavat
card-stats-review-log-type-filtered = Suodatetut
card-stats-review-log-type-manual = Manuaalinen
card-stats-review-log-type-rescheduled = Ajastettu uudelleen
card-stats-review-log-elapsed-time = Kulunut aika
card-stats-no-card = (Ei näytettävää korttia.)
card-stats-custom-data = Mukautettu data
card-stats-fsrs-stability = Vakaus
card-stats-fsrs-difficulty = Vaikeus
card-stats-fsrs-retrievability = Palautettavuus
card-stats-fsrs-forgetting-curve-title = Unohtamiskäyrä
card-stats-fsrs-forgetting-curve-first-week = Ensimmäinen viikko
card-stats-fsrs-forgetting-curve-first-month = Ensimmäinen kuukausi
card-stats-fsrs-forgetting-curve-first-year = Ensimmäinen vuosi
card-stats-fsrs-forgetting-curve-all-time = Koko aika
card-stats-fsrs-forgetting-curve-probability-of-recalling = Muistamisen todennäköisyys
card-stats-fsrs-forgetting-curve-desired-retention = Toivottu retentio

## Window Titles

card-stats-current-card = Nykyinen kortti ({ $context })
card-stats-previous-card = Edellinen kortti ({ $context })
