editing-actual-size = Näytä/piilota todellinen koko
editing-add-media = Lisää mediatiedosto
editing-align-left = Tasaa vasemmalle
editing-align-right = Tasaa oikealle
editing-an-error-occurred-while-opening = Kohdetta { $val } avattaessa tapahtui virhe
editing-attach-picturesaudiovideo = Liitä kuvia/ääntä/videota
editing-bold-text = Lihavoitu teksti
editing-cards = Kortit
editing-center = Keskitä
editing-change-color = Muuta väriä
editing-cloze-deletion = Aukkotehtävä (uuteen korttiin)
editing-cloze-deletion-repeat = Aukkotehtävä (samaan korttiin)
editing-copy-image = Kopioi kuva
editing-couldnt-record-audio-have-you-installed = Äänen tallennus ei onnistunut. Oletko asentanut 'lame'-kirjaston?
editing-customize-card-templates = Mukauta korttimalleja
editing-customize-fields = Mukauta kenttiä
editing-cut = Leikkaa
editing-double-click-image = kaksoisnapsauta kuvaa
editing-double-click-to-expand = (laajenna kaksoisnapsauttamalla)
editing-double-click-to-collapse = pienennä kaksoisnapsauttamalla
editing-edit-current = Muokkaa nykyistä
editing-edit-html = Muokkaa HTML:ää
editing-fields = Kentät
editing-float-left = Kelluta vasemmalle
editing-float-right = Kelluta oikealle
editing-float-none = Ei kellutusta
editing-indent = Kasvata sisennystä
editing-italic-text = Kursivoitu teksti
editing-jump-to-tags-with-ctrlandshiftandt = Siirry tunnisteisiin painamalla Ctrl+Shift+T
editing-justify = Tasaa reunoihin
editing-latex = LaTeX
editing-latex-equation = LaTeX-yhtälö
editing-latex-math-env = LaTeX matem. ympär.
editing-mathjax-block = MathJax-lohko
editing-mathjax-chemistry = MathJax -kemian kaava
editing-mathjax-inline = Rivinsisäinen MathJax
editing-mathjax-placeholder = Hyväksy painamalla { $accept }, luo uusi rivi painamalla { $newline }.
editing-media = Mediatiedostot
editing-open-image = Avaa kuva
editing-show-in-folder = Näytä kansiossa
editing-ordered-list = Numeroitu luettelo
editing-outdent = Vähennä sisennystä
editing-paste = Liitä
editing-record-audio = Tallenna ääntä
editing-remove-formatting = Poista muotoilu
editing-restore-original-size = Palauta alkuperäinen koko
editing-select-remove-formatting = Valitse poistettava muotoilu
editing-show-duplicates = Näytä kaksoiskappaleet
editing-subscript = Alaindeksi
editing-superscript = Yläindeksi
editing-tags = Tunnisteet
editing-tags-add = Lisää tunniste
editing-tags-copy = Kopioi tunnisteet
editing-tags-remove = Poista tunnisteet
editing-tags-select-all = Valitse kaikki tunnisteet
editing-text-color = Tekstin väri
editing-text-highlight-color = Tekstin korostusväri
editing-to-make-a-cloze-deletion-on = Voidaksesi tehdä aukkotehtävän olemassa olevasta muistiinpanosta, sinun täytyy ensin muuttaa se aukkotehtävätyypiksi: Muokkaa>Vaihda muistiinpanotyyppiä
editing-toggle-html-editor = Näytä/piilota HTML-muokkausnäkymä
editing-toggle-visual-editor = Näytä/piilota visuaalinen muokkausnäkymä
editing-toggle-sticky = Tarttuminen päälle/pois
editing-expand = Laajenna
editing-collapse = Supista
editing-expand-field = Laajenna kenttä
editing-collapse-field = Pienennä kenttä
editing-underline-text = Alleviivattu teksti
editing-unordered-list = Numeroimaton luettelo
editing-warning-cloze-deletions-will-not-work = Varoitus: aukkotehtävät eivät toimi ennen kun vaihdat tyypin ylhäältä aukkotehtäväksi.
editing-mathjax-preview = MathJax-esikatselu
editing-shrink-images = Kutista kuvatiedostot
editing-close-html-tags = Sulje HTML-tägit automaattisesti
editing-from-clipboard = Leikepöydältä
editing-alignment = Tasaus
editing-equations = Yhtälöt
editing-no-image-found-on-clipboard = Leikepöydältä ei löytynyt kuvaa.
editing-image-occlusion-mode = Kuvan peittämistila
editing-image-occlusion-zoom-out = Loitonna
editing-image-occlusion-zoom-in = Lähennä
editing-image-occlusion-zoom-reset = Nollaa zoomaus
editing-image-occlusion-toggle-translucent = Läpinäkyvyys päälle/pois
editing-image-occlusion-delete = Poista
editing-image-occlusion-duplicate = Monista
editing-image-occlusion-group = Ryhmitä valinta
editing-image-occlusion-ungroup = Poista valinnan ryhmitys
editing-image-occlusion-select-all = Valitse kaikki
editing-image-occlusion-alignment = Tasaus
editing-image-occlusion-align-left = Tasaa vasemalle
editing-image-occlusion-align-h-center = Keskitä vaakasuunnassa
editing-image-occlusion-align-right = Tasaa oikealle
editing-image-occlusion-align-top = Tasaa ylös
editing-image-occlusion-align-v-center = Keskitä pystysuunnassa
editing-image-occlusion-align-bottom = Tasaa alas
editing-image-occlusion-select-tool = Valitse
editing-image-occlusion-zoom-tool = Zoomaa
editing-image-occlusion-rectangle-tool = Suorakulmio
editing-image-occlusion-ellipse-tool = Soikio
editing-image-occlusion-polygon-tool = Monikulmio
editing-image-occlusion-text-tool = Teksti
editing-image-occlusion-fill-tool = Täytä värillä
editing-image-occlusion-toggle-mask-editor = Näytä/piilota maskien muokkausnäkymä
editing-image-occlusion-reset = Nollaa kuvan peite
editing-image-occlusion-confirm-reset = Haluatko varmasti nollata tämän kuvan peitteen?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML-muokkain
