name: anki-woodrow
base: core18
version: '2.1.14+master'
version-script: |
  echo $SNAPCRAFT_PROJECT_VERSION-commit.$(git rev-parse --short HEAD)
summary: Anki is a friendly, intelligent spaced learning system.
description: |
  Anki is a program which makes remembering things easy. Because it's a lot
  more efficient than traditional study methods, you can either greatly
  decrease your time spent studying, or greatly increase the amount you learn.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
    run-on: [amd64]

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /etc/asound.conf:
    bind-file: $SNAP/etc/alsa.conf
  /usr/share/alsa/alsa.conf:
    bind-file: $SNAP/usr/share/alsa/alsa.conf

apps:
  anki:
    adapter: full
    command: bin/runanki
    command-chain:
      - bin/desktop-launch
    desktop: anki.desktop
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - network
      - home
      - browser-support
      - pulseaudio
      - opengl
      - unity7
    environment:
      LC_ALL: C.UTF-8
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/samba/
      QTWEBENGINEPROCESS_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt5/libexec/QtWebEngineProcess

parts:
  # Remote part for support of various desktop technologies
  # Refer: https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt

    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
    - build-essential
    - qtbase5-dev
    - dpkg-dev
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libqt5gui5
    - libgdk-pixbuf2.0-0
    - libqt5svg5 # for loading icon themes which are svg
    - try: [appmenu-qt5] # not available on core18
    - locales-all
    - xdg-user-dirs
    - fcitx-frontend-qt5

  alsa:
    plugin: nil
    source: https://github.com/diddledan/snapcraft-alsa.git
    override-pull: |
      cat > alsa.conf <<EOF
      pcm.!default {
        type pulse
        fallback "sysdefault"
        hint {
          show on
          description "Default ALSA Output (currently PulseAudio Sound Server)"
        }
      }
      ctl.!default {
        type pulse
        fallback "sysdefault"
      }
      EOF
    override-build: |
      install -m644 -D -t $SNAPCRAFT_PART_INSTALL/etc alsa.conf
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins

  anki:
    plugin: python
    python-version: python3
    source: .
    after: [desktop-qt5, alsa]
    build-packages:
      - python3
      - python3-pyqt5
      - pyqt5-dev-tools
      - portaudio19-dev
      - bzr
      - gettext
    override-build: |
      snapcraftctl build
      ./tools/build_ui.sh
      cd ..
      bzr branch lp:anki i18n
      mv build dtop
      cd i18n
      ./update-mos.sh
      cd ..
      mv dtop build
    stage-packages:
      - python3
      - python3-pyqt5
      - python3-pyqt5.qtwebengine
      - libportaudio2
      - libgtk-3-0
      - libglu1-mesa
      - libxtst6
      - libnss3
      - libnspr4
      - mpv
      - lame
      - locales
      - libc-bin
      - libxcomposite1
      - libcairo-gobject2
      - libepoxy0
      - libatspi2.0-0
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libbluray2
      - libslang2
      - samba-libs
      - execstack
    override-prime: |
      snapcraftctl prime

      cp -r $SNAPCRAFT_PART_BUILD/aqt/forms lib/python3.6/site-packages/aqt/
      cp -r $SNAPCRAFT_PART_BUILD/locale lib/python3.6/site-packages/
      cp anki.* lib/python3.6/site-packages/
      cp -r designer lib/python3.6/site-packages/
      cp -r web lib/python3.6/site-packages/
      # Workaround
      cp -r usr/share/qt5/resources/* usr/bin
      cp -r usr/share/qt5/resources/* usr/lib/x86_64-linux-gnu/qt5/libexec
      cp -r usr/share/qt5/translations/qtwebengine_locales usr/bin
      cp -r usr/share/qt5/translations/qtwebengine_locales usr/lib/x86_64-linux-gnu/qt5/libexec/qtwebengine_locales
      execstack --clear-execstack usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5.9.5
      sed -i -E 's|Icon=anki|Icon=anki.png|' anki.desktop

