qt-accel-about = &Acerca de...
qt-accel-about-mac = Acerca de Anki
qt-accel-cards = &Tarjetas
qt-accel-check-database = Comprobar base de datos
qt-accel-check-media = Comprobar &multimedia...
qt-accel-edit = &Editar
qt-accel-exit = S&alir
qt-accel-export = &Exportar...
qt-accel-export-notes = &Exportar Notas...
qt-accel-file = &Archivo
qt-accel-filter = Fil&trar
qt-accel-find = &Buscar
qt-accel-find-and-replace = Buscar y re&emplazar...
qt-accel-find-duplicates = Buscar &duplicadas...
qt-accel-go = &Ir
qt-accel-guide = &Guía...
qt-accel-help = &Ayuda
qt-accel-import = &Importar...
qt-accel-info = &Info...
qt-accel-invert-selection = &Invertir selección
qt-accel-next-card = &Siguiente tarjeta
qt-accel-note = N&ota
qt-accel-notes = &Notas
qt-accel-preferences = &Preferencias...
qt-accel-previous-card = &Tarjeta anterior
qt-accel-select-all = Seleccionar &todo
qt-accel-select-notes = Seleccionar &notas
qt-accel-support-anki = &Apoyar Anki...
qt-accel-switch-profile = Cambiar perfil
qt-accel-tools = &Herramientas
qt-accel-undo = &Deshacer
qt-accel-redo = &Listo
qt-accel-set-due-date = Establecer &fecha de vencimiento...
qt-accel-forget = &Olvidar
qt-accel-view = &Visualización
qt-accel-full-screen = Alternar &Pantalla completa
qt-accel-layout = &Diseño
qt-accel-layout-auto = &Automático
qt-accel-layout-vertical = &Vertical
qt-accel-layout-horizontal = &Horizontal
qt-accel-zoom-in = &Ampliar Zoom
qt-accel-zoom-out = &Reducir Zoom
qt-accel-reset-zoom = &Restablecer Zoom
qt-accel-toggle-sidebar = Activar o desactivar la barra lateral
qt-accel-zoom-editor-in = &Ampliar Zoom del editor
qt-accel-zoom-editor-out = &Reducir Zoom del editor
qt-accel-create-backup = Crear una copia de seguridad
qt-accel-load-backup = &Restaurar una copia de seguridad
qt-accel-upgrade-downgrade = Actualizar/Desactualizar
