qt-accel-about = &Sobre
qt-accel-about-mac = Sobre o Anki..
qt-accel-cards = &Cartões
qt-accel-check-database = Verificar Banco de &Dados
qt-accel-check-media = Verificar &Mídia
qt-accel-edit = &Editar
qt-accel-exit = &Sair
qt-accel-export = &Exportar...
qt-accel-export-notes = &Exportar Notas...
qt-accel-file = &Arquivo
qt-accel-filter = &Filtrar
qt-accel-find = &Localizar
qt-accel-find-and-replace = Achar e &Substituir...
qt-accel-find-duplicates = Encontrar &Duplicadas...
qt-accel-go = &Ir
qt-accel-guide = &Guia
qt-accel-help = A&juda
qt-accel-import = &Importar...
qt-accel-info = &Informação...
qt-accel-invert-selection = &Inverter seleção
qt-accel-next-card = &Próximo Cartão
qt-accel-note = N&ota
qt-accel-notes = &Notas
qt-accel-preferences = &Preferências
qt-accel-previous-card = Cartão &Anterior
qt-accel-select-all = Selecionar &tudo
qt-accel-select-notes = Selecionar &notas
qt-accel-support-anki = &Contribua com o Anki
qt-accel-switch-profile = Mudar &perfil
qt-accel-tools = &Ferramentas
qt-accel-undo = &Desfazer
qt-accel-redo = &Refazer
qt-accel-set-due-date = Definir &Data de Revisão...
qt-accel-forget = &Esquecer
qt-accel-view = &Exibir
qt-accel-full-screen = Tela Cheia
qt-accel-layout = Layout
qt-accel-layout-auto = Auto
qt-accel-layout-vertical = &Vertical
qt-accel-layout-horizontal = &Horizontal
qt-accel-zoom-in = &Ampliar Zoom
qt-accel-zoom-out = &Reduzir Zoom
qt-accel-reset-zoom = &Redefinir Zoom
qt-accel-toggle-sidebar = Exibir/ocultar barra lateral
qt-accel-zoom-editor-in = &Ampliar Zoom (Editor)
qt-accel-zoom-editor-out = &Reduzir Zoom (Editor)
qt-accel-create-backup = Criar &Backup
qt-accel-load-backup = &Reverter para Backup
qt-accel-upgrade-downgrade = Atualizar / Voltar versão
