#!/bin/bash

set -e

STATE=$(pwd)/../state/anki-ci
mkdir -p $STATE

echo "+++ Building and testing"
ln -sf out/node_modules .
SKIP_RUNNER_BUILD=0 BUILD_ROOT=$STATE/build ./ninja pylib qt wheels check
