## Progress info

database-check-rebuilding = Дахин барьж байна...
database-check-checking-cards = Картуудыг шалгаж байна...
database-check-checking-notes = Тэмдэглэлүүдийг шалгаж байна...
database-check-checking-history = Түүхийг шалгаж байна...
database-check-title = Өгөгдлийн санг шалгах
