importing-failed = Import ebaõnnestus.
importing-aborted = Katkestatud: { $val }
importing-allow-html-in-fields = Luba väljadel HTML
importing-by-default-anki-will-detect-the = Anki tuvastab vaikimisi selle märgi,mida kasutatakse väljade vahe nagu näiteks tabulaatori, koma jne. Kui Anki tuvastab selle märgi valesti, saad selle sisestada siin. Kasuta tabulaatori jaoks kombinatsiooni: \t
importing-change = Muuda
importing-field-mapping = Väljade vastendus
importing-field-of-file-is = Selle faili <b>{ $val }.</b> väli on:
importing-ignored = <eiratud>
importing-import-options = Importimise suvandid
importing-map-to = Liida väljadele { $val }
importing-map-to-tags = Liida märksõnadega
importing-mapped-to = liidetud väljadele <b>{ $val }</b>-ga
importing-mapped-to-tags = liidetud <b>siltidega</b>
importing-rows-had-num1d-fields-expected-num2d = '{ $row }' omasid { $found } välja, väljaarvatud { $expected }
importing-supermemo-xml-export-xml = Supermemo XML eksport (*.xml)
importing-added = Lisatud
