profiles-anki-could-not-read-your-profile = Anki ne povis legi datumojn de via profilo. Grandoj de fenestroj kaj viaj ensalutaj detaloj pri samtempigo estis forgesitaj.
profiles-anki-could-not-rename-your-profile = Anki ne povis alinomi vian profilon, ĉar ĝi ne povis alinomi vian profil-dosierujon sur la disko. Certiĝu, ĉu vi havas skriborajton al la dosierujo Documents/Anki kaj neniu alia programo atingas vian profil-dosierujon, kaj sekve reprovu.
profiles-folder-already-exists = La dosierujo jam ekzistas.
profiles-open = Malfermi
profiles-open-backup = Malfermi sekurkopion…
profiles-please-remove-the-folder-and = Forigu la dosierujon { $val } kaj reprovu.
profiles-profile-corrupt = Profilo difektita
profiles-profiles = Profiloj
profiles-quit = Forlasi
profiles-user-1 = 1-a uzanto
profiles-confirm-lang-choice = Ĉu vi certe volas vidigi fasadon de Anki en la lingvo { $lang }?
profiles-could-not-create-data-folder = Anki ne povis krei sian datum-dosierujon. Legu la ĉapitron “Administri datumojn kaj vian kolekton” en la gvidlibro kaj certiĝu, ke tiu dosierujo ne estas nurlega.
profiles-prefs-corrupt-title = Preferoj difektitaj
profiles-prefs-file-is-corrupt = La dosiero prefs21.db estas difektita kaj estis rekreita. Se vi uzis plurajn profilojn, realdonu ilin kun la samaj nomoj por restarigi viajn kartojn.
profiles-profile-does-not-exist = Postulata profilo ne ekzistas.
profiles-creating-backup = Kreado de sekurkopio…
profiles-backup-created = Kreis sekurkopion.
profiles-backup-creation-failed = Malsukcesis krei sekurkopion: { $reason }
profiles-backup-unchanged = Neniu ŝanĝo ekde la antaŭa sekurkopio.
