qt-accel-about = &O Anki...
qt-accel-about-mac = O Anki...
qt-accel-cards = &Karty
qt-accel-check-database = &Zkontrolovat databázi
qt-accel-check-media = Zkontrolovat &multimédia...
qt-accel-edit = &Upravit
qt-accel-exit = U&končit
qt-accel-export = &Exportovat...
qt-accel-export-notes = &Exportovat poznámky...
qt-accel-file = &Soubor
qt-accel-filter = Fil&tr
qt-accel-find = &Najít
qt-accel-find-and-replace = Najít a na&hradit...
qt-accel-find-duplicates = Najít &duplikáty...
qt-accel-go = &Jdi na
qt-accel-guide = &Příručka...
qt-accel-help = &Nápověda
qt-accel-import = &Importovat...
qt-accel-info = &Info...
qt-accel-invert-selection = &Invertovat výběr
qt-accel-next-card = &Následující karta
qt-accel-note = Poz&námky
qt-accel-notes = Poz&námky
qt-accel-preferences = &Předvolby...
qt-accel-previous-card = &Předchozí karta
qt-accel-select-all = Vybrat &vše
qt-accel-select-notes = Vybrat poz&námky
qt-accel-support-anki = Podpořte &Anki...
qt-accel-switch-profile = &Přepnout profil
qt-accel-tools = Nás&troje
qt-accel-undo = &Zpět
qt-accel-redo = Zn&ovu
qt-accel-set-due-date = Nastavit &datum zkoušení...
qt-accel-forget = Za&pomenout
qt-accel-view = &Zobrazit
qt-accel-full-screen = &Celá obrazovka
qt-accel-layout = Roz&ložení
qt-accel-layout-auto = &Automaticky
qt-accel-layout-vertical = &Vertikální
qt-accel-layout-horizontal = &Horizontální
qt-accel-zoom-in = &Přiblížit
qt-accel-zoom-out = &Oddálit
qt-accel-reset-zoom = &Resetovat přiblížení
qt-accel-toggle-sidebar = Přepnout postranní panel
qt-accel-zoom-editor-in = &Přiblížit editor
qt-accel-zoom-editor-out = &Oddálit editor
qt-accel-create-backup = &Vytvořit zálohu
qt-accel-load-backup = &Obnovit ze zálohy
qt-accel-upgrade-downgrade = Upgradovat/Downgradovat
