actions-add = ଯୋଡ଼ନ୍ତୁ
actions-all-selected = ସମସ୍ତ ମନୋନୀତ
actions-any-selected = ଯେକୌଣସି ମନୋନୀତ
actions-cancel = ବାତିଲ୍ କର
actions-choose = ବାଛନ୍ତୁ
actions-close = ବନ୍ଦ କରନ୍ତୁ
actions-copy = ନକଲ କରନ୍ତୁ
actions-create-copy = ନକଲ ତିଆରି କରନ୍ତୁ
actions-custom-study = କଷ୍ଟମ୍ ଅଧ୍ୟୟନ
actions-decks = ଡେକଗୁଡ଼ିକ
actions-decrement-value = ମୂଲ୍ୟ ହ୍ରାସ କରିବା
actions-delete = ଅପସାରଣ କରନ୍ତୁ
actions-export = ରପ୍ତାନି
actions-filter = ଶୋଧନ କରନ୍ତୁ
actions-help = ସହାୟତା
actions-increment-value = ମୂଲ୍ୟ ଵୃଦ୍ଧି କରିବା
actions-import = ଆମଦାନୀ
actions-manage = ପରିଚାଳନା କରନ୍ତୁ...
actions-name = ନାମ:
actions-new = ନୂତନ
actions-new-name = ନୂତନ ନାମ:
actions-options = ବିକଳ୍ପଗୁଡ଼ିକ
actions-options-for = { $val } ପାଇଁ ବିକଳ୍ପଗୁଡ଼ିକ
actions-preview = ପୂର୍ଵାଵଲୋକନ
actions-rebuild = ପୁନଃନିର୍ମାଣ
actions-rename = ନାମ ବଦଳାନ୍ତୁ
actions-rename-deck = ଡେକ୍ ନାମ ବଦଳାନ୍ତୁ
actions-rename-tag = ଟ୍ୟାଗ୍ ର ନାମ ବଦଳାନ୍ତୁ
actions-rename-with-parents = ଶ୍ରେଣୀ ସହିତ ନାମ ପରିବର୍ତ୍ତନ କରନ୍ତୁ
actions-remove-tag = ଟ୍ୟାଗ୍ ଅପସାରଣ କରନ୍ତୁ
actions-replay-audio = ଅଡିଓ ପୁଣି ଚଲାନ୍ତୁ
actions-reposition = ରିପୋଜିସନ୍ କର
actions-save = ସଞ୍ଚୟ
actions-search = ଖୋଜନ୍ତୁ
actions-select = ଚୟନ କରନ୍ତୁ
actions-shortcut-key = Shortcut key: { $val }
actions-suspend-card = ପତ୍ର ନିଲମ୍ବିତ କରନ୍ତୁ
actions-set-due-date = ଧାର୍ଯ୍ୟ ତାରିଖ ସେଟ୍ କରନ୍ତୁ
actions-answer-card = ଉତ୍ତର ପତ୍ର
actions-unbury-unsuspend = ସ୍ଥଗିତରୁ ଫେରାଇ ଆଣ/ଅନିଲମ୍ବିତ କରନ୍ତୁ
actions-add-deck = ଡେକ୍ ଯୋଡ଼ନ୍ତୁ
actions-add-note = ନୋଟ୍ ଯୋଡ଼ନ୍ତୁ
actions-update-tag = ଟ୍ୟାଗ୍ ଅଦ୍ୟତନ କରନ୍ତୁ
actions-update-note = ନୋଟ୍ ଅଦ୍ୟତନ କରନ୍ତୁ
actions-update-card = ପତ୍ର ଅଦ୍ୟତନ କରନ୍ତୁ
actions-update-deck = ଡେକ୍ ଅଦ୍ୟତନ କରନ୍ତୁ
actions-forget-card = ପତ୍ରଟିକୁ ଭୁଲିଯାଅ
actions-build-filtered-deck = ଡେକ୍ ନିର୍ମାଣ କରନ୍ତୁ
actions-add-notetype = ନୋଟ୍-ପ୍ରକାର ଯୋଡ଼ନ୍ତୁ
actions-remove-notetype = ନୋଟ୍-ପ୍ରକାର ଅପସାରଣ କରନ୍ତୁ
actions-update-notetype = ନୋଟ୍-ପ୍ରକାର ଅଦ୍ୟତନ କରନ୍ତୁ
actions-update-config = ବିନ୍ୟାସ ଅଦ୍ୟତନ କରନ୍ତୁ
actions-card-info = ପତ୍ର ସୂଚନା
actions-previous-card-info = ପୂର୍ବବର୍ତ୍ତୀ ପତ୍ର ସୂଚନା
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = ଏହି କାର୍ଯ୍ୟ ବର୍ତ୍ତମାନ ଆପଣଙ୍କ ସିଷ୍ଟମରେ ସମର୍ଥିତ ନୁହେଁ।

## Flags

actions-flag-number = ପତାକା { $number }
actions-flag-red = ନାଲି
actions-flag-orange = କମଳା
actions-flag-green = ସବୁଜ
actions-flag-blue = ନୀଳ
actions-flag-pink = ଗୋଲାପୀ
actions-flag-turquoise = ଫୀରୋଜା
actions-flag-purple = ବାଇଗଣୀ
actions-set-flag = ପତାକା ନ୍ୟସ୍ତ କରନ୍ତୁ
actions-nothing-to-undo = ପୂର୍ବବତ୍ କରିବା ପାଇଁ କିଛି ନାହିଁ
actions-nothing-to-redo = ପୁନଃକରଣ କରିବା ପାଇଁ କିଛି ନାହିଁ
actions-processing = ପ୍ରକ୍ରିୟାରତ...
