editing-actual-size = ପ୍ରକୃତ ଆକାର ଟୋଗଲ୍ କର
editing-add-media = ମିଡ଼ିଆ ଯୋଡ଼ନ୍ତୁ
editing-align-left = ବାମକୁ ଶ୍ରେଣୀବଦ୍ଧ କର
editing-align-right = ଡାହାଣକୁ ଶ୍ରେଣୀବଦ୍ଧ କର
editing-an-error-occurred-while-opening = { $val } ଖୋଲିବା ସମୟରେ ଏକ ତ୍ରୁଟି ଘଟିଛି
editing-attach-picturesaudiovideo = ପ୍ରତିଛବି/ଅଡ଼ିଓ/ଭିଡ଼ିଓ ସଂଲଗ୍ନ କରନ୍ତୁ
editing-cards = ପତ୍ରଗୁଡ଼ିକ
editing-center = କେନ୍ଦ୍ର
editing-change-color = ରଙ୍ଗ ପରିବର୍ତ୍ତନ କର
editing-cloze-deletion = କ୍ଲୋଜ୍ ବିଲୋପ
editing-couldnt-record-audio-have-you-installed = ଅଡ଼ିଓ ରେକର୍ଡ଼ କରାଯାଇ ପାରିଲା ନାହିଁ। ଆପଣ 'lame' ସଂସ୍ଥାପନ କରିଛନ୍ତି କି?
editing-customize-card-templates = ପତ୍ର ଟେମ୍ପଲେଟ୍ କଷ୍ଟମାଇଜ୍ କର
editing-customize-fields = କ୍ଷେତ୍ରଗୁଡ଼ିକୁ କଷ୍ଟମାଇଜ୍ କରନ୍ତୁ
editing-double-click-image = ପ୍ରତିଛବିକୁ ଦୁଇଥର-କ୍ଲିକ୍ କର
editing-edit-html = HTML ସମ୍ପାଦନା
editing-fields = କ୍ଷେତ୍ରଗୁଡ଼ିକ
editing-jump-to-tags-with-ctrlandshiftandt = Ctrl+Shift+T ସହ ଟ୍ୟାଗକୁ ଯାଅ
editing-justify = ଯର୍ଥାଥତା
editing-latex = LaTeX
editing-latex-equation = LaTeX ସମୀକରଣ
editing-latex-math-env = LaTeX ଗଣିତ ପରିବେଶ
editing-mathjax-chemistry = MathJax ରସାୟନବିଜ୍ଞାନ
editing-media = ମିଡ଼ିଆ
editing-record-audio = ଅଡ଼ିଓ ରେକର୍ଡ କର
editing-remove-formatting = ଫର୍ମାଟିଂ ଅପସାରଣ କର
editing-show-duplicates = ନକଲ ଦେଖାନ୍ତୁ
editing-subscript = ପାଦାଙ୍କ
editing-superscript = ଉର୍ଦ୍ଧଲିପି
editing-tags = ଟ୍ୟାଗ୍‌ଗୁଡ଼ିକ
editing-text-color = ପାଠ୍ୟର ରଙ୍ଗ
editing-toggle-html-editor = HTML ସମ୍ପାଦକ ଟୋଗଲ୍ କରିବା
editing-toggle-sticky = Sticky ଟୋଗଲ୍ କରନ୍ତୁ
editing-expand = ପ୍ରସାରଣ
editing-collapse = ସଙ୍କୋଚନ
editing-expand-field = କ୍ଷେତ୍ର ପ୍ରସାରଣ
editing-collapse-field = କ୍ଷେତ୍ର ସଙ୍କୋଚନ
editing-mathjax-preview = MathJax ପୂର୍ଵାଵଲୋକନ
editing-image-occlusion-mode = ପ୍ରତିଛବି ଅନ୍ତର୍ଦ୍ଧାନ ଧାରା
editing-image-occlusion-alignment = ଶ୍ରେଣୀବଦ୍ଧକରଣ
editing-image-occlusion-align-left = ବାମକୁ ଶ୍ରେଣୀବଦ୍ଧ କର
editing-image-occlusion-align-right = ଡାହାଣକୁ ଶ୍ରେଣୀବଦ୍ଧ କର
editing-image-occlusion-rectangle-tool = ଆୟତ କ୍ଷେତ୍ର
editing-image-occlusion-ellipse-tool = ଉପବୃତ୍ତ
editing-image-occlusion-polygon-tool = ବହୁଭୂଜ
editing-image-occlusion-text-tool = ପାଠ୍ୟ
editing-image-occlusion-toggle-mask-editor = ଆବେଷ୍ଟନ ସମ୍ପାଦକ ଟୋଗଲ୍ କରିବା

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML ସମ୍ପାଦକ
