preferences-automatically-sync-on-profile-openclose = ପ୍ରୋଫାଇଲ୍ ଖୋଲା/ବନ୍ଦ ରେ ସ୍ୱତଃସ୍ପୃତ ଭାବେ ସିଙ୍କ୍ କରନ୍ତୁ
preferences-backups = ବ୍ୟାକଅପ୍
preferences-backups2 = ବ୍ୟାକଅପଗୁଡ଼ିକ
preferences-backupsanki-will-create-a-backup-of = <html><head/><body><p><span style=" font-weight:600;">ବ୍ୟାକଅପଗୁଡ଼ିକ</span><br/>ପ୍ରତ୍ୟେକ ଥର ବନ୍ଦ ହେବାବେଳେ Anki ଆପଣଙ୍କ ସଂଗ୍ରହର ଏକ ବ୍ୟାକଅପ୍ ସୃଷ୍ଟି କରିବ।</p></body></html>
preferences-basic = ମୌଳିକ
preferences-change-deck-depending-on-note-type = ନୋଟ୍ ପ୍ରକାର ଉପରେ ନିର୍ଭର କରି ଡେକ୍ ପରିବର୍ତ୍ତନ କରନ୍ତୁ
preferences-changes-will-take-effect-when-you = ଆପଣ Anki ପୁନଃଆରମ୍ଭ କରିବା ସମୟରେ ପରିବର୍ତ୍ତନଗୁଡ଼ିକ କାର୍ଯ୍ୟକାରୀ ହେବ।
preferences-hours-past-midnight = ମଧ୍ୟରାତ୍ରିର ଏତିକି ଘଣ୍ଟା ପରେ
preferences-interface-language = ଇଣ୍ଟରଫେସ୍ ଭାଷା:
preferences-interrupt-current-audio-when-answering = ଉତ୍ତର ଦେବାବେଳେ ସାମ୍ପ୍ରତିକ ଅଡିଓକୁ ବାଧା ଦିଅ
preferences-keep = ରଖନ୍ତୁ
preferences-learn-ahead-limit = ଆଗୁଆ ଶିଖିବା ସମୟସୀମା
preferences-mins = ମିନିଟ୍
preferences-network = ନେଟୱର୍କ
preferences-next-day-starts-at = ପରବର୍ତ୍ତୀ ଦିନ ଆରମ୍ଭ ହୁଏ
preferences-night-mode = ରାତ୍ରି ମୋଡ୍
preferences-note-media-is-not-backed-up = ଟିପ୍ପଣୀ: ମିଡ଼ିଆ ବ୍ୟାକଅପ୍ ହୋଇନାହିଁ। ସୁରକ୍ଷିତ ରହିବାକୁ ଦୟାକରି ଆପଣଙ୍କ Anki ଫୋଲ୍ଡରର ଏକ ପର୍ଯ୍ୟାୟବ୍ୟାକଅପ୍ ସୃଷ୍ଟି କରନ୍ତୁ।
preferences-on-next-sync-force-changes-in = ପରବର୍ତ୍ତୀ ସିଙ୍କ୍ ରେ, ଗୋଟିଏ ଦିଗରେ ପରିବର୍ତ୍ତନକୁ ବାଧ୍ୟ କରନ୍ତୁ
preferences-paste-clipboard-images-as-png = PNG ଭାବରେ କ୍ଲିପବୋର୍ଡ ପ୍ରତିଛବିଗୁଡ଼ିକୁ ଲଗାନ୍ତୁ
preferences-periodically-sync-media = ସମୟସମୟରେ ମିଡିଆକୁ ସିଙ୍କ୍ କରନ୍ତୁ
preferences-please-restart-anki-to-complete-language = ଭାଷା ପରିବର୍ତ୍ତନ ସମ୍ପୂର୍ଣ୍ଣ କରିବା ପାଇଁ ଦୟାକରି Anki ପୁନଃଆରମ୍ଭ କରନ୍ତୁ।
preferences-preferences = ଅଗ୍ରାଧିକାରସମୂହ
preferences-show-next-review-time-above-answer = ଉତ୍ତର ବଟନ୍ ଉପରେ ପରବର୍ତ୍ତୀ ସମୀକ୍ଷା ସମୟ ଦେଖାନ୍ତୁ
preferences-show-play-buttons-on-cards-with = ଅଡ଼ିଓ ଗଚ୍ଛିତ ପତ୍ରରେ ପ୍ଲେ ବଟନ୍ ଦେଖାନ୍ତୁ
preferences-show-remaining-card-count-during-review = ସମୀକ୍ଷା ସମୟରେ ଅବଶିଷ୍ଟ ପତ୍ର ଗଣନା ଦେଖାନ୍ତୁ
preferences-some-settings-will-take-effect-after = ଆପଣ Anki ପୁନଃଆରମ୍ଭ କରିବା ପରେ କିଛି ସେଟିଂସ୍ କାର୍ଯ୍ୟକାରୀ ହେବ।
preferences-synchronisation = <b>ସିଙ୍କ୍ରୋନାଇଜେସନ୍</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>ସିଙ୍କ୍ରୋନାଇଜେସନ୍</b><br> ବର୍ତ୍ତମାନ ସକ୍ଷମ ହୋଇନାହିଁ; ସକ୍ଷମ କରିବାକୁ ମୁଖ୍ୟ ୱିଣ୍ଡୋରେ ସିଙ୍କ୍ ବଟନ୍ କ୍ଲିକ୍ କରନ୍ତୁ।
preferences-synchronize-audio-and-images-too = ଅଡ଼ିଓ ଏବଂ ପ୍ରତିଛବିଗୁଡ଼ିକୁ ମଧ୍ୟ ସିଙ୍କ୍ରୋନାଇଜ୍ କରନ୍ତୁ
preferences-timebox-time-limit = ଟାଇମ୍ ବକ୍ସ ସମୟ ସୀମା
preferences-user-interface-size = ଉପଭୋକ୍ତା ଇଣ୍ଟରଫେସ୍ ଆକାର
preferences-legacy-timezone-handling = ପୁରୁଣା ସମୟ କ୍ଷେତ୍ର ପରିଚାଳନା (ତୃଟିପୂର୍ଣ୍ଣ ଅଟେ, କିନ୍ତୁ AnkiDroid <= 2.14 ପାଇଁ ଆବଶ୍ୟକ)
preferences-default-search-text = ଡିଫଲ୍ଟ ସନ୍ଧାନ ପାଠ୍ୟ
preferences-default-search-text-example = ଯଥା: 'deck:current '
preferences-theme-label = ଥିମ୍: { $theme }
preferences-theme-follow-system = ସିଷ୍ଟମ୍ କୁ ଅନୁସରଣ କରିବା
preferences-theme-light = ହାଲୁକା
preferences-theme-dark = ଗାଢ଼
preferences-theme = ଥିମ୍
