editing-actual-size = Bật/tắt hiển thị kích thước thực
editing-add-media = Thêm dữ liệu Phương tiện
editing-align-left = Căn lề trái
editing-align-right = Căn lề phải
editing-an-error-occurred-while-opening = Có lỗi xảy ra khi mở { $val }
editing-attach-picturesaudiovideo = Đính kèm hình ảnh/âm thanh/video
editing-bold-text = In đậm
editing-cards = Thẻ
editing-center = Căn giữa
editing-change-color = Đổi màu
editing-cloze-deletion = Xóa khoảng điền
editing-cloze-deletion-repeat = Xóa điền chỗ trống (cùng thẻ)
editing-copy-image = Sao chép hình ảnh
editing-couldnt-record-audio-have-you-installed = Không thể ghi âm. Bạn đã cài đặt 'lame' chưa?
editing-customize-card-templates = Tùy chỉnh mẫu thẻ
editing-customize-fields = Tùy chỉnh Trường
editing-cut = Cắt
editing-double-click-image = ân đôi hình ảnh
editing-double-click-to-expand = ấn đôi để mở rộng
editing-double-click-to-collapse = ấn đôi để thu gọn
editing-edit-current = Sửa Ghi chú Hiện hành
editing-edit-html = Sửa HTML
editing-fields = Trường tin
editing-float-left = Nổi bên trái
editing-float-right = Nổi bên phải
editing-float-none = Không nổi lên
editing-indent = Tăng thụt lề
editing-italic-text = In nghiêng
editing-jump-to-tags-with-ctrlandshiftandt = Nhảy đến nhãn với Ctrl+Shift+T
editing-justify = Căn đều
editing-latex = LaTeX
editing-latex-equation = Phương trình LaTeX
editing-latex-math-env = Môi trường toán LaTeX
editing-mathjax-block = MathJax ô trống
editing-mathjax-chemistry = MathJax hóa học
editing-mathjax-inline = MathJax nội tuyến
editing-mathjax-placeholder = Nhấn { $accept } để chấp nhận, { $newline } cho dòng mới.
editing-media = Phương tiện
editing-open-image = Mở hình ảnh
editing-show-in-folder = Hiển thị trong thư mục
editing-ordered-list = Danh sách có thứ tự
editing-outdent = Giảm thụt lề
editing-paste = Dán
editing-record-audio = Ghi âm
editing-remove-formatting = Xóa định dạng
editing-restore-original-size = Khôi phục kích thước ban đầu
editing-select-remove-formatting = Chọn định dạng để xóa
editing-show-duplicates = Hiện Thẻ trùng
editing-subscript = Chỉ số dưới
editing-superscript = Chỉ số trên
editing-tags = Nhãn
editing-tags-add = Thêm nhãn
editing-tags-copy = Sao chép nhãn
editing-tags-remove = Xóa nhãn
editing-tags-select-all = Chọn tất cả các nhãn
editing-text-color = Màu văn bản
editing-text-highlight-color = Màu văn bản dạ quang
editing-to-make-a-cloze-deletion-on = Để tạo chỗ điền trống trong phiếu hiện có, trước tiên cần chuyển nó sang kiểu phiếu điền chỗ trống, bằng cách chọn Chỉnh sửa>Đổi Kiểu Phiếu.
editing-toggle-html-editor = Bật tắt Trình soạn thảo HTML
editing-toggle-visual-editor = Bật tắt Trình soạn thảo Trực quan
editing-toggle-sticky = Bật/tắt tính năng giữ lại những lần tìm kiếm
editing-expand = Mở rộng
editing-collapse = Thu gọn
editing-expand-field = Mở rộng trường tin
editing-collapse-field = Thu gọn trường tin
editing-underline-text = Gạch chân văn bản
editing-unordered-list = Danh sách không có thứ tự
editing-warning-cloze-deletions-will-not-work = Cảnh báo, nút tạo chỗ trống sẽ không hoạt động được cho đến khi bạn chuyển kiểu phiếu ở trên cùng sang kiểu Điền chỗ trống.
editing-mathjax-preview = Xem trước MathJax
editing-shrink-images = Co hình ảnh lại
editing-close-html-tags = Tự động đóng thẻ HTML
editing-from-clipboard = Từ Bộ nhớ tạm
editing-alignment = Căn chỉnh
editing-equations = Công thức
editing-no-image-found-on-clipboard = Không tìm thấy ảnh trong bộ nhớ tạm.
editing-image-occlusion-mode = Chế độ Che khuất Hình ảnh
editing-image-occlusion-zoom-out = Thu nhỏ
editing-image-occlusion-zoom-in = Phóng to
editing-image-occlusion-zoom-reset = Đặt lại độ phóng
editing-image-occlusion-toggle-translucent = Bật tắt Độ trong mờ
editing-image-occlusion-delete = Xóa
editing-image-occlusion-duplicate = Sao chép
editing-image-occlusion-group = Kết hợp Lựa chọn
editing-image-occlusion-ungroup = Tách Lựa chọn
editing-image-occlusion-select-all = Chọn tất cả
editing-image-occlusion-alignment = Căn chỉnh
editing-image-occlusion-align-left = Căn trái
editing-image-occlusion-align-h-center = Căn ngang giữa
editing-image-occlusion-align-right = Căn phải
editing-image-occlusion-align-top = Căn trên
editing-image-occlusion-align-v-center = Căn dọc giữa
editing-image-occlusion-align-bottom = Căn dưới
editing-image-occlusion-select-tool = Chọn
editing-image-occlusion-zoom-tool = Phóng to
editing-image-occlusion-rectangle-tool = Hình chữ nhật
editing-image-occlusion-ellipse-tool = Hình bầu dục
editing-image-occlusion-polygon-tool = Hình đa giác
editing-image-occlusion-text-tool = Văn bản
editing-image-occlusion-fill-tool = Tô màu
editing-image-occlusion-toggle-mask-editor = Bật tắt Trình soạn thảo Mặt nạ
editing-image-occlusion-reset = Đặt lại Che khuất Hình ảnh
editing-image-occlusion-confirm-reset = Bạn có chắc là mình muốn đặt lại che khuất hình ảnh không?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Trình soạn thảo HTML
