profiles-anki-could-not-read-your-profile = Anki không thể đọc dữ liệu hồ sơ của bạn. Kích thước cửa sổ và chi tiết đăng nhập đồng bộ của bạn đã bị quên.
profiles-anki-could-not-rename-your-profile = Anki không đổi tên hồ sơ của bạn được vì không thể đổi tên thư mục hồ sơ trên đĩa. Vui lòng bảo đảm rằng bạn có quyền ghi vào Documents/Anki và không có chương trình nào khác truy cập thư mục hồ sơ của bạn, rồi thử lại.
profiles-folder-already-exists = Thư mục đã tồn tại.
profiles-open = Mở
profiles-open-backup = Mở Bản sao lưu...
profiles-please-remove-the-folder-and = Vui lòng bỏ thư mục { $val } và thử lại.
profiles-profile-corrupt = Hồ sơ bị hỏng
profiles-profiles = Hồ sơ
profiles-quit = Thoát
profiles-user-1 = Người dùng 1
profiles-confirm-lang-choice = Bạn có chắc chắn muốn hiển thị giao diện của Anki trong { $lang }?
profiles-could-not-create-data-folder = Anki không thể tạo thư mục dữ liệu của nó. Vui lòng xem phần Vị trí tệp của sách hướng dẫn, và đảm bảo rằng vị trí không ở chế độ chỉ-đọc.
profiles-prefs-corrupt-title = Tùy chỉnh bị hỏng
profiles-prefs-file-is-corrupt = Tệp prefs21.db của Anki đã bị hỏng và đã được tạo lại. Nếu bạn đang sử dụng nhiều cấu hình, vui lòng thêm lại chúng bằng các tên giống nhau để khôi phục thẻ của bạn.
profiles-profile-does-not-exist = Hồ sơ được yêu cầu không tồn tại.
profiles-creating-backup = Tạo bản sao lưu...
profiles-backup-created = Đã tạo bản sao lưu.
profiles-backup-creation-failed = Tạo bản sao lưu không thành công: { $reason }
profiles-backup-unchanged = Không có thay đổi sau bản sao cuối cùng.
