# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: build-on-linux

concurrency: 
  group: "${{ github.head_ref || github.run_id }}-build-on-linux"
  cancel-in-progress: true

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ ]
#    paths:
#    - .github/workflows/build-on-ubuntu.yml
#  pull_request:
#    branches: [ main ]
  workflow_call:
     inputs:
        buildArgs:
          description: 'buildArgs ie: --test_verbose_timeout_warnings'
          required: false
          type: string
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     inputs:
          buildArgs:
            description: 'buildArgs ie: --test_verbose_timeout_warnings'
            required: false
            default: ''

# https://github.com/actions/virtual-environments
jobs:
  build:
#    runs-on: ubuntu-20.04
    runs-on: ubuntu-latest
#    runs-on: ubuntu-18.04
#    runs-on: windows-latest
#    runs-on: macos-latest
#    runs-on: macos-10.15
    steps:
    - name: cancel previous runs
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: build
 #     shell: sh
      env:
        RUST_BACKTRACE: 1
      run: |
         sudo apt-get update \
            && sudo apt-get install --yes\
            autoconf \
            bash \
            ca-certificates \
            curl \
            findutils \
            g++ \
            gcc \
            git \
            grep \
            libdbus-1-3 \
            libegl1 \
            libfontconfig1 \
            libgl1 \
            libgstreamer-gl1.0-0 \
            libgstreamer-plugins-base1.0 \
            libgstreamer1.0-0 \
            libnss3 \
            libpulse-mainloop-glib0 \
            libpulse-mainloop-glib0 \
            libssl-dev \
            libxcomposite1 \
            libxcursor1 \
            libxi6 \
            libxkbcommon-x11-0 \
            libxkbcommon0 \
            libxkbfile1	\
            libxrandr2 \
            libxrender1 \
            libxtst6 \
            make \
            pkg-config \
            portaudio19-dev \
            python3-dev \
            rsync \
            zstd
            python --version
            python3 --version
            sudo mkdir -p /state/bazel
            sudo chown -R $USER /state
            export BAZEL_VERSION=5.0.0
            sudo curl -fLo /usr/bin/bazel "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-linux-x86_64"
            sudo chmod +x /usr/bin/bazel
            ./.buildkite/linux/entrypoint ${{ github.event.inputs.buildArgs }}
