# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/learn-github-actions/expressions#operators
# https://github.com/actions/virtual-environments
# https://docs.github.com/en/actions/using-workflows/reusing-workflows

name: build-on-all-os

concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
#    paths:
#    - .github/workflows/build-on-macos.yml
    branches: [ 'test4all**', 'build4all**' ]
    paths-ignore:
    - 'README.md'
    - '.gitignore'
    - '.gitmodules'
#  pull_request:
#    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      buildArgs:
        description: 'buildArgs ie: --test_verbose_timeout_warnings'
        required: false
        default: '--verbose_failures'
      cacheOn:
        description: 'cacheOn: change to false for disable.'
        required: false
        default: 'true'
        type: choice
        options:
        - true
        - false
jobs:
  build-on-linux:
    uses: ./.github/workflows/build-on-linux.yml
    with:
      buildArgs: ${{ github.event.inputs.buildArgs }}
      cacheOn: ${{ github.event.inputs.cacheOn }}
  build-on-windows:
    uses: ./.github/workflows/build-on-windows.yml
    with:
      buildArgs: ${{ github.event.inputs.buildArgs }}
      cacheOn: ${{ github.event.inputs.cacheOn }}
  build-on-macos:
    uses: ./.github/workflows/build-on-macos.yml
    with:
      buildArgs: ${{ github.event.inputs.buildArgs }}
      cacheOn: ${{ github.event.inputs.cacheOn }}
