name: Author in CONTRIBUTORS

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: |
          .github/scripts/contrib.sh
