name: Publish PyPI Packages

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup build environment
        uses: ./.github/actions/setup-anki

      - name: Build wheels
        run: |
          ./ninja wheels
          sudo apt-get install --yes --no-install-recommends libc6-dev-arm64-cross gcc-aarch64-linux-gnu
          ./tools/build-arm-lin

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux
          # Upload both anki and aqt wheels from this platform;
          # the pure-Python aqt wheel is the same on all platforms
          path: out/wheels/*.whl
    env:
      RELEASE: 2

  build-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Setup build environment
        uses: ./.github/actions/setup-anki

      - name: Build wheels
        run: |
          ./ninja wheels:anki
          ./tools/build-x64-mac

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos
          path: out/wheels/anki-*.whl
    env:
      RELEASE: 2


  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup build environment
        uses: ./.github/actions/setup-anki

      - name: Build wheels
        run: |
          ./tools/ninja wheels:anki

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-windows
          path: out/wheels/anki-*.whl
    env:
      RELEASE: 2

  publish:
    needs:
      - build-linux
      - build-macos
      - build-windows
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
