[package]
name = "pymod"
version = "0.1.0"
edition = "2018"
authors = ["Ankitects Pty Ltd and contributors"]

[dependencies]
ankirs = { path = "../ankirs" }

[dependencies.pyo3]
version = "0.8.0"
features = ["extension-module"]

[lib]
name = "_ankirs"
crate-type = ["cdylib"]
