qt-accel-about = &Жайлы
qt-accel-about-mac = Anki Жайлы...
qt-accel-cards = &Карталар
qt-accel-check-database = &Дерекқорды Тексеру
qt-accel-check-media = &Медианы Тексеру
qt-accel-edit = &Өңдеу
qt-accel-exit = &Шығу
qt-accel-export = &Экспорт...
qt-accel-export-notes = Жазбаларды &Экспорттау
qt-accel-file = &Файл
qt-accel-filter = &Сүзгі
qt-accel-find = &Табу
qt-accel-find-and-replace = Табу және &Ауыстыру...
qt-accel-find-duplicates = &Телнұсқаларды Табу...
qt-accel-go = Ө&ту
qt-accel-guide = &Нұсқау
qt-accel-help = &Көмек
qt-accel-import = &Импорт
qt-accel-info = &Ақпар...
qt-accel-invert-selection = Таңдауды &Керілеу
qt-accel-next-card = &Келесі Карта
qt-accel-note = &Жазба
qt-accel-notes = &Жазбалар
qt-accel-preferences = &Бапталымдар
qt-accel-previous-card = &Алдыңғы Карта
qt-accel-select-all = Б&әрін Таңдау
qt-accel-select-notes = &Жазбаларды Таңдау
qt-accel-support-anki = Anki-ді &Қолдау
qt-accel-switch-profile = &Бейінді Ауыстыру
qt-accel-tools = &Құралдар
qt-accel-undo = &Болдырмау
qt-accel-redo = &Қайтару
qt-accel-set-due-date = &Мерізім Қою...
qt-accel-forget = &Ысыру
qt-accel-view = Кө&рініс
qt-accel-full-screen = &Толық Бейнебетті Қосу
qt-accel-layout = &Орналасу
qt-accel-layout-auto = &Ауто
qt-accel-layout-vertical = &Тік
qt-accel-layout-horizontal = &Көлденең
qt-accel-zoom-in = &Ірілеу
qt-accel-zoom-out = &Кішілеу
qt-accel-reset-zoom = &Ысыру
qt-accel-toggle-sidebar = Бүйірлік Үстелді Қосу
qt-accel-zoom-editor-in = Өңдегішті Ірілеу
qt-accel-zoom-editor-out = Өңдегішті Кішілеу
qt-accel-create-backup = &Сақтық Көшіру
qt-accel-load-backup = &Қалпына Келтіру
qt-accel-upgrade-downgrade = Нұсқа ауыстыру
