editing-actual-size = Attiva/disattiva dimensione effettiva
editing-add-media = Aggiungi media
editing-align-left = Allinea a sinistra
editing-align-right = Allinea a destra
editing-an-error-occurred-while-opening = Si è verificato un errore durante l'apertura di { $val }
editing-attach-picturesaudiovideo = Allega immagini/audio/video
editing-bold-text = Grassetto
editing-cards = Carte
editing-center = Centro
editing-change-color = Cambia colore
editing-cloze-deletion = Cancellazione cloze (Nuova carta)
editing-cloze-deletion-repeat = Cancellazione cloze (Stessa carta)
editing-copy-image = Copia immagine
editing-couldnt-record-audio-have-you-installed = Non è stato possibile registrare l'audio. Hai installato 'lame'?
editing-customize-card-templates = Personalizza i modelli delle carte
editing-customize-fields = Personalizza i campi
editing-cut = Taglia
editing-double-click-image = doppio clic sull'immagine
editing-double-click-to-expand = doppio clic per espandere
editing-double-click-to-collapse = doppio clic per comprimere
editing-edit-current = Modifica attuale
editing-edit-html = Modifica HTML
editing-fields = Campi
editing-float-left = Ancora a sinistra
editing-float-right = Ancora a destra
editing-float-none = Posizionamento automatico
editing-indent = Aumenta l'indentazione
editing-italic-text = Corsivo
editing-jump-to-tags-with-ctrlandshiftandt = Salta a etichette con Ctrl+Shift+T
editing-justify = Giustificato
editing-latex = LaTeX
editing-latex-equation = Equazione LaTeX
editing-latex-math-env = Ambiente matematico LaTeX
editing-mathjax-block = Blocco MathJax
editing-mathjax-chemistry = MathJax chimica
editing-mathjax-inline = MathJax in linea
editing-mathjax-placeholder = Premi { $accept } per accettare, { $newline } per una nuova riga.
editing-media = File multimediale
editing-open-image = Apri immagine
editing-show-in-folder = Mostra nella cartella
editing-ordered-list = Lista ordinata
editing-outdent = Riduci indentazione
editing-paste = Incolla
editing-record-audio = Registra audio
editing-remove-formatting = Rimuovi formattazione
editing-restore-original-size = Ripristina dimensione originale
editing-select-remove-formatting = Seleziona formattazione da rimuovere
editing-show-duplicates = Mostra i duplicati
editing-subscript = Pedice
editing-superscript = Apice
editing-tags = Etichette
editing-tags-add = Aggiungi etichetta
editing-tags-copy = Copia etichette
editing-tags-remove = Rimuovi etichette
editing-tags-select-all = Seleziona tutte le etichette
editing-text-color = Colore del testo
editing-text-highlight-color = Colore di evidenziazione del testo
editing-to-make-a-cloze-deletion-on = Per inserire una cancellazione cloze in una nota esistente è necessario cambiarla in una nota di tipo cloze, accedendo a "Modifica>Cambia tipo di nota"
editing-toggle-html-editor = Attiva/disattiva editor HTML
editing-toggle-visual-editor = Attiva/disattiva editor visuale
editing-toggle-sticky = Attiva/disattiva ancoraggio del campo
editing-expand = Espandi
editing-collapse = Comprimi
editing-expand-field = Espandi campo
editing-collapse-field = Comprimi campo
editing-underline-text = Sottolinea testo
editing-unordered-list = Lista non ordinata
editing-warning-cloze-deletions-will-not-work = Attenzione, le cancellazioni cloze non funzioneranno fino a quando non cambierai il tipo di nota in Cloze.
editing-mathjax-preview = Anteprima MathJax
editing-shrink-images = Ridimensiona Immagini
editing-close-html-tags = Chiudi automaticamente i tag HTML
editing-from-clipboard = Da Appunti
editing-alignment = Allineamento
editing-equations = Equazioni
editing-no-image-found-on-clipboard = Nessuna immagine trovata nella clipboard.
editing-image-occlusion-mode = Modalità Occludi Immagine
editing-image-occlusion-zoom-out = Riduci Zoom
editing-image-occlusion-zoom-in = Aumenta Zoom
editing-image-occlusion-zoom-reset = Ripristina Zoom
editing-image-occlusion-toggle-translucent = Attiva/disattiva trasparenza
editing-image-occlusion-delete = Elimina
editing-image-occlusion-duplicate = Duplica
editing-image-occlusion-group = Raggruppa selezione
editing-image-occlusion-ungroup = Rimuovi raggruppamento
editing-image-occlusion-select-all = Seleziona tutto
editing-image-occlusion-alignment = Allineamento
editing-image-occlusion-align-left = Allinea a sinistra
editing-image-occlusion-align-h-center = Centra orizzontalmente
editing-image-occlusion-align-right = Allinea a destra
editing-image-occlusion-align-top = Allinea in alto
editing-image-occlusion-align-v-center = Centra verticalmente
editing-image-occlusion-align-bottom = Allinea in basso
editing-image-occlusion-select-tool = Seleziona
editing-image-occlusion-zoom-tool = Zoom
editing-image-occlusion-rectangle-tool = Rettangolo
editing-image-occlusion-ellipse-tool = Ellisse
editing-image-occlusion-polygon-tool = Poligono
editing-image-occlusion-text-tool = Testo
editing-image-occlusion-fill-tool = Riempi con il colore
editing-image-occlusion-toggle-mask-editor = Attiva/disattiva editor delle maschere
editing-image-occlusion-reset = Ripristina Occludi Immagine
editing-image-occlusion-confirm-reset = Confermi di voler resettare questa occlusione dell'immagine?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Editor HTML
