card-stats-added = Додано
card-stats-first-review = Вперше повторена
card-stats-latest-review = Останнє повторення
card-stats-interval = Інтервал
card-stats-ease = Легкість
card-stats-review-count = Повторень
card-stats-lapse-count = Невдачі
card-stats-average-time = Середній час
card-stats-total-time = Загальний час
card-stats-new-card-position = Позиція
card-stats-card-template = Тип картки
card-stats-note-type = Тип нотаток
card-stats-deck-name = Колода
card-stats-preset = Конфігурація
card-stats-note-id = Індекс нотатки
card-stats-card-id = Індекс картки
card-stats-review-log-rating = Рейтинг
card-stats-review-log-type = Тип
card-stats-review-log-date = Дата
card-stats-review-log-time-taken = Час
card-stats-review-log-type-learn = Вчити
card-stats-review-log-type-review = Пригадувальні
card-stats-review-log-type-relearn = Вчити знову
card-stats-review-log-type-filtered = Відфільтровані
card-stats-review-log-type-manual = Посібник
card-stats-review-log-type-rescheduled = Переплановано
card-stats-review-log-elapsed-time = Затрачено часу
card-stats-no-card = (Нема карток для показу.)
card-stats-custom-data = Спеціальні дані
card-stats-fsrs-stability = Стабільність
card-stats-fsrs-difficulty = Складність
card-stats-fsrs-retrievability = легкість пригадування
card-stats-fsrs-forgetting-curve-title = Крива забування
card-stats-fsrs-forgetting-curve-first-week = Перший тиждень
card-stats-fsrs-forgetting-curve-first-month = Перший місяць
card-stats-fsrs-forgetting-curve-first-year = Перший рік
card-stats-fsrs-forgetting-curve-all-time = За весь час
card-stats-fsrs-forgetting-curve-probability-of-recalling = Ймовірність нагадування
card-stats-fsrs-forgetting-curve-desired-retention = Бажана затримка

## Window Titles

card-stats-current-card = Поточна картка ({ $context })
card-stats-previous-card = Минула картка ({ $context })
