profiles-anki-could-not-read-your-profile = Anki не може прочитати дані Вашого профілю. Розміри вікна та Ваші дані для входу для синхронізації загублено.
profiles-anki-could-not-rename-your-profile = Anki не вдалося перейменувати ваш профіль, оскільки не вдалося перейменувати теку профілю на диску. Переконайтеся, що у вас є дозвіл на запис до теки Документи/Anki і що інші програми не мають доступ до тек ваших профілів і спробуйте знову.
profiles-folder-already-exists = Тека вже існує.
profiles-open = Відкрити
profiles-open-backup = Відкривання резервної копії…
profiles-please-remove-the-folder-and = Будь ласка, видаліть теку { $val } і повторіть спробу.
profiles-profile-corrupt = Профіль пошкоджено.
profiles-profiles = Профілі
profiles-quit = Вийти
profiles-user-1 = Користувач 1
profiles-confirm-lang-choice = Ви справді хочете змінити мову Anki на { $lang }?
profiles-could-not-create-data-folder = Anki не може створити цю теку. Будь ласка, перегляньте «Розташування файлів» в довіднику і переконайтесь що для цієї теки є дозвіл на запис.
profiles-prefs-corrupt-title = Налаштування пошкоджені
profiles-prefs-file-is-corrupt = Пошкоджений файл Anki prefs21.db повторно створено. Якщо Ви використовуєте декілька профілів, будь ласка, додайте їх повторно використовуючи такі ж назви для відновлення Ваших карток.
profiles-profile-does-not-exist = Запитаного профілю не існує.
profiles-creating-backup = Створення резервної копії…
profiles-backup-created = Резервну копію створено.
profiles-backup-creation-failed = Не вдалося створити резервну копію: { $reason }
profiles-backup-unchanged = Без змін від останньої резервної копії.
